Readme.md

https://bugzilla.tianocore.org/show_bug.cgi?id=2315
Update Readme.md with the status badges from the Azure
Pipelines, tianocore organization, edk2-ci project
https://dev.azure.com/tianocore/edk2-ci/_build
* Windows VS2019 CI pipeline badges and results
* Ubuntu GCC5 CI pipeline badges and results

Readme.md: Update EDK II CI build status badge and links

---

MdeModulePkg/Library/BrotliCustomDecompressLib/brotli/types.h
MdeModulePkg/Library/LzmaCustomDecompressLib/UefiLzma.h

REF:https://bugzilla.tianocore.org/show_bug.cgi?id=2338

MdeModulePkg: Unify the definitions of size_t

---

MdePkg/Include/Library/UefiLib.h
MdePkg/Library/UefiLib/UefiLib.c

Keep the comment style of IsLanguageSupported align with
other functions.

MdePkg: Update the comments of IsLanguageSupported

---

MdeModulePkg/Universal/Variable/RuntimeDxe/VariableParsing.c
MdeModulePkg/Universal/Variable/RuntimeDxe/VariableSmmRuntimeDxe.c

REF:https://bugzilla.tianocore.org/show_bug.cgi?id=2364

MdeModulePkg/Variable: Initialize local variable "Variable"

---

NetworkPkg/Dhcp6Dxe/Dhcp6Io.c
NetworkPkg/Ip4Dxe/Ip4If.c
NetworkPkg/TcpDxe/TcpDispatcher.c

Introducing fixes to memory leak issues identified by static code analysis
tool.

NetworkPkg: Fixes to static code analysis hits

---

MdeModulePkg/MdeModulePkg.uni
NetworkPkg/NetworkPkg.uni
UefiCpuPkg/UefiCpuPkg.uni

Add the missing UNI string for PCD

Add the missing UNI string for PCD

---

UefiCpuPkg/Library/MpInitLib/MpLib.c
UefiCpuPkg/PiSmmCpuDxeSmm/Ia32/PageTbl.c
UefiCpuPkg/PiSmmCpuDxeSmm/PiSmmCpuDxeSmm.h
UefiCpuPkg/PiSmmCpuDxeSmm/X64/PageTbl.c

In MpLib.c, remove the white space on a new line.
In PageTbl.c and PiSmmCpuDxeSmm.h, update the comment style.

UefiCpuPkg: Update the coding styles

---

MdeModulePkg/Library/LzmaCustomDecompressLib/LzmaCustomDecompressLib.inf
MdeModulePkg/MdeModulePkg.dsc

Fix EBC Build Failure in MdeModulePkg

Fix EBC Build Failure in MdeModulePkg

---

IntelFsp2WrapperPkg/FspsWrapperPeim/FspsWrapperPeim.c
IntelFsp2WrapperPkg/Include/Library/FspWrapperApiLib.h
IntelFsp2WrapperPkg/Include/Library/FspWrapperPlatformLib.h
IntelFsp2WrapperPkg/Library/BaseFspWrapperApiLib/X64/Thunk64To32.nasm
IntelFsp2WrapperPkg/Library/BaseFspWrapperPlatformLibSample/FspWrapperPlatformLibSample.c
IntelFsp2WrapperPkg/Library/PeiFspWrapperHobProcessLibSample/FspWrapperHobProcessLibSample.c
IntelFsp2WrapperPkg/Library/SecFspWrapperPlatformSecLibSample/Ia32/SecEntry.nasm
IntelFsp2WrapperPkg/Library/SecFspWrapperPlatformSecLibSample/Ia32/Stack.nasm

Fix various typos in comments and documentation.
Signed-off-by: Philippe Mathieu-Daude <philmd@redhat.com>

IntelFsp2WrapperPkg: Fix various typos

---

BaseTools/Scripts/PatchCheck.py

https://bugzilla.tianocore.org/show_bug.cgi?id=2406
* Always print subject line after the git commit id to make
it easier to know the context of warnings or errors.
* Allow UTF-8 characters in subject line
* Error if subject line length > 75 without CVE-xxx-xxxxx present
* Error if subject line length > 92 with CVE-xxxx-xxxxx present
* If body line length is > 75, then print warning instead of error.
Tested-by: Laszlo Ersek <lersek@redhat.com>

BaseTools/Scripts/PatchCheck: Address false error conditions

---

MdeModulePkg/Library/UefiBootManagerLib/BmBoot.c
NetworkPkg/HttpDxe/HttpImpl.c

This series aims to improve HTTP(S) Boot experience with large (4GiB+) files.
https://edk2.groups.io/g/devel/message/53034
http://mid.mail-archive.com/20200108234313.28510-1-lersek@redhat.com

[PATCH 0/2] UefiBootManagerLib, HttpDxe: tweaks for large HTTP(S) downloads

---

UefiCpuPkg/PiSmmCpuDxeSmm/SmmProfile.c

review thread:
https://edk2.groups.io/g/devel/message/53098
http://mid.mail-archive.com/20200109232512.11022-1-lersek@redhat.com

[edk2-devel] [PATCH] UefiCpuPkg/PiSmmCpuDxeSmm: fix 2M->4K page splitting regression for PDEs -- push

---

BaseTools/Scripts/PatchCheck.py

https://bugzilla.tianocore.org/show_bug.cgi?id=2484
https://bugzilla.tianocore.org/show_bug.cgi?id=2485
Update PatchCheck to not enforce no tabs and not enforce CR/LF
line endings for .gitmodules files.  These files are updated by
git when a git submodule command is used and the updates by git
use tab characters and LF line endings.
Also update patch check to not enforce CR/LF line endings for
patch lines that create a submodule directory.  These patch
lines use LF line endings.  The git submodule directory is
added as a new file with attributes 160000 that can be detected
by looking for the pattern "new file mode 160000".
Signed-off-by: Michael D Kinney …

BaseTools/Scripts/PatchCheck.py: Remove submodule false positives

---

OvmfPkg/Include/IndustryStandard/I440FxPiix4.h
OvmfPkg/Include/IndustryStandard/Q35MchIch9.h
OvmfPkg/Include/IndustryStandard/QemuCpuHotplug.h
OvmfPkg/OvmfPkgIa32.dsc
OvmfPkg/OvmfPkgIa32X64.dsc
OvmfPkg/OvmfPkgX64.dsc
OvmfPkg/OvmfXen.dsc
OvmfPkg/PlatformPei/Platform.c
OvmfPkg/PlatformPei/PlatformPei.inf

https://bugzilla.tianocore.org/show_bug.cgi?id=1515
https://edk2.groups.io/g/devel/message/49364
http://mid.mail-archive.com/20191022221554.14963-1-lersek@redhat.com

[edk2-devel] [PATCH v2 0/3] OvmfPkg: distinguish boot CPU count from possible CPU count -- push

---

BaseTools/Conf/gitattributes

https://edk2.groups.io/g/devel/message/53398
http://mid.mail-archive.com/20200120094245.9010-1-lersek@redhat.com

[edk2-devel] [PATCH v2] BaseTools/Conf/gitattributes: fix "--function-context" for C source code -- push

---

OvmfPkg/Include/IndustryStandard/Q35MchIch9.h
OvmfPkg/Library/SmmCpuFeaturesLib/SmmCpuFeaturesLib.c
OvmfPkg/Library/SmmCpuFeaturesLib/SmmCpuFeaturesLib.inf
OvmfPkg/OvmfPkg.dec
OvmfPkg/OvmfPkgIa32.dsc
OvmfPkg/OvmfPkgIa32X64.dsc
OvmfPkg/OvmfPkgX64.dsc
OvmfPkg/OvmfXen.dsc
OvmfPkg/PlatformPei/AmdSev.c
OvmfPkg/PlatformPei/MemDetect.c
OvmfPkg/PlatformPei/Platform.c
OvmfPkg/PlatformPei/Platform.h
OvmfPkg/PlatformPei/PlatformPei.inf
OvmfPkg/SmmAccess/SmmAccess2Dxe.c
OvmfPkg/SmmAccess/SmmAccess2Dxe.inf
OvmfPkg/SmmAccess/SmmAccessPei.c
OvmfPkg/SmmAccess/SmmAccessPei.inf
OvmfPkg/SmmAccess/SmramInternal.c
OvmfPkg/SmmAccess/SmramInternal.h

https://bugzilla.tianocore.org/show_bug.cgi?id=1512
http://mid.mail-archive.com/20200129214412.2361-1-lersek@redhat.com
https://edk2.groups.io/g/devel/message/53545

[edk2-devel] [PATCH v2 00/11] support QEMU's "SMRAM at default SMBASE" feature -- push

---

BaseTools/Conf/tools_def.template
MdePkg/Include/Base.h

https://bugzilla.tianocore.org/show_bug.cgi?id=2415

Fix CLANG38 Build Failure

---

FmpDevicePkg/FmpDxe/Dependency.c
FmpDevicePkg/FmpDxe/Dependency.h
FmpDevicePkg/FmpDxe/FmpDxe.c
MdeModulePkg/Bus/Pci/PciBusDxe/PciEnumeratorSupport.c
MdeModulePkg/Bus/Pci/SdMmcPciHcDxe/SdMmcPciHci.c
MdeModulePkg/MdeModulePkg.uni
SecurityPkg/Tcg/Tcg2Dxe/Tcg2Dxe.c
SecurityPkg/Tcg/Tcg2Pei/Tcg2Pei.c

BZ https://bugzilla.tianocore.org/show_bug.cgi?id=2515

Issues reported by ECC in edk2

---

Maintainers.txt

Change Jiaxin Wu from Maintainer to Reviewer.

Maintainers.txt: Change NetworkPkg maintainer role.

---

ShellPkg/Library/UefiShellAcpiViewCommandLib/AcpiParser.c
ShellPkg/Library/UefiShellAcpiViewCommandLib/AcpiParser.h
ShellPkg/Library/UefiShellAcpiViewCommandLib/AcpiTableParser.c

ShellPkg: acpiview: Remove duplicate ACPI structure size definitions
ShellPkg: acpiview: Validate ACPI table 'Length' field

Apci view update

---

NetworkPkg/Ip4Dxe/Ip4Input.c

v3: correct the coding style.
v2: correct the commit message & add BZ number.
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=1610
This patch is to check the received package length to make sure the package
has a valid length field.
Cc: Fu Siyuan <siyuan.fu@intel.com>
Signed-off-by: Wu Jiaxin <jiaxin.wu@intel.com>

NetworkPkg/Ip4Dxe: Check the received package length (CVE-2019-14559).

---

ArmPkg/Library/ArmMmuLib/AArch64/ArmMmuLibCore.c

[edk2-devel] [PATCH v4 0/2] ArmPkg/ArmMmuLib: rewrite and improve cache handling with MMU off
https://edk2.groups.io/g/devel/message/55635
msgid `<20200307083849.8940-1-ard.biesheuvel@linaro.org>`
[edk2-devel] [PATCH 0/2] ArmPkg/ArmMmuLib AARCH64: final cleanups
https://edk2.groups.io/g/devel/message/55638
msgid `<20200307091008.14918-1-ard.biesheuvel@linaro.org>`

Aarch64 mmulib apply 2

---

OvmfPkg/OvmfPkgIa32.fdf
OvmfPkg/OvmfPkgIa32X64.fdf
OvmfPkg/OvmfPkgX64.fdf

http://mid.mail-archive.com/20200310175025.18849-1-lersek@redhat.com
https://edk2.groups.io/g/devel/message/55717
https://bugzilla.tianocore.org/show_bug.cgi?id=2585

[edk2-devel] [PATCH] OvmfPkg: raise DXEFV size to 12 MB -- push

---

UefiCpuPkg/Library/MpInitLib/DxeMpLib.c
UefiCpuPkg/Library/MpInitLib/MpLib.h
UefiCpuPkg/Library/MpInitLib/PeiMpLib.c

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2553
The comment haven't indicate the output attribute.

UefiCpuPkg/MpInitLib: Add out attribute for parameter.

---

OvmfPkg/Include/IndustryStandard/PvScsi.h
OvmfPkg/OvmfPkg.dec
OvmfPkg/OvmfPkgIa32.dsc
OvmfPkg/OvmfPkgIa32.fdf
OvmfPkg/OvmfPkgIa32X64.dsc
OvmfPkg/OvmfPkgIa32X64.fdf
OvmfPkg/OvmfPkgX64.dsc
OvmfPkg/OvmfPkgX64.fdf
OvmfPkg/PvScsiDxe/PvScsi.c
OvmfPkg/PvScsiDxe/PvScsi.h
OvmfPkg/PvScsiDxe/PvScsiDxe.inf

https://bugzilla.tianocore.org/show_bug.cgi?id=2567
https://edk2.groups.io/g/devel/message/56533
http://mid.mail-archive.com/20200328200100.60786-1-liran.alon@oracle.com

[edk2-devel] [PATCH v3 00/17] OvmfPkg: Support booting from VMware PVSCSI controller -- push

---

.pytool/Plugin/SpellCheck/cspell.base.yaml
CryptoPkg/CryptoPkg.dsc
CryptoPkg/Library/BaseCryptLib/BaseCryptLib.inf
CryptoPkg/Library/BaseCryptLib/RuntimeCryptLib.inf
CryptoPkg/Library/BaseCryptLibNull/BaseCryptLibNull.inf
CryptoPkg/Library/BaseCryptLibOnProtocolPpi/DxeCryptLib.inf
CryptoPkg/Library/BaseCryptLibOnProtocolPpi/PeiCryptLib.inf
CryptoPkg/Library/Include/CrtLibSupport.h
CryptoPkg/Library/OpensslLib/OpensslLib.inf
CryptoPkg/Library/OpensslLib/OpensslLibCrypto.inf
CryptoPkg/Library/TlsLib/TlsLib.inf
CryptoPkg/Library/TlsLibNull/TlsLibNull.inf
FatPkg/FatPkg.dsc
FmpDevicePkg/FmpDevicePkg.dsc
MdeModulePkg/MdeModulePkg.dsc
MdePkg/Include/IndustryStandard/Dhcp.h
MdePkg/Library/DxeServicesLib/DxeServicesLib.inf
NetworkPkg/HttpBootDxe/HttpBootDhcp4.h
NetworkPkg/NetworkPkg.dsc
SecurityPkg/SecurityPkg.dsc
ShellPkg/ShellPkg.dsc
UnitTestFrameworkPkg/UnitTestFrameworkPkg.dsc

RISC-V edk2 code change for CI : Part-1

RISC-V edk2 code change for CI : Part-1

---

BaseTools/Edk2ToolsBuild.py

REF:https://bugzilla.tianocore.org/show_bug.cgi?id=2640
Azure Pipelines agents have 2 threads. This commit has been shown to
reduce the build time in half on those agents.
Cc: Bob C Feng <bob.c.feng@intel.com>
Reviewed-by: Bob C Feng <bob.c.feng@intel.com>

BaseTools: Update Edk2ToolsBuild.py to use multiple threads on Linux

---

.azurepipelines/templates/pr-gate-steps.yml

Update CI steps to build base tools after setup and update,
as basetools might have dependencies that need to be resolved.

.azurepipelines: Update CI steps

---

CryptoPkg/Library/BaseCryptLibOnProtocolPpi/DxeCryptLib.c
CryptoPkg/Library/BaseHashApiLib/BaseHashApiLib.inf

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2552

CryptoPkg Code Style update

---

.mailmap

[edk2-devel] [PATCH 0/2] .mailmap: Update description and my email address
https://edk2.groups.io/g/devel/message/57040
http://mid.mail-archive.com/cover.1586295726.git.eugene@nuviainc.com

lersek queue 2020-Apr-09

---

NetworkPkg/Ip6Dxe/Ip6ConfigImpl.c
NetworkPkg/SnpDxe/Callback.c
NetworkPkg/SnpDxe/Snp.c
NetworkPkg/TlsAuthConfigDxe/TlsAuthConfigDxe.inf
NetworkPkg/TlsAuthConfigDxe/TlsAuthConfigDxeStrings.uni
NetworkPkg/TlsAuthConfigDxe/TlsAuthConfigImpl.c
NetworkPkg/TlsAuthConfigDxe/TlsAuthConfigImpl.h

NetworkPkg/Ip6Dxe: Validate source data record length
https://edk2.groups.io/g/devel/message/57052
NetworkPkg/SnpDxe: Prevent invalid PCI BAR access
https://edk2.groups.io/g/devel/message/57093
NetworkPkg/SnpDxe: Register SnpNotifyExitBootServices at TPL_CALLBACK
https://edk2.groups.io/g/devel/message/57137
NetworkPkg/TlsAuthConfigDxe: Use HiiPopUp() instead of CreatePopUp()
https://edk2.groups.io/g/devel/message/57108

Ww16 pipeline

---

CryptoPkg/Library/BaseCryptLib/Pk/CryptPkcs7VerifyBase.c

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2539
Microsoft signtool supports creation of attached P7's with any OID payload
via the "/p7co" parameter. It is necessary to check the data before get
the string.

CryptoPkg/Pkcs7: Extend support for other OID types

---

.pytool/CISettings.py
BaseTools/Plugin/HostBasedUnitTestRunner/HostBasedUnitTestRunner.py
BaseTools/Plugin/HostBasedUnitTestRunner/HostBasedUnitTestRunner_plug_in.yaml

REF:https://bugzilla.tianocore.org/show_bug.cgi?id=2513

Enable Host Unit Tests for Linux in Core CI

---

.pytool/Readme.md
UnitTestFrameworkPkg/ReadMe.md
UnitTestFrameworkPkg/UnitTestFrameworkPkg.ci.yaml

Cc: Bret Barkelew <bret.barkelew@microsoft.com>
Signed-off-by: Bret Barkelew <bret.barkelew@microsoft.com>

UnitTestFrameworkPkg: Add info to readme about working with UnitTests

---

Maintainers.txt

Add more reviewers for security-related feature domains.

Maintainers.txt: Add more reviewers for security features.

---

BaseTools/Scripts/PatchCheck.py

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2691
For files to be added to the tree, this feature will check
whether it has BSD plus patent license. If not, licenses listed in
Readme are also accepted but warning will be reported.
Otherwise, it should be error.

BaseTools/PatchCheck.py: Add LicenseCheck

---

SecurityPkg/Tcg/Tcg2Dxe/Tcg2Dxe.c
SecurityPkg/Tcg/Tcg2Dxe/Tcg2Dxe.inf

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2839
Signed-off-by: Jiewen Yao <jiewen.yao@intel.com>

SecurityPkg/Tcg2Dxe: Add PcdTcgPfpMeasurementRevision in SpecId event.

---

MdeModulePkg/Universal/Variable/RuntimeDxe/Variable.c

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2844
Update Reclaim() to return the error status from the reclaim
operation and not the status of SynchronizeRuntimeVariableCache()
that can be EFI_SUCCESS even through the status from reclaim
is an error.  Without this change, the return status from
SetVariable() can be EFI_SUCCESS even though the variable was
not actually set.  This occurs if the variable store is full
and a Reclaim() is invoked to free up space and even after all
possible space is freed, there is still not enough room for
the variable being set.  This condition should return
EFI_OUT_OF_RESOURCES.
Reviewed-by: Hao A Wu …

MdeModulePkg/Variable/RuntimeDxe: Fix return status from Reclaim()

---

MdeModulePkg/Universal/DisplayEngineDxe/ProcessOptions.c

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2326
Currently when meet mismatch case for one-of and ordered-list
menu, just show a popup window to indicate mismatch, no more
info for debugging. This patch is to add more debug message
about mismatch menu info which is helpful to debug.
Signed-off-by: Dandan Bi <dandan.bi@intel.com>

MdeModulePkg/DisplayEngine: Add Debug message to show mismatch menu info

---

Maintainers.txt

Add 'Zhiguang Liu' as a reviewer for MdePkg.

Maintainers.txt: Add 'Zhiguang Liu' for MdePkg review

---

EmbeddedPkg/Library/AndroidBootImgLib/AndroidBootImgLib.c
EmbeddedPkg/Universal/MmcDxe/Diagnostics.c
EmbeddedPkg/Universal/MmcDxe/MmcBlockIo.c

Based on original contribution at:
https://edk2.groups.io/g/devel/message/61830

Fixes emabling vs2017 build of EmbeddedPkg

---

MdePkg/Library/BaseLib/UnitTestHostBaseLib.inf

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2862
Add ReadMmx()/WriteMmx() services
Add MemoryFence() service

MdePkg/Library/UnitTestHostBaseLib: Add missing services

---

UefiCpuPkg/Library/CpuCommonFeaturesLib/MachineCheck.c

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2357

UefiCpuPkg/CpuCommonFeaturesLib: Fix spelling mistake

---

MdeModulePkg/Universal/EbcDxe/EbcDebugger/EdbCommand.c

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2360

MdeModulePkg/EbcDxe: Fix spelling mistake

---

MdeModulePkg/Universal/BdsDxe/BdsEntry.c

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2355

MdeModulePkg/BdsDxe: Fix spelling mistake

---

BaseTools/Source/C/VolInfo/VolInfo.c

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2349

BaseTools/VolInfo: Fix spelling mistake

---

Maintainers.txt

https://edk2.groups.io/g/devel/message/63631
http://mid.mail-archive.com/20200802034217.656418-1-rebecca@bsdio.com
https://edk2.groups.io/g/devel/message/63777
http://mid.mail-archive.com/b7fb5182-b6ef-b545-b985-fffe60b60372@freebsd.org
~~~
Bhyve files are under OvmfPkg, in OvmfPkg/Bhyve and
various files in OvmfPkg/Library and OvmfPkg/Include.
Update Maintainers.txt to indicate reviewers for all
bhyve-specific files.
Message-Id: <20200802034217.656418-1-rebecca@bsdio.com>
Reviewed-by: Laszlo …

Maintainers.txt: Add bhyve reviewers -- push

---

Maintainers.txt

Maintainers.txt: Add reviewer for serial, disk and SMBIOS

---

UnitTestFrameworkPkg/ReadMe.md
UnitTestFrameworkPkg/UnitTestFrameworkPkg.ci.yaml

* Add additional documentation about running tests locally
* Add a note about XML formatting
* Update readme with BaseLib and UNIT_TESTING_DEBUG
Signed-off-by: Bret Barkelew <Bret.Barkelew@microsoft.com>

UnitTestFrameworkPkg/Readme.md: Update documentation for latest features

---

MdeModulePkg/Application/CapsuleApp/CapsuleOnDisk.c

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2356
Reviewed-by: Guomin Jiang <guomin.jiang@intel.com>

MdeModulePkg/CapsuleApp: Fix spelling mistake

---

.pytool/Plugin/EccCheck/EccCheck.py
.pytool/Plugin/EccCheck/EccCheck_plug_in.yaml
.pytool/Plugin/EccCheck/Readme.md
ArmVirtPkg/ArmVirtPkg.ci.yaml
CryptoPkg/CryptoPkg.ci.yaml
EmulatorPkg/EmulatorPkg.ci.yaml
FatPkg/FatPkg.ci.yaml
FmpDevicePkg/FmpDevicePkg.ci.yaml
MdeModulePkg/MdeModulePkg.ci.yaml
MdePkg/MdePkg.ci.yaml
NetworkPkg/NetworkPkg.ci.yaml
OvmfPkg/OvmfPkg.ci.yaml
PcAtChipsetPkg/PcAtChipsetPkg.ci.yaml
SecurityPkg/SecurityPkg.ci.yaml
ShellPkg/ShellPkg.ci.yaml
UefiCpuPkg/UefiCpuPkg.ci.yaml
UnitTestFrameworkPkg/UnitTestFrameworkPkg.ci.yaml
pip-requirements.txt

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2606

Add a plugin to check Ecc issues for edk2 on open ci

---

SecurityPkg/Tcg/Opal/OpalPassword/OpalHii.c

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2346

SecurityPkg/OpalPassword: Fix spelling mistake

---

.azurepipelines/templates/pr-gate-build-job.yml
.pytool/CISettings.py
.pytool/Readme.md

Adds support for building DynamicTablesPkg using the EKDII Core C

Enable EDKII CI support for DynamicTablesPkg

---

Maintainers.txt

https://edk2.groups.io/g/devel/message/64539
http://mid.mail-archive.com/20200821144949.654-1-gaoliming@byosoft.com.cn
~~~
Message-Id: <20200821144949.654-1-gaoliming@byosoft.com.cn>
~~~

Maintainers.txt: Update Liming mail address -- push

---

IntelFsp2WrapperPkg/IntelFsp2WrapperPkg.dec

https://bugzilla.tianocore.org/show_bug.cgi?id=2944
https://edk2.groups.io/g/devel/message/64812
http://mid.mail-archive.com/20200831020721.8967-1-qi1.zhang@intel.com
~~~
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2944
Signed-off-by: Qi Zhang <qi1.zhang@intel.com>
Message-Id: <20200831020721.8967-1-qi1.zhang@intel.com>
~~~

[edk2-devel] [PATCH] IntelFsp2WrapperPkg/IntelFsp2WrapperPkg.dec: add FspMeasurementLib.h -- push

---

Maintainers.txt

https://edk2.groups.io/g/devel/message/65041
http://mid.mail-archive.com/20200904071913.17295-1-abner.chang@hpe.com
~~~
Add reviewers for all /RiscV64 folders.
Message-Id: <20200904071913.17295-1-abner.chang@hpe.com>
[lersek@redhat.com: pick up Leif's R-b from <20200830114401.GB20124@vanye>]
~~~

[edk2-devel] [PATCH v2 1/1] Maintainers.txt: Update reviewers of */RiscV64 -- push

---

BaseTools/Source/C/GNUmakefile
BaseTools/Source/C/Include/RiscV64/ProcessorBind.h
BaseTools/Source/C/Makefiles/header.makefile

- Add RISCV64 ProcessorBind.h
- Add RISCV64 to Makefiles
Signed-off-by: Nikita Ermakov <sh1r4s3@mail.si-head.nl>
Ack-by: Liming Gao <gaoliming@byosoft.com.cn>
Acked-by: Abner Chang <abner.chang@hpe.com>

BaseTools: Add RISCV64 binding

---

NetworkPkg/Library/DxeHttpLib/DxeHttpLib.c

When an HTTP server sends a non-chunked body data with no
Content-Length header, the HttpParserMessageBody in DxeHttpLib
gets confused and never sets the Char pointer beyond the body start.
This causes "for" loop to never break because the condition of
"Char >= Body + BodyLength" is never satisfied.
Use BodyLength as the ContentLength for the parser when
ContentLength is absent in HTTP response headers.
BZ: https://bugzilla.tianocore.org/show_bug.cgi?id=2941
Signed-off-by: Vladimir Olovyannikov <vladimir.olovyannikov@broadcom.com>

NetworkPkg: Fix possible infinite loop in HTTP msg body parser

---

IntelFsp2Pkg/Tools/GenCfgOpt.py

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2967
When no change in FSP UPD DSC files, GenCfgOpt.py should skip
recreating UPD header and BSF files.
This patch added a check to handle this case.

IntelFsp2Pkg/GenCfgOpt: skip unnecessarily header/BSF recreating.

---

BaseTools/Source/Python/AutoGen/GenC.py

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2969
Add EDKII_DSC_PLATFORM_GUID MACRO to AutoGen.h and AutoGen.c
Tested-by: Michael Kubacki <michael.kubacki@microsoft.com>

BaseTools: Add EDKII_DSC_PLATFORM_GUID MACRO

---

UefiCpuPkg/Library/MpInitLib/MpLib.c

https://edk2.groups.io/g/devel/message/65540
http://mid.mail-archive.com/21345cdbc906519558202b3851257ca07b9239ba.1600884239.git.thomas.lendacky@amd.com
~~~
UefiCpuPkg/MpInitLib: Reduce reset vector memory pressure
The AP reset vector stack allocation is only required if running as an
SEV-ES guest. Since the reset vector allocation is below 1MB in memory,
eliminate the requirement for bare-metal systems and non SEV-ES guests
to allocate the extra stack area, which can be large if the
PcdCpuMaxLogicalProcessorNumber value is large, and also remove the
CPU_STACK_ALIGNMENT alignment.
Fixes: 7b7508ad784d ("UefiCpuPkg: Allow AP booting under SEV-ES")
Cc: Garrett Kirkendall <garrett.kirkendall@amd.com>
Signed-off-by: Tom Lendacky <thomas.lendacky@amd.com>
Message-Id: …

[edk2-devel] [PATCH v2 1/1] UefiCpuPkg/MpInitLib: Reduce reset vector memory pressure -- push

---

FmpDevicePkg/FmpDxe/FmpDxe.c

Commit 6ad819c introduced two new functions in FmpDeviceLib:
1. FmpDeviceCheckImageWithStatus ()
2. FmpDeviceSetImageWithStatus ()
These functions allow an FmpDeviceLib implementation to return a
Last Attempt Status code value within the Device Library range from
LAST_ATTEMPT_STATUS_DEVICE_LIBRARY_MIN_ERROR_CODE_VALUE to
LAST_ATTEMPT_STATUS_DEVICE_LIBRARY_MAX_ERROR_CODE_VALUE.
To maintain backward compatibility, commit 6ad819c did not update
the FmpDxe driver to invoke these functions. FmpDeviceLib instances
should update their FmpDeviceCheckImage () function to simply call
FmpDeviceCheckImageWithStatus (). Similarly, FmpDeviceSetImage ()
should simply call FmpDeviceSetImageWithStatus (). This is
demonstrated in the implementation of these functions in …

FmpDevicePkg/FmpDxe: Call FmpDeviceLib WithStatus() functions

---

MdeModulePkg/Universal/DisplayEngineDxe/FormDisplay.c

Signed-off-by: gechao <gechao@greatwall.com.cn>

MdeModulePkg DisplayEngineDxe: Correct the local variable name.

---

OvmfPkg/Bhyve/BhyveX64.dsc
OvmfPkg/Bhyve/PlatformPei/Platform.c
OvmfPkg/Bhyve/ResetVector/Ia16/Real16ToFlat32.asm
OvmfPkg/Library/PlatformBootManagerLibBhyve/BdsPlatform.c

msgid <20201124005733.18107-1-rebecca@bsdio.com>
https://edk2.groups.io/g/devel/message/67844
https://www.redhat.com/archives/edk2-devel-archive/2020-November/msg01003.html
~~~
various bhyve tweaks and updates
v2: Added my copyright notice to Real16ToFlat32.asm
Rebecca Cran (3):
OvmfPkg/Bhyve: Add VariablePolicy engine to Bhyve
OvmfPkg/Bhyve: Add support for the AMD host bridge
OvmfPkg/Bhyve: Copy Real16ToFlat32.asm and enable cache in CR0
OvmfPkg/Bhyve/BhyveX64.dsc                    |   4 +-
OvmfPkg/Bhyve/PlatformPei/Platform.c          |   3 +-
.../PlatformBootManagerLibBhyve/BdsPlatform.c |   6 +-
.../Bhyve/ResetVector/Ia16/Real16ToFlat32.asm | 143 ++++++++++++++++++
4 files changed, 152 insertions(+), 4 deletions(-)
create mode 100644 OvmfPkg/Bhyve/ResetVector/Ia16/Real16ToFlat32.asm …

[edk2-devel] [PATCH v2 0/3] various bhyve tweaks and updates -- push

---

BaseTools/Scripts/ConvertFceToStructurePcd.py

Currently, only parts of the Header files can be collected which
caused some struct definition can not be found. To solve this issue,
Header files full collection has been added in this file to support
the struct finding.

BaseTools: Collect full Header files for struct finding.

---

UefiPayloadPkg/UefiPayloadPkg.dsc

UefiPayloadPkg: Fix master by adding SafeIntLib

---

UefiCpuPkg/Library/SmmCpuFeaturesLib/SmmCpuFeaturesLib.c

Add Tiger Lake ModelId support in the SMM CPU feature lib.

UefiCpuPkg/SmmCpuFeaturesLib: Add Tiger Lake support

---

UefiCpuPkg/Library/RegisterCpuFeaturesLib/CpuFeaturesInitialize.c

CpuInfo.First stores whether the current thread belongs to the first
package in the platform, first core in a package, first thread in a
core.
But the time complexity of original algorithm to calculate the
CpuInfo.First is O (n) * O (p) * O (c).
n: number of processors
p: number of packages
c: number of cores per package
The patch trades time with space by storing the first package, first
core per package, first thread per core in an array.
The time complexity becomes O (n).
Cc: Yun Lou <yun.lou@intel.com>

UefiCpuPkg/CpuFeature: reduce time complexty to calc CpuInfo.First

---

BaseTools/Scripts/ConvertFceToStructurePcd.py

Currently VFR files have variables comments which will not be
added into StructurePcd.dsc file. Thus, it is not convenient for
developer to Modify Pcds. To solve this problem, The comments will
be modified to user friendly format and added after the corresponding
Pcd values in StructurePcd.dsc file.

BaseTools: Add comments in StructurePcd DSC file.

---

MdeModulePkg/Bus/Pci/PciSioSerialDxe/SerialIo.c

https://bugzilla.tianocore.org/show_bug.cgi?id=3114
Add logic to flush all UART transmit buffers if there is a
config change from Reset(), SetAttributes() or SetControl().
Use a timeout in the flush operation, so the system can
continue to boot if the transmit buffers can not be
flushed for any reason.
This change prevents lost characters on serial debug logs
and serial consoles when a config change is made.  It also
prevents a UART from getting into a bad state or reporting
error status due to characters being transmitted at the same
time registers are updated with new communications settings.
Reviewed-by: Hao A Wu …

MdeModulePkg/PciSioSerialDxe: Flush Tx before config change

---

.azurepipelines/Ubuntu-GCC5.yml
.azurepipelines/Ubuntu-PatchCheck.yml
.azurepipelines/Windows-VS2019.yml
ArmVirtPkg/PlatformCI/.azurepipelines/Ubuntu-GCC5.yml
EmulatorPkg/PlatformCI/.azurepipelines/Ubuntu-GCC5.yml
EmulatorPkg/PlatformCI/.azurepipelines/Windows-VS2019.yml
OvmfPkg/PlatformCI/.azurepipelines/Ubuntu-GCC5.yml
OvmfPkg/PlatformCI/.azurepipelines/Windows-VS2019.yml

https://bugzilla.tianocore.org/show_bug.cgi?id=3130

[edk2-devel] [Patch 0/4] Enable EDK II CI for stable/* branches

---

.mergify/config.yml

https://bugzilla.tianocore.org/show_bug.cgi?id=3130

.mergify: Enable Mergify for stable/* branches

---

NetworkPkg/DnsDxe/DnsDhcp.c
NetworkPkg/DnsDxe/DnsDriver.c
NetworkPkg/DnsDxe/DnsImpl.c
NetworkPkg/DnsDxe/DnsImpl.h
NetworkPkg/DnsDxe/DnsProtocol.c

add whitespace according to coding style.

NetworkPkg/DnsDxe: cosmetic fixups

---

BaseTools/Source/C/LzmaCompress/LZMA-SDK-README.txt
BaseTools/Source/C/LzmaCompress/LzmaCompress.c
BaseTools/Source/C/LzmaCompress/Sdk/C/7zTypes.h
BaseTools/Source/C/LzmaCompress/Sdk/C/7zVersion.h
BaseTools/Source/C/LzmaCompress/Sdk/C/CpuArch.h
BaseTools/Source/C/LzmaCompress/Sdk/C/LzFind.c
BaseTools/Source/C/LzmaCompress/Sdk/C/LzFindMt.c
BaseTools/Source/C/LzmaCompress/Sdk/C/LzFindMt.h
BaseTools/Source/C/LzmaCompress/Sdk/C/LzmaDec.c
BaseTools/Source/C/LzmaCompress/Sdk/C/LzmaEnc.c
BaseTools/Source/C/LzmaCompress/Sdk/DOC/lzma-history.txt
BaseTools/Source/C/LzmaCompress/Sdk/DOC/lzma-sdk.txt
MdeModulePkg/Library/LzmaCustomDecompressLib/LZMA-SDK-README.txt
MdeModulePkg/Library/LzmaCustomDecompressLib/LzmaArchCustomDecompressLib.inf
MdeModulePkg/Library/LzmaCustomDecompressLib/LzmaCustomDecompressLib.inf
MdeModulePkg/Library/LzmaCustomDecompressLib/Sdk/C/7zTypes.h
MdeModulePkg/Library/LzmaCustomDecompressLib/Sdk/C/7zVersion.h
MdeModulePkg/Library/LzmaCustomDecompressLib/Sdk/C/CpuArch.h
MdeModulePkg/Library/LzmaCustomDecompressLib/Sdk/C/LzFind.c
MdeModulePkg/Library/LzmaCustomDecompressLib/Sdk/C/LzmaDec.c
MdeModulePkg/Library/LzmaCustomDecompressLib/Sdk/DOC/lzma-history.txt
MdeModulePkg/Library/LzmaCustomDecompressLib/Sdk/DOC/lzma-sdk.txt
MdeModulePkg/MdeModulePkg.ci.yaml

New formal release in https://www.7-zip.org/sdk.html is 19.00.
Update LZMA version from 18.05 to 19.00

Update LZMA SDK version to 19.00

---

UefiCpuPkg/PiSmmCpuDxeSmm/CpuS3.c

https://edk2.groups.io/g/devel/message/70097
https://www.redhat.com/archives/edk2-devel-archive/2021-January/msg00584.html
Message-Id: <20210111015419.28368-1-star.zeng@intel.com>
~~~
This patch makes two refinements to reduce SMRAM consumption in CpuS3.c.
1. Only do CopyRegisterTable() when register table is not empty,
IsRegisterTableEmpty() is created to check whether the register table
is empty or not.
Take empty PreSmmInitRegisterTable as example, about 24K SMRAM consumption
could be reduced when mAcpiCpuData.NumberOfCpus=1024.
sizeof (CPU_REGISTER_TABLE) = 24
mAcpiCpuData.NumberOfCpus = 1024 = 1K
mAcpiCpuData.NumberOfCpus * sizeof (CPU_REGISTER_TABLE) = 24K
2. Only copy table entries buffer instead of whole buffer.
AllocatedSize in SourceRegisterTableList is the whole buffer size. …

[edk2-devel] [PATCH V4] UefiCpuPkg PiSmmCpuDxeSmm: Reduce SMRAM consumption in CpuS3.c -- push

---

MdeModulePkg/MdeModulePkg.dec
MdeModulePkg/MdeModulePkg.uni

No cover-letter for the series.
(Change default value of PcdPcieResizableBarSupport to FALSE to resolve regression)
**Bugzilla tracker:**
https://bugzilla.tianocore.org/show_bug.cgi?id=3138
**Series at mailing list:**
https://edk2.groups.io/g/devel/message/70139
https://edk2.groups.io/g/devel/message/70140

Push pcie resizable bar

---

OvmfPkg/CpuS3DataDxe/CpuS3Data.c
OvmfPkg/CpuS3DataDxe/CpuS3DataDxe.inf
UefiCpuPkg/CpuS3DataDxe/CpuS3Data.c
UefiCpuPkg/Include/AcpiCpuData.h
UefiCpuPkg/Library/RegisterCpuFeaturesLib/RegisterCpuFeaturesLib.c

https://bugzilla.tianocore.org/show_bug.cgi?id=3159
Message-Id: <20210119155440.2262-1-lersek@redhat.com>
https://edk2.groups.io/g/devel/message/70548
https://www.redhat.com/archives/edk2-devel-archive/2021-January/msg01036.html
~~~
Ref:    https://bugzilla.tianocore.org/show_bug.cgi?id=3159
Branch: remove-cpu-reg-table-alloc-3159-v2
Updates in v2:
- v1 patches have not received any updates, I've only picked up the
feedback tags.
- Patch v2 #1 -- for RegisterCpuFeaturesLib -- is new; authored by Ray
and updated slightly by myself. Star and/or Eric should please approve
this patch.
v1 was posted at:
[edk2-devel] [PATCH 0/3] UefiCpuPkg, OvmfPkg: do not allocate useless
register tables for S3 resume
Message-Id: …

[edk2-devel] [PATCH v2 0/4] UefiCpuPkg, OvmfPkg: do not allocate useless register tables for S3 resume -- push

---

BaseTools/Source/Python/tests/Split/test_split.py

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3165
This patch is to add the unit test for Split python tool

BaseTools: Add unittest for Split tool

---

OvmfPkg/QemuFlashFvbServicesRuntimeDxe/QemuFlashDxe.c

https://bugzilla.tianocore.org/show_bug.cgi?id=3183
https://edk2.groups.io/g/devel/message/70703
https://www.redhat.com/archives/edk2-devel-archive/2021-January/msg01190.html
msgid: <84a5f9161541db5aa3b57c96b737afbcb4b6189d.1611410263.git.thomas.lendacky@amd.com>
~~~
From: Tom Lendacky <thomas.lendacky@amd.com>
BZ: https://bugzilla.tianocore.org/show_bug.cgi?id=3183
Under SEV-ES, a write to the flash device is done using a direct VMGEXIT
to perform an MMIO write. The address provided to the MMIO write must be
the physical address of the MMIO write destitnation. During boot, OVMF
runs with an identity mapped pagetable structure so that VA == PA and the
VMGEXIT MMIO write destination is just the virtual address of the flash
area address being written.
However, when the UEFI …

[edk2-devel] [PATCH v2] OvmfPkg/QemuFlashFvbServicesRuntimeDxe: Use physical address with SEV-ES -- push

---

UefiCpuPkg/Library/MpInitLib/MpLib.c

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3182
Fix the order of operations in ApWakeupFunction() when PcdCpuApLoopMode
is set to HLT mode that uses INIT-SIPI-SIPI to wake APs.  In this mode,
volatile state is restored and saved each time a INIT-SIPI-SIPI is sent
to an AP to request a function to be executed on the AP.  When the
function is completed the volatile state of the AP is saved.  However,
the counters NumApsExecuting and FinishedCount are updated before
the volatile state is saved.  This allows for a race condition window
for the BSP that is waiting on these counters to request a new
INIT-SIPI-SIPI before all the APs have completely saved their volatile
state.  The fix is to save the AP volatile state before updating the
NumApsExecuting and FinishedCount counters.
Cc: …

UefiCpuPkg/Library/MpInitLib: Fix AP VolatileRegisters race condition

---

UefiCpuPkg/Library/MpInitLib/MpLib.c

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3179
When BSP first time wakes all APs, each AP atomically increases
CpuMpData->CpuCount and CpuMpData->FinishedCount.
Each AP atomically increases CpuMpData->NumApsExecuting
in early assembly code and decreases it before it enters to HLT or
MWAIT state.
Putting them together, the 3 variables are changed in the following order:
1. NumApsExecuting++ // in assembly
2. CpuCpunt++
4. FinishedCount++
3. NumApsExecuting-- // in C
BSP waits for a certain timeout and then polls NumApsExecuting
until it drops to zero. It assumes all APs are waken up concurrently
and NumApsExecuting only drops to zero when all APs have checked in.
Then it additionally waits for FinishedCount == CpuCount - 1. (FinishedCount doesn't include BSP while CpuCount …

UefiCpuPkg/MpInitLib: Don't increase CpuCount in ApWakeupFunction

---

UefiCpuPkg/Include/Library/CpuCacheInfoLib.h
UefiCpuPkg/Library/CpuCacheInfoLib/CpuCacheInfoLib.c
UefiCpuPkg/Library/CpuCacheInfoLib/DxeCpuCacheInfoLib.c
UefiCpuPkg/Library/CpuCacheInfoLib/DxeCpuCacheInfoLib.inf
UefiCpuPkg/Library/CpuCacheInfoLib/PeiCpuCacheInfoLib.inf

Several bug fixes to CpuCacheInfoLib

Several bug fixes to CpuCacheInfoLib

---

RedfishPkg/PrivateLibrary/RedfishCrtLib/RedfishCrtLib.c

Add more functions which were missed in the first time commit,
that causes the build error with EDK2 Redfish feature driver.
strerror - We don't support this on edk2 environment.
strpbrk  - Cloned this function from edk2-LibC
File operation functions - Not supported on edk2 environment.
Acked-by: Leif Lindholm <leif@nuviainc.com>

RedfishPkg/RedfishCrtLib: Add more CRT functions

---

RedfishPkg/Include/Library/JsonLib.h
RedfishPkg/Library/JsonLib/JsonLib.c

Add JsonLoadString function to load a NULL terminated-string JSON

RedfishPkg/JsonLib: Add JsonLoadString function

---

ArmPkg/Library/StandaloneMmMmuLib/AArch64/ArmMmuStandaloneMmLib.c

The following patches added support for StandaloneMM using FF-A:
9da5ee116a28 ArmPkg: Allow FF-A calls to set memory region's attributes
0e43e02b9bd8 ArmPkg: Allow FF-A calls to get memory region's attributes
However, in the error handling logic for the Get/Set Memory attributes,
the CLANG compiler reports that a status variable could be used without
initialisation. This issue is a false positive and is not seen with GCC.
The Get/Set Memory attributes operation is atomic and therefore an
FFA_INTERRUPT or FFA_SUCCESS response is not expected in response
to FFA_MSG_SEND_DIRECT_REQ. So the remaining cases that could occur
are:
- the target sends FFA_MSG_SEND_DIRECT_RESP with a success or
failure code.
or
- FFA_MSG_SEND_DIRECT_REQ transmission failure.
Therefore,
- reorder the error handling …

ArmPkg: Fix uninitialised variable in ArmMmuStandaloneMmLib

---

ShellPkg/Library/UefiShellDebug1CommandsLib/SmbiosView/PrintInfo.c
ShellPkg/Library/UefiShellDebug1CommandsLib/SmbiosView/SmbiosViewStrings.uni

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3177
Add ContainedElementCount, ContainedElementRecordLength and
ContainedElements for smbiosview type 3.
Signed-off-by: Mars CC Lin <mars_cc_lin@phoenix.com>
Cc: Philippe Mathieu-Daude <philmd@redhat.com>

ShellPkg/SmbiosView: add more items for smbiosview -t 3

---

UefiCpuPkg/PiSmmCpuDxeSmm/X64/PageTbl.c

Use SMM stack guard feature to detect SMM shadow stack overflow.
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3280
Signed-off-by: Sheng Wei <w.sheng@intel.com>
Cc: Roger Feng <roger.feng@intel.com>

UefiCpuPkg/PiSmmCpuDxeSmm: Support detect SMM shadow stack overflow

---

BaseTools/Source/Python/AutoGen/PlatformAutoGen.py

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3312
Update parsing of MAKE_FLAGS in DSC [BuildOptions] sections
to split the flags into a list to be compatible with
running the make command using Popen().  Parsing MAKE_FLAGS
from tools_def.txt already uses _SplitOption().  This change
uses the same _SplitOption() method for MAKE_FLAGS from a
DSC [BuildOptions] section.
Also update the parsing of MAKE_PATH to support MAKE_PATH
from tools_def.txt or the DSC [BuildOptions] section.  MAKE_PATH
in DSC [BuildOptions] section is higher priority than MAKE_PATH
in tools_def.txt.
Reviewed-by: Yuwei Chen …

BaseTools/PlatformAutoGen: MAKE_FLAGS and MAKE_PATH fixes

---

ArmPkg/Include/Library/OemMiscLib.h
ArmPkg/Universal/Smbios/OemMiscLibNull/OemMiscLib.c
ArmPkg/Universal/Smbios/SmbiosMiscDxe/Type03/MiscChassisManufacturerData.c
ArmPkg/Universal/Smbios/SmbiosMiscDxe/Type03/MiscChassisManufacturerFunction.c
ArmPkg/Universal/Smbios/SmbiosMiscDxe/Type32/MiscBootInformationFunction.c

Add the set of improvements requested during the initial series to move                                 
closer to a full/proper implementation, fix the                                                         
chassis SKU number string, and fix a typo in a comment.                                                 
This is a breaking change wrt SbsaQemu in edk2-platforms.                                               
Rebecca Cran (5):                                                                                       
ArmPkg: Allow platforms to override PCI supported state in                                            
SmbiosMiscDxe                                                                                       
ArmPkg: Allow platforms to supply more data for SMBIOS Type3 record …

ArmPkg: OemMiscLib and Universal/Smbios improvements and fixes

---

UefiCpuPkg/PiSmmCpuDxeSmm/MpService.c

5-level paging can be enabled on CPU which supports up to 52 physical
address size. But when the feature was enabled, the 48 address size
limit was not removed and the 5-level paging testing didn't access
address >= 2^48. So the issue wasn't detected until recently an
address >= 2^48 is accessed.

UefiCpuPkg/PiSmmCpu: Remove hardcode 48 address size limitation

---

BaseTools/Source/C/GenFw/Elf64Convert.c

Ref: https://bugzilla.tianocore.org/show_bug.cgi?id=3096
This patch adds support for R_RISCV_CALL_PLT and R_RISCV_GOT_HI20
relocations generated by PIE enabled compiler. This also needed
changes to R_RISCV_32 and R_RISCV_64 relocations as explained in
https://github.com/riscv/riscv-gnu-toolchain/issues/905#issuecomment-846682710
Testing:
1) Debian GCC 8.3.0 and booted sifive_u and QMEU virt models.
2) Debian 10.2.0 and booted QEMU virt model.
3) riscv-gnu-tool chain 9.2 and booted QEMU virt model.
Signed-off-by: Sunil V L <sunilvl@ventanamicro.com>
Acked-by: Abner Chang <abner.chang@hpe.com>
Reviewed-by: Daniel Schaefer <daniel.schaefer@hpe.com>
Tested-by: Daniel Schaefer <daniel.schaefer@hpe.com>
Cc: …

BaseTools GenFw: Add support for RISCV GOT/PLT relocations

---

IntelFsp2Pkg/Tools/PatchFv.py

REF:https://bugzilla.tianocore.org/show_bug.cgi?id=3476
parseInfFile currently reading the EFI_BASE_ADDRESS from INF, once the
address found still it's continues to read the complete inf file which
is not required. once the EFI_BASE_ADDRESS read from the INF no need to
read the INF further.
MSFT compiler can generate the map file address 8 or 16 based on which
architecture the INF is compiler. currently it's support for IA32,
modified the patchfv to support for all.
modification of few typo errors in parseModMapFile, getCurr function
required
verification : Working Fine
Signed-off-by: Ashraf Ali S <ashraf.ali.s@intel.com>
Reviewed-by: …

IntelFsp2Pkg: PatchFv parseInfFile function modification

---

IntelFsp2Pkg/Tools/ConfigEditor/ConfigEditor.py
IntelFsp2Pkg/Tools/ConfigEditor/GenYamlCfg.py
IntelFsp2Pkg/Tools/UserManuals/ConfigEditorUserManual.md

BZ: https://bugzilla.tianocore.org/show_bug.cgi?id=3482
This patch adds a search function in the Config Editor GUI at
the top right corner. Once users key in the words to search,
it will look for the option containing the string in the
same page and display it. It also includes a README for this
function.

IntelFsp2Pkg: Add search function for Config Editor

---

UefiPayloadPkg/UefiPayloadPkg.fdf

UefiPayloadPkg: Add FV Guid for DXEFV and PLDFV

---

MdePkg/Library/BaseLib/BaseLib.inf
MdePkg/Library/BaseLib/RiscV64/MemoryFence.S

Reviewed-by: Abner Chang <abner.chang@hpe.com>

MdePkg/BaseLib: Add MemoryFence implementation for RiscV64

---

SecurityPkg/Library/Tpm2CommandLib/Tpm2Capability.c

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2855
The Tpm2GetCapabilitySupportedAndActivePcrs function prints a
count number that should reflect the *supported and currently
active* PCR banks, but the implementation in place displays
instead the count of the *supported PCR banks* retrieved
directly from the Tpm2GetCapabilityPcrs()
TPML_PCR_SELECTION output.
The counter should only take into account those PCRs banks
which are active.
Replaced usage of EFI_D_* for DEBUG_* definitions in debug
messages.
Signed-off-by: Rodrigo Gonzalez del Cueto <rodrigo.gonzalez.del.cueto@intel.com>

SecurityPkg: Fix GetSupportedAndActivePcrs counter calculation

---

RedfishPkg/Include/Library/JsonLib.h
RedfishPkg/Library/JsonLib/JsonLib.c

RedfishPkg/JsonLib: Add more JsonLib functions

---

IntelFsp2Pkg/Tools/ConfigEditor/ConfigEditor.py
IntelFsp2Pkg/Tools/ConfigEditor/GenYamlCfg.py

BZ: https://bugzilla.tianocore.org/show_bug.cgi?id=3567
This patch is to enable config editor to have a new feature that
can spell out the delta between the default configuration files'
data, such as YAML and BSF, against the data stored in the binary.
This can help users understand and track the difference when
modifications are made.

IntelFsp2Pkg: Support Config File and Binary delta comparison

---

.azurepipelines/templates/pr-gate-build-job.yml
.pytool/CISettings.py
UefiPayloadPkg/UefiPayloadPkg.ci.yaml

Create configuration .yaml file in UefiPayloadPkg.
Add UefiPayloadPkg in gate-build-job.yml and CISetting.py.

Enable Core ci for UefiPayloadPkg

---

SecurityPkg/FvReportPei/FvReportPei.c

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3615
Debug message should be added for indicating IBB is successfully verifying
the OBB.
Cc: Min M Xu <min.m.xu@intel.com>
Signed-off-by: Longlong Yang <longlong.yang@intel.com>
Reviewed-by: Min M Xu <min.m.xu@intel.com>

SecurityPkg: Add debug log for indicating IBB verified OBB successfully

---

MdeModulePkg/Application/BootManagerMenuApp/BootManagerMenu.c

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3590
Limit the draw box always within the screen's column and row.
Limit the string drawing within one line.
For the incompleted string the last 3 characters in one line would
be replaced with "...".

MdeModulePkg/BootManagerMenuApp: Limit string drawing within one line

---

UefiPayloadPkg/UefiPayloadPkg.dsc

Signed-off-by: Cheng-Chieh Huang <chengchieh@google.com>
Cc: Cheng-Chieh Huang <chengchieh@google.com>
Cc: Trammell Hudson <hudson@trmm.net>

UefiPayloadPkg: Update maximum logic processor to 256

---

RedfishPkg/Readme.md

Add more information of network settings for EDK2
Redfish service on EmulatorPkg.

RedfishPkg: Add more information to Readme.md

---

IntelFsp2Pkg/Tools/SplitFspBin.py

Signed-off-by: Star Zeng <star.zeng@intel.com>

IntelFsp2Pkg SplitFspBin.py: Correct file name in file header

---

MdeModulePkg/Bus/Pci/UfsPciHcPei/UfsPciHcPei.c

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3703
MMIO base address size will overflow while finding two or more Host
controller in the system. Correct it and support 32 and 64 bits address
space.
Signed-off-by: Ian Chiu <ian.chiu@intel.com>
Cc: Maggie Chu <maggie.chu@intel.com>

MdeModulePkg\UfsBlockIoPei: UFS MMIO address size support both 32/64 bits

---

.pytool/Plugin/EccCheck/EccCheck.py

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2986
---
New in V2
* Change temp directory path from Build/ecctemp to
Build/.pytool/Plugin/EccCheck to provide a unique
temp directory location for any .pytool Plugin.
* Set working directory when ECC runs to temp directory
to guarantee all temp files created by EccCheck are
cleaned up.
---
* Use temp directory for all operations to prevent any
changed to git state.
* Remove git reset operation that could corrupt staged
and local changes.
* Improve performance by removing redundant directory scans
* Improve performance and reduce log file sizes by using
--output option of git diff to a temp file instead of
using stdout.
Cc: Liming Gao …

Bug 2986 ecc check remove git revert v2

---

StandaloneMmPkg/Library/FvLib/FvLib.c

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3769
Current FvLib will hit parse issue when encountering LARGE file, then
ignore latter ffs/section, thus causing required drivers not being
dispatched. Therefore, need to add support for EFI_FFS_FILE_HEADER2
and EFI_COMMON_SECTION_HEADER2 in FvLib to fix this issue.
Signed-off-by: Wei6 Xu <wei6.xu@intel.com>

StandaloneMmPkg/FvLib: Support large file with EFI_FFS_FILE_HEADER2.

---

OvmfPkg/PlatformPei/MemDetect.c

This reverts commit 41d8bb30386ceab55787fc9f5aac6434e2493e27, as it
breaks Cloud Hypervisor.
Reported-by: Sebastien Boeuf <sebastien.boeuf@intel.com>
Signed-off-by: Ard Biesheuvel <ardb@kernel.org>

OvmfPkg/PlatformPei: Revert "stop using cmos for memory detection"

---

MdeModulePkg/Bus/Ufs/UfsBlockIoPei/UfsBlockIoPei.c
MdeModulePkg/Bus/Ufs/UfsBlockIoPei/UfsHci.c

**Series sent at:** https://edk2.groups.io/g/devel/message/85193
**BZ:**
https://bugzilla.tianocore.org/show_bug.cgi?id=3714
https://bugzilla.tianocore.org/show_bug.cgi?id=3775
https://bugzilla.tianocore.org/show_bug.cgi?id=3776
**Cover letter:**
VincentX Ke (3):
MdeModulePkg: Replace with UFS_UNIT_DESC to fix timeout problem
MdeModulePkg: Refactoring UFS DME request and fix timing problem
MdeModulePkg: Put off UFS HCS.DP checking to fix timing problem
.../Bus/Ufs/UfsBlockIoPei/UfsBlockIoPei.c     |  23 +-
MdeModulePkg/Bus/Ufs/UfsBlockIoPei/UfsHci.c   | 373 ++++++++++--------
2 files changed, 217 insertions(+), 179 deletions(-)

MdeModulePkg: Fix UfsBlockIoPei timing problem

---

UefiPayloadPkg/UefiPayloadPkg.fdf

Chanage the name "Uiapp" to "Enter Setup".
Signed-off-by: Yuanhao Xie <yuanhao.xie@intel.com>

UefiPayloadPkg: Change the user interface name of the Uiapp

---

RedfishPkg/RedfishRestExDxe/RedfishRestExImpl.c

Remove redundant determine statements.
No functional change.

RedfishPkg/RedfishRestExDxe:Simplify status check

---

ArmPkg/Drivers/MmCommunicationDxe/MmCommunication.c
MdeModulePkg/Universal/Variable/RuntimeDxe/VariablePolicySmmDxe.c
MdePkg/Include/Protocol/MmCommunication2.h

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3709
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3751
This patch series is a follow up of previous submission:
https://edk2.groups.io/g/devel/message/85116

MM communicate functionality in variable policy

---

Maintainers.txt

Maintainers.txt: Add Sami Mujawar as reviewer for ArmPkg

---

MdeModulePkg/Application/UiApp/FrontPage.c
MdeModulePkg/Application/UiApp/FrontPage.h
MdeModulePkg/Application/UiApp/FrontPageVfr.Vfr

Signed-off-by: Matt DeVillier <matt.devillier@gmail.com>

MdeModulePkg/UiApp: Fix spelling of 'FRONTPAGE'

---

BaseTools/Source/C/BrotliCompress/GNUmakefile
BaseTools/Source/C/BrotliCompress/Makefile

This patch set can resolve the build failure issue with GCC 11.

Update brotli submodule

---

UefiPayloadPkg/BlSupportSmm/BlSupportSmm.c

Signed-off-by: Matt DeVillier <matt.devillier@gmail.com>

BlSupportSmm: fix definition of SetSmrr()

---

.azurepipelines/Ubuntu-PatchCheck.yml
.azurepipelines/templates/platform-build-run-steps.yml
.azurepipelines/templates/pr-gate-steps.yml
.pytool/Plugin/CharEncodingCheck/CharEncodingCheck.py
.pytool/Plugin/CompilerPlugin/CompilerPlugin.py
.pytool/Plugin/DependencyCheck/DependencyCheck.py
.pytool/Plugin/DscCompleteCheck/DscCompleteCheck.py
.pytool/Plugin/GuidCheck/GuidCheck.py
.pytool/Plugin/HostUnitTestCompilerPlugin/HostUnitTestCompilerPlugin.py
.pytool/Plugin/HostUnitTestDscCompleteCheck/HostUnitTestDscCompleteCheck.py
.pytool/Plugin/LibraryClassCheck/LibraryClassCheck.py
.pytool/Plugin/SpellCheck/SpellCheck.py
.pytool/Plugin/UncrustifyCheck/UncrustifyCheck.py
pip-requirements.txt

Update .pytools to use newest tool versions. Fixed typo in Edk2pathObj.GetAbsolutePathOnThisSystemFromEdk2RelativePath. Updated .azurepipelines to use latest python version.

Update edk2 ci v5

---

MdePkg/Include/IndustryStandard/SmBios.h

Adds following changes
1) Added support for manufacturing mode in
BIOS Characteristics Extension Byte 2.
2) Added support for slot height in
System Slot Table (type 9).
3) Updated Built-in pointing device interface with
USB, I2C and SPI.
4) Updates Onboard Devices Extended Information with
wireless LAN, bluetooth, WWAN, eMMC, NVMe and UFC.
5) Added new table Firmware Inventory Information (Type 45)
and its corresponding enum values.
6) Added new table String Property Table (Type 46)
and its corresponding enum values.
Signed-off-by: Abdul Lateef Attar <abdattar@amd.com>

MdePkg/Include: Smbios Specification 3.5.0 changes

---

IntelFsp2Pkg/FspSecCore/SecFsp.c
IntelFsp2Pkg/FspSecCore/SecFsp.h
IntelFsp2Pkg/Include/FspGlobalData.h
IntelFsp2Pkg/Include/Library/FspCommonLib.h
IntelFsp2Pkg/Library/BaseFspCommonLib/FspCommonLib.c

REF:https://bugzilla.tianocore.org/show_bug.cgi?id=3867
Add BaseFspCommonLib Support for X64.

IntelFsp2Pkg: BaseFspCommonLib Support for X64

---

MdeModulePkg/Bus/Pci/NvmExpressDxe/NvmExpressHci.c
MdeModulePkg/Bus/Pci/NvmExpressPei/NvmExpressPeiHci.c

**Series sent at:**
https://edk2.groups.io/g/devel/message/87898
https://edk2.groups.io/g/devel/message/87899
https://edk2.groups.io/g/devel/message/87900
**Cover letter:**
new patch series, including the fix for the same problem in PEI
Mara Sophie Grosch (2):
MdeModulePkg/NvmExpressDxe: fix check for Cap.Css
MdeModulePkg/NvmExpressPei: fix check for NVM command set
MdeModulePkg/Bus/Pci/NvmExpressDxe/NvmExpressHci.c    | 2 +-
MdeModulePkg/Bus/Pci/NvmExpressPei/NvmExpressPeiHci.c | 2 +-
2 files changed, 2 insertions(+), 2 deletions(-)

MdeModulePkg: fix checks for NVM command set

---

UefiPayloadPkg/BuildAndIntegrationInstructions.txt

Signed-off-by: Akihiko Odaki <akihiko.odaki@gmail.com>

UefiPayloadPkg: Fix architecture in the build instruction

---

UefiPayloadPkg/UefiPayloadPkg.dsc

Signed-off-by: Sean Rhodes sean@starlabs.systems

UefiPayloadPkg: Make Boot Timeout configurable

---

.azurepipelines/Ubuntu-PatchCheck.yml
.azurepipelines/Windows-VS2019.yml
.azurepipelines/templates/platform-build-run-steps.yml
.azurepipelines/templates/pr-gate-steps.yml
BaseTools/Bin/gcc_aarch64_linux_ext_dep.yaml
BaseTools/Bin/gcc_arm_linux_ext_dep.yaml
EmulatorPkg/PlatformCI/.azurepipelines/Windows-VS2019.yml
OvmfPkg/PlatformCI/.azurepipelines/Windows-VS2019.yml

Switch "windows-latest" VM image to "windows-2019" in repo YAML files.

Switch to vs2019 vm image

---

UefiPayloadPkg/UniversalPayloadBuild.py

UefiPayloadPkg: Add --quiet argument to Universal Payload build script

---

NetworkPkg/HttpDxe/HttpDns.c
NetworkPkg/HttpDxe/HttpDxe.inf
NetworkPkg/HttpDxe/HttpImpl.c
NetworkPkg/HttpDxe/HttpProto.c
NetworkPkg/HttpDxe/HttpProto.h
NetworkPkg/NetworkPkg.dec
NetworkPkg/NetworkPkg.uni

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2720
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3889

mrabeda queue - BZ 3889 & 2720

---

ShellPkg/Library/UefiShellDebug1CommandsLib/SmbiosView/QueryTable.c

REF:https://bugzilla.tianocore.org/show_bug.cgi?id=3900
update smbiosview type 41 related fileds.
Signed-off-by: Bo Chang Ke <bo-changx.ke@intel.com>

ShellPkg: Update smbiosview type 41 with SMBIOS 3.5 fields

---

ShellPkg/Library/UefiShellDebug1CommandsLib/SmbiosView/PrintInfo.c
ShellPkg/Library/UefiShellDebug1CommandsLib/SmbiosView/SmbiosViewStrings.uni

REF:https://bugzilla.tianocore.org/show_bug.cgi?id=3906
update smbiosview type 0 related fileds.
Signed-off-by: Bo Chang Ke <bo-changx.ke@intel.com>

ShellPkg: Update smbiosview type 0 with SMBIOS 3.5 fields

---

OvmfPkg/IntelTdx/README

RFC: https://bugzilla.tianocore.org/show_bug.cgi?id=3249
Add README for TDVF.
Cc: Brijesh Singh <brijesh.singh@amd.com>

OvmfPkg: Add README for TDVF

---

MdeModulePkg/Include/UniversalPayload/UniversalPayload.h
UefiPayloadPkg/UniversalPayloadBuild.py

Align Identifier value with UPL spec "2.12.2. Universal Payload Information Section"

---

IntelFsp2Pkg/Tools/ConfigEditor/ConfigEditor.py
IntelFsp2Pkg/Tools/ConfigEditor/GenYamlCfg.py

BZ: https://bugzilla.tianocore.org/show_bug.cgi?id=3921
This patch adds a couple of fields supported in FSP 2.3 header from
both header generation and tool support perspective.

IntelFsp2Pkg: Add FSP 2.3 header support

---

OvmfPkg/IntelTdx/PrePiHobListPointerLibTdx/PrePiHobListPointer.c
OvmfPkg/IntelTdx/PrePiHobListPointerLibTdx/PrePiHobListPointerLibTdx.inf
SecurityPkg/Library/HashLibTdx/HashLibTdx.c

Fix two TDVF issues

---

BaseTools/Source/Python/Ecc/c.py

Signed-off-by: Rebecca Cran <quic_rcran@quicinc.com>

BaseTools/Ecc: Fix grammar in Ecc error message

---

OvmfPkg/PlatformCI/.azurepipelines/Ubuntu-GCC5.yml
OvmfPkg/PlatformCI/IntelTdxBuild.py

Add build test for OvmfPkg/IntelTdx
Cc: Jiewen Yao <Jiewen.yao@intel.com>
Cc: Ard Biesheuvel <ardb@kernel.org>

OvmfPkg/PlatformCI: add IntelTdxBuild.py

---

MdePkg/Include/IndustryStandard/DmaRemappingReportingTable.h

Updated DMAR definitions accordingly to changes in Intel(R) Virtualization
Technology for Directed I/O (VT-D) Architecture Specification ver4.0.
Added new definition of remapping structure - SIDP. The SoC Integrated
Device Property (SIDP) reporting structure identifies devices that have
special properties and that may put restrictions on how system software
must configure remapping structures that govern such devices in a platform
where remapping hardware is enabled.
Updated DRHD definition - field 'reserved' is replaced with 'Size'.
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3978
Signed-off-by: Robert Kowalewski <robert.kowalewski@intel.com>
Cc: …

MdePkg/include: Update DMAR definitions to Intel VT-d spec ver4.0

---

IntelFsp2Pkg/FspSecCore/SecFsp.c
IntelFsp2Pkg/FspSecCore/SecFsp.h
IntelFsp2Pkg/FspSecCore/SecMain.c
IntelFsp2Pkg/FspSecCore/SecMain.h
UefiCpuPkg/SecCore/SecMain.c
UefiCpuPkg/SecCore/SecMain.h

Secidttable size2

---

Maintainers.txt

Signed-off-by: Nate DeSimone <nathaniel.l.desimone@intel.com>

Maintainers.txt: Add IntelFsp2*Pkg Maintainer

---

Maintainers.txt

Cc: Anthony Perard <[anthony.perard@citrix.com](mailto:anthony.perard@citrix.com)>
Cc: Julien Grall <[julien@xen.org](mailto:julien@xen.org)>
Cc: Daniel Schaefer <[daniel.schaefer@hpe.com](mailto:daniel.schaefer@hpe.com)>
Cc: Sean Rhodes <[sean@starlabs.systems](mailto:sean@starlabs.systems)>
Cc: Debkumar De <[debkumar.de@intel.com](mailto:debkumar.de@intel.com)>
Cc: Erdem Aktas <[erdemaktas@google.com](mailto:erdemaktas@google.com)>
Cc: Harry Han <[harry.han@intel.com](mailto:harry.han@intel.com)>
Cc: Gary Lin <[gary.lin@hpe.com](mailto:gary.lin@hpe.com)>
Cc: Andrew Fish <[afish@apple.com](mailto:afish@apple.com)>
Cc: Leif Lindholm <[quic_llindhol@quicinc.com](mailto:quic_llindhol@quicinc.com)>
Signed-off-by: Michael D Kinney <[michael.d.kinney@intel.com](mailto:michael.d.kinney@intel.com …

Maintainers txt updates

---

SecurityPkg/Library/Tpm2DeviceLibDTpm/Tpm2Ptp.c

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3980
As per TCG PC Client Device Driver Design Principle document,
if tpm commands fails due to timeout condition, then it should
have retry mechanism (3 retry attempts).
Existing implementation of PtpCrbTpmCommand does not have retry
mechanism if it fails with EFI_TIMEOUT.
See TCG PC Client Device Driver Design Principles for TPM 2.0
https://trustedcomputinggroup.org/wp-content/uploads/TCG_PCClient_Device_Driver_Design_Principles_TPM2p0_v1p1_r4_211104_final.pdf
Vision 1.1, Revision 0.04
Section 7.2.1
Signed-off-by: Qi Zhang <qi1.zhang@intel.com>
Tested-by: Swapnil Patil <S.Keshavrao.Patil@dell.com>

SecurityPkg: Add retry mechanism for tpm command

---

BaseTools/Source/C/GenSec/GenSec.c
BaseTools/Source/C/VolInfo/VolInfo.c

BaseTools/VolInfo: Show FV section boundaries
BaseTools/VolInfo: Parse EFI_SECTION_FREEFORM_SUBTYPE_GUID header
BaseTools/GenSec: Support EFI_SECTION_FREEFORM_SUBTYPE_GUID sections

Support EFI_SECTION_FREEFORM_SUBTYPE_GUID sections

---

MdeModulePkg/Bus/Pci/PciBusDxe/PciLib.c

Ref:https://bugzilla.tianocore.org/show_bug.cgi?id=4000
Change flow to bus scan all root bridge instances even when any
one root bridge meet bus resource OUT_OF_RESOURCE case.
thus platform handler  of "EfiPciHostBridgeEndBusAllocation" has
an chance to do relative pci bus rebalance to handle this case.
Signed-off-by: Foster Nong <foster.nong@intel.com>

MdeModulePkg: Enhance bus scan for all root bridge instances

---

MdeModulePkg/Core/DxeIplPeim/X64/VirtualMemory.c
UefiCpuPkg/PiSmmCpuDxeSmm/Ia32/PageTbl.c
UefiCpuPkg/PiSmmCpuDxeSmm/PiSmmCpuDxeSmm.h
UefiCpuPkg/PiSmmCpuDxeSmm/SmmCpuMemoryManagement.c
UefiCpuPkg/PiSmmCpuDxeSmm/X64/PageTbl.c
UefiPayloadPkg/UefiPayloadEntry/X64/VirtualMemory.c

UefiCpuPkg/PiSmmCpuDxeSmm: Add a new mIsShadowStack flag
UefiCpuPkg/PiSmmCpuDxeSmm: Remove mInternalCr3 in PiSmmCpuDxeSmm
MdeModulePkg/DxeIpl: Remove clearing CR0.WP when protecting pagetable
UefiPayloadPkg: Remove clearing CR0.WP when protecting pagetable

UefiCpuPkg/PiSmmCpuDxeSmm: Remove mInternalCr3 in PiSmmCpuDxeSmm

---

MdePkg/Include/IndustryStandard/SmBios.h
ShellPkg/Library/UefiShellDebug1CommandsLib/SmbiosView/PrintInfo.c

Created Pull Request for below Smbios Issues.
Improved Smbios Type 9 table and Smbios Spec v3.5.0 changes.(Files: MdePkg-SmBios.h, ShellPkg-PrintInfo.c)
Added support for SMBIOS spec v3.6.0 to SmBios.h(File: MdePkg-SmBios.h)
Please help to review and merge to stable tag.
https://bugzilla.tianocore.org/show_bug.cgi?id=3607
https://bugzilla.tianocore.org/show_bug.cgi?id=3843
https://bugzilla.tianocore.org/show_bug.cgi?id=3972
CC: Vasudevan Sambandan [vasudevans@ami.com](mailto:vasudevans@ami.com)
CC: Sundaresan S [sundaresans@ami.com](mailto:sundaresans@ami.com)
Signed-off-by: Sainadh Nagolu [sainadhn@ami.com](mailto:sainadhn@ami.com)

Edk2SmbiosPatchPullRequest

---

ShellPkg/Library/UefiShellAcpiViewCommandLib/Parsers/Madt/MadtParser.c

Parse Type 0 or Local APIC structure.
Also parse the Local APIC Flags as bitfields.
Signed-off-by: Abdul Lateef Attar <abdattar@amd.com>

ShellPkg: Adds Local APIC parser to AcpiView

---

Maintainers.txt

Add James Lu as UefiPayloadPkg maintainer.
Add Gua Guo as universal payload reviewer.

Maintainers.txt: Update Maintainers/reviewers for universal payload

---

DynamicTablesPkg/Library/Acpi/Arm/AcpiSsdtCpuTopologyLibArm/SsdtCpuTopologyGenerator.c

Current code will generate duplicate UID if there are nested processor
containers in the topology. For example if there is a
socket/cluster/core layout.
Change references to processor container from cluster to be more
accurate on what is being created.

DynamicTablesPkg: Fix nested processor containers

---

BaseTools/Source/C/GenFw/Elf64Convert.c

Rebecca reports that builds of AArch64 DSCs that involve PIE linking when using ELF based toolchains are failing in some cases, resulting in an error message like
bad definition for symbol '_GLOBAL_OFFSET_TABLE_'@0x72d8 or
unsupported symbol type.  For example, absolute and undefined symbols
are not supported.
The reason turns out to be that, while GenFw does carry some logic to convert GOT based symbol references into direct ones (which is always possible given that our ELF to PE/COFF conversion only supports fully linked executables), it does not support all possible combinations of relocations that the linker may emit to load symbol addresses from the GOT.
In particular, when performing a non-LTO link on object code built with GCC using -fpie, we may end up with GOT based references …

BaseTools/GenFw AARCH64: Convert more types of explicit GOT references

---

ArmPlatformPkg/Drivers/NorFlashDxe/NorFlashBlockIoDxe.c
DynamicTablesPkg/Library/Acpi/Arm/AcpiPpttLibArm/PpttGenerator.c
FatPkg/FatPei/Gpt.c
MdeModulePkg/Bus/Pci/NvmExpressPei/NvmExpressPei.c
MdeModulePkg/Bus/Pci/SdMmcPciHcDxe/SdMmcPciHci.c
MdeModulePkg/Bus/Usb/UsbBusDxe/UsbEnumer.c
MdeModulePkg/Core/Dxe/Image/Image.c
MdeModulePkg/Library/DisplayUpdateProgressLibGraphics/DisplayUpdateProgressLibGraphics.c
MdeModulePkg/Universal/CapsulePei/UefiCapsule.c
NetworkPkg/TcpDxe/SockInterface.c
OvmfPkg/Csm/LegacyBootManagerLib/LegacyBm.c
RedfishPkg/RedfishDiscoverDxe/RedfishDiscoverDxe.c
RedfishPkg/RedfishHostInterfaceDxe/RedfishHostInterfaceDxe.c
RedfishPkg/RedfishRestExDxe/RedfishRestExProtocol.c
SecurityPkg/Library/SmmTcg2PhysicalPresenceLib/MmTcg2PhysicalPresenceLibCommon.c

v1 series: https://edk2.groups.io/g/devel/message/92053
v2 series: https://edk2.groups.io/g/devel/message/92786
v3 (current) series: https://edk2.groups.io/g/devel/message/93104

Fix Debug Macros Patch Series

---

Maintainers.txt

Remove Bret Barkelew from:
- .azurepipelines
- .mergify
- .pytool
- UnitTestFrameworkPkg
Add Michael Kubacki to:
- .azurepipelines
- .pytool
Signed-off-by: Bret Barkelew <bret.barkelew@microsoft.com>

Maintainers.txt: Update maintainers/reviewers for CI and Test

---

EmbeddedPkg/Library/PrePiMemoryAllocationLib/MemoryAllocationLib.c

Update check for enough space to occur prior to alignment offset. This prevents cases where EfiFreeMemoryTop < EfiFreeMemoryBottom.

EmbeddedPkg/PrePi: Check for enough space before aligning heap pointer

---

CryptoPkg/CryptoPkg.dec
CryptoPkg/CryptoPkg.dsc
CryptoPkg/Driver/Crypto.c
CryptoPkg/Include/Library/BaseCryptLib.h
CryptoPkg/Include/Pcd/PcdCryptoServiceFamilyEnable.h
CryptoPkg/Library/BaseCryptLib/BaseCryptLib.inf
CryptoPkg/Library/BaseCryptLib/PeiCryptLib.inf
CryptoPkg/Library/BaseCryptLib/Pk/CryptEc.c
CryptoPkg/Library/BaseCryptLib/Pk/CryptEcNull.c
CryptoPkg/Library/BaseCryptLib/SmmCryptLib.inf
CryptoPkg/Library/BaseCryptLib/UnitTestHostBaseCryptLib.inf
CryptoPkg/Library/BaseCryptLibNull/BaseCryptLibNull.inf
CryptoPkg/Library/BaseCryptLibNull/Pk/CryptEcNull.c
CryptoPkg/Library/BaseCryptLibOnProtocolPpi/CryptLib.c
CryptoPkg/Private/Protocol/Crypto.h
CryptoPkg/Test/CryptoPkgHostUnitTest.dsc
CryptoPkg/Test/UnitTest/Library/BaseCryptLib/BaseCryptLibUnitTests.c
CryptoPkg/Test/UnitTest/Library/BaseCryptLib/EcTests.c
CryptoPkg/Test/UnitTest/Library/BaseCryptLib/TestBaseCryptLib.h
CryptoPkg/Test/UnitTest/Library/BaseCryptLib/TestBaseCryptLibHost.inf
CryptoPkg/Test/UnitTest/Library/BaseCryptLib/TestBaseCryptLibShell.inf

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3828
Review PR: https://github.com/tianocore/edk2/pull/3398
This patch sequence is used to add CryptEc library, which are wrapped
over OpenSSL. The implementation provides library functions for EFI
BaseCrypt protocol and EFI BaseCrypt Configuration Protocol.
All APIs passed unit test and fuzzing test, detail as:
1. Unit test:
The purpose of unit testing is to ensure that the function obtains the
expected result under specific input, that is, to ensure the correctness
of APIs.
All test case show in patch 3 :CryptoPkg/Test: Add unit test for CryptoEc.
2. Fuzzing test:
Various Fuzz Testing are employed across the all introduced APIs, and the
test is used AFL (2.52b) and Libfuzzer (clang+llvm-11.0.0) as the fuzzer,
based on HBFA.
Fuzzing …

CryptoPkg: Add EC support

---

OvmfPkg/Library/PeilessStartupLib/X64/VirtualMemory.c

PeilessStartupLib is running in SEC phase. In this phase global variable is not allowed to be modified. This patch moves mPageTablePool to stack and pass it as input parameter between functions.

OvmfPkg/PeilessStartupLib: move mPageTablePool to stack

---

UefiPayloadPkg/UniversalPayloadBuild.sh

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4071
Provide a wrapper which wrap UniversalPayloadBuild.py
Signed-off-by: VictorX Hsu <victorx.hsu@intel.com>

UefiPayloadPkg: Provide a wrapper for UniversalPayloadBuild.py

---

.azurepipelines/templates/pr-gate-build-job.yml
.pytool/CISettings.py
EmbeddedPkg/EmbeddedPkg.ci.yaml
EmbeddedPkg/EmbeddedPkg.dec
EmbeddedPkg/Include/Library/AcpiLib.h
EmbeddedPkg/Library/AcpiLib/AcpiLib.c

https://bugzilla.tianocore.org/show_bug.cgi?id=4046

Add EmbeddedPkg to edk2 CI

---

.azurepipelines/templates/pr-gate-build-job.yml
.pytool/CISettings.py
IntelFsp2Pkg/Include/Ppi/Variable.h
IntelFsp2Pkg/IntelFsp2Pkg.ci.yaml
IntelFsp2Pkg/Library/BaseFspDebugLibSerialPort/DebugLib.c
IntelFsp2Pkg/Library/BaseFspMultiPhaseLib/BaseFspMultiPhaseLib.inf
IntelFsp2Pkg/Library/BaseFspSwitchStackLib/FspSwitchStackLib.c
IntelFsp2WrapperPkg/IntelFsp2WrapperPkg.ci.yaml
IntelFsp2WrapperPkg/Library/BaseFspWrapperApiLib/FspWrapperApiLib.c
IntelFsp2WrapperPkg/Library/BaseFspWrapperApiLib/IA32/DispatchExecute.c
IntelFsp2WrapperPkg/Library/SecFspWrapperPlatformSecLibSample/SecRamInitData.c

https://bugzilla.tianocore.org/show_bug.cgi?id=4048

Add Intel FSP packages to edk2 CI (v2)

---

.azurepipelines/templates/pr-gate-build-job.yml
.pytool/CISettings.py
SignedCapsulePkg/SignedCapsulePkg.ci.yaml

https://bugzilla.tianocore.org/show_bug.cgi?id=4050

Add SignedCapsulePkg to edk2 CI

---

.azurepipelines/templates/pr-gate-build-job.yml
.pytool/CISettings.py
SourceLevelDebugPkg/Include/Library/DebugCommunicationLib.h
SourceLevelDebugPkg/Library/DebugAgent/DebugAgentCommon/DebugAgent.c
SourceLevelDebugPkg/Library/DebugAgent/DebugAgentCommon/DebugAgent.h
SourceLevelDebugPkg/Library/DebugAgent/DxeDebugAgent/SerialIo.c
SourceLevelDebugPkg/Library/DebugCommunicationLibSerialPort/DebugCommunicationLibSerialPort.c
SourceLevelDebugPkg/Library/DebugCommunicationLibUsb/DebugCommunicationLibUsb.c
SourceLevelDebugPkg/Library/DebugCommunicationLibUsb3/DebugCommunicationLibUsb3Internal.h
SourceLevelDebugPkg/Library/PeCoffExtraActionLibDebug/Ia32/IntHandlerFuncs.c
SourceLevelDebugPkg/Library/PeCoffExtraActionLibDebug/PeCoffExtraActionLib.h
SourceLevelDebugPkg/Library/PeCoffExtraActionLibDebug/X64/IntHandlerFuncs.c
SourceLevelDebugPkg/SourceLevelDebugPkg.ci.yaml

https://bugzilla.tianocore.org/show_bug.cgi?id=4091

Add SourceLevelDebugPkg to CI

---

CryptoPkg/Driver/Crypto.c
CryptoPkg/Include/Library/TlsLib.h
CryptoPkg/Include/Pcd/PcdCryptoServiceFamilyEnable.h
CryptoPkg/Library/BaseCryptLibOnProtocolPpi/CryptLib.c
CryptoPkg/Library/TlsLib/InternalTlsLib.h
CryptoPkg/Library/TlsLib/TlsConfig.c
CryptoPkg/Library/TlsLib/TlsProcess.c
CryptoPkg/Library/TlsLibNull/TlsConfigNull.c
CryptoPkg/Library/TlsLibNull/TlsProcessNull.c
CryptoPkg/Private/Protocol/Crypto.h
MdePkg/Include/IndustryStandard/Tls1.h

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3892
Review PR: https://github.com/tianocore/edk2/pull/3400
This patch sequence is used to extend Tls library, which are wrapped
over OpenSSL. The implementation provides library functions for EFI
DXE dirver and Protocol.
All APIs passed unit test and fuzzing test, detail as:
1. Unit test:
New Tls APIs tested on Intel platform as part of WIFI WPA3 feature.
2. Fuzzing test:
Various Fuzz Testing are employed across the all introduced APIs, and the
test is used AFL (2.52b) and Libfuzzer (clang+llvm-11.0.0) as the fuzzer,
based on HBFA.
Fuzzing Pass Rate is 100%;
The Code Coverage of new APIs is 91%.
All test case show in:
https://github.com/liyi77/edk2-staging/tree/HBFA/HBFA/UefiHostFuzzTestCasePkg/TestCase/CryptoPkg
V2 change:
Move the …

CryptoPkg: Extend Tls library

---

BaseTools/Source/C/Common/FirmwareVolumeBuffer.c
BaseTools/Source/C/DevicePath/DevicePathUtilities.c
BaseTools/Source/C/GenFv/GenFv.c
BaseTools/Source/C/VfrCompile/Pccts/antlr/mrhoist.c

In an effort to clean the documentation of the above package, remove duplicated words.

BaseTools: Remove duplicated words in C tools

---

IntelFsp2WrapperPkg/Library/FspWrapperMultiPhaseProcessLib/PeiFspWrapperMultiPhaseProcessLib.c

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4119
Earlier version of FSP header may not have MultiPhase fields present in the FspInfoHeader so the handler should verify header revision before accessing the MultiPhase fields from the header.

IntelFsp2WrapperPkg: Check header revision for MultiPhase support.

---

Maintainers.txt

Cc: Baoqi Zhang <zhangbaoqi@loongson.cn>
Cc: Dongyan Qian <qiandongyan@loongson.cn>
Signed-off-by: Chao Li <lichao@loongson.cn>

Maintainers.txt: Update maintainers and reviewers for LoongArch64

---

MdeModulePkg/Bus/Scsi/ScsiBusDxe/ScsiBus.c
MdeModulePkg/Bus/Scsi/ScsiDiskDxe/ScsiDisk.c
MdeModulePkg/Bus/Ufs/UfsBlockIoPei/DmaMem.c
MdeModulePkg/Bus/Ufs/UfsBlockIoPei/UfsHcMem.c

Fix the issues in Scsi and Ufs

MdeModulePkg: Fix the issues in Scsi and Ufs

---

OvmfPkg/Library/VmgExitLib/VmTdExitVeHandler.c

BZ: https://bugzilla.tianocore.org/show_bug.cgi?id=4125
EPT-violation #VE should be always on shared memory, which means the shared bit of the GuestPA should be set. But in current #VE Handler it is not checked. When it occurs, stop TD immediately and log out the error.
Reviewed-by: Guorui Yu <ruogui.ygr@alibaba-inc.com>
Tested-by: Guorui Yu <ruogui.ygr@alibaba-inc.com>

OvmfPkg/VmgExitLig: HALT on #VE when access to private memory

---

.github/codeql/codeql-config.yml
.github/codeql/edk2.qls
.github/workflows/codeql-analysis.yml
Maintainers.txt

https://bugzilla.tianocore.org/show_bug.cgi?id=4115

Enable CodeQL

---

.github/workflows/codeql-analysis.yml

Reviewed-by: Michael Kubacki <mikuback@linux.microsoft.com>

.github/workflows: Update CodeQL to install Python 3.10.6

---

UefiPayloadPkg/UefiPayloadEntry/UniversalPayloadEntry.c

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4164
To support multiple FVs provided by UPL
Signed-off-by: MarsX Lin <marsx.lin@intel.com>

UefiPayloadPkg: Support multiple firmware volume

---

MdeModulePkg/Bus/Ata/AtaAtapiPassThru/AhciMode.c

Patch sent at: https://edk2.groups.io/g/devel/message/95344
Bugzilla: https://bugzilla.tianocore.org/show_bug.cgi?id=4016
AtaAtapiPassThru driver was reporting recovery status on failed command packets which led to incorrect flows in upper layers and to SCT tests fails. This commit will change the logic to report command status.
Signed-off-by: Mateusz Albecki <mateusz.albecki@intel.com>

MdeModulePkg/Ata: Fix command status reporting

---

Maintainers.txt

Signed-off-by: Anthony PERARD <anthony.perard@citrix.com>

Maintainers.txt: Change Anthony's github id

---

OvmfPkg/PlatformPei/AmdSev.c

When running under SEV-ES, a page of shared memory is allocated for the GHCB during the SEC phase at address 0x809000. This page of memory is eventually passed to the OS as EfiConventionalMemory. When running SEV-SNP, this page is not PVALIDATE'd in the RMP table, meaning that if the guest OS tries to access the page, it will think that the host has voilated the security guarantees and will likely crash.
This patch validates this page immediately after EDK2 switches to using the GHCB page allocated for the PEI phase.
This was tested by writing a UEFI application that reads to and writes from one byte of each page of memory and checks to see if a #VC exception is generated indicating that the page was not validated.
Fixes: 6995a1b79bab ("OvmfPkg: Create a GHCB page for use during Sec …

OvmfPkg/PlatformPei: Validate SEC's GHCB page

---

.pytool/Readme.md
ArmVirtPkg/PlatformCI/ReadMe.md
BaseTools/ReadMe.rst
EmulatorPkg/PlatformCI/ReadMe.md
OvmfPkg/PlatformCI/ReadMe.md
OvmfPkg/README

Updates relevant docs to point to new instructions on the TianoCore wiki.

Update build instructions

---

UefiPayloadPkg/Library/BaseSerialPortLibHob/BaseSerialPortLibHob.c

Add condition to return success if mUartCount is greater than zero in SerialPortInitialize() to avoid filling mUartInfo with the same hob data when SerialPortInitialize() is called multiple times. Also add proper conditions in SerialPortRead function to read the data properly from multiple UART's.
Signed-off-by: Kavya <k.kavyax.sravanthi@intel.com>

UefiPayloadPkg/SerialPortLib: Enhance multi port behaviour

---

UefiCpuPkg/PiSmmCpuDxeSmm/SmmCpuMemoryManagement.c

When setting new page table pool to RO, only disable/enable WP when Cr0.WP has been set to 1 to fix potential PF caused by b822be1a20 (UefiCpuPkg/PiSmmCpuDxeSmm: Introduce page table pool mechanism). With previous code, if someone want to modify the page table and Cr0.WP has been cleared before modify page table, Cr0.WP may be set to 1 again since new pool may be generated during this process Then PF fault may happens.
Signed-off-by: Dun Tan <dun.tan@intel.com>

UefiCpuPkg/PiSmmCpuDxeSmm:Fix PF issue caused by smm page table code

---

MdePkg/Include/IndustryStandard/Nvme.h

MdePkg/Include/IndustryStandard: NVMe 2.0/RPMB  updates
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4303
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4304
Cc: Hao Wu <hao.a.wu@intel.com>
Signed-off-by: Weipu Zhu <weipu.zhu@intel.com>

Bz 4303 4304 nv me updates v2

---

OvmfPkg/RiscVVirt/Sec/Memory.c

M-mode firmware ranges should not be used by EDK2/OS. Currently, we search for mmode_resv0 node in FDT and mark it as the reserved memory in EFI memory map. However, if there are multiple M-mode firmware ranges, then this will miss those extra ranges allowing the OS to access the memory and hit a fault.
This issue is exposed since recent opensbi started creating two ranges for text and data.
Fix this by searching for all reserved memory nodes and marking them as reserved in the EFI memory map.
Reviewed-by: Andrei Warkentin <andrei.warkentin@intel.com>

OvmfPkg/RiscVVirt: Support multiple reserved memory ranges

---

ArmPkg/Universal/Smbios/SmbiosMiscDxe/Type00/MiscBiosVendorFunction.c

The BIOS Firmware Version in the SMBIOS Type 0 can be fetched from the fixed PcdFirmwareVersionString or platform specific OemMiscLib. In fact, the support from OemMiscLib comes into play when the firmware version may be modified at boot time for extended information. Therefore, the priority of getting the version from OemMiscLib should be higher.
In case there is no modification in the OemMiscLib, we have to keep HII string STR_MISC_BIOS_VERSION empty or 'Not Specified' to indicate that the firmware version should be fetched from the PcdFirmwareVersionString.
Reviewed-by: Oliver Smith-Denny <osd@smith-denny.com>

ArmPkg/SmbiosMiscDxe: Adjust the priority of getting firmware version

---

OvmfPkg/PlatformCI/PlatformBuildLib.py

Increase the chance that CI finds bugs in MP changes.

OvmfPkg/CI: Boot OVMF in SMP mode.

---

UefiPayloadPkg/UniversalPayloadBuild.py

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4386
Add additional input parameter support
--SpecRevision: user input spec version
--Revision: user input revision
--ProducerId: producer company name
1. UniversalPayloadBuild.py
2. Downgrade spec revision from 0.9 to 0.7

UefiPayloadPkg: Support more input parameter

---

.github/codeql/edk2.qls
BaseTools/Scripts/PatchCheck.py
BaseTools/Source/C/VfrCompile/Pccts/antlr/gen.c
BaseTools/Source/C/VfrCompile/Pccts/antlr/main.c
CryptoPkg/Library/BaseCryptLib/Pk/CryptX509.c
MdeModulePkg/Bus/Pci/PciBusDxe/PciIo.c
MdeModulePkg/Bus/Pci/UhciDxe/Uhci.c
MdeModulePkg/Core/Dxe/Mem/Page.c
MdeModulePkg/Library/BootMaintenanceManagerUiLib/BootOption.c
MdeModulePkg/Library/FileExplorerLib/FileExplorer.c
MdeModulePkg/Universal/BdsDxe/BdsEntry.c
MdeModulePkg/Universal/DisplayEngineDxe/ProcessOptions.c
MdeModulePkg/Universal/HiiDatabaseDxe/Font.c
MdeModulePkg/Universal/SmbiosDxe/SmbiosDxe.c
MdeModulePkg/Universal/Variable/RuntimeDxe/Variable.c
MdePkg/Library/BaseLib/String.c
NetworkPkg/Library/DxeHttpLib/DxeHttpLib.c
NetworkPkg/TcpDxe/TcpInput.c
PcAtChipsetPkg/PcatRealTimeClockRuntimeDxe/PcRtc.c
ShellPkg/Application/Shell/Shell.c
ShellPkg/Application/Shell/ShellProtocol.c
ShellPkg/Library/UefiShellCommandLib/UefiShellCommandLib.c
ShellPkg/Library/UefiShellDebug1CommandsLib/Dblk.c
ShellPkg/Library/UefiShellDebug1CommandsLib/EfiDecompress.c
ShellPkg/Library/UefiShellDriver1CommandsLib/Connect.c
ShellPkg/Library/UefiShellDriver1CommandsLib/Disconnect.c
ShellPkg/Library/UefiShellDriver1CommandsLib/DrvDiag.c
UefiCpuPkg/CpuMpPei/CpuBist.c
UefiCpuPkg/CpuMpPei/CpuMpPei.c
UefiCpuPkg/CpuMpPei/CpuPaging.c

Enable New CodeQL Queries - CWE 120, 457, 676, 758, 787, 805

---

UefiPayloadPkg/UniversalPayloadBuild.py

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4375
add '-pb' command of build bios with exist PreUniversalPayload file.
'-e'  command of olny build the UniversalPayloadentry file.

UefiPayloadPkg:Add new build commands for UniversalPayload

---

Maintainers.txt

Reviewed-by: Peter Grehan <grehan@freebsd.org>
Cc: devel@edk2.groups.io

Maintainer.txt: add myself as reviewer for bhyve's OvmfPkg

---

MdePkg/Include/IndustryStandard/PldmSmbiosTransfer.h

BZ #4396
This change adds definitions for DMTF PLDM
SMBIOS Transfer specification.
Spec ref:
https://www.dmtf.org/sites/default/files/standards/documents/DSP0246_1.0.1.pdf
Cc: Isaac Oram <isaac.w.oram@intel.com>

MdePkg/Include: Add DMTF PLDM SMBIOS definitions

---

.azurepipelines/templates/defaults.yml
BaseTools/Plugin/HostBasedUnitTestRunner/HostBasedUnitTestRunner.py

If code coverage exist failure, CI/CD need to catch it

BaseTools/Plugin: Report error if code coverage failure

---

RedfishPkg/Include/Library/HiiUtilityLib.h
RedfishPkg/Include/Library/RedfishPlatformConfigLib.h
RedfishPkg/Include/Protocol/EdkIIRedfishPlatformConfig.h
RedfishPkg/Library/HiiUtilityLib/HiiExpression.c
RedfishPkg/Library/HiiUtilityLib/HiiExpression.h
RedfishPkg/Library/HiiUtilityLib/HiiIfrParse.c
RedfishPkg/Library/HiiUtilityLib/HiiInternal.h
RedfishPkg/Library/HiiUtilityLib/HiiUtilityInternal.c
RedfishPkg/Library/HiiUtilityLib/HiiUtilityLib.c
RedfishPkg/Library/HiiUtilityLib/HiiUtilityLib.inf
RedfishPkg/Library/RedfishPlatformConfigLib/RedfishPlatformConfigInternal.h
RedfishPkg/Library/RedfishPlatformConfigLib/RedfishPlatformConfigLib.c
RedfishPkg/Library/RedfishPlatformConfigLib/RedfishPlatformConfigLib.inf
RedfishPkg/Redfish.fdf.inc
RedfishPkg/RedfishComponents.dsc.inc
RedfishPkg/RedfishLibs.dsc.inc
RedfishPkg/RedfishPkg.dec
RedfishPkg/RedfishPkg.dsc
RedfishPkg/RedfishPlatformConfigDxe/RedfishPlatformConfigDxe.c
RedfishPkg/RedfishPlatformConfigDxe/RedfishPlatformConfigDxe.h
RedfishPkg/RedfishPlatformConfigDxe/RedfishPlatformConfigDxe.inf
RedfishPkg/RedfishPlatformConfigDxe/RedfishPlatformConfigImpl.c
RedfishPkg/RedfishPlatformConfigDxe/RedfishPlatformConfigImpl.h

Introduce EDKII Redfish Platform Config Protocol and corresponding libraries. This protocol is the interface between UEFI platform configuration and Redfish property. It could handle different firmware implementation and the implementation here is to map EDK2 HII questions to the properties defined in Redfish schema. So that user can configure UEFI platform configuration through RESTful interface provided by BMC.

Introduce EDKII Redfish Platform Config Protocol v3

---

SecurityPkg/Library/Tpm12DeviceLibDTpm/Tpm12Tis.c
SecurityPkg/Library/Tpm2DeviceLibDTpm/Tpm2Ptp.c

Gerd Hoffmann (2):
SecurityPkg: add TIS sanity check (tpm2)
SecurityPkg: add TIS sanity check (tpm12)
SecurityPkg/Library/Tpm12DeviceLibDTpm/Tpm12Tis.c | 6 +++++-
SecurityPkg/Library/Tpm2DeviceLibDTpm/Tpm2Ptp.c   | 6 +++++-
2 files changed, 10 insertions(+), 2 deletions(-)

SecurityPkg: add TIS sanity check

---

Maintainers.txt

Add more maintainers and reviewers for these 2 packages.
Cc: Chen Gang C <gang.c.chen@intel.com>
Reviewed-by: Duggapu Chinni B <chinni.b.duggapu@intel.com>
Reviewed-by: Ng Ray Han Lim <ray.han.lim.ng@intel.com>
Reviewed-by: Chen Gang C <gang.c.chen@intel.com>
Reviewed-by: Kuo Ted <ted.kuo@intel.com>
Reviewed-by: Mohapatra Susovan <susovan.mohapatra@intel.com>
Reviewed-by: S Ashraf Ali <ashraf.ali.s@intel.com>

Maintainers.txt: Update for IntelFsp2Pkg and IntelFsp2WrapperPkg.

---

MdePkg/Library/BasePeCoffLib/BasePeCoff.c

Older versions of GenFw put the wrong value in the debug directory size field in the PE/COFF header: instead of putting the combined size of all the entries, it puts the size of the only entry it creates, but adds the size of the NB10 payload that the entry points to. This confuses the loader now that we started using additional debug directory entries to describe DLL characteristics.
GenFw was fixed in commit 60e85a39fe49071, but the binaries that were generated with it still need to be supported.
So let's detect this condition, and check whether the size of the debug directory is consistent with the NB10 payload: if we should expect additional directory entries where we observe the NB10 payload, the size field is clearly wrong, and we can break from the loop.
BZ: …

MdePkg/BasePeCoffLib: Deal with broken debug directories

---

MdeModulePkg/MdeModulePkg.dec
MdeModulePkg/Test/MdeModulePkgHostTest.dsc
MdeModulePkg/Test/Mock/Include/GoogleTest/Library/MockPciHostBridgeLib.h
MdeModulePkg/Test/Mock/Library/GoogleTest/MockPciHostBridgeLib/MockPciHostBridgeLib.cpp
MdeModulePkg/Test/Mock/Library/GoogleTest/MockPciHostBridgeLib/MockPciHostBridgeLib.inf
MdePkg/Test/MdePkgHostTest.dsc
MdePkg/Test/Mock/Include/GoogleTest/Library/MockHobLib.h
MdePkg/Test/Mock/Include/GoogleTest/Library/MockPeiServicesLib.h
MdePkg/Test/Mock/Library/GoogleTest/MockHobLib/MockHobLib.cpp
MdePkg/Test/Mock/Library/GoogleTest/MockHobLib/MockHobLib.inf
MdePkg/Test/Mock/Library/GoogleTest/MockPeiServicesLib/MockPeiServicesLib.cpp
MdePkg/Test/Mock/Library/GoogleTest/MockPeiServicesLib/MockPeiServicesLib.inf

V3
Remove EBC and fix some coding rule
V2:
Fixed Azure build failure
V1:
Add google mock support for HobLib
Add google mock support for PciHostBridgeLib Add google mock support for PeiServicesLib

MdePkg/MdeModulePkg: Add More GoogleMock Library support

---

MdePkg/Include/IndustryStandard/IpmiNetFnApp.h
MdePkg/Include/IndustryStandard/IpmiSsif.h
MdePkg/MdePkg.dec

Add definitions for IPMI SSIF

---

MdePkg/Include/IndustryStandard/SmBios.h
ShellPkg/Library/UefiShellDebug1CommandsLib/SmbiosView/PrintInfo.c
ShellPkg/Library/UefiShellDebug1CommandsLib/SmbiosView/SmbiosView.c

BZ: https://bugzilla.tianocore.org/show_bug.cgi?id=3805

Smbios64BitPrintEPSInfo hit a stack guard exception due to buffer overflow

---

Maintainers.txt

Update reviewers and maintainers for FdtLib.
Cc: Benny Lin <benny.lin@intel.com>

Maintainers.txt: Update reviewers and maintainers for FdtLib.

---

pip-requirements.txt

- edk2-pytool-library: 0.14.0 to 0.14.1
- edk2-pytool-extensions: 0.21.8 to 0.23.2
- edk2-basetools: 0.1.43 to 0.1.48

pip-requirements.txt: Update edk2 pip modules

---

RedfishPkg/Include/Library/RedfishDebugLib.h
RedfishPkg/Library/PlatformHostInterfaceBmcUsbNicLib/PlatformHostInterfaceBmcUsbNicLib.c
RedfishPkg/Library/RedfishPlatformCredentialIpmiLib/RedfishPlatformCredentialIpmiLib.c
RedfishPkg/PrivateLibrary/RedfishCrtLib/RedfishCrtLib.c
RedfishPkg/PrivateLibrary/RedfishLib/RedfishLib.c
RedfishPkg/PrivateLibrary/RedfishLib/edk2libredfish/src/service.c
RedfishPkg/RedfishConfigHandler/RedfishConfigHandlerCommon.c
RedfishPkg/RedfishConfigHandler/RedfishConfigHandlerDriver.c
RedfishPkg/RedfishDiscoverDxe/RedfishDiscoverDxe.c
RedfishPkg/RedfishHostInterfaceDxe/RedfishHostInterfaceDxe.c
RedfishPkg/RedfishRestExDxe/RedfishRestExImpl.c
RedfishPkg/RedfishRestExDxe/RedfishRestExProtocol.c

Use debug print level DEBUG_MANAGEABILITY in
RedfishPkg.
Reviewed-by: Nickle Wang <nicklew@nvidia.com>

RedfishPkg: Use DEBUG_MANAGEABILITY

---

OvmfPkg/Library/BaseMemEncryptSevLib/X64/PeiDxeVirtualMemory.c

Edk2 was failing, rather than creating more PML4 entries, when they weren't present in the initial memory acceptance flow. Because of that VMs with more than 512G memory were crashing. This code fixes that.
This change affects only SEV-SNP VMs.
The code was tested by successfully booting a 512G SEV-SNP VM.
Acked-by: Tom Lendacky <thomas.lendacky@amd.com>

OvmfPkg: Create additional PML1 entries for large SEV-SNP VMs

---

Maintainers.txt

Cc: Jiewen Yao <jiewen.yao@intel.com> [jyao1]
Cc: Yi Li <yi1.li@intel.com> [liyi77]
Cc: Xiaoyu Lu <xiaoyu1.lu@intel.com> [xiaoyuxlu]
Cc: Guomin Jiang <guomin.jiang@intel.com> [guominjia]
Reviewed-by: Jiewen.yao@intel.com

Maintainers.txt: update maintainer for CryptoPkg

---

Maintainers.txt

Add Zack, Saloni and remove unused IDs
Cc: Zachary Clark-willilams <zachary.clark-williams@intel.com>
Reviewed-by: Zachary Clark-willilams <zachary.clark-williams@intel.com>

Maintainers.txt: Update NetworkPkg maintainers and reviewers

---

NetworkPkg/WifiConnectionManagerDxe/WifiConnectionMgrImpl.c

FIX: https://bugzilla.tianocore.org/show_bug.cgi?id=4477
Tls connection fail over WiFi in AMT OCR flow due to invalid identity.
This was due to missing conversion between unicode and ascii string which resulted in invalid strlen.
Cc: Zachary Clark-Williams <zachary.clark-williams@intel.com>
Reviewed-by: Zachary Clark-Williams <zachary.clark-williams@intel.com>

NetworkPkg: Correct the length of EAP Identity when in ASCII format

---

OvmfPkg/IoMmuDxe/IoMmuBuffer.c

Searching for an unused bounce buffer in mReservedMemBitmap and reserving the buffer by flipping the bit is a critical section which must not be interrupted.  Raise the TPL level to ensure that.
Without this fix it can happen that IoMmuDxe hands out the same bounce buffer twice, causing trouble down the road.  Seen happening in practice with VirtioNetDxe setting up the network interface (and calling into IoMmuDxe from a polling timer callback) in parallel with Boot Manager doing some disk I/O.  An ASSERT() in VirtioNet caught the buffer inconsistency.
Full story with lots of details and discussions is available here: https://bugzilla.redhat.com/show_bug.cgi?id=2211060

OvmfPkg/IoMmuDxe: add locking to IoMmuAllocateBounceBuffer

---

CryptoPkg/Library/OpensslLib/OpensslLib.inf
CryptoPkg/Library/OpensslLib/OpensslLibAccel.inf
CryptoPkg/Library/OpensslLib/OpensslLibCrypto.inf
CryptoPkg/Library/OpensslLib/OpensslLibFull.inf
CryptoPkg/Library/OpensslLib/OpensslLibFullAccel.inf

CryptoPkg/OpensslLib: Upgrade OpenSSL to 1.1.1u

---

ArmPkg/Library/DefaultExceptionHandlerLib/AArch64/DefaultExceptionHandler.c
ArmPkg/Library/DefaultExceptionHandlerLib/Arm/DefaultExceptionHandler.c

If gST->ConOut is available when Arm's DefaultExceptionHandler is running, AsciiPrint will get called to attempt to print to ConOut, in addition to the serial output.
AsciiPrint calls AsciiInternalPrint in UefiLibPrint.c which in turn calls AllocatePool to allocate a buffer to convert the Ascii input string to a Unicode string to pass to ConOut->OutputString.
Per the comment on DefaultExceptionHandler, we should not be allocating memory in the exception handler, as this can cause the exception handler to fail if we had a memory exception or the system state is such that we cannot allocate memory.
It has been observed on ArmVirtQemu that exceptions generated in the memory handling code will fail to output the stack dump and CPU state that is critical to debugging because the AllocatePool …

ArmPkg: DefaultExceptionHandlerLib: Do Not Allocate Memory

---

UefiPayloadPkg/UniversalPayloadBuild.py

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4532
To Copy the PrebuildUplBinary to Build folder then add/replace Fvs.

UefiPayloadPkg:Enhance the build processing for Universalpayload

---

IntelFsp2Pkg/Tools/SplitFspBin.py

https://bugzilla.tianocore.org/show_bug.cgi?id=4502 Update SplitFspBin.py to support child FV in FSP binary. Without the patch, the tool won't be able to rebase the images in child FV in FSP binary.
Cc: Chinni B Duggapu <chinni.b.duggapu@intel.com>

IntelFsp2Pkg: Support child FV in SplitFspBin.py

---

MdePkg/Include/IndustryStandard/SmBios.h
ShellPkg/Library/UefiShellDebug1CommandsLib/SmbiosView/QueryTable.c

Add ProcessorUpgradeSocket definitions

Add ProcessorUpgradeSocket definitions

---

OvmfPkg/README

Add the new section for Secure Boot.

OvmfPkg/README: Document Secure Boot

---

NetworkPkg/HttpBootDxe/HttpBootClient.h
NetworkPkg/HttpDxe/HttpProto.c
NetworkPkg/HttpDxe/HttpProto.h

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4505 This gives something like ~3 fold throughput boost.
Cc: Saloni Kasbekar <saloni.kasbekar@intel.com>
Cc: Zachary Clark-williams <zachary.clark-williams@intel.com>
Reviewed-by: Saloni Kasbekar <saloni.kasbekar@intel.com>

NetworkPkg: Increase HTTP buffer size and enable TCP window scaling

---

Maintainers.txt

Update reviewers and maintainers for DynamicTablesPkg
Reviewed-by: Alexei Fedorov <Alexei.Fedorov@arm.com>

Maintainers.txt: Update reviewers and maintainers for DynamicTablesPkg

---

MdeModulePkg/Core/DxeIplPeim/Ia32/DxeLoadFunc.c

MdeModulePkg: Fix misspelling

---

OvmfPkg/VirtioFsDxe/SimpleFsOpen.c

https://edk2.groups.io/g/devel/message/109768
https://listman.redhat.com/archives/edk2-devel-archive/2023-October/069068.html
http://mid.mail-archive.com/20231018172434.91280-1-lersek@redhat.com
~~~
Referring to a file relative to a regular file makes no sense (or at least
it cannot be implemented consistently with how a file is referred to
relative to a directory). VirtioFsSimpleFileOpen() has enforced this
strictly since the beginning, and a few months ago I reported USWG Mantis
ticket #2367 [1] too, for clearing up the related confusion in the UEFI
spec.
Unfortunately, the shim boot loader contains such a bug [2] [3]. I don't
believe the shim bug is ever going to be fixed. We can however relax the
check in VirtioFsSimpleFileOpen() a bit: if the pathname that's being
opened relative to …

[PATCH] OvmfPkg/VirtioFsDxe: tolerate opening an abs. pathname rel. to a reg. file -- push

---

Maintainers.txt

Remove my name from reviewer list of following modules:
* MdeModulePkg: Console and Graphics modules
* MdeModulePkg: Reset modules
* MdeModulePkg: Serial modules
* MdeModulePkg: Universal Payload definitions

Maintainers.txt: Stop to be reviewer of several modules

---

RedfishPkg/RedfishPlatformConfigDxe/RedfishPlatformConfigDxe.c

Add debug prints to show HII option name when assert happens. This helps developer to debug assert issue easily while Redfish failed to convert HII value to Redfish value.

RedfishPkg/RedfishPlatformConfigDxe: add debug message.

---

DynamicTablesPkg/Readme.md

Update the DynamicTablesPkg documentation to explain how to specify ACPI tables in RAW format, or when there are no defined table generators.
Cc: Samer El-Haj-Mahmoud <samer.el-haj-mahmoud@arm.com>

DynamicTablesPkg: HOWTO for Handcrafted tables

---

Maintainers.txt
OvmfPkg/AcpiPlatformDxe/CloudHvAcpi.c
UefiCpuPkg/Library/BaseXApicX2ApicLib/BaseXApicX2ApicLib.c

* v2 UefiCpuPkg/BaseXApicX2ApicLib: fix CPUID_V2_EXTENDED_TOPOLOGY detection
http://mid.mail-archive.com/20231017112807.1244254-1-kraxel@redhat.com
https://edk2.groups.io/g/devel/message/109672
* v2 OvmfPkg/AcpiPlatformDxe: Fix Coverity report issues
https://bugzilla.tianocore.org/show_bug.cgi?id=4568
http://mid.mail-archive.com/20231023090539.1003-1-cepingx.sun@intel.com
https://edk2.groups.io/g/devel/message/109905
* Maintainers.txt: Update maintainers list
http://mid.mail-archive.com/20231019054328.427-2-abner.chang@amd.com
https://edk2.groups.io/g/devel/message/109790

patch queue 2023-Oct-25

---

MdeModulePkg/Include/Library/IpmiCommandLib.h
MdePkg/Include/IndustryStandard/IpmiNetFnApp.h

Definitions of IPMI NetFnApp 0x57 command

Ipmi_NetFnApp_0x57

---

UefiPayloadPkg/Tools/MkFitImage.py
UefiPayloadPkg/UniversalPayloadBuild.py

MultiImage[Index] should be deleted if fv path of MultiImage[Index] not exist.

UefiPayloadPkg: Fix incorrect code on MkFitImage.py

---

.pytool/Plugin/HostUnitTestDscCompleteCheck/HostUnitTestDscCompleteCheck.py
.pytool/Plugin/UncrustifyCheck/UncrustifyCheck.py
BaseTools/Plugin/DebugMacroCheck/BuildPlugin/DebugMacroCheckBuildPlugin.py
pip-requirements.txt

https://edk2.groups.io/g/devel/message/110215
http://mid.mail-archive.com/20231027151551.1043941-1-joeyvagedes@microsoft.com
https://listman.redhat.com/archives/edk2-devel-archive/2023-October/069516.html
~~~
Upgrades edk2-pytool-library to v0.19.3 and edk2-pytool-extensions to v0.25.1
and performs all necessary integrations as noted in the individual package
commits.
Cc: Sean Brogan [<sean.brogan@microsoft.com>](mailto:sean.brogan@microsoft.com)
Cc: Michael Kubacki [<mikuback@linux.microsoft.com>](mailto:mikuback@linux.microsoft.com)
Cc: Michael D Kinney [<michael.d.kinney@intel.com>](mailto:michael.d.kinney@intel.com)
Cc: Liming Gao [<gaoliming@byosoft.com.cn>](mailto:gaoliming@byosoft.com.cn)
Joey Vagedes (2):
.pytool: Integration of edk2-pytools
BaseTools: Plugin: Integration of …

[PATCH v1 0/2] Upgrade edk2-pytools to latest -- push

---

UefiCpuPkg/Library/MpInitLib/MpHandOff.h

https://edk2.groups.io/g/devel/message/109382
http://mid.mail-archive.com/20231007063203.936-1-yuanhao.xie@intel.com
https://listman.redhat.com/archives/edk2-devel-archive/2023-October/068682.html
~~~
Signed-off-by: Yuanhao Xie <yuanhao.xie@intel.com>
---
UefiCpuPkg/Library/MpInitLib/MpHandOff.h | 5 ++++-
1 file changed, 4 insertions(+), 1 deletion(-)
~~~

[PATCH] UefiCpuPkg: Correct file description for MpHandOff header file -- push

---

Maintainers.txt

Over the past few months, all the of the Maintainers and Reviewers listed in Maintainers.txt have been contacted to make sure Maintainers.txt accurately represents the TianoCore community members that are actively participating in their roles.  Based on specific feedback, bounced emails, and no responses, updates have been made.
* RISCV64: Daniel Schaefer replaced with Andrei Warkentin
* ArmVirtPkg Xen has no remaining reviewers and review responsibility defaults to ArmVirtPkg Maintainers/Reviewers.
* ACPI modules related to S3 has no remaining reviewers and review responsibility defaults to MdeModulePkg Maintainers/ Reviewers.
* OVMF CSM modules has no remaining reviewers and review responsibility defaults to OvmfPkg Maintainers/Reviewers.
* Bounce: Chan Laura <laura.chan@intel.com>
* …

Maintainers.txt: Update based on active community members

---

MdeModulePkg/Library/DxeCorePerformanceLib/DxeCorePerformanceLib.c
ShellPkg/DynamicCommand/DpDynamicCommand/Dp.c
ShellPkg/DynamicCommand/DpDynamicCommand/DpApp.inf
ShellPkg/DynamicCommand/DpDynamicCommand/DpDynamicCommand.inf

Allow Dp work without ACPI 

---

Maintainers.txt

We would like any proposed change in the edk2 codebase to be assignable to a human maintainer/reviewer. If there is a feature for which there is no longer any support, we should find a way to remove it from the head of the repository. For critical features, we must find community members that are willing to own it.

Maintainers.txt: Remove Orphan status option

---

Maintainers.txt

Maintainers.txt: Remove myself as a tools maintainer

---

RedfishPkg/Library/HiiUtilityLib/HiiUtilityInternal.c
RedfishPkg/Library/HiiUtilityLib/HiiUtilityLib.c

diff to v2:
recorded received R-b.
patch 3/3 was dropped

Redfish: Original set of 3/3 with USB NIC MAC fix that was dropped.

---

MdePkg/Include/IndustryStandard/Nvme.h

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4591
1. Refer NVME spec 2.0c chapter 5.24, add Sanitize Command related definition.
2. Refer NVME spec 2.0c chapter 5.16, add Get Log Page Command related definition for Sanitize status support.
Cc: Xiao X Chen <xiao.x.chen@intel.com>
Cc: Arthur Chen <arthur.g.chen@intel.com>

MdePkg:Add NVME Sanitize command support to Nvme.h

---

StandaloneMmPkg/Library/StandaloneMmHobLib/StandaloneMmHobLib.c

According to the discussion in "StandaloneMmPkg: Fix HOB space and heap space conflicted issue" [1], Standalone MM modules should be HOB consumers where HOB is read-only. Therefore, this patch removes the supported functions for HOB creation in the StandaloneMmHobLib.
[1] https://edk2.groups.io/g/devel/message/108333
Cc: Oliver Smith-Denny <osde@linux.microsoft.com>

StandaloneMmPkg/StandaloneMmHobLib: Remove HOB creation

---

BaseTools/Source/Python/FMMT/FMMT.py
BaseTools/Source/Python/FMMT/core/BinaryFactoryProduct.py
BaseTools/Source/Python/FMMT/core/BiosTree.py
BaseTools/Source/Python/FMMT/core/BiosTreeNode.py
BaseTools/Source/Python/FMMT/core/FMMTOperation.py
BaseTools/Source/Python/FMMT/core/FMMTParser.py
BaseTools/Source/Python/FMMT/core/FvHandler.py
BaseTools/Source/Python/FirmwareStorageFormat/UPLHeader.py

This PR is linked to edk2-basetools repo PR:
https://github.com/tianocore/edk2-basetools/pull/95
https://github.com/tianocore/edk2-basetools/pull/103
Updated Review-by

Fmmt enhancement

---

RedfishPkg/RedfishDiscoverDxe/RedfishDiscoverDxe.c

Remedy Redfish service discovery flow changes made in commit 8736b8fd.
The above fix creates the dependency with SMBIOS 42h record, which has a problem as SMBIOS 42h may not be created when RedfishDiscovery.Supported() is invoked even all of the required protocols are ready on the ControllerHandle. We can’t guarantee SMBIOS 42 structure will be always created before ConnectController(). USB NIC maybe detected late and it means PlatformHostInterfaceBmcUsbNicLib can populate SMBIOS 42h information late as well. Calling to
RedfishServiceGetNetworkInterface with the previous fix may result in no network interface for BMC-exposed NIC as SMBIOS 42h is not ready yet.This is the first issue.
Second, to skip the network interface when
NetworkInterfaceGetSubnetInfo() returns a failure also has …

RedfishPkg/RedfishDicovery: Remedy Redfish service discovery flow

---

BaseTools/Source/C/GenFw/Elf64Convert.c

When converting ELF to PE/COFF for the AArch64 target, we may encounter an R_AARCH64_ADR_GOT_PAGE relocation that refers to an ADR instruction instead of an ADRP instruction. This can happen when the toolchain is working around Cortex-A53 erratum #843419.  If that's the case, be sure to calculate the offset appropriately.
This resolves an issue experienced when building a StandaloneMm image (which is built with -fpie) with stack protection enabled on GCC compiled with "--enable-fix-cortex-a53-843419". In this case, the linker may convert an ADRP instruction appearing at an offset of 0xff8 or 0xffc modulo 4KiB into an ADR instruction, but will leave the original R_AARCH64_ADR_GOT_PAGE relocation in place. (This is not a bug in the linker, given that there is no other relocation type that …

BaseTools/GenFw: Correct offset when relocating an ADR

---

IntelFsp2Pkg/Tools/ConfigEditor/ConfigEditor.py
IntelFsp2Pkg/Tools/ConfigEditor/GenYamlCfg.py
IntelFsp2Pkg/Tools/Tests/TestVfrYaml.yml
IntelFsp2Pkg/Tools/UserManuals/ConfigEditorUserManual.md

REF:https://bugzilla.tianocore.org/show_bug.cgi?id=4638
Config Editor utility addition/changes:
Support to enable config editor tool to have a new feature that can load and view the configuration data of compiled VFR or HFR in form of YAML. This can help users to understand and track the configuration data when modifications are made.
Requires compiled vfr file as input in YAML format.
Running Configuration Editor:
python ConfigEditor.py …

IntelFsp2Pkg\Tools\ConfigEditor:Added new USF config workstream.

---

MdePkg/Include/Protocol/DriverHealth.h

Refer to Uefi spec 2.10 section 11.10.2, update the return value for EFI_DRIVER_HEALTH_PROTOCOL.GetHealthStatus.

MdePkg: Update GetHealthStatus function description

---

pip-requirements.txt

Updates edk2-pytool-extensions, edk2-pytool-library, and regex to their latest respective releases.

pip-requirements.txt: Update to latest

---

RedfishPkg/Include/Library/JsonLib.h
RedfishPkg/Library/JsonLib/JsonLib.c

Add JSON delete object function to remove JSON object from the given JSON paylaod.

RedfishPkg/JsonLib: Add JSON delete object function

---

MdePkg/Test/MdePkgHostTest.dsc
MdePkg/Test/Mock/Include/GoogleTest/Library/MockFdtLib.h
MdePkg/Test/Mock/Library/GoogleTest/MockFdtLib/MockFdtLib.cpp
MdePkg/Test/Mock/Library/GoogleTest/MockFdtLib/MockFdtLib.inf

Add Google Mock Library for FdtLib

MdePkg: Add FdtLib gmock support

---

MdePkg/Include/Register/Amd/Cpuid.h
OvmfPkg/IoMmuDxe/CcIoMmu.c
UefiCpuPkg/Library/BaseXApicLib/BaseXApicLib.c
UefiCpuPkg/Library/BaseXApicX2ApicLib/BaseXApicX2ApicLib.c

* [PATCH RESEND v2 0/2] AMD CPU extended topology
* https://edk2.groups.io/g/devel/message/113982
msgid <cover.1705549445.git.AbdulLateef.Attar@amd.com>
* https://edk2.groups.io/g/devel/message/114364
msgid <111fa447-7090-4138-a2e5-ad3a97712ccf@amd.com>
* [PATCH] OvmfPkg/IoMmuDxe: Provide an implementation for SetAttribute
https://edk2.groups.io/g/devel/message/114806
msgid <c0f9e95f557b601a045da015c1a97201e8aec2ab.1706634932.git.thomas.lendacky@amd.com>

Queue 2024 Jan 31

---

BaseTools/Scripts/PatchCheck.py

Code review tools like gerrit might use a 'Change-id' tag to track the evolution of patches. This tag should be removed before submitting a patch to the mailing-list.
It has been observed that contributors sometimes forget to remove this tag. Add a check in PatchCheck.py to automate this.
Also add a '--ignore-change-id' command line parameter to ignore the above check.
Acked-by: Pedro Falcato <pedro.falcato@gmail.com>

BaseTools/Scripts/PatchCheck.py: Check for Change-id

---

BaseTools/Source/Python/AutoGen/GenC.py
MdeModulePkg/Core/DxeIplPeim/X64/VirtualMemory.c
OvmfPkg/Library/PlatformInitLib/MemDetect.c
UefiCpuPkg/Library/MpInitLib/MpHandOff.h
UefiCpuPkg/Library/MpInitLib/MpLib.c
UefiCpuPkg/Library/MpInitLib/MpLib.h
UefiCpuPkg/Library/MpInitLib/PeiMpLib.c

* [PATCH v4 0/3] OvmfPkg: Add support for 5-level paging
msgid `<20240222105407.75735-1-kraxel@redhat.com>`
https://edk2.groups.io/g/devel/message/115797
* [PATCH] BaseTools/AutoGen: declare ProcessLibraryConstructorList() for SEC modules
msgid `<20240224210504.41873-1-lersek@redhat.com>`
https://edk2.groups.io/g/devel/message/115910
https://bugzilla.tianocore.org/show_bug.cgi?id=991
* [PATCH v2 1/1] UefiCpuPkg/MpInitLib: add struct MP_HAND_OFF_CONFIG
msgid `<20240228114855.1615788-1-kraxel@redhat.com>`
https://edk2.groups.io/g/devel/message/116115

queue 2024-Feb-29

---

DynamicTablesPkg/Library/Acpi/Arm/AcpiSsdtCpuTopologyLibArm/SsdtCpuTopologyGenerator.c

The code was incorrectly assuming that root nodes had to be physical package nodes and vice versa. This is not always true, so update the check to simply require exactly one package node somewhere in the hierarchy.

DynamicTablesPkg/SSDT: Require Package node in hierarchy

---

ShellPkg/Library/UefiShellAcpiViewCommandLib/AcpiParser.h
ShellPkg/Library/UefiShellAcpiViewCommandLib/Parsers/Hpet/HpetParser.c
ShellPkg/Library/UefiShellAcpiViewCommandLib/Parsers/Wsmt/WsmtParser.c
ShellPkg/Library/UefiShellAcpiViewCommandLib/UefiShellAcpiViewCommandLib.c
ShellPkg/Library/UefiShellAcpiViewCommandLib/UefiShellAcpiViewCommandLib.inf

ShellPkg/Acpiview: HPET parser and WSMT parser

---

EmbeddedPkg/Drivers/VirtualKeyboardDxe/VirtualKeyboard.c
EmbeddedPkg/Drivers/VirtualKeyboardDxe/VirtualKeyboard.h
EmulatorPkg/EmuGopDxe/GopInput.c
MdeModulePkg/Bus/Isa/Ps2KeyboardDxe/Ps2KbdTextIn.c
MdeModulePkg/Bus/Isa/Ps2KeyboardDxe/Ps2Keyboard.h
MdeModulePkg/Bus/Usb/UsbKbDxe/EfiKey.c
MdeModulePkg/Bus/Usb/UsbKbDxe/EfiKey.h
MdeModulePkg/Universal/Console/ConSplitterDxe/ConSplitter.c
MdeModulePkg/Universal/Console/ConSplitterDxe/ConSplitter.h
MdeModulePkg/Universal/Console/TerminalDxe/Terminal.h
MdeModulePkg/Universal/Console/TerminalDxe/TerminalConIn.c
ShellPkg/Application/Shell/ConsoleWrappers.c

This patch series add comments to ReadKeyStroke implementation in Edk2.

Update the comments of ReadKeyStroke and ReadKeyStrokeEx

---

ShellPkg/Library/UefiShellDebug1CommandsLib/SmbiosView/PrintInfo.c

REF:https://bugzilla.tianocore.org/show_bug.cgi?id=4737
update smbiosview type 4 related fileds.

ShellPkg: Update smbiosview type 4 with SMBIOS 3.6 fields

---

SecurityPkg/Tcg/Tcg2Config/Tcg2ConfigImpl.c

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4731
TCG2 configuration UI shows all the hash algorithms that TPM hardware supports in the checkbox. If user only selects one algorithm that is supported by TPM hardware but not supported by BIOS and uncheck the others, the SyncPcrAllocationsAndPcrMask in Tcg2Pei will not be able to decide a viable PCR to activate, then an assert occurs.
Add check against PcdTcg2HashAlgorithmBitmap when deciding whether to suppress the hash algorithm checkbox to avoid user to select the hash algorithm which may cause an assert.
Reviewed-by: Rahul Kumar <rahul1.kumar@intel.com>

SecurityPkg/Tcg2Config: Hide BIOS unsupported hash algorithm from UI

---

OvmfPkg/IntelTdx/README.md

BZ: https://bugzilla.tianocore.org/show_bug.cgi?id=4756
There are below updates in this patch:
1. Rename README to README.md so that it can be show as markdown document.
2. Update some information about TDVF.
2. Fix some typo.
Reviewed-by： Jiewen Yao <jiewen.yao@intel.com>

OvmfPkg/IntelTdx: Update TDVF README

---

IntelFsp2Pkg/Tools/GenCfgOpt.py
IntelFsp2Pkg/Tools/PatchFv.py

Ref to https://docs.python.org/3/whatsnew/3.12.html
A backslash-character pair that is not a valid
escape sequence now generates
Signed-off-by: Gua Guo <gua.guo@intel.com>
@[gguo11837463](https://github.com/gguo11837463/edk2/commits?author=gguo11837463)
gguo11837463 committed 2 minutes ago

IntelFsp2Pkg: Python3.12 support

---

OvmfPkg/Library/CcExitLib/CcExitVcHandler.c

Ensure that when a #VC exception happens, the instruction at the instruction pointer matches the instruction that is expected given the error code. This is to mitigate the ahoi WeSee attack [1] that could allow hypervisors to breach integrity and confidentiality of the firmware by maliciously injecting interrupts. This change is a translated version of a linux patch e3ef461af35a ("x86/sev: Harden #VC instruction emulation somewhat")
[1] https://ahoi-attacks.github.io/wesee/
Cc: Borislav Petkov (AMD) <bp@alien8.de>
Reviewed-by: Tom Lendacky <thomas.lendacky@amd.com>

OvmfPkg: Harden #VC instruction emulation somewhat (CVE-2024-25742)

---

MdeModulePkg/Core/PiSmmCore/Smi.c
StandaloneMmPkg/Core/Mmi.c

Initialize 'WillReturn' variable
Qemu boot successes
N/A

Initialize 'WillReturn' variable

---

UefiPayloadPkg/Readme.md

Update ReadMe.md for swig install process in
windows OS.

UefiPayloadPkg: Update ReadMe.md to swig install

---

MdePkg/Include/IndustryStandard/IpmiNetFnOem.h

Add net function definitions for OEM/Non-IPMI group request and response

MdePkg: Add Ipmi definitions header file for OEM net function

---

OvmfPkg/IntelTdx/TdxHelperLib/SecTdxHelper.c

Encrypted and Special Purpose resource attributes are introduced in PI 1.8 Specification. This patch is to update VMM Hob list integrity check to recognize these resource attributes.

OvmfPkg: Update VMM Hob list check to support new resource attributes

---

BaseTools/Source/Python/build/BuildReport.py

This produces output that matches CodeChecker log command
- Set directory to build output path
- Set build destination to the object created instead of the path
- Add recursive macro support
- Add lookup in module.Macros dictionary
- Add leading include flag to include list
- Add source file to compile commands
Validated output compile_commands.json with clangd and CodeChecker
N/A

BaseTools/BuildReport: Improve compile_commands generation

---

UefiCpuPkg/Library/CpuCacheInfoLib/CpuCacheInfoLib.c

Change-Id: I0aed2490b8a5b62ead7d3b6a9cc8c821b58bf627

UefiCpuPkg: Correct the count of different type of Cache. 

---

UefiCpuPkg/PiSmmCpuDxeSmm/SmmProfile.c

The system hang issue is exposed when SmmProfile feature enabled. Root cause to the error returned from the page table update (PageTableMap) during InitPaging.
The memory range within mProtectionMemRange shall be updated with the correct page table attribute in InitPaging function. But existing code doesn't mark the EFI_MEMORY_RP mask, which leading the attributes setting without the 'Present' attribute. Then, PageTableMap will return RETURN_INVALID_PARAMETER due to below reason (see function IsAttributesAndMaskValidForNonPresentEntry): For non-present range, Mask->Bits.Present is 0 but some other attributes are provided.
The fix is to add the EFI_MEMORY_RP in attribute mask, setting attributes or clearing attributes depends on the 'Present' flag in the mProtectionMemRange.
Note:
When …

UefiCpuPkg/PiSmmCpuDxeSmm: Fix system hang when SmmProfile enable

---

MdeModulePkg/Library/SmmReportStatusCodeLib/StandaloneMmReportStatusCodeLib.inf
MdePkg/Library/StandaloneMmServicesTableLib/StandaloneMmServicesTableLib.inf

<_Describe how these changes should be …

Mm core module type

---

MdeModulePkg/Core/Dxe/Mem/HeapGuard.c

REF:https://bugzilla.tianocore.org/show_bug.cgi?id=2411
With Use-After-Free heap guard feature enabled, the DxeCore would blindly attempt to "level-up" when the `GuardAllFreedPages` inspect a non-max level table entry from the last loop. This could cause the next round of inspection to dereference a potentially null pointer and as such causing a page fault.
This change adds a null pointer check to prevent such case from happening.
- Examples: Unit tests …

MdeModulePkg: DxeCore: Fix Use-After-Free guard causing page fault

---

.pytool/Plugin/DependencyCheck/DependencyCheck.py
.pytool/Plugin/SpellCheck/SpellCheck.py
.pytool/Plugin/UncrustifyCheck/UncrustifyCheck.py

Improves the CI output with more actionable messages and downgrades some errors/warnings.
- Verified plugin output in conditions modified
- Check if any other tools/processes depended on previous output and adjust if so.

.pytool/Plugin: Improve plugin log messages

---

UefiCpuPkg/PiSmmCpuDxeSmm/SmmCpuMemoryManagement.c

UefiCpuPkg: Revert "UefiCpuPkg/PiSmmCpuDxeSmm:Map SMRAM in 4K..."
This reverts commit ae59b8ba4166384cbfa32a921aac289bcff2aef9.
The commit ae59b8ba41 was added to modify the GenSmmPageTable() to map SMRAM in 4K page granularity. It was to urgently fix a smm hang issue by avoiding page split in paging structures that covers SMRAM range when SMI happens. But finally the smm hang issue was root caused and fixed by commit 839bd17973.
Meanwhile a smm page table creation related issue was introduced by commit ae59b8ba41:
In the function GenSmmPageTable(), the paging level for the range outside SMRAM is depend on the Input parameter PagingMode. However, the paging level for SMRAM range is depend on m5LevelPagingNeeded. If the two paging levels are different, then the smm page table is created …

UefiCpuPkg: Revert "UefiCpuPkg/PiSmmCpuDxeSmm:Map SMRAM in 4K..."

---

UefiCpuPkg/Library/MpInitLib/MpLib.c
UefiCpuPkg/Library/MpInitLib/MpLib.h

Enhance MpLib including:
Verified in platform which open the stack guard, and it disable and enable APs. Boot is fine
N/A

Mplib enhance

---

UefiCpuPkg/PiSmmCpuDxeSmm/SmmProfile.c

This commit is to fix smm code assert issue when SMM Profile is enabled.
When SMM Profile is enabled, the function InitProtectedMemRange() retrives MMIO ranges from GCD and store the MMIO ranges in the mProtectionMemRange. When ReadyToLock, the function InitPaging() modifies the page table based on the mProtectionMemRange. If the MMIO ranges in mProtectionMemRange is not 4k aligned, code will assert when modifying page table.
In this commit, we skip the MMIO ranges that BaseAddress and Length are not 4k aligned when creating mProtectionMemRange. This will only cause each access to the skipped MMIO range to be logged. In current failure case on QEMU and QSP SimicsOpenBoard, the skipped MMIO range is [0xFED00000, 0xFED00400] for HPET. Considering that the probability of HPET MMIO range …

UefiCpuPkg: fix issue when SMM profile is enabled

---

OvmfPkg/Library/HardwareInfoLib/HardwareInfoDxe.c
OvmfPkg/LoongArchVirt/Library/LsRealTimeClockLib/LsRealTimeClockLib.c
UefiCpuPkg/CpuDxe/LoongArch64/Exception.c

Clean up the last few strays of EFI_D_ output in the repo, including a few that snuck in recently. Replace with DEBUG_. No functional change.
Not tested.
N/A

OvmfPkg,UefiCpuPkg: Purge EFI_D_

---

NetworkPkg/Library/DxeHttpLib/DxeHttpLib.c

Add HTTP CONNECT message support in HttpGenRequestMessage()
Add HTTP CONNECT message support in HttpGenRequestMessage()
CI
N/A

NetworkPkg/DxeHttpLib: Support HTTP CONNECT message in Tx path.

---

MdeModulePkg/Universal/Disk/RamDiskDxe/RamDiskImpl.c

I found this memory leak during code review.
This a common type of a leak on error path.
No tests. A trivial memory leak issue.
N/A

MdeModulePkg/RamDiskDxe: fix memory leak.

---

Maintainers.txt

Susovan is no longer an active contributor.
N/A
N/A

Maintainers.txt: Remove Susovan Mohapatra

---

Maintainers.txt

The following individuals are no longer active maintainers:
- Wenxing Hou
- Zhichao Gao
- Chan Laura
- Catharine West
N/A
N/A

Maintainers.txt: Cleanup inactive maintainers.

---

BaseTools/Source/Python/Trim/Trim.py

When including one ASL file in another, add a header / footer to the included file to easily tell where the included file starts and ends.
These updates have been used in a downstream consumer with no issues. Only adds additional comments to any ASL file with an include.
N/A

BaseTools: Trim: Add header/footer for ASL include

---

ArmPkg/Library/ArmArchTimerLib/ArmArchTimerLib.c

The timer counter register can wrap around and when this happens, we'll get misbehavior for any MicroSecondDelay() calls. This adds handling for that.
Fixes the case where timer register wraps around while a timeout is in progress.
Ran with changes in software platform emulation (FVP).
N/A

ArmPkg: Fix timer wrap-around

---

EmbeddedPkg/Library/PrePiHobLib/Hob.c

SetBootMode returns the BootMode instead of status code. Fix it to return status code.
N/A

EmbeddedPkg: Fix SetBootMode return value as specified in header file.

---

MdePkg/Include/IndustryStandard/IpmiNetFnGroupExtension.h

This adds constants and structure definitions for Send/Get Boot Progress Code through IPMI, according to Server Base Manageability Requirements (SBMR) [1], Appendix F.
[1] https://developer.arm.com/documentation/den0069

MdePkg/IndustryStandard: Add definitions for IPMI Boot Progress Code

---

UefiCpuPkg/PiSmmCpuDxeSmm/Ia32/PageTbl.c
UefiCpuPkg/PiSmmCpuDxeSmm/Ia32/SmmFuncsArchDxeSmm.c
UefiCpuPkg/PiSmmCpuDxeSmm/NonMmramMapDxeSmm.c
UefiCpuPkg/PiSmmCpuDxeSmm/PiSmmCpuDxeSmm.c
UefiCpuPkg/PiSmmCpuDxeSmm/PiSmmCpuDxeSmm.inf
UefiCpuPkg/PiSmmCpuDxeSmm/PiSmmCpuStandaloneMm.c
UefiCpuPkg/PiSmmCpuDxeSmm/PiSmmCpuStandaloneMm.inf
UefiCpuPkg/PiSmmCpuDxeSmm/SmmCpuMemoryManagement.c
UefiCpuPkg/PiSmmCpuDxeSmm/X64/PageTbl.c
UefiCpuPkg/PiSmmCpuDxeSmm/X64/SmmFuncsArchDxeSmm.c

<_Describe how these changes should …

Clean restricted memory access in mm cpu

---

Maintainers.txt

I intend to help with maintenance of the following Arm modules:
ArmPkg/
ArmPlatformPkg/
ArmVirtPkg/
MdePkg/Include/Library/ArmLib.h

Maintainers.txt: Add Sami Mujawar as maintainer for Arm modules

---

UefiPayloadPkg/Readme.md

Enhance and introduce environment construction and build step for ELF and FIT format payload
N/A
N/A

UefiPayloadPkg: Enhance ReadMe.md for ELF and FIT

---

Maintainers.txt

Per discussion in an email thread, I'm adding myself as a maintainer of the UefiPayloadPkg.
N/A
N/A

Maintainers.txt: Add myself as UefiPayloadPkg maintainer

---

UefiPayloadPkg/PayloadLoaderPeim/FitPayloadLoaderPeim.c

Adjust the sequence of gEfiEndOfPeiSignalPpiGuid notify function when FDT is disabled , or some of notify functions won't work cause the debug message print twice.
Change-Id: Ib7dd28d51826ce6de1974e2a74e0960e4d20b06c
Hsd-es-id: 16025580922 …

UefiPayloadPkg : Roll back the sequence of gEfiEndOfPeiSignalPpiGuid.

---

UefiCpuPkg/Library/MpInitLib/PeiMpInitLib.inf
UefiCpuPkg/Library/MpInitLib/PeiMpLib.c
UefiCpuPkg/Universal/Acpi/S3Resume2Pei/S3Resume.c

First commit is to fix a potential s3 bug.
The second commit is to do some clean up.

Fix S3 bugs

---

Maintainers.txt

Maintainers.txt: Update GitHub username for myself

Maintainers.txt: Update GitHub username for myself

---

DynamicTablesPkg/Library/Acpi/Common/AcpiFadtLib/FadtGenerator.c

Validate the FADT fixed feature flags for
non-hardware reduced model.
Corrects FADT feature flag validation for non-hardware reduced acpi model.
Tested on AMD platform with non-hardware reduced model.
N/A

DynamicTablesPkg: Update FADT fixed feature flags validation

---

MdePkg/Include/IndustryStandard/Usb.h

- USB 3.0 spec, Section 9.6.4
- Add class specific descriptor types
Add USB Interface Association Descriptor definition
N/A

USB Association Descriptor Definitions

---

DynamicTablesPkg/Library/Acpi/X64/AcpiWsmtLib/WsmtGenerator.c

Update WSMT table with generic creator id.
Update the creator id with generic macro TABLE_GENERATOR_CREATOR_ID.
tested on X64 AMD platform.
N/A

DynamicTablesPkg: Update creator id for WSMT table

---

Maintainers.txt

As discussed with the stewards, I have decided to resume my role as a maintainer in the Tianocore project (if they will have me, of course)

Maintainers: Revert "Remove Ard Biesheuvel from all packages"

---

ArmPlatformPkg/Drivers/LcdGraphicsOutputDxe/LcdGraphicsOutputBlt.c
ArmPlatformPkg/Drivers/PL061GpioDxe/PL061Gpio.c
ArmPlatformPkg/Drivers/PL061GpioDxe/PL061Gpio.h
ArmPlatformPkg/Drivers/SP805WatchdogDxe/SP805Watchdog.c
ArmPlatformPkg/Library/PL111Lcd/PL111Lcd.h

Makes changes to comply with alerts raised by CodeQL.
The issues here fall into the following category:
1. comparison-with-wider-type
This was shipped and tested with project mu
N/A

ArmPlatformPkg: CodeQL Fixes.

---

StandaloneMmPkg/Drivers/StandaloneMmIplPei/MmFoundationHob.c

Correct max physical address bit

---

StandaloneMmPkg/Drivers/StandaloneMmIplPei/MmFoundationHob.c

StandaloneMmPkg/MmIpl: Optimize hob pointer check flow

---

Maintainers.txt

Cc: Dun Tan <dun.tan@intel.com>

Maintainers.txt: Update M and R for UefiCpuPkg and StandaloneMmPkg

---

Maintainers.txt

Per request from current FatPkg maintainer @niruiyu, I am signing up to maintain FatPkg.
N/A.
N/A.

Maintainers.txt: Add Myself as FatPkg Maintainer

---

Maintainers.txt

Thanks to @os-d who volunteers to take the role of FatPkg maintainer.
I removed myself as the maintainer of FatPkg since I do not have enough bandwidth.

Remove Ray from maintainer list of FatPkg

---

DynamicTablesPkg/Readme.md

Links from acpica.org are now redirected to the ACPICA overview page on intel.com. Update the link so it goes to the 20200717 download page.
N/A

DynamicTablesPkg: Update link to iASL in Readme.md

---

BaseTools/Plugin/HostBasedUnitTestRunner/HostBasedUnitTestRunner.py

Detect the version of lcov and only apply
version 2 workaround when needed.
Fixes 61c714285f8c
By running stuart_ci_build locally in a container using these images:
- ghcr.io/tianocore/containers/fedora-37-test (lcov 1)
- ghcr.io/tianocore/containers/fedora-40-test (lcov 2)

BaseTools: Coverage: Detect lcov version

---

BaseTools/Scripts/ConvertFceToStructurePcd.py

No functional change, just fixing misspelling in a comment
N/A
N/A

BaseTools: fix spelling error

---

OvmfPkg/RUNTIME_CONFIG.md

OvmfPkg: document runtime config options

---

Maintainers.txt

Add myself as a reviewer for the ShellPkg to help with the reviewing effort.

Maintainers.txt: Add myself as ShellPkg reviewer

---

BaseTools/Source/Python/FMMT/core/BinaryFactoryProduct.py

Removed the import statement from re import T as it was not being used and is deprecated.
Verify FMMT is working fine
N/A

Removed the import statement from re import T as it was not being used and is deprecated.

---

EmbeddedPkg/Library/PrePiHobLib/Hob.c
EmbeddedPkg/Library/PrePiLib/FwVol.c
EmbeddedPkg/SimpleTextInOutSerial/SimpleTextInOut.c

Makes changes to comply with alerts raised by CodeQL.
Most of the issues here fall into the following two categories:
1. Potential use of uninitialized pointer.
2. Inconsistent integer width in comparison.
This was shipped and tested with project mu
N/A

EmbeddedPkg: CodeQL Fixes.

---

UefiCpuPkg/PiSmmCpuDxeSmm/MpService.c

Restructured the SmmWaitForApArrival first CPU synchronization conditional checks and added new IsCpuSyncAlwaysNeeded check to determine whether the sync should be executed unconditionally when a SMI occurs.
The first CPU synchronization shall executed unconditionally if the new IsCpuSyncAlwaysNeeded check return TRUE. Otherwise, first CPU synchronization is not executed unconditionally, and the decision to synchronize should be based on the system configuration and status.
Pass the build & boot & check.

UefiCpuPkg/PiSmmCpuDxeSmm: SmmWaitForApArrival first sync check

---

UnitTestFrameworkPkg/Library/UnitTestDebugAssertLib/UnitTestDebugAssertLibHost.cpp

PR #6408 introduced a host specific NORETURN function to address false positives from the address sanitizer after LongJump() is called and the stack location is modified.
This approach was discussed here:
https://github.com/tianocore/edk2/pull/6408/files#r1918810499
Some false positives are still being observed with this initial solution.
The address sanitizer provides __asan_handle_no_return() to clean up shadow memory before a NORETURN function is called and provides a simpler implementation for this issue without having to introduce a host specific
NORETURN function.
https://github.com/llvm/llvm-project/blob/main/compiler-rt/include/sanitizer/asan_interface.h
Verified that all current unit tests pass as well as ones that were generating false positives.
N/A

UnitTestFrameworkPkg: Fix false positives from address sanitizer

---

UefiPayloadPkg/Tools/ElfFv.py

Original ELF segment/section syncup process having layout assumption which has caused build failure when layout changing.
New process will parse both existing segments and sections firstly to support different layout.
- Examples: Crypto algorithm change or buffer …

UefiPayloadPkg: Update Elf segment/section syncup process

---

Maintainers.txt

I am signing up to maintain PrmPkg.

Maintainers.txt: add myself as PrmPkg maintainer

---

MdeModulePkg/Test/MdeModulePkgHostTest.dsc
MdeModulePkg/Test/Mock/Include/GoogleTest/Library/MockVariablePolicyHelperLib.h
MdeModulePkg/Test/Mock/Library/GoogleTest/MockVariablePolicyHelperLib/MockVariablePolicyHelperLib.cpp
MdeModulePkg/Test/Mock/Library/GoogleTest/MockVariablePolicyHelperLib/MockVariablePolicyHelperLib.inf

Provide MockVariablePolicyHelperLib for GoogleTest.
Tested in module integrated with this MockVariablePolicyHelperLib and pass
Include the MockVariablePolicyHelperLib.inf in LibraryClasses session in the dsc and use the mock function provided in this PR.

Add MockVariablePolicyHelperLib

---

MdeModulePkg/Bus/Usb/UsbBusPei/UsbPeim.c

Unlike DXE USB enumeration that enumerates all changed ports on timer interrupt, PEI USB Enumeration runs once at the driver entry point. USB3.x devices initially appear in USB2.0 ports. When the USB2.0 port is reset, the USB3.x device disappears from the USB2.0 port and appears on the USB3.0 port. The USB3.x device won't be enumerated if the USB2.0 port number is greater than the USB3.0 port number. Re-enumerate USB to make sure USB3.x devices in this case.
REF: [eXtensible Host Controller Interface for Universal Serial Bus (xHCI)
](https://www.intel.com/content/www/us/en/content-details/625472/extensible-host-controller-interface-for-universal-serial-bus-xhci-requirements-specification.html)4.19.3 Connect Status Change Reporting
For a USB2 Protocol port, “device presence” is indicated …

MdeModulePkg/UsbBusPei: Improve PEI USB enumeration

---

IntelFsp2Pkg/FspSecCore/SecFspApiChk.c

Today when FspSiliconInit/FspSmmInit is called, the corresponding FSP-S/I UPD pointer is saved in FSP_GLOBAL_DATA by gen-specific code. Such code might be duplicated between different gens of FSP implementation.
The change is to update FspSecCore module to set the UPD pointer in FSP_GLOBAL_DATA for all API calls:
* FspMemoryInit
* FspSiliconInit
* FspSmmInit
This can eliminate the gen-specific code.
<_For each item, place an "x" in between `[` and `]` if true. Example: …

IntelFsp2Pkg/FspSecCore: Update FSP global data in FSP-S/I entry

---

StandaloneMmPkg/Drivers/StandaloneMmIplPei/MmFoundationHob.c
StandaloneMmPkg/Drivers/StandaloneMmIplPei/StandaloneMmIplPei.c
StandaloneMmPkg/Drivers/StandaloneMmIplPei/StandaloneMmIplPei.h

StandaloneMmPkg/MmIpl : Add EFI_HOB_HANDOFF_INFO_TABLE to MM HOB list

---

IntelFsp2Pkg/FspSecCore/SecFsp.c

IntelFsp2Pkg : Set FSP-I upd data pointer to NULL as default

---

Maintainers.txt

Removing Chinni from maintainer list of IntelFsp2Pkg and IntelFsp2WrapperPkg.

Editing maintainers list

---

Maintainers.txt

Transfer Ray's Reviewer role on BDS/Disk modules to Dandan.

Maintainers.txt: Transfer Ray's Reviewer role to Dandan

---

UefiPayloadPkg/Library/FdtParserLib/FdtParserLib.c

UefiPayloadPkg: Skip PCI RB Segment parsing if no RB semgment info provided
Skip PCI Root Bridge Segment initialization there is no Root Bridge segment information is provided in Flattern Device Tree.
When FDT based DTB is parsed, variables mPciRootBridgeInfo and mUplPciSegmentInfoHob are always dereferenced. If there is no PCI RB Bridge info or RB Segment info provided in FDT, it leads to NULL pointer dereferenced.
To address this issue, parse PCI RB and Segment information only when they are available at FDT. If they are unavailable, skip it and allow the PciBusDxe and PciHostBridgeDxe to handle them.
- N/A
- N/A
- **Tests** - Does this PR include …

UefiPayloadPkg: Skip PCI RB Segment parsing if no RB semgment info provided

---

BaseTools/Source/Python/FMMT/core/GuidTools.py

- FMMT tool would use the ```PATH``` environment variable for locating the required GUID tool.
- On Windows-like system, batch file not found in the ```PATH``` environment variable when ```shell=False```.
- This issue required commands to include program extensions ```*.exe``` or have absolute paths.
- This patch sets ```shell=True``` to extend the support for batch files, including scripts in BinWrappers under BaseTools.
- Converted input commands from lists to strings to ensure proper argument interpretation in POSIX-like shell scripts.
- Below is the example of performing the FV decompose with additional debug message and the error message got hit.
```
DEBUG   : Parsing inputfile data......
INFO    : ['LzmaCompress', '-d', '-o', …
```

BaseTools/FMMT: Fix the GUID Tool Not Found the Shell Script Issue

---

MdeModulePkg/Library/BootManagerUiLib/BootManager.c

With #10668  #10820 UiApp can be in the Boot Entries list without the LOAD_OPTION_HIDDEN flag set. This means that UiApp can be found in its internal Boot Manager list. 
Side note: Trying to start the UiApp inside the UiApp will cause an assert to fail.
This PR fixes it by simply not showing UiApp in that menu if it is found among the entries. …

MdeModulePkg/BootManagerUiLib: hide UiApp from boot entries

---

MdeModulePkg/Universal/DriverHealthManagerDxe/DriverHealthManagerDxe.c
MdeModulePkg/Universal/PlatformDriOverrideDxe/PlatDriOverrideDxe.c
MdeModulePkg/Universal/PlatformDriOverrideDxe/PlatDriOverrideDxe.uni
MdeModulePkg/Universal/PlatformDriOverrideDxe/PlatformDriOverrideDxe.inf

MdeModulePkg:Fix typos

---

SecurityPkg/Tcg/Opal/OpalPassword/OpalDriver.c

Improve OpalDriverGetDriverDeviceName function that gets device name through the component name protocol. Currently the function searches for all handles (as controller handle) to find the right GetControllerName service for the child handle. The update improves the way to get device name and supports better performance (e.g. 1681(μs) -> 3(μs) for 1 NVMe device). This can prevent a compatibility issue for GetControllerName service of some drivers, which is not flexible for handle parameter information (e.g. it was found that an EFI driver caused an exception error/hang when GetControllerName service for the driver is called in OpalDriverGetDeviceNameByProtocol function).
Current function :
1. Find all handles.
2. Find all handles with ComponentName2 protocol.
3. Find the device name by …

SecurityPkg/OpalPasswordDxe: Improve the function to get device name

---

MdePkg/Include/Library/PerformanceLib.h

propery -> property
lof     -> log
evnent  -> event
<_Describe the test(s) that were run to verify …

MdePkg: Fix typos in PerformanceLib.h

---

MdeModulePkg/Core/PiSmmCore/PiSmmIpl.c

With current implemenation, all 3 SmmCommunication* functions go through the same routine, which will dereference the incoming pointer to inspect whether this is a V3 buffer or not.
However, the caller always pass in the physical addresses, which could cause the system to page fault after OS take over the runtime control.
This change refactored the common routine to accept both virtual and physical address. …

MdeModulePkg: PiSmmIpl: Fix physical address dereferencing

---

.azurepipelines/ReadMe.md
.azurepipelines/Ubuntu-GCC.yml
.azurepipelines/Windows-VS.yml
.pytool/Readme.md
ArmVirtPkg/PlatformCI/.azurepipelines/Ubuntu-GCC.yml
EmulatorPkg/PlatformCI/.azurepipelines/Ubuntu-GCC.yml
EmulatorPkg/PlatformCI/.azurepipelines/Windows-VS.yml
OvmfPkg/PlatformCI/.azurepipelines/Ubuntu-GCC.yml
OvmfPkg/PlatformCI/.azurepipelines/Windows-VS.yml

Details about a particular pipeline change over time - such as the specific Linux distro or toolchain version. At the same time, the pipeline files are directly referenced in Azure Pipelines to run the pipeline and few users have access to change those details.
To make the files less likely to refer to outdated information over time and reduce the need for an Azure Pipeline administrator to get involved, the files are updated to drop specific details apart from the host OS environment used in the pipeline.
---
Transition Plan:
- All new pipelines have been created in edk2-ci Azure Pipelines that correspond 1:1 with today's pipelines.
- See [PR gates](https://dev.azure.com/tianocore/edk2-ci/_build?definitionScope=%5CPR) and [CI](https://dev.azure.com/tianocore/edk2-ci/_build?definitionScope …

Pipeline Updates

---

MdeModulePkg/Library/ArmFfaLib/ArmFfaCommon.c

Patch 8d03c42d38d1 ("ArmPkg: ArmFfaLib: Update FF-A direct message to support 18 registers") calls SMCCC_VERSION by default during FF-A initialization even if the SMC conduit is not enabled. This leads to sending malformed FF-A versions if the SVC conduit is used instead.
This is observed for example when using an SPMC@EL-1 (e.g. rust-spmc) which receives the FF-A message via an SVC call and interprets SMCCC_VERSION as an FF-A Function ID and subsequently fails to handle it.
Since 18-register support is only support with FF-A >= 1.2, replace
SMCCC_VERSION check with FF-A version check
- **Security** - Does this PR have a direct …

ArmFfaLib: Replace SMCCC_VERSION check with FF-A version check 

---

MdePkg/Library/BasePciSegmentLibPci/PciSegmentLib.c
MdePkg/Library/PeiPciSegmentLibPciCfg2/PciSegmentLib.c
MdePkg/Library/UefiPciSegmentLibPciRootBridgeIo/PciSegmentLib.h

MdePkg/Include/Library/PciSegmentLib.h includes address parameter definition, add the same comment here for explaining the INVALID_PCI_SEGMENT_ADDRESS flag.
- **Tests** - Does this PR include any …

MdePkg: Add comment describing address parameter in BasePciSegmentLibPci

---

IntelFsp2Pkg/FspNotifyPhase/FspNotifyPhasePeim.c

IntelFsp2Pkg: Add Fsp notify phase check

---

UefiPayloadPkg/UefiPayloadPkg.dsc

UefiPayloadPkg: Add missing VirtNorFlashDeviceLib instance

---

BaseTools/Source/Python/Workspace/DscBuildData.py
MdeModulePkg/Bus/Pci/IdeBusPei/AtapiPeim.c
MdeModulePkg/Bus/Pci/IdeBusPei/AtapiPeim.h
MdeModulePkg/Library/VariablePolicyLib/VariablePolicyLib.c
MdePkg/Library/BaseRngLib/Riscv/Rng.c
MdePkg/Library/SmmCpuRendezvousLibNull/SmmCpuRendezvousLibNull.c
NetworkPkg/HttpDxe/HttpImpl.c
OvmfPkg/LoongArchVirt/PlatformPei/Platform.c
RedfishPkg/RedfishHttpDxe/RedfishHttpData.c
RedfishPkg/RedfishHttpDxe/RedfishHttpData.h
ShellPkg/Library/UefiHandleParsingLib/UefiHandleParsingLib.c
ShellPkg/Library/UefiShellDebug1CommandsLib/SmbiosView/PrintInfo.c
ShellPkg/Library/UefiShellDebug1CommandsLib/SmbiosView/SmbiosViewStrings.uni
UefiCpuPkg/Library/SmmCpuRendezvousLib/SmmCpuRendezvousLib.c
UefiCpuPkg/PiSmmCpuDxeSmm/CpuService.c
UefiPayloadPkg/UefiPayloadEntry/UefiPayloadEntry.c

Correct spelling errors and typos for few file in below packages.
BaseTools
MdeModulePkg
MdePkg
NetworkPkg
OvmfPkg
RedfishPkg
ShellPkg
UefiCpuPkg
UefiPayloadPkg
N/A, compilation only.
N/A

Correct spelling errors and typos

---

MdeModulePkg/Universal/Console/ConPlatformDxe/ConPlatform.c
MdeModulePkg/Universal/Console/GraphicsConsoleDxe/GraphicsConsole.c
MdeModulePkg/Universal/Console/TerminalDxe/Terminal.c

Running Codeql on MdeModulePkg/Universal/Console drivers results in codeql errors stemming for the following checks.
- cpp/comparison-with-wider-type
- cpp/missing-null-test
Local CI, booting Virutal platform with no ill effects.
No integration necessary.thing is required.

MdeModulePkg: Console cumulative codeql issues.

---

UefiCpuPkg/PiSmmCpuDxeSmm/MpService.c

update AllApArrivedWithException if the 1st timeout sync is skipped but all APs have arrived
This PR also refines the debug log in the SmmWaitForApArrival.

Smm cpu wait all aps fix

---

ShellPkg/Application/Shell/ShellEnvVar.c
ShellPkg/Application/Shell/ShellProtocol.c
ShellPkg/Library/UefiShellCommandLib/UefiShellCommandLib.c
ShellPkg/Library/UefiShellDebug1CommandsLib/SmbiosView/PrintInfo.c

Updated fixes for all Deadcode and Null field Coverity fixes in ShellPkg
Fixed all Dead Code and Null Field Coverity warnings.
1. Verified Coverity
N/A

ShellPkg: Fix Dead Code and Null field Coverity warnings.

---

UefiPayloadPkg/UefiPayloadEntry/Ia32/DxeLoadFunc.c
UefiPayloadPkg/UefiPayloadEntry/Ia32/DxeLoadFuncFit.c
UefiPayloadPkg/UefiPayloadEntry/RiscV64/DxeLoadFunc.c

Uefipayload: update stack address print to 64 bit

---

UefiPayloadPkg/UefiPayloadEntry/RiscV64/DxeLoadFuncFit.c

Fixing a Licensing typo
N/A
N/A

UefiPayloadPkg: RISCV: Licensing Fix

---

MdeModulePkg/Bus/Usb/UsbMouseDxe/UsbMouse.c
MdeModulePkg/Bus/Usb/UsbMouseDxe/UsbMouse.h
MdePkg/Include/Protocol/SimplePointer.h

Correct some comments in UsbMouseDxe/UsbMouse.c and SimplePointer.h

---

StandaloneMmPkg/Drivers/StandaloneMmIplPei/StandaloneMmIplPei.c

StandaloneMmPkg: Optimize MM core image size alignment

---

MdePkg/Include/IndustryStandard/ArmAgdiTable.h
ShellPkg/Library/UefiShellAcpiViewCommandLib/AcpiParser.h
ShellPkg/Library/UefiShellAcpiViewCommandLib/Parsers/Agdi/AgdiParser.c
ShellPkg/Library/UefiShellAcpiViewCommandLib/UefiShellAcpiViewCommandLib.c
ShellPkg/Library/UefiShellAcpiViewCommandLib/UefiShellAcpiViewCommandLib.inf

The Arm AGDI ACPI table is used for holding information pertaining to the Gobal Diagnostic Dump and Reset Interface. Add support for this table and enable dumping it's contents through the acpiview command.
This was tested locally by adding a dummy Agdi table for the Arm VExpress platform. Here is the sample output for the acpiview command.
Shell> acpiview -s AGDI …

4451 agdi support upstream

---

.github/scripts/GitHub.py
.github/scripts/validate_pr_formatting.py
.github/workflows/pull-request-formatting-validator.yml

This workflow runs when GitHub PRs are modified (edited, opened, reopened, and synchronized) to perform basic validation of the PR title and description.
Right now, this includes:
- Checking that the PR title is not empty
- Checking that the PR body is not empty
- Checking that the PR body meets the minimum text length. Where the minimum text length is defined to be the number of characters in the [PR template](https://github.com/tianocore/edk2/blob/master/.github/pull_request_template.md) with empty sections
- Checking that PR template text does not remain in the PR description
If a check fails, a GitHub comment will be left on the PR and a PR status check failure will be present on the PR until the issue is resolved. Upon future runs of the workflow, existing PR validation message …

.github/workflows: Add PR formatting validator
