tianocore/edk2

Readme.md
https://bugzilla.tianocore.org/show_bug.cgi?id=2315
Update Readme.md to indicate that that status badges are for
the edk2/master branch.
=> Readme.md: Update EDK II CI build branch name

EmulatorPkg/PlatformSmbiosDxe/PlatformSmbiosDxe.c, EmulatorPkg/PlatformSmbiosDxe/PlatformSmbiosDxe.inf
Old code use platfomr.
Change PlatfomrSmbiosDriverEntryPoint to PlatformSmbiosDriverEntryPoint.
Signed-off-by: Ming Tan <ming.tan@intel.com>
=> EmulatorPkg/PlatformSmbiosDxe: fix a spell error of platform.

BaseTools/Source/Python/Workspace/MetaFileParser.py
BZ: https://bugzilla.tianocore.org/show_bug.cgi?id=2308
This patch is to enable MACRO for Components section architecture
modifier.
=> BaseTools: Enable MACRO for DSC Components section tag

BaseTools/Source/Python/build/build.py
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2304
Cc: Bob C Feng <bob.c.feng@intel.com>
=> BaseTools: Fix build failure when using python38

MdePkg/Library/BaseRngLibNull/BaseRngLibNull.c, MdePkg/Library/BaseRngLibNull/BaseRngLibNull.inf, MdePkg/Library/BaseRngLibNull/BaseRngLibNull.uni, MdePkg/MdePkg.dsc
Ref: https://bugzilla.tianocore.org/show_bug.cgi?id=1871
This is null version of RngLib which should be used with modules that
inherit an (indirect) dependency on the RngLib class, but never actually
call RngLib APIs for consuming randomness.
To be more specific, if following components or functionalities are used
in a platform, the BaseRngLibNull should *not* be used. Instead, a non-Null
version of RngLib must be used (like BaseRngLib for IA32/X64, or future
DxeRngLibRngProtocol for all ARCHs).
- HddPasswordDxe.inf
- AES, TLS (TlsDxe.inf, TlsLib.inf), RSA_OAEP, RSA_PK1
- (If BaseRngLibNull interface ASSERTed at boot time)
Signed-off-by: Jian J Wang <jian.j.wang@intel.com>
=> MdePkg: add null version of RngLib

MdeModulePkg/Universal/Variable/RuntimeDxe/Variable.c
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=2333
During a SetVariable () invocation, UpdateVariable () is called.
UpdateVariable () contains logic to determine whether a volatile or
non-volatile UEFI variable was set so the corresponding runtime
cache can be updated to reflect the change. The current logic simply
evaluates Variable->Volatile to determine which runtime cache should
be updated.
The problem is Variable->Volatile does not always reflect whether a
volatile variable is being set. Variable->Volatile is set to TRUE
only in the case a pre-existing variable is found in the volatile
variable store. Therefore, the value is FALSE when a new volatile
variable is written.
This change updates the logic to take this into account. If a new
variable is written successfully, the …
=> MdeModulePkg/Variable: Fix volatile variable RT cache update logic (BZ 2333)

MdeModulePkg/Bus/Pci/NvmExpressDxe/NvmExpress.c, MdeModulePkg/Bus/Pci/NvmExpressDxe/NvmExpressPassthru.c
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=2118
When a packet is queued/completed for the asynchronous IO queue, the logic
to roll over to the front of the queue doesn't account for actual size of
the IO Submission/Completion queue.
This causes a device to hang due to doorbell being outside of visible
queue. An example would be if an NVMe drive only supported a queue size of
128 while the driver supports 256.
Signed-off-by: Sean Brogan <sean.brogan@microsoft.com>
Signed-off-by: Hao A Wu <hao.a.wu@intel.com>
Acked-by: Ray Ni <ray.ni@intel.com>
=> MdeModulePkg/NvmExpressDxe: Fix wrong queue size for async IO queues

BaseTools/Source/Python/AutoGen/ModuleAutoGen.py, BaseTools/Source/Python/AutoGen/PlatformAutoGen.py, BaseTools/Source/Python/AutoGen/WorkspaceAutoGen.py, BaseTools/Source/Python/Common/DataType.py, BaseTools/Source/Python/Workspace/DscBuildData.py, BaseTools/Source/Python/Workspace/MetaFileParser.py, BaseTools/Source/Python/Workspace/WorkspaceCommon.py, BaseTools/Source/Python/Workspace/WorkspaceDatabase.py
BZ:https://bugzilla.tianocore.org/show_bug.cgi?id=2270
Currently a PCD (e.g. FeaturePCD) cannot be used in a conditional
statement in a DSC/FDF file without a module in the build referencing
the PCD package DEC file.
An example implementation that to support this is to allow a [Packages]
section in the DSC file to list additional package dependencies for PCD
references in the package DSC/FDF files.
this patch is going to  add the ability to have the [packages] section
defined in the DSC file
Acked-by: Liming Gao <liming.gao@intel.com>
=> BaseTools:Add [packages] section in dsc file

BaseTools/Source/Python/build/build.py
BZ:https://bugzilla.tianocore.org/show_bug.cgi?id=2363
This patch is to fix a build tool regression issue which was introduced
by commit b8ac0b7f28.This issue caused map file lost the line of IMAGE=***.
For example,in Ovmf.map, there is no line of (IMAGE=<path to efi> ) under
each of modules item.
The path to the efi file generated by each module is written on this line
The purpose of this line is add the debug image full path.
there is no information about the module in the map file other than FVName,
it allows us to quickly know which module this part corresponds to.
In commit b8ac0b7f28,add a line ("self.BuildModules = []") in function,
but it's used to calculate the variable ModuleList in the following code.
Cc: Liming Gao …
=> BaseTools:fix regression issue for platform .map file

StandaloneMmPkg/StandaloneMmPkg.dsc
The StandaloneMmPkg currently has code for supporting
Arm architecture only. Support for X64 and IA32 is
currently under development on a separate branch.
However, StandaloneMmPkg/StandaloneMmPkg.dsc is
indicating that support for X64 and IA32 is
available which is causing build failures.
This has been reported in
https://bugzilla.tianocore.org/show_bug.cgi?id=2253
This issue has been discussed earlier on the list:
(1) https://edk2.groups.io/g/devel/message/47276
(2) https://edk2.groups.io/g/devel/message/47283
In light of the above, this patch removes IA32 and X64
from SUPPORTED_ARCHITECTURES, until support for the
respective architectures is merged into StandaloneMmPkg.
Cc: Achin Gupta <achin.gupta@arm.com>
Cc: Supreeth Venkatesh …
=> StandaloneMmPkg: Fix build failure

BaseTools/Source/Python/Workspace/MetaFileParser.py
BZ:https://bugzilla.tianocore.org/show_bug.cgi?id=2400
In Dsc Parser, included dsc file is parsed always no matter
if its condition is False
gUefiOvmfPkgTokenSpaceGuid.test1|FALSE
!if gUefiOvmfPkgTokenSpaceGuid.test1 == FALSE
!include OvmfPkg/test1.dsc
!else
!include OvmfPkg/test2.dsc
!endif
The patch avoids processing redundant dsc files and improves
the way Tool handles them.
In the above case, since the conditional result is FALSE,
"test2.dsc" is not parsed.
=> BaseTools:Enhance the way to handling included dsc file

ArmPkg/Library/PlatformBootManagerLib/PlatformBm.c
Third party driver images loaded from Option ROM get queued
for execution after EndOfDxe. These queued images need to be
dispatched from the PlatformBootManagerLib.
Since the queued images were not dispatched, the PCI Option
ROM drivers were not getting loaded on Juno. Therefore,
add call to EfiBootManagerDispatchDeferredImages() for
dispatching deferred images from PlatformBootManagerLib.
Reviewed-by: Ard Biesheuvel <ard.biesheuvel@linaro.org>
=> ArmPkg: Dispatch deferred images after EndOfDxe

UefiCpuPkg/PiSmmCpuDxeSmm/MpService.c, UefiCpuPkg/PiSmmCpuDxeSmm/PiSmmCpuDxeSmm.h, UefiCpuPkg/PiSmmCpuDxeSmm/PiSmmCpuDxeSmm.inf, UefiCpuPkg/UefiCpuPkg.dec, UefiCpuPkg/UefiCpuPkg.uni
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2388
Token is new introduced by MM MP Protocol. Current logic allocate Token
every time when need to use it. The logic caused SMI latency raised to
very high. Update logic to allocate Token buffer at driver's entry point.
Later use the token from the allocated token buffer. Only when all the
buffer have been used, then need to allocate new buffer.
Signed-off-by: Eric Dong <eric.dong@intel.com>
=> UefiCpuPkg/PiSmmCpuDxeSmm: Avoid allocate Token every time

Maintainers.txt
Achin has indicated that he no longer has the bandwidth available to
co-maintain StandaloneMmPkg, and has asked Sami and me to step in.
Reviewed-by: Leif Lindholm <leif.lindholm@linaro.org>
Reviewed-by: Jiewen Yao <Jiewen.Yao@intel.com>
Reviewed-by: Achin Gupta <achin.gupta@arm.com>
=> Maintainers: assume co-maintainership of StandaloneMmPkg

SecurityPkg/Tcg/Tcg2Smm/Tcg2Smm.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=1940
According to TCG PFP specification: the ACPI table must be
measured prior to any modification, and the measurement
must be same cross every boot cycle.
There is a fix 3a63c17ebc853cbb27d190729d01e27f68e65b94
for the HID data. However that is not enough.
The LAML/LASA and PCD configuration change may also cause
similar problem.
We need measure the table before any update.
Signed-off-by: Jiewen Yao <Jiewen.Yao@intel.com>
Reviewed-by: Chao Zhang <chao.b.zhang@intel.com>
=> SecurityPkg/Tcg2Smm: Measure the table before patch.

ArmPkg/Drivers/MmCommunicationDxe/MmCommunication.c, ArmPkg/Drivers/MmCommunicationDxe/MmCommunication.inf
PI defines a few architected events that have significance in the MM
context as well as in the non-secure DXE context. So register notify
handlers for these events, and relay them into the standalone MM world.
Reviewed-by: Achin Gupta <achin.gupta@arm.com>
=> ArmPkg/MmCommunicationDxe: signal architected PI events into MM context

BaseTools/Source/Python/AutoGen/ModuleAutoGen.py, BaseTools/Source/Python/AutoGen/PlatformAutoGen.py, BaseTools/Source/Python/build/build.py
BZ: https://bugzilla.tianocore.org/show_bug.cgi?id=2371
This patch is to fix a regression issue that build fails
if multiple build targets given.
Two changes cause this regression issue.
One is AutoGen object __hash__ function only
hash file path and arch, missing ToolChain and build target.
The other is changing the multiple-thread-genfds function as default
build behavior. To generate the genffs command to Makefile, there
is a global data set is used, GenFdsGlobalVariable, which cause build
tool use the data of first build-target build in
the second build-target build.
Cc: Steven Shi <steven.shi@intel.com>
=> BaseTools: Fix build failure when multiple build targets given

BaseTools/Conf/tools_def.template
BZ:https://bugzilla.tianocore.org/show_bug.cgi?id=2423
That commit 13c5e34a1b introduces the first two UTF-8
characters (the quote ') in an otherwise all-ascii file.
In Conf\tools_def.template
There is tow lines of
Notes: Since this tool chain is obsolete, it doesn't enable
the compiler option for included header file list generation,
we replaces the two offending quotes by proper ascii quotes
The patch is going to fix this issue
=> BaseTools:replaces the two offending quotes by ascii quotes

Maintainers.txt
Created new email account that will not append legal disclaimers to
my responses/patches.
Switching to NetworkPkg maintainer.
=> Maintainers.txt: Update email address and role

BaseTools/Source/Python/build/build.py
BZ: https://bugzilla.tianocore.org/show_bug.cgi?id=2311
In patch set 13c5e34a - 0c3e8e99, we implemented incremental build with
using compiler/pre-processor generate dependent header file function.
A issue is found for MSVC compiler, that the cl.exe /showIncludes
build option generate header file list to either stdout or stderr.
For .c file, the header file list is print out to stdout while for
.vfr, .aslc and .nasm file, the file list is print out to stderr.
The build tool use two threads to process the message from stdout and
stderr, but to generate correct *.deps file, build tool need to
combine the header file list from stderr and other messages from stdout
together with correct time sequence order.
So this patch is trying to combine the stdout and stderr together for
the process …
=> BaseTools: Resolve a issue of Incremental build

MdePkg/Include/IndustryStandard/Spdm.h
Align to SPDM 1.0.0 specification.
Fix Nonce data structure error.
Signed-off-by: Jiewen Yao <jiewen.yao@intel.com>
=> MdePkg/Spdm: fix Nonce structure error.

ShellPkg/Application/Shell/ShellProtocol.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2395
Errors happened in the arguments parsing is not a critical error.
And it would miss the error status code in the release version of shell.
So replace the ASSERT with returning error status code while fail
parsing command-line in UpdateArgcArgv.
Cc: Linson Augustine <linson.augustine@intel.com>
=> ShellPkg/ShellProtocol: Return error code while fail parsing cmd-line

MdePkg/Include/IndustryStandard/PciExpress21.h
Device Control 2 Structure have an issue.
LtrMechanism - there is 2 bits instead of 1.
Signed-off-by: Daniel Pawel Banaszek <daniel.pawel.banaszek@intel.com>
=> MdePkg PciExpress21: PCI_REG_PCIE_DEVICE_CONTROL2 struct has 17 bits

MdePkg/Include/Base.h
BZ: https://bugzilla.tianocore.org/show_bug.cgi?id=2393
CLANGPDB does not define __GNUC__, but it does define __clang__. Check
for the __clang__ preprocessor definition to use __builtin_offsetof to
implement the OFFSET_OF macro.
Signed-off-by: Alex James <theracermaster@gmail.com>
=> MdePkg: Use __builtin_offset with CLANGPDB toolchain

MdePkg/Include/IndustryStandard/UefiTcgPlatform.h
The latest TCG PFP specification (TCG PC Client Platform Firmware Profile
Specification, Revision 1.05) added new data structure. For example,
the SPDM device measurement. This patch adds the new content.
Signed-off-by: Jiewen Yao <jiewen.yao@intel.com>
=> MdePkg/Tcg: Add new definition in TCG PFP spec.

BaseTools/Source/C/Makefiles/NmakeSubdirs.py
This issue happens under two conditions.
1. Unicode language environment in Windows
2. Python2 (Not reproducible with Python3)
Step to reproduce
C:\edk2>edksetup.bat forcerebuild
The edksetup.bat stuck at 'nmake cleanall'.
Signed-off-by: Aiden Park <aiden.park@intel.com>
=> edksetup.bat stuck on unicode locale Windows

BaseTools/Scripts/SetupGit.py
If git finds a '\r' character in the message, then it
converts the entire message content into Quoted-Printable
encoding. It appears that when groups.io converts the QP
encoding back to text format, the '\r' characters somehow
become '\n'. To workaround this, the SetupGit.py script
will now explicitly set the sendemail.transferEncoding git
config option to '8bit'
Signed-off-by: Nate DeSimone <nathaniel.l.desimone@intel.com>
=> BaseTools/Scripts: Add sendemail.transferEncoding to SetupGit.py

UefiPayloadPkg/Library/PlatformBootManagerLib/PlatformConsole.c, UefiPayloadPkg/UefiPayloadPkg.fdf, UefiPayloadPkg/UefiPayloadPkgIa32.dsc, UefiPayloadPkg/UefiPayloadPkgIa32X64.dsc
Add PS2 keyboard support.
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=2316
This patch adds PS2 keyboard support in boot manager, and
add a build flag PS2_KEYBOARD_ENABLE for PS2 keyboard to
build PS2 keyboard driver and SIO driver. Be default the
build flag is not enabled since PS2 keyboard is not common
used. could use -DPS2_KEYBOARD_ENABLE to enable build it
if need this feature.
Reviewed-by: Benjamin You <benjamin.you@intel.com>
=> UefiPayloadPkg/BootManager: Add PS2 keyboard support

UefiCpuPkg/PiSmmCpuDxeSmm/MpService.c, UefiCpuPkg/PiSmmCpuDxeSmm/PiSmmCpuDxeSmm.h
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2388
Token is new introduced by MM MP Protocol. Current logic allocate Token
every time when need to use it. The logic caused SMI latency raised to
very high. Update logic to allocate Token buffer at driver's entry point.
Later use the token from the allocated token buffer. Only when all the
buffer have been used, then need to allocate new buffer.
Former change (9caaa79dd7e078ebb4012dde3b3d3a5d451df609) missed
PROCEDURE_TOKEN part, this change covers it.
Signed-off-by: Eric Dong <eric.dong@intel.com>
=> UefiCpuPkg/PiSmmCpuDxeSmm: Pre-allocate PROCEDURE_TOKEN buffer

.mailmap
https://edk2.groups.io/g/devel/message/52894
http://mid.mail-archive.com/20200106115415.11624-1-philmd@redhat.com
On 01/06/20 12:53, Philippe Mathieu-Daudé wrote:
> The .mailmap git feature helps fixing commit mistakes (in name/email).
>
> The easiest way to use it is with the --use-mailmap flag:
>
>   $ git log --use-mailmap
>
> See documentation [1] and [2], and interesting blog [3].
>
> Laszlo replied [4] to v1 explaining stewards want to avoid avoid
> cross-domain mapping, and suggested to split in per email-address
> patches, so contributors can individually Ack/Nack.
>
> This v4 collects the patches of the 30 developers who replied to
> the v2 [5] and v3 [6] with their R-b tag.
>
> I dropped the unreviewed patches and am cc'ing this series to the
> Tianocore stewards, as suggested …
=> [edk2-devel] [PATCH v4 00/32] .mailmap: Add mailmap file to have a cleaner git history -- push

edksetup.bat
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2404
Set the below two environment variables in edksetup.bat:
set CLANG_HOST_BIN=n
set CLANG_BIN=C:\Program Files\LLVM\bin\
In Windows, set CLANG_HOST_BIN=n to use nmake command
The CLANG_BIN is only be set if it is not defined.
=> edksetup.bat: Simplify the step to use CLANGPDB

UefiCpuPkg/Library/MpInitLib/Microcode.c, UefiCpuPkg/Library/MpInitLib/MpLib.h
This patch removes the unnecessary alignment check on microcode patch
TotalSize introduced by commit d786a172. The TotalSize has already been
checked with 1K alignment and MAX_ADDRESS in previous code as below:
if ( (UINTN)MicrocodeEntryPoint > (MAX_ADDRESS - TotalSize) ||
((UINTN)MicrocodeEntryPoint + TotalSize) > MicrocodeEnd ||
(DataSize & 0x3) != 0 ||
(TotalSize & (SIZE_1KB - 1)) != 0 ||
TotalSize < DataSize
) {
BZ link,
https://bugzilla.tianocore.org/show_bug.cgi?id=2429
=> UefiCpuPkg: Remove alignment check when calculate microcode size.

UefiCpuPkg/Library/MpInitLib/Microcode.c
This patch updates the microcode loader to always perform a microcode
detect and load on both BSP and AP processor. This is to fix a potential
microcode revision mismatch issue in below situation:
1. Assume there are two microcode co-exists in flash: one production
version and one debug version microcode.
2. FIT loads production microcode to BSP and all AP.
3. UefiCpuPkg loader loads debug microcode to BSP, and skip the loading
on AP.
As a result, different microcode patches are loaded to BSP and AP, and
trigger microcode mismatch error during OS boot.
BZ link: https://bugzilla.tianocore.org/show_bug.cgi?id=2431
=> UefiCpuPkg: Always load microcode patch on AP processor.

CryptoPkg/Library/BaseCryptLib/Pk/CryptRsaBasic.c, CryptoPkg/Library/BaseCryptLib/Pk/CryptRsaExt.c
BZ: https://bugzilla.tianocore.org/show_bug.cgi?id=2389
Currently RSA signing scheme support is available for MD5, SHA-1 or
SHA-256 algorithms.The fix is to extend this support for SHA384 and
SHA512.
Signed-off-by: Pavana.K <pavana.k@intel.com>
=> pull-request-branch-base-bz2389

MdeModulePkg/Include/Protocol/PlatformBootManager.h, MdeModulePkg/Library/UefiBootManagerLib/BmBoot.c, MdeModulePkg/Library/UefiBootManagerLib/InternalBm.h, MdeModulePkg/Library/UefiBootManagerLib/UefiBootManagerLib.inf, MdeModulePkg/MdeModulePkg.dec
Add edk2 platform boot manager protocol which would have platform
specific refreshes to the auto enumerated as well as NV boot options
for the platform.
Signed-off-by: Ashish Singhal <ashishsingha@nvidia.com>
=> pull-request-branch-add-platform-boot-manager-protocol

UefiCpuPkg/PiSmmCpuDxeSmm/MpService.c
This issue caused by below change:
SHA-1: b948a496150f4ae4f656c0f0ab672608723c80e6
* UefiCpuPkg/PiSmmCpuDxeSmm: Pre-allocate PROCEDURE_TOKEN buffer
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2388
Signed-off-by: Eric Dong <eric.dong@intel.com>
=> UefiCpuPkg/PiSmmCpuDxeSmm: Add missed comments for parameter.

MdePkg/Library/DxeRuntimeDebugLibSerialPort/DebugLib.c, MdePkg/Library/DxeRuntimeDebugLibSerialPort/DxeRuntimeDebugLibSerialPort.inf, MdePkg/Library/DxeRuntimePciExpressLib/DxeRuntimePciExpressLib.inf, MdePkg/Library/DxeRuntimePciExpressLib/PciExpressLib.c, MdePkg/Library/PciSegmentLibSegmentInfo/DxeRuntimePciSegmentLib.c, MdePkg/Library/PciSegmentLibSegmentInfo/DxeRuntimePciSegmentLibSegmentInfo.inf, MdePkg/Library/UefiDebugLibConOut/DebugLibConstructor.c, MdePkg/Library/UefiDebugLibConOut/UefiDebugLibConOut.inf, MdePkg/Library/UefiDebugLibDebugPortProtocol/DebugLibConstructor.c, MdePkg/Library/UefiDebugLibDebugPortProtocol/UefiDebugLibDebugPortProtocol.inf, MdePkg/Library/UefiDebugLibStdErr/DebugLibConstructor.c, MdePkg/Library/UefiDebugLibStdErr/UefiDebugLibStdErr.inf, MdePkg/Library/UefiRuntimeLib/RuntimeLib.c, MdePkg/Library/UefiRuntimeLib/UefiRuntimeLib.inf
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2446
There are many firmwares in the wild not supporting CreateEventEx,
including devices less than 5 years old.
Signed-off-by: Vitaly Cheptsov <vit9696@protonmail.com>
=> MdePkg: Do not use CreateEventEx unless required

MdeModulePkg/Bus/Pci/SdMmcPciHcDxe/SdMmcPciHci.c, MdeModulePkg/Bus/Pci/SdMmcPciHcDxe/SdMmcPciHci.h
Changed @rtval to @retval in SdMmcHcStartSdClock
function description.
Signed-off-by: Mateusz Albecki <mateusz.albecki@intel.com>
=> MdeModulePkg/SdMmcPciHcDxe: Fix unknown doxygen tag error

MdeModulePkg/Universal/SetupBrowserDxe/IfrParse.c
Update data type of variables which save the opcode numbers
to UINTN, in case some configuration module has lots of
configuration items.
Signed-off-by: Brian R Haug <brian.r.haug@intel.com>
=> MdeModulePkg/Setup: Update opcode number variable type to UINTN

BaseTools/Source/Python/Capsule/GenerateCapsule.py, BaseTools/Source/Python/Common/Uefi/Capsule/CapsuleDependency.py
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2412
Capsule generate tool support encode capsule dependencies through '-j'
command with a JSON file. To enable dependency feature, "Dependencies"
field for each payload in JSON file is required.
The value of "Dependencies" field is C style infix notation expression.
For example:
"Dependencies":"72E2945A-00DA-448E-9AA7-075AD840F9D4 > 0x00000001"
The relation of Dependency Expression Opcode in UEFI2.8 chap 23.2 and
infix notation expression value is as follows:
+-----------------------------+--------------------------+
| OPCODE                      | INFIX EXPRESSION VALUE   |
+-----------------------------+--------------------------+
| 0x00 (PUSH_GUID)            | {GUID}                   |
| 0x01 (PUSH_VERSION)         | {UINT32} …
=> BaseTools/Capsule: Add capsule dependency support

ShellPkg/Library/UefiShellAcpiViewCommandLib/AcpiParser.c, ShellPkg/Library/UefiShellAcpiViewCommandLib/AcpiParser.h, ShellPkg/Library/UefiShellAcpiViewCommandLib/Parsers/Srat/SratParser.c
Add support for revision 3 of System Resource Affinity Table (SRAT).
Decode and dump the new Generic Initiator Affinity Structure.
Validate the Device Handle Type field inside the Generic Initiator
Affinity Structure.
Reviewed-by: Alexei Fedorov <Alexei.Fedorov@arm.com>
Reviewed-by: Jaben Carsey <jaben.carsey@intel.com>
Tested-by: Sudipto Paul <sudipto.paul@arm.com>
Signed-off-by: Krzysztof Koch <krzysztof.koch@arm.com>
=> ShellPkg: acpiview: Update SRAT parser to ACPI 6.3

MdePkg/Include/Base.h
#if MACRO is not good style. It should be changed to
#ifdef MACRO style or #if defined (MACRO) style.
=> MdePkg Base.h: Use correct style to check the defined macro

MdeModulePkg/Universal/Variable/RuntimeDxe/Variable.c
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=2457
This commit fixes an offset calculation that is used to write the
VarErrorFlag UEFI variable to the UEFI variable runtime cache.
Currently a physical address is used instead of an offset. This
commit changes the offset to zero with a length of the entire
non-volatile variable store so the entire non-volatile variable
store buffer in SMRAM (with the variable update modification) is
copied to the runtime variable cache. This follows the same pattern
used in other SynchronizeRuntimeVariableCache () calls for
consistency.
* Observable symptom: An exception in SMM will most likely occur
due to the invalid memory reference when the VarErrorFlag variable
is written. The variable is most commonly written when the UEFI
variable store is full. …
=> MdeModulePkg/Variable: Fix VarErrorFlag RT cache offset calculation

Maintainers.txt
Leif now works at NUVIA Inc, update email address accordingly.
Signed-off-by: Leif Lindholm <leif.lindholm@linaro.org>
Tested-by: Philippe Mathieu-Daude <philmd@redhat.com>
=> Maintainers.txt: update email address for Leif Lindholm

FmpDevicePkg/FmpDxe/Dependency.c, FmpDevicePkg/FmpDxe/Dependency.h, FmpDevicePkg/FmpDxe/FmpDxe.c, FmpDevicePkg/FmpDxe/FmpDxe.inf, FmpDevicePkg/FmpDxe/FmpDxeLib.inf, MdeModulePkg/Application/CapsuleApp/CapsuleDump.c, MdePkg/Include/Guid/SystemResourceTable.h, MdePkg/Include/Protocol/FirmwareManagement.h
This series implements Fmp Capsule Dependency.
Fmp Capsule Dependency is an incremental change of Fmp Capsule Update.
The capsule format is extended to include a set of binary encoded dependency expression.
The dependency expression is evaluated before update is applied.
This feature is defined in UEFI Spec 2.8.
=> Fmp Capsule Dependency implementation

UefiCpuPkg/Library/MpInitLib/MpLib.c
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=2474
Previous commit d786a17232:
UefiCpuPkg/MpInitLib: Reduce the size when loading microcode patches
Removed the below assignments for the 'InitFlag' field of CPU_MP_DATA
structure in function MpInitLibInitialize() when APs are waken up to do
some initialize sync:
CpuMpData->InitFlag  = ApInitReconfig;
...
CpuMpData->InitFlag = ApInitDone;
The above commit mistakenly assumed the 'InitFlag' field will have a value
of 'ApInitDone' when the APs have been successfully waken up before. And
since there is no explicit comparision for the 'InitFlag' field with the
'ApInitReconfig' value. The commit removed those assignments.
However, under some cases (e.g. when variable OldCpuMpData is not NULL,
which means function CollectProcessorCount() will …
=> UefiCpuPkg/MpInitLib: Fix possible uninitialized 'InitFlag' field

BaseTools/Source/Python/AutoGen/GenMake.py, BaseTools/Source/Python/AutoGen/IncludesAutoGen.py, BaseTools/Source/Python/build/build.py
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=2451
If removing a header file from source code and file
system, the incremental build will fail.
This patch is to fix this issue by setting each header file
as a target without any actions in makefile.
=> BaseTools: Fixed a incremental build bug

SecurityPkg/Library/DxeImageVerificationLib/DxeImageVerificationLib.c
https://bugzilla.tianocore.org/show_bug.cgi?id=2129
https://edk2.groups.io/g/devel/message/53314
http://mid.mail-archive.com/20200116190705.18816-1-lersek@redhat.com
=> [edk2-devel] [PATCH 00/11] SecurityPkg/DxeImageVerificationHandler: fix retval for "deny" policy -- push

CryptoPkg/CryptoPkg.dec, CryptoPkg/CryptoPkg.dsc, CryptoPkg/CryptoPkg.uni, CryptoPkg/Include/Library/HashApiLib.h, CryptoPkg/Library/BaseHashApiLib/BaseHashApiLib.c, CryptoPkg/Library/BaseHashApiLib/BaseHashApiLib.inf, CryptoPkg/Library/BaseHashApiLib/BaseHashApiLib.uni
https://bugzilla.tianocore.org/show_bug.cgi?id=2151
Currently, the UEFI drivers using the SHA/SM3 hashing algorithms use hard-coded
API to calculate the hash, for instance, sha_256(...), etc. Since SHA384 and/or
SM3_256 are being increasingly adopted for robustness, it becomes cumbersome to
modify each driver that calls into hash calculating API.
To better achieve this, we are proposing a Unified API, which can be used by UEFI
drivers, that provides the drivers with flexibility to use the desired hashing
algorithm based on the required robnustness.
Alternatively, the design document is also attached to Bugzilla,
https://bugzilla.tianocore.org/show_bug.cgi?id=2151 …
=> CryptoPkg/BaseHashApiLib: Implement Unified Hash Calculation API

BaseTools/Source/Python/Workspace/DscBuildData.py
https://bugzilla.tianocore.org/show_bug.cgi?id=2494
When using structured PCDs, a C application is auto generated
to fill in the structured PCD value.  The C application uses
the standard include files <stdio.h>, <stdlib.h>, and <string.h>.
This C application also supports include paths from package DEC
files when a structured PCD declaration provides a <Packages>
list.  The complete list of include paths are -I options for
include paths from package DEC files and the compiler's standard
include paths.
-I include paths are higher priority than the standard include
paths.  If the -I included paths from package DEC files contain
<stdio.h>, <stdlib.h>, or <string.h> the wrong include files are
used to compile the C application for the structured PCD value.
Update GenerateByteArrayValue() to …
=> BaseTools/DscBuildData: Fix PCD autogen include file conflict

CryptoPkg/Library/BaseCryptLibNull/BaseCryptLibNull.inf, CryptoPkg/Library/BaseCryptLibNull/Kdf/CryptHkdfNull.c
https://bugzilla.tianocore.org/show_bug.cgi?id=2493
The BaseCryptLib was expanded to add the HkdfSha256ExtractAndExpand()
service in the following commit:
https://github.com/tianocore/edk2/commit/4b1b7c1913092d73d689d8086dcfa579c0217dc8
When BaseCryptLibNull was added in the commit below, this new
service was not included.
https://github.com/tianocore/edk2/commit/d95de082da01f4a4cb3ebf87e15972a12d0f8d53
=> CryptoPkg/BaseCryptLibNull: Add missing HkdfSha256ExtractAndExpand()

UefiCpuPkg/Library/MpInitLib/Microcode.c
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=2498
Commit fd30b00707 updated the logic in function MicrocodeDetect() that
will directly use the CPUID and PlatformID information from the 'CpuData'
field in the CPU_MP_DATA structure, instead of collecting these
information for each processor via AsmCpuid() and AsmReadMsr64() calls
respectively.
At that moment, this approach worked fine for APs. Since:
a) When the APs are waken up for the 1st time (1st MpInitLibInitialize()
entry at PEI phase), the function InitializeApData() will be called for
each AP and the CPUID and PlatformID information will be collected.
b) During the 2nd entry of MpInitLibInitialize() at DXE phase, when the
APs are waken up again, the function InitializeApData() will not be
called, which means the CPUID and …
=> UefiCpuPkg/MpInitLib: Always get CPUID & PlatformID in MicrocodeDetect()

MdeModulePkg/Universal/MemoryTest/GenericMemoryTestDxe/LightMemoryTest.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2463
Perform Data and Address line test only if not ignore memory test.
=> MdeModulePkg: Perform test only if not ignore memory test

MdePkg/Include/Base.h, MdePkg/Include/Ia32/ProcessorBind.h, MdePkg/Include/X64/ProcessorBind.h
=> MdePkg Base.h: Use correct style to check macro _MSC_VER value

BaseTools/BinWrappers/PosixLike/AmlToHex, BaseTools/BinWrappers/WindowsLike/AmlToHex.bat, BaseTools/Conf/build_rule.template, BaseTools/Source/Python/AmlToHex/AmlToHex.py
The "-tc" option of the iasl compiler allows to generate a
.hex file containing a C array storing AML bytecode.
An online discussion suggested that this "-tc" option
was specific to the iasl compiler and it shouldn't be relied
on. This conversation is available at:
https://edk2.groups.io/g/devel/topic/39786201#49659
A way to address this issue is to implement a compiler
independent script that takes an AML file as input, and
generates a .hex file.
This patch implements a Python script that converts an AML
file to a .hex file, containing a C array storing AML bytecode.
This scipt has been tested with the AML output from the
following compilers supported by the EDKII implementation:
* Intel ASL compiler
* Microsoft ASL compiler …
=> BaseTools: Script for converting .aml to .hex

MdeModulePkg/Library/BaseSerialPortLib16550/BaseSerialPortLib16550.c
Before writing data to FIFO, wait for the serial port to be ready,
to make sure both the transmit FIFO and shift register empty. Code
comment was saying the right thing but code was missing a check.
Signed-off-by: Ashish Singhal <ashishsingha@nvidia.com>
=> MdeModulePkg/BaseSerialPortLib16550: Fix Serial Port Ready

BaseTools/Conf/tools_def.template
BZ: https://bugzilla.tianocore.org/show_bug.cgi?id=2487
The call stack unwindability of the COFF X64 binary requires
the binary to remain the pdata and xdata sections.
Details see the MSVC X64 calling convertion doc in below link:
https://docs.microsoft.com/en-us/cpp/build/x64-calling-convention
Current build options discard or zero the data in pdata and xdata
sections which cause the debugger cannot correctly unwind the
X64 binary call stack in the runtime.
Enhance the build options to force emit the unwind tables and
keep the data of pdata and xdata sections correct in the binary.
Signed-off-by: Steven Shi <steven.shi@intel.com>
=> BaseTools: Enhance call stack unwindability for CLANGPDB x64 binary

SecurityPkg/Library/DxeTcgPhysicalPresenceLib/DxeTcgPhysicalPresenceLib.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2472
Replace the ASSERT with the error code return in the TpmPhysicalPresence
and GetTpmCapability.
Add missing error checking after call TpmPhysicalPresence in
TcgPhysicalPresenceLibProcessRequest.
=> SecurityPkg/TcgPhysicalPresenceLib: Replace the ASSERT with error code

MdeModulePkg/MdeModulePkg.dec, MdeModulePkg/MdeModulePkg.uni, MdeModulePkg/Universal/CapsuleRuntimeDxe/CapsuleRuntimeDxe.inf, MdeModulePkg/Universal/CapsuleRuntimeDxe/CapsuleService.c
V2:
Add feature PCD for this change.
Current UpdateCapsule service will reject all non-reset capsule images and
return EFI_OUT_OF_RESOURCE if the system is at runtime. This will block a
platform CapsuleLib from implementing ProcessCapsuleImage() with runtime
capsule processing capability.
This patch removes this restriction. The change is controled by a feature
PCD PcdSupportProcessCapsuleAtRuntime, and the default value is FALSE
which means not enable this feature.
BZ: https://bugzilla.tianocore.org/show_bug.cgi?id=2501
=> MdeModulePkg/Capsule: Remove RT restriction in UpdateCapsule service.

ArmPlatformPkg/Scripts/Ds5/firmware_volume.py
Increase length of path that can be read from system from 200 to 400 to
allow for longer build paths.
Reviewed-by: Ard Biesheuvel <ard.biesheuvel@linaro.org>
=> ArmPlatformPkg/Ds5: Increase path length to 400

BaseTools/Source/Python/AutoGen/GenMake.py
The .map file is not update to FFS_OUTPUT_DIR folder
in the incremental build.
=> BaseTools: Fixed a Incremental build issue

SecurityPkg/Library/DxeTpm2MeasureBootLib/DxeTpm2MeasureBootLib.c, SecurityPkg/Library/DxeTpmMeasureBootLib/DxeTpmMeasureBootLib.c
The DxeTpmMeasureBootHandler and DxeTpm2MeasureBootHandler handlers
are SECURITY2_FILE_AUTHENTICATION_HANDLER prototype. This prototype
can not return EFI_INVALID_PARAMETER.
The prototype documentation states it returns EFI_ACCESS_DENIED if:
"The file specified by File and FileBuffer did not authenticate,
and the platform policy dictates that the DXE Foundation may not
use File."
Correct the documentation, and add a early check, returning
EFI_ACCESS_DENIED when File is NULL.
Noticed while reviewing commit 6d57592740cdd0b6868baeef7929d6e6fef.
Signed-off-by: Philippe Mathieu-Daude <philmd@redhat.com>
Reviewed-by: Jian J Wang …
=> SecurityPkg: Fix incorrect return value when File is NULL

ShellPkg/Application/Shell/ShellParametersProtocol.c, ShellPkg/Application/Shell/ShellParametersProtocol.h, ShellPkg/Library/UefiShellAcpiViewCommandLib/AcpiParser.c, ShellPkg/Library/UefiShellAcpiViewCommandLib/Parsers/Dbg2/Dbg2Parser.c, ShellPkg/Library/UefiShellAcpiViewCommandLib/Parsers/Fadt/FadtParser.c, ShellPkg/Library/UefiShellAcpiViewCommandLib/Parsers/Gtdt/GtdtParser.c, ShellPkg/Library/UefiShellAcpiViewCommandLib/Parsers/Iort/IortParser.c, ShellPkg/Library/UefiShellAcpiViewCommandLib/Parsers/Madt/MadtParser.c, ShellPkg/Library/UefiShellAcpiViewCommandLib/Parsers/Pptt/PpttParser.c, ShellPkg/Library/UefiShellAcpiViewCommandLib/Parsers/Rsdp/RsdpParser.c, ShellPkg/Library/UefiShellAcpiViewCommandLib/Parsers/Slit/SlitParser.c, ShellPkg/Library/UefiShellAcpiViewCommandLib/Parsers/Srat/SratParser.c
Check if global pointers have been successfully updated before they
are used for further table parsing.
=> ShellPkg: Validate global pointer before use

MdePkg/Include/IndustryStandard/SmBios.h
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2482
Refer to DSP0134_3.3.0.pdf, there are two additional DWORD added
for type 17. One is "Extended Speed", the other is "Extended
Configured Memory Speed". The lack of these field may cause strange
error in some operating systems.
=> MdePkg/SmBios.h: Add two additional DWORD for smbios 3.3.0 type17

BaseTools/Conf/tools_def.template
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2397
Signed-off-by: Vitaly Cheptsov <vit9696@protonmail.com>
=> BaseTools: Switch to GNU mode for CLANGPDB

UnitTestFrameworkPkg/Library/UnitTestLib/Assert.c, UnitTestFrameworkPkg/Library/UnitTestLib/Log.c
https://bugzilla.tianocore.org/show_bug.cgi?id=2512
Remove extra sets of parenthesis that generate warnings on XCODE5
builds.
=> UnitTestFrameworkPkg/UnitTestLib: Fix XCODE parenthesis issues

MdePkg/Include/IndustryStandard/PciExpress50.h
The header includes Physical Layer PCI Express Extended Capability
definitions based on section 7.7.6 of PCI Express Base Specification 5.0.
Signed-off-by: Felix Polyudov <felixp@ami.com>
=> MdePkg: Add PCI Express 5.0 Header File

BaseTools/Source/Python/Ecc/MetaFileWorkspace/MetaFileParser.py
BZ:https://bugzilla.tianocore.org/show_bug.cgi?id=2142
gAdvancedFeaturePkgTokenSpaceGuid.PcdSmbiosType0BiosInformation|
{0x0}|SMBIOS_TABLE_TYPE0|0x80010000 {
<HeaderFiles>
IndustryStandard/SmBios.h
<Packages>
MdePkg/MdePkg.dec
AdvancedFeaturePkg/AdvancedFeaturePkg.dec
}
If there's a PcdStructHF or PcdStructPKGs in StructPcd,
EccTool report error,IndexError: list index out of range
This patch is going to fix this issue
=> BaseTools:fix Ecc tool issue for check StructPcd

BaseTools/Source/Python/build/BuildReport.py
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2304
SyntaxWarning: "is" with a literal. Did you mean "=="?
Using "is" instead of "==" is an irregular syntax
Cc: Bob C Feng <bob.c.feng@intel.com>
=> BaseTools: Fixed build failure when using python38

MdePkg/Library/BaseSafeIntLib/SafeIntLib.c
https://bugzilla.tianocore.org/show_bug.cgi?id=2525
SafeUint64Mult() looks for 64-bit overflows and performs
several 32-bit multiples with 64-bit results to check for
all possible overflow conditions.  IA32 builds using VS20xx
with optimizations enabled are producing a reference to
the _allmull intrinsic.
The fix is to use MultU64x64() instead of '*' for
these operations.  These are safe because the inputs
are guaranteed to have the upper 32-bits clear, which
means MultU64x64() can never overflow with those inputs.
=> MdePkg/BaseSafeIntLib: Fix VS20xx IA32 link failures

BaseTools/Source/Python/AutoGen/IncludesAutoGen.py
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=2520
Incremental build failure in CLANGPDB tool chain on Windows host
The build failure is like below when do incremental build.
The root cause is in generated deps_target file. It has one line ":".
=> BaseTools:build failure in CLANGPDB tool chain

BaseTools/Conf/tools_def.template
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2524
remove -DNO_MSABI_VA_FUNCS option in CLANGPDB tool chain After CLANGPDB is
switched to GNU mode, to use MS ABI version of GCC built-in macros for
variable argument lists as same as CLANG38 tool chain.
=> BaseTools: remove -DNO_MSABI_VA_FUNCS option in CLANGPDB tool chain

MdePkg/Include/IndustryStandard/Acpi50.h, MdePkg/Include/IndustryStandard/Acpi51.h, MdePkg/Include/IndustryStandard/Acpi60.h, MdePkg/Include/IndustryStandard/Acpi61.h, MdePkg/Include/IndustryStandard/Acpi62.h, MdePkg/Include/IndustryStandard/Acpi63.h
The Platform Communications Channel Table (PCCT) was defined in:
ACPI Specification Version 5.0, Errata A - Published Nov. 13, 2013.
Starting from the Acpi50.h header file, there are definitions
describing the table but a macro with the table's signature is missing.
This patch adds the definition of Platform Communications Channel
Table's signature to the relevant ACPI header files.
Signed-off-by: Krzysztof Koch <krzysztof.koch@arm.com>
=> MdePkg: Add PCCT table signature definition

UefiCpuPkg/Include/Library/RegisterCpuFeaturesLib.h, UefiCpuPkg/Library/CpuCommonFeaturesLib/CpuCommonFeaturesLib.c, UefiCpuPkg/Library/RegisterCpuFeaturesLib/CpuFeaturesInitialize.c, UefiCpuPkg/Library/RegisterCpuFeaturesLib/RegisterCpuFeatures.h, UefiCpuPkg/Library/RegisterCpuFeaturesLib/RegisterCpuFeaturesLib.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=1584
The flow of CPU feature initialization logic is:
1. BSP calls GetConfigDataFunc() for each thread/AP;
2. Each thread/AP calls SupportFunc() to detect its own capability;
3. BSP calls InitializeFunc() for each thread/AP.
There is a design gap in step #3. For a package scope feature that only
requires one thread of each package does the initialization operation,
what InitializeFunc() currently does is to do the initialization
operation only CPU physical location Core# is 0.
But in certain platform, Core#0 might be disabled in hardware level
which results the certain package scope feature isn't initialized at
all.
The patch adds a new field First to indicate the CPU's location in
its parent scope.
First.Package is set for all …
=> UefiCpuPkg/CpuFeature: Introduce First to indicate 1st unit.

UefiCpuPkg/Library/RegisterCpuFeaturesLib/CpuFeaturesInitialize.c
Match data type and format specifier for printing.
1. Type cast ProcessorNumber and FeatureIndex to UINT32
as %d only expects a UINT32.
2. Use %08x instead of %08lx for CacheControl to print Index
as it is UINT32 type.
3. Use %016lx instead of %08lx for MemoryMapped to print
(Index | LShiftU64 (HighIndex, 32)) as it is UINT64 type.
Signed-off-by: Star Zeng <star.zeng@intel.com>
=> UefiCpuPkg RegisterCpuFeaturesLib: Match data type and format specifier

MdeModulePkg/Core/Dxe/Hand/Handle.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=1869
The UEFI spec requires that if any error occurs in
UninstallMultipleProtocolInterfaces(), EFI_INVALID_PARAMETER is returned
and not the return code of UninstallProtocolInterface().
Signed-off-by: Heinrich Schuchardt <xypron.glpk@gmx.de>
=> MdeModulePkg: Make retval in UninstallMultipleProtocol follow Spec

ShellPkg/Library/UefiShellAcpiViewCommandLib/Parsers/Dbg2/Dbg2Parser.c, ShellPkg/Library/UefiShellAcpiViewCommandLib/Parsers/Gtdt/GtdtParser.c, ShellPkg/Library/UefiShellAcpiViewCommandLib/Parsers/Iort/IortParser.c, ShellPkg/Library/UefiShellAcpiViewCommandLib/Parsers/Madt/MadtParser.c, ShellPkg/Library/UefiShellAcpiViewCommandLib/Parsers/Pptt/PpttParser.c, ShellPkg/Library/UefiShellAcpiViewCommandLib/Parsers/Srat/SratParser.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2534
Extend validation of ACPI structure lengths which are read from the
ACPI table being parsed. Additionally check if the structure 'Length'
field value is positive. If not, stop parsing the faulting table.
Some ACPI tables define internal structures of variable size. The
'Length' field inside the substructure is used to update a pointer used
for table traversal. If the byte-length of the structure is equal to 0,
acpiview can enter an infinite loop. This condition can occur if, for
example, the zero-allocated ACPI table buffer is not fully populated.
This is typically a bug on the ACPI table writer side.
In short, this method helps acpiview recover gracefully from a
zero-valued ACPI structure length.
Signed-off-by: Krzysztof Koch …
=> ShellPkg: acpiview: Prevent infinite loop if structure length is 0

NetworkPkg/ArpDxe/ArpImpl.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2031
This patch triggers the RecycleEvent for invalid ARP packets.
Prior to this, we would just ignore invalid ARP packets,
and never free them.
Signed-off-by: Nicholas Armour <nicholas.armour@intel.com>
=> NetworkPkg/ArpDxe: Recycle invalid ARP packets (CVE-2019-14559)

OvmfPkg/QemuVideoDxe/Driver.c
https://bugzilla.tianocore.org/show_bug.cgi?id=2555
http://mid.mail-archive.com/20200224171741.7494-1-lersek@redhat.com
https://edk2.groups.io/g/devel/message/54760
=> [edk2-devel] [PATCH edk2-stable202002] OvmfPkg/QemuVideoDxe: unbreak "secondary-vga" and "bochs-display" support -- push

BaseTools/Source/Python/AutoGen/IncludesAutoGen.py
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2563
This patch is to fix a incremental build regression bug
which happen when using nmake. That's introduced by 818283de3f6d.
If there is white space before !INCLUDE instruction, nmake will not
process it. Source code's dependent header files are listed in
${deps_file} file, if it's not included successfully, nmake will
not detect the change of those header file.
This patch has been verified in Windows with VS2015 and Linux with GCC5.
The header file add/modify/delete can trig the incremental build with this fix.
There is no impact on the clean build.
Cc: Pierre Gondois …
=> BaseTools: Remove invalid leading space before !INCLUDE in Makefile

UefiCpuPkg/Library/MpInitLib/MpLib.c, UefiCpuPkg/Library/MpInitLib/MpLib.h
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2556
This patch uses CPUID signature check to skip reading the PlatformId MSR,
which is not implemented on AMD processors.
The PlatformId is used for loading microcode patches, which is also not
supported and AMD-based platforms. To mitigate the PlatformId dependency,
PcdCpuMicrocodePatchAddress and PcdCpuMicrodePatchRegionSize must be set
to 0 (default value), in order to bypass microcode loading code paths.
Signed-off-by: Leo Duran <leo.duran@amd.com>
=> UefiCpuPkg/MpInitLib: Skip reading PlatformId on AMD processors.

ArmVirtPkg/Library/PlatformBootManagerLib/PlatformBm.c, ArmVirtPkg/Library/PlatformBootManagerLib/PlatformBootManagerLib.inf, OvmfPkg/Library/PlatformBootManagerLib/BdsPlatform.c, OvmfPkg/Library/PlatformBootManagerLib/PlatformBootManagerLib.inf
[edk2-devel] [PATCH 0/2] OvmfPkg, ArmVirtPkg: sync Timeout with PcdPlatformBootTimeOut
https://edk2.groups.io/g/devel/message/55379
http://mid.mail-archive.com/20200304094413.19462-1-lersek@redhat.com
=> [edk2-devel] [PATCH 0/2] OvmfPkg, ArmVirtPkg: sync Timeout with PcdPlatformBootTimeOut -- push

OvmfPkg/OvmfXen.dsc
Commit 859b55443a4253ba ("OvmfPkg/PlatformBootManagerLib: switch to
QemuLoadImageLib") replaced a dependency on LoadLinuxLib with one on
QemuLoadImageLib in the PlatformBootManagerLib implementation that is
shared between all OVMF builds, without taking into account that even
the Xen targeted builds incorporate this code, which is only used to
load kernels passed via the QEMU command line.
Since this is dead code on Xen, we can satisfy the dependency using
the generic version of QemuLoadImageLib, which does not rely on
LoadLinuxLib, which we can therefore drop from OvmfXen.dsc.
Fixes: 859b55443a4253bad8bb618d04a51b2ded67f24b
=> OvmfPkg/OvmfXen: fix build by providing QemuLoadImageLib resolution

BaseTools/Source/Python/Workspace/DscBuildData.py
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=2568
PcdValueInit shares the same Edk2\BaseTools\Source\C\PcdValueCommon.c.
To avoid the conflict, it should copy this file to its output directory,
If so, PcdValueCommon.c file will be private for PcdValueInit
=> BaseTools:copy the common PcdValueCommon.c to output directory

MdeModulePkg/Library/DeviceManagerUiLib/DeviceManager.c
GCC translates a simple assignment to memcpy, which EDKII doesn't provide.
See: https://www.mail-archive.com/edk2-devel@lists.01.org/msg11928.html
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=2547
Cc: Gilbert Chen <gilbert.chen@hpe.com>
=> MdeModulePkg: Use CopyMem instead of GUID assignment

MdeModulePkg/Universal/SetupBrowserDxe/Setup.c
From the function description of GetIfrBinaryData(), FormSetGuid can be
NULL. However, FormSetGuid is passed to IsZeroGuid(). This causes exception
when FormSetGuid is NULL.
Signed-off-by: Nickle Wang <nickle.wang@hpe.com>
=> MdeModulePkg/SetupBrowserDxe: Fix IsZeroGuid() ASSERT.

OvmfPkg/OvmfPkg.fdf.inc, OvmfPkg/OvmfPkgIa32.dsc, OvmfPkg/OvmfPkgIa32.fdf, OvmfPkg/OvmfPkgIa32X64.dsc, OvmfPkg/OvmfPkgIa32X64.fdf, OvmfPkg/OvmfPkgX64.dsc, OvmfPkg/OvmfPkgX64.fdf, OvmfPkg/PlatformPei/MemTypeInfo.c, OvmfPkg/PlatformPei/Platform.c, OvmfPkg/PlatformPei/Platform.h, OvmfPkg/PlatformPei/PlatformPei.inf, OvmfPkg/QemuFlashFvbServicesRuntimeDxe/FvbServicesRuntimeDxe.inf, OvmfPkg/QemuFlashFvbServicesRuntimeDxe/FvbServicesSmm.inf, OvmfPkg/QemuFlashFvbServicesRuntimeDxe/FwBlockService.c, OvmfPkg/QemuFlashFvbServicesRuntimeDxe/FwBlockService.h, OvmfPkg/QemuFlashFvbServicesRuntimeDxe/FwBlockServiceDxe.c, OvmfPkg/QemuFlashFvbServicesRuntimeDxe/FwBlockServiceSmm.c
https://bugzilla.tianocore.org/show_bug.cgi?id=386
https://edk2.groups.io/g/devel/message/55726
http://mid.mail-archive.com/20200310222739.26717-1-lersek@redhat.com
=> [edk2-devel] [PATCH 0/5] OvmfPkg: improve SMM comms security with adaptive MemoryTypeInformation -- push#2

OvmfPkg/Library/X86QemuLoadImageLib/X86QemuLoadImageLib.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2582
warning C4244: '=': conversion from 'UINTN' to 'UINT32', possible loss of data
With this fix, OvmfIa32, OvmfX64 and OvmfIa32X64 can pass build.
Signed-off-by: Liming Gao <liming.gao@intel.com>
=> OvmfPkg: Fix build failure with VS2015 tool chain

ArmVirtPkg/Library/ArmVirtGicArchLib/ArmVirtGicArchLib.c
ArmVirtGicArchLib was originally implemented before virtualization
emulation was implemented in QEMU, and the GICv2 model implemented only
the physical copy of control registers.
Enabling virtualization emulation to QEMU adds also the virtual copy,
doubling the RegSize returned by FindCompatibleNodeReg () in
ArmVirtGicArchLibConstructor (). This triggered an ASSERT when running
QEMU with -M virt,virtualization=on. Address this by testing for both
possible valid values of RegSize.
BZ: https://bugzilla.tianocore.org/show_bug.cgi?id=2588
=> ArmVirtPkg: fix ASSERT in ArmVirtGicArchLib with virtualization=on

MdePkg/Include/IndustryStandard/PciExpress40.h
BZ: https://bugzilla.tianocore.org/show_bug.cgi?id=2598
All registers definition of DVSEC are defined as per the PCI Express Base
Specification 4.0 chapter 7.9.6.
Signed-off-by: Ashraf Javeed <ashraf.javeed@intel.com>
=> MdePkg/PciExpress40.h: DVSEC definition missing

ArmPkg/Library/ArmLib/AArch64/ArmLibSupport.S
Because of a bug, current EL gets passed to DC IVAC instruction instead
of the VA entry that needs to be invalidated.
Signed-off-by: Ashish Singhal <ashishsingha@nvidia.com>
=> ArmPkg/ArmLib: Fix cache-invalidate initial page tables

DynamicTablesPkg/Library/Acpi/Arm/AcpiFadtLibArm/FadtGenerator.c
Update FADT table generator to support ACPI revision 6.3
Reviewed-by: Alexei Fedorov <Alexei.Fedorov@arm.com>
=> DynamicTablesPkg: Update FADT generator to ACPI 6.3

EmbeddedPkg/RealTimeClockRuntimeDxe/RealTimeClock.c
ASSERT in SetTime_Conf Consistency Test.
SCT Test expect return as Invalid Parameter.
So removed ASSERT().
While at it, check that the NanoSecond field is within the range given
by the UEFI specification.
Signed-off-by: Gaurav Jain <gaurav.jain@nxp.com>
Reviewed-by: Ard Biesheuvel <ard.biesheuvel@linaro.org>
=> EmbeddedPkg/RealTimeClockRuntimeDxe: Drop ASSERTs on function arguments

UefiCpuPkg/Library/MpInitLib/DxeMpInitLib.inf, UefiCpuPkg/Library/MpInitLib/DxeMpLib.c, UefiCpuPkg/UefiCpuPkg.dec, UefiCpuPkg/UefiCpuPkg.uni
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=2627
The commit will introduce a static PCD to specify the periodic interval
for checking the AP status when MP services StartupAllAPs() and
StartupThisAP() are being executed in a non-blocking manner. Or in other
words, specifies the interval for callback function CheckApsStatus().
The purpose is to provide the platform owners with the ability to choose
the proper interval value to trigger CheckApsStatus() according to:
A) The number of processors in the system;
B) How MP services (StartupAllAPs & StartupThisAP) being used.
Setting the PCD to a small value means the AP status check callback will
be triggered more frequently, it can benefit the performance for the case
when the BSP uses WaitForEvent() or uses CheckEvent() in a loop to …
=> UefiCpuPkg/MpInitLib DXE: Add PCD to control AP status check interval

MdeModulePkg/Bus/Sd/SdDxe/SdBlockIo.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2286
Token pointer may be NULL, it should be checked before use it.
=> MdeModulePkg/SdDxe: Check the Token to avoid null pointer

MdePkg/Test/UnitTest/Library/BaseLib/Base64UnitTest.c, UnitTestFrameworkPkg/Library/UnitTestLib/RunTests.c, UnitTestFrameworkPkg/Library/UnitTestLib/UnitTestLib.c, UnitTestFrameworkPkg/Library/UnitTestResultReportLib/UnitTestResultReportLib.c
MdePkg/UnitTestBaseLib: Add check for pointer BinData
UnitTestFrameworkPkg/UnitTestLib: Check Suite pointer before use.
UnitTestFrameworkPkg/ResultReportLib: Remove invalid index string indicator
=> Fix in UnitTestFrameworkPkg

OvmfPkg/Library/GenericQemuLoadImageLib/GenericQemuLoadImageLib.c
Building OVMF for X64 with secure boot enabled on VS2019 results in
the following error:
d:\a\1\s\OvmfPkg\Library\GenericQemuLoadImageLib\GenericQemuLoadImageLib.c(154):
error C2220: the following warning is treated as an error
d:\a\1\s\OvmfPkg\Library\GenericQemuLoadImageLib\GenericQemuLoadImageLib.c(154):
warning C4244: '=': conversion from 'UINTN' to 'UINT32', possible loss of data
Suppress the error by making the cast explicit.
Link: https://bugzilla.tianocore.org/show_bug.cgi?id=2636
=> OvmfPkg/GenericQemuLoadImageLib: Fix VS2019 UINT32 conversion error

NetworkPkg/Ip6Dxe/Ip6Nd.c, NetworkPkg/Ip6Dxe/Ip6Nd.h, NetworkPkg/Ip6Dxe/Ip6Option.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2174
Problem has been identified with Ip6ProcessRouterAdvertise() when
Router Advertise packet contains options with malicious/invalid
'Length' field. This can lead to platform entering infinite loop
when processing options from that packet.
=> NetworkPkg/Ip6Dxe: Improve Neightbor Discovery message validation.

EmbeddedPkg/Include/Library/AcpiLib.h
ACPI 6.3 added a 16-bit SPE overflow Interrupt field, replacing
2 of the 3 reserved bytes that are defined at the end of the
GICC structure for 6.0.
Add a new macro to initialise the new field.
Signed-off-by: Pete Batard <pete@akeo.ie>
Reviewed-by: Ard Biesheuvel <ard.biesheuvel@linaro.org>
=> EmbeddedPkg/AcpiLib: add GICC table init macro for ACPI 6.3

BaseTools/Source/Python/AutoGen/PlatformAutoGen.py, BaseTools/Source/Python/build/build.py
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=2538
For LzmaCompress or BrotliCompress, the platform may use the different
options and add their batch file, such as LzmaCompressPlatform.
Then, specify it in platform.dsc [BuildOptions] to override the default
one in tools_def.txt.
*_*_*_LZMA_PATH = LzmaCompressPlatform
This override tool will be used. But, its name is not specified in the
generated GuidedSectionTools.txt.
=> BaseTools:GuidedSectionTools.txt is not generated correctly

Maintainers.txt
I no longer work for Linaro (and haven't for a while) so in anticipation
of losing access to my @linaro.org mailbox, let's switch to the ARM one
for my Tiancore contributions and maintainerships.
=> Maintainers: switch to my Arm email address

DynamicTablesPkg/Library/Acpi/Arm/AcpiSratLibArm/SratGenerator.c
This patch series fixes issues reported in the SRAT generator by the
VS2017 compiler with the static analysis option enabled.
=> Review 774 702 srat vs2017 compile warning v2

ShellPkg/Library/UefiShellNetwork1CommandsLib/Ping.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2032
'ping' command's receive flow utilizes a single Rx token which it
attempts to reuse before recycling the previously received packet.
This causes a situation where under ICMP traffic,
Ping6OnEchoReplyReceived() function will receive an already
recycled packet with EFI_SUCCESS token status and finally
dereference invalid pointers from RxData structure.
Acked-by: Zhichao Gao <zhichao.gao@intel.com>
=> ShellPkg: Fix 'ping' command Ip4 receive flow.

Maintainers.txt, NetworkPkg/UefiPxeBcDxe/PxeBcBoot.c, OvmfPkg/OvmfPkgIa32.dsc, OvmfPkg/OvmfPkgIa32X64.dsc, OvmfPkg/OvmfPkgX64.dsc, OvmfPkg/OvmfXen.dsc, OvmfPkg/PvScsiDxe/PvScsi.c
* [edk2-devel] [PATCH 1/1] OvmfPkg: Fix SMM/RT driver section alignment for XCODE5/CLANGPDB
https://edk2.groups.io/g/devel/message/56559
http://mid.mail-archive.com/20200329132158.35259-2-cheptsov@ispras.ru
* [edk2-devel] [PATCH] NetworkPkg/UefiPxeBcDxe: handle competing DHCP servers (more) gracefully
https://edk2.groups.io/g/devel/message/56699
http://mid.mail-archive.com/20200331004749.16128-1-lersek@redhat.com
* [edk2-devel] [PATCH] Maintainers.txt: Add Liran and Nikita as OvmfPkg/PvScsiDxe reviewers
https://edk2.groups.io/g/devel/message/56746
http://mid.mail-archive.com/20200331110244.51409-1-liran.alon@oracle.com
* [edk2-devel] [PATCH] OvmfPkg/PvScsiDxe: Fix VS2019 build error because of implicit cast
https://edk2.groups.io/g/devel/message/56747 …
=> lersek queue 2020-Apr-01

NetworkPkg/Ip6Dxe/Ip6Nd.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2655
=> NetworkPkg/Ip6Dxe: Fix ASSERT logic in Ip6ProcessRouterAdvertise()

ArmPkg/Drivers/CpuDxe/AArch64/Mmu.c
The local #define TT_ATTR_INDX_INVALID is used as a local error code
in the AArch64 implementation, but is misleadingly named to match the
definitions in ArmPkg/Include/Chipset/AArch64Mmu.h.
Rename it INVALID_ENTRY to reduce confusion and improve readability.
=> ArmPkg: rename misleading local #define in CpuDxe

MdeModulePkg/Application/SmiHandlerProfileInfo/SmiHandlerProfileInfo.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2272
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2287
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2288
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2289
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2290
Index should be off-by one than size of array, so when check
array, the max index should less than size of array.
=> MdeModulePkg/SmiHandlerProfileInfo: Overflowed Array Index

OvmfPkg/OvmfPkg.dec
http://mid.mail-archive.com/20200407100545.25406-1-lersek@redhat.com
https://edk2.groups.io/g/devel/message/57020
https://bugzilla.tianocore.org/show_bug.cgi?id=2662
=> [edk2-devel] [PATCH] OvmfPkg: supply missing lib class declarations in the DEC file -- push

ArmVirtPkg/ArmVirtQemu.dsc, ArmVirtPkg/ArmVirtQemuFvMain.fdf.inc, ArmVirtPkg/ArmVirtQemuKernel.dsc
Enable support for NVMe storage in ArmVirtQemu/QemVirtQemuKernel in order
to simplify booting/installing operating systems that don't support
virtio.
=> ArmVirtPkg: Include NVMe support in ArmVirtQemu*

MdePkg/Include/Library/DebugLib.h
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=1548
For clang compiler, This change will make the generated image not include the
absolute file path. If so, the generated debug image can be reproduced in the
different root directory. Also, it will reduce the size of debug image size.
To do so, use __FILE_NAME__ macro to replace __FILE__. __FILE_NAME__ is
Clang-specific extension that functions similar to __FILE__ but only renders
the last path component (the filename) instead of an invocation dependent full
path to that file, and __FILE_NAME__ is introduced since clang 9.
CC: Michael D Kinney <michael.d.kinney@intel.com>
CC: Liming Gao <liming.gao@intel.com>
=> MdePkg DebugLib: Enable FILE NAME as DEBUG ASSERT for CLANG

MdePkg/Include/IndustryStandard/Scsi.h, MdePkg/Library/UefiScsiLib/UefiScsiLib.c
The FUA (Force Unit Access) bit forces data to be written directly to
disk instead of the write cache. This prevents data from being lost if a
shutdown or reset is requested immediately after a SCSI write operation.
Signed-off-by: Christopher J Zurcher <christopher.j.zurcher@intel.com>
=> MdePkg/UefiScsiLib: Set FUA bit for synchronous SCSI Write operations

MdePkg/Include/IndustryStandard/AcpiAml.h
The ACPI specification, version 6.3, January 2019,
defines the Named Objects Encoding for FieldElements
in section '20.2.5.2 Named Objects Encoding'.
FieldElements can be one of the following:
NamedField | ReservedField | AccessField |
ExtendedAccessField | ConnectField
Some of these keywords are starting with an opcode,
allowing to identify their type.
E.g.: ReservedField := 0x00 PkgLength
This patch adds these FieldElement opcodes definitions to
the list of AML Opcode definitions.
=> MdePkg: Add AML FieldList OpCode definitions

.pytool/Plugin/SpellCheck/cspell.base.yaml
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=2593
Increases the maximum number of failures in the SpellCheck plugin so
that more issues can be caught in a single pass.
Reviewed-by: Shenglei Zhang <shenglei.zhang@intel.com>
=> .python/SpellCheck: Increase SpellCheck plugin max failures

UefiCpuPkg/Library/MpInitLib/DxeMpInitLib.inf, UefiCpuPkg/Library/MpInitLib/MpLib.h, UefiCpuPkg/Library/MpInitLib/PeiMpInitLib.inf
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=2632
Both PEI and DXE instances of the MpInitLib are using PcdLib APIs, but
none of them list the dependency of the PcdLib in INF & header files.
This commit will explicitly add such dependency in .H and .INF files.
Test done:
Library level build pass for VS2015x86 tool chain
Signed-off-by: Hao A Wu <hao.a.wu@intel.com>
=> UefiCpuPkg/MpInitLib: Add missing explicit PcdLib dependency

NetworkPkg/IScsiDxe/IScsiDhcp.c, NetworkPkg/IScsiDxe/IScsiDhcp6.c
Array 'TargetUrl' of size 255 may use index value(s) 255 and 256.
So enhance the boundary check to ensure the index is valid.
=> NetworkPkg/IScsiDxe: Enhance the check for array boundary

OvmfPkg/Library/PlatformDebugLibIoPort/DebugIoPortNocheck.c, OvmfPkg/Library/PlatformDebugLibIoPort/DebugIoPortQemu.c, OvmfPkg/Library/PlatformDebugLibIoPort/DebugLib.c, OvmfPkg/Library/PlatformDebugLibIoPort/DebugLibDetect.c, OvmfPkg/Library/PlatformDebugLibIoPort/DebugLibDetect.h, OvmfPkg/Library/PlatformDebugLibIoPort/DebugLibDetectRom.c, OvmfPkg/Library/PlatformDebugLibIoPort/PlatformDebugLibIoPort.inf, OvmfPkg/Library/PlatformDebugLibIoPort/PlatformRomDebugLibIoPort.inf, OvmfPkg/Library/PlatformDebugLibIoPort/PlatformRomDebugLibIoPortNocheck.inf, OvmfPkg/OvmfXen.dsc
https://edk2.groups.io/g/devel/message/57940
http://mid.mail-archive.com/20200423095358.2518197-1-anthony.perard@citrix.com
~~~
Patch series available in this git branch:
git://xenbits.xen.org/people/aperard/ovmf.git br.ovmfxen-debug-io-v2
v2:
- reuse PlatformDebugLibIoPort rather than duplicate it.
Remove non working DEBUG_ON_SERIAL_PORT, then add a new LibIoPort which always
writes to the IO port.
Issues was discovered and discuss in this mail threads:
<e1f7e62c-adb4-eace-3828-7d73ae59ecd4@bsdio.com>
"OvmfPkg XenPkg: X64 DEBUG GCC5 -DDEBUG_ON_SERIAL_PORT=TRUE build is broken"
Cheers,
Anthony PERARD (5):
OvmfPkg/OvmfXen: Remove DEBUG_ON_SERIAL_PORT
OvmfPkg/PlatformDebugLibIoPort: Reword QEMU to hypervisor
OvmfPkg/PlatformDebugLibIoPort: factor out debug port detection …
=> [edk2-devel] [PATCH v2 0/5] OvmfXen: Cleanup debug options

ArmVirtPkg/ArmVirtQemu.dsc, ArmVirtPkg/ArmVirtQemuKernel.dsc, ArmVirtPkg/Library/QemuFwCfgLib/QemuFwCfgLib.inf, OvmfPkg/Include/Library/QemuFwCfgSimpleParserLib.h, OvmfPkg/Library/PxeBcPcdProducerLib/PxeBcPcd.c, OvmfPkg/Library/PxeBcPcdProducerLib/PxeBcPcdProducerLib.inf, OvmfPkg/Library/QemuFwCfgLib/QemuFwCfgDxeLib.inf, OvmfPkg/Library/QemuFwCfgSimpleParserLib/QemuFwCfgSimpleParser.c, OvmfPkg/Library/QemuFwCfgSimpleParserLib/QemuFwCfgSimpleParserLib.inf, OvmfPkg/OvmfPkg.dec, OvmfPkg/OvmfPkgIa32.dsc, OvmfPkg/OvmfPkgIa32X64.dsc, OvmfPkg/OvmfPkgX64.dsc, OvmfPkg/PlatformPei/MemDetect.c, OvmfPkg/PlatformPei/Platform.c, OvmfPkg/PlatformPei/PlatformPei.inf
https://bugzilla.tianocore.org/show_bug.cgi?id=2681
https://edk2.groups.io/g/devel/message/58030
http://mid.mail-archive.com/20200424075353.8489-1-lersek@redhat.com
~~~
Ref:    https://bugzilla.tianocore.org/show_bug.cgi?id=2681
Branch: pxe_fw_cfg
With this series applied, the QEMU command line options listed below
control whether the guest firmware supports PXEv4 / PXEv6 boot. And
correspondingly, whether UefiBootManagerLib generates *new* PXEv4 /
PXEv6 boot options automatically. (Existent boot options are never
deleted in response to just the flags below.)
-fw_cfg name=opt/org.tianocore/IPv4PXESupport,string=[yn]
-fw_cfg name=opt/org.tianocore/IPv6PXESupport,string=[yn]
Cc: Jordan Justen …
=> [edk2-devel] [PATCH 0/7] OvmfPkg, ArmVirtPkg: control PXE v4/v6 boot support from the QEMU cmdline

.gitmodules
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2692
BrotliCompress submodule change for BaseTools causes untracked
files in BaseTools after building. This is regression for git.
=> .gitmodules: ignore untracked files in brotli

MdeModulePkg/Library/DeviceManagerUiLib/DeviceManager.c, MdeModulePkg/Library/DeviceManagerUiLib/DeviceManager.h, MdeModulePkg/Library/DeviceManagerUiLib/DeviceManagerUiLib.inf
The device manager UI library creates a UiApp submenu that contains a
list of network devices in the system. The logic that creates this menu
assumes that all handles have been connected to their drivers, but this
is not guaranteed in the general case: due to the way UiApp is constructed,
this logic runs before the UiApp entrypoint is invoked, which is where
ConnectAll() is normally called to ensure that all existing controllers
are connected to their drivers. Moving this call into DeviceManagerUiLib
is not an option, since it is incorporated into UiApp via NULL library
class resolution, and so it may not be included to begin with.
So work around this by doing an explicit additional ConnectAll() before
populating the pages.
Link: …
=> MdeModulePkg/DeviceManagerUiLib: connect all before creating menu page

OvmfPkg/Library/QemuFwCfgLib/QemuFwCfgLibNull.inf, OvmfPkg/Library/QemuFwCfgLib/QemuFwCfgNull.c
Add a null implementation library for QemuFwCfgLib, in order to
support building PciHostBridgeLib for bhyve.
Message-Id: <20200503230910.26783-1-rebecca@bsdio.com>
Reviewed-by: Philippe Mathieu-Daudé <philmd@redhat.com>
=> OvmfPkg: Add QemuFwCfgLibNull

OvmfPkg/Include/IndustryStandard/Bhyve.h, OvmfPkg/Library/ResetSystemLib/BaseResetShutdownBhyve.c, OvmfPkg/Library/ResetSystemLib/BaseResetSystemLibBhyve.inf
Introduce BaseResetSystemLibBhyve.inf, to support powering off
bhyve guests.
Message-Id: <20200504021853.76658-1-rebecca@bsdio.com>
[lersek@redhat.com: MODULE_TYPE: replace DXE_DRIVER with BASE]
[lersek@redhat.com: replace <OvmfPlatforms.h> with <IndustryStandard/Bhyve.h>]
[lersek@redhat.com: strip ".inf" from subject line]
=> OvmfPkg: Add BaseResetSystemLibBhyve

FmpDevicePkg/FmpDxe/Dependency.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2602
Zero the allocated buffer in case GetImageInfo `continue` in the middle of
a loop. This will cause unexpected GetImageInfo failure not clearing the
corresponding entry and lead to GP faults when dereferencing this entry.
Signed-off-by: Wei6 Xu <wei6.xu@intel.com>
Reviewed-by: Guomin Jiang <guomin.jiang@intel.com>
=> FmpDevicePkg/FmpDxe: Fix uninitialized pointer dereference

EmbeddedPkg/EmbeddedPkg.dsc
Some driver were recently moved to edk2-platforms, but the DSC file
in EmbeddedPkg still refers to them. Drop these references.
=> EmbeddedPkg/EmbeddedPkg.dsc: remove some stale component references

ShellPkg/Library/UefiShellAcpiViewCommandLib/AcpiTableParser.c, ShellPkg/Library/UefiShellAcpiViewCommandLib/AcpiView.c, ShellPkg/Library/UefiShellAcpiViewCommandLib/AcpiView.h, ShellPkg/Library/UefiShellAcpiViewCommandLib/Arm/SbbrValidator.c, ShellPkg/Library/UefiShellAcpiViewCommandLib/Arm/SbbrValidator.h, ShellPkg/Library/UefiShellAcpiViewCommandLib/UefiShellAcpiViewCommandLib.inf, ShellPkg/Library/UefiShellAcpiViewCommandLib/UefiShellAcpiViewCommandLib.uni
This patch series adds a new capability to the Acpiview UEFI shell tool.
Using the -r command line parameter, it is now possible to choose a
specification which lists mandatory ACPI tables. The parameter value is
then consumed by a library which validates ACPI tables identified on the
platform against these requirements.
The -r parameter is architecture agnostic. However, as of now, the
possible values for the parameter are only defined in the context of
the Arm architecture.
For Arm-based platforms, it is now possible to validate that Server Base
Boot Requirements (SBBR) mandatory ACPI tables are present on the
platform.
Changes can be seen at: https://github.com/KrzysztofKoch1/edk2/tree/617_sbbr_validate_acpi_table_counts_v1
=> Check if required ACPI tables are installed

BaseTools/Scripts/SetupGit.py
Allow users who didn't clone one of the TianoCore repos from a
canonical URL to specify the name of the repo (edk2, edk2-platforms
or edk2-non-osi) when running SetupGit.py to allow them to configure
their repo properly.
The new option is:
-n repo, --name repo  set the repo name to configure for, if not
detected automatically
=> BaseTools: add repo name option to SetupGit.py

BaseTools/Scripts/GetMaintainer.py
GetMaintainer.py already extracts the value of any S: tags for sections,
but it doesn't do anything with that information.
Print a warning message, with the status, for each matching section with
a status explicitly set to anything other than 'Supported' or
'Maintained'.
Acked-by: Ard Biesheuvel <ard.biesheuvel@arm.com>
=> BaseTools: add handling for 'S:' flag to GetMaintainer.py

OvmfPkg/OvmfPkgIa32.dsc, OvmfPkg/OvmfPkgIa32X64.dsc, OvmfPkg/OvmfPkgX64.dsc, OvmfPkg/OvmfXen.dsc, UefiCpuPkg/Library/CpuExceptionHandlerLib/DxeCpuExceptionHandlerLib.inf, UefiCpuPkg/Library/CpuExceptionHandlerLib/SmmCpuExceptionHandlerLib.inf, UefiCpuPkg/Library/CpuExceptionHandlerLib/X64/ExceptionHandlerAsm.nasm, UefiCpuPkg/Library/CpuExceptionHandlerLib/X64/Xcode5ExceptionHandlerAsm.nasm, UefiCpuPkg/Library/CpuExceptionHandlerLib/Xcode5SecPeiCpuExceptionHandlerLib.inf, UefiCpuPkg/Library/CpuExceptionHandlerLib/Xcode5SecPeiCpuExceptionHandlerLib.uni, UefiCpuPkg/UefiCpuPkg.dsc
https://bugzilla.tianocore.org/show_bug.cgi?id=2340
http://mid.mail-archive.com/cover.1588856809.git.thomas.lendacky@amd.com
https://edk2.groups.io/g/devel/message/58786
~~~
Commit 2db0ccc2d7fe ("UefiCpuPkg: Update CpuExceptionHandlerLib pass
XCODE5 tool chain") introduced binary patching in the
ExceptionHandlerAsm.nasm in order to support the XCODE5 toolchain.
However, the CpuExceptionHandlerLib can be used during SEC phase which
would result in binary patching of flash.
This series creates a new CpuExceptionHandlerLib file to support
the required binary patching for the XCODE5 toolchain, while reverting
the changes from commit 2db0ccc2d7fe in the standard file. As the Pei,
Dxe and SMM versions of the library operate in memory (as opposed to
flash), only the SEC/PEI version is of the …
=> [PATCH v3 0/3] XCODE5 toolchain binary patching fix

BaseTools/Source/Python/Ecc/EccMain.py
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=2707
Ecc fails with Python 3.8 because it uses the deprecated time.clock()
function - https://docs.python.org/3.7/library/time.html#time.clock
This change updates EccMain.py to use time.perf_counter().
=> BaseTools/Ecc: Replace deprecated function time.clock()

BaseTools/Source/Python/Common/Misc.py
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2686
The build tool will give an incorrect GUID value if the GUID includes character ' or " ASCII value.
This patch is going to fix this issue.
Signed-off-by: Yunhua Feng <yunhuax.feng@intel.com>
=> BaseTools: Fix parse PCD GUID expression issue

IntelFsp2Pkg/FspSecCore/Fsp22SecCoreS.inf, IntelFsp2Pkg/FspSecCore/Ia32/Fsp22ApiEntryS.nasm, IntelFsp2Pkg/FspSecCore/Ia32/FspApiEntryCommon.nasm, IntelFsp2Pkg/FspSecCore/SecFsp.c, IntelFsp2Pkg/FspSecCore/SecFspApiChk.c, IntelFsp2Pkg/FspSecCore/SecMain.c, IntelFsp2Pkg/Include/FspEas/FspApi.h, IntelFsp2Pkg/Include/FspGlobalData.h, IntelFsp2Pkg/Include/Guid/FspHeaderFile.h, IntelFsp2Pkg/Include/Library/FspSecPlatformLib.h, IntelFsp2Pkg/Library/SecFspSecPlatformLibNull/PlatformSecLibNull.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2698
To enhance FSP silicon initialization flexibility an optional
Multi-Phase API is introduced and FSP header needs update for
new API offset. Also new SecCore module created for
FspMultiPhaseSiInit API
New ARCH_UPD introduced for enhancing FSP debug message
flexibility now bootloader can pass its own debug handler
function pointer and FSP will call the function to handle
debug message.
To support calling bootloader functions, a FspGlobalData field
added to indicate if FSP needs to switch stack when FSP running
on separate stack from bootloader.
Reviewed-by: Nate …
=> IntelFsp2Pkg: Support Multi-Phase SiInit and debug handlers.

OvmfPkg/OvmfPkgIa32.dsc, OvmfPkg/OvmfPkgIa32.fdf, OvmfPkg/OvmfPkgIa32X64.dsc, OvmfPkg/OvmfPkgIa32X64.fdf, OvmfPkg/OvmfPkgX64.dsc, OvmfPkg/OvmfPkgX64.fdf, OvmfPkg/OvmfXen.dsc, OvmfPkg/OvmfXen.fdf
http://mid.mail-archive.com/20200514134820.62047-1-r.bolshakov@yadro.com
https://edk2.groups.io/g/devel/message/59565
~~~
OVMF booting stops with the assert if built with Xcode on macOS:
Loading driver at 0x0001FAB8000 EntryPoint=0x0001FABF249 LinuxInitrdDynamicShellCommand.efi
InstallProtocolInterface: BC62157E-3E33-4FEC-9920-2D3B36D750DF 1F218398
ProtectUefiImageCommon - 0x1F218140
- 0x000000001FAB8000 - 0x0000000000008A60
ASSERT_EFI_ERROR (Status = Unsupported)
ASSERT LinuxInitrdDynamicShellCommand.c(378): !EFI_ERROR (Status)
The assert comes from InitializeHiiPackage() after an attempt to
retrieve HII package list from ImageHandle.
Xcode still doesn't support HII resource section and
LinuxInitrdDynamicShellCommand depends on it. Likewise 277a3958d93a
("OvmfPkg: Don't include …
=> OvmfPkg: Skip initrd command on Xcode toolchain

UefiCpuPkg/Library/MpInitLib/MpLib.c
Intel SDM introduces 6-levels for describing the CPU topology:
* Package
* Module
* Tile
* Die
* Core
* Thread
A PI spec ECR was submitted to enhance CPU_MP PPI/Protocol to
support returning such information through GetProcessorInfo().
An accordingly change was implemented and pushed to edk2-staging.
Now the PI spec has been published.
The patch is cherry-picked from edk2-staging to edk2.
=> UefiCpuPkg/MpService: GetProcessorInfo returns 6-level topology

OvmfPkg/OvmfPkgIa32.dsc, OvmfPkg/OvmfPkgIa32X64.dsc, OvmfPkg/OvmfPkgX64.dsc, OvmfPkg/PlatformPei/MemTypeInfo.c, OvmfPkg/PlatformPei/PlatformPei.inf
https://edk2.groups.io/g/devel/message/58876
http://mid.mail-archive.com/20200508121651.16045-1-lersek@redhat.com
https://bugzilla.tianocore.org/show_bug.cgi?id=2706
~~~
Ref:    https://bugzilla.tianocore.org/show_bug.cgi?id=2706
Branch: memtypeinfo_rework
Please find the problem statement and the solution outline in the
Bugzilla ticket linked above.
Thanks,
Laszlo
Laszlo Ersek (4):
OvmfPkg/PlatformPei: don't track BS Code/Data in default MemTypeInfo
HOB
OvmfPkg/PlatformPei: rewrite MemTypeInfo HOB production logic
OvmfPkg/PlatformPei: extract memory type info defaults to …
=> [PATCH 0/4] OvmfPkg/PlatformPei: rewrite MemTypeInfo HOB production logic

NetworkPkg/Library/DxeNetLib/NetBuffer.c
Patch: https://edk2.groups.io/g/devel/message/59914
The condition, NET_HEADSPACE(&(Nbuf->BlockOp[Index])) < Len, is
meaningless if Index = 0. So checking 'Index != 0' should be
performed first in the if statement.
=> NetworkPkg/DxeNetLib: Change the order of conditions in IF statement

IntelFsp2Pkg/Include/FspGlobalData.h, IntelFsp2Pkg/Include/Library/FspSwitchStackLib.h
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2726
When FSP switching stack and calling bootloader functions,
the function parameter in stack may not be accessible easily.
We can store the function parameter pointer to FspGlobalData
and retrieve it after stack switched.
Also need to add Loader2PeiSwitchStack () to header file
as public function for platform FSP code to consume.
=> IntelFsp2Pkg: Add FunctionParametePtr to FspGlobalData.

OvmfPkg/Tcg/Tcg2Config/Tcg2ConfigPei.inf, OvmfPkg/Tcg/Tcg2Config/Tcg2ConfigPeim.c, OvmfPkg/Tcg/Tcg2Config/Tpm12Support.c, OvmfPkg/Tcg/Tcg2Config/Tpm12Support.h, OvmfPkg/Tcg/Tcg2Config/Tpm12SupportNull.c
https://bugzilla.tianocore.org/show_bug.cgi?id=2728
http://mid.mail-archive.com/20200520225841.17793-1-lersek@redhat.com
https://edk2.groups.io/g/devel/message/60005
~~~
Ref:    https://bugzilla.tianocore.org/show_bug.cgi?id=2728
Branch: restrict_tpm12_to_x86_bz_2728
Another regression fix for edk2-stable202005.
End of February 2020, Ard and Marc-André worked on two TPM-related
features in parallel. Respectively:
- [edk2-devel] [PATCH v4 00/11]
ArmVirtPkg: implement measured boot for ArmVirtQemu
http://mid.mail-archive.com/20200227144056.56988-1-ard.biesheuvel@linaro.org
https://edk2.groups.io/g/devel/message/55004
- [edk2-devel] [PATCH v4 0/5]
Ovmf: enable TPM 1.2
http://mid.mail-archive.com/20200226152433.1295789-1-marcandre.lureau@redhat.com …
=> [edk2-devel] [PATCH 0/3] OvmfPkg/Tcg2ConfigPei: fix ARM/AARCH64 build failure -- push

BaseTools/Conf/tools_def.template
The VS2017 compiler reports 'warning D9035 : option
'Gm' has been deprecated and will be removed in a
future release'
The documentation for the 'Gm' option at
https://docs.microsoft.com/en-us/cpp/build/reference/gm-enable-minimal-rebuild?view=vs-2019
indicates that this option can be safely removed
from the project.
Therefore, remove the deprecated 'Gm' Visual Studio
Compiler option.
Ref: https://bugzilla.tianocore.org/show_bug.cgi?id=2660
=> BaseTools: Remove deprecated Visual Studio Option

MdePkg/Include/Protocol/DevicePath.h
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2716
Add definitions for ACPI NVDIMM Device Path following UEFI spec.
Signed-off-by: James Anandraj <james.sushanth.anandraj@intel.com>
=> MdePkg: add definitions for ACPI NVDIMM Device Path

SecurityPkg/Include/Library/Tcg2PhysicalPresenceLib.h, SecurityPkg/Library/DxeTcg2PhysicalPresenceLib/DxeTcg2PhysicalPresenceLib.c, SecurityPkg/Library/PeiTcg2PhysicalPresenceLib/PeiTcg2PhysicalPresenceLib.c, SecurityPkg/Library/PeiTcg2PhysicalPresenceLib/PeiTcg2PhysicalPresenceLib.inf, SecurityPkg/Library/SmmTcg2PhysicalPresenceLib/SmmTcg2PhysicalPresenceLib.c, SecurityPkg/Library/SmmTcg2PhysicalPresenceLib/SmmTcg2PhysicalPresenceLib.inf, SecurityPkg/SecurityPkg.dec
https://bugzilla.tianocore.org/show_bug.cgi?id=2713
In current code, If TCG2_PHYSICAL_PRESENCE_FLAGS_VARIABLE variable
is not exist, code will get default value from two places.
This fix is to make the default value comes from the PCD
gEfiSecurityPkgTokenSpaceGuid.PcdTcg2PhysicalPresenceFlags
Signed-off-by: Maggie Chu <maggie.chu@intel.com>
=> SecurityPkg: Change default value source

MdePkg/Include/Library/BaseLib.h, MdePkg/Library/BaseLib/SafeString.c, MdePkg/Test/UnitTest/Library/BaseLib/Base64UnitTest.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2054
V9 Update unit test comment and use zero buffers to verify more behavior.
V8 Add DEBUG_VERBOSE message and unit test.
V7 addressed review comments (only documentation changes).
Current implementation of SafeString does not let one parse untrusted
data with its interfaces as they ASSERT on failing runtime checks and
require one to effectively reimplement the function on the caller side.
All the former proposals made it clear that the attempts to introduce
a solution preserving this behavior require a lot of changes
throughout the codebase including platform code (e.g. introducing
constraint assertions and updating all DebugLib implementations)
or require all sorts of hacks.
Since the original code has roughly no benefit except in …
=> Disable safe string constraint assertions

UnitTestFrameworkPkg/Library/UnitTestResultReportLib/UnitTestResultReportLibConOut.c, UnitTestFrameworkPkg/Library/UnitTestResultReportLib/UnitTestResultReportLibDebugLib.c
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=2721
The ReportOutput() function in UnitTestResultReportLib copies characters
from a function input buffer to an intermediate local buffer in fixed
size chunks of the maximum size of the intermediate buffer. The
implementation currently calls AsciiStrCpyS() which will ASSERT on an
error.
This commit changes the call to AsciiStrnCpyS() to avoid the
ASSERT which is not expected in the usage of the string copy in this
implementation.
=> UnitTestFrameworkPkg/UnitTestResultReportLib: Use AsciiStrnCpyS()

ArmPkg/Library/CompilerIntrinsicsLib/AArch64/Atomics.S, ArmPkg/Library/CompilerIntrinsicsLib/CompilerIntrinsicsLib.inf
Gary reports the GCC 10 will emit calls to atomics intrinsics routines
unless -mno-outline-atomics is specified. This means GCC-10 introduces
new intrinsics, and even though it would be possible to work around this
by specifying the command line option, this would require a new GCC10
toolchain profile to be created, which we prefer to avoid.
So instead, add the new intrinsics to our library so they are provided
when necessary.
Tested-by: Gary Lin <glin@suse.com>
=> ArmPkg/CompilerIntrinsicsLib: provide atomics intrinsics

ArmPkg/ArmPkg.dsc
PlatformBootManagerLib now asserts at build time that the correct
terminal type is used, and so leaving it unset breaks the ArmPkg
DSC build. So fix that.
=> ArmPkg/ArmPkg.dsc: set terminal type PCD to the right value

EmulatorPkg/EmulatorPkg.dec, EmulatorPkg/Win/Host/WinHost.c, EmulatorPkg/Win/Host/WinHost.h, EmulatorPkg/Win/Host/WinHost.inf, EmulatorPkg/Win/Host/WinPacketFilter.c
Follow the implementation from Unix host to implement SNP
EMU_IO_THUNK_PROTOCOL and EMU_SNP_PROTOCOL. The network IO driver is the
same one as Nt32. Please refer to NETWORK-IO Subproject for network Io
driver(SnpNt32Io.dll).
Signed-off-by: Nickle Wang <nickle.wang@hpe.com>
Signed-off-by: Derek Lin <derek.lin2@hpe.com>
Acked-by: Ray Ni <ray.ni@intel.com>
=> EmulatorPkg/WinHost: Enable network support.

ArmPkg/Library/ArmSvcLib/AArch64/ArmSvc.S, ArmPkg/Library/ArmSvcLib/Arm/ArmSvc.S, ArmPkg/Library/ArmSvcLib/Arm/ArmSvc.asm
Supervisor Call instruction (SVC) is used by the Arm Standalone MM
environment to request services from the privileged software (such as
ARM Trusted Firmware running in EL3) and also return back to the
non-secure caller via EL3. Some Arm CPUs speculatively executes the
instructions after the SVC instruction without crossing the privilege
level (S-EL0). Although the results of this execution are
architecturally discarded, adversary running on the non-secure side can
manipulate the contents of the general purpose registers to leak the
secure work memory through spectre like micro-architectural side channel
attacks. This behavior is demonstrated by the SafeSide project [1] and
[2]. Add barrier instructions after SVC to prevent speculative execution
to mitigate such attacks.
[1]: …
=> ArmPkg/ArmSvcLib: prevent speculative execution beyond svc

BaseTools/Source/Python/build/build.py
AutoGen manager/workers halt the progress when an error occurs but
doesn't propagate the error code to main and allows main exit with 0
and gets the build system unable to catch the occurrence of an error.
This change informs main with an error when a progress is halted and
helps main exit with 1.
Signed-off-by: Irene Park <ipark@nvidia.com>
Reviewed-by: Bob Feng<bob.c.feng@intel.com>
=> BaseTools/build.py: Exit with 1 when AutoGen error occurred

BaseTools/Source/Python/Trim/Trim.py
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2770
The Trim.py would break the build process when the file not found
issue occures, however sometimes we do not care about this issue.
This patch changes the error with warning in order to solve this
kind of break.
Reviewed-by: Bob Feng<bob.c.feng@intel.com>
=> BaseTools: Warn user the file not found issue instead of break build.

ArmPkg/ArmPkg.dsc
Commit 045e4b84c18f  ("ArmPkg/ArmPkg.dsc: Add missing components")
adds some components to the ArmPkg.dsc build config, but it adds
them to Components.common, and MmCommunicationDxe is AArch64 only.
Move it to Components.AARCH64 to stop the ARM build breaking.
Cc: Michael Kubacki <michael.kubacki@microsoft.com>
=> ArmPkg: only attempt building MmCommunicationDxe for AArch64

Maintainers.txt
http://mid.mail-archive.com/20200603160627.3594-1-lersek@redhat.com
https://edk2.groups.io/g/devel/message/60681
https://bugzilla.tianocore.org/show_bug.cgi?id=2778
~~~
Ref:    https://bugzilla.tianocore.org/show_bug.cgi?id=2778
Branch: sort_maintainers
We originally meant to keep the subsystem (package) titles sorted, in
"Maintainers.txt".
However, as of 7191dd3c5990 ("ArmPkg/PlatformBootManagerLib: reject
'default' parity and stop bit count", 2020-06-03), we have some disorder
introduced.
This patch series restores lexicographical order between the subsystem
(package) headers.
The package / subsystem headers can be collected with the following
small script:
$ dos2unix < Maintainers.txt \
| sed -n -e '/^EDK II Packages:$/,$p' \
| tail -n +3 \
| …
=> Maintainers.txt: restore lexicographical order between package / subsystem headers [push]

OvmfPkg/Tcg/Tcg2Config/Tcg2ConfigPei.inf, OvmfPkg/Tcg/Tcg2Config/Tcg2ConfigPeim.c
https://bugzilla.tianocore.org/show_bug.cgi?id=2752
http://mid.mail-archive.com/20200603170413.23936-1-lersek@redhat.com
https://edk2.groups.io/g/devel/message/60690
~~~
Ref:    https://bugzilla.tianocore.org/show_bug.cgi?id=2752
Branch: tcg_config_pei_trivial
Two trivial cleanups after commit 89236992913f ("OvmfPkg: detect TPM 1.2
in Tcg2ConfigPei", 2020-03-04) and commit 74f90d38c446
("OvmfPkg/Tcg2ConfigPei: skip TPM-1.2 detection when building for
ARM/AARCH64", 2020-05-21), respectively.
Cc: Marc-André Lureau <marcandre.lureau@redhat.com>
Cc: Stefan Berger <stefanb@linux.ibm.com>
Thanks
Laszlo
Laszlo Ersek …
=> OvmfPkg/Tcg2ConfigPei: trivial cleanups [push]

OvmfPkg/Library/X86QemuLoadImageLib/X86QemuLoadImageLib.c
http://mid.mail-archive.com/20200605235242.32442-1-lersek@redhat.com
https://edk2.groups.io/g/devel/message/60825
~~~
When an image fails Secure Boot validation, LoadImage() returns
EFI_SECURITY_VIOLATION if the platform policy is
DEFER_EXECUTE_ON_SECURITY_VIOLATION.
If the platform policy is DENY_EXECUTE_ON_SECURITY_VIOLATION, then
LoadImage() returns EFI_ACCESS_DENIED (and the image does not remain
loaded).
(Before <https://bugzilla.tianocore.org/show_bug.cgi?id=2129>, this
difference would be masked, as DxeImageVerificationLib would incorrectly
return EFI_SECURITY_VIOLATION for DENY_EXECUTE_ON_SECURITY_VIOLATION as
well.)
In X86QemuLoadImageLib, proceed to the legacy Linux/x86 Boot Protocol upon
seeing EFI_ACCESS_DENIED too.
Cc: Jordan Justen …
=> OvmfPkg/X86QemuLoadImageLib: handle EFI_ACCESS_DENIED from LoadImage() [push]

MdeModulePkg/Application/BootManagerMenuApp/BootManagerMenu.c
Its been observed that in MenuManagerMenuApp when user
selects a different BootOption using Up/Down key, the
current Cursor position is not chaning.
Still points to the old BootOption.
This changes first dispalys/redraws the old BootOption
followed by new BootOption. Doing so will make current
cursor pointing to the user selected BootOption.
Signed-off-by: Abdul Lateef Attar <abdul@marvell.com>
=> MdeModulePkg: Sets the Cursor to selected BootOption.

MdeModulePkg/Universal/SetupBrowserDxe/Presentation.c, MdeModulePkg/Universal/SetupBrowserDxe/Setup.c
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=2701
Recording to the spec, the reconnect is activated upon exiting of the
formset or the browser. Exiting is by user but form-browser internal
logic. That means the reconnection is only happened when user press
ESC or _EXIT action to exit form.
Driver callback may update HII form dynamically so form-browser needs
to refresh its internal data. It's not exiting formset for user
exactly and they didn't know what happened. So use a flag to record
that and do not reconnect driver if updated by callback.
Signed-off-by: Walon Li <walon.li@hpe.com>
=> MdeModulePkg/SetupBrowserDxe: Do not reconnect driver with form-update

OvmfPkg/Library/GenericQemuLoadImageLib/GenericQemuLoadImageLib.c
http://mid.mail-archive.com/20200609105414.12474-1-lersek@redhat.com
https://edk2.groups.io/g/devel/message/60948
~~~
gBS->LoadImage() returning EFI_NOT_FOUND is an expected condition; it
means that QEMU wasn't started with "-kernel". Log this status code as
INFO rather than ERROR.
---
Notes:
Branch: gqlil_not_found
OvmfPkg/Library/GenericQemuLoadImageLib/GenericQemuLoadImageLib.c | 3 ++-
1 file changed, 2 insertions(+), 1 deletion(-)
~~~
=> OvmfPkg/GenericQemuLoadImageLib: log "Not Found" at INFO level [push]

BaseTools/Source/C/GenFv/GenFvInternalLib.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2790
If the top FFS is placed in FV image, current FV will show there is no space.
In fact, the pad ffs in FV image can be regarded as the spare space.
This change reports the max pad ffs size as the spare space for use.
Signed-off-by: Liming Gao <liming.gao@intel.com>
=> BaseTools GenFv: Report the correct spare FV image size

IntelFsp2Pkg/IntelFsp2Pkg.dsc
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2788
DSC is incomplete according to the established CI policies.
Fsp22SecCoreS.inf needs to be added to the Components section
for completeness.
=> IntelFsp2Pkg: Add Fsp22SecCoreS.inf to Dsc.

EmbeddedPkg/Universal/MmcDxe/MmcBlockIo.c
Moved BlockCount calculation below BufferSize Validation checks.
First Ensure Buffersize is Not Zero and multiple of Media BlockSize.
then calculate BlockCount and perform Block checks.
Corrected BlockCount calculation, as BufferSize is multiple of BlockSize,
So adding (BlockSize-1) bytes to BufferSize and
then divide by BlockSize will have no impact on BlockCount.
Reading Large Images from MMC causes errors.
As per SD Host Controller Spec version 4.20,
Restriction of 16-bit Block Count transfer is 65535.
Max block transfer limit in single cmd is 65535 blocks.
Added Max Block check that can be processed is 0xFFFF.
then Update BlockCount on the basis of MaxBlock.
Signed-off-by: Gaurav Jain <gaurav.jain@nxp.com>
Reviewed-by: "Loh, Tien Hock" <tien.hock.loh@intel.com>
=> EmbeddedPkg/MmcDxe: Added MaxBlock Transfer Limit 65535 in R/W.

MdePkg/Include/Library/UnitTestLib.h, UnitTestFrameworkPkg/Library/UnitTestLib/RunTests.c, UnitTestFrameworkPkg/Library/UnitTestLib/UnitTestLib.c
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=2612
Simplifies the SaveFrameworkState() interface by removing the
FrameworkHandle parameter. The expectation is that this API is called
from within a test suite prior to test case completion such as a reboot.
The active framework is tracked internally to the initialization API.
Cc: Bret Barkelew <brbarkel@microsoft.com>
=> Drop FrameworkHandle param from SaveFrameworkState()

ShellPkg/Library/UefiShellDebug1CommandsLib/SmbiosView/PrintInfo.c
This prevents overflow when printing DWORD fields such as the type 17
tables's extended DIMM size.
Cc: Philippe Mathieu-Daude <philmd@redhat.com>
Reviewed- by: Zhichao Gao <zhichao.gao@intel.com>
=> ShellPkg: smbiosview - print field values as unsigned integers

MdePkg/Library/BasePrintLib/PrintLibInternal.c
The mStatusString[] array is constructed as an array of pointer-to-char,
which means that on X64 or AARCH64, it is emitted as a single linear list
of 64-bit quantities, each containing the absolute address of one of the
string literals in memory.
This means that each string takes up 8 bytes of additional space, along
with 2 bytes of relocation data. It also means that extra work needs to
be done at runtime to process these relocations, every time a module is
loaded that incorporates this library.
So fix both issues, by splitting mStatusString into two arrays of char
arrays. The memory footprint decreases from 955 to 843 bytes, and given
that in the latter case, the overhead consists of 278 NUL characters rather
than 390 bytes worth of absolute addresses and relocation records, the size
of …
=> MdePkg/BasePrintLib: avoid absolute addresses for error strings

OvmfPkg/OvmfPkgIa32.dsc, OvmfPkg/OvmfPkgIa32X64.dsc, OvmfPkg/OvmfPkgX64.dsc
https://edk2.groups.io/g/devel/message/61301
http://mid.mail-archive.com/20200615144514.24597-1-lersek@redhat.com
~~~
This reverts commit ced77332cab626f35fbdb36630be27303d289d79.
The command
virt-install --location NETWORK-URL
downloads the vmlinuz and initrd files from the remote OS tree, and passes
them to the guest firmware via fw_cfg.
When used with IA32 / X64 guests, virt-install expects the guest firmware
to do two things, at the same time:
- launch the fw_cfg kernel image even if the latter does not pass SB
verification (SB checking is supposed to be bypassed entirely in favor
of the Linux/x86 Boot Protocol),
- still let the guest kernel perceive SB as enabled.
Commit ced77332cab6 prevented this, by removing the Linux/x86 Boot
Protocol from such an OVMF image that was built with …
=> Revert "OvmfPkg: use generic QEMU image loader for secure boot enabled builds" [push]

MdeModulePkg/Universal/StatusCodeHandler/Pei/SerialStatusCodeWorker.c, MdeModulePkg/Universal/StatusCodeHandler/RuntimeDxe/SerialStatusCodeWorker.c, MdeModulePkg/Universal/StatusCodeHandler/Smm/SerialStatusCodeWorker.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2787
When output string data through serial port, will not ouput \n\r now.
Caller can output several data in one line, and output \n\r when needed.
Signed-off-by: Ming Tan <ming.tan@intel.com>
=> MdeModulePkg/StatusCodeHandler: do not output \n\r for string data

EmulatorPkg/EmulatorPkg.dsc, MdeModulePkg/MdeModulePkg.dec, MdeModulePkg/Universal/StatusCodeHandler/Pei/StatusCodeHandlerPei.c, MdeModulePkg/Universal/StatusCodeHandler/Pei/StatusCodeHandlerPei.inf, MdeModulePkg/Universal/StatusCodeHandler/RuntimeDxe/StatusCodeHandlerRuntimeDxe.c, MdeModulePkg/Universal/StatusCodeHandler/RuntimeDxe/StatusCodeHandlerRuntimeDxe.inf, MdeModulePkg/Universal/StatusCodeHandler/Smm/StatusCodeHandlerSmm.c, MdeModulePkg/Universal/StatusCodeHandler/Smm/StatusCodeHandlerSmm.inf, OvmfPkg/OvmfPkgIa32.dsc, OvmfPkg/OvmfPkgIa32X64.dsc, OvmfPkg/OvmfPkgX64.dsc, OvmfPkg/OvmfXen.dsc, UefiPayloadPkg/UefiPayloadPkgIa32.dsc, UefiPayloadPkg/UefiPayloadPkgIa32X64.dsc
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2786
Change the following PCDs from [PcdsFeatureFlag] to [PcdsFixedAtBuild, PcdsPatchableInModule, PcdsDynamic, PcdsDynamicEx]:
PcdStatusCodeUseSerial
PcdStatusCodeUseMemory
The original platforms can use PcdsFixedAtBuild in .dsc files.
Some platforms can use PcdsDynamic or others in .dsc files to support enable/disable report status code through memory and serial dynamic,
=> MdeModulePkg.dec: Change PCDs for status code

OvmfPkg/8254TimerDxe/Timer.c, OvmfPkg/XenTimerDxe/XenTimerDxe.c
https://bugzilla.tianocore.org/show_bug.cgi?id=2815
https://edk2.groups.io/g/devel/message/61329
http://mid.mail-archive.com/1592275782-9369-1-git-send-email-igor.druzhinin@citrix.com
~~~
RestoreTPL called while at TPL_HIGH_LEVEL unconditionally enables
interrupts even if called in interrupt handler. That opens a window while
interrupt is not completely handled but another interrupt could be
accepted.
If a VM starts on a heavily loaded host hundreds of periodic timer
interrupts might be queued while vCPU is descheduled (the behavior is
typical for a Xen host). The next time vCPU is scheduled again all of them
get delivered back to back causing OVMF to accept each one without
finishing a previous one and cleaning up the stack. That quickly results
in stack overflow and a triple fault.
Fix …
=> OvmfPkg: End timer interrupt later to avoid stack overflow under load [push]

MdePkg/Include/IndustryStandard/MemoryMappedConfigurationSpaceAccessTable.h
ACPI memory mapped configuration space access (MCFG) table requires
defination of EFI_ACPI_DESCRIPTION_HEADER.
Signed-off-by: Wasim Khan <wasim.khan@nxp.com>
=> MdePkg: Include Acpi header file

UefiCpuPkg/SecCore/Ia32/ResetVec.nasmb
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=2776
Add a vector at 0xFF000 (0xFFFFF000) that can be used by Init-SIPI-SIPI
to start an AP before memory is initialized. This vector jumps into the
same SEC entry point as the ordinary reset vector, with a special value
of "AP" in the DI register. The platform-specific SEC code is expected
to check for that value and take a different path for APs, if this
feature is supported by the platform.
Signed-off-by: Deric Cole <deric.cole@intel.com>
=> UefiCpuPkg/SecCore: Add pre-memory AP vector

BaseTools/Conf/tools_def.template
Add opensbi external definitions to RISC-V build for assembly
code. Use GCC5_RISCV_OPENSBI_TYPES to refer to edk2 data type
for assembly files instead of using opensbi data type.
=> BaseTools: Add external definitions for RISC-V assembly build

ArmVirtPkg/Library/NorFlashQemuLib/NorFlashQemuLib.c
Our UEFI guest firmware takes ownership of the emulated NOR flash in
order to support the variable runtime services, and it does not expect
the OS to interfere with the underlying storage directly. So disable
the NOR flash DT nodes as we discover them, in a way similar to how we
disable the PL031 RTC in the device tree when we attach our RTC runtime
driver to it.
Note that this also hides the NOR flash bank that carries the UEFI
executable code, but this is not intended to be updatable from inside
the guest anyway, and if it was, we should use capsule update to do so.
Also, the first -pflash argument that defines the backing for this flash
bank is often issued with the 'readonly' modifier, in order to prevent
any changes whatsoever to be made to the executable firmware image by
the guest. …
=> ArmVirtPkg/NorFlashQemuLib: disable NOR flash DT nodes upon discovery

ArmPkg/Library/ArmMmuLib/AArch64/ArmMmuLibCore.c
While building with the following command line:
build -b DEBUG -a AARCH64 -t VS2017 -p MdeModulePkg\MdeModulePkg.dsc
A missing cast triggers the following warning, then triggering an error:
ArmPkg/Library/ArmMmuLib/AArch64/ArmMmuLibCore.c(652):
warning C4152: nonstandard extension, function/data pointer
conversion in expression
This patch first casts the function pointer to (UINTN), then to (VOID *),
followowing the C99 standard s6.3.2.3 "Pointer", paragraphs 5 and 6.
This suppresses the warning.
Suggested-by: Laszlo Ersek <lersek@redhat.com>
=> ArmPkg/ArmMmuLib: Fix implicit cast

CryptoPkg/Driver/Crypto.c, CryptoPkg/Include/Library/BaseCryptLib.h, CryptoPkg/Library/BaseCryptLib/Hash/CryptMd5.c, CryptoPkg/Library/BaseCryptLib/Hash/CryptSha1.c, CryptoPkg/Library/BaseCryptLibOnProtocolPpi/CryptLib.c
Add MARCO to disable the deprecated functions MD5 and SHA1
=> Add MARCO to disable the MD5 and SHA1

ArmPlatformPkg/Library/PL011UartLib/PL011UartLib.c, ArmPlatformPkg/Library/PL011UartLib/PL011UartLib.inf
PL011UartLib determines its FIFO depth based on the PID2 value but
the register PID2 is not mandatory as per the SBSA spec.
This change won't check PID2 if PcdUartDefaultReceiveFifoDepth is set
to a value > 0.
Signed-off-by: Irene Park <ipark@nvidia.com>
=> ArmPlatformPkg/PL011UartLib: Check PID2 if FiFoDepth is zero

BaseTools/Scripts/PatchCheck.py
Bash scripts require LF line endings to work.
PatchCheck.py checks that the files added in a patch have CRLF
line endings. It excludes files ending with the ".sh" extension
from this check.
Some bash script don't have a ".sh" extension. Most of them are
located in:
- BaseTools/BinWrappers/PosixLike/
- BaseTools/Bin/CYGWIN_NT-5.1-i686/
This patch excludes these folder plus BaseTools/BuildEnv from
this CRLF check.
=> BaseTools: PatchCheck: Exclude bash scripts from CRLF check

PcAtChipsetPkg/PcAtChipsetPkg.dsc, SourceLevelDebugPkg/SourceLevelDebugPkg.dsc, UefiCpuPkg/Include/Library/UefiCpuLib.h, UefiCpuPkg/Library/BaseUefiCpuLib/BaseUefiCpuLib.c, UefiCpuPkg/Library/BaseUefiCpuLib/BaseUefiCpuLib.inf, UefiCpuPkg/Library/BaseXApicLib/BaseXApicLib.c, UefiCpuPkg/Library/BaseXApicLib/BaseXApicLib.inf, UefiCpuPkg/Library/BaseXApicX2ApicLib/BaseXApicX2ApicLib.c, UefiCpuPkg/Library/BaseXApicX2ApicLib/BaseXApicX2ApicLib.inf, UefiCpuPkg/Library/MpInitLib/MpLib.c, UefiCpuPkg/PiSmmCpuDxeSmm/Ia32/SmiEntry.nasm, UefiCpuPkg/PiSmmCpuDxeSmm/SmmProfile.c, UefiCpuPkg/PiSmmCpuDxeSmm/SmmProfileInternal.h, UefiCpuPkg/PiSmmCpuDxeSmm/X64/SmiEntry.nasm
https://edk2.groups.io/g/devel/message/61556
http://mid.mail-archive.com/20200622131825.1352-1-Garrett.Kirkendall@amd.com
~~~
AMD processor does not support MSR_IA32_MISC_ENABLE register.  Accessing
this register on AMD causes an unhandled exception in SmmEntry.nasm and
a subsequent failure to boot since this is too early in SMM path for the
exception handler to be loaded.
1. Prepare PcAtChipsetPkg/PcAtChipsetPkg.dsc to move
StandardSignatureIsAuthenticAMD into UefiCpuLib LibraryClass
BaseUefiCpuLib in UefiCpuPkg.
2. To distinguish between AMD and other processors, refactor
StandardSignatureIsAuthenticAMD into BaseUefiCpuLib.  So there is only
one copy in the source.
3. Skip manipulation of MSR_IA32_MISC_ENABLE register if running
on an AMD processor.
Tested on AMD X64 hardware.
OvmfIa32 …
=> [edk2-devel] [PATCH v6 0/4] AMD processor MSR_IA32_MISC_ENABLE -- push

UefiPayloadPkg/UefiPayloadPkg.fdf
When build UEFI payload using NOOPT, it would build failure since
the FV size. So this patch increases FV size to support NOOPT.
If not NOOPT build, there is no change to FV size.
=> UefiPayloadPkg:Fix NOOPT build failure

UefiPayloadPkg/UefiPayloadPkg.fdf, UefiPayloadPkg/UefiPayloadPkgIa32.dsc, UefiPayloadPkg/UefiPayloadPkgIa32X64.dsc
As the TerminalDxe significantly slows down the boot menu rendering,
add the DISABLE_SERIAL_TERMINAL option to disable it at build time.
Signed-off-by: Marcello Sylvester Bauer <marcello.bauer@9elements.com>
=> UefiPayloadPkg: Make TerminalDxe build time configurable

SecurityPkg/Tcg/Tcg2Pei/Tcg2Pei.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2840
Signed-off-by: Jiewen Yao <jiewen.yao@intel.com>
=> SecurityPkg/Tcg2Pei: Add missing PCRIndex in FvBlob event.

UefiPayloadPkg/UefiPayloadPkgIa32.dsc, UefiPayloadPkg/UefiPayloadPkgIa32X64.dsc
This patch fixed the merge issue for the previous TerminalDxe patch.
Signed-off-by: Marcello Sylvester Bauer <marcello.bauer@9elements.com>
=> UefiPayloadPkg: Fix TerminalDxe build time configurable

MdeModulePkg/Universal/Disk/PartitionDxe/Mbr.c, MdeModulePkg/Universal/Disk/PartitionDxe/Partition.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2823
Drop V1 because it is a bug: there should not be two partition types in one media.
1. Correct the LastBlock value in MBR handler. It should be the number of
sectors (512 bytes).
2. Skip the MBR check if the MBR is added for the Windows comaptiblity. We treat such
media as ElTorito and do the check.
3. Fix the partition check bug: One partition type returns already started should
be treated as success to avoid multi partition type be installed into same media.
=> MdeModulePkg/PartitionDxe: Fix the partition check issue

MdeModulePkg/Core/Dxe/Gcd/Gcd.c, MdeModulePkg/Core/Dxe/Mem/Page.c, MdeModulePkg/Core/Dxe/Misc/MemoryProtection.c, MdeModulePkg/Core/PiSmmCore/PiSmmIpl.c, MdePkg/Include/Uefi/UefiSpec.h, UefiCpuPkg/CpuDxe/CpuDxe.c, UefiCpuPkg/CpuDxe/CpuDxe.h, UefiCpuPkg/CpuDxe/CpuPageTable.c, UefiCpuPkg/PiSmmCpuDxeSmm/SmmCpuMemoryManagement.c
https://edk2.groups.io/g/devel/message/61992
http://mid.mail-archive.com/20200702205039.52400-1-oleksiyy@ami.com
~~~
This series of patches add usage of new memory
attributes EFI_MEMORY_SP and EFI_MEMORY_CPU_CRYPTO,
introduced in UEFI2.8 (mantis 1919 and 1872).
First patch fix typos in description and introduce two
bitmasks for all memory type attributes.
Second and fourth patches get rid of multiple memory attributes
bitmasks definitions trough multiple files and headers,
and replace them with new common definitions from MdePkg.
Third patch includes WP attribute into cache type mask in
CpuDexe.h to make next change in this file more clear.
Oleksiy Yakovlev (4):
MdePkg: Add New Memory Attributes
MdeModulePkg: Add New Memory Attributes
UefiCpuPkg: Update EFI_MEMORY_CACHETYPE_MASK …
=> [edk2-devel] [PATCH V3 0/4] Add New Memory Attributes -- push

SignedCapsulePkg/Universal/SystemFirmwareUpdate/SystemFirmwareUpdateDxe.c
Original code GetFmpImageDescriptors for OriginalFmpImageInfoBuf
pointer, if failed, return a NULL pointer. The OriginalFmpImageInfoBuf
should not be NULL and the NULL pointer dereference case
should be false positive.
Signed-off-by: Vin Xue <vinxue@outlook.com>
=> SignedCapsulePkg: Address NULL pointer dereference case.

BaseTools/Source/Python/AutoGen/WorkspaceAutoGen.py, BaseTools/Source/Python/Common/GlobalData.py, BaseTools/Source/Python/GenFds/FdfParser.py
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2762
The Fv Section in the FDF files use hard coding Guid values
which is inconvenient to manage. This patch adds Guid name
support in GenFfs to solve this problem.
Reviewed-by: Bob Feng<bob.c.feng@intel.com>
=> BaseTools: Add Guid name support in GenFfs.

Maintainers.txt, OvmfPkg/Include/IndustryStandard/LsiScsi.h, OvmfPkg/LsiScsiDxe/LsiScsi.c, OvmfPkg/LsiScsiDxe/LsiScsi.h, OvmfPkg/LsiScsiDxe/LsiScsiDxe.inf, OvmfPkg/OvmfPkg.dec, OvmfPkg/OvmfPkgIa32.dsc, OvmfPkg/OvmfPkgIa32.fdf, OvmfPkg/OvmfPkgIa32X64.dsc, OvmfPkg/OvmfPkgIa32X64.fdf, OvmfPkg/OvmfPkgX64.dsc, OvmfPkg/OvmfPkgX64.fdf
http://mid.mail-archive.com/20200717061130.8881-1-glin@suse.com
https://edk2.groups.io/g/devel/message/62722
~~~
This patch series implement the driver for LSI 53C895A SCSI controller
for OVMF so that the user can access the storage devices connected to
QEMU "lsi" controller. The driver is disabled by default since LSI
53C895A is considered as a legacy device. To enable the driver, please
add "-D LSI_SCSI_ENABLE" when building OvmfPkg.
The patch series is also available in my git branch:
https://github.com/lcp/edk2/tree/ovmf-lsi-v3
v3:
- Set DStat, SIst0, and SIst1 to 0 before using them
- Amend the if statements for the DMA data instruction and add the
assertions …
=> [edk2-devel] [PATCH v3 00/11] Introduce LsiScsi driver to OvmfPkg -- push

BaseTools/Scripts/PatchCheck.py
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2836
Current PatchCheck.py checks each line to ensure line's length is not
larger than 76. But there's a case that length of user's name is much
longer than that number. So enhance the script to handle this case.
Reviewed-by: Yuwei Chen<yuwei.chen@intel.com>
=> BaseTools/PatchCheck.py: Skip length check for user name in xxx-by

MdeModulePkg/Library/DxeCorePerformanceLib/DxeCorePerformanceLib.c
UnicodeStrToAsciiStrS requires that the source string is shorter than
the destination buffer and will ASSERT if this is not true. Switch to
UnicodeStrnToAsciiStrS as there are cases where the source string is
longer than the buffer allocated for the device path.
=> MdeModulePkg/DxeCorePerformanceLib: Switch to UnicodeStrnToAsciiStrS

BaseTools/Source/Python/GenFds/EfiSection.py
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2624
When EFI file come from binary file, not generate .map file, so need ignore the map file.
Signed-off-by: Yunhua Feng <yunhuax.feng@intel.com>
=> BaseTools: Fix binary file not generate map file issue

BaseTools/Scripts/PatchCheck.py
If the submodule is upgraded, skip the CRLF check as it isn't change for
file.
=> BaseTools/Scripts: Ignore the CRLF check when upgrade submodule.

IntelFsp2Pkg/Tools/GenCfgOpt.py
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2827
Fix a bug about parse the macro value which use another macro.
Use the following example to verify:
[Define]
DEFINE M1 = V1
DEFINE M2 = $(M1)/V2
!include $(M2)/pcd.dsc
The old code will failed parse M2 and cause following error:
Traceback (most recent call last):
File "Edk2\IntelFsp2Pkg\Tools\GenCfgOpt.py", line 1550, in <module>
sys.exit(Main())
File "Edk2\IntelFsp2Pkg\Tools\GenCfgOpt.py", line 1513, in Main
if GenCfgOpt.ParseDscFile(DscFile, FvDir) != 0:
File "Edk2\IntelFsp2Pkg\Tools\GenCfgOpt.py", line 533, in ParseDscFile
NewDscLines = IncludeDsc.readlines()
ValueError: I/O operation on closed file.
The tool should support the value use another macro, and expand it.
Cc: Nate DeSimone …
=> IntelFsp2Pkg/Tools/GenCfgOpt.py: Fix a bug about parse macro

BaseTools/Conf/tools_def.template
This reverts commit dbd546a32d5abe225306e22d43a7d86e3a042eee.
This patch also breaks about half of the ARM/AARCH64 platforms in edk2-platforms
=> Revert "BaseTools: Add gcc flag to warn on void* pointer arithmetic"

MdePkg/Include/IndustryStandard/Cxl.h, MdePkg/Include/IndustryStandard/Cxl11.h, MdePkg/Include/IndustryStandard/Pci.h
BZ: https://bugzilla.tianocore.org/show_bug.cgi?id=2611
Register definitions from chapter 7 of Compute Express Link
Specification Revision 1.1 are ported into the new Cxl11.h.
The CXL Flex Bus registers are based on the PCIe Extended Capability
DVSEC structure header, led to the inclusion of upgraded Pci.h.
=> MdePkg/Include/IndustryStandard: CXL 1.1 Registers

MdePkg/Include/Base.h
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=1004
Being a compiler builtin, the type of __builtin_return_address is
already known to the compiler so no prototype is needed. Clang also
errors out when redeclaring certain builtins like this[1], though
currently only for ones with custom type checking. At the moment,
__builtin_return_address does not use custom type checking and so does
not trigger this error, however, the CHERI fork of LLVM, which will form
the basis of the toolchain for Arm's experimental Morello platform, does
use custom type checking for it, and so gives an error. Thus, simply
delete the unnecessary line.
[1] llvm/llvm-project@41af97137572ad6d4dafc872e7ecf6bbb08d4984
Signed-off-by: Jessica Clarke <jrtc27@jrtc27.com> …
=> MdePkg Base.h: Delete prototype for __builtin_return_address

BaseTools/Source/C/Common/PeCoffLoaderEx.c
BZ:2864 GCC build fails due to variable self assignment.
This local variable is not used at any where, we can just remove it.
=> BaseTools/PeCoffLoaderEx: Remove the unused local variable

.pytool/Plugin/LicenseCheck/LicenseCheck.py, .pytool/Plugin/LicenseCheck/LicenseCheck_plug_in.yaml, .pytool/Plugin/LicenseCheck/Readme.md, ArmVirtPkg/ArmVirtPkg.ci.yaml, CryptoPkg/CryptoPkg.ci.yaml, EmulatorPkg/EmulatorPkg.ci.yaml, FatPkg/FatPkg.ci.yaml, FmpDevicePkg/FmpDevicePkg.ci.yaml, MdeModulePkg/MdeModulePkg.ci.yaml, MdePkg/MdePkg.ci.yaml, NetworkPkg/NetworkPkg.ci.yaml, OvmfPkg/OvmfPkg.ci.yaml, PcAtChipsetPkg/PcAtChipsetPkg.ci.yaml, SecurityPkg/SecurityPkg.ci.yaml, ShellPkg/ShellPkg.ci.yaml, UefiCpuPkg/UefiCpuPkg.ci.yaml, UnitTestFrameworkPkg/UnitTestFrameworkPkg.ci.yaml
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2691
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2833
LicenseCheck is now enabled in PatchCheck.py. But there's a patch "Revert 'BaseTools/PatchCheck.py: Add LicenseCheck'"
to suggest revert the change.These patch series introduce a plugin LicenseCheck into open ci so that license issues can still be checked after the checker is disabled in PatchCheck.py.
1/15 is the plugin implementation.
2/15 ~ 15/15 introduce sections "IgnoreFiles" to allow developers to skip license check for some files like generated files.
Only BSD-2-Clause-Patent can pass this checker.
=> Add a plugin LicenseCheck in open ci

BaseTools/Scripts/PatchCheck.py
This reverts commit a4cfb842fca9693a330cb5435284c1ee8bfbbace.
This commit suggests inclusion of non-edk2+license content without
a contribution agreement is something the community has made a
decision on, which is incorrect.
Cc: Shenglei Zhang <shenglei.zhang@intel.com>
=> Revert "BaseTools/PatchCheck.py: Add LicenseCheck"

UefiCpuPkg/PiSmmCpuDxeSmm/MpService.c
http://mid.mail-archive.com/20200729185217.10084-1-lersek@redhat.com
https://edk2.groups.io/g/devel/message/63454
~~~
Most busy waits (spinlocks) in "UefiCpuPkg/PiSmmCpuDxeSmm/MpService.c"
already call CpuPause() in their loop bodies; see SmmWaitForApArrival(),
APHandler(), and SmiRendezvous(). However, the "main wait" within
APHandler():
>     //
>     // Wait for something to happen
>     //
>     WaitForSemaphore (mSmmMpSyncData->CpuData[CpuIndex].Run);
doesn't do so, as WaitForSemaphore() keeps trying to acquire the semaphore
without pausing.
The performance impact is especially notable in QEMU/KVM + OVMF
virtualization with CPU overcommit (that is, when the guest has
significantly more VCPUs than the host has physical CPUs). The guest BSP
is working heavily in:
BSPHandler() …
=> [edk2-devel] [PATCH] UefiCpuPkg/PiSmmCpuDxeSmm: pause in WaitForSemaphore() before re-fetch -- push

EmbeddedPkg/Include/Library/TimeBaseLib.h
These can be used, for instance, to automate the population of an SMBIOS
Type 0 BIOS Release Date when building a UEFI firmware (which is how we
plan to use these macros for the Raspberry Pi platform).
These macros should work for any compiler that follows ISO/IEC 9899, but
we add a check for the compiler we have tested to be on the safe side.
Note that we decided against adding a #error or #warn for compilers that
haven't been validated, as we don't want to introduce breakage for people
who may already be using the header with something else than gcc, MSVC or
Clang. Instead, we expect those to send a patch that adds their compiler
to the list, once they have tested the macros there.
Signed-off-by: Pete Batard <pete@akeo.ie>
=> EmbeddedPkg/TimeBaseLib: Add macros to get build year/month/day

BaseTools/Source/C/GenSec/GenSec.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2345
=> BaseTools/GenSec: Fix spelling mistake

BaseTools/Source/Python/AutoGen/AutoGenWorker.py, BaseTools/Source/Python/build/build.py
Ref: https://bugzilla.tianocore.org/show_bug.cgi?id=2807
The Queue.empty() method is not reliable in the multiple
process runtime environment. This patch uses a new method
to check if all modules are processed and workers need
to be stopped. That is to add a None item at the bottom
of the queue. Worker check if it gets that None item to
know if all the module is processed.
Cc: Lucy Yan <lucyyan@google.com>
=> BaseTools: Improve the method of checking queue empty

FmpDevicePkg/FmpDxe/FmpDxe.c, FmpDevicePkg/Include/Library/FmpDependencyLib.h, FmpDevicePkg/Library/FmpDependencyCheckLib/FmpDependencyCheckLib.c, FmpDevicePkg/Library/FmpDependencyLib/FmpDependencyLib.c
From: Michael Kubacki <michael.kubacki@microsoft.com>
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=2869
This patch series makes minor fixes and enhancements in
FmpDevicePkg. None of the issues impact functionality in a
major way.
These are smaller sets of changes that are being submitted prior
to a larger future patch series that will cover functional changes
for BZ2802.
Note: The v3 series with Reviewed-bys is on the following branch.
https://github.com/makubacki/edk2/tree/fmpdevicepkg_minor_fixes
V3 changes:
1. 1. [PATCH v2 7/7]:
* Reverted retval descriptions in FmpDxe FMP functions back
to the original description. These will be updated collectively
to match the latest text in the UEFI Spec 2.8B in the future.
V2 changes:
1. [PATCH v1 7/7]:
* Added a DEBUG_ERROR message if the …
=> FmpDevicePkg Minor Fixes

ShellPkg/Library/UefiShellDebug1CommandsLib/SmbiosView/PrintInfo.c
Change how some SMBIOS TYpe 17 field values are printed:
- TotalWidth, DataWidth, ConfiguredMemoryClockSpeed: Print as
hex values instead of decimal, since there are some special meanings
for certain values (e.g. 0xFFFF)
- VolatileSize, NonVolatileSize, CacheSize, and LogicalSize: Print
as "0x%lx" instead of "0x%x" to prevent truncating output when
printing these QWORD fields.
Signed-off-by: Samer El-Haj-Mahmoud <samer.el-haj-mahmoud@arm.com>
=> ShellPkg: smbiosview - Change some type 17 field values format

MdePkg/Library/BaseLib/RiscV64/RiscVInterrupt.S
While RISC-V hart is trapped into S-Mode, the S-Mode interrupt
CSR (SIE) is disabled by RISC-V hart. However the (SIE) is enabled
again by RestoreTPL, this causes the second S-Mode trap is triggered
by the machine mode (M-Mode)timer interrupt redirection. The SRET
instruction clear Supervisor Previous Privilege (SPP) to zero
(User mode) in the second S-Mode interrupt according to the RISC-V
spec. Above brings hart to the user mode (U-Mode) when execute
SRET in the nested S-Mode interrupt handler because SPP is set to
User Mode in the second interrupt. Afterward, system runs in U-Mode
and any accesses to S-Mode CSR causes the invalid instruction exception.
Cc: Liming Gao …
=> BaseLib:Fix RISC-V Supervisor mode (S-Mode) trap handler reentry issue.

CryptoPkg/Library/OpensslLib/OpensslLib.inf
Remove the redundant build option for RISCV64 architecture.
BZ: https://bugzilla.tianocore.org/show_bug.cgi?id=2848
Reviewed-by: Guomin Jiang <guomin.jiang@intel.com>
=> CryptoPkg/Library: Remove the redundant build option

MdeModulePkg/Universal/Disk/PartitionDxe/Mbr.c, MdeModulePkg/Universal/Disk/PartitionDxe/Partition.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2823
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2843
Refer to the UEFI spec 2.8, Section 13.3.2:
A block device should be scanned as below order:
1. GPT
2. ISO 9660 (El Torito) (UDF should aslo be here)
4. MBR
5. no partition found
But the code implementation is:
1. GPT
2. MBR
3. ISO 9660 (El Torito) (UDF)
4. no partition found
Which would cause the ISO 9960 image with MBR info be treated as MBR
device. That would cause unexpect behavior. So fix it to follow the spec
description.
The fix of the PartitionInstallChildHandle would change the boot behavior
of Linux ISO image with MBR table. So add it after the order adjustment
to make no impact of the boot.
V2:
1. Add description of the different behavior between grub boot from MBR …
=> MdeModulePkg/PartitionDxe: Make the parition driver match the spec

FmpDevicePkg/FmpDxe/FmpDxe.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2887
The local Private pointer variable in SetTheImage() is initialized
based on the caller provided This pointer argument. The cleanup
label path uses the Private pointer which will not be
initialized if This is NULL.
This change initializes Private to NULL and accounts for Private
potentially being NULL in the cleanup label path.
Cc: Wei6 Xu <wei6.xu@intel.com>
Tested-by: Liming Gao <liming.gao@intel.com>
Reviewed-by: Guomin Jiang <guomin.jiang@intel.com>
=> FmpDevicePkg/FmpDxe: Fix Clang build error

BaseTools/Source/Python/AutoGen/AutoGenWorker.py, BaseTools/Source/Python/build/build.py
AsBuiltInf can be created during AutoGen phase. Move CreateAsBuiltInf
into AutoGenWorker to make this step run in parallel.
Reviewed-by: Jaben Carsey <jaben.carsey@intel.com>
=> BaseTools: Move CreateAsBuiltInf into AutoGenWorker for parallel

BaseTools/set_vsprefix_envs.bat
BZ: https://bugzilla.tianocore.org/show_bug.cgi?id=2896
When VS2017/VS2019 are both installed. VS prefix setting will
wrongly be set. VS2017_PREFIX is set to the same value of VS2019.
This patch clears VSINSTALLDIR and VCToolsVersion env, then
the different vcvars32 can set the correct VS env.
=> BaseTools: Fix the issue in VS prefix setting for VS2017/VS2019

CONTRIBUTING.md
https://edk2.groups.io/g/devel/message/64005
http://mid.mail-archive.com/df6219e77613e93c494996437cf53e302c473392.1597168987.git.crobinso@redhat.com
~~~
Googling for 'edk2 pull request' did not find this wiki page:
https://github.com/tianocore/tianocore.github.io/wiki/EDK-II-Development-Process
Add it to CONTRIBUTING.md for more discoverability.
(When someone opens a pull request, they will see a link to
CONTRIBUTING.md; see
<https://docs.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors>.)
Signed-off-by: Cole Robinson <crobinso@redhat.com>
Message-Id: <df6219e77613e93c494996437cf53e302c473392.1597168987.git.crobinso@redhat.com>
[lersek@redhat.com: add paragraph with docs.github.com reference]
~~~
=> Add a stub CONTRIBUTING.md pointing to the wiki -- push

.pytool/Plugin/EccCheck/EccCheck.py
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2920
Ecc issues whose error code is 10014, can't be correctly handled
under Linux OS, resulting from a bug in Ecc tool.
So we need to disable it before ecc tool is repaired.
=> .pytool/EccCheck: Disable Ecc error code 10014 for open CI

MdePkg/Library/UefiFileHandleLib/UefiFileHandleLib.c
https://edk2.groups.io/g/devel/message/61938
http://mid.mail-archive.com/20200702023113.10517-1-vladimir.olovyannikov@broadcom.com
~~~
If the size of the supplied buffer in FileHandleReadLine(), module
UefiFileHandleLib.c, was not 0, but was not enough to fit in
the line, the size is increased, and then the Buffer of the new
size is zeroed. This size is always larger than the supplied buffer size,
causing supplied buffer overrun. Fix the issue by using the
supplied buffer size in ZeroMem().
Signed-off-by: Vladimir Olovyannikov <vladimir.olovyannikov@broadcom.com>
Message-Id: <20200702023113.10517-1-vladimir.olovyannikov@broadcom.com>
Reviewed-by: Zhiguang Liu …
=> [PATCH v2 1/1] MdePkg: UefiFileHandleLib: fix buffer overrun in FileHandleReadLine() -- push

OvmfPkg/SmmControl2Dxe/SmiFeatures.c, OvmfPkg/SmmControl2Dxe/SmmControl2Dxe.inf
https://edk2.groups.io/g/devel/message/62561
http://mid.mail-archive.com/20200714184305.9814-1-lersek@redhat.com
~~~
The ICH9_LPC_SMI_F_BROADCAST and ICH9_LPC_SMI_F_CPU_HOTPLUG feature flags
cause QEMU to behave as follows:
BROADCAST  CPU_HOTPLUG  use case / behavior
---------  -----------  ------------------------------------------------
clear      clear        OVMF built without SMM_REQUIRE; or very old OVMF
(from before commit a316d7ac91d3 / 2017-02-07).
QEMU permits CPU hotplug operations, and does
not cause the OS to inject an SMI upon hotplug.
Firmware is not expected to be aware of hotplug
events.
clear      set          Invalid feature set; QEMU rejects the feature
negotiation.
set        clear        OVMF after a316d7ac91d3 / 2017-02-07, built with
SMM_REQUIRE, but no support for …
=> OvmfPkg/SmmControl2Dxe: negotiate ICH9_LPC_SMI_F_CPU_HOTPLUG -- push

EmbeddedPkg/Include/libfdt_env.h
https://edk2.groups.io/g/devel/message/63767
http://mid.mail-archive.com/20200806023421.25161-1-abner.chang@hpe.com
~~~
For the implementation which utilizes libfdt provided in EmbeddedPkg
however it uses strncmp function in the libfdt helper library,
libfdt_env.h should provide the macro implied with edk2 strncmp
implementation.
The example is RISC-V OpenSBI library. edk2 RISC-V port uses OpenSBI
library and incorporate with edk2 libfdt. edk2 libfdt_env.h provides
the necessary macros to build OpenSBI which uses fdt functions in edk2
environment. However, OpenSBI also has libfdt helper library that uses
strncmp function which is not defined in edk2 libfdt_env.h. This commit
addresses the build issue caused by missing strncmp macro in
libfdt_env.h.
Check below three commits for the …
=> EmbeddedPkg/libfdt: Add strncmp macro to use AsciiStrnCmp -- push

UefiCpuPkg/Library/MpInitLib/MpLib.c
https://edk2.groups.io/g/devel/message/64507
http://mid.mail-archive.com/76a9f18992475b915e5f8457704676067210cacf.1597935198.git.thomas.lendacky@amd.com
~~~
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2901
The DoDecrement variable in ApWakeupFunction () wasn't always being
initialized. Update the code to always fully initialize it.
Signed-off-by: Tom Lendacky <thomas.lendacky@amd.com>
Message-Id: <76a9f18992475b915e5f8457704676067210cacf.1597935198.git.thomas.lendacky@amd.com>
Tested-by: Liming Gao <liming.gao@intel.com>
~~~
=> [PATCH v2 1/1] UefiCpuPkg/MpInitLib: Always initialize the DoDecrement variable -- push

MdePkg/Include/IndustryStandard/SmBios.h
Add host interface Protocol Type Data Format structure in SmBios.h
BZ: https://bugzilla.tianocore.org/show_bug.cgi?id=2328
=> MdePkg/Include: Add missing definition of SMBIOS type 42h in SmBios.h

IntelFsp2WrapperPkg/FspmWrapperPeim/FspmWrapperPeim.c, IntelFsp2WrapperPkg/FspmWrapperPeim/FspmWrapperPeim.inf, IntelFsp2WrapperPkg/FspsWrapperPeim/FspsWrapperPeim.c, IntelFsp2WrapperPkg/FspsWrapperPeim/FspsWrapperPeim.inf, IntelFsp2WrapperPkg/Include/Library/FspMeasurementLib.h, IntelFsp2WrapperPkg/IntelFsp2WrapperPkg.dec, IntelFsp2WrapperPkg/IntelFsp2WrapperPkg.dsc, IntelFsp2WrapperPkg/Library/BaseFspMeasurementLib/BaseFspMeasurementLib.inf, IntelFsp2WrapperPkg/Library/BaseFspMeasurementLib/FspMeasurementLib.c, SecurityPkg/Include/Library/TcgEventLogRecordLib.h, SecurityPkg/Include/Ppi/Tcg.h, SecurityPkg/Library/TcgEventLogRecordLib/TcgEventLogRecordLib.c, SecurityPkg/Library/TcgEventLogRecordLib/TcgEventLogRecordLib.inf, SecurityPkg/Library/TcgEventLogRecordLib/TcgEventLogRecordLib.uni, SecurityPkg/SecurityPkg.dec, SecurityPkg/SecurityPkg.dsc, SecurityPkg/Tcg/Tcg2Pei/Tcg2Pei.c
https://bugzilla.tianocore.org/show_bug.cgi?id=2376
https://edk2.groups.io/g/devel/message/64354
http://mid.mail-archive.com/20200818062618.3698-1-qi1.zhang@intel.com
~~~
v4 change:
rename FvEventLogRecordLib to TcgEventLogRecordLib.
v3 change:
add a new lib FvEventLogRecordLib for gerneric code.
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2376
The EDKII BIOS calls FSP API in FSP Wrapper Pkg.
This FSP code need to be measured into TPM.
We need add a generic module in FSP Wrapper Pkg code to measure:
1) FSP-T, FSP-M, FSP-S in API mode.
2) FSP-T in Dispatch-mode. The FSP-M and FSP-S will be reported
as standard FV and they will be measured by TCG-PEI.
Cc: Chasel Chiu …
=> [edk2-devel] [PATCH v4 0/8] Need add a FSP binary measurement -- push

OvmfPkg/CpuHotplugSmm/CpuHotplug.c, OvmfPkg/CpuHotplugSmm/Smbase.c
https://bugzilla.tianocore.org/show_bug.cgi?id=2929
https://edk2.groups.io/g/devel/message/64659
http://mid.mail-archive.com/20200826222129.25798-1-lersek@redhat.com
~~~
Ref:    https://bugzilla.tianocore.org/show_bug.cgi?id=2929
Branch: cpu_hotplug_races_bz_2929
Proposing these bugfixes for edk2-stable202008. We should either include
them in the release, or revert commit 5ba203b54e59
("OvmfPkg/SmmControl2Dxe: negotiate ICH9_LPC_SMI_F_CPU_HOTPLUG",
2020-08-24). Please see the BZ for more details.
Cc: Igor Mammedov <imammedo@redhat.com>
Thanks,
Laszlo
Laszlo Ersek (2):
OvmfPkg/CpuHotplugSmm: fix CPU hotplug race …
=> [edk2-devel] [PATCH 0/2] OvmfPkg: fix race conditions in VCPU hotplug (for edk2-stable202008) -- push

MdePkg/Include/IndustryStandard/Acpi10.h
In Acpi10.h, EFI_ACPI_DMA_TRANSFER_TYPE_16_BIT is defined as 0x10,
but should be 0x02 per the ACPI Specification.
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=2937
Signed-off-by: Paul G <paul.grimes@amd.com>
=> MdePkg: Correcting EFI_ACPI_DMA_TRANSFER_TYPE_16_BIT definition

SecurityPkg/Tcg/Tcg2Pei/Tcg2Pei.c
https://bugzilla.tianocore.org/show_bug.cgi?id=2945
https://edk2.groups.io/g/devel/message/64865
http://mid.mail-archive.com/20200901005505.1722-1-zhiguang.liu@intel.com
~~~
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2945
V2: Move "Status = EFI_SUCCESS;" before the EDKII_TCG_PRE_HASH check.
Message-Id: <20200901005505.1722-1-zhiguang.liu@intel.com>
~~~
=> [edk2-devel] [PATCH] SecurityPkg: Initailize variable Status before it is consumed. -- push

BaseTools/Source/Python/Ecc/Check.py
https://bugzilla.tianocore.org/show_bug.cgi?id=2904
https://edk2.groups.io/g/devel/message/64887
http://mid.mail-archive.com/20200901102315.38840-1-bob.c.feng@intel.com
~~~
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2904
The path separator is different in Windows and Linux, the
original code does not handle this difference. This patch
is to fix this issue.
Cc: Shenglei Zhang <shenglei.zhang@intel.com>
Message-Id: <20200901102315.38840-1-bob.c.feng@intel.com>
~~~
=> [edk2-devel] [Patch V2] BaseTools/Ecc: Fix an issue of path separator compatibility -- push

SecurityPkg/Library/DxeImageVerificationLib/DxeImageVerificationLib.c
https://bugzilla.tianocore.org/show_bug.cgi?id=2215
https://edk2.groups.io/g/devel/message/64882
http://mid.mail-archive.com/20200901091221.20948-1-lersek@redhat.com
~~~
Ref:    https://bugzilla.tianocore.org/show_bug.cgi?id=2215
Branch: tianocore_2215
I'm neutral on whether this becomes part of edk2-stable202008.
Cc: Wenyi Xie <xiewenyi2@huawei.com>
Thanks,
Laszlo
Laszlo Ersek (3):
SecurityPkg/DxeImageVerificationLib: extract SecDataDirEnd,
SecDataDirLeft
SecurityPkg/DxeImageVerificationLib: assign WinCertificate after size
check
SecurityPkg/DxeImageVerificationLib: catch alignment overflow
(CVE-2019-14562) …
=> [edk2-devel] [PATCH 0/3] SecurityPkg/DxeImageVerificationLib: catch alignment overflow (CVE-2019-14562) -- push

SecurityPkg/Library/DxeImageVerificationLib/DxeImageVerificationLib.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2943
Disable SHA1 base on the MACRO DISABLE_SHA1_DEPRECATED_INTERFACES.
SHA1 is deprecated function and the MACRO is used to remove the whole
implementation of the SHA1. For the platforms that do not need SHA1
for security, the MACRO should works for DxeImageVerificationLib as
well.
=> SecurityPkg/DxeImageVerificationLib: Disable SHA1 base on MACRO

BaseTools/Source/Python/AutoGen/PlatformAutoGen.py, BaseTools/Source/Python/Workspace/DscBuildData.py
If VPD PcdNvStoreDefaultValueBuffer is used, all DynamicHii and
DynamicExHii PCD value will be generated into that VPD.
In order to generate the same VPD binary file in every build,
sort the Pcd set when generating VPD.
=> BaseTools: Sort the Pcd set when generating the VPD binary

EmbeddedPkg/Include/Library/TimeBaseLib.h
https://edk2.groups.io/g/devel/message/65058
http://mid.mail-archive.com/20200904154541.23340-1-lersek@redhat.com
~~~
The SEC_PER_MONTH and SEC_PER_YEAR macros are wrong: they both evaluate to
0 (of type "int"). They are also unused (they could never be used for
division, for example); so remove them. The macros were originally
introduced in commit 0f4386e775c7 ("ArmPlatformPkg/PL031RealTimeClockLib:
Implement PL031 RTC drive", 2011-06-11).
Reported-by: Maciej Rabeda <maciej.rabeda@linux.intel.com>
Message-Id: <20200904154541.23340-1-lersek@redhat.com>
Reviewed-by: …
=> [edk2-devel] [PATCH] EmbeddedPkg/TimeBaseLib: remove the SEC_PER_MONTH, SEC_PER_YEAR macros -- push

UefiPayloadPkg/UefiPayloadPkgIa32.dsc, UefiPayloadPkg/UefiPayloadPkgIa32X64.dsc
The BaseSerialPortLib16550 does fallback to a fixed address UART defined
by PcdSerialRegisterBase and does not initialize if it is zero. Do not
assume a serial port at 0x3F8, otherwise it could cause errors during
initialization of a non-existent serial port on non legacy platforms.
Signed-off-by: Marcello Sylvester Bauer <marcello.bauer@9elements.com>
=> UefiPayloadPkg: Remove x86 legacy UART defaults

EmulatorPkg/EmulatorPkg.dec
edk2 DEC specification document only knows about DEC_SPECIFICATION,
so using DEC_VERSION in [Defines] section in EmulatorPkg.dec is not
correct.
=> EmulatorPkg:Change DEC_VERSION to DEC_SPECIFICATION

UefiCpuPkg/Library/RegisterCpuFeaturesLib/PeiRegisterCpuFeaturesLib.c, UefiCpuPkg/Library/RegisterCpuFeaturesLib/PeiRegisterCpuFeaturesLib.inf, UefiCpuPkg/Library/RegisterCpuFeaturesLib/RegisterCpuFeatures.h
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2883
MpServices Ppi can be replaced by MpServices2 Ppi and MpServices2
Ppi is mandatory for RegisterCpuFeaturesLib functionality,
basing on this we can drop MpServices Ppi usage from the library
and the constraint that both Ppis must be installed.
=> UefiCpuPkg/RegisterCpuFeaturesLib: Support MpServices2 only case.

BaseTools/Bin/iasl_ext_dep.yaml
The IASL extdep is used for CI only and a recent fork of the ACPICA
repo was made to make nuget builds more regular and easier to audit.
https://dev.azure.com/projectmu/_git/acpica
Signed-off-by: Matthew Carlson <matthewfcarlson@gmail.com>
=> BaseTools: update IASL extdep to more modern version

OvmfPkg/Library/VirtioMmioDeviceLib/VirtioMmioDevice.c
There is a DEBUG warning printout in VirtioMmioDeviceLib if the current
device's VendorID does not match the traditional 16-bit Red Hat PCIe
vendor ID used with virtio-pci. The virtio-mmio vendor ID is 32-bit and
has no connection to the PCIe registry.
Most specifically, this causes a bunch of noise when booting an AArch64
QEMU platform, since QEMU's virtio-mmio implementation used 'QEMU' as
the vendor ID:
VirtioMmioInit: Warning:
The VendorId (0x554D4551) does not match the VirtIo VendorId (0x1AF4).
Drop the warning message.
Reviewed-by: Philippe Mathieu-Daudé …
=> OvmfPkg: drop redundant VendorID check in VirtioMmioDeviceLib

MdeModulePkg/Bus/Pci/NonDiscoverablePciDeviceDxe/NonDiscoverablePciDeviceIo.c
Add check for NULL HostAddress in AllocateBuffer as required by UEFI
specification.
=> MdeModulePkg/NonDiscoverablePciDeviceDxe: Add NULL pointer check

EmulatorPkg/EmulatorPkg.dsc
* Recently, OpensslLib [LibraryClasses] has been changed
to include RngLib which causes the SECURE_BOOT_ENABLE
build to fail in want of RngLib
* This patch adds the RngLib for OpensslLib
Signed-off-by: Divneil Rai Wadhawan <divneil.r.wadhawan@intel.com>
=> EmulatorPkg: Add RngLib to satisfy dependency of OpensslLib

.mailmap
https://edk2.groups.io/g/devel/message/65096
http://mid.mail-archive.com/20200907193102.30535-1-lersek@redhat.com
Note: this pull request only contains the following patches from the series, given that the rest has not received sufficient feedback / approval:
~~~
[edk2-devel] [PATCH 05/22] .mailmap: add entry for Zhichao Gao
[edk2-devel] [PATCH 09/22] .mailmap: add entry for Tom Lendacky
[edk2-devel] [PATCH 11/22] .mailmap: add entry for Zhiguang Liu
[edk2-devel] [PATCH 15/22] .mailmap: add entry for Wei6 Xu
[edk2-devel] [PATCH 17/22] .mailmap: add entry for Matt DeVillier
[edk2-devel] [PATCH 20/22] .mailmap: add (another) entry for Liming Gao
[edk2-devel] [PATCH 22/22] .mailmap: add entries for Rebecca Cran
~~~
Original cover letter:
~~~
Branch: …
=> [edk2-devel] [PATCH 00/22] .mailmap: add mappings after edk2-stable202008 -- push

OvmfPkg/README
https://bugzilla.tianocore.org/show_bug.cgi?id=2852
https://edk2.groups.io/g/devel/message/65433
http://mid.mail-archive.com/20200922091827.12617-1-lersek@redhat.com
~~~
In QEMU commit range 4abf70a661a5..69699f3055a5 (later fixed up in QEMU
commit 4318432ccd3f), Phil implemented a QEMU facility for exposing the
host-side TLS cipher suite configuration to OVMF. The purpose is to
control the permitted ciphers in the guest's UEFI HTTPS boot. This
complements the forwarding of the host-side crypto policy from the host to
the guest -- the other facet was the set of CA certificates (for which
p11-kit patches had been upstreamed, on the host side).
Mention the new command line options in "OvmfPkg/README".
Cc: Gary Lin <glin@suse.com>
Cc: Jordan Justen …
=> [edk2-devel] [PATCH v2] OvmfPkg/README: HTTPS Boot: describe host-side TLS cipher suites forwarding -- push

EmulatorPkg/Win/Host/WinHost.c
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=2947
When calculating memory regions and store the information in the
gSystemMemory in file WinHost.c, the code below will cause overflow,
because _wtoi (MemorySizeStr) return an int value and SIZE_1MB is
also an int value, if MemorySizeStr is lager for example 2048, then
result of multiplication will overflow.
for (Index = 0, Done = FALSE; !Done; Index++) {
//
// Save the size of the memory and make a Unicode filename SystemMemory00
//
gSystemMemory[Index].Size = _wtoi (MemorySizeStr) * SIZE_1MB;
=> EmulatorPkg/host: fix overflow in Mult

IntelFsp2Pkg/Tools/GenCfgOpt.py
IncLines as empty list for the case when InputHeaderFile is not specified.
=> IntelFsp2Pkg GenCfgOpt.py: Initialize IncLines as empty list

EmulatorPkg/PlatformCI/.azurepipelines/Ubuntu-GCC5.yml, EmulatorPkg/PlatformCI/.azurepipelines/Windows-VS2019.yml, EmulatorPkg/PlatformCI/ReadMe.md, ReadMe.rst
https://bugzilla.tianocore.org/show_bug.cgi?id=2979
Add EmulatorPkg CI builds for SECURE_BOOT_ENABLE=TRUE
for IA32/X64 and DEBUG/RELEASE/NOOPT and update add these
to the CI build status in Readme.rst.
Cc: Divneil Rai Wadhawan <divneil.r.wadhawan@intel.com>
=> EmulatorPkg: Add CI build for SECURE_BOOT_ENABLE

MdeModulePkg/Bus/Pci/XhciDxe/XhciReg.c, MdeModulePkg/Bus/Pci/XhciDxe/XhciSched.c
https://edk2.groups.io/g/devel/message/65543
https://bugzilla.tianocore.org/show_bug.cgi?id=2948
Timeouts in the XhciDxe driver are taking longer than expected due to the timeout loops not accounting for code execution time. As en example, 5 second timeouts have been observed to take around 36 seconds to complete.
Use SetTimer and Create/CheckEvent from Boot Services to determine when timeout occurred. This patch was tested using forced timeouts and print statements with QEmu as well as phycial hardware. The forced timeouts were implemented in code via static variables that guaranteed a timeout the first time the function with the broken timeout was called.
Example:
XhcExecTransfer (
.
.
)
{
.
.
static int do_once = 1;  // test line
.
.
do {
Finished = XhcCheckUrbResult …
=> MdeModulePkg/XhciDxe: Fix Broken Timeouts

ArmVirtPkg/ArmVirt.dsc.inc, ArmVirtPkg/ArmVirtQemuFvMain.fdf.inc, ArmVirtPkg/ArmVirtXen.fdf, OvmfPkg/OvmfPkgIa32.dsc, OvmfPkg/OvmfPkgIa32.fdf, OvmfPkg/OvmfPkgIa32X64.dsc, OvmfPkg/OvmfPkgIa32X64.fdf, OvmfPkg/OvmfPkgX64.dsc, OvmfPkg/OvmfPkgX64.fdf, OvmfPkg/OvmfXen.dsc, OvmfPkg/OvmfXen.fdf
https://bugzilla.tianocore.org/show_bug.cgi?id=2857
https://edk2.groups.io/g/devel/message/63148
http://mid.mail-archive.com/20200722205434.4348-1-vladimir.olovyannikov@broadcom.com
~~~
Hi,
This patchset enables HttpDynamicCommand (Shell command "http") which can be
used on ArmVirt and Ovmf platforms. HttpDynamicCommand needs to be available
in the tree before this patchset can be applied. The patchset needs to
be tested on both platforms.
PATCH v2 patchset addresses comments from Laszlo:
- mention BZ id in commit message;
- remove the extra whitespace in dsc files;
- add the new module to OvmfPkg/ArmVirPkg fdf files.
BZ: https://bugzilla.tianocore.org/show_bug.cgi?id=2857
Thank you,
Vladimir
Vladimir Olovyannikov (2):
ArmVirtPkg: enable HttpDynamiCommand
OvmfPkg: enable …
=> [edk2-devel] [PATCH v2 0/2] Enable HttpDynamicCommand for ArmVirtPkg and OvmfPkg -- push

MdeModulePkg/Universal/HiiDatabaseDxe/ConfigRouting.c
https://edk2.groups.io/g/devel/message/65192
Update function behavior to not modify the incoming string that is
marked as CONST in the prototype.
=> MdeModulePkg/HiiDatabase: Do not modify CONST string

NetworkPkg/NetworkPkg.dsc
Recent change to OpensslLib (b5701a4c7a0fb185e0c5b9db9525939c78664bfd)
causes NetworkPkg build to fail due to lack of RngLib entry in
NetworkPkg's .dsc file.
=> NetworkPkg: Add RngLib entry to .dsc file.

NetworkPkg/HttpDxe/HttpProto.c
BZ #2909,
https://bugzilla.tianocore.org/show_bug.cgi?id=2909
When Http->Configure() is invoked with HttpConfigData set to
NULL to reset the EFI HTTP instance, TLS child instance is
destroyed but HttpInstance->TlsChildHandle is not set to
NULL. After reconfiguring HTTP through Http->Configure()
and sending the HTTP request to HTTPS URL, TLS child
instance is not recreated because
HttpInstance->TlsChildHandle is not NULL.
Cc: Wu Jiaxin <jiaxin.wu@intel.com>
Cc: Fu Siyuan <siyuan.fu@intel.com>
Reviewed-by: Wu Jiaxin <jiaxin.wu@intel.com>
=> NetworkPkg/HttpDxe: TlsChildHandle is not cleared when reset

MdePkg/Include/IndustryStandard/SmBios.h
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2352
SMBIOS 3.4 spec adds new memory device types (DDR5, LPDDR5)
Signed-off-by: Sanyo Wang <sanyo.wang@intel.com>
=> MdePkg: SMBIOS 3.4.0 Update "adding DDR5 definitions".

BaseTools/Conf/build_rule.template
=> BaseTools Build_Rule: Add the missing ASM16_FLAGS for ASM16 source file

MdePkg/Library/BaseLib/AArch64/SetJumpLongJump.S, MdePkg/Library/BaseLib/AArch64/SetJumpLongJump.asm
Correct the memory offsets used in REG_ONE/REG_PAIR macros to
synchronize them with definition of the BASE_LIBRARY_JUMP_BUFFER
structure on AArch64.
The REG_ONE macro declares only a single 64-bit register be
read/written; however, the subsequent offset is 16 bytes larger,
creating an unused memory gap in the middle of the structure and
causing SetJump/LongJump functions to read/write 8 bytes of memory
past the end of the jump buffer struct.
Signed-off-by: Jan Bobek <jbobek@nvidia.com>
=> MdePkg/BaseLib: Fix invalid memory access in AArch64 SetJump/LongJump

ShellPkg/Library/UefiShellDebug1CommandsLib/SmbiosView/QueryTable.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2352
Refer to SMBIOS 3.4 spec, add new memory device type - DDR5
and LPDDR5 support for the shell command "smbiosview".
=> ShellPkg/SmbiosView: Add DDR5 support

MdePkg/Library/BaseMemoryLibSse2/Ia32/SetMem.nasm, MdePkg/Library/BaseMemoryLibSse2/Ia32/SetMem16.nasm, MdePkg/Library/BaseMemoryLibSse2/Ia32/SetMem32.nasm, MdePkg/Library/BaseMemoryLibSse2/Ia32/SetMem64.nasm, MdePkg/Library/BaseMemoryLibSse2/Ia32/ZeroMem.nasm, MdePkg/Library/BaseMemoryLibSse2/X64/SetMem.nasm, MdePkg/Library/BaseMemoryLibSse2/X64/SetMem16.nasm, MdePkg/Library/BaseMemoryLibSse2/X64/SetMem32.nasm, MdePkg/Library/BaseMemoryLibSse2/X64/SetMem64.nasm, MdePkg/Library/BaseMemoryLibSse2/X64/ZeroMem.nasm
The current SSE2 implementation of the ZeroMem(), SetMem(),
SetMem16(), SetMem32 and SetMem64 functions is writing 16 bytes per 16
bytes. It hurts the performances so bad that this is even slower than
a simple 'rep stos' (4% slower) in regular DRAM.
To take full advantages of the 'movntdq' instruction it is better to
"queue" a total of 64 bytes in the write combining buffers.  This
patch implement such a change.  Below is a table where I measured
(with 'rdtsc') the time to write an entire 100MB RAM buffer. These
functions operate almost two times faster.
| Function | Arch | Untouched | 64 bytes | Result |
|----------+------+-----------+----------+--------|
| ZeroMem  | Ia32 |  17765947 |  9136062 | 1.945x |
| ZeroMem  | X64  |  17525170 |  9233391 | 1.898x |
| SetMem   | Ia32 |  17522291 …
=> BaseMemoryLibSse2: Take advantage of write combining buffers

SecurityPkg/Library/SmmTcg2PhysicalPresenceLib/SmmTcg2PhysicalPresenceLib.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2697
Tcg2PhysicalPresenceLibConstructor set the module variable
mIsTcg2PPVerLowerThan_1_3 with incorrect TCG version comparision.
=> SecurityPkg/Tcg2PhysicalPresenceLib: Fix incorrect TCG VER comparision

FmpDevicePkg/FmpDevicePkg.dsc
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=3010
Commit b5701a4 in CryptoPkg introduced a dependency on RngLib.
The FmpDevicePkg build currently fails since it does not specify
a RngLib instance and OpensslLib links against RngLib.
Cc: Wei6 Xu <wei6.xu@intel.com>
Cc: Matthew Carlson <matthewfcarlson@gmail.com>
=> FmpDevicePkg: Add RngLib instance to DSC

IntelFsp2Pkg/Tools/PatchFv.py
Error message:
raise Exception ("'%s' is not a valid directory!" % FvDir)
NameError: name 'FvDir' is not defined
FvDir should be fvDir.
=> IntelFsp2Pkg/Tools: Fix a typo issue

MdeModulePkg/Universal/Disk/PartitionDxe/Partition.c
This reverts commit e0eacd7daa6f2e59de2b35a5dfe8bb4c38821e31.
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3012
The patch to fix LBA size would cause a regression that make the
partition of CD image with media type other than NO_EMULATOR unobserved.
The patch used to fix the CD image's MBR table issue. The CD MBR
table would always be ignored because it would be handled by the
Eltorito partition handler first and never go into the MBR handler.
So directly revert it.
Tested-by: Gary Lin <glin@suse.com>
=> Revert "MdeModulePkg/PartitionDxe: Fix the incorrect LBA size in child..."

CryptoPkg/Library/BaseCryptLib/Pk/CryptAuthenticode.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=1914
AuthenticodeVerify() calls OpenSSLs d2i_PKCS7() API to parse asn encoded
signed authenticode pkcs#7 data. when this successfully returns, a type
check is done by calling PKCS7_type_is_signed() and then
Pkcs7->d.sign->contents->type is used. It is possible to construct an asn1
blob that successfully decodes and have d2i_PKCS7() return a valid pointer
and have PKCS7_type_is_signed() also return success  but have Pkcs7->d.sign
be a NULL pointer.
Looking at how PKCS7_verify() [inside of OpenSSL] implements checking for
pkcs7 structs it does the following:
- call PKCS7_type_is_signed()
- call PKCS7_get_detached()
Looking into how PKCS7_get_detatched() is implemented, it checks to see if
p7->d.sign is NULL or if …
=> CryptoPkg/BaseCryptLib: fix NULL dereference (CVE-2019-14584)

EmbeddedPkg/Library/VirtualRealTimeClockLib/VirtualRealTimeClockLib.c
Addresses BZ https://bugzilla.tianocore.org/show_bug.cgi?id=2380 where
explicit casts are required for 64 to 32 bit assignment.
We can apply a straight cast for Time->Nanosecond since we already checked
for overflow.
On the other hand, we may have a frequency that is greater than UINT32_MAX
for Capabilities->Resolution. But using the frequency for the resolution
is the wrong approach anyway, since we can't actually vouch for the actual
resolution of the virtual library. Instead, play it safe by defaulting to
1 Hz, which is what a standard PC-AT CMOS RTC device would use.
Signed-off-by: Pete Batard <pete@akeo.ie>
=> EmbeddedPkg/VirtualRealTimeClockLib: Explicit cast to UINT32

BaseTools/Source/C/Common/PcdValueCommon.h
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3001
When the 64-bit version of VS compiler is used, the generated
PcdValueInit tool will be failed to compile.
This patch is going to fix that issue.
=> BaseTools: Fix PcdValueInit tool build issue with VS compiler x64

MdeModulePkg/Bus/Pci/XhciDxe/XhciSched.c
Patch: https://edk2.groups.io/g/devel/message/66550
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3007
Currently UsbDevContext is not cleaned up if USB slot initialization is
failed, the wrong context data will affect next USB devices and
the USB devices can not be enumerated.
Need to disable slot if USB slot initialization is failed.
Below test cases are passed on UpXtreme:
a. USB 3.0 thumb drives can be recognized in UEFI shell
b. SUT can boot to Puppylinux  from USB3.0 mass storage,
the storage can be recognized in linux
c. Plug in a USB  keyboard (hot plug) and enumeration is OK
in UEFI shell and linux
d. Plug in a USB mouse(hot plug) and enumeration is OK in linux. …
=> MdeModulePkg/XhciDxe: Error handle for USB slot initialization failure

BaseTools/Source/Python/Ecc/MetaDataParser.py
BZ: https://bugzilla.tianocore.org/show_bug.cgi?id=3011
MetaFile Copyright support below format:
=> BaseTools/Ecc: Fix ECC check MetaFile Copyright information issue

MdeModulePkg/Core/Dxe/FwVol/FwVolRead.c
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=3028
The FirmwareVolume2Protocol->GetNextFile() produced by DXE Core can be used
to search for a file based on the value of *FileType input. However, this
service will always return EFI_NOT_FOUND if the input FileType is set to
EFI_FV_FILETYPE_MM_STANDALONE or EFI_FV_FILETYPE_MM_CORE_STANDALONE, Which
means user can't use this service to search any standalone MM image in that
FV.
This patch update the FirmwareVolume2Protocol->GetNextFile() service to
support searching standalone MM module.
=> MdeModulePkg/Core: Support standalone MM in FV2 protocol GetNextFile().

MdeModulePkg/Bus/Pci/XhciDxe/XhciSched.c, MdeModulePkg/Bus/Pci/XhciDxe/XhciSched.h
Patch sent at: https://edk2.groups.io/g/devel/message/66697
With some super-speed USB mass storage devices it has been observed
that a USB transaction error may occur when attempting the set the
device address during enumeration.
According the the xHCI specification (section 4.6.5) ...
"A USB Transaction ErrorCompletion Code for an Address Device Command
may be due to a Stall response from a device. Software should issue a
Disable Slot Commandfor the Device Slot then an Enable Slot Command
to recover from this error."
To fix this, retry the device slot initialization if it fails due to a
device error.
Change was verified using a superspeed mass storage device that was
occasionally failing to enumerate in UEFI. With this change this failure
to enumerate was resolved. This failure was also …
=> MdeModulePkg/XhciDxe: Retry device slot init on failure

RedfishPkg/Include/Protocol/RedfishDiscover.h, RedfishPkg/RedfishPkg.dec
Header file of EFI Redfish Discover Protocol for UEFI spec
v2.8 Section 31.1.
=> RedfishPkg/Include: EFI Redfish Discover Protocol header file

BaseTools/Source/Python/GenFds/GenFds.py
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3009
Update the FV Space Information to display decimal and Hex
FV Space Information
before format:
SECFV [13%Full] 212992 total, 28400 used, 184592 free
Updated format:
SECFV [13%Full] 212992 (0x34000) total, 28400 (0x6ef0) used,
184592 (0x2d110) free
=> BaseTools: Update the FV Space Information to display decimal and Hex

BaseTools/Source/Python/GenFds/Section.py
When generating compressed section, the build tool rely on the
build intermediate files, which were generated in last build, to
get the file list. This method will cause the incremental build to
generate incorrect build result. To reproduce this incremental build
error, you can do:
1. build Ovmf
2. change the module OvmfPkg\AcpiTables a source file Facp.aslc
name from Facp.aslc to Facpxxx.aslc.
3. change the Facp.aslc file name in [sources] section of AcpiTables.inf
4. incremental build Ovmf
you will see the in AcpiTables module Makefile, the corresponding
Facp.acpi file is not changed.
This patch is to make the build always get file list from the INF. …
=> BaseTools: Remove the dependency on the build intermediate file

MdeModulePkg/Core/Dxe/Gcd/Gcd.c
CoreInitializeMemoryServices was not checking for any existing memory
allocation created in the HOB producer phase. If there are memory
allocations outside of the region covered by the HOB List then Gcd could
select that region for memory which can result in the memory allocation
to not be handled and memory overwrites.
Regression-tested-by: Laszlo Ersek <lersek@redhat.com>
=> MdeModulePkg/Gcd: Check memory allocation when initializing memory

BaseTools/Source/Python/AutoGen/DataPipe.py, BaseTools/Source/Python/AutoGen/ModuleAutoGen.py, BaseTools/Source/Python/AutoGen/ModuleAutoGenHelper.py, BaseTools/Source/Python/AutoGen/PlatformAutoGen.py, BaseTools/Source/Python/Workspace/BuildClassObject.py, BaseTools/Source/Python/Workspace/DscBuildData.py, BaseTools/Source/Python/build/BuildReport.py
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2648
This patch is to enable the Module scoped Structure Pcd usage.
User can set structure pcd field value in module scope. For example,
under the [components] section of a dsc file, user can override some
field value for a specific module.
Package/Module.inf{
<PcdsFixedAtBuild>
gUefiTokenSpaceGuid.StructurePcdModule.FieldName | 5
}
Tested-by: Liming Gao <gaoliming@byosoft.com.cn>
=> BaseTools: Enable Module Scope Structure Pcd

ShellPkg/Library/UefiShellDebug1CommandsLib/Edit/FileBuffer.c
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=2998
In the function FileBufferCutLine(),set the CutLine pointer to NULL,
The function header specifies that the pointer is valid on a successful
or failed return code.
Signed-off-by: Enze Zhu <zhuenze@byosoft.com.cn>
=> ShellPkg:Fix bug in FileBuffer.c

BaseTools/Source/C/Makefiles/NmakeSubdirs.py
On windows system, when use command chcp displays the number of the
active console code page, if the active console code is 936, run
make cleanall in the BaseTools will hang.
Issue reproduce step:
chcp 936
edksetup.bat VS2015
cd BaseTools
nmake cleanall
=> BaseTools: Fix BaseTools nmake cleanall hang issue

MdeModulePkg/Core/Dxe/DxeMain/DxeMain.c
msgid `<20201103161557.30621-1-lersek@redhat.com>`
https://www.redhat.com/archives/edk2-devel-archive/2020-November/msg00091.html
https://edk2.groups.io/g/devel/message/66932
https://edk2.groups.io/g/devel/message/66937
https://edk2.groups.io/g/devel/message/67019
~~~
CoreInitializeMemoryServices() logs "BaseAddress" and "Length" with
DEBUG() before DxeMain() calls ProcessLibraryConstructorList()
explicitly. (Library construction is not an automatic part of the DXE
Core entry point.)
So those DEBUG()s in CoreInitializeMemoryServices() are issued against
an un-constructed DebugLib, and also against a -- possibly underlying --
un-constructed SerialPortLib.
Some DebugLib instances can deal with this (see for example commit
91a5b1365075, "OvmfPkg/PlatformDebugLibIoPort: fix port detection for …
=> [edk2-devel] [PATCH] MdeModulePkg/Core/Dxe: log memory base and length, after lib ctors again -- push

BaseTools/Source/Python/Trim/Trim.py
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=2972
When using incremental build to delete an included xxx.asi file from
the ASL file, the xxx.asl.trim.deps file generated by previous build
process will not be deleted from the OUTPUT directory, which caused
the dependency file still include the xxx.asl.trim.deps file.
If the include file is deleted and DEPs is empty.
Signed-off-by: Mingyue Liang <mingyuex.liang@intel.com>
=> BaseTools: Incremental build issue for included ASI file's deletion.

BaseTools/Source/C/GenFv/GenFvInternalLib.c, BaseTools/Source/Python/build/BuildReport.py
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2977
For a source-level BIOS debugger the .map files are quite useful with one major shortcoming: the debugger cannot know, solely from the .map file, the format (PE/COFF vs. TE) of the image included in the final BIOS ROM
Yunhua Feng (2):
BaseTools: Add image type into generate map file
BaseTools: update report map file format
BaseTools/Source/C/GenFv/GenFvInternalLib.c  | 7 ++++++-  BaseTools/Source/Python/build/BuildReport.py | 2 +-
2 files changed, 7 insertions(+), 2 deletions(-)
=> BaseTools: Add image type into generate map file

BaseTools/Source/Python/AutoGen/GenMake.py, BaseTools/Source/Python/AutoGen/IncludesAutoGen.py
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2528
Currently, CL command contains multiple C files will be compiled,
and that caused command line too long, which may trigger build error.
In order to solve this issue, the following rules is used in this scene:
If the number of C files is greater than one, a txt file will be used
to record these C files, and replaces the corresponding content in
command line with the file name.
Else (only one C file listed in the command line), the length of the
whole CL command line will determine whether use a file to record. If
the length exceeds the limited max length, use the recording file; else
C file name directly listed in the command line
Signed-off-by: Mingyue Liang <mingyuex.liang@intel.com>
Cc: Liming …
=> BaseTools: Limit command line length.

MdePkg/Include/Register/Amd/Ghcb.h, OvmfPkg/Library/VmgExitLib/VmgExitLib.c, OvmfPkg/Library/VmgExitLib/VmgExitVcHandler.c, OvmfPkg/QemuFlashFvbServicesRuntimeDxe/QemuFlash.c, OvmfPkg/QemuFlashFvbServicesRuntimeDxe/QemuFlashDxe.c, UefiCpuPkg/Include/Library/VmgExitLib.h, UefiCpuPkg/Library/MpInitLib/DxeMpLib.c, UefiCpuPkg/Library/MpInitLib/MpLib.c, UefiCpuPkg/Library/MpInitLib/X64/MpFuncs.nasm, UefiCpuPkg/Library/VmgExitLibNull/VmgExitLibNull.c
https://bugzilla.tianocore.org/show_bug.cgi?id=3008
https://edk2.groups.io/g/devel/message/67099
http://mid.mail-archive.com/cover.1603981082.git.thomas.lendacky@amd.com
https://www.redhat.com/archives/edk2-devel-archive/2020-November/msg00258.html
~~~
From: Tom Lendacky <thomas.lendacky@amd.com>
This patch series provides some fixes, updates and cleanup to the SEV-ES
guest support:
- Update the calculation of the qword offset of fields within the GHCB
by removing the hardcoding of the offsets and using the OFFSET_OF ()
and sizeof () functions to calculate the values. Remove unused values
and add values that will be used in later patches.
- Set the SwExitCode, SwExitInfo1, SwExitInfo2 and SwScratch valid bits
in the GHCB ValidBitmap area when these fields are for a VMGEXIT. This
is done …
=> [edk2-devel] [PATCH v4 00/11] SEV-ES guest support fixes and cleanup -- push

MdeModulePkg/Bus/Ata/AtaAtapiPassThru/AhciMode.c, MdeModulePkg/Bus/Ata/AtaAtapiPassThru/AhciMode.h
**BZ:**
https://bugzilla.tianocore.org/show_bug.cgi?id=3024
https://bugzilla.tianocore.org/show_bug.cgi?id=3025
https://bugzilla.tianocore.org/show_bug.cgi?id=3026
**Patch at mailing list:**
https://edk2.groups.io/g/devel/message/67038
https://edk2.groups.io/g/devel/message/67039
https://edk2.groups.io/g/devel/message/67040
https://edk2.groups.io/g/devel/message/67041
**Cover letter:**
To increase boot stability when booting from SATA drives SATA driver should implement the AHCI spec defined port error recovery. This will allow the driver to handle random fails on SATA link.
Performed tests on 2 setups. One with AHCI controller booting OS successfully without error recovery(control setup) and other which fails 1 in 5 times(fail setup).
Tests performed:
1. Booted control setup to OS …
=> MdeModulePkg/AtaAtapiPassThru: Add SATA error recovery

RedfishPkg/RedfishPkg.dec
This PCD is the UEFI device path which is used as the Redfish
host interface.
Signed-off-by: Ting Ye <ting.ye@intel.com>
Signed-off-by: Fan Wang <fan.wang@intel.com>
=> RedfishPkg: Add PCD definition to RedfishPkg

RedfishPkg/Redfish.dsc.inc, RedfishPkg/Redfish.fdf.inc, RedfishPkg/RedfishComponents.dsc.inc, RedfishPkg/RedfishDefines.dsc.inc, RedfishPkg/RedfishLibs.dsc.inc
Provide the DSC/FDF include files of edk2 Redfish related
modules and definitions which can be included in platform's
DSC/FDF.
=> RedfishPkg: DSC and FDF include files for enabling EFI Redfish support

RedfishPkg/RedfishPkg.ci.yaml, RedfishPkg/RedfishPkg.dsc
- Include Redfish.dsc.inc in RedfishPkg.dsc. which
consolidates the necessary components in Redfish.dsc.inc.
- Remove unnecessary library instances from RedfishPkg.dsc.
- Add build option in RedfishPkg.yaml.
=> RedfishPkg: Use DSC include file

OvmfPkg/Bhyve/BhyveX64.dsc, OvmfPkg/Bhyve/BhyveX64.fdf, OvmfPkg/Bhyve/ResetVector/Ia32/PageTables64.asm, OvmfPkg/Bhyve/ResetVector/ResetVector.inf, OvmfPkg/Bhyve/ResetVector/ResetVector.nasmb
https://www.redhat.com/archives/edk2-devel-archive/2020-November/msg00514.html
https://edk2.groups.io/g/devel/message/67355
msgid <20201112053153.22038-1-rebecca@bsdio.com>
~~~
Fix Bhyve following breaking changes in OvmfPkg.
Follows suggestions from Laszlo in the v1 patch set.
I also changed the INF version in ResetVector.inf to 1.29.
Rebecca Cran (2):
OvmfPkg/Bhyve: detach ResetVector from before the SEV-ES changes
OvmfPkg/Bhyve: fix build breakage after SEV-ES changes
OvmfPkg/Bhyve/BhyveX64.dsc                    |   3 +-
OvmfPkg/Bhyve/BhyveX64.fdf                    |   2 +-
OvmfPkg/Bhyve/ResetVector/ResetVector.inf     |  38 +++++
.../Bhyve/ResetVector/Ia32/PageTables64.asm   | 149 ++++++++++++++++++
OvmfPkg/Bhyve/ResetVector/ResetVector.nasmb   |  68 ++++++++
5 files changed, 258 …
=> [edk2-devel] [PATCH v2 0/2] OvmfPkg/Bhyve: Fix Bhyve build following breaking changes in OvmfPkg -- push

IntelFsp2Pkg/Tools/SplitFspBin.py
Current FSP rebasing script SplitFspBin.py has support for both
PE32 and PE32+ image formats. However, while updating the ImageBase
field in the image header, it always assumed the ImageBase field is
32bit long. Since PE32+ image format defined ImageBase as 64bit,
the current script will only update the lower 32bit value and leave
the upper 32bit untouched. It does not work well for PE32+ image
that requires update in the upper 32bit ImageBase field. The
expected behavior is to update the full 64bit field. This patch
implemented this fix.
Signed-off-by: Maurice Ma <maurice.ma@intel.com>
Reviewed-by: Star Zeng …
=> IntelFsp2Pkg: Fix FSP binary rebasing issue for PE32+ image

MdePkg/Include/IndustryStandard/Cxl11.h
https://bugzilla.tianocore.org/show_bug.cgi?id=3074
* Fix offset of LinkLayerControlAndStatus in the
CXL_1_1_LINK_CAPABILITY_STRUCTURE structure
* Fix offset of LinkLayerAckTimerControl in the
CXL_1_1_LINK_CAPABILITY_STRUCTURE structure
* Fix offset of LinkLayerDefeature in
the CXL_1_1_LINK_CAPABILITY_STRUCTURE structure
* Add CXL_11_SIZE_ASSERT() macro to verify the size of
a register layout structure at compile time and use
it to verify the sizes of the CXL 1.1 register structures.
* Add CXL_11_OFFSET_ASSERT() macro to verify the offset of
fields in a register layout structure at compiler time and
use it to verify the offset of fields in CXL 1.1
register structures.
Cc: Ashraf Javeed …
=> MdePkg/IndustryStandard: Fix CXL 1.1 structure layout issues

UefiCpuPkg/PiSmmCpuDxeSmm/Ia32/PageTbl.c, UefiCpuPkg/PiSmmCpuDxeSmm/PiSmmCpuDxeSmm.h, UefiCpuPkg/PiSmmCpuDxeSmm/SmmCpuMemoryManagement.c, UefiCpuPkg/PiSmmCpuDxeSmm/X64/PageTbl.c
When trying to get page table base, if mInternalCr3 is zero, it will use  the page table from CR3, and reflect the page table depth by CR4 LA57 bit.
If mInternalCr3 is non zero, it will use the page table from mInternalCr3  and reflect the page table depth of mInternalCr3 at same time.
In the case of X64, we use m5LevelPagingNeeded to reflect the depth of  the page table. And in the case of IA32, it will not the page table depth  information.
This patch is a bug fix when enable CET feature with 5 level paging.
The SMM page tables are allocated / initialized in PiCpuSmmEntry().
When CET is enabled, PiCpuSmmEntry() must further modify the attribute of  shadow stack pages. This page table is not set to CR3 in PiCpuSmmEntry().
So the page table base address is set to mInternalCr3 for modifty …
=> UefiCpuPkg/PiSmmCpuDxeSmm: Reflect page table depth with page table address

BaseTools/Source/Python/AutoGen/IncludesAutoGen.py
This problem is generated by solving bz2972's
patch, and the commit ID is
0af7f8e6a9253960ba820cd6ddfd8c36543d30cb.
This is a problem when updating the DEPs file.
The code does not consider that there is only
one line of content in the file, so the filter
condition is added to prevent the index from
exceeding the range.
Signed-off-by: Mingyue Liang <mingyuex.liang@intel.com>
=> BaseTools: Resolve index out of range errors.

IntelFsp2Pkg/Tools/PatchFv.py
The commit 76e8aac158b0717fa27f12e4d008f79161ddb050 changed Fv map format.
It added the image type to better support source level debug. But it broke
the function of PatchFv.py because PatchFv.py also consume Fv map file.
This patch is to update PatchFv.py to make it work again.
Cc: Yunhua Feng <fengyunhua@byosoft.com.cn>
=> IntelFsp2Pkg/Tools: Fixed PatchFv.py to parse new Fv map file format

SecurityPkg/Include/Library/RpmcLib.h, SecurityPkg/Library/RpmcLibNull/RpmcLibNull.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2594
The re-design requires multiple RPMC counter usages.
The consumer will be capable of selecting amongst multiple counters.
Signed-off-by: Nishant C Mistry <nishant.c.mistry@intel.com>
=> SecurityPkg: Add RPMC Index to the RpmcLib

MdeModulePkg/Core/Dxe/DxeMain.inf, MdeModulePkg/Core/Dxe/SectionExtraction/CoreSectionExtraction.c, MdeModulePkg/MdeModulePkg.dec, MdeModulePkg/MdeModulePkg.uni
msgid <20201119105340.16225-1-lersek@redhat.com>
https://edk2.groups.io/g/devel/message/67707
https://www.redhat.com/archives/edk2-devel-archive/2020-November/msg00865.html
~~~
Branch: tianocore_1743_v2_resend
Ref:    https://bugzilla.tianocore.org/show_bug.cgi?id=1743
"RESEND" because I'm publicly posting the patches from
<https://bugzilla.tianocore.org/show_bug.cgi?id=1743#c19>.
The Reviewed-by tags on the patches originate from
<https://bugzilla.tianocore.org/show_bug.cgi?id=1743#c20> and
<https://bugzilla.tianocore.org/show_bug.cgi?id=1743#c22>.
Retested with Liming's reproducer; see
<https://bugzilla.tianocore.org/show_bug.cgi?id=1743#c16> and
<https://bugzilla.tianocore.org/show_bug.cgi?id=1743#c18>.
This series targets edk2-stable202011. I …
=> [edk2-devel] [PATCH v2 RESEND 0/2] security fix: unlimited FV recursion, round 2 (DXE Core) -- push

MdeModulePkg/Library/LzmaCustomDecompressLib/LzmaDecompress.c, MdeModulePkg/Library/LzmaCustomDecompressLib/LzmaDecompressLibInternal.h
msgid <20201119115034.12897-1-lersek@redhat.com>
https://edk2.groups.io/g/devel/message/67708
https://www.redhat.com/archives/edk2-devel-archive/2020-November/msg00866.html
~~~
Branch: tianocore_1816_resend
Ref:    https://bugzilla.tianocore.org/show_bug.cgi?id=1816
"RESEND" because I'm publicly posting the patch from
<https://bugzilla.tianocore.org/show_bug.cgi?id=1816#c9>.
The Reviewed-by tags on the patch originate from
<https://bugzilla.tianocore.org/show_bug.cgi?id=1816#c12> and
<https://bugzilla.tianocore.org/show_bug.cgi?id=1816#c17>.
Repeated the simple regression test at
<https://bugzilla.tianocore.org/show_bug.cgi?id=1816#c10>.
This series targets edk2-stable202011. I plan to merge it later this
week, based on Liming's R-b.
Liming, …
=> [edk2-devel] [PATCH RESEND 0/1] security fix: possible heap corruption with LzmaUefiDecompressGetInfo -- push

SecurityPkg/Include/Library/RpmcLib.h, SecurityPkg/Library/RpmcLibNull/RpmcLibNull.c
This reverts commit 6c8dd15c4ae42501438a525ec41299f365f223cb.
Based on the discussion https://edk2.groups.io/g/devel/message/67764,
this change is regarded as the feature request. But, it doesn't pass
reviewed before 202011 stable tag soft feature freeze. So, it should
not be merged into 202011 stable tag.
Cc: Nishant C Mistry <nishant.c.mistry@intel.com>
Acked-by: Jiewen Yao <Jiewen.yao@intel.com>
=> Revert "SecurityPkg: Add RPMC Index to the RpmcLib"

CryptoPkg/Library/BaseCryptLib/Pk/CryptPkcs7VerifyEku.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2459
*The issue is in VerifyEKUsInPkcs7Signature routine of
CryptoPkg/Library/BaseCryptLib/Pk/CryptPkcs7VerifyEku.c:
At the "Exit" portion of this routine, this function uses X509_free to free
SignerCert instance and PKCS7_free function to free Pkcs7. But SignerCert
is part of Pkcs7 instance, thus PKCS7_free will release the memory of
SignerCert for a second time with existed routine, which will cause page
fault if use-after-free guard is enabled.
The patch fix is to free Pkcs7 instance only using PKCS7_free.
The v2 patch includes changes from updated git configuration and reworded
patch to include review tag.
Patch v1 branch: https://github.com/kuqin12/edk2/tree/buffer_double_free_v1
Patch v2 branch: …
=> CryptoPkg: BaseCryptLib: Fix buffer double free in CryptPkcs7VerifyEku

OvmfPkg/XenPvBlkDxe/BlockFront.c
msgid <1606183592-81879-1-git-send-email-xiewenyi2@huawei.com>
https://edk2.groups.io/g/devel/message/67862
https://www.redhat.com/archives/edk2-devel-archive/2020-November/msg01022.html
~~~
Main Changes since v1 :
Returning EFI_OUT_OF_RESOURCES if pool allocting fail.
Wenyi Xie (1):
OvmfPkg/XenPvBlkDxe: add return value if allocting fail
OvmfPkg/XenPvBlkDxe/BlockFront.c | 4 ++++
1 file changed, 4 insertions(+)
~~~
=> [edk2-devel] [PATCH v2 0/1] OvmfPkg/XenPvBlkDxe: add return value if allocting fail -- push

OvmfPkg/Bhyve/AcpiPlatformDxe/AcpiPlatform.c, OvmfPkg/Bhyve/AcpiPlatformDxe/AcpiPlatform.h, OvmfPkg/Bhyve/AcpiPlatformDxe/AcpiPlatformDxe.inf, OvmfPkg/Bhyve/AcpiPlatformDxe/Bhyve.c, OvmfPkg/Bhyve/AcpiTables/AcpiTables.inf, OvmfPkg/Bhyve/AcpiTables/Platform.h, OvmfPkg/Bhyve/BhyveRfbDxe/BhyveRfbDxe.inf, OvmfPkg/Bhyve/BhyveRfbDxe/Gop.h, OvmfPkg/Bhyve/BhyveX64.dsc, OvmfPkg/Bhyve/PlatformPei/Cmos.h, OvmfPkg/Bhyve/PlatformPei/Fv.c, OvmfPkg/Bhyve/PlatformPei/Platform.c, OvmfPkg/Bhyve/PlatformPei/PlatformPei.inf, OvmfPkg/Bhyve/SmbiosPlatformDxe/SmbiosPlatformDxe.h, OvmfPkg/Bhyve/SmbiosPlatformDxe/SmbiosPlatformDxe.inf, OvmfPkg/Include/Library/BhyveFwCtlLib.h, OvmfPkg/Library/BhyveFwCtlLib/BhyveFwCtlLib.c, OvmfPkg/Library/BhyveFwCtlLib/BhyveFwCtlLib.inf
msgid <20201130053412.2-1-rebecca@bsdio.com>
https://edk2.groups.io/g/devel/message/68063
https://www.redhat.com/archives/edk2-devel-archive/2020-November/msg01223.html
~~~
There are several problems with the code style and formatting in Bhyve related files.
These include using structs without typedef'ing them, wrong indentation (e.g. three
spaces instead of two), and UINTN/UINT32 mix-ups which cause build errors when
using VS 2019.
I've taken this opportunity to also change the INF and DSC versions to decimal and
bump the version to 1.29 for INF files and 1.30 for the DSC.
Rebecca Cran (5):
OvmfPkg: Fix BhyveFwCtlLib build with VS2019
OvmfPkg: Improve code style/formatting in BhyveFwCtlLib.c
OvmfPkg: Fix style of BhyveFwCtlLib.inf
OvmfPkg: Improve style and formatting in BhyveFwCtlLib.h …
=> [edk2-devel] [PATCH 0/5] OvmfPkg: Fix Bhyve code formatting and style problems -- push

NetworkPkg/Network.fdf.inc, NetworkPkg/NetworkComponents.dsc.inc, NetworkPkg/NetworkDefines.dsc.inc, NetworkPkg/NetworkPkg.ci.yaml
BZ: https://bugzilla.tianocore.org/show_bug.cgi?id=2917
Add NETWORK_HTTP_ENABLE macro and separate HttpDxe
and HttpUtilitiesDxe drivers from
HTTP_NETWORK_HTTP_BOOT_ENABLE macro.
Current NETWORK_HTTP_BOOT_ENABLE macro is defined to enable HTTP
boot feature in POST, this macro is not only enabling HTTP Boot
related modules but also enabling other generic HTTP modules
such as HttpDxe, HttpUtilitiesDxe and DnsDxe.
These HTTP base drivers would not be only used by HTTP boot
when we introduce the use case of Redfish implementation over
HTTP to edk2.
We should have a dedicate macro to enable generic HTTP functions
on Network stack and additionally provide NETWORK_HTTP_BOOT_ENABLE
for HTTP boot functionality for the use case that platform doesn't
require HTTP boot.
Signed-off-by: Abner Chang …
=> NetworkPkg: Add NETWORK_HTTP_ENABLE macro

UefiCpuPkg/Include/AcpiCpuData.h, UefiCpuPkg/Library/RegisterCpuFeaturesLib/CpuFeaturesInitialize.c, UefiCpuPkg/PiSmmCpuDxeSmm/CpuS3.c
Today's code assumes every core contains the same number of threads.
It's not always TRUE for certain model.
Such assumption causes system hang when thread count per core
is different and there is core or package dependency between CPU
features (using CPU_FEATURE_CORE_BEFORE/AFTER,
CPU_FEATURE_PACKAGE_BEFORE/AFTER).
The change removes such assumption by calculating the actual thread
count per package and per core.
Cc: Yun Lou <yun.lou@intel.com>
=> UefiCpuPkg/Feature: Support different thread count per core

MdeModulePkg/Core/Pei/Dispatcher/Dispatcher.c, MdeModulePkg/Core/Pei/PeiMain.h, MdeModulePkg/Core/Pei/Ppi/Ppi.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3098
XCODE5 toolchain in NOOPT mode generates memcpy when trying
to copy PEI_CORE_FV_HANDLE structure. This breaks OVMF
compilation with XCODE5.
CC: Jian J Wang <jian.j.wang@intel.com>
CC: Hao A Wu <hao.a.wu@intel.com>
CC: Jordan Justen <jordan.l.justen@intel.com>
CC: Laszlo Ersek <lersek@redhat.com>
CC: Ard Biesheuvel <ard.biesheuvel@arm.com>
Signed-off-by: Vitaly Cheptsov <cheptsov@ispras.ru>
=> MdeModulePkg: Fix undefined reference to memcpy with XCODE5

MdeModulePkg/Library/FileExplorerLib/FileExplorer.c
If "Info" is a valid pointer to an EFI_FILE_SYSTEM_VOLUME_LABEL
structure, then "Info->VolumeLabel" denotes a valid array object.
When the "Info->VolumeLabel" expression is evaluated, as seen in
the LibFindFileSystem(), it is implicitly converted to
(&Info->VolumeLabel[0]). Because the object described by the
expression (Info->VolumeLabel[0]) is a valid CHAR16 object, its
address can never compare equal to NULL. Therefore, the condition
(Info->VolumeLabel == NULL) will always evaluate to FALSE.
Substitute the constant FALSE into the "if" statement, and
simplify the resultant code (eliminate the dead branch).
Signed-off-by: Wenyi Xie …
=> MdeModulePkg/FileExplorerLib: remove redundant null pointer check

ArmPkg/Library/ArmDisassemblerLib/ArmDisassembler.c
As shift = (OpCode >> 5) & 0x3, shift will never be larger than 0x3,
so the comparison between shift and 0x12 will always be false. The right
shift type of ASR is 0x2.
=> ArmPkg/ArmDisassemblerLib: fix incorrect comparison

UefiCpuPkg/CpuDxe/X64/CpuAsm.nasm
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3084
When DXE drivers are dispatched above 4GB memory and
the system is already in 64bit mode, the address
setCodeSelectorLongJump in stack will be override
by parameter. so change to use 64bit address and
jump to qword address.
=> UefiCpuPkg/CpuDxe: Fix boot error

IntelFsp2Pkg/Tools/GenCfgOpt.py
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3107
Current script only compares main DSC and output file datetime
to determine if re-generation required or not.
When UPD defined in sub DSC and was modified current script cannot
detect and will not re-generate output files which caused incremental
build issue.
Since UPD can be defined in any sub DSC the script has been updated
to compare all DSC datetime with output files to determine re-generation
is needed or not.
Reviewed-by: Star Zeng …
=> IntelFsp2Pkg/GenCfgOpt.py: Incremental build with UPD in sub DSC.

MdePkg/Include/IndustryStandard/SmBios.h, ShellPkg/Library/UefiShellDebug1CommandsLib/SmbiosView/PrintInfo.c
Fix typos in MdePkg/Include/IndustryStandard/SmBios.h and make
corresponding changes to the ShellPkg smbiosview command.
Testing:
Built OvmfPkgX64, OvmfPkgIa32, OvmfPkgIa32X64 for DEBUG, RELEASE, NOOPT
Built edk2-platforms RPi4, SbsaQemu for DEBUG, RELEASE, NOOPT
Built edk2-platforms Armada80x0McBin for RELEASE
Built edk2-platforms Intel UpXtreme, GalagoPro3, KabylakeRvp3
Ran stuart_ci_build with X64,AARCH64,RISCV64,IA32 for NO-TARGET,NOOPT,RELEASE,DEBUG
Ran OVMF X64 and verified smbiosview runs correctly.
=> MdePkg,ShellPkg: Fix typos in IndustryStandard/SmBios.h

RedfishPkg/Redfish.fdf.inc, RedfishPkg/RedfishComponents.dsc.inc, RedfishPkg/RedfishPkg.dsc, RedfishPkg/RedfishRestExDxe/ComponentName.c, RedfishPkg/RedfishRestExDxe/RedfishRestExDriver.c, RedfishPkg/RedfishRestExDxe/RedfishRestExDriver.h, RedfishPkg/RedfishRestExDxe/RedfishRestExDxe.inf, RedfishPkg/RedfishRestExDxe/RedfishRestExDxe.uni, RedfishPkg/RedfishRestExDxe/RedfishRestExDxeExtra.uni, RedfishPkg/RedfishRestExDxe/RedfishRestExImpl.c, RedfishPkg/RedfishRestExDxe/RedfishRestExInternal.h, RedfishPkg/RedfishRestExDxe/RedfishRestExProtocol.c
BZ#: 2908
https://bugzilla.tianocore.org/show_bug.cgi?id=2908
Implementation of EFI EX Protocol according to UEFI spec
2.8 Section 29.7.2 EFI REST EX Protocol.
This is the network stack based EFI REST EX protocol instance.
Signed-off-by: Fan Wang <fan.wang@intel.com>
Signed-off-by: Ting Ye <ting.ye@intel.com>
=> RedfishPkg/RedfishRestExDxe: Implementation of EFI REST EX Protocol

ShellPkg/Library/UefiShellAcpiViewCommandLib/AcpiParser.c, ShellPkg/Library/UefiShellAcpiViewCommandLib/AcpiParser.h, ShellPkg/Library/UefiShellAcpiViewCommandLib/AcpiTableParser.h, ShellPkg/Library/UefiShellAcpiViewCommandLib/Parsers/Pcct/PcctParser.c, ShellPkg/Library/UefiShellAcpiViewCommandLib/Parsers/Pcct/PcctParser.h, ShellPkg/Library/UefiShellAcpiViewCommandLib/UefiShellAcpiViewCommandLib.c, ShellPkg/Library/UefiShellAcpiViewCommandLib/UefiShellAcpiViewCommandLib.inf
Ref: https://edk2.groups.io/g/devel/topic/77055380#66556
This patch series:
- Fixes an issue wherein the field validation is not
invoked when a print formatter is present.
- Addresses the feedback for v1 patch for PCCT parser.
Signed-off-by: Marc Moisson-Franckhauser <marc.moisson-franckhauser@arm.com>
=> ShellPkg/Acpiview: Add support for PCCT parser

MdeModulePkg/Universal/RegularExpressionDxe/OnigurumaUefiPort.c
Ref: https://bugzilla.tianocore.org/show_bug.cgi?id=3085
Coding error in converting memset call to SetMem - Length and Value
is not swapped on calling SetMem
Signed-off-by: Baraneedharan Anbazhagan <anbazhagan@hp.com>
=> MdeModulePkg: Fix SetMem parameter in OnigurumaUefiPort

UefiCpuPkg/Library/RegisterCpuFeaturesLib/CpuFeaturesInitialize.c
The required buffer size for InitOrder will be 96K when NumberOfCpus=1024.
sizeof (CPU_FEATURES_INIT_ORDER) = 96
NumberOfCpus = 1024 = 1K
sizeof (CPU_FEATURES_INIT_ORDER) * NumberOfCpus = 96K
AllocateZeroPool() will call to PeiServicesAllocatePool() which will use
EFI_HOB_MEMORY_POOL to management memory pool.
EFI_HOB_MEMORY_POOL.Header.HobLength is UINT16 type, so there is no way
for AllocateZeroPool() to allocate > 64K memory.
So AllocateZeroPool() could not be used anymore for the case above or
even bigger required buffer size.
This patch updates the code to use AllocatePages() instead of
AllocateZeroPool() to allocate buffer for InitOrder.
Signed-off-by: Star Zeng <star.zeng@intel.com>
Cc: Eric Dong …
=> UefiCpuPkg RegisterCpuFeaturesLib: Use AllocatePages() for InitOrder

OvmfPkg/OvmfPkg.ci.yaml
https://edk2.groups.io/g/devel/message/68670
https://www.redhat.com/archives/edk2-devel-archive/2020-December/msg00669.html
~~~
From: Sean Brogan <sean.brogan@microsoft.com>
---
OvmfPkg/OvmfPkg.ci.yaml | 3 ++-
1 file changed, 2 insertions(+), 1 deletion(-)
~~~
=> [edk2-devel] [PATCH v1 1/1] OvmfPkg: Disable EccCheck CI until EccCheck issues are fixed -- push

.azurepipelines/templates/platform-build-run-steps.yml, .azurepipelines/templates/pr-gate-steps.yml
Use git config insteadOf feature to use an alternate
cmocka repo from github when running CI.
=> .azurepipelines: Use alternate cmocka repo

MdeModulePkg/Test/MdeModulePkgHostTest.dsc, MdeModulePkg/Universal/Variable/RuntimeDxe/RuntimeDxeUnitTest/VariableLockRequestToLockUnitTest.c, MdeModulePkg/Universal/Variable/RuntimeDxe/RuntimeDxeUnitTest/VariableLockRequestToLockUnitTest.inf, MdeModulePkg/Universal/Variable/RuntimeDxe/VariableLockRequestToLock.c
New in V4
==========
* Fix spelling in unit tests
* Call ValidateSetVariable() with DataSize=0, Attributes=0
New in V3
==========
* Split into 2 patches.  One for code change.  Second for unit tests.
* Remove duplicate code and use ValidateSetVariable() to detect if a
variable is already locked.
https://bugzilla.tianocore.org/show_bug.cgi?id=3111
The VariableLock shim currently fails if called twice because the
underlying Variable Policy engine returns an error if a policy is set
on an existing variable.
This breaks existing code which expect it to silently pass if a variable
is locked multiple times (because it should "be locked").
Refactor the shim to confirm that the variable is indeed locked and then
change the error to EFI_SUCCESS and generate a DEBUG_ERROR message so
the duplicate …
=> Restore Variable Lock Protocol behavior

MdePkg/Include/IndustryStandard/DmaRemappingReportingTable.h
SoC Integrated Address Translation Cache (SATC) reporting structure is one
of the Remapping Structure, which is imported since Intel(R) Virtualization
Technology for Directed I/O (VT-D) Architecture Specification v3.2.
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3109
Signed-off-by: Sheng Wei <w.sheng@intel.com>
Cc: Jenny Huang <jenny.huang@intel.com>
Cc: Kowalewski Robert <robert.kowalewski@intel.com>
Cc: Feng Roger <roger.feng@intel.com>
=> MdePkg/include: Add DMAR SATC Table Definition

ArmVirtPkg/PlatformCI/.azurepipelines/Ubuntu-GCC5.yml, OvmfPkg/PlatformCI/.azurepipelines/Ubuntu-GCC5.yml
https://edk2.groups.io/g/devel/message/69152
https://www.redhat.com/archives/edk2-devel-archive/2020-December/msg01054.html
~~~
Personal build: https://github.com/tianocore/edk2/pull/1237
"vm_image: 'ubuntu-latest'" now refers to Ubuntu Focal (20.04LTS), not
Ubuntu Bionic (18.04LTS), according to
<https://github.com/actions/virtual-environments/issues/1816>.
In Focal, the "qemu" package is a dummy package with no dependencies,
and so the actual emulators are not pulled in. Compare:
https://packages.ubuntu.com/bionic/qemu
https://packages.ubuntu.com/focal/qemu
This causes CI runs to fail.
It would be best to switch to the "qemu-system" package name, which
continues to depend on the emulators:
https://packages.ubuntu.com/bionic/qemu-system
https://packages.ubuntu.com/focal/qemu-system …
=> [edk2-devel] [PATCH 0/2] {ArmVirtPkg,OvmfPkg}/PlatformCI: stick with "ubuntu-18.04" for now -- push

UefiCpuPkg/CpuDxe/X64/CpuAsm.nasm
https://bugzilla.tianocore.org/show_bug.cgi?id=3121
https://edk2.groups.io/g/devel/message/69087
https://www.redhat.com/archives/edk2-devel-archive/2020-December/msg00990.html
msgid: <20201217085055.15131-1-lersek@redhat.com>
~~~
This reverts commit cee5b0441af39dd6f76cc4e0447a1c7f788cbb00.
Commit cee5b0441af3 ("UefiCpuPkg/CpuDxe: Fix boot error", 2020-12-08)
breaks CpuDxe (and with it, OVMF boot) on AMD processors. AMD processors
cannot do far jumps to 64-bit targets, as documented in the AMD64
Architecture Programmer's Manual.
Revert the patch until a RETFQ-based substitute is posted.
Cc: James Bottomley <James.Bottomley@HansenPartnership.com>
Cc: …
=> [edk2-devel] [PATCH] Revert "UefiCpuPkg/CpuDxe: Fix boot error" -- push

OvmfPkg/Library/PlatformBootManagerLib/BdsPlatform.c
msgid: <8dbedc4c7a1c3fd390aca915270814e3b35e13a5.camel@amazon.com>
https://edk2.groups.io/g/devel/message/69133
https://www.redhat.com/archives/edk2-devel-archive/2020-December/msg01036.html
~~~
This patch fixes an issue with the current programming of the i440fx
PCI Interrupt routing assignment.
Explanation by Laszlo Ersek:
(1) The rotating pattern is a map:
(slot, function) --> (interrupt link) [LNKA..LNKD]
(more precisely, it is a pattern from (slot, pin) to (interrupt link),
but function<->pin is an identity mapping in the QEMU hardware, so we
can just use (slot, function) rather than (slot, pin) on the left hand
side. But I digress.)
The ACPI _PRT object is generated by QEMU; it describes this map.
(2) Another map is
(interrupt link) --> { set of possible interrupt numbers,
for this …
=> [edk2-devel] [PATCH v2] OvmfPkg/PlatformBootManagerLib: fix PCI interrupt link (LNKx) -- push

EmulatorPkg/PlatformCI/.azurepipelines/Ubuntu-GCC5.yml
msgid <20201221031903.1950-1-bob.c.feng@intel.com>
https://edk2.groups.io/g/devel/message/69293
https://www.redhat.com/archives/edk2-devel-archive/2020-December/msg01198.html
msgid <20201221031930.1799-1-bob.c.feng@intel.com>
https://edk2.groups.io/g/devel/message/69294
https://www.redhat.com/archives/edk2-devel-archive/2020-December/msg01199.html
~~~
The following PRs failed caused by Ubuntu-20.04. 
https://github.com/tianocore/edk2/pull/1249 
https://github.com/tianocore/edk2/pull/1250
https://github.com/tianocore/edk2/pull/1251
This patch is to fix this issue. This patch was tested by PR
https://github.com/tianocore/edk2/pull/1252
Bob Feng (1):
EmulatorPkg/PlatformCI: stick with "ubuntu-18.04" for now
EmulatorPkg/PlatformCI/.azurepipelines/Ubuntu-GCC5.yml | 2 +-
1 file changed, 1 …
=> [edk2-devel] [Patch 0/1] EmulatorPkg/PlatformCI: stick with "ubuntu-18.04" for now -- push

ArmPlatformPkg/Library/PL031RealTimeClockLib/PL031RealTimeClockLib.c, EmbeddedPkg/Include/Library/TimeBaseLib.h, EmbeddedPkg/Library/TimeBaseLib/TimeBaseLib.c
msgid <20201221113657.6779-1-lersek@redhat.com>
https://edk2.groups.io/g/devel/message/69313
https://www.redhat.com/archives/edk2-devel-archive/2020-December/msg01218.html
~~~
Branch: timebaselib_uintn
Through the virtio-fs driver, EmbeddedPkg/TimeBaseLib got exposed to
VS2019 for the first time. VS2019 flagged an arguably unintended,
implicit UINTN->UINT32 conversion in EfiTimeToEpoch(); let's remedy
that.
Thanks!
Laszlo
Laszlo Ersek (2):
ArmPlatformPkg/PL031RealTimeClockLib: cast EfiTimeToEpoch() val. to
UINT32
EmbeddedPkg/TimeBaseLib: remove useless truncation to 32-bit
EmbeddedPkg/Include/Library/TimeBaseLib.h …
=> [edk2-devel] [PATCH 0/2] EmbeddedPkg/TimeBaseLib: remove useless truncation to 32-bit -- push

BaseTools/Source/Python/Ecc/c.py
While running the Ecc tool, some unexpected behaviors occurred. These patches aim to correct them.
=> Ecc tool modifications

BaseTools/Source/Python/Workspace/MetaFileTable.py
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3127
If one protocol is not found in package dec file, Build will report the
error message that module.inf(-1): error 4000: Value of Protocol
[gXxxProtocolGuid] is not found under [Protocols] section in MdePkg.dec.
Here, -1 should be the line number of this protocol in module INF file.
=> BaseTools: Correct report the line number in INF file issue

BaseTools/Source/C/GenFfs/GenFfs.c
When Alignment < 0x400 is false, the expression of Alignment >= 0x400 is
always true. So extract the expression from the else if statement.
=> BaseTools/GenFfs: Optimazing else if statement

MdeModulePkg/Universal/StatusCodeHandler/RuntimeDxe/SerialStatusCodeWorker.c, MdeModulePkg/Universal/StatusCodeHandler/RuntimeDxe/StatusCodeHandlerRuntimeDxe.c, MdeModulePkg/Universal/StatusCodeHandler/RuntimeDxe/StatusCodeHandlerRuntimeDxe.h
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3126
1. If use PeiDxeDebugLibReportStatusCode as DebugLib, then some logs
after ExitBootService() will be lost.
2. The root cause:
2.1 The original code will register an unregister function
of gEfiEventExitBootServicesGuid, this unregister function will call
EFI_RSC_HANDLER_PROTOCOL->Unregister and does not support log through
serial port.
2.2 And some other drivers also register call back funtions of
gEfiEventExitBootServicesGuid.
2.3 Then after the unregister function is called, other call back
functions can't out log if them use RSC as DebugLib.
3. The DxeMain will report status code EFI_SW_BS_PC_EXIT_BOOT_SERVICES
after notify all the call back functions of
gEfiEventExitBootServicesGuid.
4. Solution: the StatusCodeHandlerRuntimeDxe.c …
=> MdeModulePkg/Universal/StatusCodeHandler: Fix a bug about log lost

BaseTools/Source/C/EfiRom/EfiRom.c
As the condition of while statement is argc > 0, so argc < 1 will always
be false, it's redundant.
=> BaseTools/EfiRom: remove redundant checking of argc

BaseTools/Source/Python/AutoGen/PlatformAutoGen.py
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3120
FixedAtBuild, PatchableInModule and FeatureFlag PCD don't use PCD TOKEN.
Their PCD TOKEN value can always be zero.
AutoGen.h will not be changed when static PCD is added or removed.
Dynamic PCD add or remove will still cause dynamic PCD token value be
changed.
=> BaseTools: Should always define PCD TOKEN value as Zero for static PCD

MdeModulePkg/Library/VarCheckPolicyLib/VarCheckPolicyLib.c, MdeModulePkg/Library/VarCheckPolicyLib/VarCheckPolicyLib.h, MdeModulePkg/Library/VarCheckPolicyLib/VarCheckPolicyLibStandaloneMm.c, MdeModulePkg/Library/VarCheckPolicyLib/VarCheckPolicyLibStandaloneMm.inf, MdeModulePkg/Library/VarCheckPolicyLib/VarCheckPolicyLibTraditional.c, MdeModulePkg/MdeModulePkg.dsc
This commit adds the VarCheckPolicyLib that will be able to
execute in the context of standalone MM.
Signed-off-by: Masahisa Kojima <masahisa.kojima@linaro.org>
Co-authored-by: Kun Qin <kun.q@outlook.com>
Cc: Supreeth Venkatesh <supreeth.venkatesh@arm.com>
=> MdeModulePkg/VarCheckPolicyLib: implement standalone MM version

RedfishPkg/Include/Library/RestExLib.h, RedfishPkg/Library/DxeRestExLib/DxeRestExLib.c, RedfishPkg/Library/DxeRestExLib/DxeRestExLib.inf, RedfishPkg/RedfishLibs.dsc.inc, RedfishPkg/RedfishPkg.dec, RedfishPkg/RedfishPkg.dsc
Add EFI REST EX helper library to create child instance of
REST EX service.
=> RedfishPkg/DxeRestExLib: DxeRestExLib

ArmPlatformPkg/Drivers/LcdGraphicsOutputDxe/LcdGraphicsOutputBlt.c, ArmPlatformPkg/Drivers/LcdGraphicsOutputDxe/LcdGraphicsOutputDxe.c, ArmPlatformPkg/Include/Library/LcdPlatformLib.h
This patch fixes the following Ecc reported error:
Variable name does not follow the rules:
1. First character should be upper case
2. Must contain lower case characters
3. No white space characters
4. Global variable name must start with a 'g'
Indeed, according to the EDK II C Coding Standards
Specification, s5.6.2.2 "Enumerated Types" and
s4.3.4 Function and Data Names, elements of an
enumerated type shoud be a mixed upper- and
lower-case text.
A max element is also added, as advised by
s5.6.2.2.3 of the same document.
Reference:
https://edk2-docs.gitbook.io/edk-ii-c-coding-standards-specification/
=> ArmPlatformPkg: Fix Ecc error 8005

.azurepipelines/Ubuntu-GCC5.yml, .azurepipelines/Ubuntu-PatchCheck.yml, .azurepipelines/Windows-VS2019.yml, ArmVirtPkg/PlatformCI/.azurepipelines/Ubuntu-GCC5.yml, EmulatorPkg/PlatformCI/.azurepipelines/Ubuntu-GCC5.yml, EmulatorPkg/PlatformCI/.azurepipelines/Windows-VS2019.yml, OvmfPkg/PlatformCI/.azurepipelines/Ubuntu-GCC5.yml, OvmfPkg/PlatformCI/.azurepipelines/Windows-VS2019.yml, ReadMe.rst
Cherry-pick the following commits from edk2/master to enable EDK II CI
on the stable/202011 branch and also update Readme.rst so the status badges
show the build results from the stable/202011 branch.
d21d2706761b OvmfPkg/.azurepipelines: Enable EDK II CI for stable/* branches
e690b8103813 EmulatorPkg/.azurepipelines: Enable EDK II CI for stable/* branches
db83d696084f ArmVirtPkg/.azurepipelines: Enable EDK II CI for stable/* branches
2bca741149a7 .azurepipelines: Enable EDK II CI for stable/* branches
3ce3274a5ea4 EmulatorPkg/PlatformCI: stick with "ubuntu-18.04" for now
c487970ac89d OvmfPkg/PlatformCI: stick with "ubuntu-18.04" for now
90683caedf1e ArmVirtPkg/PlatformCI: stick with "ubuntu-18.04" for now
Cc: Bret Barkelew …
=> [stable/202011][Patch 0/8] Enable EDK II CI for stable/* branches

MdeModulePkg/Test/MdeModulePkgHostTest.dsc, MdeModulePkg/Universal/Variable/RuntimeDxe/RuntimeDxeUnitTest/VariableLockRequestToLockUnitTest.c, MdeModulePkg/Universal/Variable/RuntimeDxe/RuntimeDxeUnitTest/VariableLockRequestToLockUnitTest.inf, MdeModulePkg/Universal/Variable/RuntimeDxe/VariableLockRequestToLock.c
https://bugzilla.tianocore.org/show_bug.cgi?id=3111
Cherry-pick the following commits from edk2/master to stable/202011.
(cherry picked from commit dcaa93936591883aa7826eb45ef00416ad82ef08) 
(cherry picked from commit a18a9bde36d2ffc12df29cdced1efa1f8f9f2021)
Signed-off-by: Bret Barkelew <Bret.Barkelew@microsoft.com>
=> [stable/202011][Patch 0/2] MdeModulePkg/Variable/RuntimeDxe:Restore Variable Lock Protocol behavior

BaseTools/Source/Python/GenFds/GenFdsGlobalVariable.py
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3136
Python 3.9 remove the array.array.tostring and
array.array.fromstring() function. This patch
is to use other method to replace tostring() and
fromstring()
Cc: Mingyue Liang <mingyuex.liang@intel.com>
=> BaseTools: Fix the issue caused by tostring() removal on Py39

BaseTools/Source/Python/AutoGen/GenPcdDb.py
EdkLogger.ERROR() was replaced with EdkLogger.error() to deliver the
expected error message when an error occurs.
Signed-off-by: Irene Park <ipark@nvidia.com>
=> BaseTools: Fix the improper error logging

BaseTools/Source/C/Common/CommonLib.h
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=3032
We had a build fail due to the hard coded MAX_LONG_FILE_PATH value.
We should use PATH_MAX if it is available.
Signed-off-by: Enze Zhu <zhuenze@byosoft.com.cn>
=> BaseTools/CommonLib.h: Build failed due to MAX_LONG_FILE_PATH

MdeModulePkg/Library/BrotliCustomDecompressLib/BrotliDecompress.c
The same functions have been defined in BrotliDecUefiSupport.c.
=> MdeModulePkg BrotliCustomDecompressLib: Remove the duplicated functions

IntelFsp2Pkg/FspSecCore/FspSecCoreM.inf, IntelFsp2Pkg/FspSecCore/SecMain.c, IntelFsp2Pkg/IntelFsp2Pkg.dec
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=3153
In FSP the temporary memory provided by bootloader typically will be
totally given to PeiCore as Heap, but in some cases FSP may have to
reserve some more temporary memory for private usage.
This commit adds this flexibility for FSP to reserve some
temporary memory before giving them to PeiCore.
=> IntelFsp2Pkg: Support FSP private temporary memory.

MdeModulePkg/Library/VarCheckLib/VarCheckLib.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3154
Update VarCheckLibSetVariableCheck() to allow locked variables
to be updated if the RequestSource is VarCheckFromTrusted even
if one or more variable check handlers return EFI_WRITE_PROTECTED.
RequestSource is only set to VarCheckFromTrusted if the request
is through the EFI_SMM_VARAIBLE_PROTOCOL.
=> MdeModulePkg/Library/VarCheckLib: Allow SetVariable from SMM

OvmfPkg/VirtioFsDxe/Helpers.c
https://edk2.groups.io/g/devel/message/69907
https://www.redhat.com/archives/edk2-devel-archive/2021-January/msg00395.html
Message-Id: <20210107095051.22715-1-lersek@redhat.com>
~~~
EmbeddedPkg/TimeBaseLib provides a verification function called
IsTimeValid(), for enforcing the UEFI spec requirements on an EFI_TIME
object.
When EFI_FILE_PROTOCOL.SetInfo() is called in order to update the
timestamps on the file, let's invoke IsTimeValid() first, before passing
the new EFI_FILE_INFO.{CreateTime,LastAccessTime,ModificationTime} values
to EfiTimeToEpoch().
This patch is not expected to make a practical difference, but it's better
to ascertain the preconditions of EfiTimeToEpoch() on the
EFI_FILE_PROTOCOL.SetInfo() caller. The FAT driver (EnhancedFatDxe) has a
similar check, namely in …
=> [edk2-devel] [PATCH] OvmfPkg/VirtioFsDxe: call IsTimeValid() before EfiTimeToEpoch() -- push

ArmPlatformPkg/Drivers/NorFlashDxe/NorFlashDxe.c, ArmPlatformPkg/Drivers/NorFlashDxe/NorFlashDxe.inf, ArmPlatformPkg/Drivers/NorFlashDxe/NorFlashFvb.c, ArmPlatformPkg/Drivers/NorFlashDxe/NorFlashStandaloneMm.c, ArmPlatformPkg/Drivers/NorFlashDxe/NorFlashStandaloneMm.inf
The existing NOR Flash DXE and StandaloneMm driver supports NOR flash
devices connected in the 32-bit address space. Extend these drivers to
allow NOR flash devices connected to 64-bit address space to be usable
as well. Also, convert the base address and size sanity check from
ASSERT() to if condition so that even if the firmware is build in
release mode, it can return error if the parameter(s) is/are invalid.
Signed-off-by: Vijayenthiran Subramaniam <vijayenthiran.subramaniam@arm.com>
Tested-by: Masahisa Kojima <masahisa.kojima@linaro.org>
=> ArmPlatformPkg: Enable support for flash in 64-bit address space

EmbeddedPkg/Include/Library/TimeBaseLib.h, EmbeddedPkg/Library/TimeBaseLib/TimeBaseLib.c, EmbeddedPkg/RealTimeClockRuntimeDxe/RealTimeClock.c, EmbeddedPkg/RealTimeClockRuntimeDxe/RealTimeClockRuntimeDxe.inf
This patch series replaces all time checking functions and leverage
the helper function in TimeBaseLib library.
Nhi Pham (4):
EmbeddedPkg/TimeBaseLib: Update comment blocks for API functions
EmbeddedPkg/TimeBaseLib: Fix for minor code formatting
EmbeddedPkg/TimeBaseLib: Add function to check Timezone and Daylight
EmbeddedPkg/RealTimeClockRuntimeDxe: Use helper functions from TimeBaseLib
.../RealTimeClockRuntimeDxe.inf               |   2 +
EmbeddedPkg/Include/Library/TimeBaseLib.h     |  90 +++++++++++-
EmbeddedPkg/Library/TimeBaseLib/TimeBaseLib.c | 134 +++++++++++++++---
.../RealTimeClockRuntimeDxe/RealTimeClock.c   |  88 +-----------
4 files changed, …
=> EmbeddedPkg/TimeBaseLib: Reduce duplicate code in RTC modules

MdePkg/Include/IndustryStandard/ArmErrorSourceTable.h, ShellPkg/Library/UefiShellAcpiViewCommandLib/AcpiParser.h, ShellPkg/Library/UefiShellAcpiViewCommandLib/Parsers/Aest/AestParser.c, ShellPkg/Library/UefiShellAcpiViewCommandLib/UefiShellAcpiViewCommandLib.c, ShellPkg/Library/UefiShellAcpiViewCommandLib/UefiShellAcpiViewCommandLib.inf, ShellPkg/Library/UefiShellAcpiViewCommandLib/UefiShellAcpiViewCommandLib.uni
Resending v2 patch series with Bugzilla IDs added. No code change
since v2 patch seiries.
Arm Error Source Table (AEST) enables kernel-first handling of
errors in a system that supports the Armv8 RAS extensions. AEST
is described in the ACPI for the Armv8 RAS Extensions 1.1,
Platform Design Document, dated 28 September 2020.
(https://developer.arm.com/documentation/den0085/0101/)
=> Add AEST parser support to Acpiview

EmbeddedPkg/Library/PrePiMemoryAllocationLib/MemoryAllocationLib.c
Use the correct type in the sizeof() expression to calculate the size
of the newly allocated EFI_HOB_MEMORY_POOL hob.
Link: https://bugzilla.tianocore.org/show_bug.cgi?id=3139
=> EmbeddedPkg/PrePiMemoryAllocationLib: use correct size for pool hob

EmbeddedPkg/EmbeddedPkg.dsc
Commit 55ee36b0c490
("EmbeddedPkg/RealTimeClockRuntimeDxe: Use helper functions from TimeBaseLib")
added a TimeBaseLib dependency to RealTimeClockRuntimeDxe, which now breaks
build of EmbeddedPkg.dsc.
Add a resolution for EmbeddedPkg/Library/TimeBaseLib/TimeBaseLib.inf.
Cc: Nhi Pham <nhi@os.amperecomputing.com>
=> EmbeddedPkg: add TimeBaseLib resolution to EmbeddedPkg.dsc

OvmfPkg/OvmfXen.dsc
Commit 55ee36b0c490
("EmbeddedPkg/RealTimeClockRuntimeDxe: Use helper functions from TimeBaseLib")
added a TimeBaseLib dependency to RealTimeClockRuntimeDxe, which now breaks
build of OvmfXen.dsc.
Add a resolution for EmbeddedPkg/Library/TimeBaseLib/TimeBaseLib.inf.
Cc: Anthony Perard <anthony.perard@citrix.com>
Cc: Julien Grall <julien@xen.org>
=> OvmfPkg: add TimeBaseLib resolution for OvmfXen

EmbeddedPkg/RealTimeClockRuntimeDxe/RealTimeClockRuntimeDxe.inf
The EfiGetVariable() is used in the entry of this module. So, the
variable services are required to be ready before they are used. This
patch adds the arch protocol gEfiVariableArchProtocolGuid to dependency
expression to guarantee that this module will be started once the
variable protocol is available.
=> EmbeddedPkg/RealTimeClockRuntimeDxe: depend on gEfiVariableArchProtocolGuid

BaseTools/Source/Python/build/BuildReport.py
In the following corner case, the build report
will crash. This patch is to fix this problem.
Case:
Multiple SKU are used and 2 more DynamicHii structure Pcds
are set in dsc file under different SKU. And 1 more of those
Pcds are not used in any INF file.
Reviewed-by: Yuwei Chen<yuwei.chen@intel.com>
=> BaseTools: Fix the build report crash issue

MdeModulePkg/Library/FileExplorerLib/FileExplorer.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3113
According to FAT specification, the length of file path
should not larger than 260. When the length exceed 260,
function FatLocateOFile will return EFI_INVALID_PARAMETER
and the parameter FileHandle will be NULL. Then on the
top-level function?an exception happens when the NULL
pointer is passed and be used.
So adding return value check after calling
LibGetFileHandleFromMenu, if return value is not success,
stop calling LibFindFiles.
=> MdeModulePkg/FileExplorerLib: Add return value check

EmulatorPkg/EmulatorPkg.dec, EmulatorPkg/EmulatorPkg.dsc, EmulatorPkg/Library/RedfishPlatformCredentialLib/RedfishPlatformCredentialLib.c, EmulatorPkg/Library/RedfishPlatformCredentialLib/RedfishPlatformCredentialLib.inf
Platform specific implementation of acquiring credential
to access to Redfish service. This is the platform library
that incorporates with Redfish Credential DXE driver under
Redfish package.
Acked-by: Ray Ni <ray.ni@intel.com>
=> EmulatorPkg/library: RedfishPlatformCredentialLib

MdeModulePkg/Bus/Pci/PciBusDxe/PciEnumeratorSupport.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3149
Address MEM64 BAR in type unknown if sizing fail in high 32bit.
Signed-off-by: Zarcd Zhong <zarcd.zhong@intel.com>
=> MdeModulePkg/PciBusDxe: Handle BAR sizing fail in high 32bit of MEM64.

Maintainers.txt
I will no longer work for ARM as of next month, and will therefore
lose access to my @arm.com email account. I intend to remain active
in the Tianocore project nonetheless, so let's update my email accounts
to one that is not tied to my current or future employer.
Cc: <ardb+tianocore@kernel.org>
Reviewed-by: Andrew Fish <afish@apple.com>
Acked-by: Sami Mujawar <sami.mujawar@arm.com>
=> Maintainers: update Ard's email address

ArmPlatformPkg/Drivers/NorFlashDxe/NorFlashDxe.c, ArmPlatformPkg/Drivers/NorFlashDxe/NorFlashStandaloneMm.c, ArmPlatformPkg/Drivers/NorFlashDxe/NorFlashStandaloneMm.inf
Commit 8015f3f6d4005d83 ("ArmPlatformPkg: Enable support for flash in
64-bit address space") updated the NorFlash DXE and StMM drivers to
take alternate PCDs into account when discovering the base of the
NOR flash regions.
This introduced a disparity between the declarations of the PCD references
in the .INF files, which permits the use of dynamic PCDs, and the code
itself, which now uses FixedPcdGet() accessors. On platforms that actually
use dynamic PCDs, this results in a build error.
So let's clean this up:
- for the DXE version, use the generic PcdGet() accessors, so dynamic PCDs
are permitted
- for the standalone MM version, redeclare the PCDs as [FixedPcd] in the
.INF description, and switch to the FixedPcdGet() accessors. …
=> ArmPlatformPkg/NorFlashDxe: use correct PCD accessors

MdePkg/Include/Register/Intel/Cpuid.h, UefiCpuPkg/Include/Library/CpuCacheInfoLib.h, UefiCpuPkg/Library/CpuCacheInfoLib/CpuCacheInfoLib.c, UefiCpuPkg/Library/CpuCacheInfoLib/CpuCacheInfoLib.uni, UefiCpuPkg/Library/CpuCacheInfoLib/DxeCpuCacheInfoLib.c, UefiCpuPkg/Library/CpuCacheInfoLib/DxeCpuCacheInfoLib.inf, UefiCpuPkg/Library/CpuCacheInfoLib/InternalCpuCacheInfoLib.h, UefiCpuPkg/Library/CpuCacheInfoLib/PeiCpuCacheInfoLib.c, UefiCpuPkg/Library/CpuCacheInfoLib/PeiCpuCacheInfoLib.inf, UefiCpuPkg/UefiCpuPkg.dec, UefiCpuPkg/UefiCpuPkg.dsc
This new library uses a platform agnostic algorithm to get CPU
cache information. It provides user with an API(GetCpuCacheInfo)
to get detailed CPU cache information by each package, each core
type included in this package, and each cache level & type.
This library can be used by code that produces SMBIOS_TABLE_TYPE7
SMBIOS table.
=> Create new CpuCacheInfoLib

OvmfPkg/OvmfXen.dsc, OvmfPkg/XenPlatformPei/MemDetect.c
(previous PR attempt: #1365)
msgid: 1610509335-23314-1-git-send-email-igor.druzhinin@citrix.com
https://edk2.groups.io/g/devel/message/70190
https://www.redhat.com/archives/edk2-devel-archive/2021-January/msg00674.html
~~~
We faced a problem with passing through a PCI device with 64GB BAR to
UEFI guest. The BAR is expectedly programmed into 64-bit PCI aperture at
64G address which pushes physical address space to 37 bits. That is above
36-bit width that OVMF exposes currently to a guest without tweaking
PcdPciMmio64Size knob.
The reverse calculation using this knob was inhereted from QEMU-KVM platform
code where it serves the purpose of finding max accessible physical
address without necessary trusting emulated CPUID physbits value (that could
be different from host physbits). On Xen we …
=> [edk2-devel] [PATCH] OvmfPkg/XenPlatformPei: Use CPUID to get physical address width on Xen -- push#2

NetworkPkg/Library/DxeHttpIoLib/DxeHttpIoLib.c, NetworkPkg/Library/DxeHttpIoLib/DxeHttpIoLib.inf, NetworkPkg/NetworkPkg.dec
https://bugzilla.tianocore.org/show_bug.cgi?id=3170
Using PcdHttpIoTimeout to set default timeout value to HttpIoLib.
Signed-off-by: GregX Yeh <gregx.yeh@intel.com>
=> DxeHttpIoLib: Http boot failure with no initializes timeout value.

UefiCpuPkg/Library/RegisterCpuFeaturesLib/RegisterCpuFeaturesLib.c
https://bugzilla.tianocore.org/show_bug.cgi?id=3159
https://edk2.groups.io/g/devel/message/70614
https://www.redhat.com/archives/edk2-devel-archive/2021-January/msg01101.html
msgid <20210121093944.1621-1-star.zeng@intel.com>
~~~
NumberOfCpus local variable in GetAcpiCpuData will be uninitialized
when CpuS3DataDxe runs before DxeRegisterCpuFeaturesLib (linked by
CpuFeaturesDxe) because there is no code to initialize it at
(AcpiCpuData != NULL) execution path.
The issue is exposed after cefad282fb31aff3e1a6dcbd368cbbffc3fce900
and 38ee7bafa72f58982f99ac6f61eef160f80bad69.
There was negligence in that code review.
One further topic may be "Could EDK2 CI be enhanced to catch this kind
of uninitialized local variable case?". 
This patch fixes this regression issue.
Cc: Eric Dong …
=> [edk2-devel] [PATCH] UefiCpuPkg RegisterCpuFeaturesLib: NumberOfCpus may be uninitialized -- push

UefiCpuPkg/CpuMpPei/CpuMpPei.c, UefiCpuPkg/CpuMpPei/CpuMpPei.h, UefiCpuPkg/CpuMpPei/CpuMpPei.inf
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3167
When StackGuard is enabled, the CpuMp driver allocates
known good stacks for all CPUs for DF# and PF# exceptions.
It uses AllocatePool to do so.
The size needed equals to 64KB
= StackSize (2K) * ExceptionNumber (2) * NumberOfProcessors (16)
However, AllocatePool max allocation size is less than 64K.
To fix the issue, AllocatePages() is used.
=> UefiCpuPkg/CpuMp: Fix hang when StackGuard is enabled in 16-core cpu

MdePkg/Include/IndustryStandard/Tpm2Acpi.h
Add Start Method Specific Parameters for ARM SMC Start Method described
in the TCG ACPI Specification version 1.2, revision 8.
=> MdePkg/Tpm2Acpi.h: Add Start Method Specific Parameters for ARM SMC

MdePkg/Include/Register/Intel/Cpuid.h, UefiCpuPkg/Library/CpuCacheInfoLib/CpuCacheInfoLib.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3105
Change and add some macro definitions about
CPUID_HYBRID_INFORMATION Leaf(1Ah).
=> MdePkg/Cpuid.h: Change and add some macro definitions.

MdePkg/Library/SmiHandlerProfileLibNull/SmiHandlerProfileLibNull.c, MdePkg/Library/SmiHandlerProfileLibNull/SmiHandlerProfileLibNull.inf
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=3184
Allows the library instance to be linked with MM_STANDALONE modules.
=> MdePkg/SmiHandlerProfileLibNull: Add MM_STANDALONE support

MdeModulePkg/Bus/Pci/PciBusDxe/PciEnumeratorSupport.c
The ProcessOptionRomLight() assumes that OpRom has already been
processed in the previous full enumeration and updates
AllOpRomProcessed flag to TRUE by default. However, this may not
be applicable with other pre-stage boot firmwares.
This will update AllOpRomProcessed flag properly by checking
PciRomGetImageMapping().
Signed-off-by: Aiden Park <aiden.park@intel.com>
=> MdeModulePkg/PciBusDxe: Fix a bug in ProcessOptionRomLight

MdeModulePkg/Universal/Console/TerminalDxe/Terminal.h
Fix the bug of terminal fifo buffer overflow with UINT8 type.
typedef struct {
UINT8 Head;
UINT8 Tail;
UINT8 Data[RAW_FIFO_MAX_NUMBER + 1];
} RAW_DATA_FIFO;
RAW_FIFO_MAX_NUMBER is 256.
the data buffer size is 257 (Index from 0 to 256), but the max value of
the index, Head or Tail (UINT8), is 255. That means the last data of the
data buffer would be always empty if we use Head/Tail to output/input the
data correctly.  And because of the incorrect buffer size the FIFO full
check "((Tail + 1) % (RAW_FIFO_MAX_NUMBER + 1)) == Head" would never meet.
Signed-off-by: gechao <gechao@greatwall.com.cn>
=> MdeModulePkg/TerminalDxe: Terminal fifo buffer overflow.

ArmPkg/Library/PlatformBootManagerLib/PlatformBm.c, ArmPkg/Library/PlatformBootManagerLib/PlatformBootManagerLib.inf
If no valid boot options were found, PlatformBootManagerLib refreshes a
set of sane default options and then reboots. However, if there is in
fact no persistent varstore, the same thing happens again on next boot,
and we end up in an endlessly rebooting loop.
So when PcdEmuVariableNvModeEnable is TRUE, skip the reboot step and
enter the setup menu instead.
=> ArmPkg/Library: prevent endless reboot loop with emulated NV varstore

MdeModulePkg/Include/Library/HiiLib.h, MdeModulePkg/Library/UefiHiiLib/HiiString.c
Add HiiGetStringEx and leveraged by HiiGetString function to support
getting string with the best language in optionally. This avoids the
string in x-uefi language is misled to the language defined by
"PlatformLang" or the "Supported Languages". This change is introduced
to support x-uefi keyword language for configuring BIOS setting.
Signed-off-by: Fan Wang <fan.wang@intel.com>
=> MdeModulePkg/Library: Add HiiGetStringEx to UefiHiiLib for EDK2 Redfish

BaseTools/Source/Python/Split/Split.py, BaseTools/Source/Python/tests/Split/test_split.py
If the output file path is a relative path, the split
tool will create the output file under the input file path.
But the expected behavior for this case is the output file
should be relative to the current directory. This patch will
fix this bug.
If the output file path is not specified and output prefix is not
specified, the output file should be under the input file path
=> BaseTools: fix the split output files root dir

Maintainers.txt
https://edk2.groups.io/g/devel/message/71263
https://listman.redhat.com/archives/edk2-devel-archive/2021-February/msg00315.html
msgid: <20210204194902.101548-1-jordan.l.justen@intel.com>
~~~
[edk2-devel] [PATCH v2 1/2] Maintainers.txt: Remove Jordan Justen from EmulatorPkg
[edk2-devel] [PATCH v2 2/2] Maintainers.txt: Change Jordan Justen to a reviewer for OvmfPkg
~~~
=> update Jordan Justen's entries in Maintainers.txt, v2 -- push

IntelFsp2Pkg/Tools/FspDscBsf2Yaml.py, IntelFsp2Pkg/Tools/GenCfgOpt.py, IntelFsp2Pkg/Tools/Tests/ExpectedFspUpd.h, IntelFsp2Pkg/Tools/Tests/ExpectedFspmUpd.h, IntelFsp2Pkg/Tools/Tests/ExpectedFspsUpd.h, IntelFsp2Pkg/Tools/Tests/ExpectedFsptUpd.h, IntelFsp2Pkg/Tools/Tests/ExpectedOutput.bsf, IntelFsp2Pkg/Tools/Tests/ExpectedOutput.yaml, IntelFsp2Pkg/Tools/Tests/QemuFspPkg.dsc, IntelFsp2Pkg/Tools/Tests/test_yaml.py, IntelFsp2Pkg/Tools/UserManuals/FspDscBsf2YamlUserManual.md
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=3091
Add support for YAML format file generation in addition
to current BSF structure. Configuration of YAML format
output will be supported by an open source ConfigEditor.
Reference to YAML code, test and ConfigEditor is at
https://github.com/joshloo/fsp_yaml_cfg/tree/master/Tools
A unit test is also added in Tests folder. This test compares
the generated yaml file against the expected output to know
if it is constructing the yaml data structure as expected.
=> IntelFsp2Pkg: Add YAML file generation support

ArmPkg/Universal/Smbios/OemMiscLibNull/OemMiscLib.c, ArmPkg/Universal/Smbios/OemMiscLibNull/OemMiscLibNull.inf
The just added OemMiscLibNull fails to build due to DebugLib.h not
being included, missing the ASSERT definition. Add the include and the
library dependency.
Cc: Rebecca Cran <rebecca@nuviainc.com>
Reviewed-by: Rebecca Cran <rebecca@nuviainc.com>
=> ArmPkg: add DebugLib to OemMiscLibNull

ArmPkg/Universal/Smbios/ProcessorSubClassDxe/SmbiosProcessorArm.c
The ARM ProcessorSubClassDxe build was broken due to changes in the
SmbiosProcessor API and an unused variable.
=> ArmPkg: Fix ARM ProcessorSubClassDxe build

StandaloneMmPkg/Include/Library/FvLib.h
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=3203
The EFIAPI modifier is present in the function definition in
FvLib.c but missing in FvLib.h. Causes a GCC build error.
=> StandaloneMmPkg/FvLib.h: Add EFIAPI to FfsFindSection()

DynamicTablesPkg/Library/Common/AmlLib/NameSpace/AmlNameSpace.c
Building the DynamicTablesPkg for a NOOPT target
fails because unused variables are set.
Remove these variables.
Fixes: d9800046ea43
Reported-by: Leif Lindholm <leif@nuviainc.com>
=> DynamicTablesPkg/AmlLib: Remove unused variables

EmbeddedPkg/Library/VirtualRealTimeClockLib/VirtualRealTimeClockLib.c
The DEBUG message for using compilation time epoch is appearing very
frequently on DEBUG firmware builds, for example during UEFI SCT runs.
Reduce verbosity to avoid the annoying repetitive message.
Signed-off-by: Samer El-Haj-Mahmoud <Samer.El-Haj-Mahmoud@arm.com>
=> EmbeddedPkg/VirtualRealTimeClockLib: Reduce DEBUG message verbosity

ArmPkg/Include/Library/OemMiscLib.h, ArmPkg/Universal/Smbios/OemMiscLibNull/OemMiscLib.c, ArmPkg/Universal/Smbios/ProcessorSubClassDxe/ProcessorSubClass.c, ArmPkg/Universal/Smbios/SmbiosMiscDxe/Type03/MiscChassisManufacturerFunction.c
Update OemMiscLib with the following changes:                                                           
o Fixed ordering of return type and EFIAPI specifier.                                                   
o Renamed 'mHiiHandle' parameter in OemUpdateSmbiosInfo to 'HiiHandle'.                                 
o Renamed 'Offset' parameter in OemUpdateSmbiosInfo to 'Field'.                                         
o Renamed OemGetProcessorMaxSockets to OemGetMaxProcessors.                                             
o Renamed OemIsSocketPresent to OemIsProcessorPresent.                                                  
o Updated OemGetChassisType to return MISC_CHASSIS_TYPE instead of                                      
EFI_STATUS, which matches other OemMiscLib functions.
=> ArmPkg: Fix several issues in OemMiscLib

RedfishPkg/Library/JsonLib/JsonLib.c
json_string_value() in JsonValueGetAsciiString () is removed by a accident
when clean up the code.
=> RedfishPkg/JsonLib: Fix the mistake of removing code by a accident

RedfishPkg/Library/JsonLib/JsonLib.inf
Ignore the build error of assignment within conditional expression.
Add build option to ignore the build error of "assignment within
conditional expression".
This build error is caused by the macros defined in open source
project jansson header file jansson.h.
- json_object_foreach
- json_object_foreach_safe
- json_array_foreach
We use build option to avoid the build errors on Visual Studio
(GCC doesn't havvve this problem) for now. Already sent an email
to jansson open source community to revise these macro as Leif's
suggestion as below,
for (key = json_object_iter_key(json_object_iter(object));    \
       key;                                                   \
       key = json_object_iter_key(                            \
            json_object_iter_next(object, …
=> RedfishPkg/JsonLib: Ignore the build error of conditional expression.

RedfishPkg/Include/Library/RedfishContentCodingLib.h, RedfishPkg/Library/RedfishContentCodingLibNull/RedfishContentCodingLibNull.c, RedfishPkg/Library/RedfishContentCodingLibNull/RedfishContentCodingLibNull.inf, RedfishPkg/RedfishPkg.dec, RedfishPkg/RedfishPkg.dsc
BZ#:3174
Platform library to provide the encoding/decoding algorithms for
the Redfish packets.
The supported value could be one of below or any which is
platform-specific.
- HTTP_CONTENT_ENCODING_IDENTITY "identity"
- HTTP_CONTENT_ENCODING_GZIP     "gzip"
- HTTP_CONTENT_ENCODING_COMPRESS "compress"
- HTTP_CONTENT_ENCODING_DEFLATE  "deflate"
- HTTP_CONTENT_ENCODING_BROTLI   "br"
=> RedfishPkg/RedfishContentCodingLib: EDKII Redfish En/Decode library

MdeModulePkg/Library/UefiBootManagerLib/BmBoot.c
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=3135
When Boot Menu does not exist in the BootOrder, BmRegisterBootManagerMenu
will create one into list. However, it should be put at the "end" of
BootOrder instead of "start" of BootOrder. Replace 0 by -1 to adjust
order of load options.
Signed-off-by: Walon Li <walon.li@hpe.com>
=> MdeModulePkg/UefiBootManagerLib: Put BootMenu at the end of BootOrder

BaseTools/Source/Python/Ecc/Check.py, BaseTools/Source/Python/Ecc/EccToolError.py
The EDK II C Coding Standards Specification states that:
"Names starting with one or two underscores, such as
_MACRO_GUARD_FILE_NAME_H_, must not be used. They are
reserved for compiler implementation." [1]
The Ecc tool currently checks that the include guard end with
a trailing underscore. Thus, the check and the error message
should both be modified.
The new check forces having one sole trailing underscore
character, as the example in the specification shows:
"FILE_NAME_H_" [1]
This would allow to have more consistency.
[1] Section 5.3.5 "All include file contents must be protected
by a #include guard":
https://edk2-docs.gitbook.io/
edk-ii-c-coding-standards-specification/5_source_files/53_include_files
Reviewed-by: Sami Mujawar …
=> BaseTools: Align include guards policy

UefiCpuPkg/Library/MpInitLib/Ia32/MpFuncs.nasm, UefiCpuPkg/Library/MpInitLib/X64/MpFuncs.nasm
When AP firstly wakes up, MpFuncs.nasm contains below logic to assign
an unique ApIndex to each AP according to who comes first:
---ASM---
TestLock:
xchg       [edi], eax
cmp        eax, NotVacantFlag
jz         TestLock
mov        ecx, esi
add        ecx, ApIndexLocation
inc        dword [ecx]
mov        ebx, [ecx]
Releaselock:
mov        eax, VacantFlag
xchg       [edi], eax
---ASM END---
"lock inc" cannot be used to increase ApIndex because not only the
global ApIndex should be increased, but also the result should be
stored to a local general purpose register EBX.
This patch learns from the NASM implementation of
InternalSyncIncrement() to use "XADD" instruction which can increase
the global ApIndex and store the original ApIndex to EBX in one
instruction.
With this patch, OVMF when …
=> UefiCpuPkg/MpInitLib: Use XADD to avoid lock acquire/release

ArmPkg/Drivers/ArmGic/ArmGicLib.c
The first patch is prepare for the second one.
Ming Huang (2):
ArmPkg/ArmGicLib: Fix two macros issue for offset parameter
ArmPkg/ArmGicLib: Fix GICR_IPRIORITYR address wrong issue
ArmPkg/Drivers/ArmGic/ArmGicLib.c | 9 ++++++---
1 file changed, 6 insertions(+), 3 deletions(-)
This resolves https://bugzilla.tianocore.org/show_bug.cgi?id=3236
=> Fix two issue in ArmGicLib

MdePkg/Include/Ia32/Nasm.inc, MdePkg/Include/X64/Nasm.inc, UefiCpuPkg/Library/CpuExceptionHandlerLib/DxeCpuExceptionHandlerLib.inf, UefiCpuPkg/Library/CpuExceptionHandlerLib/PeiCpuExceptionHandlerLib.inf, UefiCpuPkg/Library/CpuExceptionHandlerLib/SecPeiCpuExceptionHandlerLib.inf, UefiCpuPkg/Library/CpuExceptionHandlerLib/SmmCpuExceptionHandlerLib.inf, UefiCpuPkg/Library/CpuExceptionHandlerLib/X64/Xcode5ExceptionHandlerAsm.nasm, UefiCpuPkg/Library/CpuExceptionHandlerLib/Xcode5SecPeiCpuExceptionHandlerLib.inf, UefiCpuPkg/PiSmmCpuDxeSmm/MpService.c, UefiCpuPkg/PiSmmCpuDxeSmm/X64/PageTbl.c, UefiCpuPkg/PiSmmCpuDxeSmm/X64/SmmFuncsArch.c
If CET shadows stack feature enabled in SMM and stack switch is enabled.
When code execute from SMM handler to SMM exception, CPU will check SMM
exception shadow stack token busy bit if it is cleared or not.
If it is set, it will trigger #DF exception.
If it is not set, CPU will set the busy bit when enter SMM exception.
So, the busy bit should be cleared when return back form SMM exception to
SMM handler. Otherwise, keeping busy bit 1 will cause to trigger #DF
exception when enter SMM exception next time.
So, we use instruction SAVEPREVSSP, CLRSSBSY and RSTORSSP to clear the
shadow stack token busy bit before RETF instruction in SMM exception.
Since open CI is using NASM 2.14.02, it has not supported CET instructions
yet. DB-encoded CET instructions will to be removed after open CI …
=> Fix CET shadow stack token busy bit clear issue

MdeModulePkg/Bus/Ufs/UfsPassThruDxe/UfsPassThru.c, MdeModulePkg/Bus/Ufs/UfsPassThruDxe/UfsPassThru.h
https://bugzilla.tianocore.org/show_bug.cgi?id=3217
Current Ufs Pass thru driver polls for 5us and return success even when
the timeout occurs.
There are cards that can take upto 600ms for Init and hence increased
the time out for fDeviceInit polling loop.
Signed-off-by: Bandaru <purna.chandra.rao.bandaru@intel.com>
Cc: Mateusz Albecki <mateusz.albecki@intel.com>
=> MdeModulePkg/UfsPassThruDxe: Improve Device initialization polling Loop

BaseTools/Bin/nasm_ext_dep.yaml
Update the external dependency (consumed by Edk2Tools) version for NASM,
as agreed in recent community meetings:
https://edk2.groups.io/g/devel/message/71289
https://edk2.groups.io/g/devel/message/71070
This is primarily used by CI builds, but may also be used by platforms.
Signed-off-by: Bret Barkelew <Bret.Barkelew@microsoft.com>
=> BaseTools: Update the NASM CI dependency

BaseTools/Scripts/ConvertFceToStructurePcd.py
Currently StructurePcd.dsc have the list order issue. For a Pcd
with several elements, the list indexs are used to distinguish
these elements like this:
PcdName.name.offset_name[0]|0x0
PcdName.name.offset_name[10]|0x0
PcdName.name.offset_name[11]|0x0
...
PcdName.name.offset_name[2]|0x0
...
However, the index is not strictly sorted by decimal numerical order,
which is not user friendly. One more sort rule for index is added to
the current rules to support for decimal numerical order in this patch.
=> BaseTools: Adjust StructurePcd List Order.

BaseTools/Scripts/ConvertFceToStructurePcd.py
Currently the struct parser for StructPcd Generation does not
filter the types such as UINT8 which should be ignored successfully.
This patch modifies this issue.
=> BaseTools: Modify struct parser for StructPcd

EmbeddedPkg/Library/VirtualRealTimeClockLib/VirtualRealTimeClockLib.c
The message "LibGetTime: RtcEpochSeconds non volatile variable was not
found - Using compilation time epoch." can be printed a very large
number of times, causing log files to become excessively large. This is
because the RtcEpochSeconds variable only gets set if LibSetTime is
called, for example by running 'time 12:00' in the UEFI Shell.
Avoid this by setting RtcEpochSeconds to BUILD_EPOCH (EpochSeconds)
after printing the message. It's set to a volatile variable so the
message will be displayed on future boots and not hidden.
Commit 44ae214591e58af468eacb7b873eaa0bc187c4fa reduced the verbosity of
the message to DEBUG_VERBOSE. Revert it back to DEBUG_INFO so it's more
prominent now that it doesn't get printed so frequently.
Acked-by: …
=> EmbeddedPkg: Only print LibGetTime message about compile time epoch once

UefiCpuPkg/Library/SmmCpuFeaturesLib/CpuFeaturesLib.h, UefiCpuPkg/Library/SmmCpuFeaturesLib/Ia32/SmmStmSupport.c, UefiCpuPkg/Library/SmmCpuFeaturesLib/SmmCpuFeaturesLib.c, UefiCpuPkg/Library/SmmCpuFeaturesLib/SmmCpuFeaturesLib.inf, UefiCpuPkg/Library/SmmCpuFeaturesLib/SmmCpuFeaturesLibCommon.c, UefiCpuPkg/Library/SmmCpuFeaturesLib/SmmCpuFeaturesLibNoStm.c, UefiCpuPkg/Library/SmmCpuFeaturesLib/SmmCpuFeaturesLibStm.inf, UefiCpuPkg/Library/SmmCpuFeaturesLib/SmmStm.c, UefiCpuPkg/Library/SmmCpuFeaturesLib/StandaloneMmCpuFeaturesLib.c, UefiCpuPkg/Library/SmmCpuFeaturesLib/StandaloneMmCpuFeaturesLib.inf, UefiCpuPkg/Library/SmmCpuFeaturesLib/TraditionalMmCpuFeaturesLib.c, UefiCpuPkg/Library/SmmCpuFeaturesLib/X64/SmmStmSupport.c, UefiCpuPkg/UefiCpuPkg.dsc
https://bugzilla.tianocore.org/show_bug.cgi?id=3218
https://edk2.groups.io/g/devel/message/71751
message-id: <20210217213227.1277-1-mikuback@linux.microsoft.com>
https://listman.redhat.com/archives/edk2-devel-archive/2021-February/msg00803.html
~~~
From: Michael Kubacki <michael.kubacki@microsoft.com>
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=3218
The present SmmCpuFeaturesLib implementation in UefiCpuPkg can be
useful for IA32/X64 platforms that need a library instance for
a Standalone MM environment. Much of the logic can be reused and a
new INF can isolate the differences unique to Standalone MM.
This patch series contains an initial set of changes for cleaning
up pre-existing design issues in the library. The final two patches
contain changes needed for Standalone MM support. …
=> [edk2-devel] [PATCH v3 0/5] UefiCpuPkg/StandaloneMmCpuFeaturesLib: Add Standalone MM support -- push

RedfishPkg/PrivateInclude/Library/RedfishLib.h, RedfishPkg/PrivateLibrary/RedfishLib/RedfishLib.c, RedfishPkg/PrivateLibrary/RedfishLib/RedfishLib.inf, RedfishPkg/PrivateLibrary/RedfishLib/RedfishMisc.c, RedfishPkg/PrivateLibrary/RedfishLib/RedfishMisc.h, RedfishPkg/PrivateLibrary/RedfishLib/edk2libredfish/include/redfish.h, RedfishPkg/PrivateLibrary/RedfishLib/edk2libredfish/include/redfishPayload.h, RedfishPkg/PrivateLibrary/RedfishLib/edk2libredfish/include/redfishService.h, RedfishPkg/PrivateLibrary/RedfishLib/edk2libredfish/include/redpath.h, RedfishPkg/PrivateLibrary/RedfishLib/edk2libredfish/src/payload.c, RedfishPkg/PrivateLibrary/RedfishLib/edk2libredfish/src/redpath.c, RedfishPkg/PrivateLibrary/RedfishLib/edk2libredfish/src/service.c, RedfishPkg/RedfishLibs.dsc.inc, RedfishPkg/RedfishPkg.ci.yaml, RedfishPkg/RedfishPkg.dec, RedfishPkg/RedfishPkg.dsc
EDK2 port of DMTF libredfish project. We clone the necessary files
from open source project libredfish (https://github.com/DMTF/
libredfish) tag v1.0.0 and revise it to incorporate with edk2
firmware codebase.
The reason for cloning the necessary files instead of using extern
submodule of libredfish project:
libredfish as a C library that is executed under Windows and
Linux. It could be bound with other programming languages such as
java and python. The library uses curl library as the communication service with Redfish, which is not easy to be abstracted and
replaced with EFI specific protocols (e.g. EFI_REST_EX_PROTOCOL or
payload encode/decode library) and EFI data types. We had the
conversation with DMTF community and they think edk2 is a firmware
solution but not the programming …
=> RedfishPkg/Library: RedfishLib

OvmfPkg/CpuHotplugSmm/CpuHotplug.c, OvmfPkg/CpuHotplugSmm/CpuHotplugSmm.inf, OvmfPkg/CpuHotplugSmm/QemuCpuhp.c, OvmfPkg/CpuHotplugSmm/QemuCpuhp.h, OvmfPkg/Include/IndustryStandard/QemuCpuHotplug.h, OvmfPkg/Include/Pcd/CpuHotEjectData.h, OvmfPkg/Library/SmmCpuFeaturesLib/SmmCpuFeaturesLib.c, OvmfPkg/Library/SmmCpuFeaturesLib/SmmCpuFeaturesLib.inf, OvmfPkg/OvmfPkg.dec, OvmfPkg/SmmControl2Dxe/SmiFeatures.c
https://bugzilla.tianocore.org/show_bug.cgi?id=3132
msgid: <20210312062656.2477515-1-ankur.a.arora@oracle.com>
https://edk2.groups.io/g/devel/message/72702
https://listman.redhat.com/archives/edk2-devel-archive/2021-March/msg00449.html
~~~
Hi,
This series adds OVMF support for CPU hot-unplug.
QEMU secureboot hot-unplug logic corresponding to this is in upstream.
Also posted here:
https://lore.kernel.org/qemu-devel/20201207140739.3829993-1-imammedo@redhat.com/
Testing (with QEMU 5.2.50):
- Stable with randomized CPU plug/unplug (guest maxcpus=33,128)
- Synthetic tests with simultaneous multi CPU hot-unplug
Also at:
github.com/terminus/edk2/ hot-unplug-v9
Changelog:
v9:
- Rebased on top of edd46cd407ea
- Clarify comments around memory-barriers in patches 7, 8, 9
- Address other review …
=> [edk2-devel] [PATCH v9 00/10] support CPU hot-unplug -- push

EmbeddedPkg/Library/PrePiHobLib/PrePiHobLib.inf
Currently there is a duplicate GUID shared by two INFs.
This rolls the INF for the PrePiHobLib.
Ref: https://bugzilla.tianocore.org/show_bug.cgi?id=2381
Signed-off-by: Matthew Carlson <matthewfcarlson@gmail.com>
=> EmbeddedPkg/PrePiHobLib: replace duplicate GUID

MdePkg/Library/UefiLib/UefiLib.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3211
Correct the arguments passed to the IsLanguageSupported() function in
AddUnicodeString2() and LookupUnicodeString2() as expected by the function
Signed-off-by: Chandramohan Akula <chandramohan.akula@broadcom.com>
=> MdePkg/UefiLib: Correct the arguments passed to IsLanguageSupported()

UefiCpuPkg/Include/Library/CpuCacheInfoLib.h, UefiCpuPkg/Library/CpuCacheInfoLib/CpuCacheInfoLib.c, UefiCpuPkg/Library/CpuCacheInfoLib/InternalCpuCacheInfoLib.h
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3265
Support collecting cache associative type in CpuCacheInfoLib.
This prevents the user from using additional code to obtain the
same information.
=> UefiCpuPkg/CpuCacheInfoLib: Collect cache associative type

UefiCpuPkg/Library/MpInitLib/Microcode.c, UefiCpuPkg/Library/MpInitLib/MpLib.c, UefiCpuPkg/Library/MpInitLib/MpLib.h
MpInitLib contains a function MicrocodeDetect() which is called by
all threads as an AP procedure.
Today this function contains below code:
if (CurrentRevision != LatestRevision) {
AcquireSpinLock(&CpuMpData->MpLock);
DEBUG ((
EFI_D_ERROR,
"Updated microcode signature [0x%08x] does not match \
loaded microcode signature [0x%08x]\n",
CurrentRevision, LatestRevision
));
ReleaseSpinLock(&CpuMpData->MpLock);
}
When the if-check is passed, the code may call into PEI services:
1. AcquireSpinLock
When the PcdSpinTimeout is not 0, TimerLib
GetPerformanceCounterProperties() is called. And some of the
TimerLib implementations would get the information cached in
HOB. But AP procedure cannot call PEI services to retrieve the
HOB list.
2. DEBUG
Certain DebugLib relies on ReportStatusCode services and …
=> UefiCpuPkg/MpInitLib: avoid printing debug messages in AP

UefiCpuPkg/CpuDxe/CpuGdt.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3233
GDT needs to be allocated below 4GB in 64bit environment
because AP needs it for entering to protected mode.
CPU running in big real mode cannot access above 4GB GDT.
But CpuDxe driver contains below code:
gdt = AllocateRuntimePool (sizeof (GdtTemplate) + 8);
.....
gdtPtr.Base = (UINT32)(UINTN)(VOID*) gdt;
The AllocateRuntimePool() may allocate memory above 4GB.
Thus, we cannot use AllocateRuntimePool (), instead,
we should use AllocatePages() to make sure GDT is below 4GB space.
=> UefiCpuPkg/CpuDxe: Guarantee GDT is below 4GB

BaseTools/Source/Python/Ecc/Check.py
The Ecc tool checks the format of the include guard. This check is
currently done on all the names following the '#ifndef' statement.
It should only be done on the first include guard.
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3252
=> BaseTools/Ecc: Make Ecc only check first include guard

Maintainers.txt
msgid: <20210310185649.19801-1-lersek@redhat.com>
https://edk2.groups.io/g/devel/message/72637
https://listman.redhat.com/archives/edk2-devel-archive/2021-March/msg00384.html
~~~
Ref: https://bugzilla.tianocore.org/show_bug.cgi?id=2198
Ref: https://bugzilla.tianocore.org/show_bug.cgi?id=3077
Ref: https://bugzilla.tianocore.org/show_bug.cgi?id=3249
Generalize the current OVMF SEV subsystem entry, so that we can use it
for Intel TDX in the future, ensuring proper patch circulation for
reviews.
Cc: Brijesh Singh <brijesh.singh@amd.com>
Cc: Michael D …
=> [edk2-devel] [PATCH 0/2] Maintainers: create the "OvmfPkg: Confidential Computing" subsystem -- push

OvmfPkg/Library/X86QemuLoadImageLib/X86QemuLoadImageLib.c
msgid: <YFPJsaGzVWQxoEU4@martin-ThinkPad-T440p>
https://edk2.groups.io/g/devel/message/73028
https://listman.redhat.com/archives/edk2-devel-archive/2021-March/msg00795.html
~~~
The CommandLine and InitrdData may be set to NULL if the provided
size is too large. Because the zero page is mapped, this would not
cause an immediate crash but can lead to memory corruption instead.
This patch just adds validation and returns error if either allocation
has failed.
Ref: https://github.com/martinradev/edk2/commit/6c0ce748b97393240c006e24b73652f30e597a05
Signed-off-by: Martin Radev <martin.b.radev@gmail.com>
---
OvmfPkg/Library/X86QemuLoadImageLib/X86QemuLoadImageLib.c | 11 +++++++++++
1 file changed, 11 insertions(+)
~~~
=> [edk2-devel] [PATCH v1] OvmfPkg/X86QemuLoadImageLib: Handle allocation failure for CommandLine -- push

ShellPkg/Library/UefiShellDebug1CommandsLib/Pci.c
Bugzilla: 3262 (https://bugzilla.tianocore.org/show_bug.cgi?id=3262)
No need to print PCIe details while CapabilityId is 0xFFFF.
Limit the NextCapabilityOffset to PCI configuration space.
Signed-off-by: VincentX Ke <vincentx.ke@intel.com>
=> ShellPkg/Pci: Add valid check for PCI extended config space parser

CryptoPkg/Library/Include/openssl/opensslconf.h
Update openssl from 1.1.1g to 1.1.1j. Current OpenSSL version
1.1.1g contains the vulnerabilities of CVE-2021-23841 and
CVE-2021-23840. The related vulnerable API EVP_DecryptUpdate
are used in drivers.
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3266
Besides, the opensslconf.h automatically generated by process_files.pl.
Signed-off-by: Liu Wei <weix.c.liu@intel.com>
=> CryptoPkg/OpensslLib: Upgrade OpenSSL to 1.1.1j

OvmfPkg/AmdSev/AmdSevX64.dsc, OvmfPkg/Bhyve/BhyveX64.dsc, OvmfPkg/OvmfPkgIa32.dsc, OvmfPkg/OvmfPkgIa32X64.dsc, OvmfPkg/OvmfPkgX64.dsc, OvmfPkg/OvmfXen.dsc
https://bugzilla.tianocore.org/show_bug.cgi?id=3256
msgid: <20210324115819.605436-1-ross.burton@arm.com>
https://edk2.groups.io/g/devel/message/73207
https://listman.redhat.com/archives/edk2-devel-archive/2021-March/msg00954.html
~~~
GenFw will embed a NB10 section which contains the path to the input file,
which means the output files have build paths embedded in them.  To reduce
information leakage and ensure reproducible builds, pass --zero in release
builds to remove this information.
Ref: https://bugzilla.tianocore.org/show_bug.cgi?id=3256
Signed-off-by: Ross Burton <ross.burton@arm.com>
---
OvmfPkg/AmdSev/AmdSevX64.dsc | 1 +
OvmfPkg/Bhyve/BhyveX64.dsc   | 1 +
OvmfPkg/OvmfPkgIa32.dsc      | 1 +
OvmfPkg/OvmfPkgIa32X64.dsc   | 1 +
OvmfPkg/OvmfPkgX64.dsc       | 1 +
OvmfPkg/OvmfXen.dsc …
=> [edk2-devel] [PATCH v2] OvmfPkg: strip build paths in release builds -- push

MdeModulePkg/Bus/Ata/AtaAtapiPassThru/AhciMode.c, MdeModulePkg/Library/VariablePolicyHelperLib/VariablePolicyHelperLib.c
This change is to fix the compiler error (false report) on GCC49 release build.
=> MdeModulePkg: Initialize local variable value before they are used

UefiCpuPkg/PiSmmCommunication/PiSmmCommunicationPei.c
The comments in PiSmmCommunicationPei.c describe the whole memory
layout of the SMRAM regarding the SMM communication.
But SHA-1: 8b1d14939053b63d80355465649c50f9f391a64a
PiSmmCommunicationSmm: Deprecate SMM Communication ACPI Table
removed the code that produces the ACPI Table.
This change updates the accordingly comments.
=> UefiCpuPkg/SmmCommunication: Remove out-dated comments

MdePkg/Library/BaseLib/CpuDeadLoop.c
CpuPause() might allow the CPU to go into a lower power state
state while we spin.
On X86, CpuPause() executes a PAUSE instruction which the Intel
and AMD specs describe as follows:
Intel:
"PAUSE: An additional function of the PAUSE instruction is to reduce
the power consumed by a processor while executing a spin loop. A
processor can execute a spin-wait loop extremely quickly, causing the
processor to consume a lot of power while it waits for the resource it
is spinning on to become available. Inserting a pause instruction in a
spin-wait loop greatly reduces the processor?s power consumption."
AMD:
"PAUSE: Improves the performance of spin loops, by providing a hint to
the processor that the current code is in a spin loop. The processor
may use this to optimize power consumption while in …
=> MdePkg: use CpuPause() in CpuDeadLoop()

CryptoPkg/Private/Protocol/Crypto.h, MdePkg/Include/Protocol/HiiPopup.h, MdePkg/Include/Protocol/ResetNotification.h
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3287
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3286
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3285
Remove duplicate declarations of the following types that may
generate compiler warnings or errors:
* EFI_HII_POPUP_PROTOCOL
* EFI_RESET_NOTIFICATION_PROTOCOL
* EDKII_CRYPTO_RSA_GET_PUBLIC_KEY_FROM_X509
=> Remove duplicate type declarations in MdePkg and CryptoPkg

CryptoPkg/CryptoPkg.dsc
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3288
Simplify the DSC file by using the library mappings from
UnitTestFrameworkPkgTarget.dsc.inc to build the CryptoPkg
target based unit tests that run from the UEFI Shell.
=> CryptoPkg: Simplify DSC by using UnitTestFrameworkPkgTarget.dsc.inc

MdePkg/Include/Library/BaseLib.h, MdePkg/Library/BaseLib/BaseLib.inf, MdePkg/Library/BaseLib/Ia32/XSetBv.nasm, MdePkg/Library/BaseLib/X64/XSetBv.nasm
*v2: refine the coding format.
https://bugzilla.tianocore.org/show_bug.cgi?id=3284
This patch is to support XSETBV instruction so as to support
Extended Control Register(XCR) write.
Extended Control Register(XCR) read has already been supported
by below commit to support XGETBV instruction:
9b3ca509abd4e45439bbdfe2c2fa8780c950320a
Cc: Ni Ray <ray.ni@intel.com>
Cc: Yao Jiewen <jiewen.yao@intel.com>
Signed-off-by: Jiaxin Wu <Jiaxin.wu@intel.com>
Signed-off-by: Zhang Hongbin1 <hongbin1.zhang@intel.com>
=> MdePkg/BaseLib: Add support for the XSETBV instruction

MdeModulePkg/Library/PiDxeS3BootScriptLib/BootScriptSave.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3297
Rename the global variable mAcpiS3Enable to mS3BootScriptAcpiS3Enable
to avoid duplicate symbol errors from CLANGPDB tool change when
PiDxeS3BootScriptLib from the MdeModulePkg is linked with PiSmmCpuDxeSmm
from the UefiCpuPkg.
=> MdeModulePkg/PiDxeS3BootScriptLib: Rename mAcpiS3Enable to avoid dup symbol

ShellPkg/Library/UefiShellDebug1CommandsLib/SmbiosView/QueryTable.c
The SystemEnclosureTypeTable in QueryTable.c contained a couple
of errors: value 0x10 is "Lunch Box" not "Main Server Chassis", and
the Sub Notebook value was repeated as 0x13 when that entry is for
"SubChassis". The entries in-between needed adjusted.
=> ShellPkg: Fix smbiosview system enclosure type table

UefiCpuPkg/Library/CpuTimerLib/BaseCpuTimerLib.inf
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2832
Update LIBRARY_CLASS of BaseCpuTimerLib to remove the usage limitation,
otherwise the Base instance cannot be used in some types of modules.
=> UefiCpuPkg/CpuTimerLib: Update LIBRARY_CLASS of Base instance.

RedfishPkg/Redfish.fdf.inc, RedfishPkg/RedfishComponents.dsc.inc, RedfishPkg/RedfishDiscoverDxe/ComponentName.c, RedfishPkg/RedfishDiscoverDxe/RedfishDiscoverDxe.c, RedfishPkg/RedfishDiscoverDxe/RedfishDiscoverDxe.inf, RedfishPkg/RedfishDiscoverDxe/RedfishDiscoverInternal.h, RedfishPkg/RedfishDiscoverDxe/RedfishSmbiosHostInterface.c
BZ#:2906
EDK2 EFI Redfish Discover Protocol implementation. Refer to UEFI
spec 2.9 section 31.1.
=> RedfishPkg/RedfishDiscoverDxe: EFI Redfish Discover Protocol

RedfishPkg/Redfish.fdf.inc, RedfishPkg/RedfishComponents.dsc.inc, RedfishPkg/RedfishConfigHandler/RedfishConfigHandlerCommon.c, RedfishPkg/RedfishConfigHandler/RedfishConfigHandlerCommon.h, RedfishPkg/RedfishConfigHandler/RedfishConfigHandlerDriver.c, RedfishPkg/RedfishConfigHandler/RedfishConfigHandlerDriver.h, RedfishPkg/RedfishConfigHandler/RedfishConfigHandlerDriver.inf
BZ:2919
The driver is used to manage EDK2 Redfish Configuration Handler
Protocol installed by EDK2 Redfish feature drivers.
This is the EDK2 Redfish client driver written based on the EDK2
Redfish foundation to initialize EDK2 Redfish feature drivers.
EDK2 Redfish feature drivers are used to provision/consume/update
the firmware owns Redfish properties during system power on
initialization.
RedfishConfigHandlerCommon.c has the common code for the driver
instances used in different EDK2 boot phases or used by different
driver models in the future contribution.
Signed-off-by: Fan Wang <fan.wang@intel.com> …
=> RedfishPkg/RedfishConfigHandler: EDKII RedfishConfigHandler Protocol

UefiCpuPkg/PiSmmCpuDxeSmm/PiSmmCpuDxeSmm.h, UefiCpuPkg/PiSmmCpuDxeSmm/SmramSaveState.c
https://bugzilla.tianocore.org/show_bug.cgi?id=3283
msgid: <20210406195254.1018-2-kuqin12@gmail.com>
https://edk2.groups.io/g/devel/message/73742
https://listman.redhat.com/archives/edk2-devel-archive/2021-April/msg00156.html
~~~
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3283
Current SMM Save State routine does not check the number of bytes to be
read, when it comse to read IO_INFO, before casting the incoming buffer
to EFI_SMM_SAVE_STATE_IO_INFO. This could potentially cause memory
corruption due to extra bytes are written out of buffer boundary.
This change adds a width check before copying IoInfo into output buffer.
Signed-off-by: Kun …
=> [v2] UefiCpuPkg: PiSmmCpuDxeSmm: Check buffer size before accessing

BaseTools/Conf/tools_def.template
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3313
Change MAKE_FLAG to MAKE_FLAGS to match required name from
EDK II Build Specifications for VS20xx tool chains.
=> BaseTools/Conf: Fix MAKE_FLAGS typos in tools_def.template

MdeModulePkg/Library/VarCheckPolicyLib/VarCheckPolicyLib.c
DumpVariablePolicy() will return EFI_INVALID_PARAMETER if the Buffer
pointer is NULL and the indirect Size is anything but 0. Since this
TempSize was not being initialized it is very likely that this sequence
would not return the total buffer size as expected.
Bugzilla: https://bugzilla.tianocore.org/show_bug.cgi?id=3310
Signed-off-by: Bret Barkelew <bret.barkelew@microsoft.com>
=> MdeModulePkg: Initialize temp variable in VarCheckPolicyLib

SecurityPkg/Tcg/Tcg2Smm/Tcg2Smm.c
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=3277
Initializes the Status variable in TcgMmReadyToLock().
Fixes a Clang build failure:
Tcg2Smm.c - SecurityPkg\Tcg\Tcg2Smm\Tcg2Smm.c:254:7: error:
variable 'Status' is used uninitialized whenever 'if'
condition is false [-Werror,-Wsometimes-uninitialized]
Initializing this variable is required to address a practical
scenario in which the return value of TcgMmReadyToLock() is
undefined based on conditional evaluation in the function.
Cc: Kun Qin <kun.q@outlook.com>
Reviewed-by: …
=> SecurityPkg/Tcg2Smm: Initialize local Status variable

DynamicTablesPkg/Include/Library/TableHelperLib.h, DynamicTablesPkg/Library/Common/SsdtSerialPortFixupLib/SsdtSerialPortFixupLib.c, DynamicTablesPkg/Library/Common/TableHelperLib/TableHelper.c
According to ACPI 6.4, 6.1.5 _HID states:
- A valid PNP ID must be of the form "AAA####" where A is an uppercase
letter and # is a hex digit.
- A valid ACPI ID must be of the form "NNNN####" where N is an uppercase
letter or a digit ('0'-'9') and # is a hex digit.
Signed-off-by: Joey Gouly <joey.gouly@arm.com>
=> DynamicTablesPkg: add validation for PcdNonBsaCompliant16550SerialHid

.azurepipelines/templates/platform-build-run-steps.yml, .azurepipelines/templates/pr-gate-steps.yml, .gitmodules, ReadMe.rst
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3301
The cmocka repository https://git.cryptomilk.org/projects/cmocka.git
has gone down a few times in past year.  When it is down, it blocks
EDK II CI.  A mirror of this repository has been created in the
TianoCore organization at https://github.com/tianocore/edk2-cmocka.git
and uses a GitHub Action to auto-sync changes from
https://git.cryptomilk.org/projects/cmocka.git.
* Update .gitmodules to use https://github.com/tianocore/edk2-cmocka.git
instead of https://git.cryptomilk.org/projects/cmocka.git.
* Update README.rst to reference the COPYING file in
https://github.com/tianocore/edk2-cmocka.git with the cmocka license.
* Update Azure Pipelines YML files to remove a temporary workaround that
used an alternate GitHub mirror of cmocka. …
=> UnitTestFrameworkPkg: Use TianoCore mirror of cmocka repository

MdePkg/Include/Protocol/RestJsonStructure.h
In v2, BZ reference is added.
BZ#:3030
Fix the typo [in]/[out] of parameter DestroyStructure in
function header.
=> RedfishPkg/RestJsonStructureDxe: Fix typo in function header

BaseTools/Source/C/GenFw/Elf32Convert.c, BaseTools/Source/C/GenFw/Elf64Convert.c, BaseTools/Source/Python/GenFds/FdfParser.py, BaseTools/Source/Python/TargetTool/TargetTool.py, BaseTools/Source/Python/build/buildoptions.py, CryptoPkg/Library/Include/CrtLibSupport.h, MdePkg/Include/Uefi/UefiBaseType.h, MdePkg/Include/Uefi/UefiSpec.h
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3308
New in V2
=======
* Support all combinations of EFI_IMAGE_MACHINE_TYPE_SUPPORTED and
EFI_IMAGE_MACHINE_CROSS_TYPE_SUPPORTED.  Also update the way these
macros are supported that is compatible with all toolchains by introducing
two new optional #defines called EFI_IMAGE_MACHINE_TYPE_VALUE and
EFI_IMAGE_MACHINE_CROSS_TYPE_VALUE
* Missing copyright update in CryptoPkg
* Split BaseTools patch into 2 patches.  One for C code and one for Python.
The EDK II Build Specifications do not restrict the set of
CPU architectures that can be supported.  Remove places in
the EDK II that assume a fixed set of CPU architectures.
Remove build breaks in the following tools and DEFINES when a check against
a fixed set of CPU architectures is made.
* …
=> Remove fixed CPU architecture list assumptions V2

SecurityPkg/FvReportPei/FvReportPei.c
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=3333
In function InstallPreHashFvPpi, when calculating the size
of struct HASH_INFO, sizeof is used twice. This bug does
not lead to buffer overflow, "sizeof (HASH_INFO)" is 4,
whereas "sizeof (sizeof (HASH_INFO))" is 4 or 8.
Acked-by: Jiewen Yao <Jiewen.yao@intel.com>
=> SecurityPkg/FvReportPei: remove redundant sizeof

UefiCpuPkg/PiSmmCpuDxeSmm/X64/PageTbl.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3300
Current implementation of SetStaticPageTable routine in PiSmmCpuDxeSmm
driver will check a global variable mPhysicalAddressBits, and eventually
cap any value larger than 39 at 39.
This global variable is used in ConvertMemoryPageAttributes, which backs
SmmSetMemoryAttributes and SmmClearMemoryAttributes. Thus for a processor
that supports more than 39 bits width, trying to mark page table regions
higher than 39-bit will always return EFI_UNSUPPROTED.
This change updated the interface of SetStaticPageTable function to take
PhysicalAddressBits as an input parameter, in order to avoid changing/
accessing the global variable.
Reviewed-by: Laszlo Ersek …
=> UefiCpuPkg: PiSmmCpuDxeSmm: Not to Change Bitwidth During Static Paging

MdePkg/Include/Register/Intel/Cpuid.h
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3309
Define new element(Hybird) in CPUID_STRUCTURED_EXTENDED_FEATURE_FLAGS
(07h) data structure.
Reviewed: Ray Ni <ray.ni@intel.com>
=> MdePkg/Cpuid.h: Define new element in CPUID Leaf(07h) data structure.

edksetup.bat
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3341
Current CLANG_BIN env variable is set without double quote
around the LLVM default installation path string in windows,
which causes some CI build service cannot find the LLVM path
in windows.
This patch enhance it to add double quote around it.
Signed-off-by: Steven Shi <steven.shi@intel.com>
=> BaseTools: Add double quote around CLANG_BIN path string

Maintainers.txt
Message-Id: <a557b66c92d3e44dcd02db7ee3800d1f9fef81b4.1619102863.git.erdemaktas@google.com>
https://edk2.groups.io/g/devel/message/74372
https://listman.redhat.com/archives/edk2-devel-archive/2021-April/msg00786.html
~~~
Add 'Erdem Aktas' as a reviewer for OvmfPkg/Confidential Computing.
Signed-off-by: Erdem Aktas <erdemaktas@google.com>
---
Maintainers.txt | 1 +
1 file changed, 1 insertion(+)
~~~
=> [edk2-devel] [PATCH] Maintainers.txt: Add 'Erdem Aktas' to Confidential Computing reviewers -- push

BaseTools/Source/Python/AutoGen/ModuleAutoGenHelper.py, BaseTools/Source/Python/AutoGen/PlatformAutoGen.py
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3344
Veify that TAB_TOD_DEFINES_FAMILY key is present in ToolDef
dictionary before access.
=> BaseTools/Source/Python: Verify TAB_TOD_DEFINES_FAMILY key present

BaseTools/Source/Python/AutoGen/GenMake.py
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3353
Sort the tool definition content of generated makefiles to help
verify that makefile contents have not changed after BaseTools
code changes.
=> BaseTools/GenMake: Sort generated makefile tool definitions

EmulatorPkg/PlatformCI/.azurepipelines/Ubuntu-GCC5.yml
EmulatorPkg IA32 GCC builds are not working due to a failure
to install the i386 library dependencies in Ubuntu 18.04.
Temporarily disable these specific CI tests until the issue
can be resolved.
=> EmulatorPkg: Temp remove IA32 GCC CI builds

BaseTools/Source/Python/AutoGen/ModuleAutoGenHelper.py, BaseTools/Source/Python/AutoGen/PlatformAutoGen.py, BaseTools/Source/Python/Common/ToolDefClassObject.py, BaseTools/Source/Python/GenFds/GenFdsGlobalVariable.py, BaseTools/Source/Python/build/build.py
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3359
Update BaseTools to support new build targets, new tool chains,
and new architectures declared in DSC file [BuildOptions] sections.
* Do not expand * when tools_def.txt is parsed.  Only expand when
both tools_def.txt and DSC [BuilsOptions] sections have been parsed.
This also requires more flexible matching of tool keys that contain *
in tool key fields.
* Pre-scan the platform DSC file for FAMILY and TOOLCHAIN declarations
DSC in [BuildOptions] sections before the FAMILY and TOOLCHAIN need
to be known.
=> BaseTools/Source/Python: New Target/ToolChain/Arch in DSC [BuildOptions]

BaseTools/Source/Python/AutoGen/ModuleAutoGenHelper.py, BaseTools/Source/Python/AutoGen/PlatformAutoGen.py, BaseTools/Source/Python/build/build.py
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3359
* Save/Restore global state in GetToolChainAndFamilyFromDsc()
This resolves an issue where the multi-arch build for
UefiPayloadPkg would skip the autogen and build of IA32
components.
* Expand tools wildcard.
This resolves the issue where autogen makefile contents
would have a BUIDLRULEFAMILY tools definitions with an
'*' in the tool field that breaks the build from invalid
makefile syntax.
* Build rule family higher priority than Family.
This resolves the issue where flags were appended from
both the BUILDRULEFAMILY and FAMILY when only
BUILDRULEFAMILY should be appended when present.
Cc: …
=> BaseTools: Fix New Target/ToolChain/Arch in DSC [BuildOptions] issues

UnitTestFrameworkPkg/Library/UnitTestLib/Assert.c, UnitTestFrameworkPkg/Library/UnitTestResultReportLib/UnitTestResultReportLib.c, UnitTestFrameworkPkg/Library/UnitTestResultReportLib/UnitTestResultReportLibConOut.c, UnitTestFrameworkPkg/Library/UnitTestResultReportLib/UnitTestResultReportLibDebugLib.c
Sample unit tests in UnitTestFrameworkPkg hangs when running in OVMF/QEMU
environment. Build target is X64/GCC5. Fixing this issue by adding EFIAPI
to ReportPrint() function that use VA_ARGS.
Signed-off-by: Getnat Ejigu <getnatejigu@gmail.com>
=> UnitTestFrameworkPkg: Sample unit test hangs when running in OVMF/QEMU

ArmPkg/Drivers/ArmScmiDxe/ScmiDxe.c, ArmPkg/Include/Protocol/ArmScmiBaseProtocol.h
The SCP-firmware has moved to full support for SCMIv2 which means that
the base protocol can be either compliant with SCMI v1 or v2.
Allow any version between SCMI v1.0 and SCMI v2.0 to be compatible
with the current implementation.
Signed-off-by: Nicola Mazzucato <nicola.mazzucato@arm.com>
Tested-by: Sami Mujawar <sami.mujawar@arm.com>
=> ArmPkg: Update SCMI Base Protocol version to 0x20000

BaseTools/Source/Python/AutoGen/PlatformAutoGen.py, BaseTools/Source/Python/GenFds/GenFdsGlobalVariable.py, BaseTools/Source/Python/build/build.py
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3359
If the DSC file provides an override of a Guided tool path
and/or Guided tool GUID value, then make sure the one from the
DSC file is used if it is higher priority than the Guided tool
in the tools_def.txt file.  This makes the Guided tool used by
GenFds match the tool listed GuidedSectionTools.txt.
=> BaseTools: Fix DSC override of Guided tool

UefiCpuPkg/Library/MpInitLib/MpLib.c
https://bugzilla.tianocore.org/show_bug.cgi?id=3385
https://edk2.groups.io/g/devel/message/74878
https://listman.redhat.com/archives/edk2-devel-archive/2021-May/msg00194.html
msgid: c89bc819856d448360430c32cb3833a9667f987b.1620656694.git.thomas.lendacky@amd.com
~~~
BZ: https://bugzilla.tianocore.org/show_bug.cgi?id=3385
A VS2012 build fails with a cast conversion warning when the SEV-ES work
area PCD is cast as a pointer to the SEV_ES_AP_JMP_FAR type.
When casting from a PCD value to a pointer, the cast should first be done
to a UINTN and then to the pointer. Update the code to perform a cast to
a UINTN before casting to a pointer to the SEV_ES_AP_JMP_FAR type.
Cc: Rahul Kumar …
=> [edk2-devel] [PATCH] UefiCpuPkg/MpInitLib: Properly cast from PCD to SEV-ES jump table pointer -- push

BaseTools/Source/Python/Capsule/GenerateCapsule.py, BaseTools/Source/Python/Common/Uefi/Capsule/FmpCapsuleHeader.py
Add support for the ImageCapsuleSupport field, introduced in version 3
of the EFI_FIRMWARE_MANAGEMENT_CAPSULE_IMAGE_HEADER structure. This
structure member is used to indicate if the corresponding payload has
support for authentication and dependency.
Signed-off-by: Sughosh Ganu <sughosh.ganu@linaro.org>
=> BaseTools: Add support for version 3 of FMP Image Header structure

OvmfPkg/VirtioFsDxe/SimpleFsOpen.c, ShellPkg/Library/UefiShellCommandLib/UefiShellCommandLib.c
https://bugzilla.tianocore.org/show_bug.cgi?id=3228
https://edk2.groups.io/g/devel/message/75045
https://listman.redhat.com/archives/edk2-devel-archive/2021-May/msg00411.html
msgid: <20210511225616.5942-1-sergei@posteo.net>
~~~
Compiling for IA32 target with gcc-5.5.0 emits "maybe-uninitialized" warnings.
Compilation command: build -a IA32 -p OvmfPkg/OvmfPkgIa32.dsc -t GCC49
Sergei Dmitrouk (2):
ShellPkg/UefiShellCommandLib: suppress incorrect gcc warning
OvmfPkg/VirtioFsDxe: suppress incorrect gcc warnings
OvmfPkg/VirtioFsDxe/SimpleFsOpen.c                    | 11 +++++++++++
.../Library/UefiShellCommandLib/UefiShellCommandLib.c |  5 +++++
2 files changed, 16 insertions(+)
~~~
=> [edk2-devel] [PATCH v1 0/2] "maybe-uninitialized" warnings emitted by -- push

UefiCpuPkg/Library/CpuExceptionHandlerLib/CpuExceptionCommon.c
https://bugzilla.tianocore.org/show_bug.cgi?id=3373
https://edk2.groups.io/g/devel/message/75097
https://listman.redhat.com/archives/edk2-devel-archive/2021-May/msg00413.html
msgid: <40e55bf6563ed8ea4962a1219efbe1ab77a56cc4.1620919615.git.thomas.lendacky@amd.com>
~~~
BZ: https://bugzilla.tianocore.org/show_bug.cgi?id=3373
An update to expand the mExceptionNameStr array failed to add a comma
after original last entry, therefore causing the #CP name to have extra
incorrect characters and the remaining entries to be indexed incorrectly
(off by 1).
Add a comma after the "#CP" entry to resolve this issue.
Fixes: 5277540e37e88a1a69f9517c4ad895051b4b3ed3
Cc: Allen Wynn <Allen_Wynn@Dell.com>
Cc: …
=> [edk2-devel] [PATCH] UefiCpuPkg/CpuExceptionHandler: Add missing comma to exception name array -- push

BaseTools/Source/C/BrotliCompress/BrotliCompress.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2946
Currenly, when using the Brotli tool to compress data, the output
compressed binary file does not record complete compressed data
when size of input file is too large, which makes the data loss and
will trigger decompress-check issue.
The Brotli document mentioned:
The brotli tool use BrotliEncoderCompressStream method to compresses
input stream to output stream. Under some circumstances (e.g. lack of
output stream capacity) the BrotliEncoderOperation would require
several calls to BrotliEncoderCompressStream. The method must be
called again until both input stream is depleted and encoder has no
more output after the method is called.
This patch fixes this issue based on the Brotli document.
Cc: …
=> BaseTools/Brotli: Fix compressed data loss issue

BaseTools/Conf/tools_def.template
Some/all platforms are going to require EDK2 to build a device tree and
use it in the early stages of boot.
Reviewed-by: Abner Chang <abner.chang@hpe.com>
=> BaseTools: Add DTCPP_FLAGS for GCC5 RISCV64 toolchain

IntelFsp2Pkg/Tools/FspDscBsf2Yaml.py, IntelFsp2Pkg/Tools/GenCfgOpt.py
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=3395
This patch fixes the issue observed during
BSF file to YAML file conversion. It also
addresses the issue during multibyte array
data conversion check, for example the data
representation of 0xFFFF instead of 0xFF, 0xFF
would be thrown exception "Array size is not
proper" without this patch.
=> IntelFsp2Pkg: YAML script bug fix

MdeModulePkg/Library/UefiBootManagerLib/BmBoot.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3384
Currently, UefiBootManagerLib has the below assumption:
Assume the BootManagerMenuFile is in the same FV as the module links to this library.
It has some limitation now, so remove the assumption.
=> MdeModulePkg: Retrieve boot manager menu from any fv

CryptoPkg/Library/BaseCryptLib/Pk/CryptRsaPss.c, CryptoPkg/Library/BaseCryptLib/Pk/CryptRsaPssSign.c, MdeModulePkg/Bus/Pci/PciBusDxe/PciLib.c, ShellPkg/DynamicCommand/HttpDynamicCommand/Http.c
Compiling for IA32 target with gcc-5.5.0 emits "maybe-uninitialized" warnings.
Compilation command: build -a IA32 -p OvmfPkg/OvmfPkgIa32.dsc -t GCC49
Unlike other cases mentioned in
https://bugzilla.tianocore.org/show_bug.cgi?id=3228
these seem to be actual issues in the code.  Read patches for specifics.
=> Fix possible uninitialized uses

BaseTools/Source/Python/build/build.py
When build.by POSTBUILD handling section returns other than 0, set
ReturnCode to POSTBUILD_ERROR so build.py exits with return code other
than 0.
Fix for https://bugzilla.tianocore.org/show_bug.cgi?id=1977
Signed-off-by: Garrett Kirkendall <garrett.kirkendall@amd.com>
=> BaseTools: build: Set ReturnCode on POSTBUILD fail

MdeModulePkg/Universal/PlatformDriOverrideDxe/PlatDriOverrideLib.c
Code mistake, VariableIndex is smaller normally than buffer+buffersize
so should not break loop.
Signed-off-by: Walon Li <walon.li@hpe.com>
=> MdeModulePkg/PlatformDriOverrideDxe: Fix overflow condition check

MdeModulePkg/Universal/Variable/RuntimeDxe/VariableLockRequestToLock.c
https://bugzilla.tianocore.org/show_bug.cgi?id=3410
Message-Id: <20210521204037.11980-1-lersek@redhat.com>
https://listman.redhat.com/archives/edk2-devel-archive/2021-May/msg00764.html
https://edk2.groups.io/g/devel/message/75449
~~~
Commit a18a9bde36d2 ("MdeModulePkg/Variable/RuntimeDxe: Restore Variable
Lock Protocol behavior", 2020-12-15), for bug 3111, added two such sets of
debug messages that:
(a) are relevant for developers,
(b) yet should not necessarily poke end-users, because no functionality
suffers in practice.
Both message sets are in function VariableLockRequestToLock(): the first
is a generic interface deprecation warning; the second is the
double-locking situation, which we permit for compatibility (return status
EFI_SUCCESS).
Both message sets should be emitted with the …
=> [edk2-stable202105 PATCH] MdeModulePkg/VariableLock: downgrade compatibility warnings to DEBUG_WARN -- push

ArmPkg/Drivers/ArmGic/ArmGicLib.c
Bugzilla: 3415 (https://bugzilla.tianocore.org/show_bug.cgi?id=3415)
The GICv3 architecture supports up to 1020 ordinary interrupt
lines. The actual number of interrupts supported is described by the
ITLinesNumber field in the GICD_TYPER register. The total number of
implemented registers is normally calculated as
32*(ITLinesNumber+1). However, maximum value (0x1f) is a special case
since that would indicate that 1024 interrupts are implemented.
Add handling for this special case in ArmGicGetMaxNumInterrupts.
Signed-off-by: Andreas Sandberg <andreas.sandberg@arm.com>
Signed-off-by: Joey Gouly <joey.gouly@arm.com>
=> ArmPkg/ArmGic: Fix maximum number of interrupts in GICv3

Maintainers.txt
https://edk2.groups.io/g/devel/message/75116
https://listman.redhat.com/archives/edk2-devel-archive/2021-May/msg00432.html
msgid: <20210514114857.12286-1-lersek@redhat.com>
~~~
For distributing ArmVirtPkg patch review tasks better, move Sami Mujawar
from the "ArmVirtPkg: Kvmtool" section to the top-level "ArmVirtPkg"
section.
Given that "ArmVirtPkg: Kvmtool" remains without a specific "R" role,
remove "ArmVirtPkg: Kvmtool" altogether.
Cc: Julien Grall <julien@xen.org>
---
Maintainers.txt | …
=> [edk2-devel] [PATCH] Maintainers.txt: add Sami Mujawar as top-level ArmVirtPkg reviewer -- push

UefiCpuPkg/Library/MpInitLib/DxeMpLib.c, UefiCpuPkg/Library/MpInitLib/MpLib.c, UefiCpuPkg/Library/MpInitLib/PeiMpLib.c
https://bugzilla.tianocore.org/show_bug.cgi?id=3324
msgid <3cae2ac836884b131725866264e0a0e1897052de.1621024125.git.thomas.lendacky@amd.com>
https://edk2.groups.io/g/devel/message/75132
https://listman.redhat.com/archives/edk2-devel-archive/2021-May/msg00448.html
~~~
BZ: https://bugzilla.tianocore.org/show_bug.cgi?id=3324
The SEV-ES stacks currently share a page with the reset code and data.
Separate the SEV-ES stacks from the reset vector code and data to avoid
possible stack overflows from overwriting the code and/or data.
When SEV-ES is enabled, invoke the GetWakeupBuffer() routine a second time
to allocate a new area, below the reset vector and data.
Both the PEI and DXE versions of GetWakeupBuffer() are changed so that
when PcdSevEsIsEnabled is true, they will track the previous reset …
=> [edk2-devel] [PATCH v2] UefiCpuPkg/MpInitLib: Allocate a separate SEV-ES AP reset stack area -- push

IntelFsp2WrapperPkg/IntelFsp2WrapperPkg.dec, IntelFsp2WrapperPkg/Library/SecFspWrapperPlatformSecLibSample/SecFspWrapperPlatformSecLibSample.inf, IntelFsp2WrapperPkg/Library/SecFspWrapperPlatformSecLibSample/SecRamInitData.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3334
IntelFsp2WrapperPkg defines following PCDs:
PcdCpuMicrocodePatchAddress
PcdCpuMicrocodePatchRegionSize
PcdFlashMicrocodeOffset
But the PCD name caused confusion because UefiCpuPkg defines:
PcdCpuMicrocodePatchAddress
PcdCpuMicrocodePatchRegionSize
PcdCpuMicrocodePatchAddress in IntelFsp2WrapperPkg means the base
address of the FV that holds the microcode.
PcdCpuMicrocodePatchAddress in UefiCpuPkg means the address of the
microcode.
The relationship between the PCDs is:
IntelFsp2WrapperPkg.PcdCpuMicrocodePatchAddress
+  IntelFsp2WrapperPkg.PcdFlashMicrocodeOffset
== UefiCpuPkg.PcdCpuMicrocodePatchAddress
IntelFsp2WrapperPkg.PcdCpuMicrocodePatchRegionSize
-  IntelFsp2WrapperPkg.PcdFlashMicrocodeOffset
== …
=> IntelFsp2WrapperPkg: Remove microcode related PCDs

MdePkg/Include/Ppi/MmControl.h
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3397
Current Ppi/MmControl.h file has structure definition of "struct
_PEI_MM_CONTROL_PPI". This name mismatches with its definition in PI
Specification v1.7 (Errata) as "struct _EFI_PEI_MM_CONTROL_PPI".
In addition, field types "PEI_MM_ACTIVATE" and "PEI_MM_DEACTIVATE" used
in "struct _PEI_MM_CONTROL_PPI" mismatches with the definition of
"EFI_PEI_MM_ACTIVATE" and "EFI_PEI_MM_DEACTIVATE" in the PI spec.
This change fixes these mismatches by using the PI spec defined names.
Fixes: 6f33f7a262314af35e2b99c849e08928ea49aa55
Reviewed-by: Liming Gao …
=> MdePkg: MmControl: Fix function and structure definition mismatches

EmbeddedPkg/RealTimeClockRuntimeDxe/RealTimeClock.c
GetWakeupTime should return full time information, including
the daylight/timezone. Make use of the existing non-volatile
variables for that purpose. Moreover add an error checking
of possibly invalid parameters.
This partially fixes FWTS and SCT Set/GetWakeupTime tests on
Marvell platforms.
Signed-off-by: Marcin Wojtas <mw@semihalf.com>
=> EmbeddedPkg/RealTimeClockRuntimeDxe: Improve GetWakeupTime

MdeModulePkg/Bus/Pci/XhciDxe/XhciSched.c, MdeModulePkg/Bus/Pci/XhciPei/XhciSched.c
Patch sent at: https://edk2.groups.io/g/devel/message/75808
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3418
According to xhci spec, at USB packet level, a Control Transfer
consists of multiple transactions partitioned into stages: a
setup stage, an optional data stage, and a terminating status
stage. If Data Stage does not exist, the Transfer Type flag(TRT)
should be No Data Stage.
So if data length equals to 0, TRT is set to 0.
=> MdeModulePkg/Xhci: Fix TRT when data length is 0

OvmfPkg/Library/VirtioMmioDeviceLib/VirtioMmioDevice.h, OvmfPkg/Library/VirtioMmioDeviceLib/VirtioMmioDeviceFunctions.c
https://edk2.groups.io/g/devel/message/75937
https://listman.redhat.com/archives/edk2-devel-archive/2021-June/msg00054.html
msgid: <20210602045935.762211-1-kraxel@redhat.com>
~~~
This error was found while compiling VirtioMmioDeviceLib for X64
with the GCC5 toolchain, where EFIAPI makes a difference.
---
OvmfPkg/Library/VirtioMmioDeviceLib/VirtioMmioDevice.h          | 1 +
OvmfPkg/Library/VirtioMmioDeviceLib/VirtioMmioDeviceFunctions.c | 1 +
2 files changed, 2 insertions(+)
~~~
=> [edk2-devel] [PATCH v2 1/1] Add missing EFIAPI to VirtioMmioSetQueueAddress -- push

MdePkg/Library/BaseLib/Ia32/GccInlinePriv.c, MdePkg/Library/BaseLib/X64/GccInlinePriv.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3405
AsmReadSs() in Ia32/GccInlinePriv.c and X64/GccInlinePriv.c return the
DS segment selector value instead of SS.
Signed-off-by: Satoshi Tanda <tanda.sat@gmail.com>
=> MdePkg/BaseLib: Fix AsmReadSs() with GCC toolchain

BaseTools/Source/C/GenFw/Elf32Convert.c, BaseTools/Source/C/GenFw/Elf64Convert.c
Commit c6b872c updates GenFw base code attribute to find .text section.
With GCC49 tool chain, aslc file is compiled into elf image.
But, its text section has no CODE attribute. So, it can't be detected
by new GenFw tool.For this type file. its text section is not required.
Its data section will be converted to acpi table.
This fix is to remove assert check when the generated image is ACPI data.
Tested-by: Leif Lindholm <leif@nuviainc.com>
=> BaseTools GenFw: Fix regression issue to convert the image to ACPI data

OvmfPkg/README
https://edk2.groups.io/g/devel/message/76102
https://listman.redhat.com/archives/edk2-devel-archive/2021-June/msg00222.html
msgid: <20210605171712.GA16976@kaaira-HP-Pavilion-Notebook>
~~~
Fix typographical error in the OvmfPkg/README by correcting the 'an'
mistyped as 'and'.
Cc: mikuback@linux.microsoft.com
Cc: ray.ni@intel.com
Signed-off-by: Kaaira Gupta <kaaira7319@gmail.com>
---
Changes in v2:
- Rebase on commit ae4aa4a
- Improve commit message.
OvmfPkg/README | 2 +-
1 file changed, 1 insertion(+), 1 deletion(-)
~~~
=> [edk2-devel] [PATCH v2] OvmfPkg/README: Fix typo in README -- push

ShellPkg/Library/UefiShellDriver1CommandsLib/UefiShellDriver1CommandsLib.uni
Fix typo of 'specified' in UefiShellDriver1CommandsLib.
=> ShellPkg: Fix typo

OvmfPkg/PlatformCI/.azurepipelines/Windows-VS2019.yml
msgid: <20210609155731.10431-1-lersek@redhat.com>
https://edk2.groups.io/g/devel/message/76283
https://listman.redhat.com/archives/edk2-devel-archive/2021-June/msg00403.html
~~~
We currently require QEMU choco package version 2020.08.14 (from commit
3ab9d60fcbe7), in "OvmfPkg/PlatformCI/.azurepipelines/Windows-VS2019.yml".
Said package version references the following URLs:
https://community.chocolatey.org/packages/Qemu/2020.08.14#files
-> https://qemu.weilnetz.de/w32/qemu-w32-setup-20200814.exe
-> https://qemu.weilnetz.de/w64/qemu-w64-setup-20200814.exe
These URLs no longer work; Stefan Weil seems to have moved the binaries to
the following archive directories:
- https://qemu.weilnetz.de/w32/2020/
- https://qemu.weilnetz.de/w64/2020/
In theory, the old QEMU choco packages should be fixed …
=> [edk2-devel] [URGENT PATCH] OvmfPkg/PlatformCI: bump QEMU choco package version to 2021.5.5 -- push

NetworkPkg/IScsiDxe/IScsiCHAP.c, NetworkPkg/IScsiDxe/IScsiCHAP.h, NetworkPkg/IScsiDxe/IScsiDxe.inf, NetworkPkg/IScsiDxe/IScsiImpl.h, NetworkPkg/IScsiDxe/IScsiMisc.c, NetworkPkg/IScsiDxe/IScsiMisc.h
https://bugzilla.tianocore.org/show_bug.cgi?id=3356
Message-Id: <20210608121259.32451-1-lersek@redhat.com>
https://listman.redhat.com/archives/edk2-devel-archive/2021-June/msg00316.html
https://edk2.groups.io/g/devel/message/76198
~~~
Bugzilla: https://bugzilla.tianocore.org/show_bug.cgi?id=3356
Repo:     https://pagure.io/lersek/edk2.git
Branch:   iscsi_overflow_bz3356
The main goal of this series is to fix a remotely exploitable buffer
overflow in the IScsiHexToBin() function.
This posting corresponds to:
https://bugzilla.tianocore.org/show_bug.cgi?id=3356#c22
meaning that it corresponds to the v2 patches attached to, and tested
in,
https://bugzilla.tianocore.org/show_bug.cgi?id=3356#c17
and that it carries Phil's and Maciej's R-b's that were given up to
comment#22.
Today is the Public …
=> [edk2-devel] [PUBLIC edk2 PATCH v2 00/10] NetworkPkg/IScsiDxe: fix IScsiHexToBin() security and functionality bugs -- push

.pytool/Plugin/SpellCheck/SpellCheck.py
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3443
Existing implementation could modify class global data that causes
potential incorrect file mask to be used for execution of plugin.
This change switches class variable to be tuple so that it cannot be
accidently modified. Local usage of STANDARD_PLUGIN_DEFINED_PATHS is also
changed to copy to new list before modification.
Signed-off-by: Sean Brogan <sean.brogan@microsoft.com>
=> Pytool: SpellCheck: Fix incorrect file mask across package matrices

BaseTools/Source/C/GenFw/Elf32Convert.c, BaseTools/Source/C/GenFw/Elf64Convert.c
This is the fix of the regression issue at c6b872c6.
Based on ELF spec, readonly alloc section is .rodata section. It is used.
This fix is to add back original check logic for ELF section. Now,
the readonly alloc section and execute alloc section are regarded as .text.
=> BaseTools GenFw: Keep read only alloc section as text when convert ELF

ArmPkg/Include/IndustryStandard/ArmCache.h, ArmPkg/Include/Library/ArmLib.h, ArmPkg/Library/ArmLib/ArmLibPrivate.h, ArmPkg/Universal/Smbios/ProcessorSubClassDxe/ProcessorSubClass.c, ArmPkg/Universal/Smbios/ProcessorSubClassDxe/SmbiosProcessorAArch64.c, ArmPkg/Universal/Smbios/ProcessorSubClassDxe/SmbiosProcessorArm.c, ArmPkg/Universal/Smbios/ProcessorSubClassDxe/SmbiosProcessorArmCommon.c
Many of the cache definitions in ArmLibPrivate.h are being used outside
of ArmLib, in Universal/Smbios. Move them into ArmCache.h to make them
public, and remove the include of ArmLibPrivate.h from files in
Universal/Smbios.
=> ArmPkg: Move cache defs used in Universal/Smbios into ArmCache.h

UefiCpuPkg/Library/CpuCommonFeaturesLib/C1e.c, UefiCpuPkg/Library/CpuCommonFeaturesLib/MachineCheck.c, UefiCpuPkg/Library/CpuCommonFeaturesLib/Ppin.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3424
Processor location information check needs to updated
When Core 0 is disabled.
In C1e.c, change MSR_FEATURE_CONFIG to MSR_NEHALEM_POWER_CTL in comments
to match the correct MSR name.
Signed-off-by: Daoxiang Li <daoxiang.li@intel.com>
=> UefiCpuPkg/CpuCommonFeaturesLib: Correct the CPU location check

MdeModulePkg/Universal/BdsDxe/Bds.h, MdeModulePkg/Universal/BdsDxe/BdsDxe.inf, MdeModulePkg/Universal/BdsDxe/BdsEntry.c
Changed BdsEntry.c to use Variable Policy instead of Variable Lock
as Variable Lock will be Deprecated eventually
Signed-off-by: Kenneth Lautner <kenlautner3@gmail.com>
=> MdeModulePkg/BdsDxe: Update BdsEntry to use Variable Policy

UefiPayloadPkg/UefiPayloadEntry/UefiPayloadEntry.c, UefiPayloadPkg/UefiPayloadEntry/UefiPayloadEntry.h
Currently several DXE crash due to invalid memory resource settings.
The PciHostBridgeDxe which expects the MMCONF and PCI Aperature
to be EfiMemoryMappedIO, but currently those regions are (partly)
mapped as EfiReservedMemoryType.
coreboot and slimbootloader provide an e820 compatible memory map,
which doesn't work well with EDK2 as the e820 spec is missing MMIO regions.
In e820 'reserved' could either mean "DRAM used by boot firmware" or "MMIO
in use and not detectable by OS".
Guess Top of lower usable DRAM (TOLUD) by walking the bootloader provided
memory ranges. Memory types of RAM, ACPI and ACPI NVS below 4 GiB are used
to increment TOLUD and reserved memory ranges touching TOLUD at the base
are also assumed to be reserved DRAM, which increment TOLUD.
Then mark everything reserved …
=> UefiPayloadPkg/UefiPayloadEntry: Improve bootloader memrange parsing

UefiPayloadPkg/UefiPayloadEntry/UefiPayloadEntry.c
Previous it would hang in CpuDxe if DXE drivers are dispatched above 4GB.
Now remove the work around since the fixed in CpuDxe are merged.
=> UefiPayloadPkg/UefiPayloadEntry: Remove 4GB memory WA

.azurepipelines/templates/spell-check-prereq-steps.yml
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3445
Per update from Cspell tool, the minimal requirement of Cspell 5.x
regarding Node is 12 and above. This has caused multple Cspell failures
during CI build validation:
"Failed to process "**.c" TypeError: text.matchAll(...) is not a function
or its return value is not iterable"
This change updates the lowest required node version to 14.x to support
Cspell functionalities.
Reviewed-by: Sean Brogan …
=> Azurepipeline: SpellCheck: Enforce Node dependency to use version 14.x

CryptoPkg/Library/BaseCryptLib/RuntimeCryptLib.inf, CryptoPkg/Library/BaseCryptLib/SmmCryptLib.inf
Intel Platform utility Syscfg/sysfwupdt will trigger SMI
to enter BIOS interface. then BIOS invoke EncodePassword
in SMM mode to check password.
it's need sha384(in CryptSha512.c) in SMM mode.
the origin SmmCryptLib.lib size is 1389KB,
after changed, the size is 1391KB.
the origin RuntimeCryptLib.lib size is 911KB,
after changed,the size is 913KB.
in SmmCryptLib.inf and RuntimeCryptLib.inf,
change CryptSha512NULL.c to CryptSha512.c.
https://bugzilla.tianocore.org/show_bug.cgi?id=3423
Signed-off-by: xueshengfeng <xueshengfeng@byosoft.com.cn>
=> CryptoPkg/BaseCryptLib: Enabled CryptSha512 for Smm/Runtime drivers

OvmfPkg/Bhyve/BhyveX64.dsc, OvmfPkg/Bhyve/BhyveX64.fdf
https://edk2.groups.io/g/devel/message/76436
https://listman.redhat.com/archives/edk2-devel-archive/2021-June/msg00554.html
msgid: <20210612204340.52290-1-rebecca@bsdio.com>
~~~
TPM support hasn't been tested and any lines in the .dsc and .fdf files
that appear to show support are bogus. Remove them.
This fixes https://bugzilla.tianocore.org/show_bug.cgi?id=3354 .
---
OvmfPkg/Bhyve/BhyveX64.dsc | 64 --------------------
OvmfPkg/Bhyve/BhyveX64.fdf | 15 -----
2 files changed, 79 deletions(-)
~~~
=> [edk2-devel] [PATCH] OvmfPkg/Bhyve: clean up TPM_ENABLE remnants -- push

BaseTools/toolsetup.bat
Split is now a Python tool, so BaseTools\Bin\Win32\Split.exe no longer
exists. Remove the check for it from toolsetup.bat to prevent the
erroneous claim that the binary C tools are missing.
=> BaseTools: Remove check for Split.exe in toolset.bat

BaseTools/toolsetup.bat
The words "overwrite" and "overwriting" are one word and shouldn't have
hyphens.
=> BaseTools: Fix spelling of "overwrite" and "overwriting" in toolset.bat

BaseTools/toolsetup.bat
When using the in-source BaseTools, edksetup.bat will exit with an
ERRORLEVEL of 1 because the line in toolsetup.bat
"%PYTHON_COMMAND% -c "import edk2basetools" >NUL 2>NUL"
fails.
Ensure ERRORLEVEL is set to 0 when edksetup.bat or toolsetup.bat is
successfully run.
=> BaseTools: Reset ERRORLEVEL in toolsetup.bat after edk2basetools check

OvmfPkg/Library/GenericQemuLoadImageLib/GenericQemuLoadImageLib.c, OvmfPkg/Library/GenericQemuLoadImageLib/GenericQemuLoadImageLib.inf, OvmfPkg/Library/X86QemuLoadImageLib/X86QemuLoadImageLib.c, OvmfPkg/Library/X86QemuLoadImageLib/X86QemuLoadImageLib.inf, OvmfPkg/QemuKernelLoaderFsDxe/QemuKernelLoaderFsDxe.c
https://bugzilla.tianocore.org/show_bug.cgi?id=3457
https://edk2.groups.io/g/devel/message/77174
https://listman.redhat.com/archives/edk2-devel-archive/2021-June/msg01286.html
msgid: <20210628105110.379951-1-dovmurik@linux.ibm.com>
~~~
BZ: https://bugzilla.tianocore.org/show_bug.cgi?id=3457
In order to support measured SEV boot with kernel/initrd/cmdline, we'd
like to have one place that reads those blobs; in the future we'll add
the measurement and verification in that place.
We already have a synthetic filesystem (QemuKernelLoaderFs) which holds
three files: "kernel", "initrd", and "cmdline".  The kernel is indeed
read from this filesystem in LoadImage; but the cmdline (and the length
of initrd) are read from QemuFwCfgLib items.
This patch series first fixes two identical memory leak …
=> [edk2-devel] [PATCH v3 0/5] OvmfPkg: Use QemuKernelLoaderFs to read cmdline/initrd -- push

OvmfPkg/XenPlatformPei/Xen.c
http://mid.mail-archive.com/20210628132337.46345-1-anthony.perard@citrix.com
https://edk2.groups.io/g/devel/message/77183
https://listman.redhat.com/archives/edk2-devel-archive/2021-June/msg01297.html
~~~
From: Anthony PERARD <anthony.perard@citrix.com>
Unfortunately, Xen isn't ready to deal with mapping at the top of the
physical address space, so we relocate the mapping after the LAPIC
location.
See this thread about the issue with the mapping:
- https://lore.kernel.org/xen-devel/f8c4151a-6dac-d87c-ef46-eb35ada07bd9@suse.com/
The PhysicalAddressIdentityMapping() call isn't going to do anything
anymore since everything under 4GB is already mapped, but there is no
need to remove the call.
CC: Jan Beulich <JBeulich@suse.com>
CC: Andrew Cooper <andrew.cooper3@citrix.com>
Signed-off-by: …
=> [edk2-devel] [PATCH] OvmfPkg/XenPlatformPei: Relocate shared_info page mapping -- push

MdePkg/Include/IndustryStandard/IpmiNetFnChassis.h, MdePkg/Include/IndustryStandard/IpmiNetFnFirmware.h
Build error reported for missing structures IPMI_SET_BOOT_OPTIONS_RESPONSE,
EFI_IPMI_MSG_GET_BMC_EXEC_RSP, macro EFI_FIRMWARE_GET_BMC_EXECUTION_CONTEXT
EFI_FIRMWARE_BMC_IN_FULL_RUNTIME/EFI_FIRMWARE_BMC_IN_FORCED_UPDATE_MODE
when using edk2-platforms\Features\Intel\OutOfBandManagement\IpmiFeaturePkg
Rename EFI_IPMI_MSG_GET_BMC_EXEC_RSPB,
EFI_FIRMWARE_GET_BMC_EXECUTION_CONTEXT
EFI_FIRMWARE_BMC_IN_FORCED_UPDATE_MODE to
IPMI_MSG_GET_BMC_EXEC_RSPB,IPMI_GET_BMC_EXECUTION_CONTEXT
IPMI_BMC_IN_FORCED_UPDATE_MODE
Signed-off-by: Manickavasakam Karpagavinayagam <manickavasakamk@ami.com>
Reviewed-by: Isaac Oram <isaac.w.oram@intel.com>
=> MdePkg : Add IPMI Macro and Structure Defintions to resolve build errors

Maintainers.txt
Add Ray Ni as UefiPayloadPkg Maintainer.
Update Maurice Ma and Benjamin You as reviewers to continue support
UefiPayloadPkg patch review.
Reviewed-by: Benjamin You <benjamin.you@intel.com>
=> Maintainers.txt: Update Maintainers and reviewers for UefiPayloadPkg

UefiPayloadPkg/UefiPayloadEntry/UefiPayloadEntry.c, UefiPayloadPkg/UefiPayloadEntry/UniversalPayloadEntry.c
For non-universal payload, HandoffHobTable is used without initialization.
This patch fixed this failure.
=> UefiPayloadPkg: Fix the build failure

OvmfPkg/Bhyve/BhyveX64.dsc, OvmfPkg/Bhyve/BhyveX64.fdf, OvmfPkg/Bhyve/PlatformPei/Platform.c
mid: <20210705110842.14088-1-c.koehne@beckhoff.com>
https://edk2.groups.io/g/devel/message/77485
https://listman.redhat.com/archives/edk2-devel-archive/2021-July/msg00101.html
=> OvmfPkg/Bhyve USB/GPU passthrough improvements, v4 -- push

MdeModulePkg/Universal/Disk/PartitionDxe/Gpt.c
https://bugzilla.tianocore.org/show_bug.cgi?id=3474
https://edk2.groups.io/g/devel/message/77477
mid: <20210705093603.575707-1-ngompa@fedoraproject.org>
https://listman.redhat.com/archives/edk2-devel-archive/2021-July/msg00093.html
~~~
Per UEFI Spec 2.8 (UEFI_Spec_2_8_final.pdf, page 114)
5.2.3 Protective MBR
Table 20. Protective MBR Partition Record protecting the entire disk
The description for BootIndicator states the following:
> Set to 0x00 to indicate a non-bootable partition. If set to any
> value other than 0x00 the behavior of this flag on non-UEFI
> systems is undefined. Must be ignored by UEFI implementations.
Unfortunately, we have been incorrectly assuming that the
BootIndicator value must be 0x00, which leads to problems
when the 'pmbr_boot' flag is set on a disk containing …
=> [edk2-devel] [PATCH] MdeModulePkg/PartitionDxe: Ignore PMBR BootIndicator per UEFI spec -- push

UefiCpuPkg/Library/CpuExceptionHandlerLib/X64/Xcode5ExceptionHandlerAsm.nasm, UefiCpuPkg/PiSmmCpuDxeSmm/X64/SmmFuncsArch.c
When enter SMM exception, there will be a stack switch only if the IST
field of the interrupt gate is set. When CET shadow stack feature is
enabled, if there is a stack switch between SMM exception and SMM, the
shadow stack token busy bit needs to be cleared when return from SMM
exception to SMM. In UEFI BIOS, only page fault exception does the stack
swith when SMM shack guard feature is enabled. The condition of clear
shadow stack token busy bit should be SMM stack guard enabled, CET shadows
stack feature enabled and page fault exception.
The shadow stack token should be initialized by UINT64.
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3462
Signed-off-by: Sheng Wei <w.sheng@intel.com>
Cc: Laszlo Ersek …
=> UefiCpuPkg/ExceptionLib: Conditionally clear shadow stack token busy bit

MdeModulePkg/MdeModulePkg.ci.yaml, MdeModulePkg/Universal/RegularExpressionDxe/OnigurumaUefiPort.c, MdeModulePkg/Universal/RegularExpressionDxe/OnigurumaUefiPort.h
Memory buffer that is allocated by malloc() and realloc() will be
shifted by 8 bytes because Oniguruma keeps its memory signature. This 8
bytes shift is not handled while calling free() to release memory. Add
free() function to check Oniguruma signature before release memory
because memory buffer is not touched when using calloc().
Signed-off-by: Nickle Wang <nickle.wang@hpe.com>
=> MdeModulePkg/RegularExpressionDxe: Fix memory assert in FreePool()

.pytool/Plugin/SpellCheck/SpellCheck.py
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3454
On Linux the shell expands the wildcard paths and causes multiple files
to be missed. This change adds additional quotes to defer expansion in
order to bring parity in cspell result.
Signed-off-by: Sean Brogan <sean.brogan@microsoft.com>
=> Pytool: SpellCheck: Defer path expansion in cspell parameters

Maintainers.txt
I'm relinquishing all my roles listed in "Maintainers.txt", for personal
reasons.
My email address <lersek@redhat.com> remains functional.
To my understanding, my employer is working to assign others engineers to
the edk2 project (at their discretion).
Cc: Philippe Mathieu-Daud? <philmd@redhat.com>
Reviewed-by: Andrew Fish <afish@apple.com> …
=> Maintainers.txt: remove Laszlo Ersek's entries

.azurepipelines/templates/pr-gate-build-job.yml, .mergify/config.yml, BaseTools/Scripts/PatchCheck.py
* Removed FINISHED and FAILED states with 10 second delays
* Update PatchCheck.py to ignore commit message format issues
in merge commits added by Mergify
* Enable Mergify queue feature to support auto rebase when
'push' label is set and guarantee that all EDK II CI checks
are run before merging in changes with linear history.
* Use status checks configured in GitHub branch protections
* Allow non EDK II Maintainers to create a PR
Requires an EDK II Maintainer to accept the change and
request merge by adding 'push' label.  Only EDK II Maintainers
have ability to set/clear labels.
* Do not automatically close PRs for personal builds.
Cc: Bob Feng …
=> Mergify Enhancements

MdePkg/Include/Base.h
Add STATIC_ASSERT() macros to verify that the compiler is
configured correctly for the use of L'' and L"" strings.
=> MdePkg/Include: Add STATIC_ASSERT for L'' and L"" strings

BaseTools/Scripts/ConvertFceToStructurePcd.py
Currently, the ConvertFceToStructurePcd.py tool generate
StructurePcd dsc file with comments from UNI file including
non-ascii character. Following DSC spec, there should not have
non-ascii character in DSC file. This patch removes the non-ascii
character when adding the comment and changes the circle R to (R).
=> BaseTools: Remove non-ascii character of StructurePcd comment

.pytool/Plugin/EccCheck/EccCheck.py
From: Pierre Gondois <Pierre.Gondois@arm.com>
EccCheck currently makes some assumptions on its working
environment that prevent it from running it in other repositories.
For instance, the workspace is assumed to be pointing to the edk2
repository path, which can be wrong.
This patch-set aims to allow the EccCheck tool to run on the
edk2-platforms repository, with edk2 being a submodule of
edk2-platforms.
The changes can be seen at: https://github.com/PierreARM/edk2/commits/1628_Ecc_environment_paths_update_v2
=> Allow EccCheck to run on other repositories

UefiPayloadPkg/UefiPayloadEntry/PrintHob.c, UefiPayloadPkg/UefiPayloadEntry/UniversalPayloadEntry.c, UefiPayloadPkg/UefiPayloadEntry/UniversalPayloadEntry.inf
V1:
Universal Payload will consume Hobs from boot loader.
Dump all hobs in the Universal Payload entry.
V2:
Add function comments
V3:
minor change, for example Hobsize -> HobLength, SMBiosTable -> SmBiosTable
Signed-off-by: Thiyagu Kesavan Balakrishnan <thiyagux.kesavan.balakrishnan@intel.com>
=> UefiPayloadPkg: Dump hob information from boot loader

MdeModulePkg/Universal/Disk/RamDiskDxe/RamDiskDriver.c
**Patch sent at:** https://edk2.groups.io/g/devel/message/77723
**Cover letter:** https://edk2.groups.io/g/devel/message/77722
Sending this patch on behalf of Trammell, who asked me to do so, so that he doesn't have to set up git-send-email config.
See his PR: https://github.com/tianocore/edk2/pull/1810
Trammell Hudson (1):
RamDiskDxe: initialize list head before registering ram disk protocol
MdeModulePkg/Universal/Disk/RamDiskDxe/RamDiskDriver.c | 11 ++++++-----
1 file changed, 6 insertions(+), 5 deletions(-)
**Commit message:**
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=3483
This patch initializes the linked list RegisteredRamDisks in
RamDiskDxeEntryPoint before the registration of gEfiRamDiskProtocolGuid
with InstallMultipleProtocolInterfaces, allowing ramdisks to be created …
=> MdeModulePkg/RamDiskDxe: Init list head before registering RamDisk protocol

IntelFsp2Pkg/Library/BaseCacheLib/BaseCacheLib.inf, IntelFsp2Pkg/Library/BaseCacheLib/CacheLib.c
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=3485
CacheLib EfiProgramMtrr Function takes MTRR number as a input parameter,
in the function the parameter is defined as UINTN were as the caller
calling MTTR number in UINT32.
Signed-off-by: Ashraf Ali S <ashraf.ali.s@intel.com>
Cc: Digant H Solanki <digant.h.solanki@intel.com>
Cc: Sangeetha V <sangeetha.v@intel.com>
=> IntelFsp2Pkg: BaseCacheLib EfiProgramMtrr MtrrNumber Should be UINT32

UefiPayloadPkg/UefiPayloadPkg.dsc
PCD_DYNAMIC_AS_DYNAMICEX is recently added to Edk2, and it can treat
Dynamic PCD to Dynamic Ex PCD, which is Uefi Payload needs.
=> UefiPayloadPkg: Add PCD_DYNAMIC_AS_DYNAMICEX and set to True

ArmPlatformPkg/Scripts/Ds5/cmd_load_symbols.py, ArmPlatformPkg/Scripts/Ds5/console_loader.py
cmd_load_symbols.py can only load symbols from FV. Add the possibility to
use UEFI console output to calculate dll load address and send
add-symbol-file commands directly to ArmDS debugger
dll load address can't be used directly from UEFI output, see comment in
DebugPeCoffExtraActionLib: "This may not work correctly if you generate
PE/COFF directly as then the Offset would not be required".
1) Use objdump -S module.dll | grep <_ModuleEntryPoint> to get offset
in dll (offset)
2) Use Entrypoint=<address> from UEFI console output (entrypoint)
3) dll load address is (entrypoint)-(offset)
Signed-off-by: Artem Kopotev <artem.kopotev@arm.com>
Tested-by: Pierre Gondois <Pierre.Gondois@arm.com>
=> ArmPlatformPkg/Scripts: Infer dll load address from console output

MdePkg/Include/IndustryStandard/SmBios.h, ShellPkg/Library/UefiShellDebug1CommandsLib/SmbiosView/QueryTable.c
The following changes were addressed,
1. Smbios specs 3.4.0 table-51 bit5&6, these fields moved
from specific MemoryArrayLocationCXLFlexbus10AddonCard
to generic MemoryArrayLocationCXLAddonCard
to address both CXL1.0 and 2.0 CXL revisions.
2. Smbios specs 3.4.0 table-79, The memory technology name changed
from MemoryTechnologyIntelPersistentMemory
to MemoryTechnologyIntelOptanePersistentMemory.
Signed-off-by: Thotala Gopi <gopi.thotala@intel.com>
=> MdePkg/Include: Smbios Specification 3.4.0 changes

MdeModulePkg/Universal/PCD/Dxe/Service.c
**Cover-letter:** https://edk2.groups.io/g/devel/message/77759
When reaching the assert, it can't be debugged because the PCD is
unknown. Therefore the PCD's GUID and token number should be printed.
=> MdeModulePkg PCD: Print which PCD was unable to be found

BaseTools/Source/C/GenFw/Elf64Convert.c
Ref: https://bugzilla.tianocore.org/show_bug.cgi?id=3459
This patch adds support for R_RISCV_PCREL_LO12_S relocation type.
The logic is same as existing R_RISCV_PCREL_LO12_I relocation
except the difference between load vs store instruction formats.
Signed-off-by: Sunil V L <sunilvl@ventanamicro.com>
Cc: Pete Batard <pete@akeo.ie>
Reviewed-by: Daniel Schaefer <daniel.schaefer@hpe.com>
Acked-by: Abner Chang <abner.chang@hpe.com>
=> BaseTools GenFw: Add support for R_RISCV_PCREL_LO12_S relocation

MdeModulePkg/Core/PiSmmCore/MemoryAttributesTable.c
1. Reduce the debug message during boot.
2. Update SmmCore debug level of MemoryAttributesTable align to DxeCore.
Signed-off-by: Yang Gang <yanggang@byosoft.com.cn>
=> MdeModulePkg PiSmmCore: Change MemoryAttributes message to DEBUG_VERBOSE

Maintainers.txt
=> Maintainers.txt: Add Jiewen Yao as OvmfPkg Maintainer

MdeModulePkg/Application/CapsuleApp/CapsuleOnDisk.c
Fix typo in error message in CapsuleApp.
Signed-off-by: Seonghyun Park <shpark1@protonmail.com>
=> MdeModulePkg/CapsuleApp: Fix typo in error message

BaseTools/Source/Python/AutoGen/UniClassObject.py, BaseTools/Source/Python/UPT/Library/UniClassObject.py, BaseTools/Source/Python/build/build.py, BaseTools/Tests/RunTests.py
This addresses some python DeprecationWarnings that are popping up with python 3.10
Signed-off-by: Cole Robinson <crobinso@redhat.com>
=> BaseTools: fix some python DeprecationWarnings

BaseTools/Source/Python/Split/Split.py
In Split tool, the copy file actions only need to
copy file content but not need to copy file metadata.
copy2() copies the file metadata that causes split
unit test failed under edk2-basetools CI environment.
So this patch changes the call of copy2() to copyfile().
=> BaseTools: use shutil.copyfile instead shutil.copy2

MdeModulePkg/Include/Guid/BootDiscoveryPolicy.h, MdeModulePkg/Library/BootDiscoveryPolicyUiLib/BootDiscoveryPolicyUiLib.c, MdeModulePkg/Library/BootDiscoveryPolicyUiLib/BootDiscoveryPolicyUiLib.inf, MdeModulePkg/Library/BootDiscoveryPolicyUiLib/BootDiscoveryPolicyUiLib.uni, MdeModulePkg/Library/BootDiscoveryPolicyUiLib/BootDiscoveryPolicyUiLibStrings.uni, MdeModulePkg/Library/BootDiscoveryPolicyUiLib/BootDiscoveryPolicyUiLibVfr.Vfr, MdeModulePkg/MdeModulePkg.dec, MdeModulePkg/MdeModulePkg.dsc
(https://edk2.groups.io/g/devel/message/78512)
This patchset extends Boot Maintenance Menu and allows to select Boot Discovery Policy. Raspberry Pi platforms uses the variable to connect specified class of devices on boot. This patchset also removes efdc159e which has similar functionality.
Discussion on design can be found at:
https://edk2.groups.io/g/rfc/topic/rfc_boot_discovery_policy/82450628
Changes since v1:
- make 'Connect All' (0x2) default value for PcdBootDiscoveryPolicy
- initialize BootDiscoveryPolicy variable in platform code, if not found
Changes since v2:
- add missing local variable initialization
Changes since v3:
- add description to PcdBootDiscoveryPolicy
Changes since v4:
- fixed coding style
- add module to MdeModulePkg.dsc
**Commit message:**
This …
=> MdeModulePkg: Add BootDiscoveryPolicyUiLib.

Maintainers.txt
Add Abner Chang as the maintainer of EmbeddedPkg/
Add Daniel Schaefer as the reviewer of EmbeddedPkg/
Reviewed-by: Ard Biesheuvel <ardb+tianocore@kernel.org>
Reviewed-by: Andrew Fish <afish@apple.com>
=> Maintainers.txt: Add new maintainer and reviewer to EmbeddedPkg/

EmbeddedPkg/Include/libfdt_env.h
OpenSBI has started using those in v0.9. See:
https://github.com/riscv/opensbi/blob/v0.9/lib/utils/fdt/fdt_domain.c
Cc: Anup Patel <anup.patel@wdc.com>
Acked-by: Leif Lindholm <leif@nuviainc.com>
=> EmbeddedPkg/libfdt: Add strcmp and strncpy to libfdt_env.h

UefiCpuPkg/Include/Library/CpuCacheInfoLib.h, UefiCpuPkg/Library/CpuCacheInfoLib/CpuCacheInfoLib.c, UefiCpuPkg/Library/CpuCacheInfoLib/DxeCpuCacheInfoLib.inf, UefiCpuPkg/Library/CpuCacheInfoLib/InternalCpuCacheInfoLib.h, UefiCpuPkg/Library/CpuCacheInfoLib/PeiCpuCacheInfoLib.inf
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3508
Sort the CpuCacheInfo array by CPU package ID, core type, cache level
and cache type.
=> UefiCpuPkg/CpuCacheInfoLib: Sort CpuCacheInfo array

UefiPayloadPkg/UefiPayloadEntry/UniversalPayloadEntry.c
Fix the non-ascii character in UniversalPayloadEntry.c
Signed-off-by: DunTan <dun.tan@intel.com>
=> UefiPayloadPkg: Fix the non-ascii character in UniversalPayloadEntry.c

MdePkg/Include/IndustryStandard/Acpi.h, MdePkg/Include/IndustryStandard/Acpi64.h, MdePkg/MdePkg.ci.yaml
This patch series introduces a header file for the latest version of the
ACPI 6.4 specification, January 2021. This header contains all updates
to the ACPI specification in addition to addressing a few small errors
from the previous ACPI header files.
=> Add ACPI 6.4 header file

RedfishPkg/Include/Library/RedfishCrtLib.h, RedfishPkg/PrivateLibrary/RedfishLib/edk2libredfish/include/redfishPayload.h, RedfishPkg/PrivateLibrary/RedfishLib/edk2libredfish/include/redfishService.h, RedfishPkg/PrivateLibrary/RedfishLib/edk2libredfish/include/redpath.h, RedfishPkg/RedfishPkg.ci.yaml, RedfishPkg/RedfishPkg.dec
Public the header file, move RefishCrtLib.h from PrivateInclude/
to Include/.
RefishCrtLib.lib will be public later. (Moved out from PrivateLibrary/)
=> RedfishPkg/RefishCrtLib: Public RefishCrtLib

MdeModulePkg/Library/UefiSortLib/UnitTest/UefiSortLibUnitTest.c, MdeModulePkg/Library/UefiSortLib/UnitTest/UefiSortLibUnitTest.inf, MdeModulePkg/MdeModulePkg.ci.yaml, MdeModulePkg/Test/MdeModulePkgHostTest.dsc
Adding two unit test case for UefiSortLib. One is a test on
sorting an array of UINT32 by using PerformQuickSort, another
is a test on comparing the same buffer by using StringCompare.
Add 'main' function name to ECC exception list to avoid ECC
error.
=> MdeModulePkg/UefiSortLib:Add UefiSortLib unit test

MdeModulePkg/Universal/PCD/Pei/Pcd.c
https://bugzilla.tianocore.org/show_bug.cgi?id=3525
After PciSegmentLib using Dynamic PCD for Pcie base address such
long delay found in FSP. The root cause is some of the PCD service
PPIs not shadowed to memory and flash cache may have been disabled
in NotifyPhase stage. Solution is to shadow all PCD service PPIs
to memory.
Signed-off-by: GregX Yeh <gregx.yeh@intel.com>
=> MdeModulePkg PCD: Reinstall PCD service PPIS when memory available

UefiCpuPkg/Library/CpuCacheInfoLib/CpuCacheInfoLib.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3265
Correct the logical for identifying "Direct mapped" cache type.
=> UefiCpuPkg/CpuCacheInfoLib: Correct logical for identifying cache type

CryptoPkg/Library/BaseCryptLib/Pk/CryptTs.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3550
Function ConvertAsn1TimeToEfiTime initializes timestamp to zeroes with SetMem, but the actual parameters are out of order.
The result is the SetMem operation has no effect. The fix is to put the actual parameters in the correct order.
Signed-off-by: Chris Stewart <chris.stewart@hp.com>
CC: Jiewen Yao <jiewen.yao@intel.com>
CC: Jian J Wang <jian.j.wang@intel.com>
CC: Xiaoyu Lu <xiaoyux.lu@intel.com>
CC: Guomin Jiang <guomin.jiang@intel.com>
=> CryptoPkg: BaseCryptLib fix incorrect param order

OvmfPkg/Include/IndustryStandard/Virtio10.h, OvmfPkg/Library/VirtioMmioDeviceLib/VirtioMmioDevice.c, OvmfPkg/Library/VirtioMmioDeviceLib/VirtioMmioDevice.h, OvmfPkg/Library/VirtioMmioDeviceLib/VirtioMmioDeviceFunctions.c
This little series adds virtio 1.0 support for the virtio-mmio
transport.  For the mmio transport the difference between 0.9.5 and 1.0
is rather small (when compared to the pci transport), it is just a bunch
of new registers for the changed virtio queue initialization.  So the
patch series is small too ...
v2 changes:
- Added review tags for patches #1 + #2.
- Add a patch to make sure we have a valid QueueNum.
- Add a patch to support all 64 virtio 1.0 feature bits.
v3 changes:
- Add #defines for virtio-mmio version field.
v4 changes:
- split patches into smaller ones.
- enable virtio 1.0 at the end when everything is in place.
v5 changes:
- Added review tags.
- Fixed 32bit arm build failure.
=> add support for virtio-mmio 1.0

MdeModulePkg/Universal/EbcDxe/EbcDebugger/Edb.c, MdeModulePkg/Universal/EbcDxe/EbcDebugger/EdbCmdBreakpoint.c, MdeModulePkg/Universal/EbcDxe/EbcDebugger/EdbHook.c
Patch sent at: https://edk2.groups.io/g/devel/message/79317
Assignments of structure values cause the emission of memcpy()
intrinsics by the CLANG38 toolchain. Substitute the assignments with
calls to CopyMem() to mitigate the issue.
Cc: Vitaly Cheptsov <vit9696@protonmail.com>
Signed-off-by: Marvin H?user <mhaeuser@posteo.de>
=> MdeModulePkg/EbcDxe: Mitigate memcpy intrinsics

MdeModulePkg/Include/Guid/BootDiscoveryPolicy.h
Patch sent at: https://edk2.groups.io/g/devel/message/79471
This variable is needed to track the change to
BootDiscoveryPolicy variable. Boot options should
be refreshed only if BootDiscoveryPolicy has been
changed.
Signed-off-by: Grzegorz Bernacki <gjb@semihalf.com>
Reviewed-by: Samer El-Haj-Mahmoud <Samer.El-Haj-Mahmoud@arm.com>
Acked-by: Hao A Wu <hao.a.wu@intel.com>
=> MdeModulePkg: Add BootDiscoveryPolicyOld variable.

MdeModulePkg/Bus/Pci/NvmExpressDxe/NvmExpressHci.c, MdePkg/Include/IndustryStandard/Nvme.h
**Cover-letter:** https://edk2.groups.io/g/devel/message/79565
MdePkg:Update IndustryStandard/Nvme.h with Nvme amdin controller data
Add the definition of Nvme total capacity in Nvme structure.
zhoucheng (2):
MdePkg:Update IndustryStandard/Nvme.h with Nvme amdin controller data
MdeModulePkg:Increase Nvme capacity display
MdePkg/Include/IndustryStandard/Nvme.h             | 11 ++++++++++-
MdeModulePkg/Bus/Pci/NvmExpressDxe/NvmExpressHci.c |  2 ++
2 files changed, 12 insertions(+), 1 deletion(-)
Patches are sent at:
https://edk2.groups.io/g/devel/message/79564
https://edk2.groups.io/g/devel/message/79563
=> Push nvme capacity

ArmPkg/Library/PlatformBootManagerLib/PlatformBm.c, ArmPkg/Library/PlatformBootManagerLib/PlatformBootManagerLib.inf
This commit adds code which check BootDiscoveryPolicy variable and
calls Boot Policy Manager Protocol to connect device specified by
the variable. To enable that mechanism for platform
EfiMdeModulePkgTokenSpaceGuid.PcdBootDiscoveryPolicy PCD must be
added to DSC file and BootDiscoveryPolicyUiLib should be added to
UiApp libraries.
Signed-off-by: Grzegorz Bernacki <gjb@semihalf.com>
Reviewed-by: Sunny Wang <sunny.wang@arm.com>
=> ArmPkg: Enable boot discovery policy for ARM package.

OvmfPkg/OvmfXen.dsc, OvmfPkg/OvmfXen.fdf
Without QemuKernelLoaderFsDxe, QemuLoadKernelImage() couldn't download
the kernel, initrd, and kernel command line from QEMU's fw_cfg.
Ref: https://bugzilla.tianocore.org/show_bug.cgi?id=3574
Signed-off-by: Gary Lin <gary.lin@hpe.com>
Acked-by: Anthony PERARD <anthony.perard@citrix.com>
Tested-by: Jim Fehlig <jfehlig@suse.com>
=> OvmfPkg/OvmfXen: add QemuKernelLoaderFsDxe

UefiCpuPkg/PiSmmCpuDxeSmm/PiSmmCpuDxeSmm.c, UefiCpuPkg/PiSmmCpuDxeSmm/SmmProfile.c
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=3584
Function AsmCpuid should first check the value for Basic CPUID Information.
The fix is to update the mPatchCetSupported judgment statement.
Signed-off-by: Wenxing Hou <wenxing.hou@intel.com>
Cc: Eric Dong   <eric.dong@intel.com>
Cc: Ray Ni      <ray.ni@intel.com>
Cc: Sheng W     <w.sheng@intel.com>
Cc: Yao Jiewen  <jiewen.yao@intel.com>
=> UefiCpuPkg/PiSmmCpuDxeSmm: Update mPatchCetSupported set condition

UefiPayloadPkg/UefiPayloadEntry/MemoryAllocation.c
UefiPayloadEntry's AllocatePool() applies the "sizeof" operator to
HOB index rather than the HOB header structure. This yields 4 Bytes
compared to the 8 Bytes the structure header requires. Fix the call
to allocate the required space instead.
Cc: Vitaly Cheptsov <vit9696@protonmail.com>
Signed-off-by: Marvin H?user <mhaeuser@posteo.de>
=> UefiPayloadPkg/UefiPayloadEntry: Fix memory corruption

MdeModulePkg/Core/PiSmmCore/SmramProfileRecord.c, MdeModulePkg/Include/Guid/MemoryProfile.h
The legacy codebase allowed SMM images to be registered for profiling
from DXE. Support for this has been dropped entirely, so remove the
remaining handlers.
Cc: Vitaly Cheptsov <vit9696@protonmail.com>
Signed-off-by: Marvin H?user <mhaeuser@posteo.de>
=> MdeModulePkg/PiSmmCore: Drop deprecated image profiling commands

UefiCpuPkg/PiSmmCpuDxeSmm/SmramSaveState.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2956
In functions ReadSaveStateRegisterByIndex and WriteSaveStateRegister:
* check width > 4 instead of >= 4 when writing upper 32 bytes.
- This improves the code but will not affect functionality.
Signed-off-by: Mark Wilson <Mark.Wilson@amd.com>
=> UefiCpuPkg: Clean up save state boundary checks and comments.

MdeModulePkg/Universal/HiiDatabaseDxe/ConfigRouting.c
As the if statement outside has confirmed that
BlockData->Name == NULL, so the if statement inside
is always false.
=> MdeModulePkg/HiiDatabaseDxe:remove dead code block

MdeModulePkg/Universal/Disk/RamDiskDxe/RamDiskProtocol.c
Patch sent at: https://edk2.groups.io/g/devel/message/79960
Fix a typo of "memory" in a debug message in RamDiskProtocol.c.
=> MdeModulePkg: Fix typo of "memory" in RamDiskDxe debug message

Maintainers.txt
Patch sent at: https://edk2.groups.io/g/devel/message/79885
Remove Hao A Wu as the MdeModulePkg maintainer.
Add Liming Gao as the MdeModulePkg maintainer.
Remove Hao A Wu as the MdeModulePkg: Firmware Update modules reviewer.
Remove Hao A Wu as the MdeModulePkg: Serial modules reviewer.
Signed-off-by: Hao A Wu <hao.a.wu@intel.com>
=> Maintainers.txt: Update maintainer/reviewer roles in MdeModulePkg

SecurityPkg/Tcg/MemoryOverwriteControl/TcgMor.c
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=3605
The error message is missing the argument for the status code
print specifier.
=> SecurityPkg/MemoryOverwriteControl: Add missing argument to DEBUG print

OvmfPkg/OvmfXen.dsc
VerifyBlob() has been added recently to QemuKernelLoaderFsDxe, also
QemuKernelLoaderFsDxe has been added recently to OvmfXen but without an
implementation of VerifyBlob().
Fix this by adding the same runes that have been added to
OvmfPkgX64.dsc.
Fixes: 9f3eda177a4b ("OvmfPkg/OvmfXen: add QemuKernelLoaderFsDxe")
Signed-off-by: Anthony PERARD <anthony.perard@citrix.com>
=> OvmfPkg/OvmfXen: Fix build with QemuKernelLoaderFsDxe

SecurityPkg/Include/Library/TpmPlatformHierarchyLib.h, SecurityPkg/Library/PeiDxeTpmPlatformHierarchyLib/PeiDxeTpmPlatformHierarchyLib.c, SecurityPkg/Library/PeiDxeTpmPlatformHierarchyLib/PeiDxeTpmPlatformHierarchyLib.inf, SecurityPkg/SecurityPkg.dec, SecurityPkg/SecurityPkg.dsc, SecurityPkg/Tcg/Tcg2PlatformDxe/Tcg2PlatformDxe.c, SecurityPkg/Tcg/Tcg2PlatformDxe/Tcg2PlatformDxe.inf, SecurityPkg/Tcg/Tcg2PlatformPei/Tcg2PlatformPei.c, SecurityPkg/Tcg/Tcg2PlatformPei/Tcg2PlatformPei.inf
This series imports code from the edk2-platforms project related to
disabling the TPM2 platform hierarchy in Ovmf. It addresses the Ovmf
aspects of the following bugs:
https://bugzilla.tianocore.org/show_bug.cgi?id=3510
https://bugzilla.tianocore.org/show_bug.cgi?id=3499
I have patched the .dsc files and successfully test-built with most of
them. Some I could not build because they failed for other reasons
unrelated to this series.
I tested the changes with QEMU on x86 following the build of
OvmfPkgX64.dsc.
Neither one of the following commands should work anymore on first
try when run on Linux:
With IBM tss2 tools:
tsshierarchychangeauth -hi p -pwdn newpass
With Intel tss2 tools:
tpm2_changeauth -c platform newpass
Regards,
Stefan
Only SecurityPkg change is merged, because we need more …
=> Disable the TPM2 platform hierarchy

MdeModulePkg/Core/Pei/Dispatcher/Dispatcher.c, MdeModulePkg/Core/Pei/PeiMain.h
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=3512
This patch series contains three patches. The first two are for
relatively minor improvments - a typo fix in function descriptions
and changing the error level of a debug print. The third patch
fixes a pointer size mismatch.
=> MdeModulePkg/Core/Pei: Migration improvements and fixes

ArmPkg/Universal/Smbios/ProcessorSubClassDxe/SmbiosProcessorArmCommon.c
According to SMBIOS 3.4, section 7.5.3.3 ARM64-class CPUs, if
SMCCC_ARCH_SOC_ID is supported, the first DWORD is the JEP-106 code and
the second DWORD is the SoC revision value. But in the current
implementation, they are set in reverse. This patch is to correct it.
Cc: Rebecca Cran <rebecca@nuviainc.com>
Reviewed-by: Rebecca Cran <rebecca@nuviainc.com>
Acked-by: Leif Lindholm <leif@nuviainc.com>
=> ArmPkg/ProcessorSubClassDxe: Fix the format of ProcessorId

UefiCpuPkg/SecCore/SecCoreNative.inf, UefiCpuPkg/UefiCpuPkg.dsc
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=3492
Currently SecCore.inf having the resetvector code under IA32. if the
user wants to use both SecCore and UefiCpuPkg ResetVector it's not
possible, since SecCore and ResetVector(VTF0.INF/ResetVector.inf)
are sharing the same GUID which is BFV. to overcome this issue we can
create the Duplicate version of the SecCore.inf as SecCoreNative.inf
which contains pure SecCore Native functionality without resetvector.
SecCoreNative.inf should have the Unique GUID so that it can be used
along with UefiCpuPkg ResetVector in there implementation.
Cc: Debkumar De <debkumar.de@intel.com>
Cc: Harry Han <harry.han@intel.com>
Cc: Catharine West <catharine.west@intel.com> …
=> UefiCpuPkg: SecCoreNative without ResetVector

IntelFsp2WrapperPkg/IntelFsp2WrapperPkg.dec
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3632
PcdFspModeSelection will be used to set FSP mode.
Make PcdFspModeSelection dynamic and set it accordingly.
Signed-off-by: Zhang Xiaoqiang <xiaoqiang.zhang@intel.com>
=> IntelFsp2WrapperPkg: Make PcdFspModeSelection dynamic

OvmfPkg/Include/WorkArea.h, OvmfPkg/OvmfPkg.dec
SEC checks in IsSevGuest if the PCD defined WorkAreaHeader size
matches the size of the WorkAreaHeader struct definition. Set a
default value for the PCD to avoid unnecessary DSC/FDF file
changes in all OVMF DSC/FDF files.
Signed-off-by: Corvin Köhne <c.koehne@beckhoff.com>
=> OvmfPkg: set a default value for the WorkAreaHeader PCD

EmbeddedPkg/EmbeddedPkg.dec, EmbeddedPkg/Library/AndroidBootImgLib/AndroidBootImgLib.c, EmbeddedPkg/Library/AndroidBootImgLib/AndroidBootImgLib.inf
Added support for using loadfile2 approach for passing ramdisk to linux.                                                                             
Created patch series for general error handling improvments based on                                                                                 
review feedback.                                                                                                                                     
If ACPI tables are in system table or PCD is defined the LoadFile2 method                                                                            
of passing initrd will be used.                                                                                                                      
[v3] …
=> AndroidBootImgLib improvements

UefiPayloadPkg/UefiPayloadPkg.dsc, UefiPayloadPkg/UefiPayloadPkg.fdf
Add Macro to enable or disable RamDiskDxe and SioBusDxe drivers.
=> UefiPayloadPkg: Add Macro to enable or disable some drivers.

MdeModulePkg/Bus/Pci/PciBusDxe/PciEnumeratorSupport.c
https://bugzilla.tianocore.org/show_bug.cgi?id=3635
Currently, in order to test the supported attributes,
the PciTestSupportedAttribute() will set the command register
to 0x27 (EFI_PCI_COMMAND_IO_SPACE, EFI_PCI_COMMAND_MEMORY_SPACE,
EFI_PCI_COMMAND_BUS_MASTER, EFI_PCI_COMMAND_VGA_PALETTE_SNOOP) firstly,
and then read back to check whether these attributes are
set successfully in the device.
This will cause the other enabled bits
(other than EFI_PCI_COMMAND_IO_SPACE,EFI_PCI_COMMAND_MEMORY_SPACE,
EFI_PCI_COMMAND_BUS_MASTER,EFI_PCI_COMMAND_VGA_PALETTE_SNOOP)
be cleared for a short of time
This patch fixes this issue by keeping the origina
enabled bits when setting 0x27.
Signed-off-by: xueshengfeng <xueshengfeng@byosoft.com.cn>
Reviewed-by: Ray <ray.ni@intel.com>
=> MdeModulePkg/PciBusDxe: Improve the flow of testing support attributes

UefiPayloadPkg/UefiPayloadEntry/AcpiTable.c, UefiPayloadPkg/UefiPayloadEntry/UefiPayloadEntry.c, UefiPayloadPkg/UefiPayloadEntry/UefiPayloadEntry.h, UefiPayloadPkg/UefiPayloadEntry/UefiPayloadEntry.inf, UefiPayloadPkg/UefiPayloadEntry/UniversalPayloadEntry.c, UefiPayloadPkg/UefiPayloadEntry/UniversalPayloadEntry.inf
For universal UEFI payload, build a HOB from the ACPI table, so that
other modules could use this info from HOB at very early DXE phase.
This code are shared by universal payload and non universal payload.
=> UefiPayloadPkg: Build a HOB from bootloader ACPI table

UefiPayloadPkg/Library/UniversalPayloadPlatformHookLib/PlatformHookLib.c, UefiPayloadPkg/Library/UniversalPayloadPlatformHookLib/PlatformHookLib.inf
The Library constructor is only used for library dependency.
So use a dummy function to make it clear instead of using an
actual function.
=> UefiPayloadPkg: Use dummy constructor for PlatformHookLib

UefiPayloadPkg/UniversalPayloadBuild.py
From the universal scalable firmware payload requirement V0.75,
Payload must have Universal Payload Information Section ".upld_info"
So update the build tool to add this section.
=> UefiPayloadPkg: Add ".upld_info" in universal payload

BaseTools/Bin/gcc_aarch64_linux_ext_dep.yaml, BaseTools/Bin/gcc_arm_linux_ext_dep.yaml, BaseTools/Plugin/LinuxGcc5ToolChain/LinuxGcc5ToolChain.py
BaseTools/Bin/gcc_[arm,aarch64]_linux_ext_dep.yaml downloads GCC releases from https://releases.linaro.org/components/toolchain/binaries/7.4-2019.02 . 
As indicated in the URL, those builds are from 2019 because Linaro no longer do GCC releases, with that task having moved to Arm. 
The Arm GCC page is https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-a/downloads,
with the latest release being 10.3-2021.07.
gcc_aarch64_linux_ext_dep.yaml is used when setting up a CI environment using the stuart tools.
BZ: https://bugzilla.tianocore.org/show_bug.cgi?id=3594
PR: https://github.com/tianocore/edk2/pull/1909
=> BaseTools: Switch to downloading the ARM and AARCH64 compilers from Arm's site
