tianocore/edk2

BaseTools/Source/Python/AutoGen/GenMake.py, BaseTools/Source/Python/AutoGen/ModuleAutoGen.py, BaseTools/Source/Python/GenFds/GenFds.py, BaseTools/Source/Python/GenFds/GenFdsGlobalVariable.py, BaseTools/Source/Python/TargetTool/TargetTool.py, BaseTools/Source/Python/Workspace/BuildClassObject.py, BaseTools/Source/Python/Workspace/DscBuildData.py, BaseTools/Source/Python/build/build.py
A Makefile name is not set in BaseTools when only building modules or libraries. This patch-set sets a default Makefile name for the "build" command.
The patch-set also:
Removes unsused Makefile variables
Removes hard-coded references to "target.txt" and "tools_def.txt"
The changes can be seen at: https://github.com/PierreARM/edk2/tree/1868_BaseTools_build_py_corrections_v1
=> Set default Makefile name

OvmfPkg/AmdSev/AmdSevX64.dsc, OvmfPkg/AmdSev/AmdSevX64.fdf, OvmfPkg/Library/PlatformBootManagerLib/BdsPlatform.c, OvmfPkg/Library/PlatformBootManagerLibBhyve/BdsPlatform.c, OvmfPkg/Library/PlatformBootManagerLibGrub/BdsPlatform.c, OvmfPkg/Library/Tcg2PhysicalPresenceLibQemu/DxeTcg2PhysicalPresenceLib.c, OvmfPkg/Library/Tcg2PhysicalPresenceLibQemu/DxeTcg2PhysicalPresenceLib.inf, OvmfPkg/OvmfPkgIa32.dsc, OvmfPkg/OvmfPkgIa32.fdf, OvmfPkg/OvmfPkgIa32X64.dsc, OvmfPkg/OvmfPkgIa32X64.fdf, OvmfPkg/OvmfPkgX64.dsc, OvmfPkg/OvmfPkgX64.fdf
This series of patches adds support for disabling the TPM 2 platform
hierarchy to Ovmf. To be able to do this we have to handle TPM 2
physical presence interface (PPI) opcodes before the TPM 2 platform
hierarchy is disabled otherwise TPM 2 commands that are sent due to the
PPI opcodes may fail if the platform hierarchy is already disabled.
Therefore, we need to invoke the handler function
Tcg2PhysicalPresenceLibProcessRequest from within
PlatformBootManagerBeforeConsole. Since handling of PPI opcodes may require
interaction with the user, we also move PlatformInitializeConsole 
to before the handling of PPI codes so that the keyboard is available
when needed. The PPI handling code will activate the default consoles
only if it requires user interaction.
Regards,
Stefan
v3:
- Added Yao's …
=> OvmfPkg: Disable the TPM 2 platform hierarchy

SecurityPkg/VariableAuthenticated/SecureBootDefaultKeysDxe/SecureBootDefaultKeysDxe.c
The dbt and dbx keys are optional, the driver entry should return
EFI_SUCCESS to start if they are not found in the firmware flash. This
patch is to fix it and update the description of retval as well.
Cc: Grzegorz Bernacki <gjb@semihalf.com>
Reviewed-by: Grzegorz Bernacki <gjb@semihalf.com>
=> SecurityPkg: Fix SecureBootDefaultKeysDxe failed to start

ArmPkg/Universal/Smbios/SmbiosMiscDxe/Type00/MiscBiosVendorFunction.c
According to the SMBIOS specification, the ExtendedBiosSize field should
be zero when the BIOS size is less than 16MB:
"Size (n) where 64K * (n+1) is the size of the
physical device containing the BIOS, in
bytes.
FFh - size is 16MB or greater, see Extended
BIOS ROM Size for actual size."
Fix the code in MiscBiosVendorFunction.c to only populate the
ExtendedBiosSize field if the BIOS size is greater than 16MB.
Fix the code to correctly populate the ExtendedBiosSize field with the
unit bits set to MB if the size is between 16MB and 16GB.
Acked-by: Nhi Pham <nhi@os.amperecomputing.com>
=> ArmPkg: SmbiosMiscDxe: Don't populate ExtendedBiosSize when size < 16MB

DynamicTablesPkg/Library/Acpi/Arm/AcpiFadtLibArm/FadtGenerator.c
Bugzilla: 3568 (https://bugzilla.tianocore.org/show_bug.cgi?id=3568)
Update the FADT generator to use Acpi64.h. As the FADT revision tracks
the ACPI revision this updates the minor revision value generated.
Mantis ID for change: https://mantis.uefi.org/mantis/view.php?id=2105
Signed-off-by: Chris Jones <christopher.jones@arm.com>
=> DynamicTablesPkg: Update FADT generator to ACPI 6.4

SecurityPkg/FvReportPei/FvReportPei.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2673
M mean that Measured Boot, V mean that Verified Boot.
The FvReport do below:
1. Do nothing if neither M nor V
2. Allocate pages to save the firmware volume and use it to install
firmware info Ppi
3. Install PreHashFv Ppi if the FV need measurement.
4. Verify the Hash if the FV need verification
Notes:
1. The component is used to verify the FV or measure the FV
2. Copy action is just for security purpose but not main purpose.
3. If you use this component, Doesn't need to copy in other compoent
which result time consumption.
=> SecurityPkg/FvReportPei: Remove the ASSERT to allow neither M nor V

BaseTools/Source/C/VfrCompile/VfrUtilityLib.cpp
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3687
If a C structure parsed by the VFR compiler contains an unnamed
field, then mFieldName is left uninitialized, which generates
random data in the VFR compiler output file.
If the FieldName is NULL, then initialize pNewField->mFieldName
to a Null-terminated empty string.
=> BaseTools/VrfCompile: Fix uninitialized field from unnamed field

DynamicTablesPkg/DynamicTablesPkg.dsc, MdeModulePkg/Universal/Variable/RuntimeDxe/RuntimeDxeUnitTest/VariableLockRequestToLockUnitTest.c, NetworkPkg/NetworkPkg.dsc, SecurityPkg/SecurityPkg.dsc, SignedCapsulePkg/SignedCapsulePkg.dsc, UefiCpuPkg/Library/MtrrLib/UnitTest/MtrrLibUnitTest.c
This patch series fixes a number of different package build
issues.  These were discovered when evaluating the source
format changes from uncrustify and there where valid
package builds that are not working before applying the
uncrustify changes. 
* Missing RngLib mappings
* Missing ArmSoftFloatLib mapping
* Missing BaseStackCheckLib instance
* Incorrect use of UT_ASSERT_EQUAL() with pointers
* Incorrect use of cmocka will_return*() with pointers
Cc: Sami …
=> [Patch V2 0/7] Fix package build issues

BaseTools/Scripts/ConvertFceToStructurePcd.py
Currently when parse VFR files to get the struct info,
BOOLEAN type struct is ignored, which caused offset errors.
This patch fixed these bugs.
=> BaseTools: Fix StructurePcd offset error.

MdeModulePkg/Bus/Pci/XhciDxe/XhciSched.c
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=3662
Two DEBUG macros in XhciDxe/XhciSched.c are missing the argument
that should be passed for the print specifier.
In addition, this change updates the print level to "DEBUG_ERROR"
and prints the status as well.
=> MdeModulePkg/XhciSched: Fix missing DEBUG arguments

ArmPkg/Universal/Smbios/ProcessorSubClassDxe/ProcessorSubClass.c, ArmPkg/Universal/Smbios/SmbiosMiscDxe/Type00/MiscBiosVendorFunction.c, ArmPkg/Universal/Smbios/SmbiosMiscDxe/Type01/MiscSystemManufacturerFunction.c, ArmPkg/Universal/Smbios/SmbiosMiscDxe/Type02/MiscBaseBoardManufacturerFunction.c, ArmPkg/Universal/Smbios/SmbiosMiscDxe/Type03/MiscChassisManufacturerFunction.c, ArmPkg/Universal/Smbios/SmbiosMiscDxe/Type13/MiscNumberOfInstallableLanguagesFunction.c, ArmPkg/Universal/Smbios/SmbiosMiscDxe/Type32/MiscBootInformationFunction.c, MdeModulePkg/Bus/Pci/PciHostBridgeDxe/PciHostBridge.c, MdeModulePkg/Library/UefiBootManagerLib/BmDriverHealth.c, MdePkg/Include/Library/DebugLib.h, MdePkg/Include/Library/UnitTestLib.h, MdePkg/Library/BaseLib/SafeString.c, NetworkPkg/Include/Library/NetLib.h, NetworkPkg/Library/DxeNetLib/DxeNetLib.c, OvmfPkg/Csm/LegacyBiosDxe/LegacyPci.c, OvmfPkg/Library/PlatformBootManagerLib/BdsPlatform.c, OvmfPkg/Library/PlatformBootManagerLibBhyve/BdsPlatform.c, OvmfPkg/Library/PlatformBootManagerLibGrub/BdsPlatform.c, SecurityPkg/Include/Library/TcgStorageCoreLib.h
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3688
New in V2
=======
* Split MdePkg DebugLib class enhancements out into its own commit
* Address ECC failures
* Align macro continuation marks in same column
This change is required to help verify that source code formatting
changes such as the use of uncrustify and line ending corrections
do not have any functional differences.  Source format changes may
add or remove line endings that change the source file line numbers
of C statements or may change the use of spaces in C expressions 
used in an ASSERT() statements.  These types of changes can impact
the generated binaries when DEBUG() and ASSERT() macros are 
enabled.  The following set of changes adds 2 defines that can be used
to override the use of `__LINE__` in DEBUG() macros …
=> Bug 3688 reproduce builds across source format changes v2

ShellPkg/Library/UefiShellAcpiViewCommandLib/AcpiParser.h
Add a comment to clarify that in Acpiview the ItemPtr is not set until
after the FieldValidator has been called.
Signed-off-by: Chris Jones <christopher.jones@arm.com>
=> ShellPkg: Add comment that ItemPtr is set after validation

MdeModulePkg/Library/DxeCapsuleLibFmp/CapsuleOnDisk.c, MdeModulePkg/Library/DxeCapsuleLibFmp/DxeCapsuleLib.inf
Enhance RelocateCapsuleToRam() to skip creation of the Capsule on Disk
file name capsule if PcdSupportUpdateCapsuleReset feature is not enabled.
This avoids an EFI_UNSUPPORTED return status from UpdateCapsule() when the
file name capsule is encountered and PcdSupportUpdateCapsuleReset is FALSE.
Signed-off-by: Bob Morgan <bobm@nvidia.com>
=> MdeModulePkg/DxeCapsuleLibFmp: Capsule on Disk file name capsule

UefiCpuPkg/Include/Library/UefiCpuLib.h, UefiCpuPkg/Library/BaseUefiCpuLib/BaseUefiCpuLib.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3698
Lots of code relies on CPU Family/Model/Stepping for different logics.
The change adds two APIs for such needs.
=> UefiCpuPkg/UefiCpuLib: Add GetCpuFamilyModel and GetCpuSteppingId

MdeModulePkg/Library/DxeCapsuleLibFmp/DxeCapsuleLib.inf, MdeModulePkg/Library/DxeCapsuleLibFmp/DxeCapsuleReportLib.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3699
The code in MdeModulePkg\Library\DxeCapsuleLibFmp call the deprecated
interface VariableLockRequestToLock.c. So I changed the code in
FmpDevicePkg using RegisterBasicVariablePolicy, instead of the
deprecated interface.
Signed-off-by: Yang Jie <jie.yang@intel.com>
=> MdeModulePkg/DxeCapsuleLibFmp: Use new Variable Lock interface

UefiCpuPkg/Library/CpuExceptionHandlerLib/X64/Xcode5ExceptionHandlerAsm.nasm, UefiCpuPkg/PiSmmCpuDxeSmm/PiSmmCpuDxeSmm.c, UefiCpuPkg/PiSmmCpuDxeSmm/PiSmmCpuDxeSmm.h, UefiCpuPkg/PiSmmCpuDxeSmm/X64/PageTbl.c, UefiCpuPkg/PiSmmCpuDxeSmm/X64/SmmFuncsArch.c
When CET shadow stack feature is enabled, it needs to use IST for the
exceptions, and uses interrupt shadow stack for the stack switch.
Shadow stack should be 32 bytes aligned.
Check IST field, when clear shadow stack token busy bit when using retf.
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3728
Signed-off-by: Sheng Wei <w.sheng@intel.com>
=> UefiCpuPkg/PiSmmCpuDxeSmm: Use SMM Interrupt Shadow Stack

OvmfPkg/Library/ResetSystemLib/ResetSystemLibMicrovm.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3731
Fix VS2019 NOOPT build issues with OvmfPkg/Microvm/MicrovmX64.dsc
by fixing typecast of MICROVM_GED_MMIO_BASE_REGS to a VOID *.
=> OvmfPkg/Library/ResetSystemLib: Fix Microvm VS2019 NOOPT build issue

MdeModulePkg/Bus/Ata/AtaAtapiPassThru/AhciMode.c
BZ: https://bugzilla.tianocore.org/show_bug.cgi?id=3732
Recent change c9742578 exposes this potential issue.
Acked-by: Rebecca Cran <rebecca@nuviainc.com>
=> MdeModulePkg AtaAtapiPassThru: Skip the potential NULL pointer access

NetworkPkg/DnsDxe/DnsImpl.c
Ref: https://bugzilla.tianocore.org/show_bug.cgi?id=3719
This issue is introduced by the commit 43d7e607.
Token->RspData.H2AData is de-allocated on error but it is not
set to NULL. HTTP module attempts to free again and cause assert.
Signed-off-by: Baraneedharan Anbazhagan <anbazhagan@hp.com>
Reviewed-by: Wu Jiaxin <jiaxin.wu@intel.com>
=> NetworkPkg: Fix invalid pointer for DNS response token on error

EmulatorPkg/Win/Host/WinHost.inf
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3747
* Remove deprecated option /Gm that generates a warning.
* Remove /Zi and use '=' instead of '== to let DEBUG/RELEASE/NOOPT
profile from tools_def.txt enable debug information
* Remove /Gs8192 option that is overriding the larger setting of
/GS32768 from tools_def.txt that generates a warning.
Cc: Michael Kubacki <michael.kubacki@microsoft.com>
=> EmulatorPkg/Win/Host: Update CC_FLAGS

.pytool/Plugin/LicenseCheck/LicenseCheck.py
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3746
Use --output option in git diff command to remove code diffs
from build log on stdout when LicenseCheck plugin is run.
Instead, create a temp directory for the diff output file and
remove the temp directory after the diff output is processed.
Cc: Michael Kubacki <michael.kubacki@microsoft.com>
=> .pytools/Plugin/LicenseCheck: Use temp directory for git diff output

.azurepipelines/templates/pr-gate-build-job.yml
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3750
Large patches that modify a large number of files(e.g uncrustify)
take longer to process through CI checks such as ECC.  Increase
the max job time from 1 hour to 2 hours to accommodate larger patch
series.
Cc: Michael Kubacki <michael.kubacki@microsoft.com>
=> .azurepipelines/templates: Update max pipeline job time to 2 hours

ArmPkg/ArmPkg.ci.yaml, ArmPlatformPkg/ArmPlatformPkg.ci.yaml, ArmVirtPkg/ArmVirtPkg.ci.yaml, CryptoPkg/CryptoPkg.ci.yaml, EmulatorPkg/EmulatorPkg.ci.yaml, MdeModulePkg/MdeModulePkg.ci.yaml, MdePkg/MdePkg.ci.yaml, SecurityPkg/SecurityPkg.ci.yaml, ShellPkg/ShellPkg.ci.yaml, StandaloneMmPkg/StandaloneMmPkg.ci.yaml, UefiPayloadPkg/UefiPayloadPkg.ci.yaml, UnitTestFrameworkPkg/UnitTestFrameworkPkg.ci.yaml
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3749
Update package YAML files to ignore ECC errors that are
already present.  These issues must be fixed in the future,
but should not block source code changes for these known
issues.
Cc: Supreeth …
=> Update Package YAML to ignore specific ECC files/errors

MdeModulePkg/Library/DxeCorePerformanceLib/DxeCorePerformanceLib.c
SmmBootRecordDataSize is initialized in InternalGetSmmPerData,
but this function may fail. so to avoid using SmmBootRecordDataSize
without intialization, set it to 0 at first.
=> MdeModulePkg/DxeCorePerformanceLib:Variable Initial

.pytool/Plugin/UncrustifyCheck/Readme.md, .pytool/Plugin/UncrustifyCheck/UncrustifyCheck.py, .pytool/Plugin/UncrustifyCheck/default_file_header.txt, .pytool/Plugin/UncrustifyCheck/default_function_header.txt, .pytool/Plugin/UncrustifyCheck/uncrustify.cfg, .pytool/Plugin/UncrustifyCheck/uncrustify_ext_dep.yaml, .pytool/Plugin/UncrustifyCheck/uncrustify_plug_in.yaml, .pytool/Readme.md
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=3748
Adds a new CI plugin for Uncrustify. This is used to check
coding standard compliance of source code to the EDK II C Coding
Standards Specification.
An external dependency is added in the plugin directory to retrieve
the Uncrustify executable. Currently, the executable is from an edk2
fork of the application host in this repository:
https://dev.azure.com/projectmu/Uncrustify/
Note that the Uncrustify application outputs the commit ID that the
application was built from when given the --version parameter.
This ID can be mapped to the version specified in the Uncrustify CI
plugin external dependency file (uncrustify_ext_dep.yaml) such as
73.0.3 by visiting the Uncrustify edk2 fork release pipeline page
which associates the NuGet …
=> .pytool/Plugin/UncrustifyCheck: Add Uncrustify CI plugin

BaseTools/Source/C/DevicePath/DevicePath.c
Currently the PCD Value only support 13 Guid,When use more 13 pcd will cause the build tool fail,
Need calculate the required memory,then allocate it.
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3718
Signed-off-by: Xiaolu Jiang <xiaolu.jiang@intel.com>
=> BaseTools: Increase the DevicePath length for support more PCD value.

MdeModulePkg/Bus/Pci/UhciDxe/UsbHcMem.c
Patch sent at: https://edk2.groups.io/g/devel/message/84078
When use the UsbHcAllocMemFromBlock() and UsbHcFreeMem() to allocate
memory and free memory for the UHC, it should use the corresponding host
address but not the pci bus address.
Signed-off-by: jdzhang <jdzhang@zd-tech.com.cn>
=> MdeModulePkg/Bus/Pci/UhciDxe: Fix the UsbHc memory allocate and free issue

BaseTools/Source/C/VfrCompile/VfrFormPkg.h, BaseTools/Source/C/VfrCompile/VfrSyntax.g
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=3752
Add Bit mask to numeric/one of opcode to set correctly Flags for Bit Field.
VfrSyntax.g: Set "LFlags &= EDKII_IFR_DISPLAY_BIT" before "LFlags |= (EDKII_IFR_NUMERIC_SIZE_BIT & (_GET_CURRQEST_VARSIZE()));"
VfrFormPkg.h: update "if (LFlags & EFI_IFR_DISPLAY)" with "if (LFlags & EDKII_IFR_DISPLAY_BIT)" in SetFlagsForBitField()
Signed-off-by: Long1 Huang <long1.huang@intel.com>
=> BaseTools/VfrCompile: Correct Bit Field Flags for numeric/one of

OvmfPkg/AmdSev/AmdSevX64.dsc, OvmfPkg/AmdSev/AmdSevX64.fdf, OvmfPkg/Bhyve/BhyveX64.dsc, OvmfPkg/Bhyve/BhyveX64.fdf, OvmfPkg/Microvm/MicrovmX64.dsc, OvmfPkg/Microvm/MicrovmX64.fdf, OvmfPkg/OvmfPkgIa32.dsc, OvmfPkg/OvmfPkgIa32.fdf, OvmfPkg/OvmfPkgIa32X64.dsc, OvmfPkg/OvmfPkgIa32X64.fdf, OvmfPkg/OvmfPkgX64.dsc, OvmfPkg/OvmfPkgX64.fdf, OvmfPkg/OvmfXen.dsc, OvmfPkg/OvmfXen.fdf
PrintDxe produces gEfiPrint2ProtocolGuid and gEfiPrint2SProtocolGuid,
and those are consumed by the following PrintLib instance:
MdeModulePkg/Library/DxePrintLibPrint2Protocol/DxePrintLibPrint2Protocol.inf
However, none of the OVMF DSC files contain such a PrintLib class
resolution, so none of the OVMF platforms need PrintDxe.
Cc: Brijesh Singh <brijesh.singh@amd.com>
Suggested-by: Laszlo Ersek <lersek@redhat.com>
Ref: …
=> OvmfPkg: Remove unused print service driver (PrintDxe)

OvmfPkg/OvmfXen.dsc
commit 202fb22be6e9 "OvmfPkg/SecMain: validate the memory used for
decompressing Fv" broke building OvmfXen with:
edk2/OvmfPkg/OvmfXen.dsc(...): error 1001: Module type [SEC] is not
supported by library instancer
[edk2/OvmfPkg/Library/BaseMemEncryptSevLib/DxeMemEncryptSevLib.inf]
consumed by [edk2/OvmfPkg/Sec/SecMain.inf]
The above commit added a reference to MemEncryptSevLib into SecMain.inf,
but OvmfXen.dsc doesn't have a MemEncryptSevLib entry for SEC.  Add one
like OvmfPkgX64.dsc has.
Cc: Anthony Perard <anthony.perard@citrix.com>
Cc: Julien Grall <julien@xen.org> …
=> OvmfPkg/OvmfXen: Fix Xen build

OvmfPkg/AmdSev/AmdSevX64.dsc, OvmfPkg/Bhyve/BhyveX64.dsc, OvmfPkg/EmuVariableFvbRuntimeDxe/Fvb.c, OvmfPkg/EmuVariableFvbRuntimeDxe/Fvb.inf, OvmfPkg/Microvm/MicrovmX64.dsc, OvmfPkg/OvmfPkgIa32.dsc, OvmfPkg/OvmfPkgIa32X64.dsc, OvmfPkg/OvmfPkgX64.dsc, OvmfPkg/OvmfXen.dsc
In FvbInitialize Function,
PcdFlashNvStorageVariableBase64 PcdFlashNvStorageFtwWorkingBase
PcdFlashNvStorageFtwSpareBase will not exceed 0x100000000,
Due to truncation and variable type limitations.
That leads to the NV variable cannot be saved to the memory above 4G.
Modify as follows:
1.Remove the forced type conversion of UINT32.
2.Use UINT64 type variables.
Signed-off-by: xianglai li <lixianglai@loongson.cn>
=> OvmfPkg-EmuVariableFvbRuntimeDxe: Support Access To Memory Above 4G

EmbeddedPkg/Include/Library/AcpiLib.h, EmbeddedPkg/Library/AcpiLib/AcpiLib.c, EmbeddedPkg/Library/AcpiLib/AcpiLib.inf
This adds more helper functions that assist in calculating the checksum,
locating an ACPI table by signature, and updating an AML integer object.
Acked-by: Leif Lindholm <leif@nuviainc.com>
Reviewed-by: Abner Chang <abner.chang@hpe.com>
=> EmbeddedPkg/AcpiLib: Add more helper functions

OvmfPkg/Bhyve/BhyveX64.dsc
Path doesn't exist below OvmfPkg/Bhyve, use the OvmfPkg version
instead.  Fixes build with -D NETWORK_TLS_ENABLE.
=> OvmfPkg/Bhyve: fix tls-enabled build

OvmfPkg/Library/PlatformBootManagerLib/BdsPlatform.c, OvmfPkg/Library/PlatformBootManagerLibBhyve/BdsPlatform.c, OvmfPkg/Library/PlatformBootManagerLibGrub/BdsPlatform.c
For GPU passthrough support we have to initialize the console after
EfiBootManagerDispatchDeferredImages() has loaded ROMs, so call it after
this. This was the calling order before the TCG physical presence support
had to be moved and the console initialized earlier so user interaction
could be supported before processing TCG physical presence opcodes.
Signed-off-by: Stefan Berger <stefanb@linux.ibm.com>
Tested-by: Shivanshu Goyal <shivanshu3@gmail.com>
=> OvmfPkg: Call PlatformInitializeConsole for GPU passthrough case

IntelFsp2WrapperPkg/FspmWrapperPeim/FspmWrapperPeim.c, IntelFsp2WrapperPkg/FspmWrapperPeim/FspmWrapperPeim.inf, IntelFsp2WrapperPkg/FspsWrapperPeim/FspsWrapperPeim.c, IntelFsp2WrapperPkg/FspsWrapperPeim/FspsWrapperPeim.inf, IntelFsp2WrapperPkg/IntelFsp2WrapperPkg.dec
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=3642
when the module is not building in IA32 mode which will lead to building
error. when a module built-in X64 function pointer will be the size of
64bit width which cannot be fit in 32bit address which will lead to
error. to overcome this issue introducing the 2 new PCD's for the 64bit
modules can consume it. based on the which pcd platform set, use that.
Cc: Kuo Ted <ted.kuo@intel.com>
Cc: Rangasai V Chaganty <rangasai.v.chaganty@intel.com>
Cc: Digant H Solanki <digant.h.solanki@intel.com>
Cc: Sangeetha V <sangeetha.v@intel.com> …
=> IntelFsp2WrapperPkg : FSPM/S UPD data address based on Build Type

IntelFsp2WrapperPkg/FspmWrapperPeim/FspmWrapperPeim.c, IntelFsp2WrapperPkg/FspsWrapperPeim/FspsWrapperPeim.c
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=3642
Local functions do not need EFIAPI.
=> IntelFsp2WrapperPkg : Remove EFIAPI from local functions.

MdeModulePkg/Bus/Usb/UsbBusDxe/UsbUtility.c, MdeModulePkg/Bus/Usb/UsbBusDxe/UsbUtility.h
Patch sent at: https://edk2.groups.io/g/devel/message/85108
gcc-11 (fedora 35):
/home/kraxel/projects/edk2/MdeModulePkg/Bus/Usb/UsbBusDxe/UsbBus.c: In function ?UsbIoBulkTransfer?:
/home/kraxel/projects/edk2/MdeModulePkg/Bus/Usb/UsbBusDxe/UsbBus.c:277:12: error: ?UsbHcBulkTransfer? accessing 80 bytes in a region of size 8 [-Werror=stringop-overflow=]
=> MdeModulePkg/UsbBusDxe: fix NOOPT build error

UefiCpuPkg/MicrocodeMeasurementDxe/MicrocodeMeasurementDxe.c, UefiCpuPkg/MicrocodeMeasurementDxe/MicrocodeMeasurementDxe.inf, UefiCpuPkg/MicrocodeMeasurementDxe/MicrocodeMeasurementDxe.uni, UefiCpuPkg/MicrocodeMeasurementDxe/MicrocodeMeasurementDxeExtra.uni, UefiCpuPkg/UefiCpuPkg.dsc
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3683
TCG specification says BIOS should extend measurement of microcode to TPM.
However, reference BIOS is not doing this. BIOS shall extend measurement of
microcode to TPM.
Cc: Min M Xu <min.m.xu@intel.com>
Signed-off-by: Longlong Yang <longlong.yang@intel.com>
=> UefiCpuPkg: Extend measurement of microcode patches to TPM

BaseTools/Source/Python/AutoGen/AutoGenWorker.py, BaseTools/Source/Python/AutoGen/DataPipe.py
currently the --cmd-len build option does not work.
This patch is going to fix this bug.
=> BaseTools: Fix the bug of --cmd-len build option

IntelFsp2Pkg/FspSecCore/SecFsp.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3791
ExtendedImageRevision should be printed when Header revision >= 6.
=> IntelFsp2Pkg/FspSecCore: ExtendedImageRevision was not printed.

OvmfPkg/AmdSev/SecretPei/SecretPei.c
Mark the SEV launch secret MEMFD area as reserved, which will allow the
guest OS to use it during the lifetime of the OS, without creating
copies of the sensitive content.
Cc: Brijesh Singh <brijesh.singh@amd.com>
Cc: Tobin Feldman-Fitzthum <tobin@linux.ibm.com>
Signed-off-by: Dov Murik <dovmurik@linux.ibm.com>
Acked-by: Jiewen Yao <Jiewen.Yao@intel.com>
Reviewed-by: Brijesh Singh <brijesh.singh@amd.com>
=> OvmfPkg/AmdSev/SecretPei: Mark SEV launch secret area as reserved

MdePkg/Include/IndustryStandard/Nvme.h
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3757
Add registers of boot partition feature defined in NVM Express 1.4 Spec
Signed-off-by: Maggie Chu <maggie.chu@intel.com>
=> MdePkg: Add registers of boot partition feature

UnitTestFrameworkPkg/UnitTestFrameworkPkg.ci.yaml
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3798
UnitTestFrameworkPkg.dec contains cmockery folder from cmocka submodule.
However, the term "cmockery" is unrecognized by cspell tool.
This change grants spell check exception to "cmockery" to prevent
pipeline building failure.
=> UnitTestFrameworkPkg: CI YAML: Grant cmockery spell check exception

MdeModulePkg/Universal/Disk/PartitionDxe/Mbr.c
Patch sent at: https://edk2.groups.io/g/devel/message/85289
Read Disk does a modification of ExtMbrStartingLba with the code MultU64x32
(ExtMbrStartingLba, BlockSize) Error detection to see if ExtMbrStartingLBA
has a value of 0. This is invalid as LBA 0 = MBR. After modification, the
next time ExtMbrStartingLba is in this function if ExtMbrStartingLba is set
to 0 in the MBR it never passes the while/do evaluation It is multiplied by
0 by read disk , set to 0 by an invalid MBR and goes back to evaluation
This condition will also cause Ws19 and WS22 to hang, however Microsoft has
developed a hotfix patch that will be released in 2022
Cc: Zhichao …
=> MdeModulePkg/PartitionDxe: Add break to handle invalid LBA0 in MBR

BaseTools/Source/Python/AutoGen/GenVar.py
There are two type variable header and their size are different,
need to use matched size when calculating offset info, otherwise
it'll destroy other variables content when patching.
Signed-off-by: Chen, Lin Z <lin.z.chen@intel.com>
=> BaseTools: Fix wrong variable header size

Maintainers.txt, OvmfPkg/CloudHv/CloudHvX64.dsc, OvmfPkg/CloudHv/CloudHvX64.fdf, OvmfPkg/Library/PlatformBootManagerLib/BdsPlatform.c, OvmfPkg/PlatformCI/.azurepipelines/Ubuntu-GCC5.yml, OvmfPkg/PlatformCI/CloudHvBuild.py
From: Sebastien Boeuf <sebastien.boeuf@intel.com>
Since Cloud Hypervisor and QEMU pc/q35 are quite different, it makes
more sense to create a dedicated OVMF target for Cloud Hypervisor rather
than trying to support both VMMs from the same OvmfPkgX64 target.
That's the reason why this series introduces a new target called
CloudHvX64, meant to be used with the Cloud Hypervisor VMM only.
The new target is initially copied over from the OvmfPkgX64, then it is
trimmed down by removing what is not needed from a Cloud Hypervisor
perspective.
Sebastien Boeuf (11):
OvmfPkg/CloudHv: Add new target for Cloud Hypervisor
OvmfPkg/CloudHv: Replace legacy 8254 PIT with local APIC timer
OvmfPkg/CloudHv: Connect serial console
OvmfPkg/CloudHv: Remove legacy 8259 PIC support
OvmfPkg/CloudHv: Remove Q35 …
=> Create new target for Cloud Hypervisor

UefiPayloadPkg/UefiPayloadPkg.dsc
For recent X86 CPU, 0x15 CPUID instruction will return Time Stamp
Counter. This is recommended way to get the time, and also how
BaseCpuTimerLib works However, some CPU doesn't support this feature,
so disable it by default.
=> UefiPayloadPkg: Not use BaseCpuTimerLib by default.

FmpDevicePkg/FmpDxe/FmpDxe.c, FmpDevicePkg/Include/Library/FmpDeviceLib.h, FmpDevicePkg/Library/FmpDeviceLibNull/FmpDeviceLib.c
Update the logic handling last attempt status codes from
FmpDeviceCheckImageWithStatus() implementations to account for
cases when the function return status code is EFI_SUCCESS
(since the image was checked successfully) but the ImageUpdatable
value is not valid.
In addition the following sentence is removed from the
LastAttemptStatus parameter definition for
FmpDeviceCheckImageWithStatus() since it can lead to confusion.
The expected status code value range is sufficient to implement
the library API.
"This value will only be checked when this
function returns an error."
Cc: Wei6 Xu <wei6.xu@intel.com>
Signed-off-by: Michael Kubacki …
=> FmpDevicePkg/FmpDxe: Update FmpDeviceCheckImageWithStatus() handling

MdeModulePkg/Universal/Variable/RuntimeDxe/Variable.c
Only EFI_VARIABLE_NON_VOLATILE attribute is an invalid combination
of attribute bits, so update the variable driver to return
EFI_INVALID_PARAMETER so that we can prevent the invalid variable
being created.
This change also fixes the SCT failure below:
- RT.QueryVariableInfo - With being an invalid combination -- FAILURE
For details, please check the threads below:
- https://edk2.groups.io/g/devel/topic/86486174
- https://edk2.groups.io/g/devel/message/82466
Cc: Heinrich Schuchardt <heinrich.schuchardt@canonical.com>
Cc: G Edhaya Chandran <edhaya.chandran@arm.com>
Cc: Samer El-Haj-Mahmoud <samer.el-haj-mahmoud@arm.com>
Signed-off-by: Sunny Wang <sunny.wang@arm.com>
=> MdeModulePkg/Variable: Make only EFI_VARIABLE_NON_VOLATILE invalid

EmbeddedPkg/Library/PrePiLib/FwVol.c
BZ: https://bugzilla.tianocore.org/show_bug.cgi?id=3814
CompressedDataLength is declared as UINTN which is UINT64 in X64 arch.
But the second parameter of UefiDecompressGetInfo() is declared as
UINT32. So a build error is triggered. To declare CompressedDataLength
as UINT32 to fix the build error.
=> EmbeddedPkg: Fix a build error in FwVol.c in X64 arch

UefiPayloadPkg/UefiPayloadPkg.dsc
Current, a macro CPU_TIMER_LIB_ENABLE is added to determine which timerlib
is used. BaseCpuTimerLib.inf is a better way and only fit for recent CPU.
Meanwhile, Universal Payload are only aimed to work with recent CPU.
Therefore, for Universal Payload, use the BaseCpuTimerLib by default
=> UefiPayloadPkg: Use BaseCpuTimerLib for Universal Payload by default

MdeModulePkg/Library/UefiBootManagerLib/BmLoadOption.c, MdeModulePkg/Library/UefiBootManagerLib/InternalBm.h, MdeModulePkg/Library/UefiBootManagerLib/UefiBootManagerLib.inf
Since the Variable Lock protocol is deprecated, convert locking of
PlatformRecovery#### in EfiBootManagerLoadOptionToVariable to use the
Variable Policy protocol.
Signed-off-by: Rebecca Cran <quic_rcran@quicinc.com>
=> MdeModulePkg/UefiBootManagerLib: Convert BmLoadOption to Variable Policy

ArmPkg/Include/Guid/ArmMpCoreInfo.h, ArmPkg/Include/Library/ArmLib.h, ArmPlatformPkg/Library/ArmPlatformLibNull/ArmPlatformLibNull.c, ArmPlatformPkg/PrePeiCore/MainMPCore.c, ArmPlatformPkg/PrePi/MainMPCore.c
Remove the ClusterId and CoreId fields in the ARM_CORE_INFO structure in
favor of a new Mpidr field. Update code in
ArmPlatformPkg/PrePeiCore/MainMPCore and ArmPlatformPkg/PrePi/MainMPCore.c
to use the new field and call new macros GET_MPIDR_AFF0 and GET_MPIDR_AFF1
instead.
=> ArmPkg: Replace CoreId and ClusterId with Mpidr in ARM_CORE_INFO struct

ArmPkg/Drivers/CpuDxe/AArch64/Mmu.c, ArmPkg/Library/ArmMmuLib/AArch64/ArmMmuLibCore.c
We never run any code at EL0, and so it would seem that any access
permissions set for EL0 (via the AP[1] attribute in the page tables) are
irrelevant. We currently set EL0 and EL1 permissions to the same value
arbitrarily.
However, this causes problems on hardware like the Apple M1 running the
MacOS hypervisor framework, which enters EL1 with SCTLR_EL1.SPAN
enabled, causing the Privileged Access Never (PAN) feature to be enabled
on any exception taken to EL1, including the IRQ exceptions that handle
our timer interrupt. When PAN is enabled, EL1 has no access to any
mappings that are also accessible to EL0, causing the firmware to crash
if it attempts to access such a mapping.
Even though it is debatable whether or not SCTLR_EL1.SPAN should be
disabled at entry or whether the firmware …
=> ArmPkg/ArmMmuLib AARCH64: avoid EL0 accessible mappings

MdeModulePkg/Bus/Pci/PciBusDxe/PciRomTable.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3811
Remove ASSERT() statements that are triggered if a platform provides
an override of PCI ROM attached to a PCI Controller.  The PCI Platform
Protocol allows the platform to provide a PCI ROM image for a PCI
Controller.  This works for PCI Controllers that do not have an attached
PCI ROM, but the platform is not allowed to replace the PCI ROM for a
PCI Controller that has its own PCI ROM.  Removing these ASSERT()
statements enables this additional use case.
Acked-by: Ard Biesheuvel …
=> MdeModulePkg/Bus/Pci/PciBusDxe: Support platform PCI ROM override

ShellPkg/Library/UefiShellAcpiViewCommandLib/Parsers/Pptt/PpttParser.c
Bugzilla: 3770 (https://bugzilla.tianocore.org/show_bug.cgi?id=3770)
The PPTT parser in AcpiView incorrectly dereferences a pointer to
FlagName when trying to log an error with the PPTT cache flags, which
can lead to random crashes and other errors.
Also fix some spacing in the error message to ensure the message is
printed cleanly.
Signed-off-by: Chris Jones <christopher.jones@arm.com>
Reviewed-by: Rebecca Cran <rebecca@nuviainc.com>
=> ShellPkg: Fix incorrect PPTT FlagName dereference

BaseTools/Conf/build_rule.template, BaseTools/Conf/tools_def.template
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3810
New macro OBJCOPY_STRIPFLAG is added in build_rule.template to replace
'--strip-unneeded -R .eh_frame', so that module can have some unique
objcopy flags for its own purpose.
In tools_def.template, set '--strip-unneeded -R .eh_frame' as default
value of OBJCOPY_STRIPFLAG.
Signed-off-by: Wei6 Xu <wei6.xu@intel.com>
=> BaseTools/Conf: Add new macro for customizing dll file reduction.

BaseTools/Source/Python/Workspace/DscBuildData.py
Fix a Edk2Logger.warn() message format to match the arguments.
We ran into this after a failure in PcdValueInit.  The failure was
masked by a new exception, "TypeError: not all arguments converted
during string formatting".
Signed-off-by: Jake Garver <jake@nvidia.com>
=> BaseTools: Fix error leg in DscBuildData.py

MdeModulePkg/Core/RuntimeDxe/Runtime.c
When setting mVirtualMap to NULL also set mVirtualMapMaxIndex to 0.
Without that RuntimeDriverConvertPointer() will go search the ZeroPage
for EFI_MEMORY_DESCRIPTOR entries.
In case mVirtualMapMaxIndex happens to be small small enough that'll go
unnoticed, the search will not find anything and EFI_NOT_FOUND will be
returned.
In case mVirtualMapMaxIndex is big enough the search will reach the end
of the ZeroPage and trigger a page fault.
=> MdeModulePkg/RuntimeDxe: clear mVirtualMapMaxIndex

Maintainers.txt
The first patch adds some missing github IDs spotted when preparing the
second patch.
The second patch changes my email address from NUVIA to Qualcomm
Innovation Center (Quicinc).
=> Maintainers.txt updates

BaseTools/Conf/tools_def.template
Building with the CLANG35 and CLANG38 toolset fails because of variables
which are set but not otherwise used in the RELEASE build.
GCC added -Wno-unused-but-set-variable back in 2016, and later added
-Wno-unused-const-variable. Add those to CLANG35_WARNING_OVERRIDES and
CLANG38_WARNING_OVERRIDES.
Signed-off-by: Rebecca Cran <quic_rcran@quicinc.com>
=> BaseTools: Update CLANG{35,38}_WARNING_OVERRIDES to ignore unused vars

OvmfPkg/Library/VmgExitLib/VmgExitVcHandler.c
XCODE5 reported the following warning:
OvmfPkg/Library/VmgExitLib/VmgExitVcHandler.c:1895:12: note:
uninitialized use occurs here
Compacted
^^^^^^^^^
Initialize the 'Compacted' variable to fix the warning.
Signed-off-by: Rebecca Cran <quic_rcran@quicinc.com>
=> OvmfPkg/VmgExitLib: Fix uninitialized variable warning with XCODE5

OvmfPkg/CloudHv/CloudHvX64.dsc, OvmfPkg/OvmfPkgIa32.dsc, OvmfPkg/OvmfPkgIa32X64.dsc, OvmfPkg/OvmfPkgX64.dsc
BZ: https://bugzilla.tianocore.org/show_bug.cgi?id=3835
The commit ade62c18f4742301bbef474ac10518bde5972fba caused a boot failure
when OVMF is build with SECURE_BOOT/SMM enabled.
This happen because the above commit extended the BaseMemEncryptSevLib.inf
to include VmgExitLib. The FvbServicesSmm uses the functions provided
by the MemEncryptSevLib to clear the memory encryption mask from the
page table. It created a dependency, as shown below
OvmfPkg/FvbServicesSmm.inf
---> MemEncryptSevLib                   class
---> "OvmfPkg/BaseMemEncryptSevLib/DxeMemEncryptSevLib.inf"  instance
---> VmgExitLib
---> "OvmfPkg/VmgExitLib"    instance
---> LocalApicLib                       class
---> UefiCpuPkg/BaseXApicX2ApicLib/BaseXApicX2ApicLib.inf    instance
---> TimerLib …
=> OvmfPkg/FvbServicesSmm: use the VmgExitLibNull

ShellPkg/Library/UefiShellNetwork1CommandsLib/Ping.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3819
Ping GetTimerPeriod API returns sometime zero value when
StallCounter has smaller value than RttTimerTick (divide by zero)
which results some failure at ping UEFI shell command
Signed-off-by: MohammedX Rehan <mohammedx.rehan@intel.com>
=> ShellPkg: Fix Ping GetTimerPeriod API failure

NetworkPkg/WifiConnectionManagerDxe/WifiConnectionMgrHiiConfigAccess.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3813
The size of buffer should be 3 CHAR16 for Null-terminated Unicode
string.
The first char is the AKM/Cipher Suite number, the second char is ' ',
the third char is '\0'.
Cc: Fu Siyuan <siyuan.fu@intel.com>
Cc: Wu Jiaxin <jiaxin.wu@intel.com>
=> NetworkPkg: Fix incorrect unicode string of the AKM/Cipher Suite

MdeModulePkg/Bus/Pci/NvmExpressDxe/NvmExpress.c, MdeModulePkg/Bus/Pci/NvmExpressDxe/NvmExpressHci.c
Move the logic that stores starting PCI attributes and sets the
EFI_PCI_IO_ATTRIBUTE_DUAL_ADDRESS_CYCLE attribute to
DriverBindingStart() before the memory that backs the
DMA engine is allocated.
This ensures that the DMA-backing memory is not forcibly allocated
below 4G in system address map. Otherwise the allocation fails on
platforms that do not have any memory below the 4G mark and the drive
initialisation fails.
Leave the PCI device enabling attribute logic in NvmeControllerInit()
to ensure that the device is re-enabled on reset in case it was
disabled via PCI attributes.
Signed-off-by: Tomas Pilar <quic_tpilar@quicinc.com>
Acked-by: Hao A Wu <hao.a.wu@intel.com>
=> MdeModulePkg: Correct high-memory use in NvmExpressDxe

UefiPayloadPkg/PayloadLoaderPeim/ElfLib/Elf64Lib.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3818
It will have some potential issue when memory larger than 2G because
the high memory address will be fill with 0xFFFFFFFF when do the
operation of INTN + INT64 but it is 32 bit normal data in fact.
Should use same data type INT64 + INT64.
V3:
1. Use INT64 as input parameter because all date type is 64 bit
V2:
1. Force the data type to UINTN to avoid high dword be filled with
0xFFFFFFFF
2. Keep INTN because the offset may postive or negative.
=> UefiPayloadPkg/PayloadLoaderPeim: Use INT64 as input parameter

MdeModulePkg/Bus/Usb/UsbKbDxe/KeyBoard.c
Patch sent at: https://edk2.groups.io/g/devel/message/86964
No need to check the interface protocol then conditionally setting,
just set it to BOOT_PROTOCOL and check for error.
This is what Linux does for HID devices as some don't follow the USB spec.
One example is the Aspeed BMC HID keyboard device, which adds a massive
boot delay without this patch as it doesn't respond to
'GetProtocolRequest'.
Signed-off-by: Matt DeVillier <matt.devillier@gmail.com>
=> MdeModulePkg/Usb/Keyboard.c: Don't request protocol before setting

UefiCpuPkg/Include/Library/SmmCpuRendezvousLib.h, UefiCpuPkg/Include/Protocol/SmmCpuService.h, UefiCpuPkg/Library/SmmCpuRendezvousLib/SmmCpuRendezvousLib.c, UefiCpuPkg/Library/SmmCpuRendezvousLib/SmmCpuRendezvousLib.inf, UefiCpuPkg/PiSmmCpuDxeSmm/CpuService.c, UefiCpuPkg/PiSmmCpuDxeSmm/MpService.c, UefiCpuPkg/PiSmmCpuDxeSmm/PiSmmCpuDxeSmm.h, UefiCpuPkg/PiSmmCpuDxeSmm/PiSmmCpuDxeSmm.inf, UefiCpuPkg/UefiCpuPkg.dec, UefiCpuPkg/UefiCpuPkg.dsc
REF? https://bugzilla.tianocore.org/show_bug.cgi?id=3815
This patch define a new Protocol with the new services
SmmWaitForAllProcessor(), which can be used by SMI handler
to optionally wait for other APs to complete SMM rendezvous in
relaxed AP mode.
A new library SmmCpuRendezvousLib is provided to abstract the service
into library API to simple SMI handler code.
Cc: Zhihao Li <zhihao.li@intel.com>
=> UefiCpuPkg: Extend SMM CPU Service with rendezvous support.

Maintainers.txt
Add Sean Rhodes as UefiPayload reviewer mainly focus on
UEFI payload for coreboot support.
Reviewed-by: Sean Rhodes <sean@starlabs.systems>
=> Maintainers.txt: Add new reviewer for UefiPayloadPkg

UefiPayloadPkg/BlSupportSmm/BlSupportSmm.h
Fix case match in <Protocol/MpService.h> to avoid build failure on
Linux.
=> UefiPayloadPkg: Fix case of protocol

MdeModulePkg/Bus/Pci/NvmExpressDxe/NvmExpress.c, MdeModulePkg/Bus/Pci/NvmExpressPei/NvmExpressPei.c
Patch sent at: https://edk2.groups.io/g/devel/message/87249
Ref: https://bugzilla.tianocore.org/show_bug.cgi?id=3856
Currently this NvmeExpress Driver do not support metadata handling.
According to the NVME specs, metadata may be transferred to the host after
the logical block data. It can overrun the input buffer which may only
be the size of logical block data.
Add a check to return not support for the namespaces formatted with
metadata.
v2 changes:
- Change debug log level from INFO to ERROR
- Change to if (NamespaceData->LbaFormat[LbaFmtIdx].Ms != 0)
v1: https://edk2.groups.io/g/devel/message/87242
Signed-off-by: Hua Ma <hua.ma@intel.com> …
=> MdeModulePkg: Add a check for metadata size in NvmExpress Driver

UefiPayloadPkg/Library/PlatformBootManagerLib/PlatformBootManager.c, UefiPayloadPkg/Library/PlatformBootManagerLib/PlatformBootManagerLib.inf, UefiPayloadPkg/UefiPayloadPkg.dec, UefiPayloadPkg/UefiPayloadPkg.dsc
Provide a build option to use [Esc] instead of [F2] for devices
such as Chromebooks that don't have F-keys.
Reviewed-by: Ray Ni <ray.ni@Intel.com>
=> UefiPayloadPkg: Make Boot Manager Key configurable

.pytool/Plugin/UncrustifyCheck/Readme.md, .pytool/Plugin/UncrustifyCheck/UncrustifyCheck.py
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=3808
Changes the default for the "OutputFileDiffs" configuration option
to "True" so the formatting suggestions detected by Uncrustify
will be output in the test case log. The diff is printed in unified
diff format.
This was disabled by default during the initial enabling of
Uncrustify to reduce overall execution time of the plugin against
the codebase due to the large number of changes detected.
Reviewed-by: Rebecca Cran <quic_rcran@quicinc.com>
Reviewed-by: Michael D Kinney …
=> .pytool/Plugin/UncrustifyCheck: Output file diffs by default

MdeModulePkg/Bus/Ufs/UfsPassThruDxe/UfsPassThru.c, MdeModulePkg/Bus/Ufs/UfsPassThruDxe/UfsPassThruHci.c, MdeModulePkg/Include/Protocol/UfsHostControllerPlatform.h
Patch sent at: https://edk2.groups.io/g/devel/message/87349
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3851
When the UFS card comes out of Manufacturer, bRefClkFreq attribute is set
to 1h on the UFS card as per the Manufacturer Default Value
specified by the spec JESD220*. However, depends on the UFS host system
environment, it need to be set to the correct value.
Reference Clock Frequency value
0h:19.2 MHz
1h: 26 MHz
2h: 38.4 MHz
3h: Obsolete
Others: Reserved
Cc: Wu Hao A <hao.a.wu@intel.com>
Cc: Albecki Mateusz <mateusz.albecki@intel.com>
Signed-off-by: Purna Chandra Rao Bandaru <purna.chandra.rao.bandaru@intel.com>
=> MdeModulePkg: Add bRefClkFreq card attribute programming support

RedfishPkg/PrivateLibrary/RedfishLib/edk2libredfish/src/payload.c
The calloc memory is not free when function collectionEvalOp
return in the halfway.
Reviewed-by: Abner Chang <abner.chang@hpe.com>
=> RedfishPkg: fix memory leak issue

Maintainers.txt
Add maintainer and reviewer for the edk2 Redfish-related modules
under EmulatorPkg.
=> Maintainers: Update Maintainers.txt for edk2 Redfish modules

DynamicTablesPkg/Library/Acpi/Arm/AcpiDbg2LibArm/Dbg2Generator.c
According to the Debug Port Table 2 (DBG2) specification,
February 17, 2021, the NamespaceString is a NULL terminated
ASCII string that consists of a fully qualified reference
to the object that represents the serial port device in the
ACPI namespace.
The DBG2 table generator did not populate the full device
path for the serial port device, and this results in a FWTS
test failure.
Therefore, populate the full namespace device path for the
serial port in DBG2 table.
Tested-by: Jagadeesh Ujja <Jagadeesh.Ujja@arm.com>
Tested-by: Sunny Wang <sunny.wang@arm.com>
=> DynamicTablesPkg: Fix serial port namespace path in DBG2

BaseTools/Source/C/GenFw/Elf64Convert.c, BaseTools/Source/C/GenFw/ElfConvert.c, BaseTools/Source/C/GenFw/ElfConvert.h, BaseTools/Source/C/GenFw/GenFw.c, BaseTools/Source/C/Include/IndustryStandard/PeImage.h
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3802
Since PRM module needs to support export table in PE-COFF, we'll
enhance GenFw tool to support this.
Add one export flag in GenFw tool. If export flag is set:
Step1: Scan ELF symbol table based on PRM module descriptor to get
descriptor offset address;
Step2: Find PRM handlers number and name in COFF file based on the
address from step1;
Step3: Write PRM info such as handler name and export RVA into COFF
export table.
PRM option currently only supports DXE RUNTIME driver and X64 arch.
Signed-off-by: Lixia Huang <lisa.huang@intel.com>
=> BaseTools/GenFw: Enhance GenFw to support PRM GCC build

EmulatorPkg/Library/RedfishPlatformCredentialLib/RedfishPlatformCredentialLib.c
https://bugzilla.tianocore.org/show_bug.cgi?id=3859
Platform Redfish credential library shouldn't stop the service at either EndOfDXE or ExitBootService notification. RedfishConfigureHandler UEFI driver is responsible to stop the Redfish service when EndOfDXE or ExitBootService event is triggered.
=> EmulatorPkg/RedfishPlatformCredentialLib: Don't stop Redfish service

IntelFsp2Pkg/Library/BaseFspDebugLibSerialPort/BaseFspDebugLibSerialPort.inf, IntelFsp2Pkg/Library/BaseFspDebugLibSerialPort/DebugLib.c, IntelFsp2Pkg/Library/BaseFspDebugLibSerialPort/X64/FspDebug.nasm
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=3833
Add BaseFspDebugLibSerialPort Support for X64.
=> IntelFsp2Pkg: BaseFspDebugLibSerialPort Support for X64

IntelFsp2Pkg/Include/PushPopRegsNasm.inc, IntelFsp2Pkg/Library/BaseFspSwitchStackLib/BaseFspSwitchStackLib.inf, IntelFsp2Pkg/Library/BaseFspSwitchStackLib/FspSwitchStackLib.c, IntelFsp2Pkg/Library/BaseFspSwitchStackLib/X64/Stack.nasm
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=3832
Add BaseFspSwitchStackLib Support for X64.
=> IntelFsp2Pkg: BaseFspSwitchStackLib Support for X64

MdeModulePkg/Bus/Pci/SdMmcPciHcDxe/SdMmcPciHcDxe.h, MdeModulePkg/Bus/Pci/SdMmcPciHcDxe/SdMmcPciHcDxe.inf, MdeModulePkg/MdeModulePkg.dec, MdeModulePkg/MdeModulePkg.uni
The default 1s timeout can delay boot splash on some hardware with no
benefit.
Signed-off-by: Matt DeVillier <matt.devillier@gmail.com>
=> MdeModulePkg/SdMmcPciHcDxe: Make timeout for SD card configurable

MdePkg/Include/IndustryStandard/Acpi40.h, MdePkg/Include/IndustryStandard/Acpi50.h, MdePkg/Include/IndustryStandard/Acpi51.h, MdePkg/Include/IndustryStandard/Acpi60.h, MdePkg/Include/IndustryStandard/Acpi61.h, MdePkg/Include/IndustryStandard/Acpi62.h, MdePkg/Include/IndustryStandard/Acpi63.h, MdePkg/Include/IndustryStandard/Acpi64.h
Patch sent at: https://edk2.groups.io/g/devel/message/87344
Starting from ACPI Specification Version 5.1 Errata B, the term
'Correctable' is no longer being used as an error severity of the
reported error in Chapter 18 APEI.
This commit will
a) For Acpi40.h & Acpi50.h
Add new macro EFI_ACPI_X_X_ERROR_SEVERITY_RECOVERABLE, since both the
terms 'Correctable' and 'Recoverable' are used to denote the same error
severity.
b) Header files starting from Acpi51.h to Acpi64.h
Add new macro EFI_ACPI_X_X_ERROR_SEVERITY_RECOVERABLE.
Keeps the origin EFI_ACPI_X_X_ERROR_SEVERITY_CORRECTABLE for compatibility
consideration, but add comments to mark it as deprecated and should no
longer be used.
Cc: Zhiguang Liu …
=> MdePkg/AcpiXX.h: Update Error Severity type for Generic Error Status Block

BaseTools/Source/Python/Workspace/DscBuildData.py
For the multiple SKU case, basetools generates multiple redundant
__FLEXIBLE_SIZE statement that is from the same line in dsc file.
This behavior causes the generated PcdValueInit.c file to have huge size,
and the compilation time is very long.
This patch is going to fix this issue.
=> BaseTools: Remove the redundant __FLEXIBLE_SIZE from PcdValueInit.c

CryptoPkg/Library/BaseCryptLib/Hash/CryptParallelHash.h, CryptoPkg/Library/Include/CrtLibSupport.h
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3885
Parallel hash patch redefines uint_64 type in CrtLibSupport.h
which has been defined in openssl/include/openssl/e_os2.h.
CryptMd5.c including e_os2.h cause redefinition bug.
=> CryptoPkg: Redefinition bug in CrtLibSupport.h.

BaseTools/Source/C/DevicePath/GNUmakefile, BaseTools/Source/C/GenFfs/GenFfs.c, BaseTools/Source/C/GenSec/GenSec.c, BaseTools/Source/C/LzmaCompress/Sdk/C/LzmaEnc.c
Two bugfixes (patches 1+2), one workaround (#3).
Gerd Hoffmann (3):
BaseTools: fix gcc12 warning
BaseTools: fix gcc12 warning
Basetools: turn off gcc12 warning
=> BaseTools: patches to build with gcc12

BaseTools/Source/Python/Ecc/MetaFileWorkspace/MetaFileParser.py
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=3872
When doing ecc inf version check, the decimal type version number
like 1.27 is treated as invalid version.
So the code should be updated to support decimal type version number.
=> BaseTools:Support decimal version number in ECC check

MdeModulePkg/Bus/Ufs/UfsPassThruDxe/UfsPassThru.c
Patch sent at: https://edk2.groups.io/g/devel/message/88028
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3886
bRefClkFreq UFS card attribute need to be read and written after successful
fDeviceInit and NOP response so that link will be stable.
Cc: Wu Hao A <hao.a.wu@intel.com>
Cc: Albecki Mateusz <mateusz.albecki@intel.com>
Signed-off-by: Purna Chandra Rao Bandaru <purna.chandra.rao.bandaru@intel.com>
=> MdeModulePkg/Ufs: bRefClkFreq attribute be programmed after fDeviceInit

UefiPayloadPkg/UefiPayloadPkg.ci.yaml
Remove a duplicated entry to fix a CI error.
Acked-by: Ray Ni <ray.ni@intel.com>
Reviewed-by: Dun Tan <dun.tan@intel.com>
=> UefiPayloadPkg/UefiPayloadPkg.ci.yaml: Remove duplicated entry

UefiPayloadPkg/UefiPayloadPkg.dsc
On windows build, need add "-DPLATFORMX64_ENABLE=TRUE" in the build
command line beside -DNETWORK_DRIVER_ENABLE=TRUE in order build
network features. So update DSC to set PLATFORMX64_ENABLE to TRUE
when building network feature.
On Linux build, DSC file should not have PcdAllowHttpConnections
without building network feature, else it would cause build error.
Reviewed-by Sean Rhodes <sean@starlabs.systems>
=> UefiPayloadPkg: Fix build error

UefiPayloadPkg/Library/PciHostBridgeLib/PciHostBridgeSupport.c
On modern platforms with TBT devices the coreboot resource allocator
opens large PCI bridge MMIO windows above 4GiB to place hotplugable
PCI BARs there as they won't fit below 4GiB. In addition modern
GPGPU devices have very big PCI bars that doesn't fit below 4GiB.
The PciHostBridgeLib made lots of assumptions about the coreboot
resource allocator that were not verified at runtime and are no
longer true.
Remove all of the 'coreboot specific' code and implement the same
logic as OvmfPkg's ScanForRootBridges.
Fixes assertion
"ASSERT [PciHostBridgeDxe] Bridge->Mem.Limit < 0x0000000100000000ULL".
Tested with coreboot as bootloader on platforms that have PCI resources
above 4GiB and on platforms that don't have resources above 4GiB.
Signed-off-by: Patrick Rudolph …
=> UefiPayloadPkg: Fix PciHostBridgeLib

OvmfPkg/CloudHv/CloudHvX64.dsc, OvmfPkg/OvmfPkgIa32.dsc, OvmfPkg/OvmfPkgIa32X64.dsc, OvmfPkg/OvmfPkgX64.dsc
REF? https://bugzilla.tianocore.org/show_bug.cgi?id=3861
UefiCpuPkg define a new Protocol with the new services
SmmWaitForAllProcessor(), which can be used by SMI handler
to optionally wait for other APs to complete SMM rendezvous in
relaxed AP mode.
VariableSmm driver need use SmmCpuRendezvousLib, So add
SmmCpuRendezvousLib in OvmfPkg.
Cc: Sebastien Boeuf <sebastien.boeuf@intel.com>
=> OvmfPkg: Add dependency of VariableSmm driver to make it work normally.

BaseTools/Scripts/efi_debugging.py, BaseTools/Scripts/efi_gdb.py, BaseTools/Scripts/efi_lldb.py
This patch set adds debugging support for gdb and lldb.
It also adds generic debugging classes that use a file like object to make it easy to import into any debugger that supports Python.
Changes from v1 to v2:
- Moved scripts from the root of the repo into BaseTools/Scripts.
- Fixed typo of "RISCV" as "RISKV".
Testing:
- Tested gdb on Ubuntu and lldb on macOS for IA32 and X64.
- Tested gdb on openSUSE for AARCH64.
Rebecca Cran (3):
BaseTools: efi_debugging.py: Add debugger agnostic dbg Python Classes
BaseTools: Scripts/efi_gdb.py: Add gdb EFI commands and pretty Print
BaseTools: Scripts/efi_lldb.py: Add lldb EFI commands and pretty Print
=> BaseTools: Add support for gdb and lldb

UefiPayloadPkg/UniversalPayloadBuild.py
The payload entry module should support to build as IA32 image
beside X64 image so that it could work with 32bit bootloaders.
This patch adds a option build parameter for arch selection.
=> UefiPayloadPkg: Support IA32 Build

UefiPayloadPkg/UefiPayloadPkg.dsc
REF? https://bugzilla.tianocore.org/show_bug.cgi?id=3882
UefiCpuPkg define a new Protocol with the new services
SmmWaitForAllProcessor(), which can be used by SMI handler
to optionally wait for other APs to complete SMM rendezvous in
relaxed AP mode.
VariableSmm driver need use SmmCpuRendezvousLib, So add
SmmCpuRendezvousLib dependency in UefiPayloadPkg which use
VariableSmm driver.
=> UefiPayloadPkg: Add dependency of VariableSmm driver.

BaseTools/Source/C/DevicePath/GNUmakefile
Fix the DevicePath tool build failure that was introduced by
the fixes: 22130dcd98b4 ("Basetools: turn off gcc12 warning").
Failure cases are:
1. clang 13.1.6 on macOS
2. gcc5.4
Reported-by: Rebecca Cran <rebecca@bsdio.com>
Reported-by: Yuwei Chen <yuwei.chen@intel.com>
=> BaseTools: Fix DevicePath tool build failure issue

CryptoPkg/CryptoPkg.ci.yaml, CryptoPkg/Library/BaseCryptLib/SysCall/CrtWrapper.c, CryptoPkg/Library/Include/CrtLibSupport.h, CryptoPkg/Library/Include/fcntl.h, CryptoPkg/Test/UnitTest/Library/BaseCryptLib/DhTests.c
First batch of patches which update CrtLibSupport so it has everything
needed to build openssl3.  Also a testcase update for openssl3.
This does not update the openssl submodule, that'll happen in a
followup patch series.
v3:
- move strcpy() from .h to .c file.
- pick up review tags
v2:
- rebase to latest master.
- add codestyle exception for fcntl.h.
Gerd Hoffmann (8):
CryptoPkg/CrtLibSupport: add fcntl.h
CryptoPkg/CrtLibSupport: add strstr()
CryptoPkg/CrtLibSupport: add INT_MIN
CryptoPkg/CrtLibSupport: add UINT_MAX
CryptoPkg/CrtLibSupport: add MODULESDIR
CryptoPkg/CrtLibSupport: add off_t
CryptoPkg/CrtLibSupport: fix strcpy
CryptoPkg/UnitTest: fix DH testcase
CryptoPkg/Library/Include/CrtLibSupport.h            | 12 +++++++++++-
CryptoPkg/Library/Include/fcntl.h                    |  9 …
=> CryptoPkg updates for openssl 3.0

pip-requirements.txt
Synced the basetools patch from edk2 repo to
edk2-basetools repo. Update the basetools pip module version
to the latest.
=> pip-requirements.txt: Update basetools version to 0.1.17

Maintainers.txt
Reviewed-by: Michael Kubacki <mikuback@linux.microsoft.com>
=> Maintainers.txt: Add Michael Kubacki as UnitTestFrameworkPkg maintainer

CryptoPkg/CryptoPkg.dec, CryptoPkg/Library/Include/openssl/opensslconf.h, CryptoPkg/Library/IntrinsicLib/Ia32/MathLlmul.asm, CryptoPkg/Library/IntrinsicLib/Ia32/MathLlshr.asm, CryptoPkg/Library/IntrinsicLib/IntrinsicLib.inf, CryptoPkg/Library/OpensslLib/OpensslLib.inf, CryptoPkg/Library/OpensslLib/OpensslLibCrypto.inf, CryptoPkg/Library/OpensslLib/process_files.pl
EDK2 has Enabled a feature which allow SOURCE section in INF files to
use Pcd to customize source files list. If Pcd equal to FALSE, this 
file will not be compiled.
https://github.com/tianocore/edk2/commit/
bf9230a9f3dde065c3c8b4175ccd32e44e8f0362
The patches add a customizable EC feature to CryptoPkg by this feature.
If Pcd equal to FALSE(Diabled), the binary size will not be changed.
Size diff(Bytes):
| CryptDxe.efi | CryptPei.efi | CryptSmm.efi |
Before   |   815,616    |   540,544    |   563,712    |
Diabled  |   815,616    |   540,544    |   563,712    |
Enabled  |   1,008,352  |   721,408    |   744,832    |
Signed-off-by: yi1 li <yi1.li@intel.com>
yi1 li …
=> CryptoPkg: Enable ECC in openssllib by a customize-able way

CryptoPkg/Library/TlsLibNull/TlsConfigNull.c
MU_CHANGE tags are used in a different project (Project Mu) to
highlight deviations from Tianocore. Therefore, the comments are
not needed when the changes are present in a Tianocore repository.
=> CryptoPkg/TlsLibNull: Remove MU_CHANGE comment markers

MdePkg/Include/ConfidentialComputingGuestAttr.h, MdePkg/Include/Library/CcProbeLib.h, MdePkg/Library/BaseIoLibIntrinsic/BaseIoLibIntrinsicSev.inf, MdePkg/Library/BaseIoLibIntrinsic/IoLibInternalTdx.c, MdePkg/Library/CcProbeLibNull/CcProbeLibNull.c, MdePkg/Library/CcProbeLibNull/CcProbeLibNull.inf, MdePkg/MdePkg.dec, MdePkg/MdePkg.dsc, OvmfPkg/AmdSev/AmdSevX64.dsc, OvmfPkg/Bhyve/BhyveX64.dsc, OvmfPkg/CloudHv/CloudHvX64.dsc, OvmfPkg/Include/WorkArea.h, OvmfPkg/IntelTdx/IntelTdxX64.dsc, OvmfPkg/IntelTdx/Sec/SecMain.c, OvmfPkg/IntelTdx/Sec/SecMain.inf, OvmfPkg/Library/BaseMemEncryptSevLib/PeiMemEncryptSevLibInternal.c, OvmfPkg/Library/BaseMemEncryptSevLib/SecMemEncryptSevLibInternal.c, OvmfPkg/Library/CcProbeLib/CcProbeLib.c, OvmfPkg/Library/CcProbeLib/CcProbeLib.inf, OvmfPkg/Library/QemuFwCfgLib/QemuFwCfgPei.c, OvmfPkg/Microvm/MicrovmX64.dsc, OvmfPkg/OvmfPkgIa32.dsc, OvmfPkg/OvmfPkgIa32X64.dsc, OvmfPkg/OvmfPkgX64.dsc, OvmfPkg/OvmfXen.dsc, OvmfPkg/Sec/AmdSev.c, OvmfPkg/Sec/SecMain.c, OvmfPkg/Sec/SecMain.inf
BZ: https://bugzilla.tianocore.org/show_bug.cgi?id=3902
Bad IO performance in SEC phase is observed after TDX features was
introduced. (after commit b6b2de884864 - "MdePkg: Support mmio for
Tdx guest in BaseIoLibIntrinsic").
This is because IsTdxGuest() will be called in each MMIO operation.
It is trying to cache the result of the probe in the efi data segment.
However, that doesn't work in SEC, because the data segment is read only
(so the write seems to succeed but a read will always return the
original value), leading to us calling TdIsEnabled() check for every
mmio we do, which is causing the slowdown because it's very expensive.
CcProbe is introduced in this patch-set. It is called in
BaseIoLibIntrinsicSev instead of IsTdxGuest. There are 2 versions of
the CcProbeLib. Null instance …
=> Introduce CcProbe in MdePkg

CryptoPkg/Library/BaseCryptLib/SysCall/CrtWrapper.c, CryptoPkg/Library/Include/CrtLibSupport.h
Drop 'restrict' keyword which older visual studio compiler
versions complain about.
Fixes: fab6285a73c4 ("CryptoPkg/CrtLibSupport: fix strcpy")
=> CryptoPkg/Crt: fix strcpy build on older VS compilers

PrmPkg/Library/DxePrmContextBufferLib/UnitTest/DxePrmContextBufferLibUnitTest.c
https://bugzilla.tianocore.org/show_bug.cgi?id=3905
Fixes GCC compilation errors in DxePrmContextBufferLibUnitTest.c.
Cc: Ankit Sinha <ankit.sinha@intel.com>
Reviewed-by: Ankit Sinha <ankit.sinha@intel.com>
=> PrmPkg/DxePrmContextBufferLib: Fix unit test GCC compilation errors

OvmfPkg/OvmfPkgX64.fdf
BZ: https://bugzilla.tianocore.org/show_bug.cgi?id=3904
TdxDxe driver is introduced for Intel TDX feature. Unfortunately, this
driver also breaks boot process in SEV-ES guest. The root cause is in
the PciLib which is imported by TdxDxe driver.
In a SEV-ES guest the AmdSevDxe driver performs a
MemEncryptSevClearMmioPageEncMask() call against the
PcdPciExpressBaseAddress range to mark it shared/unencrypted. However,
the TdxDxe driver is loaded before the AmdSevDxe driver, and the PciLib
in TdxDxe is DxePciLibI440FxQ35 which will access the
PcdPciExpressBaseAddress range. Since the range has not been marked
shared/unencrypted, the #VC handler terminates the guest for trying to
do MMIO to an encrypted region.
Adjusting the load sequence of TdxDxe and AmdSevDxe can fix the issue.
Cc: Brijesh …
=> OvmfPkg/OvmfPkgX64: Adjust load sequence of TdxDxe and AmdSevDxe driver

CryptoPkg/Library/BaseCryptLib/BaseCryptLib.inf, CryptoPkg/Library/BaseCryptLib/PeiCryptLib.inf, CryptoPkg/Library/BaseCryptLib/RuntimeCryptLib.inf, CryptoPkg/Library/BaseCryptLib/SmmCryptLib.inf, CryptoPkg/Library/BaseCryptLib/UnitTestHostBaseCryptLib.inf, CryptoPkg/Library/OpensslLib/OpensslLib.inf, CryptoPkg/Library/OpensslLib/OpensslLibCrypto.inf, CryptoPkg/Library/TlsLib/TlsLib.inf
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=3679
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=3828
Tls/Base/Pei/Smm/RuntimeCryptLib.inf will use OpensslLib,
and the opensslconf.h in openssllib will use PcdEcEnabled,
but it is not declared in the inf file now,
it will cause warnings in some compilers.
Signed-off-by: Yi Li <yi1.li@intel.com>
=> CryptoPkg: Declare PcdEcEnabled in Library consuming OpensslLib

UefiPayloadPkg/UniversalPayloadBuild.py
The ObjCopyFlag and EntryOutputDir need to be modified when
building IA32 UniversalPayload Entry
Signed-off-by: Dun Tan <dun.tan@intel.com>
=> UefiPayloadPkg: Fix IA32 entry build failure

BaseTools/Source/Python/AutoGen/AutoGenWorker.py, BaseTools/Source/Python/AutoGen/DataPipe.py, BaseTools/Source/Python/Workspace/DscBuildData.py, BaseTools/Source/Python/Workspace/InfBuildData.py, BaseTools/Source/Python/Workspace/WorkspaceCommon.py
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3828
This is a bugfix of
bf9230a9f3dde065c3c8b4175ccd32e44e8f0362.
1.In the current code, gPlatformFinalPcd will save all PCDs used at
whole compile process, which wastes runtime memory and is unnecessary.
This patch makes gPlatformFinalPcd save only the PCDes which are
assigned in the DSC file, and the PCD that has not been assigned will
use the default value in DEC.
2.During the compilation process, gPlatformFinalPcd may be lost, and
the current code cannot selectively assign PCD in DSC by specifying ARCH.
This patch moves gPlatformFinalPcd into datapipe and modifies the
assignment logicto fix this.
Signed-off-by: yi1 li <yi1.li@intel.com>
Reviewed-by: Bob …
=> BaseTools: Move gPlatformFinalPcd to Datapipe and optimize size

.azurepipelines/templates/pr-gate-build-job.yml
The NOOPT build target is used for host-based unit tests. This
change adds the NOOPT target for all packages to ensure that tests
are executed if present.
If the host-based DSC is not specified in the packages CI YAML file,
the host-based compiler plugin will be reported as a skipped test.
=>  .azurepipelines: Add NOOPT to all package builds

.pytool/Plugin/UncrustifyCheck/UncrustifyCheck.py
Adds a link to the log output that contains instructions on how find
detailed file formatting errors in the Azure DevOps UI.
=>  .pytool/Plugin/UncrustifyCheck: Add Azure DevOps UI debug instructions

OvmfPkg/OvmfPkgIa32.dsc
Was dropped by accident.
Fixes: b47575801e19 ("OvmfPkg: move tcg configuration to dsc and fdf include files")
=> OvmfPkg: restore CompatImageLoaderDxe chunk

OvmfPkg/Bhyve/AcpiPlatformDxe/AcpiPlatformDxe.inf, OvmfPkg/Bhyve/AcpiPlatformDxe/Bhyve.c, OvmfPkg/Bhyve/BhyveX64.dsc
﻿QemuFwCfg is much more powerful than BhyveFwCtl. Sadly, BhyveFwCtl
decided to use the same IO ports as QemuFwCfg. It's not possible to use
both interfaces simultaneously. So, prefer QemuFwCfg over BhyveFwCtl.
Signed-off-by: Corvin Köhne <c.koehne@beckhoff.com>
Acked-by: Peter Grehan <grehan@freebsd.org>
=> OvmfPkg/Bhyve: add support for QemuFwCfg

IntelFsp2Pkg/FspSecCore/FspSecCoreM.inf, IntelFsp2Pkg/FspSecCore/SecMain.h, IntelFsp2WrapperPkg/FspmWrapperPeim/FspmWrapperPeim.inf, IntelFsp2WrapperPkg/FspsWrapperPeim/FspsWrapperPeim.inf, MdePkg/MdeLibs.dsc.inc, OvmfPkg/Sec/SecMain.c, OvmfPkg/Sec/SecMain.inf, UefiCpuPkg/Library/BaseXApicLib/BaseXApicLib.c, UefiCpuPkg/Library/BaseXApicLib/BaseXApicLib.inf, UefiCpuPkg/Library/BaseXApicX2ApicLib/BaseXApicX2ApicLib.c, UefiCpuPkg/Library/BaseXApicX2ApicLib/BaseXApicX2ApicLib.inf, UefiCpuPkg/PiSmmCpuDxeSmm/PiSmmCpuDxeSmm.h, UefiCpuPkg/SecCore/SecCore.inf, UefiCpuPkg/SecCore/SecCoreNative.inf, UefiCpuPkg/SecCore/SecMain.h, UefiPayloadPkg/UefiPayloadEntry/UefiPayloadEntry.h, UefiPayloadPkg/UefiPayloadEntry/UefiPayloadEntry.inf, UefiPayloadPkg/UefiPayloadEntry/UniversalPayloadEntry.inf
There are two libraries: MdePkg/CpuLib and UefiCpuPkg/UefiCpuLib and
UefiCpuPkg/UefiCpuLib will be merged to MdePkg/CpuLib. To avoid build
failure, add CpuLib dependency to all modules that depend on UefiCpuLib.
=> Add CpuLib to module INFs that depend on UefiCpuLib.

.pytool/Readme.md
Fix misspelling of word "Prerequisites".
In the step 5 of the Prerequisites section, the python command was missing
the "-r" option, what the command really meant was to install from the given
requirements file, so fix that.
Cc: sean.brogan@microsoft.com
Cc: Bret.Barkelew@microsoft.com
Cc: michael.d.kinney@intel.com
Cc: gaoliming@byosoft.com.cn
Signed-off-by: Chao Li <lichao@loongson.cn>
=> .pytool: Fix python command error in self introduction doc

MdeModulePkg/Core/PiSmmCore/Pool.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3488
Current free pool routine from PiSmmCore will inspect memory guard status
for target buffer without considering pool headers. This could lead to
`IsMemoryGuarded` function to return incorrect results.
In that sense, allocating a 0 sized pool could cause an allocated buffer
directly points into a guard page, which is legal. However, trying to
free this pool will cause the routine changed in this commit to read XP
pages, which leads to page fault.
This change will inspect memory guarded with pool headers. This can avoid
errors when a pool content happens to be on a page boundary.
Cc: Liming …
=> MdeModulePkg: PiSmmCore: Inspect memory guarded with pool headers

OvmfPkg/OvmfPkgX64.dsc
BZ: https://bugzilla.tianocore.org/show_bug.cgi?id=3930
CcProbeLib is designed to check the vm guest type. The OvmfPkg/CcProbeLib
reads the OvmfWorkArea (0x80B000) to get the vm guest type which is
written by each guest (SEV or TDX guest). But in SMM drivers the access
to OvmfWorkArea is illegal. PiSmmCpuDxeSmm.inf is an example. It uses
IoLib which in OvmfPkgX64 BaseIoLibIntrinsicSev.inf is included. The
IoLib probes if the working guest is td guest by calling CcProbe().
So CcProbeLibNull will be included when SMM_REQUIRE is set. Currently
only TDVF uses CcProbe to check the guest type, and TDVF doesn't
support SMM, so this fix has no side-effect.
Cc: Dann …
=> OvmfPkg/OvmfPkgX64: Use different CcProbeLib when SMM is on or off

OvmfPkg/OvmfPkgIa32.fdf, OvmfPkg/OvmfPkgIa32X64.fdf, OvmfPkg/OvmfPkgX64.fdf, OvmfPkg/ResetVector/Ia32/AmdSev.asm, OvmfPkg/ResetVector/Main.asm, OvmfPkg/ResetVector/ResetVector.nasmb
The BaseMemEncryptSevLib functionality was updated to rely on the use of
the OVMF/SEV workarea to check for SEV guests. However, this area is only
updated when running the X64 OVMF build, not the hybrid Ia32/X64 build.
Base SEV support is allowed under the Ia32/X64 build, but it now fails
to boot as a result of the change.
Update the ResetVector code to check for SEV features when built for
32-bit mode, not just 64-bit mode (requiring updates to both the Ia32
and Ia32X64 fdf files).
Fixes: f1d1c337e7c0575da7fd248b2dd9cffc755940df
Cc: Michael …
=> OvmfPkg: Make an Ia32/X64 hybrid build work with SEV

OvmfPkg/TdxDxe/X64/ApRunLoop.nasm
In TDX, Application Processor busy-loops on Mailbox for OS to issue
MpProtectedModeWakeupCommandWakeup command to UEFI.  As the AP acking to
it, it clears the command member according to ACPI spec 6.4, 5.2.12.19
Multiprocessor Wakeup Structure: "The application processor need clear the
command to Noop(0) as the acknowledgement that the command is received."
However, AsmRelocateApMailBoxLoop wrongly clears WakeupVector.  Correctly
clear command instead of WakeupVector.
Without this patch, TD guest kernel fails to boot APs.
Fixes: fae5c1464d ("OvmfPkg: Add TdxDxe driver")
Signed-off-by: Isaku Yamahata <isaku.yamahata@intel.com>
Reviewed-by: Min Xu <min.m.xu@intel.com>
=> OvmfPkg: TdxDxe: Fix AsmRelocateApMailBoxLoop

OvmfPkg/VirtioGpuDxe/Gop.c
Build fix for `-t CLANG38 -b NOOPT -p OvmfPkg/OvmfPkgX64.dsc`.
Fixes: 5f6ecaa398ba ("OvmfPkg/VirtioGpuDxe: use GopQueryMode in GopSetMode")
Reported-by: Rebecca Cran <quic_rcran@quicinc.com>
=> OvmfPkg/VirtioGpuDxe: replace struct copy with CopyMem call

IntelFsp2Pkg/FspSecCore/X64/FspApiEntryT.nasm, IntelFsp2Pkg/Include/SaveRestoreSseAvxNasm.inc, IntelFsp2WrapperPkg/Library/SecFspWrapperPlatformSecLibSample/X64/SecEntry.nasm
[IntelFsp2Pkg: FSP_TEMP_RAM_INIT call must follow X64 Calling Convention](https://github.com/tianocore/edk2/commit/18eb92c5ff5e5f64226732f164ddad62e244fe76) 
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=3926
This API accept one parameter using RCX and this is consumed
in mutiple sub functions.
Signed-off-by: cbduggap <chinni.b.duggapu@intel.com>
=> Fsptempraminitx64

OvmfPkg/ResetVector/Ia32/AmdSev.asm
The SEV-ES bit of Fn800-001F[EAX] - Bit 3 is used for a host to
determine support for running SEV-ES guests. It should not be checked by
a guest to determine if it is running under SEV-ES. The guest should use
the SEV_STATUS MSR Bit 1 to determine if SEV-ES is enabled. This check
was not part of the original SEV-ES support and was added in
a91b700e38. Removing the check makes this code consistent with the
Linux kernel
Fixes: a91b700e38 ("Ovmf/ResetVector: Simplify and consolidate the SEV features checks")
Signed-off-by: Peter Gonda <pgonda@google.com>
Acked-by: Tom Lendacky <thomas.lendacky@amd.com>
=> OvmfPkg/ResetVector: Removing SEV-ES CPUID bit check

OvmfPkg/Library/PeilessStartupLib/Hob.c, OvmfPkg/TdxDxe/X64/ApRunLoop.nasm
From: Min Xu <min.m.xu@intel.com>
Date: 5/31/2022 10:31:15 PM
Subject: [PATCH 0/2] Fix 2 issues in TDVF
During the integration test with TDX upstreaming KVM/QEMU there are 2
issues are found. This patch-set are to fix these 2 issue.
- Fix TDVMCALL error in ApRunLoop.nasm
- Search EFI_RESOURCE_MEMORY_UNACCEPTED for Fw hoblist
*** BLURB HERE ***
Min Xu (2):
OvmfPkg: Fix TDVMCALL error in ApRunLoop.nasm
OvmfPkg: Search EFI_RESOURCE_MEMORY_UNACCEPTED for Fw hoblist
OvmfPkg/Library/PeilessStartupLib/Hob.c | 4 +++-
OvmfPkg/TdxDxe/X64/ApRunLoop.nasm       | …
=> Fix 2 issues in TDVF

OvmfPkg/CloudHv/CloudHvDefines.fdf.inc, OvmfPkg/CloudHv/CloudHvX64.dsc, OvmfPkg/CloudHv/CloudHvX64.fdf, OvmfPkg/Library/PlatformInitLib/Platform.c, OvmfPkg/Library/QemuBootOrderLib/QemuBootOrderLib.c
From: Sebastien Boeuf <sebastien.boeuf@intel.com>
The goal of this series is to reduce the amount of inappropriate PIO
and MMIO accesses generated by the firmware when running on Cloud
Hypervisor.
For MMIO accesses, it is about providing the right base address where
the firmware will be loaded by the VMM in order to avoid unexpected
accesses to some address ranges.
For PIO accesses, it is about preventing some read/write to be performed
in the first place, as we know the underlying device is not emulated by
Cloud Hypervisor.
Signed-off-by: Sebastien Boeuf <sebastien.boeuf@intel.com>
Sebastien Boeuf (4):
OvmfPkg: CloudHv: Fix FW_BASE_ADDRESS
OvmfPkg: Check for QemuFwCfg availability before accessing it
OvmfPkg: CloudHv: Rely on QemuFwCfgLibNull implementation
OvmfPkg: Don't access A20 gate …
=> OvmfPkg: CloudHv: Reduce PIO and MMIO accesses

BaseTools/Source/Python/Workspace/DscBuildData.py
The generated Makefile was missing a dependency.  This resulted in a
build-time race condition if the recursive make is multi-threaded and
shares job control.
Signed-off-by: Jake Garver <jake@nvidia.com>
=> BaseTools: Fix dependency issue in PcdValueInit

.pytool/Plugin/UncrustifyCheck/UncrustifyCheck.py
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3942
`IgnoreFiles` tag is specified in the CI YAML files in each individual
packages. The current logic for UncrustifyCheck script bases specified
file paths from workspace, which requires the package name to be included
in each entry.
This change updates the ignore checking logic to be based on current
package path in order to reduce redundancy. It also keeps the consistency
of `IgnoreFiles` field other pytools such as SpellCheck and EccCheck.
Reviewed-by: Michael …
=> .pytool: UncrustifyCheck: Set IgnoreFiles path relative to package path

BaseTools/Conf/tools_def.template, OvmfPkg/Sec/SecMain.c
The ebp/rbp register can either be used for the frame pointer or
as general purpose register.  With gcc (and clang) this depends
on the -f(no-)omit-frame-pointer switch.
This patch updates tools_def.template to explicitly set the compiler
option and also add a define to allow conditionally compile code.
The new define is used to fix stack switching in TemporaryRamMigration.
The ebp/rbp must not be touched when the compiler can use it as general
purpose register.  With version 12 gcc starts actually using the
register, so changing it leads to firmware crashes in some
configurations.
Ref: https://bugzilla.tianocore.org/show_bug.cgi?id=3934
Reported-by: Jiri Slaby <jirislaby@kernel.org>
=> OvmfPkg/Sec: fix stack switch

BaseTools/Conf/tools_def.template, OvmfPkg/Sec/SecMain.c
This reverts commit ff36b2550f94dc5fac838cf298ae5a23cfddf204.
Has no effect because GCC_IA32_CC_FLAGS and GCC_X64_CC_FLAGS are unused.
=> Revert "OvmfPkg/Sec: fix stack switch"

MdePkg/Library/SmmCpuRendezvousLibNull/SmmCpuRendezvousLibNull.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3931
Some drivers will break down when they use
SmmWaitForAllProcessor() which from SmmCpuRendezvousLibNull.c.
Removing the code "ASSERT(False)" will make consumer
work normally if they keep default setting for sync mode.
=> MdePkg: Remove "assert" from SmmCpuRendevousLibNull.c

ArmPkg/Library/ArmExceptionLib/ArmExceptionLib.c, MdeModulePkg/Core/Dxe/DxeMain/DxeMain.c
Commit e7abb94d1 removed InitializeCpuExceptionHandlersEx
and updated DxeMain to call InitializeCpuExceptionHandlers
for exception setup. But the old behavior that calls *Ex() sets
up the stack guard as well. To match the old behavior,
the patch calls InitializeSeparateExceptionStacks.
=> DxeMain: Fix the bug that StackGuard is not enabled

BaseTools/Source/Python/Workspace/WorkspaceCommon.py
When a module "Module" depends on a library instance "Lib1" which
depends on "Lib2" which depends on "Lib3" ... depends on "LibN",
but "LibN" doesn't support the type (e.g.: SEC) of the "Module", the
following error messages are printed by build tool:
<DSC path>(...): error 1001: Module by library instance [<LibN path>]
consumed by [<Module path>]
But it's unclear to user how LibN is consumed by the Module.
With the patch, following errors are printed:
<DSC path>(...): error 1001: Module by library instance [<LibN path>]
consumed by library instance [<Lib N-1 path>] which is
consumed by module[<Module path>]
It doesn't print all the intermediate library instances between the
Module and LibN but at least the path of Lib N-1 can help users
to help how to fix the build errors.
I hope this …
=> BaseTools: output the intermediate library instance when error occurs

UefiPayloadPkg/UefiPayloadPkg.dsc
The maximum Unicode string could be as large as 1800000 in certain
platforms when HII code builds the configuration strings.
This causes assertion in PrintLib.
The patch increases the PcdMaximumUnicodeStringLength to 1800000 to
avoid the assertion.
Signed-off-by: Yuanhao Xie <yuanhao.xie@intel.com>
=> UefiPayloadPkg: Increase the PcdMaximumUnicodeStringLength

UefiPayloadPkg/UefiPayloadEntry/X64/VirtualMemory.c
We observed page fault in the following situation:
1.PayloadEntry uses 2M entry in page table to cover DXE stack range.
2.In DXE phase, image protection code needs to mark some sub-range in
this 2M entry as readonly. So the the 2M page table entry is split to
512 4K entries, and some of the entries are marked as readonly.
(the entries covering stack still remain R/W)
3.Page fault exception happens when trying to access stack.
Always split the page table entry to 4K if it covers stack to avoid this
issue.
More discussion about this issue can be seen at below link
https://edk2.groups.io/g/devel/topic/91446026
Cc: Sean Rhodes …
=> UefiPayloadPkg: Always split page table entry to 4K if it covers stack.

UefiPayloadPkg/UniversalPayloadBuild.py
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3955
Currently, UPL freezed all PCD and only known UPL hob can hook DXE
Drivers behavior, add optional feature on UniversalPayloadBuild.py to
have another way to hook PCD value.
Reviewed-by: : Ray Ni <ray.ni@intel.com>
Signed-off-by: Gua Guo <gua.guo@intel.com>
=> UefiPayloadPkg: UniversalPayloadBuild.py to support --pcd feature

MdeModulePkg/Bus/Pci/XhciDxe/Xhci.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3954
Report error if reserved bits are not 0 for PageSize
Cc: Hao Wu <hao.a.wu@intel.com>
=> MdeModulePkg/XhciDxe: Check return value of XHC_PAGESIZE register

UefiCpuPkg/CpuDxe/CpuPageTable.c
A memory range can be submitted for attribute changes which is large
enough to not require a page split during the attribute update. Consider
the following scenario:
1. An attribute update removed the RW attribute on a range large enough
to not require a page split.
2. Later, an attributes update is called to re-add the RW attribute for
a subsection of that larger page which requires a split
3. The attribute update logic performs a page split, so now the parent
and child pages have matching attributes
4. Then, the attribute update logic changes the child page to have the
RW attribute.
5. The child page would then correctly have the RW attribute added but
the parent page would still have the RW attribute removed which will
cause an improper access violation.
The page being split should …
=> UefiCpuPkg: CpuDxe: Set RW and P Attributes on Split Pages

MdeModulePkg/Bus/Pci/XhciDxe/Xhci.c, MdeModulePkg/Bus/Pci/XhciDxe/Xhci.h, MdeModulePkg/Bus/Pci/XhciDxe/XhciReg.c, MdeModulePkg/Bus/Pci/XhciDxe/XhciReg.h
Add support process Port Speed field value of PORTSC according to
Supported Protocol Capability (define in xHCI spec 1.1)
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3914
The value of Port Speed field in PORTSC bit[10:13]
(xHCI spec 1.1 section 5.4.8) should be change to use this value to
query thru Protocol Speed ID (PSI) (xHCI spec 1.1 section 7.2.1)
in xHCI Supported Protocol Capability and return the value according
the Protocol Speed ID (PSIV) Dword.
With this mechanism may able to detect more kind of Protocol Speed
in USB3 and also compatiable with three kind of speed of USB2.
Cc: Jenny Huang <jenny.huang@intel.com>
Cc: More Shih <more.shih@intel.com>
Signed-off-by: Ian Chiu <Ian.chiu@intel.com>
Reviewed-by: Hao …
=> MdeModulePkg/XhciDxe: Add access xHCI Extended Capabilities Pointer

MdePkg/Include/IndustryStandard/Acpi62.h, MdePkg/Include/IndustryStandard/Acpi63.h, MdePkg/Include/IndustryStandard/Acpi64.h
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3915
This commit adds a definition type 7 Platform Capabilities Structure
and the struct definition for NFIT Table Structure Types.
The type has been added since ACPI Specification Version 6.2A.
Signed-off-by: Miki Shindo <miki.shindo@intel.com>
=> MdePkg/Acpi62: Add type 7 NFIT Platform Capabilities Structure support

UefiPayloadPkg/UniversalPayloadBuild.py
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3963
Based on UPL spec 2.12.2. Universal Payload Information Section,
it defines item "Attribute" on UPLD_INFO_HEADER for Debug build
should be "1", and Release build should be "0".
Currently, The value of item "Attribute" is always "0"
Signed-off-by: Gua Guo <gua.guo@intel.com>
=> UefiPayloadPkg: Align Attribute value with UPL spec

pip-requirements.txt
Upgrade the edk2-basetools version from 0.1.17 to 0.1.24
features and bug fixes:
1. Add FMMT Python Tool
2. Remove RVCT support
3. Fix dependency issue in PcdValueInit
4. Output the intermediate library instance when error occurs
5. Ecc: Fix grammar in Ecc error message
6. Fix the GenMake bug for .cpp source file
Acked-by: Michael Kubacki <michael.kubacki@microsoft.com>
=> pip-requirements.txt: Update basetools version to 0.1.24

ArmPkg/Drivers/ArmGic/ArmGicLib.c
The issue appears to have been introduced by:
41fb5d46 : ArmPkg/ArmGic: Use the GIC Redistributor instead of GIC Distributor for GICv3
The changes to ArmGicIsInterruptEnabled() introduced the error where the Boolean
result is assigned to Interrupts, but then the bit position check is performed
again (against the computed Boolean result instead of the interrupt mask) during
the return statement.
Fix removes erroneous test and relies on boolean test made at return.
Signed-off-by: Robbie King <robbiek@xsightlabs.com>
=> ArmPkg/Drivers: ArmGicIsInterruptEnabled returns incorrect value

NetworkPkg/WifiConnectionManagerDxe/WifiConnectionManagerDxe.vfr, NetworkPkg/WifiConnectionManagerDxe/WifiConnectionMgrConfigNVDataStruct.h, NetworkPkg/WifiConnectionManagerDxe/WifiConnectionMgrDxe.h, NetworkPkg/WifiConnectionManagerDxe/WifiConnectionMgrHiiConfigAccess.c, NetworkPkg/WifiConnectionManagerDxe/WifiConnectionMgrImpl.c, NetworkPkg/WifiConnectionManagerDxe/WifiConnectionMgrMisc.c
https://bugzilla.tianocore.org/show_bug.cgi?id=3961
Add below Wpa3 support:
WPA3-Personal:
Ieee80211AkmSuiteSAE                = 8
WPA3-Enterprise:
Ieee80211AkmSuite8021XSuiteB        = 11
Ieee80211AkmSuite8021XSuiteB192     = 12
Wi-Fi CERTIFIED Enhanced Open:
Ieee80211AkmSuiteOWE                = 18
Cc: Fu Siyuan <siyuan.fu@intel.com>
Cc: Wu Jiaxin <jiaxin.wu@intel.com>
=> NetworkPkg: Add Wi-Fi Wpa3 support in WifiConnectManager

UefiCpuPkg/SecCore/SecMain.c
Add debug messages to make it easier to verify PlatformSecLib
is passing the data properly.
Cc: Debkumar De <debkumar.de@intel.com>
Cc: Harry Han <harry.han@intel.com>
Cc: Catharine West <catharine.west@intel.com>
Signed-off-by: Isaac Oram <isaac.w.oram@intel.com>
=> UefiCpuPkg/SecCore: Add debug messages to illuminate data flow

ArmVirtPkg/ArmVirt.dsc.inc
The new changes in SecureBootVariableLib brought in a new dependency
of PlatformPKProtectionLib.
This change added the new library instance from SecurityPkg to resolve
ArmVirtPkg builds.
=> ArmVirtPkg: Pipeline: Resolving newly introduced dependency

BaseTools/.gitignore
The python BaseTools/Edk2ToolsBuild.py creates files in
BaseTools/BaseToolsBuild and should be ignored.
=> .gitignore: Ignore build tools build logs

UefiPayloadPkg/UefiPayloadPkg.dsc, UefiPayloadPkg/UefiPayloadPkg.fdf
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3979
Add CryptoDxe into UPL.
Drviers can locate protocol instead of building openssl lib into drivers.
This can reduce the binary size that UPL required.
Signed-off-by: PaytonX Hsieh <paytonx.hsieh@intel.com>
=> UefiPayloadPkg: Add CryptoDxe driver to UefiPayload

DynamicTablesPkg/Include/StandardNameSpaceObjects.h, DynamicTablesPkg/Library/Acpi/Arm/AcpiFadtLibArm/FadtGenerator.c
The CM_STD_OBJ_ACPI_TABLE_INFO.AcpiTableRevision can be used to specify
the major revision number of the ACPI table that the generator must use.
Although most ACPI tables only have a major revision number, the FADT
table additionally has a minor revision number.
The FADT generator currently defaults to setting the latest supported
ACPI revision for the FADT table i.e. ACPI 6.4. This means that the minor
revision for the FADT table is always set to 4 and there is no provision
for a user to specify the minor revision to be selected.
Therefore, update CM_STD_OBJ_ACPI_TABLE_INFO to introduce a new field
MinorRevision which can be used to specify the minor revision for an
ACPI table. Also update the FADT generator to validate the supported
FADT revisions ans use the specified minor revision …
=> DynamicTablesPkg: Add support to specify FADT minor revision

UefiPayloadPkg/Library/PlatformBootManagerLib/PlatformBootManager.c
Add 4 spaces before the boot prompt "F2 or Down..." so that the
spacing is equadistant from the top, which is spaced with a `\n`,
and the left.
=> UefiPayloadPkg/PlatformBootManagerLib: Evenly space boot prompt

BaseTools/Source/Python/AutoGen/GenMake.py, BaseTools/Source/Python/Workspace/DscBuildData.py
Currently BaseTools use 'cp' command for PcdValueInit and GenMake
process, as the command can not keep the time info of the source
file, which will cause incremental build issue in Linux system,
thus the '-p' need be added to keep the source file's attributes
in copy process.
This patch fixes this issue.
=> BaseTools: add '-p' for Linux 'cp' command.

BaseTools/Source/Python/Workspace/DscBuildData.py
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3965
Currently DSC LibraryClass precedence rule is not align with DSC Spec.
The expectation rule should be:
[LibraryClasses.$(ARCH)] < [LibraryClasses.Common.$(MODULE_TYPE)]
The actual behavior is:
[LibraryClasses.$(ARCH)] > [LibraryClasses.Common.$(MODULE_TYPE)]
This patch fixes the issue.
Cc: Long1 Huang <long1.huang@intel.com>
=> BaseTools: Fix DSC LibraryClass precedence rule

DynamicTablesPkg/Library/Acpi/Arm/AcpiSsdtPcieLibArm/SsdtPcieGenerator.c, DynamicTablesPkg/Library/FdtHwInfoParserLib/FdtUtility.h
Device Tree PCI interrupt flags use the convention described at
linux/Documentation/devicetree/bindings/interrupt-controller/arm,gic.yaml
The 3rd cell is the flags, encoded as follows:
bits[3:0] trigger type and level flags.
1 = low-to-high edge triggered
2 = high-to-low edge triggered (invalid for SPIs)
4 = active high level-sensitive
8 = active low level-sensitive (invalid for SPIs).
Fix the incorrect code.
=> DynamicTables: Fix DT PCI interrupt flags parsing

DynamicTablesPkg/Library/Common/SsdtSerialPortFixupLib/SsdtSerialPortFixupLib.c
SSDT tables describing an SBSA compatible serial port receive an '_HID'
value of 'ARMH0011'. This value represents a PL011 serial port.
This patch:
- Generates an 'ARMHB000' instead
- References the 'ACPI for Arm Components 1.0 - 2020' document
specifying the '_HID' values to use.
=> DynamicTablesPkg: Fix generated _HID value for SBSA

IntelFsp2Pkg/FspSecCore/FspSecCoreI.inf, IntelFsp2Pkg/FspSecCore/Ia32/FspApiEntryI.nasm, IntelFsp2Pkg/FspSecCore/SecFspApiChk.c, IntelFsp2Pkg/FspSecCore/X64/Fsp22ApiEntryS.nasm, IntelFsp2Pkg/FspSecCore/X64/FspApiEntryI.nasm, IntelFsp2Pkg/FspSecCore/X64/FspApiEntryM.nasm, IntelFsp2Pkg/FspSecCore/X64/FspApiEntryS.nasm, IntelFsp2Pkg/Include/FspEas/FspApi.h, IntelFsp2Pkg/Include/FspGlobalData.h, IntelFsp2Pkg/Include/Guid/FspHeaderFile.h, IntelFsp2Pkg/IntelFsp2Pkg.dsc, IntelFsp2Pkg/Tools/GenCfgOpt.py, IntelFsp2Pkg/Tools/SplitFspBin.py
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3993
Add FSP-I API entry point for SMM support.
Also update 64bit API entry code to assign ApiIdx to RAX
to avoid confusion.
Signed-off-by: Hongbin1 Zhang <hongbin1.zhang@intel.com>
=> IntelFsp2Pkg/FspSecCore: Add FSP-I API for SMM support.

Maintainers.txt
I've left SUSE last month, so the original email address is not
functional anymore. Update my email address to the new one.
Signed-off-by: Gary Lin <gary.lin@hpe.com>
=> Maintainers.txt: update Gary's email address

EmulatorPkg/Unix/Host/PosixFileSystem.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4001
This commit adds NULL check on memory allocation of the size
for FileName in ASCII string format at PosixFileSetInfo().
Signed-off-by: Miki Shindo <miki.shindo@intel.com>
=> EmulatorPkg/PosixFileSystem: Add NULL check on memory allocation

MdeModulePkg/Core/Dxe/Mem/Page.c
REF: https://https://bugzilla.tianocore.org/show_bug.cgi?id=3795
CC: Dandan Bi <dandan.bi@intel.com>
CC: Liming Gao <gaoliming@byosoft.com.cn>
Updated CoreInternalAllocatePages() to call PromoteMemoryResource() and
re-attempt the allocation if unable to convert the specified memory range
Signed-off-by: Stacy Howell <stacy.howell@intel.com>
=> MdeModulePkg/CoreDxe: Allow DXE Drivers to use untested memory

MdeModulePkg/Include/Guid/StatusCodeDataTypeDebug.h, MdeModulePkg/Library/DxeReportStatusCodeLib/ReportStatusCodeLib.c, MdeModulePkg/Library/PeiReportStatusCodeLib/ReportStatusCodeLib.c, MdeModulePkg/Library/RuntimeDxeReportStatusCodeLib/ReportStatusCodeLib.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3986
The EFI_STATUS_CODE_DATA_MAX_SIZE is defined as 200 in MdeModulePkg.
After reducing 96byte buffer for variable parameters it is limited to
only 104 char debug string. This is a non-necessary limitation.
This change sets EFI_STATUS_CODE_DATA_MAX_SIZE to 0x200, and moves
MAX_EXTENDED_DATA_SIZE definition to the same header file with value
of EFI_STATUS_CODE_DATA_MAX_SIZE + sizeof (EFI_STATUS_CODE_DATA)
which is used in ReportStatusCodeLib to support longer debug string.
Signed-off-by: Cosmo Lai <cosmo.lai@intel.com>
=> MdeModulePkg/Include: Long debug string is truncated to 104 char

BaseTools/Source/Python/Workspace/InfBuildData.py
This patch is a bug fix about FeatureFlagExpression in INF file:
INF [Source] section now unconditionally use Pcd default value in DEC
when handling FeatureFlagExpression, it is wrong.
If a Pcd value has been set in the DSC file, we should use latest
value in DSC instead of default value.
Signed-off-by: Yi Li <yi1.li@intel.com>
=> BaseTools: INF should use latest Pcd value instead of default value

BaseTools/Source/C/VolInfo/VolInfo.c
Alignment attribute is not a bitmask, therefore we need to compare
field value with all alignment defines.
Remove duplicate print statements. Unify indent with other attribute
print statements.
=> BaseTools/VolInfo: Correct alignment attributes display

BaseTools/Source/C/VolInfo/VolInfo.h
Currently sections with unknown types are displayed as
`EFI_SECTION_SMM_DEPEX` which is wrong.
Increase the highest value for the section type to 0x1C
for correct parsing.
Reviewed-by: Yuwei Chen<yuwei.chen@intel.com>
=> BaseTools/VolInfo: Increase define for highest section value

BaseTools/Source/C/VolInfo/VolInfo.c
- Correct typo in print statement,
- "BuildNumber" field is UINT16, therefore it needs "0x%04X" format
modifier,
- "VersionString" field is CHAR16, therefore the input data should be
processed to be displayed with "%s" printf modifier.
=> BaseTools/VolInfo: Correct EFI_SECTION_VERSION display

UefiCpuPkg/Library/CpuExceptionHandlerLib/CpuExceptionCommon.h, UefiCpuPkg/Library/CpuExceptionHandlerLib/Ia32/ExceptionHandlerAsm.nasm, UefiCpuPkg/Library/CpuExceptionHandlerLib/X64/Xcode5ExceptionHandlerAsm.nasm
Currently, "push byte %[Vector]" causes nasm warning when Vector is larger
than 0x7F. This is because push accepts a signed value, and byte means
signed int8. Maximum signed int8 is 0x7F.
When Vector is larger the 0x7F, for example, when Vector is 255, byte 255
turns to -1, and causes the warning "signed byte value exceeds".
To avoid such warning, use dword instead of byte, this will increase 3 bytes
for each IdtVector.
For IA32, the size of IdtVector will increase from 10 bytes to 13 bytes.
For X64, the size of IdtVector will increase from 15 bytes to 18 bytes.
Cc: Debkumar De <debkumar.de@intel.com>
Cc: Harry Han <harry.han@intel.com>
Cc: Catharine West <catharine.west@intel.com> …
=> UefiCpuPkg: Fix nasm warning "signed byte value exceeds"

UefiPayloadPkg/UefiPayloadPkg.dsc, UefiPayloadPkg/UefiPayloadPkg.fdf
REF : https://bugzilla.tianocore.org/show_bug.cgi?id=4006
Add CRYPTO_PROTOCOL_SUPPORT to decide CryptoDxe built into UPL.efi
If CRYPTO_PROTOCOL_SUPPORT is true, BIOS will use crypto protocol
instead of building OpensslLib into drivers.
Signed-off-by: PaytonX Hsieh <paytonx.hsieh@intel.com>
=> UefiPayloadPkg: Add macro to support selection of CryptoDxe driver

BaseTools/Source/C/VolInfo/VolInfo.c
Currently there is no labels for start and end of the encapsulation
sections. Therefore it is not possible to see where the encapsulation
section ends and another section starts.
Add labels for start and end of encapsulation sections to fix the
issue.
=> BaseTools/VolInfo: Show encapsulation sections

UefiPayloadPkg/PayloadLoaderPeim/ElfLib/Elf32Lib.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3984
Under function RolocateElfDynamic() in Elf32Lib.c
if (RelaAddress == MAX_UINT64) is always FALSE while RelaAddress is UINT32
Fix is to  modify if condition check to "if (RelaAddress == MAX_UINT32)"
Signed-off-by: James Lu <james.lu@intel.com>
=> UefiPayloadPkg: Fix RelaAddress type always mismatch in if condition

UefiPayloadPkg/Include/Coreboot.h, UefiPayloadPkg/Library/CbSerialPortLib/CbSerialPortLib.c, UefiPayloadPkg/Library/CbSerialPortLib/CbSerialPortLib.inf, UefiPayloadPkg/UefiPayloadPkg.dsc
Writes TianoCore debug logs into the CBMEM console ringbuffer, from
where the user can retrieve them with the `cbmem` userspace utility.
The intention is to aid in debugging non-fatal issues even in release
builds, or simply make TianoCore's logs available to those interested.
Consequently, MDEPKG_NDEBUG must be masked. As an in-memory debug
logging library, ASSERTs must be non-fatal to be seen, so they neither
dead-loop nor create a breakpoint. It is assumed that ASSERT() neither
enforces fatal conditions nor security integrity, as release builds do
not call DebugAssert() from the ASSERT macro.
More detailed debug logs are produced with the DEBUG_CODE macro, but
this guards other debug-related code throughout the codebase. To avoid
changing behaviour on release builds, this is only set …
=> UefiPayloadPkg: Add support for logging to CBMEM console

Maintainers.txt, OvmfPkg/AmdSev/AmdSevX64.dsc, OvmfPkg/CloudHv/CloudHvX64.dsc, OvmfPkg/IntelTdx/IntelTdxX64.dsc, OvmfPkg/Microvm/MicrovmX64.dsc, OvmfPkg/OvmfPkgIa32.dsc, OvmfPkg/OvmfPkgIa32X64.dsc, OvmfPkg/OvmfPkgX64.dsc
The email addresses for the reviewers of the MptScsi and
PvScsi in the OvmfPkg are no longer valid.  Remove the
reviewers for the MptScsi and PvScsi drivers until new
maintainers/reviewers can be identified.
Cc: Andrew Fish <[afish@apple.com](mailto:afish@apple.com)>
Cc: Leif Lindholm <[quic_llindhol@quicinc.com](mailto:quic_llindhol@quicinc.com)>
Cc: Ard Biesheuvel <[ardb+tianocore@kernel.org](mailto:ardb+tianocore@kernel.org)>
Cc: Jiewen Yao <[jiewen.yao@intel.com](mailto:jiewen.yao@intel.com)>
Cc: Jordan Justen <[jordan.l.justen@intel.com](mailto:jordan.l.justen@intel.com)>
Cc: Gerd Hoffmann <[kraxel@redhat.com](mailto:kraxel@redhat.com)>
Signed-off-by: Michael D Kinney <[michael.d.kinney@intel.com](mailto:michael.d.kinney@intel.com)>
=> OvmfPkg: Remove MptScsi and PvScsi reviewers

IntelFsp2Pkg/Tools/GenCfgOpt.py
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3993
Fixed a logic bug in GenCfgOpt.py to skip FSPI_UPD when platforms
do not support.
=> IntelFsp2Pkg: Fix GenCfgOpt bug for FSPI_UPD support.

OvmfPkg/QemuVideoDxe/Gop.c
Ensure that the PixelInformation field of the
EFI_GRAPHICS_OUTPUT_MODE_INFORMATION structure is zeroed out in
EFI_GRAPHICS_OUTPUT_PROTOCOL.QueryMode() and
EFI_GRAPHICS_OUTPUT_PROTOCOL.SetMode() when PixelFormat is
PixelBlueGreenRedReserved8BitPerColor.
According to UEFI 2.9 Section 12.9, PixelInformation field of the
EFI_GRAPHICS_OUTPUT_MODE_INFORMATION structure is valid only if
PixelFormat is PixelBitMask. This means that firmware is not required
to fill out the PixelInformation field for other PixelFormat types,
which implies that the QemuVideoDxe implementation is technically
correct.
However, not zeroing out those fields will leak the contents of the
memory returned by the memory allocator, so it is better to explicitly
set them to zero.
In addition, the SCT test suite relies on …
=> OvmfPkg/QemuVideoDxe: Zero out PixelInformation in QueryMode

Maintainers.txt
Cc: Marc-André Lureau <marcandre.lureau@redhat.com>
Cc: Stefan Berger <stefanb@linux.ibm.com>
Acked-by: Ard Biesheuvel <ardb+tianocore@kernel.org>
=> Maintainers.txt: Add missing Github IDs for OvmfPkg TPM/TGC modules

DynamicTablesPkg/Library/Acpi/Arm/AcpiIortLibArm/IortGenerator.c
Fix using RmrNodeCount uninitliased by initliasing it to zero. Also, add
an additional check for ACPI version. This fixes a crash running on
kvmtool.
Signed-off-by: Edward Pickup <edward.pickup@arm.com>
=> DynamicTablesPkg: Fix using RmrNodeCount unitlitialised

BaseTools/Source/C/GenSec/GenSec.c
=> BaseTools/GenSec: Fix typo

MdePkg/Library/UefiDevicePathLib/UefiDevicePathLibStandaloneMm.inf, MdePkg/MdePkg.dsc
REF: https://github.com/tianocore/edk2/pull/3130
The above PR removed UefiDevicePathLibStandaloneMm.inf, which is
a non-backwards compatible change and does not provide time for
downstream platforms to use the UefiDevicePathLibBase.inf.
Add UefiDevicePathLibStandaloneMm.inf back, but add comments that
it is deprecated and that UefiDevicePathLibBase.inf should be used
instead.
Cc: Liming Gao <gaoliming@byosoft.com.cn> [lgao4]
Cc: Zhiguang Liu <zhiguang.liu@intel.com> [LiuZhiguang001]
Cc: Mateusz Albecki <mateusz.albecki@intel.com>
Cc: Yanbo Huang <yanbo.huang@intel.com>
=> MdePkg/Library/UefiDevicePathLib: Add back StandaloneMm INF file

ShellPkg/Library/UefiShellDebug1CommandsLib/SmbiosView/PrintInfo.c
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=4014
If Configured Memory Speed is 65,535 MT/s or greater,
and the actual speed is stored in the Extended Configured Memory Speed
field. but current Smbiosview have no this logic.
Signed-off-by: Shengfengx Xue <shengfengx.xue@intel.com>
=> ShellPkg/SmbiosView: Display extended memory info in smbiosview -t 17

IntelFsp2Pkg/FspSecCore/Ia32/FspApiEntryM.nasm, IntelFsp2Pkg/FspSecCore/X64/FspApiEntryM.nasm
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4019
FSPM_ARCH2_UPD in FspApiEntryM.nasm was not up-to-date and
should be fixed for both IA32 and X64 builds.
=> IntelFsp2Pkg: FSPM_ARCH2_UPD mismatching bug.

MdeModulePkg/Universal/SmbiosDxe/SmbiosDxe.c, MdeModulePkg/Universal/SmbiosDxe/SmbiosDxe.h
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4013
For the SMBIOS version can be update by UPL,we create
the gUniversalPayloadSmbios3TableGuid HOB to store
the value then updated version.
Signed-off-by: KasimX Liu <kasimx.liu@intel.com>
=> MdeModulePkg: Update the SMBIOS version by UPL

MdeModulePkg/Application/DumpDynPcd/DumpDynPcd.c
Some print statements use format specifiers like %N/%H/%E/%B that are
only supported in the shell print functions. In the ordinary 'Print'
function they are just displayed as letters N/H/E/B.
Remove these unsupported format specifiers from the 'Print' statements
to fix the issue.
=> MdeModulePkg/DumpDynPcd: Remove unsupported format specifiers

BaseTools/Source/C/GenSec/GenSec.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4021
When the size of a EFI_SECTION_FREEFORM_SUBTYPE_GUID section required
the use of EFI_FREEFORM_SUBTYPE_GUID_SECTION2 header, set the section
type to EFI_SECTION_FREEFORM_SUBTYPE_GUID.
Cc: Konstantin Aladyshev <aladyshev22@gmail.com>
Acked-by: Konstantin Aladyshev <aladyshev22@gmail.com>
=> BaseTools/Source/C/GenSec: Fix EFI_SECTION_FREEFORM_SUBTYPE_GUID header

UefiPayloadPkg/Library/PciHostBridgeLib/PciHostBridgeSupport.c
Return PciRootBridges instead of NULL and set
PcdPciDisableBusEnumeration to FALSE when
root bridge count is zero.
Signed-off-by: Kavya <k.kavyax.sravanthi@intel.com>
=> UefiPayloadPkg: Return PciRootBridges instead of NULL

UefiPayloadPkg/UefiPayloadPkg.dsc, UefiPayloadPkg/UefiPayloadPkg.fdf
Add NVME_ENABLE macro to control NvmExpressDxe driver.
Signed-off-by: Kavya <k.kavyax.sravanthi@intel.com>
=> UefiPayloadPkg: Add macro to control NvmExpressDxe

UefiPayloadPkg/Library/PciHostBridgeLib/PciHostBridgeLib.c, UefiPayloadPkg/PayloadLoaderPeim/ElfLib/ElfLib.c, UefiPayloadPkg/UefiPayloadEntry/X64/VirtualMemory.c
https://bugzilla.tianocore.org/show_bug.cgi?id=4018
Coverity report FORWARD_NULL and OVERFLOW_BEFORE_WIDEN potential defect
in UefiPayloadPkg.
Signed-off-by: Gregx Yeh <gregx.yeh@intel.com>
=> UefiPayloadPkg: Fix Coverity report defect

ShellPkg/Library/UefiShellAcpiViewCommandLib/Parsers/Dsdt/DsdtParser.c
Bugzilla: 3995 (https://bugzilla.tianocore.org/show_bug.cgi?id=3995)
ACPI 6.4 spec states that if the revision field in the DSDT header is less
than 2, then all integers are restricted in width to 32 bits, including in
SSDTs.
Arm Base boot requirements state that platforms must conform to ACPI 6.3
or later, and that legacy tables are not supported.
Adds a check for this field and raise warning if revision is less
than 2 on arm.
Signed-off-by: Edward Pickup <edward.pickup@arm.com>
=> ShellPkg: Add revision check for DSDT Header on Arm

Maintainers.txt
Update package maintainers for below package/arch,
1. RISCV64 Architecture:
Abner is stepping out from RISC-V stuff for now and hand over edk2 RISC-V
responsibilities to Sunil.
Daniel Schaefer is no longer with HPE. Update his email address for
RISCV64 arch. He will keep helping on RISC-V stuff with his personal
email.
2. EmbeddedPkg:
Daniel Schaefer is no longer with HPE. Update his email address for
EmbeddedPkg.
3. EmulatorPkg and RedfishPkg:
Nickle Wang is no longer with HPE. Update his email address for
EmulatorPkg and RedfishPkg packages. He will use the personal email for
the time being until he gets ready with his next journey.
Cc: Daniel Schaefer …
=> Maintainers.txt: Update maintainers list

BaseTools/Source/C/DevicePath/GNUmakefile
On macOS, /usr/bin/gcc is clang, and so doesn't have
the -Wno-error=stringop-overflow flag that was added
for gcc 12.
Update the GNUmakefile for DevicePath to skip setting
that on macOS.
=> BaseTools: Fix DevicePath GNUmakefile for macOS

.azurepipelines/Ubuntu-PatchCheck.yml, .azurepipelines/templates/platform-build-run-steps.yml, .azurepipelines/templates/pr-gate-steps.yml
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=3891
Changes the Python version used in pipelines to 3.10.6 or greater
since that version introduces a fix (bp0-47231) for inconsistent
trailing slashes in tarfile longname directories.
This is required for stuart_update to succeed when handling a
web_dependency (e.g. GCC ARM compilers).
=> .azurepipelines: Use Python 3.10.6+

MdeModulePkg/Bus/Pci/NvmExpressPei/DevicePath.c, MdeModulePkg/Bus/Pci/NvmExpressPei/NvmExpressPei.c, MdeModulePkg/Bus/Pci/NvmExpressPei/NvmExpressPei.h, MdeModulePkg/Bus/Pci/NvmExpressPei/NvmExpressPei.inf
(https://edk2.groups.io/g/devel/message/92956)
This change modifies NvmExpressPei library to allow usage EDKII_PCI_DEVICE_PPI to manage Nvme device.
For now, the part that performs the enumeration and creates EDKII_PCI_DEVICE_PPI will be implemented in the silicon code.
Sample code can be seen here: https://github.com/mczaj/edk2-platforms/commit/d443062e58f9fba228869b54f2546d9735b3b506
unit test:
- verified the origin EDKII_NVM_EXPRESS_HOST_CONTROLLER_PPI flow in platform project, 
Nvme controller can successful initialize.
- merged https://github.com/mczaj/edk2-platforms/commit/d443062e58f9fba228869b54f2546d9735b3b506 to platform project
to enumerate pcie device and create the EDKII_PCI_DEVICE_PPI for Nvme, 
Nvme controller also can successful initialize by …
=> MdeModulePkg/NvmExpressPei: Use PCI_DEVICE_PPI to manage Nvme device

DynamicTablesPkg/Include/Library/AmlLib/AmlLib.h, DynamicTablesPkg/Library/Common/AmlLib/CodeGen/AmlCodeGen.c
Add APIs needed to build _DSD with different UUIDs.
This is per ACPI specification 6.4 s6.2.5.
Adds support for building data packages with format
Package {"Name", Integer}
=> DynamicTablesPkg: Add support to build _DSD

DynamicTablesPkg/Library/Common/AmlLib/CodeGen/AmlResourceDataCodeGen.c
Fix typo of "Address".
Signed-off-by: Rebecca Cran <rebecca@quicinc.com>
=> DynamicTablesPkg: Fix typo in AmlCodeGenRdMemory32Fixed doxygen comment

UefiPayloadPkg/UefiPayloadPkg.dsc
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4030
For the system support the Capsule function in UPL,
we replace the libraries for the Capsule driver.
Signed-off-by: KasimX Liu <kasimx.liu@intel.com>
=> UefiPayloadPkg: To replace the libraries for the capsule driver.

OvmfPkg/TdxDxe/TdxDxe.c
In previous implementation below Pci related PCDs were set based on the
ResourceDescriptor passed in TdHob.
- PcdPciMmio64Base / PcdPciMmio64Size
- PcdPciMmio32Base / PcdPciMmio32Size
- PcdPciIoBase / PcdPciIoSize
The PCDs will not be set if TdHob doesn't include these information. This
patch set the PCDs with the information initialized in PlatformInitLib
by default. Then TdxDxe will check the ResourceDescriptor in TdHob and
reset them if they're included.
=> OvmfPkg: Set default Pci PCDs in Tdx guest

IntelFsp2Pkg/FspSecCore/Fsp24SecCoreM.inf, IntelFsp2Pkg/FspSecCore/Fsp24SecCoreS.inf, IntelFsp2Pkg/FspSecCore/Ia32/Fsp24ApiEntryM.nasm, IntelFsp2Pkg/FspSecCore/Ia32/Fsp24ApiEntryS.nasm, IntelFsp2Pkg/FspSecCore/Ia32/FspApiEntryCommon.nasm, IntelFsp2Pkg/FspSecCore/SecFsp.c, IntelFsp2Pkg/FspSecCore/SecFspApiChk.c, IntelFsp2Pkg/FspSecCore/X64/Fsp24ApiEntryM.nasm, IntelFsp2Pkg/FspSecCore/X64/Fsp24ApiEntryS.nasm, IntelFsp2Pkg/FspSecCore/X64/FspApiEntryCommon.nasm
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3916
Adopt MultiPhase functions for both FspSecCoreS and FspSecCoreM. For backward compatibility, new INF are created for new modules.
=> IntelFsp2Pkg: Adopt FSP 2.4 MultiPhase functions.

UefiPayloadPkg/Library/BaseSerialPortLibHob/BaseSerialPortLibHob.c, UefiPayloadPkg/Library/BaseSerialPortLibHob/BaseSerialPortLibHob.inf, UefiPayloadPkg/UefiPayloadPkg.dsc
Add new Serial port library instance that consumes the HOB defined
in MdeModulePkg/Include/UniversalPayload/SerialPortInfo.h to support
multiple UART's.
Signed-off-by: Kavya <k.kavyax.sravanthi@intel.com>
=> UefiPayloadPkg: Implement a new SerialPortLib instance

OvmfPkg/Include/IndustryStandard/CloudHv.h
Both ACPI shutdown and ACPI PM timer devices has been moved to different port addresses in the latest version of Cloud Hypervisor. These changes need to be reflected on the OVMF firmware.
Signed-off-by: Sebastien Boeuf <sebastien.boeuf@intel.com>
=> OvmfPkg: Update I/O port related to ACPI devices for CloudHv

MdeModulePkg/Bus/Ata/AtaAtapiPassThru/AhciMode.h, MdeModulePkg/Bus/Ata/AtaAtapiPassThru/AtaAtapiPassThru.inf, MdeModulePkg/MdeModulePkg.dec, MdeModulePkg/MdeModulePkg.uni
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4011
AHCI commands are retried internally which prevents platform feature like drive password to process correctly entered password on subsequent attempts. PCD allows the platform to determine the number of retries.
Signed-off-by: Baraneedharan Anbazhagan <anbazhagan@hp.com>
=> MdeModulePkg: Use configurable PCD for AHCI command retries

MdeModulePkg/Bus/Ata/AhciPei/AhciPei.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4041
There is a mistake in getting MMIO base using PciDevicePpi that can lead to the data corruption.
Signed-off-by: Maciej Czajkowski <maciej.czajkowski@intel.com>
=> MdeModulePkg/AhciPei: Fix MMIO base assignment

BaseTools/Source/C/GenFv/GenFvInternalLib.c
https://bugzilla.tianocore.org/show_bug.cgi?id=4035 64bit FSP FV map file cannot be created correctly when using CLANG compiler. When compiling 64bit FSP with CLANG, there is no prefix symbol '_' added to function name. Hence FSP FV map file cannot be created properly. Updated the if condition for CLANG in GenFv to get the issue fixed.
Cc: Lee Hamel <lee.m.hamel@intel.com>
=> BaseTools: 64bit FSP FV map file cannot be created correctly

DynamicTablesPkg/DynamicTablesPkg.dec, DynamicTablesPkg/Library/Acpi/Arm/AcpiSsdtPcieLibArm/SsdtPcieGenerator.c, DynamicTablesPkg/Library/Acpi/Arm/AcpiSsdtPcieLibArm/SsdtPcieLibArm.inf
Add support for selecting to use index or segment number as UID and name. This allows the path of the nodes to be well known. For example, if the PCIe node needs to be notified from by an interrupt for a Generic Event Device
=> DynamicTablesPkg: AcpiSsdtPcieLibArm: Allow use of segment number as UID

IntelFsp2Pkg/FspSecCore/Ia32/Fsp24ApiEntryM.nasm, IntelFsp2Pkg/FspSecCore/X64/Fsp24ApiEntryM.nasm
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=4063 Added NvsBufferPtr to FSPM_UPD_COMMON_FSP24 in Fsp24ApiEntryM.nasm to align with FSP 2.4 SPEC.
Cc: Chinni B Duggapu <chinni.b.duggapu@intel.com>
=> IntelFsp2Pkg: NvsBufferPtr is missing in Fsp24ApiEntryM.nasm

IntelFsp2Pkg/FspSecCore/Ia32/FspApiEntryI.nasm, IntelFsp2Pkg/FspSecCore/X64/FspApiEntryI.nasm
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4049
Link error occurred in certain compiling environment when building FspSecCoreI: unresolved external symbol _TempRamInitApi.
=> IntelFsp2Pkg: Fix FspSecCoreI build failure.

UefiPayloadPkg/PayloadLoaderPeim/PayloadLoaderPeim.c
Fix the gcc build warning:
variable PldInfo set but not used [-Wunused-but-set-variable]
Signed-off-by: Gang Chen <gang.c.chen@intel.com>
=> UefiPayloadPkg/PayloadLoaderPeim: Remove GCC build warning

BaseTools/Edk2ToolsBuild.py
Current implementation of looking up toolchain will _insert_ the findings from vsvarsall.bat to existing path and potentially stuff the variable to exceed the length of maximal path length accepted by Windows.
This change updated the logic to use the discovered shell varialbes to replace the existing path, which is desirable in the specific use case.
Co-authored-by: Sean Brogan <sean.brogan@microsoft.com>
=> BaseTools: Edk2ToolsBuild: Fixing pipeline build due to path too long

BaseTools/Bin/nasm_ext_dep.yaml
The patch version is currently: "2.15.05"
When a formal semantic version validator is run against this version
it is recognized as being invalid due to the leading zero in the
patch which is not allowed per the Semantic Versioning Specification:
https://semver.org/#spec-item-2
The NuGet Gallery already reports the version without the leading
zero: https://www.nuget.org/packages/mu_nasm/2.15.5
This change simply removes the leading zero to prevent code such as
https://pypi.org/project/semantic-version/ from reporting a version error.
Signed-off-by: Michael Kubacki …
=> nasm_ext_dep.yaml: Remove leading zero in patch version

CryptoPkg/Library/BaseCryptLib/Pk/CryptPkcs7VerifyCommon.c
CertCtx is used to be defined as a struct and ZeroMem is called to init this struct. But now CertCtx is defined as a point, so use ZeroMem (&CertCtx, sizeof (CertCtx)) is not correct any more.
=> CryptoPkg/BaseCryptLib:Remove redundant init

RedfishPkg/Library/JsonLib/JsonLib.c
VS2019 reports build failure: "warning C4701: potentially uninitialized local variable 'Ucs2Str' used". Initial Ucs2Str to NULL at the beginning of function.
Signed-off-by: Nickle Wang <nicklew@nvidia.com>
=> RedfishPkg/JsonLib: Fix JsonLib build failure

CryptoPkg/Driver/Crypto.c, CryptoPkg/Include/Library/BaseCryptLib.h, CryptoPkg/Include/Pcd/PcdCryptoServiceFamilyEnable.h, CryptoPkg/Library/BaseCryptLib/Kdf/CryptHkdf.c, CryptoPkg/Library/BaseCryptLib/Kdf/CryptHkdfNull.c, CryptoPkg/Library/BaseCryptLibNull/Kdf/CryptHkdfNull.c, CryptoPkg/Library/BaseCryptLibOnProtocolPpi/CryptLib.c, CryptoPkg/Private/Protocol/Crypto.h, CryptoPkg/Test/UnitTest/Library/BaseCryptLib/BaseCryptLibUnitTests.c, CryptoPkg/Test/UnitTest/Library/BaseCryptLib/HkdfTests.c, CryptoPkg/Test/UnitTest/Library/BaseCryptLib/TestBaseCryptLib.h, CryptoPkg/Test/UnitTest/Library/BaseCryptLib/TestBaseCryptLibHost.inf, CryptoPkg/Test/UnitTest/Library/BaseCryptLib/TestBaseCryptLibShell.inf
Add Hkdf-SHA384 support and Hkdf-SHA256 extract and expand separately.
With this change, the size increase of BaseCyrptLib is about 6K bytes.
The new functions are verifed by the Host UnitTest.
And also it has been integratd in
https://github.com/tianocore/edk2-staging/tree/DeviceSecurity and been
verified.
All the code change is on the PR https://github.com/tianocore/edk2/pull/3224.
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4033
Signed-off-by: Qi Zhang <qi1.zhang@intel.com>
Qi Zhang (4):
CryptoPkg: add new Hkdf api definition in Crypt Lib.
CryptoPkg: add new Hkdf api in Crypt …
=> CryptoPkg: Add Hkdf SHA384 support

CryptoPkg/CryptoPkg.dsc, CryptoPkg/Driver/Crypto.c, CryptoPkg/Include/Library/BaseCryptLib.h, CryptoPkg/Include/Pcd/PcdCryptoServiceFamilyEnable.h, CryptoPkg/Library/BaseCryptLib/BaseCryptLib.inf, CryptoPkg/Library/BaseCryptLib/Cipher/CryptAeadAesGcm.c, CryptoPkg/Library/BaseCryptLib/Cipher/CryptAeadAesGcmNull.c, CryptoPkg/Library/BaseCryptLib/PeiCryptLib.inf, CryptoPkg/Library/BaseCryptLib/RuntimeCryptLib.inf, CryptoPkg/Library/BaseCryptLib/SmmCryptLib.inf, CryptoPkg/Library/BaseCryptLib/UnitTestHostBaseCryptLib.inf, CryptoPkg/Library/BaseCryptLibNull/BaseCryptLibNull.inf, CryptoPkg/Library/BaseCryptLibNull/Cipher/CryptAeadAesGcmNull.c, CryptoPkg/Library/BaseCryptLibOnProtocolPpi/CryptLib.c, CryptoPkg/Private/Protocol/Crypto.h, CryptoPkg/Test/UnitTest/Library/BaseCryptLib/AeadAesGcmTests.c, CryptoPkg/Test/UnitTest/Library/BaseCryptLib/BaseCryptLibUnitTests.c, CryptoPkg/Test/UnitTest/Library/BaseCryptLib/TestBaseCryptLib.h, CryptoPkg/Test/UnitTest/Library/BaseCryptLib/TestBaseCryptLibHost.inf, CryptoPkg/Test/UnitTest/Library/BaseCryptLib/TestBaseCryptLibShell.inf
Add AeadAesGcm Encrypt and Decrypt.
With this change, the size increase of BaseCyrptLib is about 60K bytes.
The new functions are verifed by the Host UnitTest.
And also it has been integratd in
https://github.com/tianocore/edk2-staging/tree/DeviceSecurity and been
verified.
All the code change is on the PR https://github.com/tianocore/edk2/pull/3224.
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4036
Signed-off-by: Qi Zhang <qi1.zhang@intel.com>
Qi Zhang (4):
CryptoPkg: add AeadAesGcm function() definition.
CryptoPkg: add AeadAesGcm support.
CryptoPkg: add AeadAesGcm to Crypto …
=> CryptoPkg: add AeadAesGcm support.

CryptoPkg/CryptoPkg.dsc
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4080
Add SynchronizationLib and MmServicesTableLib mappings that are required for the CRYPTO_SERVICES set to ALL or MIN_DXE_MIN_SMM builds.
Also update the family PCD settings for the PACKAGE and ALL profiles to enable all families.
=> CryptoPkg: Add missing library mappings to DSC file

CryptoPkg/Library/BaseCryptLib/SysCall/CrtWrapper.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4075
Fake BIO_snprintf() does not actually print anything to buf, it should return -1 as error.
0 will be considered a correct return value, the consumer may think that the buf is valid and parse the buffer.
please refer to bugzilla link for details.
Signed-off-by: Yi Li <yi1.li@intel.com>
reviewed-by: Jiewen Yao <Jiewen.yao@intel.com>
=> CryptoPkg: Fix pem heap-buffer-overflow due to BIO_snprintf()

IntelFsp2WrapperPkg/FspmWrapperPeim/FspmWrapperPeim.c, IntelFsp2WrapperPkg/FspmWrapperPeim/FspmWrapperPeim.inf, IntelFsp2WrapperPkg/FspsWrapperPeim/FspsWrapperPeim.c, IntelFsp2WrapperPkg/FspsWrapperPeim/FspsWrapperPeim.inf
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3916
Implement MultiPhase wrapper handlers and only call to MultiPhase handlers when FSP supports.
=> IntelFsp2WrapperPkg: Implement FSP 2.4 MultiPhase wrapper handlers.

MdeModulePkg/Bus/Pci/XhciDxe/XhciSched.c
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=4074
Update XhcEvaluateContext/XhcEvaluateContext64 to properly initialize the input context for Evaluate Context command.
Signed-off-by: jdzhang <jdzhang@kunluntech.com.cn>
=> MdeModulePkg/XhciDxe: Input context update for Evaluate Context command

MdeModulePkg/Bus/Pci/NonDiscoverablePciDeviceDxe/NonDiscoverablePciDeviceIo.c
Add support for partial free of non cached buffers. If a request for less than the full size is requested new allocations for the remaining head and tail of the buffer are added to the list. Added verification that Buffer is EFI_PAGE_SIZE aligned. The XHCI driver does this if the page size for the controller is >4KB.
=> MdeModulePkg/NonDiscoverablePciDeviceDxe: Allow partial FreeBuffer

BaseTools/Source/C/VolInfo/VolInfo.c
1. BaseTools/VolInfo: Correct buffer for GenCrc32 tool
2. BaseTools/VolInfo: Fix EFI_SECTION_GUID_DEFINED parsing
3. BaseTools/VolInfo: Increase GUID base name string
4. BaseTools/VolInfo: Parse apriori files
5. BaseTools/VolInfo: Update copyright information
6. BaseTools/VolInfo: Update file and section type strings
=> PR for VolInfo patch set

MdeModulePkg/Library/UefiBootManagerLib/BmBootDescription.c, MdeModulePkg/Library/UefiBootManagerLib/UefiBootManagerLib.inf
Add support for getting disk info from UFS devices.
=> MdeModulePkg/UefiBootManagerLib: Add Disk Info support for Ufs

UefiCpuPkg/PiSmmCpuDxeSmm/MpService.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4083
In CPU relaxed mode, it doesn't reset the value of mSmmMpSyncData->AllApArrivedWithException when BSP exit smm mode. So this patch will reset this variable.
=> UefiCpuPkg: Reset a parameter when BSP Exit in CPU relaxed mode.

MdeModulePkg/Bus/Pci/PciBusDxe/PciEnumeratorSupport.c
Per the section 3.3.5 SR-IOV spec v1.1, InitialVFs (0ch). InitialVFs indicates to SR-PCIM the number of VFs that are initially associated with the PF. The minimum value of InitialVFs is 0.
Below code is used to calculate SR-IOV reserved bus number, if InitialVFs =0, it maybe calculate the wrong bus number in this case.
LastVF = PFRid + FirstVFOffset + (PciIoDevice->InitialVFs - 1) * VFStride
we can fix it with below code:
if (PciIoDevice->InitialVFs == 0) {
PciIoDevice->ReservedBusNum = 0;
} else {
PFRid  = EFI_PCI_RID (Bus, Device, Func);
LastVF = PFRid + FirstVFOffset + (PciIoDevice->InitialVFs - 1) * VFStride;
//
// Calculate ReservedBusNum for this PF
//
PciIoDevice->ReservedBusNum = (UINT16)(EFI_PCI_BUS_OF_RID (LastVF) - Bus + 1); //
// Calculate ReservedBusNum for this PF
// …
=> MdeModulePkg: Handle InitialVFs=0 case for SR-IOV

CryptoPkg/Library/BaseCryptLib/SysCall/TimerWrapper.c
SECSPERDAY is 86400 which exceeds the limit of a UINT16 which is 65536. Therefore DayRemainder cannot use UINT16. This patch makes it UINT32.
Cc: Anthony Perard <anthony.perard@citrix.com>
Cc: Julien Grall <julien@xen.org>
Signed-off-by: Yuan Yu <yuanyu@google.com>
Reviewed-by: Ard Biesheuvel <ardb+tianocore@kernel.org>
=> CryptoPkg: Fix integer overflow

OvmfPkg/VirtioNetDxe/ComponentName.c
Per the UEFI specification, a device driver implementation should return EFI_UNSUPPORTED if the ChildHandle argument in
EFI_COMPONENT_NAME2_PROTOCOL.GetControllerName() is not NULL.
Signed-off-by: Dimitrije Pavlov <Dimitrije.Pavlov@arm.com>
Reviewed-By: Samer El-Haj-Mahmoud <Samer.El-Haj-Mahmoud@arm.com>
Reviewed-by: Sunny Wang <sunny.wang@arm.com>
=> OvmfPkg/VirtioNetDxe: Check ChildHandle argument in GetControllerName

UefiPayloadPkg/UefiPayloadPkg.dsc
REF : https://bugzilla.tianocore.org/show_bug.cgi?id=4096
TDES and ARC4 services are deprecated so set it as disable.
Signed-off-by: Gua Guo <gua.guo@intel.com>
=> UefiPayloadPkg: Remove deprecate Crypto Service

MdeModulePkg/Bus/Pci/XhciDxe/UsbHcMem.c, MdeModulePkg/Bus/Pci/XhciDxe/UsbHcMem.h, MdeModulePkg/Bus/Pci/XhciDxe/XhciSched.c
Patch sent at: https://edk2.groups.io/g/devel/message/95305
According the Xhci Spec, TRB Rings may be larger than a Page, however they shall not cross a 64K byte boundary, so add a parameter to indicate whether the memory allocation is for TRB Rings or not. It will ensure the allocation not crossing 64K boundary in UsbHcAllocMemFromBlock if the memory is allocated for TRB Rings.
Signed-off-by: jdzhang <jdzhang@kunluntech.com.cn>
=> MdeModulePkg/XhciDxe: Add boundary check for TRB ring allocation

BaseTools/Scripts/PatchCheck.py
The syntax for Makefiles requires that indented lines s tart with a tab, but not a space.
This change of PatchCheck.py make the patch for Makefile/GNUmakefile pass the PatchCheck.py.
=> BaseTools/Scripts/PatchCheck.py: Allow tab in Makefile

BaseTools/Tests/GNUmakefile
When checking if $PYTHON_COMMAND exists, curly braces should be used instead of parentheses.
Also, "1" causes an error on FreeBSD: it's likely supposed to be 2>&1 like other scripts.
=> BaseTools: Fix check for ${PYTHON_COMMAND} in Tests/GNUmakefile

BaseTools/Source/C/GenFv/GenFvInternalLib.c
If operation Werro is turned on when compiling BaseTools, the multi-brackets warning will be reported. This issue is comes from on of the LoongArch enabled patche. Removed extra pairs brackets to fix it.
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4111
Signed-off-by: Chao Li <lichao@loongson.cn>
=> BaseTools: Fixed the multiple pairs brackets issue in GenFv

BaseTools/Conf/build_rule.template
Fix gcc: warning:
-x c after last input file has no effect
These kind of flag can only affect the source code after them. For the build command in build_rule.template, we have no other source code or object after these two flag. It seems we don't need them here.
Signed-off-by: JessyX Wu <jessyx.wu@intel.com>
=> remove GCC build warning

ArmPlatformPkg/PrePeiCore/PrePeiCore.c, ArmPlatformPkg/PrePeiCore/PrePeiCoreMPCore.inf, ArmPlatformPkg/PrePeiCore/PrePeiCoreUniCore.inf
Copy code from PrePi to PrePeiCore that prints the firmware version and build date early in the boot process.
Signed-off-by: Rebecca Cran <rebecca@quicinc.com>
Tested-by: Oliver Steffen <osteffen@redhat.com>
=> ArmPlatformPkg/PrePeiCore: Print the firmware version early in boot

MdeModulePkg/Bus/Pci/PciSioSerialDxe/Serial.c
gSerialDevTempate should be gSerialDevTemplate
Signed-off-by: Nate DeSimone <nathaniel.l.desimone@intel.com>
=> MdeModulePkg: Fix spelling error in PciSioSerialDxe

ArmVirtPkg/ArmVirtQemu.dsc
Clang does not support undoing the effects of -mstrict-align by passing the -mno-strict-align counterpart, so appending the latter to the compiler's XIPFLAGS does not work. Instead, clear the flags entirely.
This also removes -mgeneral-regs-only, but this is fine - we can tolerate SIMD codegen in PEIMs or BASE libraries as they run with the MMU and caches enabled.
Signed-off-by: Ard Biesheuvel <ardb@kernel.org>
=> ArmVirtPkg/ArmVirtQemu: Clear XIP flags instead of overriding them

MdeModulePkg/Bus/Scsi/ScsiDiskDxe/ScsiDisk.c, MdeModulePkg/Bus/Scsi/ScsiDiskDxe/ScsiDisk.h, MdeModulePkg/Bus/Scsi/ScsiDiskDxe/ScsiDiskDxe.inf
Patch sent at: https://edk2.groups.io/g/devel/message/95636
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=4100
ScsiDiskDxe driver updates ControllerNameTable with common string "SCSI Disk Device" for all SCSI disks. Due to this, when multiple SCSI disk devices connected, facing difficulty in identifying correct SCSI disk device. As per SCSI spec, standard Inquiry Data is having the fields to know Vendor and Product information. Updated "ControllerNameTable" with Vendor and Product information. So that, device specific name can be retrieved using ComponentName protocol.
Cc: Vasudevan Sambandan <vasudevans@ami.com>
Cc: Sundaresan Selvaraj <sundaresans@ami.com>
Signed-off-by: Cheripally Gopi <gopic@ami.com>
=> MdeModulePkg/ScsiDiskDxe: Update proper device name for ScsiDisk drive

RedfishPkg/RedfishDiscoverDxe/RedfishDiscoverDxe.c
Check the memory block pointer before freeing it.
Signed-off-by: Abner Chang <abner.chang@amd.com>
Reviewed-by: Nickle Wang <nicklew@nvidia.com>
=> RedfishPkg/RedfishDiscoverDxe: Fix memory free issue

UnitTestFrameworkPkg/UnitTestFrameworkPkgHost.dsc.inc
Always use the module name with FILE_GUID to generate the host-based unit test executable image and symbol files.  This allows the same host-based unit test INF file to be used more than once in a single DSC file with FILE_GUID override.  This is valuable when there is a requirement to run the same host-based unit test with different PCD settings, library mappings, or build options.
=> UnitTestFrameworkPkg: Support FILE_GUID override in host based unit tests

pip-requirements.txt
Fixes edk2 CI failure due to VM images being updated to Python 3.11 and the old pip modules not being compatible with Python 3.11.
Updates the following pip modules:
- edk2-pytool-library from 0.11.2 to 0.11.6
- edk2-pytool-extensions from 0.16 to 0.19.1
Needed to fix an issue with Python 3.11 compatibility.
=> pip-requirements.txt: Bump pytool extensions and library

IntelFsp2Pkg/FspSecCore/SecFsp.h, IntelFsp2Pkg/Include/Library/FspSecPlatformLib.h
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4126
Common functions will have either 32bit or 64bit instances which having different return code size. Function header should support both scenarios.
=> IntelFsp2Pkg: Update Function header to support IA32/X64.

MdeModulePkg/Core/PiSmmCore/PiSmmCore.c, MdeModulePkg/Core/PiSmmCore/PiSmmCore.h, MdeModulePkg/Core/PiSmmCore/PiSmmCore.inf, MdeModulePkg/Core/PiSmmCore/PiSmmIpl.c, MdeModulePkg/Core/PiSmmCore/PiSmmIpl.inf
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=3387
Added use of SafeIntLib to validate values are not causing overflows or underflows in user controlled values when calculating buffer sizes.
Signed-off-by: Miki Demeter <miki.demeter@intel.com>
=> MdeModulePkg/PiSmmCore: SmmEntryPoint underflow (CVE-2021-38578)

IntelFsp2Pkg/FspSecCore/Ia32/FspApiEntryT.nasm, IntelFsp2Pkg/FspSecCore/SecFspApiChk.c, IntelFsp2Pkg/FspSecCore/X64/FspApiEntryT.nasm
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4114
FSP specification supports input UPD as NULL cases which FSP will use built-in UPD region instead.
FSP should not return INVALID_PARAMETER in such cases.
In FSP-T entry point case, the valid FSP-T UPD region pointer will be passed to platform FSP code to consume.
In FSP-M and FSP-S cases, valid UPD pointer will be decided when updating corresponding pointer field in FspGlobalData.
Reviewed-by: Ted Kuo <ted.kuo@intel.com>
=> IntelFsp2Pkg: FSP should support input UPD as NULL.

UefiPayloadPkg/UefiPayloadEntry/UniversalPayloadEntry.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4136
System will depend on Boot Mode value to do different behavior Update during Capsule Update process. So UPL need to support update boot mode.
Signed-off-by: VictorX Hsu <victorx.hsu@intel.com>
=> UefiPayloadPkg: Boot mode in PHIT HOB will not be updated

MdePkg/Library/BaseLib/SafeString.c
There was a OOB access in *StrHexTo* functions, when passed strings like "XDEADBEEF".
OpenCore folks established an ASAN-equipped project to fuzz Ext4Dxe, which was able to catch these (mostly harmless) issues.
Cc: Vitaly Cheptsov <vit9696@protonmail.com>
Cc: Marvin H?user <mhaeuser@posteo.de>
Signed-off-by: Pedro Falcato <pedro.falcato@gmail.com>
Reviewed-by: Jiewen Yao <Jiewen.yao@Intel.com>
=> MdePkg/BaseLib: Fix out-of-bounds reads in SafeString

CryptoPkg/Readme.md
Commit 244ce33bdd2f ("CryptoPkg: Add Readme.md", 2022-10-24) had added the long-awaited documentation on the dynamic crypto services. Fix some of the typos and arguable grammar errors in "Readme.md". A few light clarifications are also snuck in.
Cc: Christopher Zurcher <christopher.zurcher@microsoft.com>
Reviewed-by: Christopher Zurcher <christopher.zurcher@microsoft.com>
=> CryptoPkg/Readme.md: typo and grammar fixes

CryptoPkg/Library/BaseHashApiLib/BaseHashApiLib.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3991
Fix build issue when DiSABLE_SHA1_DEPRECATED_INTERFACES is defined. Percolate the #ifndef DiSABLE_SHA1_DEPRECATED_INTERFACES to all the Sha1 functions.
Cc: Nishant C Mistry <nishant.c.mistry@intel.com>
Signed-off-by: Jian J Wang <jian.j.wang@intel.com>
Signed-off-by: Nishant C Mistry <nishant.c.mistry@intel.com>
Signed-off-by: Judah Vang <judah.vang@intel.com>
=> CryptoPkg: Sha1 functions causing build errors

pip-requirements.txt
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4146
Update edk2-pytool-library to version 0.12.0 that adds support for the environment variable PYTOOL_TEMPORARILY_IGNORE_NESTED_EDK_PACKAGES that can be set to true to ignore nested packages instead of breaking the build with an exception. Nested packages are not allowed by the edk2 specifications.  This environment variable allows pytools to run with reduced functionality if nested packages are present giving downstream consumers of edk2 that use pytools time to resolve the use of nested packages and restore all features of pytools.
Cc: Leif Lindholm …
=> pip-requirements.txt: Update edk2-pytool-library to 0.12.0

ShellPkg/Library/UefiShellDebug1CommandsLib/SmbiosView/PrintInfo.c, ShellPkg/Library/UefiShellDebug1CommandsLib/SmbiosView/SmbiosViewStrings.uni
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4135
Added spec version check while publishing new Type9 fields, added Slot Pitch field which was missing and
corrected the publishing order as per Smbios spec.
Cc: Vasudevan S <vasudevans@ami.com>
Cc: Sundaresan S <sundaresans@ami.com>
Signed-off-by: Sainadh Nagolu <sainadhn@ami.com>
=> ShellPkg:Improved Smbios Type9 data under smbiosview

ArmPkg/Library/ArmTrngLib/ArmTrngLib.c
ArmTrngLib crashes when run in DEBUG mode due to the fact that it passed the [truncated] GUID value to a DEBUG() print statement instead of a pointer to the GUID which is what the %g conversion expects.
Signed-off-by: Ard Biesheuvel <ardb@kernel.org>
=> ArmPkg/ArmTrngLib: Fix incorrect GUID reference in DEBUG() output

IntelFsp2Pkg/FspSecCore/Ia32/FspApiEntryT.nasm, IntelFsp2Pkg/FspSecCore/Ia32/FspHelper.nasm, IntelFsp2Pkg/FspSecCore/Ia32/SaveRestoreSseNasm.inc, IntelFsp2Pkg/FspSecCore/SecFsp.h, IntelFsp2Pkg/FspSecCore/X64/FspHelper.nasm
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=4114
1.Use xmm5 slot 1 and xmm6 slot 3 to save ucode status and UPD pointer
respectively in TempRamInitApi in IA32 FspSecCoreT.
2.Correct inappropriate description in the return value of
AsmGetFspInfoHeader.
3.Replace hardcoded offset value 0x1C with FSP_HEADER_IMGBASE_OFFSET in
FspHeler.nasm.
Cc: Chinni B Duggapu <chinni.b.duggapu@intel.com>
=> IntelFsp2Pkg: Improvement of supporting null UPD pointer in FSP-T

.gitmodules, .pytool/CISettings.py, BaseTools/Plugin/HostBasedUnitTestRunner/HostBasedUnitTestRunner.py, MdePkg/Include/Base.h, MdePkg/Include/Library/DebugLib.h, MdePkg/Test/GoogleTest/Library/BaseSafeIntLib/GoogleTestBaseSafeIntLib.inf, MdePkg/Test/GoogleTest/Library/BaseSafeIntLib/GoogleTestBaseSafeIntLib.uni, MdePkg/Test/GoogleTest/Library/BaseSafeIntLib/SafeIntLibUintnIntnUnitTests32.cpp, MdePkg/Test/GoogleTest/Library/BaseSafeIntLib/SafeIntLibUintnIntnUnitTests64.cpp, MdePkg/Test/GoogleTest/Library/BaseSafeIntLib/TestBaseSafeIntLib.cpp, MdePkg/Test/MdePkgHostTest.dsc, ReadMe.rst, UnitTestFrameworkPkg/Include/Library/GoogleTestLib.h, UnitTestFrameworkPkg/Library/CmockaLib/CmockaLib.inf, UnitTestFrameworkPkg/Library/GoogleTestLib/GoogleTestLib.inf, UnitTestFrameworkPkg/Library/GoogleTestLib/GoogleTestLib.uni, UnitTestFrameworkPkg/ReadMe.md, UnitTestFrameworkPkg/Test/GoogleTest/Sample/SampleGoogleTest/SampleGoogleTest.cpp, UnitTestFrameworkPkg/Test/GoogleTest/Sample/SampleGoogleTest/SampleGoogleTestHost.inf, UnitTestFrameworkPkg/Test/UnitTestFrameworkPkgHostTest.dsc, UnitTestFrameworkPkg/UnitTestFrameworkPkg.ci.yaml, UnitTestFrameworkPkg/UnitTestFrameworkPkg.dec, UnitTestFrameworkPkg/UnitTestFrameworkPkgHost.dsc.inc
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4134
Add GoogleTest support to UnitTestFrameworkPkg to provide an
additional host-based unit test framework to developers.
Code: https://github.com/google/googletest
Docs: https://google.github.io/googletest
GoogleTest is implemented in C++, but does support implementing
unit tests for C code.  This patch series makes a few updates for C++
compatibility and build issues related to multiple definitions of _ASSERT().
The GoogleTest git submodule is added to the UnitTestFrameworkPkg
and .pytools/CISettings.py file along with an update to the host-based
test runner plugin to set the GTEST_OUTPUT environment variable to 
specify the XML output file format and location.
A port of the unit tests for the the MdePkg BaseSafeIntLib are included
to …
=> Bug 4134 add google test v3

pip-requirements.txt
**Patch 1:**
pip-requirements.txt: Update to edk2-pytool-library 0.12.1
Updates edk2-pytool-library to pick up a minor bug fix release:
0.12.0 to 0.12.1 changes:
- path_utilities.py: Prevent path case modification in
GetContainingModules()
That change prevents the case of paths from being set to lower case
when returned from the function to avoid impacting case-sensitive
callers.
Release notes:
https://github.com/tianocore/edk2-pytool-library/releases/tag/v0.12.1
**Patch 2:**
pip-requirements.txt: Update to edk2-pytool-extensions 0.20.0
Updates edk2-pytool-extensions to pick up a major version release:
0.19.1 to 0.20.0 changes:
- .vscode/settings.json: Enable flake8 linting
- Add Pydocstyle
- Move dependabot.yml location
- Fix typos in robot files
- Pydocstyle Updates
- Plugin Loader …
=> Update pytool pip versions

ArmPkg/Library/ArmTrngLib/ArmTrngLib.c
Remove ASSERTs in ArmTrngLibConstructor() that prevent from booting on DEBUG builds.
=> ArmPkg/ArmTrngLib: Remove ASSERTs in ArmTrngLibConstructor()

ShellPkg/Library/UefiShellDebug1CommandsLib/SmbiosView/QueryTable.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4156
Refer to the latest SMBIOS v3.6, SMBIOS Socket not completely defined.
SMBIOS v3.6:
https://www.dmtf.org/sites/default/files/standards/documents/ DSP0134_3.6.0.pdf
Signed-off-by: JuX Zhang <jux.zhang@intel.com>
=> ShellPkg/SmbiosView: Update ProcessorUpgradeTable

.github/dependabot.yml
Enables dependabot in this repo so we can better alerted when
dependency updates are available.
This GitHub action will automatically create pull requests and
summarize the dependency details. Because it is a pull request,
the CI system will validate the dependency update in the pull
request.
Configures dependabot for:
1. PIP module updates
2. Submodule updates
3. GitHub action updates
The maintainers/reviewers of the .github directory were added as
pull request reviewers so they can be notified the pull request
is available.
Note to Maintainers:
After this change is committed, PRs from dependabot will be
automatically created in the edk2 repo.  Never set the 'push' label
directly on these PRs. If a dependency identified by dependedabot
looks like one that should be updated in the edk2 …
=> .github/dependabot.yml: Enable dependabot

ShellPkg/DynamicCommand/DpDynamicCommand/Dp.c, ShellPkg/DynamicCommand/DpDynamicCommand/Dp.uni, ShellPkg/DynamicCommand/DpDynamicCommand/DpInternal.h, ShellPkg/DynamicCommand/DpDynamicCommand/DpTrace.c
DP command should be able to parse the FPDT ACPI table and dump the ResetEnd which was logged at the beginning of the firmware image execution. So that DP can calculate SEC phase time duration start from the beginning of firmware image execution.
Signed-off-by: zhenhuay <zhenhua.yang@intel.com>
=> ShellPkg/DpDynamicCommand: Add ResetEnd support in DP command

MdePkg/Library/BaseSynchronizationLib/BaseSynchronizationLib.inf, MdePkg/Library/BaseSynchronizationLib/RiscV64/Synchronization.S
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4143
Fix the name of InternalSyncCompareExchange64() function.
Signed-off-by: Sunil V L <sunilvl@ventanamicro.com>
Reported-by: Zhihao Li <zhihao.li@intel.com>
Tested-by: Zhihao Li <zhihao.li@intel.com>
Cc: Daniel Schaefer <git@danielschaefer.me>
=> BaseSynchronizationLib: Fix RISC-V helper name

.github/ISSUE_TEMPLATE/config.yml
Adds a GitHub issue template to direct contributors familiar with GitHub's issue tracker
to the external resources used by TianoCore.
=> .github/ISSUE_TEMPLATE/config.yml: Add initial issue template

OvmfPkg/Library/PlatformInitLib/Platform.c
There should be a check that the FV HeaderLength cannot be an odd number. Otherwise in the following CalculateSum16 there would be an ASSERT.
In ValidateFvHeader@QemuFlashFvbServicesRuntimeDxe/FwBlockServices.c there a is similar check to the FwVolHeader->HeaderLength.
=> OvmfPkg/PlatformInitLib: Add check to NvVarStoreFV HeaderLength

CryptoPkg/Library/BaseCryptLib/BaseCryptLib.inf, CryptoPkg/Library/BaseCryptLib/Hash/CryptDispatchApDxe.c, CryptoPkg/Library/BaseCryptLib/Hash/CryptDispatchApMm.c, CryptoPkg/Library/BaseCryptLib/Hash/CryptDispatchApPei.c, CryptoPkg/Library/BaseCryptLib/Hash/CryptParallelHash.c, CryptoPkg/Library/BaseCryptLib/Hash/CryptParallelHash.h, CryptoPkg/Library/BaseCryptLib/PeiCryptLib.inf, CryptoPkg/Library/BaseCryptLib/SmmCryptLib.inf
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4097
The BaseCryptLib in the CryptoPkg currently supports ParallelHash algorithm for SMM. The MP Services PPI and MP Services Protocol could be used to enable ParallelHash in PEI and DXE versions of the BaseCryptLib.
=> CryptPkg: Enable CryptoPkg BaseCryptLib ParallelHash for PEI and DXE

CryptoPkg/Library/BaseCryptLib/SysCall/TimerWrapper.c, CryptoPkg/Library/Include/CrtLibSupport.h
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4167
In CrtLibSupport.h, time_t is defined as INT32, and its maximum value is 2147483647. That is, the corresponding maximum timestamp is 2038-01-19 11:14:07. Therefore, overflow occurs when the test time exceeds 2038-01-19 11:14:07. So change the type of time_t to INT64 and also change the type of variables in function gmtime which calculated with time_t.
Signed-off-by: Zihong Yi <yizihong@huawei.com>
=> CryptoPkg/BaseCryptLib:time overflow

RedfishPkg/RedfishPkg.dec
Update ReadfishPkg.dec to remove PrivateInclude from the [Includes.Common.Private] section.  The PrivateInclude directory does not contain any include files, and the PrivateInclude/Crt include path remaining in the [Includes.Common.Private] section providing the include path required to access the CRT related include files by components within the RedfishPkg.
Without this update, there are two forms of #include statements that can be used to include the CRT related include files. Include files should only be available using one form of #include statements.
=> RedfishPkg: Remove overlapping private include path in DEC file

MdeModulePkg/Core/Dxe/Mem/Page.c
The page allocator code in CoreFindFreePagesI() uses a mask derived from its UINTN Alignment argument to align the descriptor end address of a MEMORY_MAP entry to the requested alignment, in order to check whether the descriptor covers enough sufficiently aligned area to satisfy the request.
However, on 32-bit architectures, 'Alignment' is a 32-bit type, whereas DescEnd is a 64-bit type, and so the resulting operation performed on the end address comes down to masking with 0xfffff000 instead of the intended 0xffffffff_fffff000. Given the -1 at the end of the expression, the resulting address is 0xffffffff_fffffffff for any descriptor that ends on a 4G aligned boundary, and this is certainly not what was intended.
So cast Alignment to UINT64 to ensure that the mask has the right size. …
=> MdeModulePkg/DxeCore: Use correct type for alignment mask

OvmfPkg/Library/CcExitLib/CcExitVeHandler.c
According to the Intel GHCI specification document section 2.4.1, the goal for instructions that do not have a corresponding TDCALL is for the handler to treat the instruction as a NOP.
INVD does not have a corresponding TDCALL. This patch makes the #VE handler treat INVD as a NOP.
Signed-off-by: Ryan Afranji <afranji@google.com>
=> OvmfPkg: Add INVD case in #VE handler

OvmfPkg/SmbiosPlatformDxe/SmbiosPlatformDxe.c, OvmfPkg/SmbiosPlatformDxe/SmbiosPlatformDxe.inf, OvmfPkg/SmbiosPlatformDxe/XenSmbiosPlatformDxe.inf
Instead of using hard-coded strings ("0.0.0" for BiosVersion etc) which is mostly useless read the PCDs (PcdFirmwareVendor, PcdFirmwareVersionString and PcdFirmwareReleaseDateString) and build the string table dynamuically at runtime.
=> OvmfPkg/SmbiosPlatformDxe: use PcdFirmware*

MdeModulePkg/Bus/Pci/SdMmcPciHcDxe/SdDevice.c
Patch sent at: https://edk2.groups.io/g/devel/message/97100
SD1.0 cards don't support CMD8 and CMD6
CMD8 result can be used to distinguish the card is SD1.0 or not. CMD8 result can be used to decide following CMD6 is sent or skip.
Signed-off-by: Chevron Li <chevron.li@bayhubtech.com>
=> MdeModulePkg: SdMmcPciHcDxe: Fix issue that SD1.0 cards can't be recognized

ShellPkg/Application/Shell/ShellProtocol.c
Update Shell Protocol EfiShellGetMapFromDevicePath() to not set the end if the device path if it is already an end of entire device path.  This removes a write oprtation that can cause failures if the Device Path Protocol is mapped to read-only memory.  In general Device Path Protocols should not be modified unless the API explicitly states that the device path is modified.
Cc: Ard Biesheuvel <ardb@kernel.org>
=> ShellPkg/Shell: Do not set end device path if already end

DynamicTablesPkg/Library/Acpi/Arm/AcpiSsdtCpuTopologyLibArm/SsdtCpuTopologyGenerator.c
_LPI Revision should be 0 per the ACPI 6.5 specification. "The revision number of the _LPI object. Current revision is 0."
=> DynamicTablesPkg: SSDT _LPI revision is incorrect

UnitTestFrameworkPkg/Library/UnitTestLib/AssertCmocka.c
Update the UnitTestAssertStatusEqual error message to print out the expected value in addition to the seen value.
Signed-off-by: Jeshua Smith <jeshuas@nvidia.com>
=> UnitTestFrameworkPkg/UnitTestLib: Print expected Status on ASSERT fail

OvmfPkg/IntelTdx/TdTcg2Dxe/TdTcg2Dxe.c, SecurityPkg/Library/SecTpmMeasurementLib/SecTpmMeasurementLibTdx.c
BZ: https://bugzilla.tianocore.org/show_bug.cgi?id=4179
BZ: https://bugzilla.tianocore.org/show_bug.cgi?id=4184
This patch-set fix the incorrect implementation in CcMeasurement.
Patch#1:
Incorrect protocol and structure version
Patch#2/3:
Incorrect mapping between TPM PCR index and TDX Measurement Register
index.
Code: https://github.com/mxu9/edk2/tree/CcMapping.v1
Cc: Erdem Aktas <erdemaktas@google.com> [ruleof2]
Cc: James Bottomley <jejb@linux.ibm.com> [jejb]
Cc: Jiewen Yao <jiewen.yao@intel.com> [jyao1]
Cc: Tom Lendacky <thomas.lendacky@amd.com> [tlendacky]
Cc: Arti Gupta <ARGU@microsoft.com>
Reported-by: Arti Gupta <ARGU@microsoft.com>
Min M Xu (3):
OvmfPkg/TdTcg2Dxe: Fix incorrect protocol and structure version
OvmfPkg/TdTcg2Dxe: Fix the …
=> Fix incorrect implementation in CcMeasurement

UefiPayloadPkg/UefiPayloadPkg.fdf, UefiPayloadPkg/UniversalPayloadBuild.py
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4196
Since UefiPayload had supported multiple fv,
move bdsdxe.inf to new firmware volume and
modify the script of UniversalPayloadPkgBuild.py to support bdsdxe fv in elf file
Signed-off-by: MarsX Lin <marsx.lin@intel.com>
=> UefiPayloadPkg: Move bdsdxe.inf from DXEFV to BDSFV

DynamicTablesPkg/Include/ArmNameSpaceObjects.h, DynamicTablesPkg/Library/Acpi/Arm/AcpiSsdtCpuTopologyLibArm/SsdtCpuTopologyGenerator.c, DynamicTablesPkg/Library/Common/TableHelperLib/ConfigurationManagerObjectParser.c
Allow object to specify the name of processor and processor container nodes and the UID of processor containers.
This allows these to be more accurately referenced from other tables. For example for the _PSL method or the UID in the APMT table.
The UID and Name for processor container may be different as if the intention is to set names as the corresponding affinity level the UID may need to be different if there are multiple levels of containers.
=> DynamicTablesPkg: Allow for specified CPU names

UefiPayloadPkg/UefiPayloadPkg.dsc
The following PCDs have no value in UefiPayloadPkg.dsc and they can not pass the Ecc tool check, so assign the default values the same as they are in *.dec file.
1. gEfiMdeModulePkgTokenSpaceGuid.PcdAriSupport
2. gEfiMdeModulePkgTokenSpaceGuid.PcdMrIovSupport
3. gEfiMdeModulePkgTokenSpaceGuid.PcdSrIovSuppor
4. gEfiMdeModulePkgTokenSpaceGuid.PcdSrIovSystemPageSize
5. gUefiCpuPkgTokenSpaceGuid.PcdCpuApInitTimeOutInMicroSeconds
6. gUefiCpuPkgTokenSpaceGuid.PcdCpuApLoopMode
7. gUefiCpuPkgTokenSpaceGuid.PcdCpuMicrocodePatchAddress
8. gUefiCpuPkgTokenSpaceGuid.PcdCpuMicrocodePatchRegionSize
Signed-off-by: jdzhang <jdzhang@kunluntech.com.cn>
=> UefiPayloadPkg: Define default values for the DynamicEX PCDs

MdeModulePkg/Bus/Pci/XhciDxe/Xhci.c, MdeModulePkg/Bus/Pci/XhciDxe/XhciReg.c, MdeModulePkg/Bus/Pci/XhciDxe/XhciReg.h
Patch 1 - MdeModulePkg/XhciDxe/Xhci: Don't check for invalid PSIV
Sent at: https://edk2.groups.io/g/devel/message/97496
Patch 2 - MdeModulePkg/Bus/Pci/XhciDxe: Check port is compatible before getting PSIV
Sent at: https://edk2.groups.io/g/devel/message/97497
=> MdeModulePkg/XhciDxe: Add checks for PSIV (Protocol Speed ID Value)

OvmfPkg/AmdSev/AmdSevX64.dsc, OvmfPkg/CloudHv/CloudHvX64.dsc, OvmfPkg/Include/TdxCommondefs.inc, OvmfPkg/IntelTdx/Sec/X64/IntelTdxAPs.nasm, OvmfPkg/IntelTdx/Sec/X64/SecEntry.nasm, OvmfPkg/Library/PlatformInitLib/IntelTdx.c, OvmfPkg/Library/PlatformInitLib/PlatformInitLib.inf, OvmfPkg/Library/TdxMailboxLib/TdxMailbox.c, OvmfPkg/Library/TdxMailboxLib/TdxMailboxLib.inf, OvmfPkg/Library/TdxMailboxLib/TdxMailboxLibNull.inf, OvmfPkg/Microvm/MicrovmX64.dsc, OvmfPkg/OvmfPkgIa32.dsc, OvmfPkg/OvmfPkgIa32X64.dsc, OvmfPkg/Sec/X64/SecEntry.nasm
BZ: https://bugzilla.tianocore.org/show_bug.cgi?id=4172
TDVF once accepts memory only by BSP. To improve the boot performance
this patch-set introduce the multi-core accpet memory. Multi-core means
BSP and APs work together to accept memory.
TDVF leverages mailbox to wake up APs. It is not enabled in MpInitLib
(Which requires SIPI). So multi-core accept memory cannot leverages
MpInitLib to coordinate BSP and APs to work together.
So TDVF split the accept memory into 2 phases.
- AcceptMemoryForAPsStack:
BSP accepts a small piece of memory which is then used by APs to setup
stack. We assign a 16KB stack for each AP. So a td-guest with 256 vCPU
requires 255*16KB = 4080KB.
- AcceptMemory:
After above small piece of memory is accepted, BSP commands APs to
accept memory by sending AcceptPages …
=> Enable Multi-core based lazy-accept for TDVF

OvmfPkg/XenPlatformPei/Platform.c, OvmfPkg/XenPlatformPei/Platform.h
Copy the function BuildPlatformInfoHob() from OvmfPkg/PlatformPei.
QemuFwCfgLib expect this HOB to be present, or fails to do anything. InternalQemuFwCfgIsAvailable() from QemuFwCfgPeiLib module will not check if the HOB is actually present for example and try to use a NULL pointer.
Fixes: cda98df16228 ("OvmfPkg/QemuFwCfgLib: remove mQemuFwCfgSupported + mQemuFwCfgDmaSupported")
Signed-off-by: Anthony PERARD <anthony.perard@citrix.com>
=> OvmfPkg/OvmfXen: Build platform info HOB in XenPlatformPei

CryptoPkg/CryptoPkg.dsc, CryptoPkg/Readme.md
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=3992
V2: Update Readme and CryptoPkg.dsc to reflect changes and be in sync.
V1: Enable CryptAes for PEI phase. Enable CryptHkdf for SMM phase.
Update Readme.md
Cc: Nishant C Mistry <nishant.c.mistry@intel.com>
Signed-off-by: Jian J Wang <jian.j.wang@intel.com>
Signed-off-by: Nishant C Mistry <nishant.c.mistry@intel.com>
Signed-off-by: Judah Vang <judah.vang@intel.com>
=> CryptoPkg: Need to enable crypto functions

PcAtChipsetPkg/PcAtChipsetPkg.dec
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4193
In order to remove RTC_INDEX/RTC_TARGET from
the UplBuild macro list,change the RTC_INDEX
/RTC_TARGET type from PcdsFixedAtBuild to PcdsDynamicEx
Signed-off-by: KasimX Liu <kasimx.liu@intel.com>
=> PcAtChipsetPkg: Move RTC PCD to dynamic PCD

UefiPayloadPkg/UefiPayloadPkg.fdf
BDS module was moved from DXEFV to newly created BDSFV recently. Non-universal UEFI payload doesn't support multiple FV, so it failed to boot since BDS module could not be found.
This patch add BDS back to DXEFV when UNIVERSAL_PAYLOAD is not set.
=> UefiPayloadPkg: Fix boot issue for non-universal payload

BaseTools/Source/C/DevicePath/GNUmakefile
When checking the version in DevicePath's Makefile, use BUILD_CC instead of assuming "gcc".  BUILD_CC is set in header.makefile and is the compiler that will actually be used to build DevicePath.  It defaults to "gcc", but may be overridden.
Signed-off-by: Jake Garver <jake@nvidia.com>
=> BaseTools: Use BUILD_CC when checking gcc version in DevicePath

BaseTools/Conf/build_rule.template
Prior to this change, deps were not generated for Arm and AARCH64 libraries when MODULE_TYPE was BASE, SEC, PEI_CORE, or PIEM. That resulted in bad incremental builds.
Signed-off-by: Jake Garver <jake@nvidia.com>
Reviewed-by: Jeff Brasen <jbrasen@nvidia.com>
=> BaseTools: Generate deps for Arm targets

MdeModulePkg/Bus/Pci/XhciDxe/Xhci.c
Patch sent at: https://edk2.groups.io/g/devel/message/97683
Force resetting the port by clearing the USB_PORT_STAT_C_RESET bit in PortChangeStatus when XhcPollPortStatusChange fails
=> MdeModulePkg/Bus/Pci/XhciDxe: Reset port if status change returns an error

Maintainers.txt
https://listman.redhat.com/archives/edk2-devel-archive/2023-January/057182.html
https://edk2.groups.io/g/devel/message/97884
http://mid.mail-archive.com/20230103160539.87830-1-lersek@redhat.com
~~~
Maintainers.txt: designate Gerd Hoffmann as UefiCpuPkg reviewer
I suggest that Gerd be notified about all UefiCpuPkg patches, so he may
take a quick look at, or (by his preference) even test, the proposed
change, in a genuine QEMU/KVM environment.
Assuming this patch is accepted -- subsequently, please *wait* for Gerd's
approval on UefiCpuPkg patches, before merging them.
Notes:
- It's perfectly fine for a reviewer to give an A-b just so the review
process be unblocked, if they don't have anything to add, or don't have
time to review or test in detail. The point is that someone outside of
Intel …
=> Maintainers.txt: designate Gerd Hoffmann as UefiCpuPkg reviewer

Maintainers.txt
Add myself as a reviewer for OVMF/Confidential Computing patches.
Remove Brijesh while at it, since he is no longer at AMD, and the email is no longer valid.
Suggested-by: Tom Lendacky <thomas.lendacky@amd.com>
Signed-off-by: Michael Roth <michael.roth@amd.com>
=> Maintainers.txt: Update reviewers for OVMF/Confidential Computing

UefiPayloadPkg/Library/DebugPrintErrorLevelLibHob/DebugPrintErrorLevelLibHob.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4264 Fix debug print error level hob not save correct DebugPrintErrorlevel Should cover the case:
Header.Length == UNIVERSAL_PAYLOAD_SIZEOF_THROUGH_FIELD ()
Signed-off-by: Ning Feng <ning.feng@intel.com>
=> UefiPayloadPkg: Fix debug print error level hob not save correct

DynamicTablesPkg/Library/FdtHwInfoParserLib/Gic/ArmGicCParser.c
Linux's cpu DT bindings call out arm,armv8 while the code previously used arm,arm-v8, add second entry to support the arm,armv8 case.
Fixes: e366a41ef0 ("DynamicTablesPkg: FdtHwInfoParser: Add GICC parser")
Signed-off-by: Moritz Fischer <moritzf@google.com>
=> DynamicTablesPkg: FdtHwInfoParserLib: Fix compatible string

OvmfPkg/CloudHv/CloudHvX64.dsc, OvmfPkg/Microvm/MicrovmX64.dsc, OvmfPkg/OvmfPkgX64.dsc
TPM support is independent from secure boot support.  Move the TPM include snipped out of the secure boot !if block.
Fixes: b47575801e19 ("OvmfPkg: move tcg configuration to dsc and fdf include files")
Bugzilla: https://bugzilla.tianocore.org//show_bug.cgi?id=4290
=> OvmfPkg: fix OvmfTpmSecurityStub.dsc.inc include

MdeModulePkg/Bus/Pci/XhciDxe/XhciSched.c, MdeModulePkg/Bus/Pci/XhciPei/UsbHcMem.c, MdeModulePkg/Bus/Pci/XhciPei/XhciSched.c, MdeModulePkg/Bus/Usb/UsbBotPei/PeiAtapi.c
Patch 1/3 "MdeModulePkg/Xhci: Initial XHCI DCI slot's Context value" sent at:
https://edk2.groups.io/g/devel/message/98267
Patch 2/3 "MdeModulePkg/Usb: Read a large number of blocks" sent at:
https://edk2.groups.io/g/devel/message/98268
Patch 3/3 "MdeModulePkg/XhciPei: Unlinked XhciPei memory block" sent at:
https://edk2.groups.io/g/devel/message/98269
=> MdeModulePkg: XHC and USB PEI drivers fixes

ArmVirtPkg/ArmVirtKvmTool.dsc, ArmVirtPkg/ArmVirtQemu.dsc, ArmVirtPkg/ArmVirtQemuKernel.dsc
Commit 789a72328553 reclassified the NOR flash region as EFI_MEMORY_WC in the OS visible EFI memory map, and dropped the explicit aligned CopyMem() implementation, in the assumption that EFI_MEMORY_WC will be honored by the OS, and that the region will be mapped in a way that tolerates misaligned accesseses. However, Linux today uses device attributes for all EFI MMIO regions, in spite of the memory type attributes, and so using misaligned accesses is never safe.
So instead, switch to the generic CopyMem() implementation entirely, just like we already did for VariableRuntimeDxe.
Fixes: 789a72328553 ("OvmfPkg/VirtNorFlashDxe: use EFI_MEMORY_WC and drop AlignedCopyMem()")
=> ArmVirt: don't use unaligned CopyMem () on NOR flash

BaseTools/Conf/build_rule.template
EDKII build system supports OptionROM generation if particular PCI_* defines are present in the module INF file:
```
[Defines]
...
PCI_VENDOR_ID                  = <...>
PCI_DEVICE_ID                  = <...>
PCI_CLASS_CODE                 = <...>
PCI_REVISION                   = <...>
```
Although after the commit d372ab585a2cdc5348af5f701c56c631235fe698 ("BaseTools/Conf: Fix Dynamic-Library-File template") it is no longer possible.
The build system fails with the error:
```
Cyclic dependency detected while generating rule for
"<...>/DEBUG/<...>.efi" file
```
Remove "$(DEBUG_DIR)(+)$(MODULE_NAME).efi" from the 'dll' output files to fix the cyclic dependency.
=> Fix cyclic dependency error on OptionROM build

ShellPkg/Library/UefiShellDebug1CommandsLib/SmbiosView/PrintInfo.c, ShellPkg/Library/UefiShellDebug1CommandsLib/SmbiosView/SmbiosViewStrings.uni
In smbiosview command in shell, below are the fields of SMBIOS Type38 table which can be displayed in formatted manner.
1. Base Address
1. IPMI Specification Version.
2. NV Storage Device Address. Base Address:
As per spec, the value in Base Address field of SMBIOS type38 table should be right shifted by 1 if the interface type is SSIF. IPMI Specification Version:
If the value in IPMI Specification Version field is 15H, it should be displayed 1.5.
NV Storage Device Address:
If the value in NV Storage Device Address field is 0xFF, it should be displayed as "No storage device is Present".
Cc: Vasudevan Sambandan <vasudevans@ami.com>
Cc: Sundaresan Selvaraj <sundaresans@ami.com>
Cc: Gayathri Thunuguntla <gayathrit@ami.com>
Signed-off-by: Prakash K <prakashk@ami.com>
Reviewed-by: Liming Gao …
=> ShellPkg: Display SMBIOS Type38 fields in smbiosview in formatted view

OvmfPkg/Library/CcExitLib/CcExitLib.inf, OvmfPkg/Library/CcExitLib/CcExitVcHandler.c, OvmfPkg/Library/CcExitLib/CcExitVeHandler.c, OvmfPkg/Library/CcExitLib/CcInstruction.c, OvmfPkg/Library/CcExitLib/CcInstruction.h, OvmfPkg/Library/CcExitLib/SecCcExitLib.inf
BZ: https://bugzilla.tianocore.org/show_bug.cgi?id=4169
The previous TDX MmioExit doesn't handle the Mmio instructions correctly
in some scenarios. This patch-set refactors the implementation to fix the
issues.
Before the refactoring, common X86 instruction codes in CcExitVcHandler.c
are moved to separate files (CcInstruction.h / CcInstruction.c) so that
these codes can be re-used in TDX.
Code: https://github.com/mxu9/edk2/tree/TdxMmioExit.v3
v3 changes:
- Handle the error if an error is returned from TdxMmioReadWrite.
- Add more check in ParseMmioExitInstructions.
v2 changes:
- Add CpuDeadLoop () after each TDVMCALL(HALT) in VE handler. Because
TDVMCALL(HALT) is not trusted.
- Other minor changes such as deleting ASSERT in VE handler. Because
any error in VE handler will trigger …
=> Refactor TDX MmioExit

SecurityPkg/Tcg/TdTcg2Dxe/TdTcg2Dxe.c
According to TCG PC Client PFP spec 0021 Section 2.4.4.2 EFI boot variable should be measured and extended to PCR[1], not PCR[5]. This patch is proposed to fix this error.
=> SecurityPkg/TdTcg2Dxe: Extend EFI boot variable to PCR[1]

OvmfPkg/Library/CcExitLib/CcExitVeHandler.c
Status should be initialized otherwise it may return unexpected value.
=> OvmfPkg/CcExitLib: Initialize Status in IoExit

OvmfPkg/Library/PlatformInitLib/Platform.c, OvmfPkg/PlatformCI/.azurepipelines/Windows-VS2019.yml, OvmfPkg/PlatformCI/PlatformBuildLib.py
This pull request contains two, logically coherent, patch sets, in the following order:
(**1**) [RFC PATCH] OvmfPkg/PlatformCI VS2019: Enable temporary workaround for cpuhp bugfix
http://mid.mail-archive.com/20230119134302.1524569-1-ardb@kernel.org
https://listman.redhat.com/archives/edk2-devel-archive/2023-January/058197.html
https://edk2.groups.io/g/devel/message/98899
~~~
QEMU for x86 has a nasty CPU hotplug bug of which the ramifications are
difficult to oversee, even though KVM acceleration seems to be
unaffected. This has been addressed in QEMU mainline, and will percolate
through the ecosystem at its usual pace. In the mean time, due to the
potential impact on production workloads, we will be updating OVMF to
abort the boot when it detects a QEMU build that is affected.
Tiancore's …
=> OvmfPkg: catch QEMU's CPU hotplug reg block regression (TianoCore#4250, PlatformInitLib bugcheck + PlatformCI VS2019 exception) -- push

ShellPkg/Application/Shell/Shell.c, ShellPkg/Application/Shell/Shell.inf, ShellPkg/ShellPkg.dec
Create PcdShellDefaultDelay to configure the default delay the shell provides for the user at the start time if the user wishes to cancel the execution of a potential startup script.
The shell application already allows the user to override the delay default value by specifying the -delay cmdline argument. This however cannot be used when loading the shell application using direct boot or when integrating the shell into the platform firmware build.
Thus, a PCD can be easily configured by the developer either at build time, or even at runtime.
Signed-off-by: Tomas Pilar <tomas@quicinc.com>
=> ShellPkg: Export default shell delay as PCD

SecurityPkg/Library/AuthVariableLib/AuthService.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4305
Based on whether the DER-encoded ContentInfo structure is present in authenticated SetVariable payload or not, the SHA-256 OID can be located at different places.
UEFI specification explicitly states the driver shall support both cases, but the old code assumed ContentInfo was not present and incorrectly rejected authenticated variable updates when it were present.
Signed-off-by: Jan Bobek <jbobek@nvidia.com>
=> SecurityPkg/AuthVariableLib: Check SHA-256 OID with ContentInfo present

BaseTools/Conf/tools_def.template
BZ: https://bugzilla.tianocore.org/show_bug.cgi?id=2928
commit 17bd834eb5fd ("BaseTools: Factorize GCC flags") makes GCC48_ALL_CC_FLAGS inherit from GCC_ALL_CC_FLAGS. GCC_ALL_CC_FLAGS contains the '-Os' flag.
The latest flag in a command line overrides the previous optimization option. This allows more specific build configuration to override the inherited '-Os' flag.
If a build configuration includes GCC48_ALL_CC_FLAGS, hard-coded '-Os' options are not necessary anymore. Remove them.
Reported-by: Laszlo Ersek <lersek@redhat.com>
=> tools_def: Remove duplicated -Os

MdeModulePkg/Include/Pi/PrePiDxeCis.h, MdePkg/Include/Pi/PiDxeCis.h
The enumeration in MdePkg/Include/Pi/PiDxeCis.h has a duplicated entry, so the 8th position in the list doesn't count as index 7. The value EfiGcdMemoryTypeUnaccepted will have when added before EfiGcdMemoryTypeMaximum will be 6.
Signed-off-by: Dionna Glaze <dionnaglaze@google.com>
Reviewed-by: Min Xu <min.m.xu@intel.com>
=> MdeModulePkg: Correct memory type in PrePiDxeCis.h

MdePkg/Include/IndustryStandard/Acpi.h, MdePkg/Include/IndustryStandard/Acpi65.h, MdePkg/MdePkg.ci.yaml
ACPI specification 6.5 has been released in August 2022, EDK2 needs to add V6.5 header.
=> Add ACPI 6.5 header

UefiPayloadPkg/PayloadLoaderPeim/PayloadLoaderPeim.inf
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4193
In order to remove RTC_INDEX/RTC_TARGET from
the UplBuild macro list,change the RTC_INDEX
/RTC_TARGET type from PcdsFixedAtBuild to PcdsDynamicEx
Signed-off-by: KasimX Liu <kasimx.liu@intel.com>
=> UefiPayloadPkg: Set RTC dynamic PCD to PeiPCDdatabase

MdePkg/Include/LoongArch64/ProcessorBind.h
The UINT64 and INT64 should be defined as unsigned long long and long long in the linux64 bit environment, but now defined as unsigned long and long, so fix it.
BZ: https://bugzilla.tianocore.org/show_bug.cgi?id=4330
Signed-off-by: Chao Li <lichao@loongson.cn>
=> MdePkg: Fix UINT64 and INT64 word length for LoongArch64

MdeModulePkg/Bus/Scsi/ScsiBusDxe/ScsiBus.c, MdeModulePkg/Bus/Scsi/ScsiBusDxe/ScsiBus.h
Patch sent at: https://edk2.groups.io/g/devel/message/99340
Currently DiscoverScsiDevice() returns a boolean which cannot distinguish a "not found" situation from a real problem like memory allocation failures.
This patch changes the return value to an EFI_STATUS so that when memory allocation fails, it will return EFI_OUT_OF_RESOURCES.
Without this change, any FALSE returned by DiscoverScsiDevice() will result in EFI_OUT_OF_RESOURCES being returned by ScsiScanCreateDevice(), which will cause a while loop in SCSIBusDriverBindingStart() to abort before other possible Puns in the SCSI channel are scanned, which means good devices may not have a chance to be discovered.  If this good device is the boot device, boot will fail.
Cc: Liming Gao …
=> MdeModulePkg: ScsiBusDxe: Refactor DiscoverScsiDevice()

MdeModulePkg/Bus/Ata/AhciPei/AhciPeiS3.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4201
The code can reach line 69 only through the else path above at line 57. The else path already has the same NULL check at line 59 and hence the duplicate code lines are totally redundant which can be deleted.
Signed-off-by: Ranbir Singh <Ranbir.Singh3@Dell.com>
=> MdeModulePkg/Bus/Ata/AhciPei: Fix DEADCODE Coverity issue

MdePkg/Include/Uefi/UefiSpec.h
According to the UEFI 2.10 Specification, the EFI_BOOT_SERVICES_TABLE CreateEvent function has the following signature:
typedef
EFI_STATUS
(EFIAPI *EFI_CREATE_EVENT) (
IN UINT32           Type,
IN EFI_TPL          NotifyTpl,
IN EFI_EVENT_NOTIFY NotifyFunction, OPTIONAL
IN VOID             *NotifyContext, OPTIONAL
OUT EFI_EVENT       *Event
);
Fix the prototype in UefiSpec.h to match, by labeling the NotifyFunction and NotifyContext parameters as OPTIONAL.
=> MdePkg: Label CreateEvent NotifyFunction and NotifyContext optional

UefiCpuPkg/PiSmmCpuDxeSmm/SmmProfile.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4246
In function InitPaging, NumberOfPml5Entries is calculated by below code NumberOfPml5Entries = (UINTN)LShiftU64 (1, SizeOfMemorySpace - 48); If the SizeOfMemorySpace is larger than 48, NumberOfPml5Entries will be larger than 1. However, this doesn't make sense if the hardware doesn't support 5 level page table.
Reviewed-by: Wu, Jiaxin <jiaxin.wu@intel.com>
Signed-off-by: Eric Dong <eric.dong@intel.com>
=> UefiCpuPkg: Fix SMM code hangs when InitPaging

MdeModulePkg/Bus/Scsi/ScsiDiskDxe/ScsiDisk.c
Patch sent at: https://edk2.groups.io/g/devel/message/99387
Comment of MdeModulePkg/Bus/Scsi/ScsiDiskDxe/ScsiDisk.c was polluted by some previous merge. This patch clean it up.
Cc: Sivaparvathi chellaiah <sivaparvathic@ami.com>
Signed-off-by: Yuan Yu <yuanyu@google.com>
=> MdeModulePkg: ScsiDiskDxe: clean up comment in ScsiDisk.c

OvmfPkg/AcpiPlatformDxe/AcpiPlatformDxe.inf, OvmfPkg/AcpiPlatformDxe/QemuFwCfgAcpi.c
https://bugzilla.tianocore.org/show_bug.cgi?id=4245
QEMU provides the following three files for guest to install the ACPI tables:
- etc/acpi/rsdp
- etc/acpi/tables
- etc/table-loader
"etc/acpi/rsdp" and "etc/acpi/tables" are similar, they are only kept separate because they have different allocation requirements in SeaBIOS.
Both of these fw_cfg files contain preformatted ACPI payload. "etc/acpi/rsdp" contains only the RSDP table, while "etc/acpi/tables" contains all other tables, concatenated. To be noted, the tables in these two files have been filled in by qemu, but two kinds of fields are incomplete: pointers to other tables and checksums (which depend on the pointers).
"/etc/table-loader" is a linker/loader which provides the commands to "patch" the tables in "etc/acpi/tables" and …
=> OvmfPkg/AcpiPlatformDxe: Measure ACPI table from QEMU in TDVF

EmbeddedPkg/Library/PrePiLib/PrePiLib.inf
The code never references the PCD so the INF should not reference it either. The last reference was moved to PrePiHobLib in commit 05e48e00834b32e4bd2 (dated 2011!) and dropped from there as well in commit 97106391955337155e7.
Cc: Daniel Schaefer <git@danielschaefer.me>
Reported-by: Sunil V L <sunilvl@ventanamicro.com>
Signed-off-by: Ard Biesheuvel <ardb@kernel.org>
=> EmbeddedPkg/PrePiLib: Drop unused PCD PcdPrePiCpuIoSize

OvmfPkg/Bhyve/BhyveX64.dsc, OvmfPkg/CloudHv/CloudHvX64.dsc, OvmfPkg/IntelTdx/IntelTdxX64.dsc, OvmfPkg/Microvm/MicrovmX64.dsc, OvmfPkg/OvmfPkgIa32.dsc, OvmfPkg/OvmfPkgIa32X64.dsc, OvmfPkg/OvmfPkgX64.dsc, SecurityPkg/Library/AuthVariableLib/AuthService.c, SecurityPkg/Library/AuthVariableLib/AuthVariableLib.inf, SecurityPkg/SecurityPkg.dec
Hi all,
I'm sending out v1 of my patch series that addresses a UEFI spec
non-compliance when enrolling PK in setup mode. Additional info can be
found in bugzilla [1]; the changes are split into 4 patches as
suggested by Laszlo Ersek in comment #4.
I've based my work on the patch by Matthew Carlson; I've credited him
with co-authorship of the first patch even though in the end I decided
to do the implementation a bit differently.
Comments & reviews welcome!
Cheers,
-Jan
References:
1. https://bugzilla.tianocore.org/show_bug.cgi?id=2506
Jan Bobek (4):
SecurityPkg: limit verification of enrolled PK in setup mode
OvmfPkg: require self-signed PK when secure boot is enabled
ArmVirtPkg: require self-signed PK when secure boot is enabled
SecurityPkg: don't require PK to be self-signed by default …
=> Don't require self-signed PK in setup mode

OvmfPkg/IntelTdx/README
TDVF's README is updated based on the latest feature.
- RTMR based measurement is supported in OvmfPkgX64 (Config-A)
- Features of Config-B have all been implemented, such as removing unnecessary attack surfaces.
=> OvmfPkg/IntelTdx: Update README

ArmPkg/Drivers/ArmScmiDxe/ScmiClockProtocol.c
As per the SCMI specification, section CLOCK_DESCRIBE_RATES mentions that the value of num_rates_flags[11:0] in the response must be 3 if the return format is the triplet. Due to the buggy firmware, this was not noticed for long time. The firmware is now fixed resulting in ClockDescribeRates() to fail with "Buffer Too Small" error as the RequiredArraySize gets miscalculated as 72 instead of 24.
Fix the issue by reusing the logic for both the return format which must work if num_rates_flags has correct value as expected from the specification.
Cc: Girish Pathak <girish.pathak@arm.com>
Cc: Jeff Brasen <jbrasen@nvidia.com>
Tested-by: Pierre Gondois <pierre.gondois@arm.com>
Reported-by: Sami Mujawar <sami.mujawar@arm.com>
Signed-off-by: …
=> ArmPkg/ArmScmiDxe: Fix the calculation of RequiredArraySize

BaseTools/Source/C/GenFv/GNUmakefile, BaseTools/Source/C/GenFv/GenFvInternalLib.c
Signed-off-by: Thierry LARONDE <tlaronde@polynum.com>
=> BaseTools: remove useless dependency on libuuid

MdeModulePkg/MdeModulePkg.dec
Literally, the meaning of PcdDxeIplSwitchToLongMode is clear, indicating whether need switch to long mode when loading DxeCore. However, the comments in dec are confusing for the case where PEI core and DXE core are both in 64-bit. This patch makes it clear. PcdDxeIplSwitchToLongMode is true only when PEI core is 32-bit, and switch to long mode to load 64-bit DXE core. In other cases, this PCD is false. This also aligns with current usage in OvmfPkg.
=> MdeModulePkg: Disambiguate the meaning of PcdDxeIplSwitchToLongMode

MdeModulePkg/Core/Dxe/Mem/Pool.c
BZ: https://bugzilla.tianocore.org/show_bug.cgi?id=4315
MemoryType of EfiUnacceptedMemoryType should not be allocated in AllocatePool. Instead it should return EFI_INVALID_PARAMETER.
Reported-by: Liming Gao <gaoliming@byosoft.com.cn>
=> MdeModulePkg: EfiUnacceptedMemoryType is not allowed in AllocatePool

MdePkg/Include/IndustryStandard/IoRemappingTable.h
The IO Remapping Table, Platform Design Document, Revision E.e, Sept 2022 (https://developer.arm.com/documentation/den0049/ee) added flags in SMMUv3 node for validity of ID mappings for MSIs related to control interrupts.
Therefore, update the IORT header file to:
- increment IORT table revision to 6
- add support for DeviceId valid flag
Signed-off-by: Swatisri Kantamsetti <swatisrik@nvidia.com>
=> MdePkg:IORT header update for IORT Rev E.e spec

.pytool/Plugin/EccCheck/EccCheck.py
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4326
EccBuild currently assumes all packages reside in WORKSPACE. However, this is obviously not the case for many setups. Most notably, Ext4Pkg is located in edk2-platforms/Features and thus cannot be in WORKSPACE in any reasonable setup.
Use Edk2Path to locate the package in WORKSPACE and PACKAGES_PATH.
Cc: Pedro Falcato <pedro.falcato@gmail.com>
Signed-off-by: Marvin H?user <mhaeuser@posteo.de>
Acked-by: Pedro Falcato <pedro.falcato@gmail.com>
=> .pytool/Plugin/EccCheck: Add PACKAGES_PATH support

EmulatorPkg/Include/Protocol/EmuThunk.h, EmulatorPkg/Library/PeiTimerLib/PeiTimerLib.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4339
Thunk->Sleep is expecting nanoseconds, no need to multiply by 100.
Signed-off-by: Deric Cole <deric.cole@intel.com>
=> EmulatorPkg/PeiTimerLib: Bug fix in NanoSecondDelay

RedfishPkg/RedfishPkg.dec, RedfishPkg/RedfishRestExDxe/RedfishRestExDxe.inf, RedfishPkg/RedfishRestExDxe/RedfishRestExImpl.c, RedfishPkg/RedfishRestExDxe/RedfishRestExProtocol.c
Since BIOS should work with different BMC implementation chunked requests as well as Expect header should be optional.
- One PCD is used to enable/disable Expect header.
- Another PCD is used to enable/disable chunked requests.
Signed-off-by: Igor Kulchytskyy <igork@ami.com>
=> RedfishPkg/RedfishRestExDxe: Two PCDs for controlling the requests

.mergify/config.yml
PR builds and CI are currently broken due to a mergify brownout today because edk2 uses the `rebase_fallback` attribute of the `queue` action.
Message from Mergify/Summary:
```
The configuration uses the deprecated rebase_fallback attribute
of the queue action.
A brownout is planned on February 13th, 2023.
This option will be removed on March 13th, 2023.
For more information: https://docs.mergify.com/actions/queue/
```
Therefore, this change removes the attribute per the guidance in the following changelog message to retain existing behavior.
https://changelog.mergify.com/changelog/rebasefallback-is-deprecated
```
The option rebase_fallback is now deprecated and should not be
used anymore.
Mergify will always report errors in the future if a rebase merge
is impossible.
```
Cc: Michael D …
=> .mergify/config.yml: Remove rebase_fallback attribute (deprecated)

MdeModulePkg/Bus/Pci/PciBusDxe/PciEnumeratorSupport.c
In V4: Update the copyright to 2023.
In V3: Add AMD copyright.
In V2: Remove the signed-off-by: Abner Chang
Display PCIe Vendor ID and Device ID in DEBUG message.
Cc: Garrett Kirkendall <garrett.kirkendall@amd.com>
=> MdeModulePkg/Pci: Display more information of PCIe devices

MdeModulePkg/Universal/EsrtFmpDxe/EsrtFmp.c
Skip error check if HardwareInstance is 0 as this either means that
FmpVersion < 3 and not supported or,
"A zero means the FMP provider is not able to determine a
unique hardware instance number or a hardware instance number
is not needed." per UEFI specification.
As the FmpInstances are merged and HardwareInstance is not used
remove error check in this case.
=> MdeModulePkg/EsrtFmpDxe: Support multiple devices with 0 HardwareInstance

MdeModulePkg/Library/PiDxeS3BootScriptLib/BootScriptSave.c
Some platforms don't support S3 with PcdAcpiS3Enable set as False. Debug mode bios will ASSERT at this time as Follows. ASSERT_RETURN_ERROR (Status = Out of Resources)
DXE_ASSERT!: Edk2\MdePkg\Library\BaseS3PciSegmentLib\S3PciSegmentLib.c (61): !(((INTN)(RETURN_STATUS)(Status)) < 0)
Steps to reproduce the issue:
1.Set PcdAcpiS3Enable to FALSE.
2.Build the bios in debug mode.
3.Power on and Check the serial log.
Note: Prerequisite is that S3PciSegmentLib is Called and the caller's code is run.
Root Cause:
S3PciSegmentLib call S3BootScriptLib controlled by PcdAcpiS3Enable. If PcdAcpiS3Enable set as false, S3BootScriptLib will return error status(Out of Resources).
S3PciSegmentLib will ASSERT if S3BootScriptLib return error.
Solution:
Make S3BootScriptLib return success if PcdAcpiS3Enable …
=> MdeModulePkg/Library: PcdAcpiS3Enable set FALSE cause Assert

BaseTools/Plugin/WindowsVsToolChain/WindowsVsToolChain.py, pip-requirements.txt
This patch updates edk2-pytool-library dependency to v0.14.0, which has an interface change to FindWithVsWhere. The BaseTools plugin uses this function, so it is being updated to account for the interface change. In addition, it updates edk2-pytool-extensions to v0.21.8 which has no breaking changes associated with edk2.
Signed-off-by: Joey Vagedes <joeyvagedes@microsoft.com>
Acked-by: Michael Kubacki <michael.kubacki@microsoft.com>
=> BaseTools: Update WindowsVsToolChain plugin

BaseTools/Conf/tools_def.template
Replace rv64imafdc with rv64gc so that it works for gcc 12.
"g" means imafd in gcc < 12 and imafd_zifencei_zicsr in gcc >= 12. So, replacing rv64imafdc with rv64gc will work for both gcc <12 and gcc >=12.
Cc: Heinrich Schuchardt <heinrich.schuchardt@canonical.com>
Tested-by: Gerd Hoffmann <kraxel@redhat.com>
Tested-by: Heinrich Schuchardt <heinrich.schuchardt@canonical.com>
=> BaseTools/tools_def.template: Update -march parameter for RISC-V

OvmfPkg/RiscVVirt/Sec/SecMain.c
Fix the UEFI memory range calculation by including the correct stack memory range. Without this fix, SCT hangs in MemoryAllocation test cases which call AllocateAddress().
Reported-by: Heinrich Schuchardt <heinrich.schuchardt@canonical.com>
Reviewed-by: Andrei Warkentin <andrei.warkentin@intel.com>
=> OvmfPkg/RiscVVirt: Fix SCT memory allocation test case failure

OvmfPkg/RiscVVirt/Sec/SecMain.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4350
Currently, stack HOB is not created for the stack memory. This causes stack memory to be treated as free memory and any memory allocation which happens at this address causes random memory corruption. Fix this by creating the stack HOB which marks the memory as BS data.
Reported-by: Andrei Warkentin <andrei.warkentin@intel.com>
Tested-by: Andrei Warkentin <andrei.warkentin@intel.com>
Reviewed-by: Andrei Warkentin <andrei.warkentin@intel.com>
=> OvmfPkg/RiscVVirt: Add Stack HOB

RedfishPkg/Include/Library/RedfishDebugLib.h, RedfishPkg/Library/RedfishDebugLib/RedfishDebugLib.c, RedfishPkg/Library/RedfishDebugLib/RedfishDebugLib.inf, RedfishPkg/RedfishLibs.dsc.inc, RedfishPkg/RedfishPkg.dec, RedfishPkg/RedfishPkg.dsc, RedfishPkg/RedfishRestExDxe/RedfishRestExDxe.inf, RedfishPkg/RedfishRestExDxe/RedfishRestExInternal.h, RedfishPkg/RedfishRestExDxe/RedfishRestExProtocol.c
Introduce RedfishDebugLib to RedfishPkg. This library provides several debugging functions for Redfish application. Redfish drivers rely on Rest Ex protocol to communicate with BMC and the communication data may be big and complicated. Use RedfishDebugLib in RedfishRestExDxe to simplify debugging process.
=> RedfishPkg/RedfishDebugLib: provide Redfish debug

MdeModulePkg/Bus/Usb/UsbBusDxe/UsbBus.c, MdeModulePkg/Bus/Usb/UsbBusDxe/UsbDesc.c, MdeModulePkg/Bus/Usb/UsbBusDxe/UsbEnumer.c, MdeModulePkg/Bus/Usb/UsbBusDxe/UsbHub.c
Patch sent at: https://edk2.groups.io/g/devel/message/100475
Improve the formatting of DEBUG messages in UsbBusDxe by adding a hyphen to separate the EFI_STATUS code.
=> MdeModulePkg: Improve formatting of DEBUG messages in UsbBusDxe

CryptoPkg/Library/BaseCryptLib/Hash/CryptSha1.c, CryptoPkg/Library/BaseCryptLib/Hash/CryptSha256.c, CryptoPkg/Library/BaseCryptLib/Hash/CryptSha512.c
In preparation for the openssl 3.0 switch ...
openssl 3.0 sneak preview (WIP still, does not yet pass CI) is at
https://github.com/kraxel/edk2/commits/openssl3
Gerd Hoffmann (4):
CryptoPkg/BaseCryptLib: avoid using SHA1()
CryptoPkg/BaseCryptLib: avoid using SHA256()
CryptoPkg/BaseCryptLib: avoid using SHA384()
CryptoPkg/BaseCryptLib: avoid using SHA512()
.../Library/BaseCryptLib/Hash/CryptSha1.c     | 16 ++++++++--
.../Library/BaseCryptLib/Hash/CryptSha256.c   | 16 ++++++++--
.../Library/BaseCryptLib/Hash/CryptSha512.c   | 32 +++++++++++++++----
3 files changed, 52 insertions(+), 12 deletions(-)
-- 
2.39.1
-=-=-=-=-=-=-=-=-=-=-=-
Groups.io Links: You receive all messages sent to this group.
View/Reply Online (#100123): https://edk2.groups.io/g/devel/message/100123
Mute This Topic: …
=> CryptoPkg/BaseCryptLib: avoid certain openssl library calls

UefiCpuPkg/Application/Cpuid/Cpuid.c, UefiCpuPkg/Library/RegisterCpuFeaturesLib/CpuFeaturesInitialize.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4348
Per SDM:
DisplayFamily = Extended_Family_ID + Family_ID.
DisplayModelID = (Extended_Model_ID << 4) + Family_ID. Correct the related code.
Cc: Mike Maslenkin <mike.maslenkin@gmail.com>
=> UefiCpuPkg: Calculate DisplayFamily correctly

IntelFsp2Pkg/Library/BaseFspPlatformLib/FspPlatformNotify.c
Function definition should match with declaration. [-Wlto-type-mismatch]
Cc: Sai Chaganty <rangasai.v.chaganty@intel.com>
Reviewed-by: Sai Chaganty <rangasai.v.chaganty@intel.com>
=> IntelFsp2Pkg: Fix GCC Compiler warning.

CryptoPkg/Library/OpensslLib/OpensslLib.inf, CryptoPkg/Library/OpensslLib/OpensslLibAccel.inf, CryptoPkg/Library/OpensslLib/OpensslLibCrypto.inf, CryptoPkg/Library/OpensslLib/OpensslLibFull.inf, CryptoPkg/Library/OpensslLib/OpensslLibFullAccel.inf
Upgrade openssl to 1.1.1t
Pick up bugfixes from the latest openssl release.
=> CryptoPkg/OpensslLib: Upgrade OpenSSL to 1.1.1t

UefiCpuPkg/MicrocodeMeasurementDxe/MicrocodeMeasurementDxe.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4360
An incorrect format specifier is being used in a DEBUG print, specifically, a variable of type EFI_STATUS was being printed with the %a format specifier (pointer to an ASCII string), thus the value of the Status variable was being treated as the address of a string, leading to a CPU exception, when encountered this bug manifests itself as a hang near "Ready to Boot Event", with the last DEBUG print being "INFO: Got MicrocodePatchHob with microcode patches starting address" followed by a CPU Exception dump.
Reviewed-by: Jacob Narey <jacob.narey@intel.com>
=> UefiCpuPkg/MicrocodeMeasurementDxe: Fix exception

DynamicTablesPkg/DynamicTables.dsc.inc, DynamicTablesPkg/DynamicTablesPkg.dec, DynamicTablesPkg/DynamicTablesPkg.dsc, DynamicTablesPkg/Include/Library/SmbiosStringTableLib.h, DynamicTablesPkg/Library/Common/SmbiosStringTableLib/SmbiosStringTableLib.c, DynamicTablesPkg/Library/Common/SmbiosStringTableLib/SmbiosStringTableLib.inf
The Section 6.1.3, SMBIOS specification version 3.6.0 describes the handling of test strings in SMBIOS tables.
Text strings are added at the end of the formatted portion of the SMBIOS structure and are referenced by index in the SMBIOS structure.
Therefore, introduce a SmbiosStringTableLib to simplify the publishing of the string set.
SmbiosStringTableLib introduces a concept of string table which records the references to the SMBIOS strings as they are added and returns an string reference which is then assigned to the string field in the formatted portion of the SMBIOS structure. Once all strings are added, the library provides an interface to get the required size for the string set. This allows sufficient memory to be allocated for the SMBIOS table. The library also provides an …
=> DynamicTablesPkg: Add SMBIOS String table helper library

BaseTools/Source/Python/build/BuildReport.py, BaseTools/Source/Python/build/buildoptions.py
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=2850
Add "-Y REPORT_INFO" option to build command to generate compile
information as part of BuildReport.
This option generates files to be used by external tools as IDE's
to enhance functionality.
Files are created inside build folder:
///CompileInfo
Files created:
compile_commands.json - Compilation Database. To be used by IDE's
to enable advance features
cscope.files - List of files used in compilation. Used by Cscope to parse
C code and provide browse functionality.
module_report.json - Module data form buildReport in Json format.
Adding following fields to module_report.json:
LibraryClass
ModuleEntryPointList
ConstructorList
DestructorList
Signed-off-by: Guillermo Antonio Palomino Sosa …
=> BaseTools: Generate compile information in build report

UefiCpuPkg/PiSmmCpuDxeSmm/CpuS3.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4368
This issue is caused by the commit:
ec07fd0e35d90dbcc36be300a9ceeac29c5de2ad
GetFirstGuidHob() should not be used after exit boot service.
Cc: Zeng Star <star.zeng@intel.com>
Tested-by: Gerd Hoffmann <kraxel@redhat.com>
=> UefiCpuPkg/PiSmmCpuDxeSmm: Fix S3 failure in SmmRestoreCpu

MdeModulePkg/Library/UefiBootManagerLib/BmBoot.c
Only enumerate devices that have media present.
Reviewed-by: Sean Rhodes <sean@starlabs.systems>
=> MdeModulePkg/BmBoot: Skip removable media if it is not present

CryptoPkg/Library/OpensslLib/OpensslLib.inf, CryptoPkg/Library/OpensslLib/OpensslLibAccel.inf, CryptoPkg/Library/OpensslLib/OpensslLibCrypto.inf, CryptoPkg/Library/OpensslLib/OpensslLibFull.inf, CryptoPkg/Library/OpensslLib/OpensslLibFullAccel.inf
The GCC warning fix is not in 1.1.1x. Ignore the warning type -Wno-unused-but-set-variable with GCC compiler in the build option.
=> CryptoPkg/Library: add -Wno-unused-but-set-variable for openssl

OvmfPkg/Library/PlatformBootManagerLib/BdsPlatform.h, OvmfPkg/Library/PlatformBootManagerLib/PlatformData.c
Time to leave behind relics from the last century and arrive in the modern world.  Drop PC-ANSI Terminal Type for the serial console, use UTF-8 instead.
=> OvmfPkg/PlatformBootManagerLib: use utf8 for the serial console.

MdePkg/Include/Ppi/SecPlatformInformation.h
Itanium support has been removed from EDK2 around 2019. ITANIUM_HANDOFF_STATUS data structure looks to be
some leftover from that process.
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=1560
GitHub: https://github.com/tianocore/edk2/commit/4e1daa60f5372c22a11503961061ffa569eaf873
There is also positive side effect of this data structure removal. Due to HOB allocation type used in PEI stage there is a limit how much data about virtual CPU can be hold. This limit result in only 1024 vCPU can be used by VM.
With Itanium related data structure removed more allocated space can be used for vCPU data and with current allocation limit will change from 1024 to around 8k vCPUs.
Cc: Zhiguang Liu …
=> MdePkg/Include/Ppi: Remove Itanium leftover data structure

MdePkg/Include/IndustryStandard/Mctp.h
BZ #4355
This change adds definitions for DMTF MCTP
base specification.
Spec ref:
https://www.dmtf.org/sites/default/files/standards/documents/DSP0236_1.3.1.pdf
Cc: Isaac Oram <isaac.w.oram@intel.com>
Acked-by: Isaac Oram <isaac.w.oram@intel.com>
=> MdePkg/Include: Add DMTF MCTP definitions

MdePkg/Include/IndustryStandard/IpmiKcs.h, MdePkg/MdePkg.dec
BZ #4354
This change adds definitions for IPMI KCS.
Spec ref:
https://www.intel.com/content/www/us/en/products/docs/servers/ipmi/ipmi-second-gen-interface-spec-v2-rev1-1.html
Cc: Isaac Oram <isaac.w.oram@intel.com>
Acked-by: Isaac Oram <isaac.w.oram@intel.com>
Reviewed-by: Tinh Nguyen <tinhnguyen@os.amperecomputing.com>
=> MdePkg/Include: Add IPMI KCS definitions

UefiPayloadPkg/UefiPayloadEntry/UniversalPayloadEntry.c
if system both exist gUefiAcpiBoardInfoGuid and rsdp, we may need to use gUefiAcpiBoardInfoGuid as final config to have backward support.
=> UefiPayloadPkg: Add gUefiAcpiBoardInfoGuid support

UefiCpuPkg/Library/MpInitLib/X64/MpFuncs.nasm
For the case CPU logic index is 0, RSP points to the very top of all AP stacks. That address is not mapped in page table.
=> UefiCpuPkg: Solve that stack top address is not mapped in pagetable

PcAtChipsetPkg/PcAtChipsetPkg.dec, PcAtChipsetPkg/PcAtChipsetPkg.uni, PcAtChipsetPkg/PcatRealTimeClockRuntimeDxe/PcRtc.c, PcAtChipsetPkg/PcatRealTimeClockRuntimeDxe/PcatRealTimeClockRuntimeDxe.inf
Add PcdRtcDefaultYear to specify the default year to use when the RTC is in an invalid state. 
Make sure PcdRtcDefaultYear is >= PcdMinimalValidYear and <= PcdMaximalValidYear.  Set the
default value for this PCD to PcdMinimalValidYear to preserve the existing behavior. 
A platform DSC file can override this default value setting.
=> PcAtChipsetPkg: Add PCD for RTC default year

UefiCpuPkg/Include/Library/CpuPageTableLib.h, UefiCpuPkg/Library/CpuPageTableLib/CpuPageTable.h, UefiCpuPkg/Library/CpuPageTableLib/CpuPageTableMap.c, UefiCpuPkg/Library/CpuPageTableLib/CpuPageTableParse.c, UefiCpuPkg/Library/CpuPageTableLib/UnitTest/CpuPageTableLibUnitTestHost.c, UefiCpuPkg/Library/CpuPageTableLib/UnitTest/RandomTest.c, UefiCpuPkg/Library/CpuPageTableLib/UnitTest/TestHelper.c, UefiCpuPkg/Library/MpInitLib/X64/CreatePageTable.c
Dun Tan (20):
UefiCpuPkg/CpuPageTableLib: Remove unneeded 'if' condition
UefiCpuPkg/CpuPageTableLib: Add check for input Length
UefiCpuPkg/CpuPageTableLib:Initialize some LocalVariable at beginning
UefiCpuPkg/CpuPageTableLib: Fix the non-1:1 mapping issue
UefiCpuPkg/CpuPageTableLib:Clear PageSize bit(Bit7) for non-leaf
UefiCpuPkg/CpuPageTableLib: Fix issue when splitting leaf entry
UefiCpuPkg/MpInitLib: Add code to initialize MapMask
UefiCpuPkg/CpuPageTableLib:Add check for Mask and Attr
UefiCpuPkg/CpuPageTableLib: Add manual test to check Mask and Attr
UefiCpuPkg/CpuPageTableLib:Modify RandomBoolean() in RandomTest
UefiCpuPkg/CpuPageTableLib: Add LastMapEntry pointer
UefiCpuPkg/CpuPageTableLib:Modify RandomTest to check Mask/Attr
UefiCpuPkg/CpuPageTableLib: Enable non-1:1 mapping in …
=> Fix issues in CpuPageTableLib

ArmVirtPkg/CloudHvPlatformHasAcpiDtDxe/CloudHvHasAcpiDtDxe.inf
commit f13264b34 introduces a bug for CloudHv as OvmfPkg/OvmfPkg.dec is missing in CloudHvHasAcpiDtDxe.inf which leads to
gUefiOvmfPkgTokenSpaceGuid found nowhere when build.
=> ArmVirtPkg: can't find gUefiOvmfPkgTokenSpaceGuid

RedfishPkg/Library/RedfishPlatformCredentialIpmiLib/RedfishPlatformCredentialIpmiLib.c, RedfishPkg/Library/RedfishPlatformCredentialIpmiLib/RedfishPlatformCredentialIpmiLib.h, RedfishPkg/Library/RedfishPlatformCredentialIpmiLib/RedfishPlatformCredentialIpmiLib.inf, RedfishPkg/RedfishLibs.dsc.inc, RedfishPkg/RedfishPkg.dec, RedfishPkg/RedfishPkg.dsc
This library follows Redfish Host Interface specification and use IPMI command to get bootstrap account credential(NetFn 2Ch, Command 02h) from BMC. RedfishHostInterfaceDxe will use this credential for the following communication between BIOS and BMC.
Reviewed-by: Igor Kulchytskyy <igork@ami.com>
=> RedfishPkg/RedfishPlatformCredentialIpmiLib: IPMI implementation

.azurepipelines/templates/platform-build-run-steps.yml
Increase the CI agent timeout to boot to UEFI Shell from 1 minute to 2 minutes.  There have been a few cases where the boot to shell in QEMU has not quite completed in 1 minute and it is failing the CI check and preventing a PR from being merged.
=> .azurepipelines/templates: Increase run to shell timeout

OvmfPkg/PlatformCI/PlatformBuildLib.py
This is causing excessive boot times in the VS2019 IA32/X64 Full run to shell tasks (> 2 minutes) and blocking all edk2 CI.
This patch removes the change so it can be root caused separately without blocking other patches unrelated to OVMF.
Reverts f92a9dce10281c103b04d6b38283e0ff1d677b91
=> OvmfPkg/CI: Revert SMP mode

MdeModulePkg/Bus/Ata/AtaAtapiPassThru/AhciMode.c, MdeModulePkg/Bus/Ata/AtaAtapiPassThru/AhciMode.h
Patch sent at: https://edk2.groups.io/g/devel/message/101980
Cover-letter (contains general patch description and test information) is at: https://edk2.groups.io/g/devel/message/101979
bugzilla: https://bugzilla.tianocore.org/show_bug.cgi?id=4011
Currently AHCI driver will try to retry all failed packets regardless of the failure cause. This is a problem in password unlock flow where number of password retries is tracked by the device. If user passes a wrong password Ahci driver will try to send the wrong password multiple times which will exhaust number of password retries and force the user to restart the machine. This commit introduces a logic to check for the cause of packet failure and only retry packets which failed due to transient conditions on the link. With this patch only …
=> MdeModulePkg/Ahci: Skip retry for non-transient errors

UefiCpuPkg/Library/CpuPageTableLib/UnitTest/CpuPageTableLibUnitTestHost.c
The random test cases just run for too long that may cause timeout
in CI test.
Disable them for now.
Co-authored-by: Michael Kubacki <michael.kubacki@microsoft.com>
=> UefiCpuPkg/Test: Disable random test cases

.github/workflows/codeql-analysis.yml
Adds caching of PIP dependencies. This reduces overall execution time and decreases likelihood of a network error reaching out pypi to get the dependencies.
Caching happens based on modules specified in pip-requirements.txt.
=> .github/workflows/codeql-analysis.yml: Add PIP caching

.github/dependabot.yml
Sets the rebase-strategy to "disabled" to prevent automatic rebasing.
Rebasing can be done manually in the dependabot PR either through the GitHub UI or the dependabot command.
=> .github/dependabot.yml: Disable automatic rebasing

.azurepipelines/templates/pr-gate-build-job.yml, .github/workflows/codeql-analysis.yml
MdeModulePkg and CryptoPkg have double the CodeQL analysis
time of all other packages.  Split these packages up to perform
separate analysis of IA32 and X64.
CryptoPkg has double the build time of all other packages.
Split CryptoPkg up matching the style applied to MdeModulePkg.
Cc: Sean Brogan <[sean.brogan@microsoft.com](mailto:sean.brogan@microsoft.com)>
Cc: Michael Kubacki <[mikuback@linux.microsoft.com](mailto:mikuback@linux.microsoft.com)>
Cc: Liming Gao <[gaoliming@byosoft.com.cn](mailto:gaoliming@byosoft.com.cn)>
Signed-off-by: Michael D Kinney <[michael.d.kinney@intel.com](mailto:michael.d.kinney@intel.com)>
=> Balance CI Execution Times

IntelFsp2Pkg/FspSecCore/Ia32/SaveRestoreSseNasm.inc, IntelFsp2Pkg/Include/SaveRestoreSseAvxNasm.inc
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4395
FSP specification defines the TempRamInit API preserved register list which including EBX/RBX, however current implementation unexpectedly overriding EBX/RBX register that should be fixed.
=> IntelFsp2Pkg: TempRamInit API should preserve EBX/RBX register.

IntelFsp2Pkg/FspSecCore/Ia32/FspApiEntryT.nasm, IntelFsp2Pkg/FspSecCore/X64/FspApiEntryT.nasm
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4391
FSP should support the scenario that CPU microcode already loaded before calling LoadMicrocodeDefault(), in this case it should return directly without spending more time.
Also the LoadMicrocodeDefault() should only attempt to load one version of the microcode for current CPU and return directly without parsing rest of the microcode in FV.
This patch also removed unnecessary LoadCheck code after supporting CPU microcode already loaded scenario.
Reviewed-by: Ted Kuo <ted.kuo@intel.com>
=> IntelFsp2Pkg: LoadMicrocodeDefault() causing unnecessary delay.

pip-requirements.txt
Bump the version of edk2-basetools in pip-requirements.txt to 0.1.43. This version contains the update to generate makefiles with both CFLAGS and BUILD_CFLAGS.
=> pip-requirements.txt: bump edk2-basetools to 0.1.43

BaseTools/Source/C/VfrCompile/Pccts/antlr/makefile
Update the antlr makefile to remove the explicit setting of CC to either
clang or gcc. This causes it to use /usr/bin/cc or whatever the user has
set $(CC) to.
This removes the last dependency on gcc for BaseTools.
=> BaseTools: Update antlr makefile to use cc by default

OvmfPkg/Library/VirtioMmioDeviceLib/VirtioMmioDeviceFunctions.c
Nothing to do here for virtio 1.0 devices
=> OvmfPkg/VirtioMmioDeviceLib: virtio 1.0: Fix SetQueueAlignment.

MdeModulePkg/Universal/RegularExpressionDxe/OnigurumaUefiPort.h
Fix GCC build error on AARCH64 system.
Signed-off-by: Nickle Wang <nicklew@nvidia.com>
=> MdeModulePkg/RegularExpressionDxe: Fix GCC build error

.git-blame-ignore-revs
Add a .git-blame-ignore-revs file containing the hashes of every uncrustify format commit as retrieved in:
git log --oneline --no-abbrev-commit  | grep "uncrustify"
This file can be used by tools (such as GitHub[1]) to ignore certain revisions when git blame-ing a file.
It can also be trivially usable locally by doing something akin to:
git config blame.ignoreRevsFile .git-blame-ignore-revs
It may also be desirable in the future to add more commits to it.
Signed-off-by: Pedro Falcato <pedro.falcato@gmail.com>
[1]: https://github.blog/changelog/2022-03-24-ignore-commits-in-the-blame-view-beta/
=> edk2: Add .git-blame-ignore-revs file

IntelFsp2Pkg/Tools/PatchFv.py, IntelFsp2Pkg/Tools/UserManuals/PatchFvUserManual.md
https://bugzilla.tianocore.org/show_bug.cgi?id=4412
After shrinking the FSP (FV) component using FMMT, Image size in FSP info header is not in sync with the FV length in FV header. This enhancement helps to patch the FSP image size offset with correct length & can be used to patch any offset directly on the FSP Component Fd.
Reviewed-by: Ted Kuo <ted.kuo@intel.com>
=> IntelFsp2Pkg/Tools: Enhance PathFv.py to patch Fd file directly

CryptoPkg/Library/BaseCryptLibOnProtocolPpi/DxeCryptLib.inf
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4413
Make the DXE_CORE module able to call the crypto protocol, which can reduce FV size on platforms using the Crypto Binaries.
=> CryptoPkg: Enable DXE_CORE support in DxeCryptLib.inf

MdePkg/Include/IndustryStandard/Pldm.h
BZ #4396
This change adds definitions for DMTF PLDM
base specification.
Spec ref:
https://www.dmtf.org/sites/default/files/standards/documents/DSP0240_1.1.0.pdf
Cc: Isaac Oram <isaac.w.oram@intel.com>
=> MdePkg/Include: Add DMTF PLDM Base definitions

UefiPayloadPkg/UefiPayloadPkg.fdf, UefiPayloadPkg/UniversalPayloadBuild.py
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4417
Since UefiPayload had supported multiple FV,
move Network.fdf.inc to new firmware volume and
add this network FV into elf file.
=> UefiPayloadPkg: Move Network modules from Dxe FV to Network FV in elf

ArmPkg/Include/Chipset/AArch64.h
ArmCpuInfo needs to be able to read ID_AA64ISAR2_EL1 system register. Older toolchains do not know it.
Same solution as one for QEMU:
https://www.mail-archive.com/qemu-devel@nongnu.org/msg929586.html
=> ArmPkg: older assemblers may lack ID_AA64ISAR2_EL1

BaseTools/Plugin/HostBasedUnitTestRunner/HostBasedUnitTestRunner.py
HostBasedUnitTestRunner.py is a build plugin responsible for locating and executing host-based unit tests.
Recently, commit 6bb00aa introduced support for the plugin to generate code coverage reports via lcov and OpenCppCoverage.
The plugin has discovered unit tests by searching for executables with "Test" in the name for a while. However, the test coverage change makes assumptions about test presence when crafting the OpenCppCoverage command that ultimately fails with an ambiguous error message if no host-based unit tests are discovered (see "ERROR").
```
SECTION - Run Host based Unit Tests
SUBSECTION - Testing for architecture: X64
ERROR - UnitTest Coverage: Failed to generate cobertura format xml in
single package.
PROGRESS - --->Test Success: Host Unit Test Compiler Plugin NOOPT
``` …
=> BaseTools/Plugin: Clarify code coverage failure message

MdePkg/Include/Library/DebugLib.h, MdePkg/MdePkg.dec
Bug #4414
Add DEBUG_MANAGEABILITY print error lever to
output debug message of detailed manageability
related module information, such as
- RedfishPkg:
- HTTP header/request/response
- JSON plain text
- Refish resource
- Redfish Host interface information
- Redfish credential information
- Platform configuration to Redfish mapping
- etc.
- ManageabilityPKg
- Protocol payload of MCTP/PLDM/IPMI
- Payload of transport interface transfers
- IPMI BLOB transfer
- etc.
- RedfishClinetPkg
- Redfish feature driver dispatcher
- Redfish BIOS attributes
- Platform configuration (HII) to Redfish property information
- Redfish C structure information
- etc.
Cc: Nickle …
=> MdePkg: Add DEBUG_MANAGEABILITY print error level

BaseTools/Conf/build_rule.template
Add quotes around the OBJCOPY command in build_rule.template to fix the case where LLVM is installed on Windows in a path with spaces such as C:\Program Files\LLVM.
=> BaseTools: Add quotes around OBJCOPY cmd in build_rule.template

DynamicTablesPkg/Library/Acpi/Arm/AcpiSsdtCpuTopologyLibArm/SsdtCpuTopologyGenerator.c, DynamicTablesPkg/Library/Acpi/Arm/AcpiSsdtCpuTopologyLibArm/SsdtCpuTopologyGenerator.h
The topology of a platform is represented in ACPI using the PPTT table. It is possible to append information to CPUs/processor containers using their associated AML nodes in a SSDT table.
A platform might have multiple 'physical packages' (or top-level nodes) in their PPTT topology representation. It can be assumed from [1] that a 'physical packages' is always a 'top-level node', and conversely.
The SSDT topology generator doesn't support having multiple top-level nodes. The top-level node is also not generated in the SSDT topology representation.
Add support to generate multiple top-level nodes in the SSDT topology generator and generate an AML node for this top-level node. This will allow to have matching PPTT and SSDT topology representations. Prior to this patch, this top-level AML …
=> DynamicTablesPkg/SsdtCpuTopology: Allow multi-packages topologies

RedfishPkg/RedfishConfigHandler/RedfishConfigHandlerDriver.c, RedfishPkg/RedfishDiscoverDxe/RedfishDiscoverDxe.c, RedfishPkg/RedfishDiscoverDxe/RedfishDiscoverInternal.h
gRedfishDiscoveredToken may be allocated several times, if multiple NIC installed on the system.
To avoid this issue Discover Token related global variables replaced with the local variables.
=> RedfishPkg: Remove the Discover Token global variables

OvmfPkg/AmdSevDxe/AmdSevDxe.c, OvmfPkg/Include/Guid/ConfidentialComputingSevSnpBlob.h, OvmfPkg/Library/CcExitLib/CcExitVcHandler.c
From: Michael Roth <michael.roth@amd.com>
Date: 4/26/2023 4:32:54 AM
Subject: [PATCH v2 0/4] Fixes for SEV-SNP CC blob and CPUID table handling
(Mainly a resend of v1, but rolled in Gerd's Acked-by's, addressed
new coding style check in the CI, and updated Cc list)
Here are a number of fixes related to OVMF handling of the SEV-SNP
Confidential Computing blob and CPUID table.
Patch #1 is a fix for recently-reported issue that can cause
significant problems with some SEV-SNP guest operating systems.
Please consider applying this patch directly if the other
patches in this series are held up for any reason.
Patches 2-4 are minor changes for things that aren't currently
triggered in practice, but make OVMF's SEV-SNP implementation more
robust for different build/hypervisor environments in the …
=> Fixes for SEV-SNP CC blob and CPUID table handling

UefiPayloadPkg/Tools/ElfFv.py, UefiPayloadPkg/Tools/__init__.py, UefiPayloadPkg/UefiPayloadPkg.ci.yaml, UefiPayloadPkg/UniversalPayloadBuild.py
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4426
Use Python to replace llvm-objcopy in UniversalPayloadBuild.py.
1. AddSection32() and AddSection64(): Make a section named <section> with the contents of <file>.
2. RemoveSection32() and RemoveSection64(): Remove <section>.
3. ReplaceFv (): remove the section before add the section if the file exists.
reviewed-by: Gua Guo <gua.guo@intel.com>
=> UefiPayloadPkg: Clang dependency removal

SecurityPkg/Library/DxeImageVerificationLib/DxeImageVerificationLib.c
Add the AUTH_SIG_NOT_FOUND Action to the Image Execution Info Table when the Image is signed but signature is not allowed by DB and the hash of image is not found in DB/DBX.
This is documented in the UEFI spec 2.10, table 32.5.
This issue is found by the SIE SCT with the error message as follows: SecureBoot - TestImage1.bin in Image Execution Info Table with SIG_NOT_FOUND. --FAILURE
B3A670AA-0FBA-48CA-9D01-0EE9700965A9
SctPkg/TestCase/UEFI/EFI/RuntimeServices/SecureBoot/BlackBoxTest/ ImageLoadingBBTest.c:1079:Status Success
Reviewed-by: Min Xu <min.m.xu@intel.com>
=> SecurityPkg/DxeImageVerificationLib: Add AUTH_SIG_NOT_FOUND Action

MdeModulePkg/Universal/RegularExpressionDxe/OnigurumaUefiPort.c, MdeModulePkg/Universal/RegularExpressionDxe/OnigurumaUefiPort.h
Arm CI build error:
- ArmPkg/Library/CompilerIntrinsicsLib/memset.c:39:1: warning: type of ‘memset’ does not match original declaration [-Wlto-type-mismatch] MdeModulePkg/Universal/RegularExpressionDxe/OnigurumaUefiPort.c:123:1: note: type ‘char’ should match type ‘int’
- multiple definition of `memcpy'; OnigurumaUefiPort.obj (symbol from plugin):(.text+0x0): first defined here
Fix:
- Update memset() implementation to match memset() definition in ArmPkg/Library/CompilerIntrinsicsLib.
- memcpy() is supported by ArmPkg/Library/CompilerIntrinsicsLib. Exclude it in OnigurumaUefiPort.c.
=> MdeModulePkg/RegularExpressionDxe: Fix Arm build error

UefiPayloadPkg/Library/BaseSerialPortLibHob/BaseSerialPortLibHob.c, UefiPayloadPkg/Library/BaseSerialPortLibHob/DxeBaseSerialPortLibHob.c, UefiPayloadPkg/Library/BaseSerialPortLibHob/DxeBaseSerialPortLibHob.inf, UefiPayloadPkg/UefiPayloadPkg.dsc
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4427
1. Since UART speed is slower than CPU, BIOS need to check the write buffer is empty, to avoid overwrite the buffer content.
2. LPSS UART might disable MMIO space for Windows debug usage during ExitBootServices event. BIOS need to avoid access the MMIO space after ExitBootServices.
=> UefiPayloadPkg: Fix issues when MULTIPLE_DEBUG_PORT_SUPPORT is true

.gitmodules, .pytool/CISettings.py, MdePkg/Include/Library/FdtLib.h, MdePkg/Library/BaseFdtLib/BaseFdtLib.inf, MdePkg/Library/BaseFdtLib/BaseFdtLib.uni, MdePkg/Library/BaseFdtLib/FdtLib.c, MdePkg/Library/BaseFdtLib/LibFdtSupport.h, MdePkg/Library/BaseFdtLib/LibFdtWrapper.c, MdePkg/Library/BaseFdtLib/limits.h, MdePkg/Library/BaseFdtLib/stdbool.h, MdePkg/Library/BaseFdtLib/stddef.h, MdePkg/Library/BaseFdtLib/stdint.h, MdePkg/Library/BaseFdtLib/stdlib.h, MdePkg/Library/BaseFdtLib/string.h, MdePkg/MdePkg.ci.yaml, MdePkg/MdePkg.dec, MdePkg/MdePkg.dsc, ReadMe.rst
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4392
Add FDT support in EDK2 by submodule 3rd party libfdt
(https://github.com/devicetree-org/pylibfdt/tree/main/libfdt)
and refer to LibcLib implementation by Pedro.
Cc: Michael D Kinney <[michael.d.kinney@intel.com](mailto:michael.d.kinney@intel.com)>
Cc: Liming Gao <[gaoliming@byosoft.com.cn](mailto:gaoliming@byosoft.com.cn)>
Cc: Zhiguang Liu <[zhiguang.liu@intel.com](mailto:zhiguang.liu@intel.com)>
Cc: Sean Brogan <[sean.brogan@microsoft.com](mailto:sean.brogan@microsoft.com)>
Cc: Michael Kubacki <[mikuback@linux.microsoft.com](mailto:mikuback@linux.microsoft.com)>
Acked-by: Pedro Falcato <[pedro.falcato@gmail.com](mailto:pedro.falcato@gmail.com)>
Signed-off-by: Benny Lin <[benny.lin@intel.com](mailto:benny.lin@intel.com)>
V7:
Update …
=> Bug 4392 add fdt lib v7

MdePkg/Library/BaseSynchronizationLib/LoongArch64/AsmSynchronization.S, MdePkg/Library/BaseSynchronizationLib/LoongArch64/Synchronization.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4432
There is a return value bug:
The sc.w/sc.d instruction will destroy the reg_t0, use reg_t1 to avoid context reg_t0 being corrupted. Adjust Check that ptr align is UINT16.
Optimize function SyncIncrement and SyncDecrement.
Reviewed-by: Chao Li <lichao@loongson.cn>
=> BaseSynchronizationLib: Fix LoongArch64 synchronization functions

MdeModulePkg/Bus/Pci/NvmExpressDxe/NvmExpressPassthru.c, MdeModulePkg/Bus/Pci/NvmExpressPei/NvmExpressPeiPassThru.c
Cover-letter is at: https://edk2.groups.io/g/devel/message/103725
NVMe CQs are hardware queues mapped to EFI memory.
In the NVMExpress Passthru implementations in PEI and DXE,
it has been observed that NVMe CQs are not marked
volatile, meaning the compiler has significant leeway
to optimize accesses to these structures.
This led to an issue where the passthru driver waited
for a timeout period for an NVMe CQ to mark that it was
finished with a transaction, but the compiler had
optimized away the read to the actual HW mapped memory,
so the transaction had completed but the timeout continued.
Marking the CQs as volatile fixes this issue as the reads
happen to the actual HW.
Personal GitHub PR: https://github.com/tianocore/edk2/pull/4320
Github branch: …
=> Add Volatile Keyword to NvmExpress Passthru CQs

CryptoPkg/Library/BaseCryptLib/BaseCryptLib.inf, CryptoPkg/Library/BaseCryptLib/PeiCryptLib.inf, CryptoPkg/Library/BaseCryptLib/RuntimeCryptLib.inf, CryptoPkg/Library/BaseCryptLib/SecCryptLib.inf, CryptoPkg/Library/BaseCryptLib/SmmCryptLib.inf, CryptoPkg/Library/BaseCryptLib/UnitTestHostBaseCryptLib.inf, CryptoPkg/Library/OpensslLib/OpensslLib.inf, CryptoPkg/Library/OpensslLib/OpensslLibAccel.inf, CryptoPkg/Library/OpensslLib/OpensslLibCrypto.inf, CryptoPkg/Library/OpensslLib/OpensslLibFull.inf, CryptoPkg/Library/OpensslLib/OpensslLibFullAccel.inf
Since CLANG35 and CLANG38 toolchains have been deleted from tools_def.template, delete the build flags for them from CryptoPkg.
Since CLANGDWARF has replaced CLANG38, add build flags for it to the CryptoPkg .inf files.
=> CryptoPkg: Delete CLANG35 and CLANG38 build flags; add CLANGDWARF flags

SecurityPkg/Library/Tpm2CommandLib/Tpm2Capability.c
Add missing break in Tpm2TestParms.
Reported in https://github.com/tianocore/edk2/issues/4073
=> SecurityPkg: Add missing break in Tpm2TestParms

BaseTools/Plugin/HostBasedUnitTestRunner/HostBasedUnitTestRunner.py
[BaseTools/Plugin: Too many execute files cause "cmd too long" failure](https://github.com/tianocore/edk2/pull/4357/commits/61e102375ff25dc4db3bc33473a56e42f1364e11) 
Windows command prompt have 8191 characters limitation,
enhance it to make command too long can be resloved.
Provide an example, if have too many cov files, it causes to run single
command over the 8191 characters limitation.
> OpenCppCoverage
>  --export_type binary:coverage.cov
>  --working_dir={workspace}Build
>  --input_coverage=AAA.cov
>  ...
>  --input_coverage=NNN.cov
The solution is passing many coverage files in single command line to
breaking it up into many command lines with one coverage file per
command line in order to prevent single line is over to 8191 characters.
- Command Line 1
> OpenCppCoverage
> …
=> BaseTools/Plugin: Too many execute file will be failure

UefiPayloadPkg/Library/PlatformBootManagerLib/PlatformBootManager.c, UefiPayloadPkg/Library/PlatformBootManagerLib/PlatformBootManagerLib.inf, UefiPayloadPkg/UefiPayloadPkg.dec
After moving BDS driver to a new FV for universal UEFI payload, the shell boot option path is not correct since it used the BDS FV instead of DXE FV in its device path.
This patch would find the correct FV by reading shell file. It also removed PcdShellFile by using gUefiShellFileGuid.
=> UefiPayloadPkg: Fix boot shell issue for universal UEFI payload

MdePkg/Include/Library/BaseRiscVSbiLib.h, MdePkg/Library/BaseRiscVSbiLib/BaseRiscVSbiLib.c, MdePkg/Library/BaseSerialPortLibRiscVSbiLib/BaseSerialPortLibRiscVSbiLib.c, MdePkg/Library/BaseSerialPortLibRiscVSbiLib/BaseSerialPortLibRiscVSbiLib.inf, MdePkg/Library/BaseSerialPortLibRiscVSbiLib/BaseSerialPortLibRiscVSbiLib.uni, MdePkg/Library/BaseSerialPortLibRiscVSbiLib/BaseSerialPortLibRiscVSbiLibRam.c, MdePkg/Library/BaseSerialPortLibRiscVSbiLib/BaseSerialPortLibRiscVSbiLibRam.inf, MdePkg/Library/BaseSerialPortLibRiscVSbiLib/Common.c, MdePkg/Library/BaseSerialPortLibRiscVSbiLib/Common.h, MdePkg/MdePkg.dsc, OvmfPkg/RiscVVirt/Sec/SecMain.c, OvmfPkg/RiscVVirt/Sec/SecMain.h, OvmfPkg/RiscVVirt/Sec/SecMain.inf
Here are three patches that provide a SerialLib backed by SBI console. 
Both legacy and DBCN mechanisms are supported in various execution environments and have been tested with UART and HTIF consoles.
MdePkg reviewers: please review MdePkg.dsc changes.
This is also available at
https://github.com/andreiw/edk2-rv-wip/tree/patchset-2
A CI run is at https://github.com/tianocore/edk2/pull/4252
Compared to v6:
- Unify the two SerialLib implementations under one directory and
factor out the code somewhat.
- Sunil's feedback on correctness.
Compared to v5:
Rename components as per Michael Kinney's suggestions.
Compared to v4:
(not sent out). CC MdePkg maintainers, fix copyright date in SecMain.c.
Compared to v3
EccCheck fixes. Add MdePkg infs to DSC.
Compared to v2:
- Probes legacy extension as …
=> Bug xxx sbi serial port

ArmPkg/Library/ArmMmuLib/AArch64/ArmMmuLibReplaceEntry.S
The helper that updates live page table entries writes a zero entry, invalidates the covered address range from the TLBs, and finally writes the actual entry. This ensures that no TLB conflicts can occur.
Writing the final entry needs to complete before any translations can be performed, as otherwise, the zero entry, which describes an invalid translation, may be observed by the page table walker, resulting in a translation fault. For this reason, the final write is followed by a DSB barrier instruction.
However, this barrier will not stall the pipeline, and instruction fetches may still hit this invalid translation, as has been observed and reported by Oliver. To ensure that the new translation is fully active before returning from this helper, we have to insert an ISB barrier as well. …
=> ArmPkg/ArmMmuLib AARCH64: Add missing ISB after page table update

MdeModulePkg/Core/Pei/Dispatcher/Dispatcher.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4438
The main dispatch loop in PeiDispatcher() goes through each FV and calls DiscoverPeimsAndOrderWithApriori() to search Apriori file to reorder all PEIMs then do the PEIM dispatched.
DiscoverPeimsAndOrderWithApriori() calculates Apriori file count for every FV once and set Private->AprioriCount, but Private->AprioriCount doesn't be set to 0 before dispatch loop walking through the next FV.
It causes the peim which sort on less than Private->AprioriCount and depex is not satisfied would be dispatched when dispatch loop go through to a scaned FV, even the peim is not set in APRIORI file.
Cc: Leon Chen <leon.chen@insyde.com>
Cc: Tim Lewis <tim.lewis@insyde.com>
Reported-by: Esther Lee <esther.lee@insyde.com>
Reviewed-by: Liming Gao …
=> MdeModulePkg/Core/Pei: set AprioriCount=0 before walking through next FV

BaseTools/toolsetup.bat
Ideally behavior is like below order that can support one local build machine, clone multiple Edk2, some of edk2 repo use old tag and some of edk2 repo use new tag, they can both support on one machine.
1. if defined PYTHON_COMMAND only
- use PYTHON_COMMAND = user assigned
2. if not defined PYTHON_COMMAND, auto detect py -3
- use PYTHON_COMMAND = py -3
3. if defined PYTHON_COMMAND and PYTHON_HOME, use PYTHON_COMMAND
- use PYTHON_COMMAND = user assigned
4. if defined PYTHON_HOME only,
- use PYTHON_COMMAND = %PYTHON_HOME%/python.exe
SCRIPT_ERROR should return for paraent batch file to consume for error handle.
=> BaseTools: toolsetup.bat always execute PYTHON_HOME

PcAtChipsetPkg/PcatRealTimeClockRuntimeDxe/PcRtc.c, PcAtChipsetPkg/PcatRealTimeClockRuntimeDxe/PcRtcEntry.c
RTC runtime is unable to get dynamic PCD value after booting to OS using runtime services.
Resolution: Cache the dynamic PCD value in RTC driver entry point
=> PcAtChipsetPkg: RTC Runtime unable to get correct IO port by PCD

MdeModulePkg/Bus/Pci/SdMmcPciHcDxe/SdMmcPciHci.c
Patch sent at: https://edk2.groups.io/g/devel/message/104785
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4394
Fix DumpCapabilityReg() debug log to print 64 bit capability instead of 32 bit pointer
=> MdeModulePkg SdMmcPciHcDxe: SD/MMC capability debug print is incorrect

OvmfPkg/VirtioSerialDxe/VirtioSerial.c
Move init of local variable structure fom declaration to statements to fix VS2015x86 build break.
=> OvmfPkg/VirtIoSerialDxe: Update for 2015x86 compatibility

RedfishPkg/RedfishPlatformConfigDxe/RedfishPlatformConfigDxe.c
Fix incorrect value type issue for checked-box op-code. When the variable for checked-box is defined as UINT8 in varstore structure, IFR compiler assign its value type to EFI_IFR_TYPE_NUM_SIZE_8 instead of EFI_IFR_TYPE_BOOLEAN. However, the value type for checked-box is boolean value. Redfish service may return error because of incorrect value type passed to BIOS attribute registry.
=> RedfishPkg/RedfishPlatformConfigDxe: fix value type issue.

IntelFsp2WrapperPkg/FspmWrapperPeim/FspmWrapperPeim.c, IntelFsp2WrapperPkg/FspsWrapperPeim/FspsWrapperPeim.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4458
Original code call PeiServicesInstallFvInfoPpi() with NULL for the FvFormat parameter, then PeiServicesInstallFvInfoPpi() will assume it use FFS2, then ASSERT if FSP-S/M use FFS3.
Now set the FvFormat to the info got from FvHeader.
Reviewed-by: S Ashraf Ali <ashraf.ali.s@intel.com>
=> IntelFsp2WrapperPkg: Fix ASSERT when FSP-S/M use FFS3.

IntelFsp2Pkg/Library/BaseFspCommonLib/FspCommonLib.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4200
FspData->PerfIdx is getting increased for every call unconditionally in the function SetFspMeasurePoint and hence memory access can happen for out of bound FspData->PerfData[] array entries also.
Example -
FspData->PerfData is an array of 32 UINT64 entries. Assume a call
is made to SetFspMeasurePoint function when the FspData->PerfIdx
last value is 31. It gets incremented to 32 at line 400.
Any subsequent call to SetFspMeasurePoint functions leads to
FspData->PerfData[32] getting accessed which is out of the PerfData
array as well as the FSP_GLOBAL_DATA structure boundary.
Hence keep array access and index increment inside if block only and return invalid performance timestamp when PerfIdx is invalid.
Cc: Chasel Chiu …
=> IntelFsp2Pkg/Library/BaseFspCommonLib: Fix OVERRUN Coverity issue

UefiCpuPkg/PiSmmCpuDxeSmm/CpuService.c, UefiCpuPkg/PiSmmCpuDxeSmm/PiSmmCpuDxeSmm.c
add Ap Rendezvous check in PerformRemainingTasks and check cpu sync mode in  SmmCpuRendezvous().
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4424
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4431
In Ap relaxed mode, some SMI handlers should call SmmWaitForApArrival() to 
let all ap arrive in SmmCpuRendezvous(). But in traditional mode, these SMI 
handlers don't need to call SmmWaitForApArrival() again. So it need to be 
check cpu sync mode before calling SmmWaitForApArrival().
In Relaxed-AP Sync Mode, BSP will not wait for all Aps arrive. However,
PerformRemainingTasks() needs to wait all Aps arrive before calling
SetMemMapAttributes and ConfigSmmCodeAccessCheck() when mSmmReadyToLock
is true. In SetMemMapAttributes(), SmmSetMemoryAttributesEx() will call
FlushTlbForAll() …
=> UefiCpuPkg:  check cpu sync mode in  SmmCpuRendezvous()

ShellPkg/Library/UefiShellDriver1CommandsLib/Disconnect.c
In case ShellConvertStringToUint64() fails the Handles are left uninitialized.  That can for example happen for Handle2 and Handle3 in case only one parameter was specified on the command line. Which can trigger the ASSERT() in line 185.
Reproducer: boot ovmf to efi shell in qemu, using q35 machine type, then try disconnect the sata controller in efi shell.
Fix that by explicitly setting them to NULL in that case.  While being at it also simplify the logic and avoid pointlessly calling ShellConvertStringToUint64() in case ParamN is NULL.
=> ShellPkgDisconnect: zero-initialize handles

ArmPkg/ArmPkg.ci.yaml
Uncrustify checks are too rigid, making them counter-productive:
- it leads to code that is arguably harder to parse visually (e.g., the changes to ArmPkg/Include/Chipset/AArch64Mmu.h in commit 429309e0c6b74792)
- it forces indentation-only changes to code in the vicinity of actual changes, making the code history more bloated than necessary (see commit 7f198321eec0f520373 for an example)
- finding out from the web UI what exactly Uncrustify objected to is not straight-forward.
So let's enable AuditMode for ArmPkg, so that interested parties can see the uncrustify recommendations if desired, but without preventing the changes from being merged. This leaves it at the discretion of the ArmPkg maintainers to decide which level of conformance is required.
Cc: Leif Lindholm …
=> ArmPkg: Enable AuditMode for Uncrustify CI checks

.pytool/Plugin/CharEncodingCheck/CharEncodingCheck.py
Currently, CharEncodingCheckPlugin prints a message for every file that passes the test, which for some platforms can cause most of the CI build log to be filled with this print. It does not add any value, so this patch removes the noisy print and only prints if the encoding check fails.
=> [CI Check]CharEncodingCheckPlugin: Remove Noisy Print

MdePkg/Include/IndustryStandard/Acpi65.h
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4474
ACPI_Spec_6_5_Aug29 Table 5.19 page #128 that MADT Revision field is 6.
=> MdePkg ACPI65: Update MADT Revision pre ACPI Spec 6.5

MdePkg/Library/BaseLib/BaseLib.inf, MdePkg/Library/BaseLib/RiscV64/SpeculationBarrier.S
Implement the SpeculationBarrier with implementations consisting of fence instruction which provides finer-grain memory orderings. Perform Data Barrier in RiscV: fence rw,rw
Perform Instruction Barrier in RiscV: fence.i; fence r,r More detail is in Appendix A: RVWMO Explanatory Material in https://github.com/riscv/riscv-isa-manual
This API is first introduced in the below commits for IA32 and x64 https://github.com/tianocore/edk2/commit/d9f1cac51bd354507e880e614d11a1dc160d38a3 https://github.com/tianocore/edk2/commit/e83d841fdc2878959185c4c6cc38a7a1e88377a4 and below the commit for ARM and AArch64 implementation https://github.com/tianocore/edk2/commit/c0959b4426b2da45cdb8146a5116bb4fd9b86534
This commit is to add the RiscV64 implementation which will be used by variable service under …
=> MdePkg/BaseLib: Add SpeculationBarrier implementation for RiscV64

MdeModulePkg/Bus/Ata/AhciPei/AhciPeiPassThru.c
Patch sent at: https://edk2.groups.io/g/devel/message/105204
If there is no port multiplier, PortMultiplierPort should be converted to 0 to follow AHCI spec.
The same logic already applied in AtaAtapiPassThruDxe driver.
Acked-by: Abner Chang <abner.chang@amd.com>
=> MdeModulePkg/Bus: Fix port multiplier port in AhciPei PEIM

ShellPkg/Library/UefiShellDebug1CommandsLib/SmbiosView/PrintInfo.c, ShellPkg/Library/UefiShellDebug1CommandsLib/SmbiosView/PrintInfo.h, ShellPkg/Library/UefiShellDebug1CommandsLib/SmbiosView/QueryTable.c, ShellPkg/Library/UefiShellDebug1CommandsLib/SmbiosView/SmbiosViewStrings.uni
The initial version of Smbios Specification 3.6.0
type 45 and type 46 support.
=> ShellPkg/SmbiosView: type 45 and type 46 support.

UnitTestFrameworkPkg/Library/UnitTestPeiServicesTablePointerLib/UnitTestPeiServicesTablePointerLib.c, UnitTestFrameworkPkg/Library/UnitTestPeiServicesTablePointerLib/UnitTestPeiServicesTablePointerLib.h, UnitTestFrameworkPkg/Library/UnitTestPeiServicesTablePointerLib/UnitTestPeiServicesTablePointerLib.inf, UnitTestFrameworkPkg/Library/UnitTestPeiServicesTablePointerLib/UnitTestPeiServicesTablePointerLib.uni, UnitTestFrameworkPkg/Library/UnitTestPeiServicesTablePointerLib/UnitTestPeiServicesTablePointerLibHob.c, UnitTestFrameworkPkg/Library/UnitTestPeiServicesTablePointerLib/UnitTestPeiServicesTablePointerLibMisc.c, UnitTestFrameworkPkg/Library/UnitTestPeiServicesTablePointerLib/UnitTestPeiServicesTablePointerLibPpi.c, UnitTestFrameworkPkg/UnitTestFrameworkPkg.dsc, UnitTestFrameworkPkg/UnitTestFrameworkPkgHost.dsc.inc
This library supports a PeiServicesTablePointerLib implementation that allows code dependent upon PeiServicesTable to operate in an isolated execution environment such as within the context of a host-based unit test framework.
The unit test should initialize the PeiServicesTable database with any required elements (e.g. PPIs, Hob etc.) prior to the services being invoked by code under test.
It is strongly recommended to clean any global databases by using EFI_PEI_SERVICES.ResetSystem2 after every unit test so the tests execute in a predictable manner from a clean state.
=> UnitTestFrameworkPkg： Add UnitTestPeiServicesTablePointerLib

UefiPayloadPkg/Tools/ElfFv.py
Fix incorrect code on AddSectionHeader32() and AddSectionHeader64()
=> UefiPayloadPkg: Fix incorrect code on AddSectionHeader

IntelFsp2WrapperPkg/FspsWrapperPeim/FspsWrapperPeim.c
REF : https://bugzilla.tianocore.org/show_bug.cgi?id=4480
In the FspsWrapperPeim, before calling FspWrapperVariableRequestHandler and FspWrapperMultiPhaseHandler ,FspHobListPtr should be available so that BL will be able to get the correct FspHobListPtr value
Cc: Chen Gang C <gang.c.chen@intel.com>
Reviewed-by: Ashraf Ali S <ashraf.ali.s@intel.com>
=> IntelFsp2WrapperPkg: Get HobListPtr before calling the Multiphase FSPS

OvmfPkg/PciHotPlugInitDxe/PciHotPlugInit.c
Smallest IO window size for PCI bridges is 0x1000.  Fix default size accordingly.  Avoids broken resource assignments like this:
[ ... ]
PciBus: Resource Map for Root Bridge PciRoot(0x0)
Type =   Io16; Base = 0x6000;   Length = 0x7000;        Alignment = 0xFFF
[ ... ]
Base = 0xC000;       Length = 0x200; Alignment = 0xFFF;      Owner = PPB [00|02|00:**]
Base = 0xC200;       Length = 0x40;  Alignment = 0x3F;       Owner = PCI [00|1F|03:20]
Base = 0xC240;       Length = 0x20;  Alignment = 0x1F;       Owner = PCI [00|1F|02:20]
[ ... ]
... which the linux kernel fixes up later:
[    0.644657] pci 0000:00:1f.3: BAR 4: assigned [io  0x1000-0x103f]
[    0.646833] pci 0000:00:1f.2: BAR 4: assigned [io  0x1040-0x105f]
With the patch applied:
{ ... ]
PciBus: Resource Map for Root Bridge …
=> OvmfPkg/PciHotPlugInitDxe: fix io window size

.azurepipelines/templates/defaults.yml
Use the latest Linux container image (from 2023-05-30). It uses Qemu 8.0.0 and gcc 12.
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4324
=> CI: Use latest image for Linux jobs (Qemu 8, gcc 12)

BaseTools/Conf/tools_def.template
gcc-13 for RISC-V enables unwind tables by default similar to ARM64. This generates .eh_frame_hdr section which is not handled well by GenFw causing failures.
Disable the unwind tables by adding -fno-unwind-tables flag similar to [1].
[1] - https://github.com/tianocore/edk2/commit/cbf00651eda6
=> BaseTools/tools_def: Add "-fno-unwind-tables" to GCC5_RISCV64_CC_FLAGS

RedfishPkg/PrivateLibrary/RedfishCrtLib/RedfishCrtLib.inf, RedfishPkg/RedfishLibs.dsc.inc
BaseSortLib is the library instance name not the class name.
Signed-off-by: Mike Maslenkin <mike.maslenkin@gmail.com>
=> RedfishPkg: Fix SortLib library class name typo.

UefiCpuPkg/CpuTimerDxeRiscV64/Timer.c
The timer notify function should be called with timer period, not the value read from timer register.
=> Pull Tuan's timer fix

UefiCpuPkg/PiSmmCpuDxeSmm/PiSmmCpuDxeSmm.c
Some features like RAS need to use processor extended information under smm, So add code to support it
=> UefiCpuPkg: Get processor extended information for SmmCpuServiceProtocol

OvmfPkg/PlatformCI/.azurepipelines/Ubuntu-GCC5.yml
The effect of LTO is limited with optimization turned off, and blocked the upgrade of Openssl3.0. We already skipped this build with VS2019, skip the GCC NOOPT build also.
=> OvmfPkg/PlatformCI: Skip GCC5_OVMF_IA32X64_FULL_NOOPT build

MdeModulePkg/Universal/Variable/RuntimeDxe/TcgMorLockSmm.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4410
Inside TcgMorLockSmm.c, the SetVariableCheckHandlerMorLock() function contains a scenario to prevent a possible dictionary attack on the MorLock Key in accordance with the TCG Platform Reset Mitigation Spec v1.10.
The mechanism to prevent this attack must also change the MorLock Variable Value to 0x01 to indicate Locked Without Key.
ASSERT_EFI_ERROR is added for error visibility since SetMorLockVariable returns a status code
Signed-off-by: Abhi Singh <Abhi.Singh@arm.com>
Acked-by: Michael Kubacki <michael.kubacki@microsoft.com>
=> MdeModulePkg/Variable: TcgMorLockSmm Key Mismatch changes lock state

Maintainers.txt, MdeModulePkg/Bus/Usb/UsbNetwork/NetworkCommon/ComponentName.c, MdeModulePkg/Bus/Usb/UsbNetwork/NetworkCommon/DriverBinding.c, MdeModulePkg/Bus/Usb/UsbNetwork/NetworkCommon/DriverBinding.h, MdeModulePkg/Bus/Usb/UsbNetwork/NetworkCommon/NetworkCommon.inf, MdeModulePkg/Bus/Usb/UsbNetwork/NetworkCommon/PxeFunction.c, MdeModulePkg/Bus/Usb/UsbNetwork/UsbCdcEcm/ComponentName.c, MdeModulePkg/Bus/Usb/UsbNetwork/UsbCdcEcm/UsbCdcEcm.c, MdeModulePkg/Bus/Usb/UsbNetwork/UsbCdcEcm/UsbCdcEcm.h, MdeModulePkg/Bus/Usb/UsbNetwork/UsbCdcEcm/UsbCdcEcm.inf, MdeModulePkg/Bus/Usb/UsbNetwork/UsbCdcEcm/UsbEcmFunction.c, MdeModulePkg/Bus/Usb/UsbNetwork/UsbCdcNcm/ComponentName.c, MdeModulePkg/Bus/Usb/UsbNetwork/UsbCdcNcm/UsbCdcNcm.c, MdeModulePkg/Bus/Usb/UsbNetwork/UsbCdcNcm/UsbCdcNcm.h, MdeModulePkg/Bus/Usb/UsbNetwork/UsbCdcNcm/UsbCdcNcm.inf, MdeModulePkg/Bus/Usb/UsbNetwork/UsbCdcNcm/UsbNcmFunction.c, MdeModulePkg/Bus/Usb/UsbNetwork/UsbRndis/ComponentName.c, MdeModulePkg/Bus/Usb/UsbNetwork/UsbRndis/UsbRndis.c, MdeModulePkg/Bus/Usb/UsbNetwork/UsbRndis/UsbRndis.h, MdeModulePkg/Bus/Usb/UsbNetwork/UsbRndis/UsbRndis.inf, MdeModulePkg/Bus/Usb/UsbNetwork/UsbRndis/UsbRndisFunction.c, MdeModulePkg/Include/Protocol/UsbEthernetProtocol.h, MdeModulePkg/MdeModulePkg.dec, MdeModulePkg/MdeModulePkg.dsc
MdeModulePkg/Bus/Usb/UsbNetwork: Add USB network devices support
UsbNetwork provides network functions for USB ACM, USB NCM,
and USB RNDIS network device.
Signed-off-by: Richard Ho <richardho@ami.com>
Tested-by: Tinh Nguyen <tinhnguyen@os.amperecomputing.com>
Acked-by: Hao A Wu <hao.a.wu@intel.com>
Reviewed-by: Tony Lo <tonylo@ami.com>
=> Add USB Network device support

OvmfPkg/ResetVector/Ia32/Flat32ToFlat64.asm
Commit 63c50d3ff2854a76432b752af4f2a76f33ff1974 changed the check that is used to determine if SEV-ES is active. Originally, a CMP instruction with a supporting JZ instruction was used for the check. It was changed to use the BT instruction but not JZ instruction. The result of a BT instruction changes the the carry flag (CF) and not the zero flag (ZF). As a result, the wrong condition is being checked. Update the JZ to a JNC to properly detect if SEV-ES is active.
Fixes: 63c50d3ff285 ("OvmfPkg/ResetVector: cache the SEV status MSR...")
=> OvmfPkg/ResetVector: Fix assembler bit test flag check

MdeModulePkg/Bus/Pci/EhciDxe/UsbHcMem.c
The function UsbHcGetPciAddressForHostMem has
ASSERT ((Block != NULL));
and the UsbHcFreeMem has
ASSERT (Block != NULL);
statement after for loop, but these are applicable only in DEBUG mode. In RELEASE mode, if for whatever reasons there is no match inside the for loop and the loop exits because of Block != NULL; condition, then there is no "Block" NULL pointer check afterwards and the code proceeds to do dereferencing "Block" which will lead to CRASH.
Hence, for safety add NULL pointer checks always.
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4210
=> MdeModulePkg/Bus/Pci/EhciDxe: Fix FORWARD_NULL Coverity issues

OvmfPkg/Library/PeilessStartupLib/PeilessStartup.c, OvmfPkg/Library/PeilessStartupLib/PeilessStartupLib.inf
SECURE_BOOT_FEATURE_ENABLED was dropped by the commit(92da8a154f), but the PeilessStartupLib was not updated with PcdSecureBootSupported, that made SecureBoot no longer work in IntelTdxX64.
Fix this by replacing SECURE_BOOT_FEATURE_ENABLED with PcdSecureBootSupported in PeilessStartupLib.
=> OvmfPkg/PeilessStartupLib: Updated with PcdSecureBootSupported

UefiCpuPkg/Library/MmSaveStateLib/AmdMmSaveState.c, UefiCpuPkg/Library/MmSaveStateLib/AmdMmSaveStateLib.inf, UefiCpuPkg/Library/MmSaveStateLib/IntelMmSaveState.c, UefiCpuPkg/Library/MmSaveStateLib/IntelMmSaveStateLib.inf, UefiCpuPkg/Library/MmSaveStateLib/MmSaveState.h, UefiCpuPkg/Library/MmSaveStateLib/MmSaveStateCommon.c
BZ: https://bugzilla.tianocore.org/show_bug.cgi?id=4182
Use gMmst instead of gSmst.
Replace SmmServicesTableLib with MmServicesTableLib.
Acked-by: Abner Chang <abner.chang@amd.com>
=> UefiCpuPkg: Uses gMmst in MmSaveStateLib

Maintainers.txt
Add Jianyong Wu and Anatol Belski as co-reviewer for OvmfPkg/CloudHv to replace Sebastien Boeuf.
=> OvmfPkg/CloudHv: update Maintainers.txt entry

NetworkPkg/HttpDxe/HttpDriver.c
When failure happens in HttpDxeStart, the error handling code release the memory buffer but it does not uninstall HTTP service binding protocol. As the result, application can still locate this protocol and invoke service binding functions in released memory pool.
Reviewed-by: Saloni Kasbekar <saloni.kasbekar@intel.com>
=> NetworkPkg/HttpDxe: fix driver binding start issue.

EmulatorPkg/Win/Host/WinInclude.h, MdePkg/Include/IndustryStandard/PeImage.h
Remove RUNTIME_FUNCTION redefinition error workaround from
the following commit to the MdePkg that only impacts EmulatorPkg
builds that uses windows include files:
https://github.com/tianocore/edk2/commit/ff52068d9261b9391d75b83a2a4e40e040f3b6eb
The correct location for this fix is in the EmulatorPkg
in the WinInclude.h file that addresses all the name
collisions between edk2 types and windows types.
Cc: Gerd Hoffmann <[kraxel@redhat.com](mailto:kraxel@redhat.com)>
Cc: Rebecca Cran <[rebecca@bsdio.com](mailto:rebecca@bsdio.com)>
Cc: Liming Gao <[gaoliming@byosoft.com.cn](mailto:gaoliming@byosoft.com.cn)>
Cc: Zhiguang Liu <[zhiguang.liu@intel.com](mailto:zhiguang.liu@intel.com)>
Cc: Andrew Fish <[afish@apple.com](mailto:afish@apple.com)>
Cc: Ray Ni …
=> Move RUNTIME_FUNCTION redefinition fix to EmulatorPkg

RedfishPkg/Include/Library/RedfishDebugLib.h, RedfishPkg/Library/RedfishDebugLib/RedfishDebugLib.c, RedfishPkg/RedfishDiscoverDxe/RedfishDiscoverDxe.c, RedfishPkg/RedfishDiscoverDxe/RedfishDiscoverDxe.inf, RedfishPkg/RedfishDiscoverDxe/RedfishDiscoverInternal.h
Add NTOHL() for coverting IP address from EFI_IPv4_ADDRESS to IP4_ADDR so that IP4_IS_VALID_NETMASK() return correct value.
=> RedfishPkg/RedfishDiscoverDxe: fix netmask check issue

MdeModulePkg/Bus/Ata/AtaAtapiPassThru/AtaAtapiPassThru.c, MdeModulePkg/Bus/Ata/AtaAtapiPassThru/IdeMode.c
**Patch series sent at:**
https://edk2.groups.io/g/devel/message/106988
https://edk2.groups.io/g/devel/message/106989
https://edk2.groups.io/g/devel/message/106990
v3 -> v4:
- [Patch 2] Further update as per review comments
- Status storage removal at call point
- Error checks moved inside SetDriveParameters function 
v2 -> v3:
- [Patch 2] Update as per review comments
v1 -> v2:
- Retain outer cast
- Add error check instead of Status storage removal
Ranbir Singh (2):
MdeModulePkg/Bus/Ata/AtaAtapiPassThru: Fix SIGN_EXTENSION Coverity
issue
MdeModulePkg/Bus/Ata/AtaAtapiPassThru: Fix UNUSED_VALUE Coverity issue
MdeModulePkg/Bus/Ata/AtaAtapiPassThru/AtaAtapiPassThru.c |  2 +-
MdeModulePkg/Bus/Ata/AtaAtapiPassThru/IdeMode.c          | 12 ++++++++++--
2 files changed, 11 …
=> Push ataatapipassthru coverity

BaseTools/Scripts/BinToPcd.py
Removes the dependency on xdrlib and replaces it with custom logic to pack a per the xdr requirements. Necessary as xdrlib is being deprecated in python 3.13.
=> BaseTools: BinToPcd: Resolve xdrlib deprecation

BaseTools/Edk2ToolsBuild.py
Adds edk2_logging.scan_compiler_output() to Edk2ToolsBuild.py to catch some compilation errors and log them as an error.
Signed-off-by: Joey Vagedes <joeyvagedes@gmail.com>
=> BaseTools: scan Edk2ToolsBuild.py make output

MdePkg/Include/IndustryStandard/PciExpress40.h
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=4515
Add PCI_EXPRESS_EXTENDED_CAPABILITY_DESIGNATED_VENDOR_SPECIFIC_ID 0x0023 in PciExpress40.h
=> MedPkg/Include: Add PCI_EXPRESS_EXTENDED_CAPABILITY_DVSEC_ID

OvmfPkg/Bhyve/PlatformPei/Platform.c, OvmfPkg/Bhyve/PlatformPei/PlatformPei.inf
Copy the function BuildPlatformInfoHob() from OvmfPkg/PlatformPei.
QemuFwCfgLib expect this HOB to be present, or fails to do anything. InternalQemuFwCfgIsAvailable() from QemuFwCfgPeiLib module will not check if the HOB is actually present for example and try to use a NULL pointer.
Fixes: cda98df16228970dcf9a4ce2af5368219711b4b0 ("OvmfPkg/QemuFwCfgLib: remove mQemuFwCfgSupported + mQemuFwCfgDmaSupported")
=> OvmfPkg/Bhyve: build platform info HOB

MdeModulePkg/Core/Dxe/Mem/HeapGuard.c, MdeModulePkg/Core/Dxe/Mem/HeapGuard.h, MdeModulePkg/Core/Dxe/Mem/Pool.c
Currently, HeapGuard, when in the GuardAlignedToTail mode, assumes that the pool head has been allocated in the first page of memory that was allocated. This is not the case for ARM64 platforms when allocating runtime pools, as RUNTIME_PAGE_ALLOCATION_GRANULARITY is 64k, unlike X64, which has RUNTIME_PAGE_ALLOCATION_GRANULARITY as 4k.
When a runtime pool is allocated on ARM64, the minimum number of pages allocated is 16, to match the runtime granularity. When a small pool is allocated and GuardAlignedToTail is true, HeapGuard instructs the pool head to be placed as (MemoryAllocated + EFI_PAGES_TO_SIZE(Number of Pages)
- SizeRequiredForPool).
This gives this scenario:
|Head Guard|Large Free Number of Pages|PoolHead|TailGuard|
When this pool goes to be freed, HeapGuard instructs the pool …
=> MdeModulePkg: HeapGuard: Don't Assume Pool Head Allocated In First Page

IntelFsp2Pkg/Include/Library/FspCommonLib.h, IntelFsp2Pkg/Library/BaseFspCommonLib/FspCommonLib.c
FSP-SMM module need get and set FspSmmInit upd data pointer functions to get and set upd settings.
Reviewed-by: S Ashraf Ali <ashraf.ali.s@intel.com>
=> IntelFsp2Pkg: Add get and set FspSmmInit upd data pointer functions

RedfishPkg/RedfishPlatformConfigDxe/RedfishPlatformConfigImpl.c
This fixes an unused variable 'Index' error in release build.
=> RedfishPkg/RedfishPlatformConfigDxe: Fix unused variable

OvmfPkg/IntelTdx/IntelTdxX64.dsc, OvmfPkg/Microvm/MicrovmX64.dsc, OvmfPkg/OvmfXen.dsc
OvmfPkg: Disable PcdFirstTimeWakeUpAPsBySipi.
Disable PcdFirstTimeWakeUpAPsBySipi for IntelTdx, Microvm, and Xen to
preserve the original execution of INIT-SIPI-SIPI.
Signed-off-by: Yuanhao Xie <yuanhao.xie@intel.com>
=> OvmfPkg: Disable PcdFirstTimeWakeUpAPsBySipi.

BaseTools/Conf/tools_def.template
The CLANGDWARF profile sets both -Wno-tautological-compare and -Wno-tautological-constant-out-of-range-compare, but this prevents compile-time detection of certain errors.
Drop these flags.
=> BaseTools: drop tautological warning overrides for CLANGDWARF

SecurityPkg/Library/Tpm2DeviceLibTcg2/Tpm2DeviceLibTcg2.c
The global variable has a common name that can conflict with other TCG modules. For example, Tcg2Dxe has a similarly named global that is of type EFI_TCG2_PROTOCOL instead of EFI_TCG2_PROTOCOL*.
=> SecurityPkg/Tpm2DeviceLibTcg2: Make mTcg2Protocol static

MdeModulePkg/Bus/Pci/PciBusDxe/PciOptionRomSupport.c
A faulty PCI device has the Option ROM image size set to 0. UEFI reads two headers PCI_EXPANSION_ROM_HEADER and PCI_DATA_STRUCTURE to get the Option ROM information. Because the image size is 0, the Option ROM header address never changes. As a result, UEFI keeps reading the same two headers definitely. This patch is intended to fix it.
=> MdeModulePkg/PciBusDxe: Fix boot hang with faulty PCI Option ROM

ShellPkg/Library/UefiShellDebug1CommandsLib/SmbiosView/PrintInfo.c
This updates the system slot ID up to SlotTypePCIExpressGen6andBeyond (0xC4) added by updating type 9 with SMBIOS version 3.5 to cover modern PCIe Gens.
=> ShellPkg/SmbiosView: Update display of PCIe system slot ID

MdeModulePkg/Library/DxeCorePerformanceLib/DxeCorePerformanceLib.c
Fix smm perf issue in DxeCorePerformanceLib. In
current code logic, total SMM perf record is copied multiple times to FPDT table if multiple ReadyToBoot events are signaled. This patch changes the function InternalGetSmmPerfData() to only get newly generated Smm perf data. Then previous generated Smm perf data won't be copied to FPDT again.
BZ: https://bugzilla.tianocore.org/show_bug.cgi?id=4470
=> MdeModulePkg/DxeCorePerformanceLib:fix smm perf issue

ArmPkg/Universal/Smbios/SmbiosMiscDxe/Type00/MiscBiosVendorFunction.c
The top two bits of the Extended BIOS ROM Size field indicates the unit used for the remaining 14 bits. If the size is greater than 16GB, the unit is gigabytes.
The test for this uses the local BiosPhysicalSize variable, which is a UINTN, meaning that when building for ARM/CLANGDWARF we have a tautological constant comparison, which the toolchain flags now we've stopped disabling that warning.
So switch the BiosPhysicalSize variable to UINT64.
=> ArmPkg/SmbiosMiscDxe: use UINT64 for BiosPhysicalSize

MdeModulePkg/Core/Dxe/Hand/Locate.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4543
REF: https://uefi.org/specs/UEFI/2.10/07_Services_Boot_Services.html#efi-boot-services-locatehandlebuffer
CoreLocateHandleBuffer() can in certain cases, return an error and not free an allocated buffer. This scenario occurs if the first call to InternalCoreLocateHandle() returns success and the second call returns an error.
On a successful return, LocateHandleBuffer() passes ownership of the buffer to the caller. However, the UEFI specification is not explicit about what the expected ownership of this buffer is in the case of an error. However, it is heavily implied by the code example given in section 7.3.15 of v2.10 of the UEFI specificaton that if LocateHandleBuffer() returns a non-successful status code then the ownership of the …
=> MdeModulePkg: Fix memory leak in LocateHandleBuffer()

OvmfPkg/IoMmuDxe/IoMmuBuffer.c, OvmfPkg/IoMmuDxe/IoMmuDxe.inf
Instead of relying on raising the TPL to protect the critical sections that manipulate the global bitmask that keeps track of bounce buffer allocations, use compare-and-exchange to manage the global variable, and tweak the logic to line up with that.
Given that IoMmuDxe implements a singleton protocol that is shared between multiple drivers, and considering the elaborate and confusing requirements in the UEFP spec regarding TPL levels at which protocol methods may be invoked, not relying on TPL levels at all is a more robust approach in this case.
Link: https://bugzilla.redhat.com/show_bug.cgi?id=2211060
Acked-by: Pedro Falcato <pedro.falcato@gmail.com>
=> OvmfPkg/IoMmuDxe: don't rely on TPLs to manage concurrency

OvmfPkg/AmdSev/AmdSevX64.dsc
PcdFirstTimeWakeUpAPsBySipi was recently introduced to indicate when the full INIT-SIPI-SIPI sequence can be skipped for AP bringup. It is true by default, but needs to be disabled for QEMU/OVMF where early INIT is not simulated. Commit 1d76560146 ("OvmfPkg: Disable PcdFirstTimeWakeUpAPsBySipi.") added changes to disable it by default for OvmfPkg, but a similar change was not made for the AmdSev package. This breaks booting of SEV and SNP guests.
Fix this defaulting PcdFirstTimeWakeUpAPsBySipi to false for AmdSev package, as was previously done for OvmfPkg variants.
Fixes: eaffa1d7ff ("UefiCpuPkg:Wake up APs after power-up or RESET through SIPI.")
=> OvmfPkg/AmdSev: Disable PcdFirstTimeWakeUpAPsBySipti

OvmfPkg/PlatformDxe/Platform.c
The Hii form is named "MainFormState" while the EFI variable is named "PlatformConfig".  This discrepancy in names causes the following SCT cases to fail on RiscVVirtQemu:
ExtractConfigConformance
ExtractConfigFunction
ExtractConfig_Func
Previous commit 16acacf addressed two of these issues, and this patch fixes the remaining one.
=> OvmfPkg: Fix Hii form name mismatch with EFI variable

ArmVirtPkg/PlatformCI/PlatformBuildLib.py
Currently, unlike OVMF, ArmVirtQemu does not display any graphics, only the QEMU monitor. Graphics are helpful to confirm booting into an OS is successful, interacting with the EFI shell while getting separate logging messages, etc.
This patch adds the QEMU parameters to launch a graphical window and add a USB keyboard and mouse, which is modeled as a tablet as it tracks better in QEMU than a generic mouse. virtio-gpu-pci is chosen as the graphics device as it is recommended by QEMU for the ARM virtual platform.
The graphics and USB input devices will only be added to QEMU when QEMU_HEADLESS == FALSE, so CI builds will not attempt to use the graphics and if a user does not want graphics, they can add QEMU_HEADLESS=TRUE to the build cmdline.
=> ArmVirtPkg: ArmVirtQemu: Add Graphics and Input

CryptoPkg/Library/BaseCryptLib/Pk/CryptTs.c, SecurityPkg/Library/AuthVariableLib/AuthService.c, SecurityPkg/Library/AuthVariableLib/AuthServiceInternal.h, SecurityPkg/Library/AuthVariableLib/AuthVariableLib.c, SecurityPkg/Library/DxeImageVerificationLib/DxeImageVerificationLib.c, SecurityPkg/VariableAuthenticated/SecureBootConfigDxe/SecureBootConfigDxe.inf, SecurityPkg/VariableAuthenticated/SecureBootConfigDxe/SecureBootConfigImpl.c, SecurityPkg/VariableAuthenticated/SecureBootConfigDxe/SecureBootConfigImpl.h, SecurityPkg/VariableAuthenticated/SecureBootConfigDxe/SecureBootConfigStrings.uni
Patch V9:
Refine coding format for file AuthService.c
Patch V8:
Update the patch comments for CryptoPkg.
Comment should be <76 characters in each line.
Refine coding format.
Patch V7:
Drop raw RSA3072 and RSA4096. Only use gEfiCertX509Guid for RSA3072 and RSA4096
Do the positive tests and the negative tests below. And got all the expected results.
Patch V6:
Remove the changes in MdePkg.
The changes of patch v6 are in CryptoPkg and SecurityPkg.
Set signature type to gEfiCertX509Guid when enroll RSA3072/RSA4096 KEK.
This signature type is used to check the supported signature and show the strings.
Patch V5:
Using define KEY_TYPE_RSASSA to replace the magic number.
Patch V4:
Determine the RSA algorithm by a supported algorithm list.
Patch V3:
Select SHA algorithm automaticly for a unsigned …
=> Support RSA4096 and RSA3072

MdePkg/Library/BaseRngLib/BaseRngLibInternals.h
The include guard is incomplete and does not define the macro.
Reviewed-by: Rebecca Cran <rebecca@os.amperecomputing.com>
=> MdePkg/Library/BaseRngLib: Fix include guard

SecurityPkg/RandomNumberGenerator/RngDxe/AArch64/AArch64Algo.c, SecurityPkg/RandomNumberGenerator/RngDxe/Arm/ArmAlgo.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?idD91
mAvailableAlgoArray is currently allocated for "RNG_AVAILABLE_ALGO_MAX" number of bytes, whereas it was dereferenced as "EFI_RNG_ALGORITHM".
This change fixed the buffer allocation logic by allocating a proper size of buffer before referencing.
=> SecurityPkg: RngDxe: Fixing mAvailableAlgoArray allocator

MdePkg/Library/TdxLib/Rtmr.c
Removes the comparison since unsigned values are always greater than or equal to 0.
See the following CodeQL query for more info:
/cpp/cpp-unsigned-comparison-zero/
=> MdePkg/Library/TdxLib: Remove unnecessary comparison

ShellPkg/Library/UefiShellNetwork2CommandsLib/Ifconfig6.c
Moves the range check for the index into the array before attempting
any accesses using the array index.
=> ShellPkg/UefiShellNetwork2CommandsLib: Check array index before access

.editorconfig
Add a .editorconfig file which editors can use for basic formatting details of files, such as tabs/spaces, line endings etc.
=> Add a .editorconfig file to tell editors basic formatting details

MdePkg/Include/IndustryStandard/SmBios.h
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4547
Add New Intel Processor family for SMBIOS Type 4
Hex value - 16h
Name - Intel(R) Processor
Cc: Benny Lin <benny.lin@intel.com>
Cc: Prakashan Krishnadas Veliyathuparambil <krishnadas.veliyathuparambil.prakashan@intel.com>
=> MdePkg/SmBios.h: Add New Intel Processor family

MdeModulePkg/Universal/HiiDatabaseDxe/ConfigKeywordHandler.c
The immediately preceding call, GetBestLanguage, plus the implementation of HiiGetString, which is called immediately afterwards, make it clear that BestLanguage is a null-terminated ASCII string, and not just a five byte, non-null terminated buffer.
Therefore AsciiStrLen is one byte too short, meaning that whether the space allocated is really sufficient and whether the resultant string is really null-terminated becomes implementation-dependent. Rather than switching to AsciiStrSize, we use an explicitly compile-time string length calculation (both compile-time and run-time approaches are currently used elsewhere in the codebase for copying static strings).
=> MdeModulePkg/HiiDatabase: Fix incorrect AllocateCopyPool size

MdeModulePkg/Library/BootMaintenanceManagerUiLib/UpdatePage.c
Many arrays are defined with a length of MAX_MENU_NUMBER in
FormGuid.h. Two of those are BootOptionOrder and DriverOptionOrder.
In UpdatePage.c, a pointer is set to either of those arrays. The
array buffer is accessed using an index whose range is checked after
the pointer to the array is dereferenced. This change moves the check
before the dereference.
In another place in the file, the ConsoleCheck pointer is also set to
an array buffer with MAX_MENU_NUMBER elements. Only an ASSERT()
currently checks the range of the array index. This change
conditionalizes the pointer dereference itself on the range of Index.
Signed-off-by: Michael …
=> MdeModulePkg/BootMaintenanceManagerUiLib: Check array index before access

OvmfPkg/RiscVVirt/README.md
Explain how users can compose their pre-OS environment purely from binaries they've built themselves.
Cc: Sunil V L <sunilvl@ventanamicro.com>
=> OvmfPkg/RiscVVirt/README.md: bring your own OpenSBI

ArmPkg/Include/Library/ArmLib.h, ArmPkg/Library/ArmMmuLib/Arm/ArmMmuLibCore.c
Jake reports that the IS_ARM_MEMORY_REGION_ATTRIBUTES_SECURE() macro is no longer accurate since commit 852227a9d52e3cb9 ("ArmPkg/Mmu: Remove handling of NONSECURE memory regions").
Fortunately, it only affects the NS bit in level 1 short descriptors, which is ignored when executing in non-secure mode. And given that running UEFI in the secure world is not a use case we aim to support, let's just drop this logic altogether.
Reported-by: Jake Garver <jake@nvidia.com>
=> ArmPkg/ArmMmuLib: Drop buggy secure memory type check

OvmfPkg/TdxDxe/TdxAcpiTable.c
BZ: https://bugzilla.tianocore.org/show_bug.cgi?id=4527
According to ACPI 6.5 (https://uefi.org/specs/ACPI/6.5/05_ACPI_Software _Programming_Model.html?highlight=mailboxversion#multiprocessor-wakeup- structure) the MailBoxVersion is 0.
This patch changed MadtMpWk->MailBoxVersion from 1 to 0 to fix the error.
=> OvmfPkg/TdxDxe: Change MadtMpWk->MailBoxVersion from 1 to 0

RedfishPkg/RedfishPlatformConfigDxe/RedfishPlatformConfigDxe.c
StatementValue->Buffer is converted from ASCII to Unicode by caller already so we don't have to convert it again.
=> RedfishPkg/RedfishPlatformConfigDxe: fix can not set one-of option issue

OvmfPkg/RiscVVirt/README.md
Original posting: `[PATCH 0/3] updates for "OvmfPkg/RiscVVirt/README.md"`
http://mid.mail-archive.com/20230913105551.12680-1-lersek@redhat.com
https://edk2.groups.io/g/devel/message/108575
https://listman.redhat.com/archives/edk2-devel-archive/2023-September/067875.html
This v2 has never been posted to the list, but it only incorporates a small fix, addressing Drew's comment under patch#1. The change is noted in the commit message of patch#1. The interdiff is:
~~~
1:  f99c0f999a47 ! 1:  4c8053b787ca OvmfPkg/RiscVVirt/README: explain that "-bios" is only useful with TCG
@@ Commit message
Cc: Sunil V L <sunilvl@ventanamicro.com>
+    [lersek@redhat.com: '-bios' is rejected with KVM accel (Drew)]
+ …
=> [PATCH v2 0/3] updates for "OvmfPkg/RiscVVirt/README.md" -- push

MdeModulePkg/Core/Dxe/Mem/Page.c
When finding a free page range for allocation, if the found range
starts below the tracked memory bin address range, the lowest
memory bin address is updated which will not include the guard page if
present. When CoreConvertPagesWithGuard() is called on the range
being allocated, the memory range is adjusted to include guard
pages which can push it out of the memory bin address range and
cause the memory type statistics to be unaltered.
This patch updates the lowest memory bin address range to account for
the guard page if NeedGuard is TRUE so the memory type statistics
are updated correctly.
Signed-off-by: Taylor Beebe <t@taylorbeebe.com>
Reviewed-by: Liming Gao …
=> MdeModulePkg: Memory Bin Range Update Accounts for Guard Page

ArmVirtPkg/ArmVirtPkg.ci.yaml, BaseTools/Plugin/DebugMacroCheck/BuildPlugin/DebugMacroCheckBuildPlugin.py, BaseTools/Plugin/DebugMacroCheck/BuildPlugin/DebugMacroCheck_plug_in.yaml, BaseTools/Plugin/DebugMacroCheck/DebugMacroCheck.py, BaseTools/Plugin/DebugMacroCheck/Readme.md, BaseTools/Plugin/DebugMacroCheck/tests/DebugMacroDataSet.py, BaseTools/Plugin/DebugMacroCheck/tests/MacroTest.py, BaseTools/Plugin/DebugMacroCheck/tests/test_DebugMacroCheck.py, DynamicTablesPkg/DynamicTablesPkg.ci.yaml, OvmfPkg/PlatformCI/PlatformBuildLib.py, RedfishPkg/Library/PlatformHostInterfaceBmcUsbNicLib/PlatformHostInterfaceBmcUsbNicLib.c, SecurityPkg/SecurityPkg.ci.yaml, pip-requirements.txt
Adds a plugin that finds debug macro formatting issues. These errors
often creep into debug prints in error conditions not frequently
executed and make debug more difficult when they are encountered.
The code can be as a standalone script which is useful to find
problems in a large codebase that has not been checked before or as
a CI plugin that notifies a developer of an error right away.
The script was already used to find numerous issues in edk2 in the
past so there's not many code fixes in this change. More details
are available in the readme file:
BaseTools/Plugin/DebugMacroCheck/Readme.md
Standalone Mode (`DebugMacroCheck.py`)
Build Plugin Mode (pre-build)
Unit Tests on Command Line
Unit Tests in VS Code Test Explorer
Unit Tests in VS Code Test Explorer (with intentional failure) …
=> BaseTools/Plugin: Add DebugMacroCheck

MdePkg/Include/Protocol/RestEx.h, RedfishPkg/RedfishRestExDxe/RedfishRestExProtocol.c
Return unsupported HTTP status code to caller so caller can handle HTTP error status code. Current implementation only return EFI error to caller. Without knowing the HTTP status code, caller has trouble to handle HTTP request failure.
=> RedfishPkg/RedfishRestExDxe: return HTTP status code to caller.

ArmPkg/ArmPkg.dec, ArmVirtPkg/ArmVirtCloudHv.dsc, ArmVirtPkg/ArmVirtKvmTool.dsc, ArmVirtPkg/ArmVirtQemu.dsc, ArmVirtPkg/ArmVirtQemuKernel.dsc, ArmVirtPkg/ArmVirtXen.dsc, ArmVirtPkg/Library/ArmVirtTimerFdtClientLib/ArmVirtTimerFdtClientLib.c, ArmVirtPkg/Library/ArmVirtTimerFdtClientLib/ArmVirtTimerFdtClientLib.inf
An ASSERT trips when we try to add the NS-EL2 virtual timer to qemu
mach-virt.
Add a new Pcd for the new private peripheral interrupt id,
PcdArmArchTimerHypVirtIntrNum. 
Update ArmVirtTimerFdtClientLib to:
- Only assert on receiving less information that required through DT.
- Set PcdArmArchTimerHypVirtIntrNum if provided through DT.
Reported-by: Peter Maydell <peter.maydell@linaro.org>
=> ArmPkg/ArmVirtPkg: handle FEAT_VHE NS-EL2 virtual timer

MdeModulePkg/Bus/Ata/AtaBusDxe/AtaPassThruExecute.c
Line number 365 does contain a typecast with UINT32, but it is after all the operations (16-bit left shift followed by OR'ing) are over. To avoid any SIGN_EXTENSION, typecast the intermediate result after 16-bit left shift operation immediately with UINT32.
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4209
=> MdeModulePkg/Bus/Ata/AtaBusDxe: Fix SIGN_EXTENSION Coverity issue

MdeModulePkg/Bus/Pci/NvmExpressPei/NvmExpressPeiS3.c
The code can reach line 65 only through the else path above at line 53. The else path already has the same NULL check at line 55 and hence the duplicate code lines are totally redundant which can be deleted.
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4220
=> MdeModulePkg/Bus/Pci/NvmExpressPei: Fix DEADCODE Coverity issue

MdePkg/Library/BaseLib/RiscV64/RiscVSetJumpLongJump.S
InternalLongJump was not returning the 2nd parameter passed to LongJmp (Value) as the return value from SetJmp.
Seen with code compiled with -Os, where an LongJmp (Buffer, -1) somehow translated to SetJmp returning 0...
Cc: Yong Li <yong.li@intel.com>
Cc: Sunil V L <sunilvl@ventanamicro.com>
Cc: Tuan Phan <tphan@ventanamicro.com>
Cc: Daniel Schaefer <git@danielschaefer.me>
=> Pull: RISCV: Fix InternalLongJump to return correct value

RedfishPkg/Library/JsonLib/JsonLib.c, RedfishPkg/Library/JsonLib/JsonLib.inf
JsonObjectGetValue() cannot find corresponding JSON value when the EDKII_JSON_VALUE object is created by another UEFI driver. This is because "hashtable_seed" is initialized by current time while JsonLib is loaded. So, "hashtable_seed" will be different in each individual UEFI driver.
=> RedfishPkg/JsonLib: fix JsonObjectGetValue issue

MdeModulePkg/Bus/Pci/UhciDxe/UhciSched.c, MdeModulePkg/Bus/Pci/UhciDxe/UsbHcMem.c
**Patch series sent at:**
https://edk2.groups.io/g/devel/message/107788 - [PATCH v2 0/2] MdeModulePkg/Bus/Pci/UhciDxe: Fix issues pointed by Coverity
https://edk2.groups.io/g/devel/message/107789 - [PATCH v2 1/2] MdeModulePkg/Bus/Pci/UhciDxe: Fix BAD_SHIFT Coverity issue
https://edk2.groups.io/g/devel/message/107790 - [PATCH v2 2/2] MdeModulePkg/Bus/Pci/UhciDxe: Fix FORWARD_NULL Coverity issues
v1 -> v2:
Update patch wrt BAD_SHIFT changes as per review comments
Ranbir Singh (2):
MdeModulePkg/Bus/Pci/UhciDxe: Fix BAD_SHIFT Coverity issue
MdeModulePkg/Bus/Pci/UhciDxe: Fix FORWARD_NULL Coverity issues
MdeModulePkg/Bus/Pci/UhciDxe/UhciSched.c | 10 +++++++++-
MdeModulePkg/Bus/Pci/UhciDxe/UsbHcMem.c | 9 +++++++++
2 files changed, 18 insertions(+), 1 deletion(-)
=> Push uhcidxe coverity issues

MdeModulePkg/Bus/Pci/XhciDxe/Xhci.c, MdeModulePkg/Bus/Pci/XhciDxe/Xhci.h, MdeModulePkg/Bus/Pci/XhciDxe/XhciDxe.inf, MdeModulePkg/Bus/Pci/XhciDxe/XhciReg.c, MdeModulePkg/Bus/Pci/XhciDxe/XhciSched.c
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=2948
XhciDxe uses the timer functionality provided by the boot services table to detect timeout conditions. This breaks the driver's ExitBootServices call back, as CoreExitBootServices halts the timer before signaling the ExitBootServices event. If the host controller fails to halt in the call back, the timeout condition will never occur and the boot gets stuck in an indefinite spin loop. Use the free running timer provided by
TimerLib to calculate timeouts, avoiding the potential hang.
=> MdeModulePkg/XhciDxe: Use Performance Timer for XHCI Timeouts

MdeModulePkg/Bus/Pci/XhciDxe/XhciSched.c
https://bugzilla.tianocore.org/show_bug.cgi?id=4552
Following XHCI spec 4.6.1.2, software may abort the execution of Address Device Command when command failed due to timeout.
Cc: Hao A Wu     <hao.a.wu@intel.com>
Cc: Ray Ni       <ray.ni@intel.com>
Cc: Jian J Wang  <jian.j.wang@intel.com>
Cc: Liming Gao   <gaoliming@byosoft.com.cn>
Cc: More Shih    <more.shih@intel.com>
Cc: Jenny Huang  <jenny.huang@intel.com>
=> MdeModulePkg/XhciDxe: Abort the Address Device cmd when time out

BaseTools/Source/C/GenFw/Elf64Convert.c, BaseTools/Source/C/GenFw/elf_common.h
Correct relax id from 99 to 100 and added relocation support up to 109
fix gcc14 adds new relocation, and the generated relocation causes the build and compilation to fail.
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4559
Reviewed-by: Chao Li <lichao@loongson.cn>
=> BaseTools/GenFw: Add support for LOONGARCH64 relax relocation

EmulatorPkg/Unix/Host/EmuThunk.c, EmulatorPkg/Win/Host/WinThunk.c
After running EmulatorPkg, one will notice that their terminal acts strangely. This is caused by the EmulatorPkg Host changing the terminal mode and not restoring the original mode, which is now fixed.
=> EmulatorPkg: Fix Terminal Issues

MdeModulePkg/Bus/Pci/XhciDxe/UsbHcMem.c, MdeModulePkg/Bus/Pci/XhciDxe/UsbHcMem.h, MdeModulePkg/Bus/Pci/XhciDxe/XhciSched.c, MdeModulePkg/Bus/Pci/XhciPei/UsbHcMem.c, MdeModulePkg/Bus/Pci/XhciPei/UsbHcMem.h, MdeModulePkg/Bus/Pci/XhciPei/XhciSched.c
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=4560
TRB Template is 16 bytes. When boundary checking is 64 bytes for xHCI device/host memory address, it may exceed xHCI host memory pool and cause unwanted DXE_ASSERT. Introduce a new input parameter to indicate whether to enforce 64byte size alignment and round up. For TRB case, should set it to FALSE to skip the size round up.
=> MdeModulePkg/Xhci: Skip size round up for TRB during address translation

Maintainers.txt
We added Sami as a reviewer to ArmPkg early last year, and I think it was always our intention to have him as a reviewer of Arm architectural stuff in general, but we seem to have missed out the Arm/AArch64 subdir wildcards. So let's fix that.
=> Maintainers.txt: add Sami as maintainer of arm-architectural subdirs

MdePkg/Library/BaseLib/AArch64/SetJumpLongJump.S, MdePkg/Library/BaseLib/AArch64/SetJumpLongJump.asm, MdePkg/Library/BaseLib/Arm/SetJumpLongJump.S, MdePkg/Library/BaseLib/Arm/SetJumpLongJump.asm
Back in the mists of time (January 2020) I submitted a set to clean up                                                                           
and fix a few bugs in ARM/AArch64 BaseLib SetJump/LongJump implementations:                                                                      
https://edk2.groups.io/g/devel/message/65812                                                                                                     
Then hubris struck and I meant to refactor the code for all architectures,                                                                       
and since this was in my first week in a new job, that meant everything                                                                          
got completely dropped on the floor. …
=> MdePkg: various fixes to ARM/AArch64 SetJump/LongJump 

MdePkg/Library/BaseLib/Arm/SetJumpLongJump.asm
RO -> R0
Reported-by: Philippe Mathieu-Daudé <philmd@linaro.org>
=> MdePkg/BaseLib: fix typo in Arm SetJump

MdePkg/Library/DxeRngLib/DxeRngLib.inf
Add missing GUID declaration in DxeRngLib.inf.
Fixes: bd1f0eecc1df ("MdePkg/DxeRngLib: Request raw algorithm instead of default")
Tested-by: Leif Lindholm <quic_llindhol@quicinc.com>
=> MdePkg/DxeRngLib: Add missing GUID declaration in inf

.azurepipelines/Ubuntu-PatchCheck.yml, .azurepipelines/templates/defaults.yml, .github/workflows/codeql-analysis.yml
Python 3.12 released recently. The Python version is currently
specified to allow updates to newer minor versions. Time is
needed to adjust scripts for Python 3.12 so this series fixes
the Python version to 3.11.
Some places that were already fixed but need the version updated
to 3.11 for consistency are updated as well.
=> Fix Python Minor Version

ArmVirtPkg/Library/FdtPL011SerialPortLib/FdtPL011SerialPortLib.c, ArmVirtPkg/Library/FdtPL011SerialPortLib/FdtPL011SerialPortLib.inf
FdtPL011SerialPortLib claims that it's usable from the DXE_CORE. That's not correct: the DXE_CORE calls DEBUG() and ASSERT() before it calls ProcessLibraryConstructorList(). Via the BaseDebugLibSerialPort instance, those DEBUG() and ASSERT() calls result in SerialPortWrite() calls, before ProcessLibraryConstructorList() called either our constructor FdtPL011SerialPortLibInitialize(), or BaseDebugLibSerialPortConstructor().
(And even if the DXE_CORE called the latter function early enough, it would just invoke our SerialPortInitialize() function -- which does nothing.)
This means that the earliest DXE_CORE debug messages are lost.
Rename FdtPL011SerialPortLibInitialize() to SerialPortInitialize(), so that the same initialization occur through the constructor and the public …
=> ArmVirtPkg/FdtPL011SerialPortLib: initialize implicitly

CryptoPkg/Library/TlsLib/TlsConfig.c
https://bugzilla.tianocore.org/show_bug.cgi?id=2541
https://edk2.groups.io/g/devel/message/109312
https://listman.redhat.com/archives/edk2-devel-archive/2023-October/068612.html
http://mid.mail-archive.com/20231004092003.3809321-1-kraxel@redhat.com
~~~
CryptoPkg/TlsLib: fix tls cipher configuration
Trying to configure the TLS ciphers can lead to TLS handshake failures
because TlsCipherMappingTable is not in line with the ciphers actually
supported by OpensslLib.
Fix that by removing TlsCipherMappingTable altogether.  Use
SSL_get_ciphers() instead to get the stack of ciphers supported by
openssl.  Name and ID of the ciphers can be queried using the
SSL_CIPHER_get_name() and SSL_CIPHER_get_protocol_id() functions,
which allows us to map IDs to names without a hard-code table.
Bugzilla: …
=> [PATCH v2 1/1] CryptoPkg/TlsLib: fix tls cipher configuration -- push

RedfishPkg/RedfishComponents.dsc.inc, RedfishPkg/RedfishLibs.dsc.inc
BZ #: 4566
Update Redfish modules to use the small footprint
version of base SortLib by the means of module scoped subelement <LibraryClass>. With this the platform
level SortLib (full version) is not impacted if
Redfish.dsc.inc is included in platform DSC.
Cc: Nhi Pham <nhi@os.amperecomputing.com>
=> RedfishPkg: Use base version SortLib for the specific modules

ShellPkg/Application/Shell/Shell.c, ShellPkg/Library/UefiShellLib/UefiShellLib.c, ShellPkg/ShellPkg.dec
Increase max buffer size to support more than 64K.
=> ShellPkg: Increase PcdShellPrintBufferSize from UINT16 to UINT32

UefiCpuPkg/Library/BaseRiscVMmuLib/BaseRiscVMmuLib.c, UefiCpuPkg/Library/BaseRiscVMmuLib/BaseRiscVMmuLib.inf, UefiCpuPkg/UefiCpuPkg.dec
Introduce a PCD to control the maximum SATP mode that MMU allowed to use. This PCD helps RISC-V platform set bare or minimum SATP mode during bring up to debug memory map issue.
Reviewed-by: Dhaval Sharma <dhaval@rivosinc.com>
Reviewed-by: Andrei Warkentin <andrei.warkentin@intel.com>
=> Pull: UefiCpuPkg: RISC-V: MMU: Introduce a PCD for SATP mode

RedfishPkg/RedfishDiscoverDxe/RedfishDiscoverDxe.c, RedfishPkg/RedfishDiscoverDxe/RedfishDiscoverDxe.inf, RedfishPkg/RedfishPkg.dec
Introduce PCD PcdRedfishSendReceiveTimeout to RedfishDiscoverDxe driver. The SendReceiveTimeout is hard-code value in Redfish discover driver. With this PCD, platform owner can configure timeout value easily.
=> RedfishPkg/RedfishDiscoverDxe: introduce PcdRedfishSendReceiveTimeout

BaseTools/Source/Python/Trim/Trim.py
As the error is changed to warning, Trim.py will skip the build error when the source code have exactly issue.
This patch change warning to error to opens the checking.
=> BaseTools: trim warning to error

EmbeddedPkg/Library/NorFlashInfoLib/NorFlashInfoLib.c
Update Gigadevice norflash list:
gd25q16, gd25q32, gd25q64, gd25lq64c, gd25q128, gd25lq128, gd25q256
Add Silicon Kaiser norflash list:
sk25lp128
Acked-by: Heinrich Schuchardt <heinrich.schuchardt@canonical.com>
=> EmbeddedPkg/NorFlashInfoLib: Update norflash device list

DynamicTablesPkg/DynamicTablesPkg.ci.yaml, DynamicTablesPkg/Include/Library/AmlLib/AmlLib.h, DynamicTablesPkg/Library/Acpi/Arm/AcpiSsdtPcieLibArm/SsdtPcieGenerator.c, DynamicTablesPkg/Library/Common/AmlLib/CodeGen/AmlResourceDataCodeGen.c
AmlCodeGenRdQWordMemory's and AmlCodeGenRdDWordMemory's Cacheable and MemoryRangeType parameters treat specific values as having specific meanings as defined by the spec. This change adds enums to map those meanings to their corresponding values.
Acked-by: Leif Lindholm <quic_llindhol@quicinc.com>
=> DynamicTablesPkg/AmlLib: Enumerate memory attributes

RedfishPkg/RedfishDiscoverDxe/RedfishDiscoverDxe.c
- It is expected that caller receives EFI_NO_MAPPING status when call issues Configure() to unconfigured network interface. Remove this false alarm in GetSubnetInfo() function.
- Fix typos
=> RedfishPkg/RedfishDiscoverDxe: remove Redfish false alarm

ArmPlatformPkg/Library/PL031RealTimeClockLib/PL031RealTimeClockLib.c
https://bugzilla.tianocore.org/show_bug.cgi?id=4565
http://mid.mail-archive.com/20231020121748.44862-1-lersek@redhat.com
https://listman.redhat.com/archives/edk2-devel-archive/2023-October/069136.html
https://edk2.groups.io/g/devel/message/109835
~~~
RealTimeClockLib instances are consumed by edk2's
EmbeddedPkg/RealTimeClockRuntimeDxe driver. In its entry point function
InitializeRealTimeClock(), the driver:
(1) calls LibRtcInitialize(),
(2) sets the GetTime(), SetTime(), GetWakeupTime() and SetWakeupTime()
runtime services to its own similarly-named functions -- where those
functions wrap the corresponding RealTimeClockLib APIs,
(3) installs EFI_REAL_TIME_CLOCK_ARCH_PROTOCOL with a NULL protocol
interface.
Steps (2) and (3) conform to PI v1.8 sections II-9.7.2.4 through
II-9.7.2.7. …
=> [PATCH] ArmPlatformPkg/PL031RealTimeClockLib: remove superfluous instance init steps -- push

UefiCpuPkg/Library/MpInitLib/MpLib.c
https://edk2.groups.io/g/devel/message/110052
https://listman.redhat.com/archives/edk2-devel-archive/2023-October/069353.html
http://mid.mail-archive.com/20231025114216.2824-1-yuanhao.xie@intel.com
~~~
Aim:
- To solve the assertion that checks if CpuMpData->FinishedCount
equals (CpuMpData->CpuCount - 1). The assertion arises from a timing
discrepancy between the BSP's completion of startup signal checks and
the APs' incrementation of the FinishedCount.
- This patch also ensures that "finished" reporting from the APs is as
later as possible.
More specifially:
In the SwitchApContext() function, the BSP trigers
the startup signal and check whether the APs have received it. After
completing this check, the BSP then verifies if the FinishedCount is
equal to CpuCount-1.
On the AP side, upon …
=> [Patch V3] UefiCpuPkg/MpInitLib: Wait for all APs to finish initialization -- push

ArmVirtPkg/ArmVirt.dsc.inc, ArmVirtPkg/ArmVirtKvmTool.dsc, ArmVirtPkg/ArmVirtPkg.dec, ArmVirtPkg/ArmVirtXen.dsc, ArmVirtPkg/Include/Guid/EarlyPL011BaseAddress.h, ArmVirtPkg/Include/Library/FdtSerialPortAddressLib.h, ArmVirtPkg/Library/DebugLibFdtPL011Uart/DebugLib.c, ArmVirtPkg/Library/DebugLibFdtPL011Uart/DebugLibFdtPL011UartFlash.inf, ArmVirtPkg/Library/DebugLibFdtPL011Uart/DebugLibFdtPL011UartRam.inf, ArmVirtPkg/Library/DebugLibFdtPL011Uart/DxeRuntimeDebugLibFdtPL011Uart.inf, ArmVirtPkg/Library/DebugLibFdtPL011Uart/Flash.c, ArmVirtPkg/Library/DebugLibFdtPL011Uart/Ram.c, ArmVirtPkg/Library/DebugLibFdtPL011Uart/Ram.h, ArmVirtPkg/Library/DebugLibFdtPL011Uart/RamNonRuntime.c, ArmVirtPkg/Library/DebugLibFdtPL011Uart/Runtime.c, ArmVirtPkg/Library/DebugLibFdtPL011Uart/Write.h, ArmVirtPkg/Library/Fdt16550SerialPortHookLib/EarlyFdt16550SerialPortHookLib.c, ArmVirtPkg/Library/Fdt16550SerialPortHookLib/EarlyFdt16550SerialPortHookLib.inf, ArmVirtPkg/Library/FdtPL011SerialPortLib/EarlyFdtPL011SerialPortLib.c, ArmVirtPkg/Library/FdtPL011SerialPortLib/EarlyFdtPL011SerialPortLib.inf, ArmVirtPkg/Library/FdtPL011SerialPortLib/FdtPL011SerialPortLib.c, ArmVirtPkg/Library/FdtSerialPortAddressLib/FdtSerialPortAddressLib.c, ArmVirtPkg/Library/FdtSerialPortAddressLib/FdtSerialPortAddressLib.inf, ArmVirtPkg/Library/PlatformPeiLib/PlatformPeiLib.c, ArmVirtPkg/Library/PlatformPeiLib/PlatformPeiLib.inf
https://bugzilla.tianocore.org/show_bug.cgi?id=4577
https://edk2.groups.io/g/devel/message/109394
http://mid.mail-archive.com/20231008153912.175941-1-lersek@redhat.com
https://listman.redhat.com/archives/edk2-devel-archive/2023-October/068694.html
~~~
This ArmVirtPkg series can be fetched from:
repo:   https://pagure.io/lersek/edk2.git
branch: armvirt-dual-serial @ 65ee08413595
The series does the following:
- It centralizes (and cleans up) two FDT parsing actions, namely looking
up all serial ports, and looking up the /chosen "stdout-path" serial
port, in a new library class and instance.
- It rebases Fdt16550SerialPortHookLib, EarlyFdtPL011SerialPortLib and
PlatformPeiLib to the new library.
- If QEMU specifies just one PL011 UART, then this patch set is
unobservable from the outside.
- …
=> [PATCH 0/9] ArmVirtPkg: support two PL011 UARTs -- push

Maintainers.txt
Plugins can be placed either in .pytool/Plugin (CI plugin) or BaseTools/Plugin (build plugin).
Since most of the .pytool maintainers already review many of the plugins placed there, the same maintainers are added for the Plugin directory in BaseTools to increase the total number of maintainers for plugin changes.
=> Maintainers.txt: Add .pytool maintainers to BaseTools/Plugin

DynamicTablesPkg/Library/Common/TableHelperLib/ConfigurationManagerObjectParser.c
The patch "f81ee47513e5 DynamicTablesPkg: Add an ET info object parser" updates the Configuration Manager object parser to add support for parsing CM_ARM_ET_INFO object.
However, the GicC info structure also has an ET Reference token that points to the CM_ARM_ET_INFO object. Therefore, update the GICC info object parser to add an entry to parse the ET reference token. Without this change an assert stating that the RemainingSize != 0 will be triggered.
Reviewed-by: levi.yun <yeoreum.yun@arm.com>
=> DynamicTablesPkg: Fix assert in CmObject parser

ReadMe.rst
- Adds Apache License 2.0 as an acceptable source license per discussion in https://edk2.groups.io/g/devel/message/110226
- Updates the URL for existing licenses to match the current path used by opensource.org.
- The submodule list in this file is stale and is very prone to being forgotten. The list of submodules in the submodules setion is replaced with a link to .gitmodules which has an active list of submodules at any given time.
Cc: Pedro Falcato <pedro.falcato@gmail.com>
=> ReadMe.rst: Add Apache License 2.0 and update submodule list

IntelFsp2Pkg/Library/BaseFspSwitchStackLib/X64/Stack.nasm
When FSP runs in API mode, it saves the IDTR in its own stack then switches to bootloader's stack before it returns from FspMemoryInit. Next time when the bootloader calls TempRamExit, FSP switches to its own stack and restores IDTR from its stack saved earlier.
However, due to a bug in BaseFspSwitchStackLib, the IDTR saved on FSP's stack might be corrupted that results the following TempRamExit call fails inside FSP due to PeiServices pointer cannot be retrieved from IDT.base - 8.
The bug is the assembly code doesn't reserve 32 bytes before calling the C routine in 64bit. According to the x86-64 calling convention, caller is responsible for allocating 32 bytes of "shadow space" on the stack right before calling the function (regardless of the actual number of parameters used).
When FSP …
=> IntelFsp2Pkg/SwitchStack: Reserve 32B when calling C function in 64bit

IntelFsp2Pkg/Tools/UserManuals/PatchFvUserManual.md
According to the markdown language syntax, headings should be after number signs (#). The number of number signs correspond to the heading level.
But current PatchFvUserManual.md doesn't insert a space between the number signs and the heading title, resulting the markdown file is not rendered well in markdown viewers.
The patch doesn't change any content but only adds spaces to ensure the headings are correctly recognized.
Reviewed-by: Ashraf Ali S <ashraf.ali.s@intel.com>
=> IntelFsp2Pkg/PatchFv: Fix syntax issue in markdown manual

BaseTools/Scripts/PatchCheck.py
Allow .rtf files created by applications such as Notepad to be committed as-is without further manual editing by skipping the requirements for CRLF, no tabs and no trailing whitespace.
=> BaseTools: Update PatchCheck.py to allow whitespace issues in .rtf files

IntelFsp2WrapperPkg/Library/FspWrapperMultiPhaseProcessLib/PeiFspWrapperMultiPhaseProcessLib.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4595
Fix build error when remove "-Wno-sometimes-uninitialized" option, Add variable "FspMultiPhaseApiOffset" initialization.
=> IntelFsp2WrapperPkg: Add variable initialization

MdePkg/Include/IndustryStandard/Tdx.h, MdePkg/Library/BaseLib/X64/TdVmcall.nasm, OvmfPkg/Library/BaseMemEncryptTdxLib/MemoryEncryption.c
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4572
According to section 3.2 of the [GHCI] spec, if the result is 
"TDG.VP.VMCALL_RETRY" for TDG.VP.VMCALL.MapGPA, TD must retry the
mapping for the pages in the region starting at the GPA specified in r11.
Currently, TDVF does not properly handle the retry results of MapGPA.
For this, TDVF should update the TdVmCall to return the value in R11
and must retry the mapping for the pages by the value.
How to verify the retry for MapGPA in TDVF:
Note: Since the range size of MapGPA in QEMU is limited to 64MB and
TDVF always maps 1.5GB( 2GB~3.5GB) MMIO to shared-memory for TD guest, 
the retry action is triggered always.
Pre-Config:
QEMU:
https://github.com/intel/qemu-tdx/tree/tdx-qemu-upstream | tag: tdx-qemu-upstream-2023.10.20-v8.1.0 …
=> OvmfPkg: Update TdVmCall to handle the retry for MapGPA 

BaseTools/Scripts/GetMaintainer.py
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4593
Fix logic bug where maintainers was incorrectly added to lists.
If a package only has reviewers and no maintainers, then also
return the <default> maintainers.
In order to detect this case, get_maintainers() is updated to
return maintainers, reviews, and lists separately instead of
a single merged list.  This also allows this module to be used
by other scripts that need to distinguish between maintainers,
reviewers, and lists.
Simplify logic that accumulates maintainers, reviewers, lists.
Sort the list of output addresses alphabetically and use set()
instead of OrderedDict() to accumulate unique addresses.
Changes since v2:
- Reworked internal return logic to use dictionaries.
- Reordered cleanup before new functionality.
Changes …
=> Base tools get maintainer reviewers only v3

MdeModulePkg/Universal/RegularExpressionDxe/RegularExpressionDxe.inf
Ignore old style declaration warnings in oniguruma/src/st.c.  This was already ignored for MSFT, but newer versions of clang complain as well.
Reviewed-by: Nhi Pham <nhi@os.amperecomputing.com>
Tested-by: Nhi Pham <nhi@os.amperecomputing.com>
=> MdeModulePkg/RegularExpressinoDxe: Fix clang error

RedfishPkg/RedfishDiscoverDxe/RedfishDiscoverDxe.c, RedfishPkg/RedfishDiscoverDxe/RedfishDiscoverInternal.h
Supported function of the driver changed to wait for all network
interface to be installed.
Filter out the network interfaces which are not supported by
Redfish Host Interface.
=> Wait for all net interfaces installed

DynamicTablesPkg/Library/Acpi/Arm/AcpiSsdtCpuTopologyLibArm/SsdtCpuTopologyGenerator.c
Bugzilla: 4600 (https://bugzilla.tianocore.org/show_bug.cgi?id=4600)
Just like CPU _UID, ETE UID also needs to be unique so use AcpiProcessorUid instead of CpuName
=> DynamicTablesPkg: Fix ETE _UID Creation

ArmPkg/Library/ArmMmuLib/AArch64/ArmMmuLibCore.c, ArmPkg/Library/ArmMmuLib/AArch64/ArmMmuPeiLibConstructor.c, ArmPkg/Library/ArmMmuLib/ArmMmuBaseLib.inf, ArmPkg/Library/ArmMmuLib/ArmMmuLibInternal.h, ArmPkg/Library/ArmMmuLib/ArmMmuPeiLib.inf
mReplaceLiveEntryFunc is a function pointer but assigned as a VOID* pointer:
mReplaceLiveEntryFunc = *(VOID **)GET_GUID_HOB_DATA (Hob);
This leads to the Visual Studio warning:
nonstandard extension, function/data pointer conversion in
expression
This change updates the assignment to avoid using a data pointer and defines a type for the function pointer to succinctly and accurately refer to the type when it is used in the library code.
=> ArmPkg/ArmMmuLib: Use function pointer type

.git-blame-ignore-revs
Includes two recent Uncrustify formatting commits to prevent them from showing in git blame.
=> .git-blame-ignore-revs: Ignore recent uncrustify commits

MdeModulePkg/Universal/Variable/RuntimeDxe/Variable.c
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=4597
When creating a new variable, skip marking VAR_HEADER_VALID_ONLY so that variable header + data update can be merged into one flash write. This will greatly reduce the time taken for updating a variable and thus increase performance. Removing VAR_HEADER_VALID_ONLY marking doesn't have any function impact since it's not used by current code to detect variable header + data corruption.
=> MdeModulePkg/Variable: Merge variable header + data update into one step

UefiCpuPkg/PiSmmCpuDxeSmm/MpService.c
Currently, if BSP election is not enabled, will use Core0 as SMM BSP, however, Core0 does not always have the highest performance core. So, we can used NonSmm BSP as default BSP.
=> UefiCpuPkg: Use NonSmm BSP as BSP if BSP election is not enabled.

BaseTools/Conf/target.template
Updates the default tool chain from VS2015x86 to VS2019.
This is the VS tool chain used in CI and more likely to be installed on developer's systems. This is used in stuart commands when a toolchain is not explicitly specified.
---
Includes trailing whitespace fixes in the file.
---
=> BaseTools/Conf/target.template: Use VS2019 as default tool chain

.github/workflows/codeql.yml
Updates the workflow to also output files that can be loaded in emacs to show CodeQL issues (in addition to the existing SARIF output for standard SARIF viewers).
Cc: Joey Vagedes <joey.vagedes@gmail.com>
Reviewed-by: Joey Vagedes <joey.vagedes@gmail.com>
=> .github/workflows/codeql.yml: Add emacs output

RedfishPkg/Library/PlatformHostInterfaceBmcUsbNicLib/PlatformHostInterfaceBmcUsbNicLib.c, RedfishPkg/Library/PlatformHostInterfaceBmcUsbNicLib/PlatformHostInterfaceBmcUsbNicLib.inf, RedfishPkg/RedfishPkg.dec
BZ #4607
Create a PCD for the default Redfish service port.
Cc: Mike Maslenkin <mike.maslenkin@gmail.com>
Reviewed-by: Nickle Wang <nicklew@nvidia.com>
=> RedfishPkg/HostInterfaceBmcUsbNic: Set default Redfish service port

MdePkg/Library/BaseStackCheckLib/BaseStackCheckGcc.c
__builtin_return_address returns a pointer, not a string. Fix the STACK FAULT message in BaseStackCheckLib appropriately.
=> BaseStackCheckLib: Fix STACK FAULT message

PcAtChipsetPkg/Library/AcpiTimerLib/DxeStandaloneMmAcpiTimerLib.c
The DXE & MM standalone variant of AcpiTimerLib defines a global named mPerformanceCounterFrequency. A global with an identical name is also present in MdeModulePkg/Bus/Pci/XhciDxe/Xhci.c
Since XhciDxe has a dependency on TimerLib, this can cause link errors due to the same symbol being defined twice if the platform DSC chooses to use AcpiTimerLib as the TimerLib implementation for any given platform.
To resolve this, I have changed made the definition of mPerformanceCounterFrequency to static and renamed it to mAcpiTimerLibTscFrequency. Since this variable is not used outside of the DxeStandaloneMmAcpiTimerLib.c compilation unit, there is no reason to have it exported as a global.
=> PcAtChipsetPkg: Fix AcpiTimerLib incompatibility with XhciDxe

OvmfPkg/Bhyve/PlatformPei/Platform.c
Bhyve uses an io port range of [ 0x2000, 0x10000 ] [1]. At the moment, EDKII is using a subset of this range [ 0xC000, 0x10000 ] [2]. Even though the EDKII range doesn't exceed the bhyve range, it's causing issues on some guests like OpenBSD [3]. We don't know why it's causing issues yet. However, using the same IO port range in EDKII fixes the issue and is a good idea anyway.
[1] https://github.com/freebsd/freebsd-src/blob/82ea0132c8b17a7a6067c8a36c6434e587ede6de/usr.sbin/bhyve/pci_emul.c#L133-L134
[2] https://github.com/tianocore/edk2/blob/fb044b7fe893a4545995bfe2701fd38e593355d9/OvmfPkg/Bhyve/PlatformPei/Platform.c#L156-L157
[3] https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=274389
Cc: Ard …
=> OvmfPkg/Bhyve: use a proper PCI IO range

MdePkg/Include/Uefi/UefiSpec.h
Update the EFI LoadImage API in accordance with the UEFI v2.10 specification.
Cc: T V Krishnamoorthy <krishnamoorthy.t.v@intel.com>
=> MdePkg: Define the DevicePath argument from LoadImage as optional

MdePkg/Include/Uefi/UefiSpec.h
New memory type as defined in UEFI standard v2.10
Cc: T V Krishnamoorthy <krishnamoorthy.t.v@intel.com>
=> MdePkg: Add UEFI v2.10 ISA memory type definition

ArmVirtPkg/ArmVirtPkg.dec, ArmVirtPkg/Library/PlatformBootManagerLib/PlatformBm.c, ArmVirtPkg/Library/PlatformBootManagerLib/PlatformBootManagerLib.inf
Shim's PE loader uses the EFI memory attributes protocol in a way that results in an immediate crash when invoking the loaded image unless the base and size of its executable segment are both aligned to 4k.
If this is not the case, it will strip the memory allocation of its executable permissions, but fail to add them back for the executable region, resulting in non-executable code. Unfortunately, the PE loader does not even bother invoking the protocol in this case (as it notices the misalignment), making it very hard for system firmware to work around this by attempting to infer the intent of the caller.
So let's introduce a QEMU command line option to indicate that the protocol should not be exposed at all.
=> ArmVirtPkg: Allow EFI memory attributes protocol to be disabled

ArmVirtPkg/PlatformCI/.azurepipelines/Ubuntu-GCC5.yml, ArmVirtPkg/PlatformCI/CloudHvBuild.py
Add the long lost CI for CloudHv on AArch64.
As CloudHv CI works nearly the same way with other VMMs like KvmTool, thus we can easily create its CI configuration based on KvmTool.
=> CloudHv: Add CI for CloudHv on AArch64

ArmPkg/Library/DebugPeCoffExtraActionLib/DebugPeCoffExtraActionLib.c
The DebugPeCoffExtraActionLib implemention in ArmPkg contains some cruft that dates back to the original RVCT based ARM port, and support for RVCT was dropped a while ago.
Also drop the handling of Cygwin specific paths, which is highly unlikely to be still depended upon by anyone.
Tweak the logic so that only two versions of the DEBUG() invocations remain: one for __GNUC__ when PdbPointer is set, and the fallback that just prints the image address and the address of the entrypoint.
=> ArmPkg/DebugPeCoffExtraActionLib: Drop RVCT and Cygwin support

FatPkg/FatPei/FatLiteApi.c
Move the range check before array access to enforce the bounds as expected.
Reviewed-by: Michael D Kinney [<michael.d.kinney@intel.com>](mailto:michael.d.kinney@intel.com)
=> FatPkg/FatPei: Check array offset before use

ShellPkg/Library/UefiShellLevel2CommandsLib/Reset.c
ShellPkg: Tidy for code readability
Use error handling instead of success handling.
Less indented logic is easier to read.
Signed-off-by: Daniel Nguyen <daniel.nguyen@arm.com>
=> ShellPkg: Tidy for code readability

StandaloneMmPkg/Core/Dispatcher.c, StandaloneMmPkg/Core/FwVol.c, StandaloneMmPkg/Core/StandaloneMmCore.c, StandaloneMmPkg/Core/StandaloneMmCore.h, StandaloneMmPkg/Core/StandaloneMmCore.inf, StandaloneMmPkg/StandaloneMmPkg.dec
V1:
This patch is to fix the issue that StandaloneMmCore fails to detect uncompressed inner FV.
PR: https://github.com/tianocore/edk2/pull/4943
V2:
Based on V1, fix some other issues
1. Add Missing object size checks before casting pointers to header types
a. InnerFvHeader = (EFI_FIRMWARE_VOLUME_HEADER *)SectionData; 
This is introduced in V1, add the size check on SectionDataSize against EFI_FIRMWARE_VOLUME_HEADER
b. Section = (EFI_COMMON_SECTION_HEADER *)(FileHeader + 1);
Use FfsFindSection instead of FfsFindSectionData to avoid pointer casting.
2. Fix potential memory leak issue that ScratchBuffer is not freed when page allocation for DstBuffer fails.
PR: https://github.com/tianocore/edk2/pull/4965
V3:
1. Separate patch per individual issue fix on patch V2.
2. Fix one more issue: Limit …
=> StandaloneMmCore finds drivers in uncompressed inner fv. v4

MdeModulePkg/Library/UefiBootManagerLib/BmLoadOption.c
Currently, the ReadyToBoot event is only signaled when a formal Boot Manager option is executed (in BmBoot.c -> EfiBootManagerBoot ()).
However, the introduction of Platform Recovery in UEFI 2.5 makes it necessary to signal ReadyToBoot when a Platform Recovery boot loader runs because otherwise it may lead to the execution of a boot loader that has similar requirements to a regular one that is not launched as a Boot Manager option.
This is especially critical to ensuring that the graphical console is actually usable during platform recovery, as some platforms do rely on the ConsolePrefDxe driver, which only performs console initialization after ReadyToBoot is triggered.
This patch fixes that behavior by calling EfiSignalEventReadyToBoot () in EfiBootManagerProcessLoadOption () when …
=> MdeModulePkg/UefiBootManagerLib: Signal ReadyToBoot on platform recovery

BaseTools/Source/Python/FMMT/core/GuidTools.py
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4624
Currently, Python FMMT tool does not support automatically select FMMTConf.ini file which saves GuidTool settings. This patch supports this features.
=> BaseTools: FMMT GuidTool Auto Select Config file Enabling

CryptoPkg/Library/Include/CrtLibSupport.h, CryptoPkg/Library/Include/stdint.h
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=4632
The before code will cause redefine error.
This patch move them to CrtLibSupport header.
But Openssl has already defined them internally,
need to increase support for OPENSLL_SYS_UEFI judgment.
=> CryptoPkg: move define to CrtLibSupport

EmulatorPkg/Include/Protocol/EmuThunk.h, EmulatorPkg/Unix/Host/EmuThunk.c, EmulatorPkg/Win/Host/WinThunk.c
There is an inconsistency between the UNIX and Windows
implementations of EMU_THUNK_PROTOCOL.SetTime(). The Windows
version returns an EFI_STATUS value whereas the the UNIX
implementation is VOID. However, the UNIX implementation is an
unimplemented stub whereas the Windows version is implementated.
The current EMU_THUNK_PROTOCOL function pointer definition
specifies a VOID return type. However, EMU_THUNK_PROTOCOL.SetTime()
is close to the spec defined gRT->SetTime() except for missing the
EFI_STATUS return type.
Therefore, I conclude that the most sensible reconciliation is to
add the EFI_STATUS return type to the protocol definition.
Cc: Chasel Chiu …
=> Add EFI_STATUS return to EMU_THUNK_PROTOCOL.SetTime()

MdePkg/Include/Uefi/UefiSpec.h
Add the description of CapsuleImageSize to align with UEFI spec 2.10.
REF: UEFI spec 2.10 section 8.5.3.1
=> MdePkg: Updated the definition of CapsuleImageSize on EFI_CAPSULE_HEADER

UefiPayloadPkg/UefiPayloadPkg.dsc, UefiPayloadPkg/UefiPayloadPkg.fdf
Add macro to enable selection of timer
- HPET:  UEFI Payload will use HPET timer
- LAPIC: UEFI Payload will use local APIC timer
=> UefiPayloadPkg: Add macro to enable selection of timer

CryptoPkg/Library/MbedTlsLib/Include/mbedtls/mbedtls_config.h
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=4630
Enable MBEDTLS_NO_UDBL_DIVISION to fix GCC x64 build failure.
=> CryptoPkg: fix gcc build fail for CryptoPkgMbedtls

MdePkg/Include/Protocol/NvdimmLabel.h
Add the description of EFI_NVDIMM_LABEL_FLAGS_LOCAL to align with UEFI spec 2.10.
REF: UEFI spec 2.10 Table 13.19.4
=> MdePkg: Update the definition of EFI_NVDIMM_LABEL_FLAGS_LOCAL 

BaseTools/Source/Python/AutoGen/GenMake.py, BaseTools/Source/Python/Common/Misc.py, BaseTools/Source/Python/Workspace/DscBuildData.py
Fixes raw regex strings that contain valid (and purposeful) escape characters as they are being treated as individual characters rather than the single escaped character they represent (i.e. '\t' is being treated as a '\' and a 't' rather than a single tab character).
=> BaseTools: Fix raw strings containing valid escape characters

CryptoPkg/Library/Include/CrtLibSupport.h, CryptoPkg/Library/Include/stdint.h
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=4632
Move the define to stdint and add MACRO to prevent duplicate inclusion.
=> CryptoPkg: Fix redefinition error of int defines

MdePkg/Library/BaseLib/BaseLib.inf, MdePkg/Library/BaseLib/RiscV64/InternalSwitchStack.c, MdePkg/Library/BaseLib/RiscV64/SwitchStack.S
For scene of
HandOffToDxeCore()->SwitchStack(DxeCoreEntryPoint)-> InternalSwitchStack()->LongJump(),Variable HobList.Raw will be passed (from *Context1 to register a0) to
DxeMain() in parameter *HobStart.
However, meanwhile the function LongJump() overrides register a0 with a1 (-1)  due to commit (ea628f28e5 "RISCV: Fix InternalLongJump to return correct value"), then cause hang.
Replacing calling LongJump() with new InternalSwitchStackAsm() to pass addres data in register s0 to register a0 could fix this issue (just like the solution in MdePkg/Library/BaseLib/AArch64/SwitchStack.S)
Cc: Bamvor Jian ZHANG <zhangjian@bosc.ac.cn>
Cc: Sunil V L …
=> Pull : MdePkg/BaseLib: Fix boot DxeCore hang on riscv platform
