.pytool/Readme.md

Update the "Basic Status" matrix for DynamicTablesPkg by adding a check mark for Windows VS2019 IA32/X64 support.
Cc: Joey Vagedes <joey.vagedes@gmail.com>
Reviewed-by: Joey Vagedes <joey.vagedes@gmail.com>

.pytool/Readme.md: Update matrix for DynamicTablesPkg

---

NetworkPkg/WifiConnectionManagerDxe/WifiConnectionMgrImpl.c

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4605
When UEFI Wi-Fi is in BSS connected state, the platform is considered as a static and Wi-Fi roaming support is not needed. Wifi connection manager should not initiate Scan requests in this state affect BSS client connectivity and must be avoided. Triger timely scan only if not connect to AP.
Cc: Saloni Kasbekar <saloni.kasbekar@intel.com>
Cc: Zachary Clark-williams <zachary.clark-williams@intel.com>

NetworkPkg: Triger timely scan only if not connect to AP

---

OvmfPkg/RiscVVirt/RiscVVirtQemu.dsc

Only need to include Network.dsc.inc to have all network drivers/components be built. Otherwise, there were missing definition that prevent them from be built for RiscVVirt platform.

Pull Tuan's fix (OvmfPkg: RiscVVirt: Fix network drivers not be built)

---

MdePkg/Include/Protocol/HiiConfigAccess.h

Add status code EFI_DEVICE_ERROR for ExtractConfig to align with UEFI spec 2.10.
REF: UEFI spec 2.10 Table 35.5.2

MdePkg: Update the comments of ExtractConfig 

---

MdePkg/Include/Protocol/FormBrowser2.h

Add status code return for BROWSER callback in EFI_FORM_BROWSER2_PROTOCOL to align with UEFI spec 2.10.
REF: UEFI spec 2.10 Table 35.6.3

MdePkg: Update the comments of callback in EFI_FORM_BROWSER2_PROTOCOL

---

MdePkg/Include/Protocol/Tcp6.h
NetworkPkg/TcpDxe/TcpInput.c
NetworkPkg/TcpDxe/TcpProto.h

REF: UEFI spec 2.10 section 28.2.5
Change the description of RFC1323 to align with UEFI spec 2.10.
Signed-off-by: Suqiang Ren <suqiangx.ren@intel.com>
Cc: Saloni Kasbekar <saloni.kasbekar@intel.com>
Cc: Zachary Clark-williams <zachary.clark-williams@intel.com>

MdePkg: Update the definition of EFI_TCP6_OPTION

---

MdePkg/Include/Protocol/NvdimmLabel.h

Refer to Uefi spec 2.10 section 13.19.5, update the Label Definitions for NVDIMM SPA Location Cookie.

MdePkg: Update the Label difinations of the EFI_NVDIMM_LABEL

---

SecurityPkg/Library/DxeTpm2MeasureBootLib/DxeTpm2MeasureBootLib.c
SecurityPkg/Library/DxeTpm2MeasureBootLib/DxeTpm2MeasureBootLib.inf
SecurityPkg/Library/DxeTpm2MeasureBootLib/DxeTpm2MeasureBootLibSanitization.c
SecurityPkg/Library/DxeTpm2MeasureBootLib/DxeTpm2MeasureBootLibSanitization.h
SecurityPkg/Library/DxeTpm2MeasureBootLib/InternalUnitTest/DxeTpm2MeasureBootLibSanitizationTest.c
SecurityPkg/Library/DxeTpm2MeasureBootLib/InternalUnitTest/DxeTpm2MeasureBootLibSanitizationTestHost.inf
SecurityPkg/Library/DxeTpmMeasureBootLib/DxeTpmMeasureBootLib.c
SecurityPkg/Library/DxeTpmMeasureBootLib/DxeTpmMeasureBootLib.inf
SecurityPkg/Library/DxeTpmMeasureBootLib/DxeTpmMeasureBootLibSanitization.c
SecurityPkg/Library/DxeTpmMeasureBootLib/DxeTpmMeasureBootLibSanitization.h
SecurityPkg/Library/DxeTpmMeasureBootLib/InternalUnitTest/DxeTpmMeasureBootLibSanitizationTest.c
SecurityPkg/Library/DxeTpmMeasureBootLib/InternalUnitTest/DxeTpmMeasureBootLibSanitizationTestHost.inf
SecurityPkg/SecurityFixes.yaml
SecurityPkg/SecurityPkg.ci.yaml
SecurityPkg/Test/SecurityPkgHostTest.dsc

This patch series include the combined / merged security patches
(as seperate commits) for TCBZ4117 (CVE-2022-36763) and TCBZ4118
(CVE-2022-36764) for DxeTpm2MeasureBootLib and DxeTpmMeasureBootLib.
These patches have already been reviewed by SecurityPkg Maintainer
(Jiewen) on GHSA. 
This patch series (specifically TCBZ4117) supersedes TCBZ2168.
Douglas Flick [MSFT] (6):
SecurityPkg: DxeTpm2MeasureBootLib: SECURITY PATCH 4117 - CVE
2022-36763
SecurityPkg: DxeTpmMeasureBootLib: SECURITY PATCH 4117 - CVE
2022-36763
SecurityPkg: : Adding CVE 2022-36763 to SecurityFixes.yaml
SecurityPkg: DxeTpm2MeasureBootLib: SECURITY PATCH 4118 - CVE
2022-36764
SecurityPkg: DxeTpmMeasureBootLib: SECURITY PATCH 4118 - CVE
2022-36764
SecurityPkg: : Adding CVE 2022-36764 …

 SECURITY PATCHES TCBZ4117 & TCBZ4118

---

NetworkPkg/Ip4Dxe/Ip4Config2Nv.c

Exercising reset to default does not reset the settings. Add handler code for the case where configuration is disabled.
Reviewed-by: Saloni Kasbekar <saloni.kasbekar@intel.com>

NetworkPkg/Ip4Dxe: Fix Reset To Default

---

MdePkg/Include/IndustryStandard/Acpi30.h
MdePkg/Include/IndustryStandard/Acpi40.h
MdePkg/Include/IndustryStandard/Acpi50.h
MdePkg/Include/IndustryStandard/Acpi51.h
MdePkg/Include/IndustryStandard/Acpi60.h
MdePkg/Include/IndustryStandard/Acpi61.h
MdePkg/Include/IndustryStandard/Acpi62.h
MdePkg/Include/IndustryStandard/Acpi63.h
MdePkg/Include/IndustryStandard/Acpi64.h
MdePkg/Include/IndustryStandard/Acpi65.h

Add definitions for:
- _PSD version: added in ACPI 3.0
- C-state Coordination Types: added in ACPI 3.0
- _CPC version: added in ACPI 5.0

MdePkg/IndustryStandard: Add _PSD/_CPC/Coord types definitions

---

MdePkg/Library/BaseIoLibIntrinsic/IoLibInternalTdx.c

Currently the types of casting mismatch with TD MMIO read 1, 2 and 4 bytes, that might introduce potential issues.  So fix the types as conventional MmioRead[8|16|32] does.

MdePkg/Library/BaseIoLibIntrinsic: Fix TD MMIO read type cast

---

CryptoPkg/CryptoPkg.ci.yaml
CryptoPkg/Library/Include/inttypes.h

REF:https://bugzilla.tianocore.org/show_bug.cgi?id=4642
When use Mbedtls, there is a clang build error.
Add dummy inttypes header to fix clang build.
Signed-off-by: Wenxing Hou <wenxing.hou@intel.com>

CryptoPkg: Add dummy inttypes header to fix clang build

---

UefiPayloadPkg/Library/CbParseLib/CbParseLib.c

The IMD entry uses the 32bit start field as relative offset to root. On Ia32X64 this works fine as UINTN is also 32 bit and negative relative offsets are properly calculated due to an integer overflow.
On X64 this doesn't work as UINTN is 64 bit and the offset is no longer subtracted, but it's added to the root. Fix that by sign extending the start field to 64 bit.
Test: Booting UefiPayloadPkg still works on Ia32X64 and now also
works on X64.

UefiPayloadPkg: CbParseLib: Fix integer overflow

---

.pytool/Plugin/UncrustifyCheck/UncrustifyCheck.py

The UncrustifyCheck plugin passes os.stat.S_IWRITE to os.chmod, when attempting to change file permissions. os.stat.S_IWRITE does not exist as os.stat is a function. The correct value is stat.S_IWRITE.

.pytool/Plugin: UncrustifyCheck: use stat instead of os.stat

---

StandaloneMmPkg/Core/Dependency.c

The current dependency evaluator violates the memory access permission when patching depex grammar directly in the read-only depex memory area.
Laszlo pointed out the optimization issue in the thread (1) "Memory Attribute for depex section" and provided suggested patch to remove the perf optimization.
In my testing, removing the optimization does not make significant perf reduction. That makes sense that StandaloneMM dispatcher only searches in MM protocol database and does not depend on UEFI/DXE protocol database. Also, we don't have many protocols in StandaloneMM like UEFI/DXE.
From Laszlo,
"The patch removes the EFI_DEP_REPLACE_TRUE handling altogether, plus it CONST-ifies the Iterator pointer (which points into the DEPEX section), so that the compiler catch any possible accesses at …

StandaloneMmPkg/Core: Remove optimization for depex evaluation

---

MdePkg/Include/Guid/FileInfo.h

Add the description of EFI_FILE_INFO FileName[1] field to align with UEFI spec 2.10 Section 13.5.16.

MdePkg/Include/Guid: Update the definition of FileName in EFI_FILE_INFO

---

MdePkg/Library/BaseCpuLibNull/BaseCpuLibNull.c

CpuLib.h exposes StandardSignatureIsAuthenticAMD() API and we require stub function in its BaseCpuLibNull library instance to avoid potential link issue.

MdePkg/Library/BaseCpuLibNull: Add StandardSignatureIsAuthenticAMD()

---

MdePkg/Library/BaseFdtLib/LibFdtSupport.h
MdePkg/Library/BaseFdtLib/LibFdtWrapper.c

Rename the standard functions in the LibFdtSupport to remove conflicts with other libraries that define them.

MdePkg/BaseFdtLib: Rename standard functions

---

UefiPayloadPkg/UefiPayloadPkg.dsc
UefiPayloadPkg/UefiPayloadPkg.fdf

Crypto in serveral case will use old version, treat as optional will make customer easy to upgrade it.

UefiPayloadPkg/Crypto: Support external Crypto drivers.

---

MdePkg/Library/BaseCpuLibNull/BaseCpuLibNull.c
MdePkg/Library/BaseCpuLibNull/BaseCpuLibNull.inf
MdePkg/Library/BaseCpuLibNull/X86BaseCpuLibNull.c

* Add InitializeFloatingPointUnits() to x86 specific file
* Add GetCpuFamilyModel() to x86 specific file
* Add GetCpuSteppingId() to x86 specific file
* Move StandardSignatureIsAuthenticAMD() to x86 specific file.
* Add CpuLib library class include to all C files.
Cc: Qing Huang <qing.huang@intel.com>

MdePkg/Library/BaseCpuLibNull: Add missing X86 specific services

---

PcAtChipsetPkg/HpetTimerDxe/HpetTimer.c

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4659
When HPET timer is used as the timer interrupt and nested interrupts into the HPET timer interrupt handler occur, the elapsed time passed into the DXE Core is sometime too large and this causes the DXE Core internal system time to run too fast. Fix the logic so the previous main counter value stored in the module global variable mPreviousMainCounter is always captured before the timer notification function is called.
Without this change, mPreviousMainCounter is updated after the timer notification function is called and when nesting occurs, it updates with the value from the first level of nesting which is further back in time than the interrupt from the deepest level of nesting.  This causes the next two timer interrupts to compute …

PcAtChipsetPkg/HpetTimerDxe: Fix nested interrupt time accuracy

---

OvmfPkg/ResetVector/QemuDebugCon.asm
OvmfPkg/ResetVector/ResetVector.nasmb

~~~
Neat when doing ResetVector coding.
Incompatible with TDX and SEV, therefore not enabled by default.
Acked-by: Tom Lendacky <thomas.lendacky@amd.com>
Acked-by: Erdem Aktas <erdemaktas@google.com>
---
OvmfPkg/ResetVector/QemuDebugCon.asm  | 36 +++++++++++++++++++++++++++
OvmfPkg/ResetVector/ResetVector.nasmb |  4 +++
2 files changed, 40 insertions(+)
create mode 100644 OvmfPkg/ResetVector/QemuDebugCon.asm
~~~

[PATCH v3 1/1] OvmfPkg/ResetVector: send post codes to qemu debug console -- push

---

MdeModulePkg/Core/Dxe/DxeMain.h
MdeModulePkg/Core/Dxe/DxeMain/DxeMain.c
MdeModulePkg/Core/Dxe/Gcd/Gcd.c
MdeModulePkg/Core/Dxe/Image/Image.c
MdeModulePkg/Core/Dxe/Mem/Page.c
MdeModulePkg/Include/Guid/MemoryTypeInformation.h

Provide an optional method for PEI to declare a specific address range to use for the Memory Type Information bins. The current algorithm uses heuristics that tends to place the Memory Type Information bins in the same location, but memory configuration changes across boots or algorithm changes across a firmware updates could potentially change the Memory Type Information bin location.
If the HOB List contains a Resource Descriptor HOB that describes tested system memory and has an Owner GUID of gEfiMemoryTypeInformationGuid, then use the address range described by the Resource Descriptor HOB as the preferred location of the Memory Type Information bins. If this HOB is not detected, then the current behavior is preserved.
The HOB with an Owner GUID of gEfiMemoryTypeInformationGuid is …

MdeModulePkg/Core/Dxe: Set MemoryTypeInfo bin range from HOB

---

BaseTools/Source/Python/AutoGen/WorkspaceAutoGen.py

The patch "[PATCH v3 1/2] StandaloneMmPkg: Make StandaloneMmCpu driver architecture independent" (https://edk2.groups.io/g/devel/message/109178) removed ArmPkg/ArmPkg.dec from the Packages section in the INF file: StandaloneMmPkg/Drivers/StandaloneMmCpu/StandaloneMmCpu.inf
This change was done as part of making the StandaloneMmCpu driver architecture independent.
Although this change is correct, it results in a side effect here some platforms that utilise PCDs declared in ArmPkg.dec are no longer declared.
An example of this issue can be seen when building edk2-platforms/Platform/ARM/SgiPkg/PlatformStandaloneMm.dsc
$ build -a AARCH64 -t GCC -p Platform/ARM/SgiPkg/PlatformStandaloneMm.dsc build.py...
/mnt/source/edk2-platforms/Platform/ARM/SgiPkg/PlatformStandaloneMm.fdf(23):
error F001: …

Basetools: Include PCD declarations from Library Instance

---

MdeModulePkg/Core/Dxe/Image/Image.c
ShellPkg/Library/UefiShellDebug1CommandsLib/SmbiosView/PrintInfo.c
ShellPkg/Library/UefiShellDebug1CommandsLib/SmbiosView/QueryTable.c

[PATCH 1/2] MdeModulePkg: Dxe: add LOONGARCH64 to mMachineTypeInfo
This fixes messages like:
"Image type X64 can't be loaded on <Unknown> UEFI system"
Reviewed-by: Chao Li <lichao@loongson.cn>
[PATCH 2/2] ShellPkg: Update smbiosview for LoongArch
According to SMBIOS spec3.6, LoongArch information support has been added,
so this patch is submitted for display as information in smbiosview.
Reviewed-by: Chao Li <lichao@loongson.cn>

Update Support for LoongArch

---

StandaloneMmPkg/Core/Mmi.c

Currently, if a MMI handler returns an unexpected failure status code, ASSERT (FALSE) is used. It is more useful to use ASSERT_EFI_ERROR() which also outputs the status code value.

StandaloneMmPkg/Core: Output status in MMI handler assertion

---

OvmfPkg/ResetVector/Ia32/AmdSev.asm

The current support within the boot SNP CPUID table processing mistakenly swaps the ECX and EDX results. It does not have an effect at this time because current CPUID results checking does not check ECX or EDX. However, any future CPUID checks that need to check ECX or EDX may have erroneous behavior.
Fix the assembler code to save ECX and EDX to the proper locations.
Fixes: 34819f2caccb ("OvmfPkg/ResetVector: use SEV-SNP-validated CPUID values")
Reviewed-by: Michael Roth <michael.roth@amd.com>

OvmfPkg/ResetVector: Fix SNP CPUID table processing results for ECX/EDX

---

UefiCpuPkg/CpuDxeRiscV64/CpuDxe.c
UefiCpuPkg/CpuDxeRiscV64/CpuDxe.h

With CMO operations available for RISC-V, utilize them in CPU Architecture protocol.
Cc: Sunil VL <sunilvl@ventanamicro.com>

Pull RISC-V: UefiCpuPkg: Add cache operations support for Arch proto

---

MdePkg/MdeLibs.dsc.inc

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4675
Add library mapping for the SynchrnizationLib to MdeLibs.dsc.inc to resolve build failures in the FmpDevicePkg and NetworkPkg for missing library mapping.
The following email details why this was missed by EDK II CI
* https://edk2.groups.io/g/devel/message/115185
Local builds of all packages that use -D CONTINUOUS_INTEGRATION were performed to verify that this change resolves the missing library mapping.
Cc: Wei6 Xu <wei6.xu@intel.com>
Cc: Saloni Kasbekar <saloni.kasbekar@intel.com>
Cc: Zachary Clark-williams <zachary.clark-williams@intel.com>

MdePkg: Add SynchronizationLib to MdeLibs.dsc.inc

---

BaseTools/Source/Python/AutoGen/WorkspaceAutoGen.py
BaseTools/Source/Python/Workspace/DscBuildData.py

During the Incremental build GenerateByteArrayValue used to generate the ByteArrayValue even when there is no change in the PCD/VPDs. which is time consuming API based on the number of PCD/VPDs and SKU IDs.
The optimization is that GenerateByteArrayValue is used to store the StructuredPcdsData in a JSON file for each of the arch. and during the Incremental build this API will check, if there is any change in the Structured PCD/VPDs then rest of the flow remains the same. if there is no change then it will return the provious build data.
Flow:
during the 1st build StructuredPcdsData.json is not exists, StructuredPcdsData will be dumped to json file. and it will copy the output.txt as well.
Note: as the output.txt are different for different Arch, so it will be stored in the Arch folder. …

BaseTools: Optimize GenerateByteArrayValue and CollectPlatformGuids APIs

---

BaseTools/Source/Python/AutoGen/PlatformAutoGen.py

Currently when the platform has many SKUs then allskuset will be having so many duplicate. and while parsing the allskuset will take longer time while assigning Pcd.SkuInfoList.
This patch is to eliminate those duplicate entries to reduce the build time
Cc: Amy Chan <amy.chan@intel.com>
Cc: Sai Chaganty <rangasai.v.chaganty@intel.com>
Reviewed-by: Amy Chan <amy.chan@intel.com>

BaseTools: Remove Duplicate sets of SkuName and SkuId from allskuset

---

EmbeddedPkg/Library/PrePiMemoryAllocationLib/MemoryAllocationLib.c

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4668
This commit fixes the issue reported in the BZ4668. The EmbeddedPkg fails to compile with a compiler error generated due to invalid/illegal arithmetic operation on void pointers. It has been fixed by using explicit type conversion of the void pointer to UINTN.
Cc: Jayaprakash N <n.jayaprakash@intel.com>
Reviewed-by: Ard Biesheuvel <ardb+tianocore@kernel.org>

EmbeddedPkg: compiler error due to arithmetic operation on void pointer

---

ArmPlatformPkg/Library/PL031RealTimeClockLib/PL031RealTimeClockLib.c
EmbeddedPkg/Include/Library/RealTimeClockLib.h
EmbeddedPkg/RealTimeClockRuntimeDxe/RealTimeClock.c
MdeModulePkg/Core/RuntimeDxe/Runtime.c
MdeModulePkg/Core/RuntimeDxe/Runtime.h
MdeModulePkg/Universal/CapsuleRuntimeDxe/CapsuleService.c
MdeModulePkg/Universal/MonotonicCounterRuntimeDxe/MonotonicCounter.c
MdeModulePkg/Universal/Variable/RuntimeDxe/Variable.c
MdeModulePkg/Universal/Variable/RuntimeDxe/Variable.h
MdeModulePkg/Universal/Variable/RuntimeDxe/VariableSmmRuntimeDxe.c
MdePkg/Include/Library/UefiRuntimeLib.h
MdePkg/Include/Uefi/UefiSpec.h
MdePkg/Library/UefiRuntimeLib/RuntimeLib.c
OvmfPkg/Library/XenRealTimeClockLib/XenRealTimeClockLib.c

According to UEFI Spec 2.10 page 206, if any EFI_RUNTIME_SERVICES* calls
are not supported for use by the OS at runtime, an EFI_RT_PROPERTIES_TABLE
configuration table should be published describing which runtime services
are supported at runtime. So need to add EFI_UNSUPPORTED return for some
Runtime Service functions.
REF: UEFI spec 2.10 section 8 Services — Runtime Services
V3:
Update the commit message to align with the change for each package.
V2:
Update some Runtime Service functions header return on both C and H header files.
V1:
Add EFI_UNSUPPORTED return for some Runtime Service functions on UefiSpec.h file.
Signed-off-by: Suqiang Ren <[suqiangx.ren@intel.com](mailto:suqiangx.ren@intel.com)>
Cc: Michael D Kinney <[michael.d.kinney@intel.com](mailto:michael.d.kinney@intel.com)> …

Add EFI_UNSUPPORTED return for some Runtime Service functions

---

NetworkPkg/Dhcp6Dxe/Dhcp6Io.c
NetworkPkg/Dhcp6Dxe/Dhcp6Io.h
NetworkPkg/Dhcp6Dxe/Dhcp6Utility.c
NetworkPkg/SecurityFixes.yaml

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4673
This patch series corrects an additional security concern
found in Dhc6Dxe related to CVE-2023-45229. 
Additionally this fixes some issues on the mailing list
that were not pulled in before merging into Edk2.
Cc: Saloni Kasbekar <[saloni.kasbekar@intel.com](mailto:saloni.kasbekar@intel.com)>
Cc: Zachary Clark-williams <[zachary.clark-williams@intel.com](mailto:zachary.clark-williams@intel.com)>
Cc: Andrew Fish <[afish@apple.com](mailto:afish@apple.com)>
Cc: Leif Lindholm <[quic_llindhol@quicinc.com](mailto:quic_llindhol@quicinc.com)>
Cc: Michael D Kinney <[michael.d.kinney@intel.com](mailto:michael.d.kinney@intel.com)>
Signed-off-by: Doug Flick [MSFT] <[doug.edk2@gmail.com](mailto:doug.edk2@gmail.com)>

Bug 4673 network pkg dhcp6 dxe advertise message parsing

---

UefiCpuPkg/PiSmmCpuDxeSmm/PiSmmCpuDxeSmm.c

Ref: https://bugzilla.tianocore.org/show_bug.cgi?id=4682
Commit 725acd0b9cc0 ("UefiCpuPkg: Avoid assuming only one smmbasehob",
2023-12-12) introduced a NULL pointer dereference to PiSmmCpuDxeSmm on
such platforms that do not produce the "gSmmBaseHobGuid" GUID HOB at
all.
Please see the multi-step analysis in the following thread:
[edk2-devel] [PATCH 1/1] OvmfPkg/QemuVideoDxe: purge VbeShim
https://edk2.groups.io/g/devel/message/115377
message-id: <[20240213085925.687848-1-kraxel@redhat.com](mailto:20240213085925.687848-1-kraxel@redhat.com)>
This issue needs to be fixed for edk2-stable202402.
Cc: Dun Tan <[dun.tan@intel.com](mailto:dun.tan@intel.com)>
Cc: Gerd Hoffmann <[kraxel@redhat.com](mailto:kraxel@redhat.com)>
Cc: Liming Gao …

Bug 4682 uefi cpu pkg pi smm cpu dxe smm fix null deref

---

UefiPayloadPkg/Tools/MkFitImage.py
UefiPayloadPkg/UefiPayloadPkg.ci.yaml
UefiPayloadPkg/UefiPayloadPkg.dsc
UefiPayloadPkg/UniversalPayloadBuild.py

Current implementation makes assumptions about arch it will be built for. Need to make it more generic to add follow up support for RISCV. Right now it does not build for RV until relevant dsc file is available.

UefiPayloadPkg: Make UPL build script arch agnostic

---

OvmfPkg/AmdSev/AmdSevX64.dsc
OvmfPkg/AmdSev/AmdSevX64.fdf
OvmfPkg/Include/Dsc/ShellComponents.dsc.inc
OvmfPkg/Include/Dsc/ShellLibs.dsc.inc
OvmfPkg/Include/Fdf/ShellDxe.fdf.inc
OvmfPkg/IntelTdx/IntelTdxX64.dsc
OvmfPkg/IntelTdx/IntelTdxX64.fdf
OvmfPkg/Microvm/MicrovmX64.dsc
OvmfPkg/Microvm/MicrovmX64.fdf
OvmfPkg/OvmfPkgIa32.dsc
OvmfPkg/OvmfPkgIa32.fdf
OvmfPkg/OvmfPkgIa32X64.dsc
OvmfPkg/OvmfPkgIa32X64.fdf
OvmfPkg/OvmfPkgX64.dsc
OvmfPkg/OvmfPkgX64.fdf
OvmfPkg/PlatformCI/PlatformBuildLib.py

https://edk2.groups.io/g/devel/message/115782
msgid `<20240222101358.67818-1-kraxel@redhat.com>`
~~~
- Create include files to reduce duplication.
- Fix varpolicy command.
- Little CI tweak.
v3:
- pick up review and ack tags.
- no functional changes.
v2:
- do not move ShellCEntryLib to include file.
- refine network config conditionals.
- improve some commit messages.
- add patch to drop the shell from secure boot builds.
Gerd Hoffmann (12):
OvmfPkg: add ShellComponents.dsc.inc
OvmfPkg: add ShellLibs.dsc.inc
OvmfPkg: add ShellDxe.fdf.inc
OvmfPkg: Shell*.inc: allow building without network support
OvmfPkg: ShellDxe.fdf.inc: add VariablePolicyDynamicCommand to FV
OvmfPkg: switch OvmfPkgIa32 to new shell include files
OvmfPkg: switch OvmfPkgIa32X64 to new shell include files
OvmfPkg: switch …

[PATCH v3 00/12] OvmfPkg: tweak shell builds -- push

---

ArmVirtPkg/XenAcpiPlatformDxe/XenAcpiPlatformDxe.c

https://edk2.groups.io/g/devel/message/115381
msgid `<881dd0a2558ecbdfa02c844722d8a1103ab97ab3.camel@infradead.org>`
~~~
From: David Woodhouse <dwmw@amazon.co.uk>
The FACS may still exist when the reduced hardware flag is set in FADT;
it is optional. Since it contains the hardware signature field which
indicates that a hibernated system should boot cleanly instead of
attempting to resume, a platform may choose to expose it. Propagate it
correctly.
Also avoid a NULL pointer dereference if the platform doesn't provide
a DSDT.
Signed-off-by: David Woodhouse <dwmw@amazon.co.uk>
---
.../XenAcpiPlatformDxe/XenAcpiPlatformDxe.c   | 37 +++++++++++++++----
1 file changed, 29 insertions(+), 8 deletions(-)
~~~

[PATCH] ArmVirtPkg/XenAcpiPlatformDxe: Install FACS table from DT -- push

---

MdePkg/Include/Protocol/SimpleTextIn.h
MdePkg/Include/Protocol/SimpleTextInEx.h
MdePkg/Include/Uefi/UefiSpec.h

1. Refer to Uefi spec 2.10 section 4.3.1, Updated the comments of EFI_SYSTEM_TABLE to satisfy ConIn/ConOut/StdErr requirements.
2. Refer to Uefi spec 2.10 section 13.3.3, Add a new retval EFI_UNSUPPORTED to EFI_SIMPLE_TEXT_INPUT_EX_PROTOCOL.ReadKeyStrokeEx and EFI_SIMPLE_TEXT_INPUT_PROTOCOL.ReadKeyStroke().

MdePkg Updated the comments of EFI_SYSTEM_TABLE and ReadKeyStroke

---

UefiCpuPkg/Library/MpInitLib/MpLib.c
UefiCpuPkg/Library/MpInitLib/MpLib.h
UefiCpuPkg/Library/MpInitLib/PeiMpLib.c

https://edk2.groups.io/g/devel/message/115826
msgid `<20240222160106.686484-1-kraxel@redhat.com>`
~~~
Needed to boot guests with thousands of vcpus.
v3:
- refine comments and commit messages.
- fix MaxCpusPerHob calculation.
- pick up review tags.
- add patch to speed up GetBspNumber a bit.
v2:
- rework HOB loops for better performance: O(n) instead of O(n^2).
Gerd Hoffmann (6):
UefiCpuPkg/MpInitLib: Add support for multiple HOBs to GetMpHandOffHob
UefiCpuPkg/MpInitLib: Add support for multiple HOBs to GetBspNumber()
UefiCpuPkg/MpInitLib: Add support for multiple HOBs to
SwitchApContext()
UefiCpuPkg/MpInitLib: Add support for multiple HOBs to
MpInitLibInitialize
UefiCpuPkg/MpInitLib: Add support for multiple HOBs to SaveCpuMpData()
UefiCpuPkg/MpInitLib: return early in GetBspNumber() …

[PATCH v3 0/6] UefiCpuPkg/MpInitLib: Add support for multiple MP_HAND_OFF HOBs -- push

---

MdeModulePkg/Library/TraceHubDebugSysTLib/BaseTraceHubDebugSysTLib.c
MdeModulePkg/Library/TraceHubDebugSysTLib/DxeSmmTraceHubDebugSysTLib.c
MdeModulePkg/Library/TraceHubDebugSysTLib/InternalTraceHubApi.c

Resolves a new CodeQL error due to the value being incremented in the
loop being a narrower type than the variable it is being compared
against.
The variable is changed to a UINT32 type so it has the same width as
the type it is being compared against.
Issue explanation: In a loop condition, comparison of a value of a
narrow type with a value of a wide type may result in unexpected
behavior if the wider value is sufficiently large (or small). This
is because the narrower value may overflow. This can lead to an
infinite loop.
Cc: Prakashan Krishnadas Veliyathuparambil <krishnadas.veliyathuparambil.prakashan@intel.com>
Cc: K N Karthik <karthik.k.n@intel.com>
Signed-off-by: Michael Kubacki …

MdeModulePkg/TraceHubDebugSysTLib: Use wider type for loop comparisons

---

OvmfPkg/PlatformPei/MemDetect.c

https://edk2.groups.io/g/devel/message/115439
msgid `<20240214104504.2931339-1-kraxel@redhat.com>`
~~~
v3:
- squash one patch #4 chunk into patch #1
- more format string fixes.
- fine-tune page table calculation.
- misc small tweaks.
v2:
- rewrite page table calculation, rewrite comment (Laszlo)
- add warning message if PEI memory is tight.
- format string fixes.
- misc small tweaks.
Gerd Hoffmann (4):
OvmfPkg/PlatformPei: log a warning when memory is tight
OvmfPkg/PlatformPei: consider AP stacks for pei memory cap
OvmfPkg/PlatformPei: rewrite page table calculation
OvmfPkg/PlatformPei: log pei memory cap details
OvmfPkg/PlatformPei/MemDetect.c | 103 +++++++++++++++++++++++++-------
1 file changed, 80 insertions(+), 23 deletions(-)
~~~

[PATCH v3 0/4] OvmfPkg/PlatformPei: scaleability fixes for GetPeiMemoryCap() -- push

---

EmbeddedPkg/Scripts/LauterbachT32/EfiLoadDxe.cmm
EmbeddedPkg/Scripts/LauterbachT32/EfiProcessPeImage.cmm
EmbeddedPkg/Scripts/LauterbachT32/Readme.md

There have been many changes since EfiLoadDxe.cmm was last updated in
2011. The EFI_SYSTEM_TABLE can no longer be found by scanning memory on 4KB boundaries, so require users pass in its address instead. Update various offsets so that the debug information can be found and loaded with a recent version of TRACE32.

EmbeddedPkg/Scripts/LauterbachT32: Fix EfiLoadDxe.cmm

---

BaseTools/Source/Python/Workspace/DscBuildData.py

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4666
This commit fixes the issue reported through BZ4666. The Syntax warning related to invalid escape sequence for \C is seen on Windows OS based builds of edk2 sources. On Windows the path seperator needs to prefixed with \ so essentially we need to use \\ as path seperator.
Cc: Jayaprakash N <n.jayaprakash@intel.com>

BaseTools: Syntax warning invalid escape sequence \C

---

MdeModulePkg/Core/Pei/Dispatcher/Dispatcher.c
MdeModulePkg/Core/PiSmmCore/Smi.c
OvmfPkg/ResetVector/Ia32/AmdSev.asm
OvmfPkg/ResetVector/Ia32/IntelTdx.asm
OvmfPkg/ResetVector/Ia32/PageTables64.asm
OvmfPkg/ResetVector/ResetVector.inf
OvmfPkg/ResetVector/ResetVector.nasmb
StandaloneMmPkg/Core/Mmi.c
UefiCpuPkg/Library/CpuPageTableLib/CpuPageTableMap.c

* [PATCH v2] UefiCpuPkg/CpuPageTableLib: Fix IN OUT parameters marked as IN
msgid `<20240222023922.29275-1-jianfeng.zhou@intel.com>`
https://edk2.groups.io/g/devel/message/115871
* [PATCH] UefiCpuPkg/CpuPageTableLib: qualify page table accesses as volatile
msgid `<20240301025447.41170-1-jianfeng.zhou@intel.com>`
https://edk2.groups.io/g/devel/message/116230
* [PATCH v3 0/4] Support to unregister SMI handler inside SMI handler
msgid `<20240301030133.628-1-zhiguang.liu@intel.com>`
https://edk2.groups.io/g/devel/message/116202
* [PATCH v1] MdeModulePkg/Core/Pei: Improve the copy performance
msgid `<20240301071147.519-1-zhihao.li@intel.com>`
https://edk2.groups.io/g/devel/message/116212
https://bugzilla.tianocore.org/show_bug.cgi?id=4697
* [PATCH v2 00/10] OvmfPkg/ResetVector: cleanup and add …

Queue 2024-Mar-01

---

UefiPayloadPkg/UniversalPayloadBuild.py

After 11ad164bcea6b0ed3628d merge,
ELF format API won't meet backward requirement.

UefiPayloadPkg: UPL arch backward support ELF

---

BaseTools/Source/Python/GenFds/FfsInfStatement.py

Currently, if an INF path is an absolute path on Linux (begins with
"/"), the "/" character will be removed. If the path is an absolute
system path, this creates an invalid path.
An example of when this may be an issue is in external dependencies
where an INF is within the external dependency, the `set_build_var`
flag is set, and DSC files refer to files by its build variable
(e.g. `$(SHARED_BINARIES)/Module.inf`). INFs in a binary distribution
like this example may contain a [Binaries] section and refer to
different section files that can be used by a platform to compose an
FFS file. For example, the PE32 (.efi) and DEPEX (.depex) files.
In this case, `$(SHARED_BINARIES)` will be an absolute path to the
ext dep directory and `FfsInfStatement.__InfParse__` will remove the
leading "/" …

BaseTools/GenFds: Resolve absolute workspace INF paths

---

.github/workflows/codeql.yml

Currently CodeQL runs have the following warnings:
```
Node.js 16 actions are deprecated. Please update the following
actions to use Node.js 20: actions/setup-python@v4,
actions/upload-artifact@v3, actions/cache@v3. For more information
see:
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```
And:
```
CodeQL Action v2 will be deprecated on December 5th, 2024. Please
update all occurrences of the CodeQL Action in your workflow files
to v3. For more information, see:
https://github.blog/changelog/2024-01-12-code-scanning-deprecation-of-codeql-action-v2/
```
The first is resolved by updating the actions to the latest versions
that were released to use Node.js 20. The second is specifically
referring to the codeql-action/upload-sarif action …

.github/workflows/codeql.yml: Update actions being deprecated

---

UefiPayloadPkg/UefiPayloadPkg.dsc

Current DSC files contains a lot of files which are specific to X86 arch. Need to move around files under arch specific sections.

UefiPayloadPkg: Make Dsc accomodative of other archs

---

EmbeddedPkg/Drivers/NonCoherentIoMmuDxe/NonCoherentIoMmuDxe.c

NonCoherentIoMmuSetAttribute() does nothing except return EFI_UNSUPPORTED. This was fine when it was introduced, but now, the PCI bus driver will fail a PCI I/O Map() operation if the call to SetAttributes() fails.
So return EFI_SUCCESS instead.

EmbeddedPkg/NonCoherentIoMmuDxe: Make SetAttributes always succeed

---

MdeModulePkg/Bus/Ata/AtaBusDxe/AtaBus.c
MdeModulePkg/Bus/Ata/AtaBusDxe/AtaBus.h
MdeModulePkg/Bus/Pci/NvmExpressDxe/NvmExpressBlockIo.c
MdeModulePkg/Bus/Pci/NvmExpressDxe/NvmExpressBlockIo.h
MdeModulePkg/Bus/Scsi/ScsiDiskDxe/ScsiDisk.c
MdeModulePkg/Bus/Scsi/ScsiDiskDxe/ScsiDisk.h
MdeModulePkg/Bus/Sd/EmmcDxe/EmmcBlockIo.c
MdeModulePkg/Bus/Sd/EmmcDxe/EmmcBlockIo.h
MdePkg/Include/Protocol/StorageSecurityCommand.h
SecurityPkg/Tcg/Opal/OpalPassword/OpalPasswordPei.c

Refer to Uefi spec 2.10 section 13.14, update the parameter 'MediaId'
description for EFI_STORAGE_SECURITY_COMMAND_PROTOCOL function 
ReceiveData and SendData.
V4:
Split patch so there is one patch per package
V3:
Add maintainer to CC list.
V2:
Update some functions description in C and H header files in MdeModulePkg and SecurityPkg.
V1:
update the parameter description in MdePkg/Include/Protocol/StorageSecurityCommand
Signed-off-by: Qingyu Shang <qingyu.shang@intel.com>

Bug xxx storage security command uefi210 v3

---

IntelFsp2WrapperPkg/Library/BaseFspMeasurementLib/FspMeasurementLib.c

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4700
TpmMeasureAndLogDataWithFlags() computes the measure the code and
log it into PCR 0. TpmMeasureAndLogData() computes the hash for the
configuration. The same "Status" variable is used to store the return
values for both of the functions. There is no error handling if
TpmMeasureAndLogDataWithFlags() returns an error Status.
Fix the issue by adding error handling for TpmMeasureAndLogDataWithFlags().

IntelFsp2WrapperPkg: Error handling of TpmMeasureAndLogDataWithFlags()

---

IntelFsp2WrapperPkg/FspmWrapperPeim/FspmWrapperPeim.c

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4701
The error handling of FspmWrapperInit() is limited to ASSERT
statements only, which only works in debug builds, but not in
release builds.
Fix the issue by enhancing the error handling of FspmWrapperInit()
to cover both debug builds and release builds.

IntelFsp2WrapperPkg: Error handling of FspmWrapperInit()

---

MdePkg/Library/BaseLib/X64/TdVmcall.nasm
OvmfPkg/Library/CcExitLib/X64/TdVmcallCpuid.nasm
OvmfPkg/TdxDxe/X64/ApRunLoop.nasm

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4696
According to section 2.4.1 of [GHCI] spec,
RBP register is usually used as a frame pointer according to the C language calling convention. 
The software should not use RBP as an input/output parameter and should clear BIT5 (RBP) in
the GPR mask in RCX.
Reference:
[GHCI]: TDX Guest-Host-Communication Interface v1.5
https://cdrdv2.intel.com/v1/dl/getContent/726792
Cc: Isaku …

 OvmfPkg: Update TDVMCALL to avoid leaking secrets to the VMM

---

MdeModulePkg/Bus/Pci/XhciDxe/XhciSched.c
MdeModulePkg/Bus/Pci/XhciPei/XhciSched.c

REF:https://bugzilla.tianocore.org/show_bug.cgi?id=4560
Commit f36e1ec1f0a5fd3be84913e09181d7813444b620 had fixed the DXE_ASSERT caused by the TRB size round up from 16 to 64 for most cases.
However, there is a remaining case that the TRB size is also rounded up during setting TR dequeue pointer that would trigger DXE_ASSERT.
This patch sets the alignment flag to FALSE in XhcSetTrDequeuePointer to fix this issue as well.
Cc: Gao Cheng <gao.cheng@intel.com>

MdeModulePkg/Xhci: Skip another size round up for TRB address

---

MdePkg/Include/Guid/DeviceAuthentication.h
MdePkg/MdePkg.dec

Signed-off-by: Wenxing Hou <wenxing.hou@intel.com>
Wenxing Hou (2):
MdePkg: Add UEFI 2.10 DeviceAuthentication
MdePkg: Add gEfiDeviceSignatureDatabaseGuid to dec
MdePkg/Include/Guid/DeviceAuthentication.h | 61 ++++++++++++++++++++++
MdePkg/MdePkg.dec                          |  8 ++-
2 files changed, 68 insertions(+), 1 deletion(-)
create mode 100644 MdePkg/Include/Guid/DeviceAuthentication.h

Add UEFI 2.10 DeviceAuthentication and GUID

---

MdeModulePkg/Core/Dxe/Misc/MemoryProtection.c
MdeModulePkg/Library/ImagePropertiesRecordLib/ImagePropertiesRecordLib.c

ImagePropertiesRecordLib is currently creating Image Records that
are not accurate. It is setting the CodeSegmentSize to be the size
of the raw data in the image file, however, when the image is
loaded into memory, the raw data size is aligned to the
section alignment. This caused the memory attributes table to
have incorrect entries for systems, like ARM64, where the section
alignment is not 4k for all modules.
In fixing this, I noticed that MemoryProtection.c is using its own
version of image record creation where this logic was actually
correct. ImagePropertiesRecordLib was created to consolidate the
logic around creating and managing image records, so this patchset
also updates MemoryProtection.c to use ImagePropertiesRecordsLib
after making a few small adjustments to ensure the same …

MdeModulePkg: ImagePropertiesRecordLib Fixes

---

SecurityPkg/VariableAuthenticated/SecureBootConfigDxe/SecureBootConfigImpl.c

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4713
In UEFI_Spec_2_10_Aug29.pdf page 1694 section 35.5.4 for EFI_BROWSER_ACTION_FORM_OPEN:
NOTE: EFI_FORM_BROWSER2_PROTOCOL.BrowserCallback() cannot be used with this browser action because question values have not been retrieved yet.
So should not call HiiGetBrowserData() and HiiSetBrowserData() in FORM_OPEN call back function.
Now call SecureBootExtractConfigFromVariable() and update IfrNvData->ListCount to save the change to EFI variable, then HII use EFI variable to control the UI.
Cc: Felix Polyudov <Felixp@ami.com>
Reviewed-by: Felix Polyudov <Felixp@ami.com>
Acked-by: Jiewen Yao …

SecurityPkg/SecureBootConfigDxe: Update UI according to UEFI spec

---

MdePkg/MdePkg.dec
OvmfPkg/RiscVVirt/RiscVVirt.dsc.inc
UefiCpuPkg/Library/BaseRiscVMmuLib/BaseRiscVMmuLib.c
UefiCpuPkg/Library/BaseRiscVMmuLib/BaseRiscVMmuLib.inf

This series adds support for RISC-V Svpbmt extension.                                                                                                                                                       
The GCD EFI_MEMORY_UC and EFI_MEMORY_WC attributes will                                                                                                                                                     
be mapped to IO and NC mode defined in PBMT field.

Pull: RISC-V: Support Svpbmt extension 

---

MdeModulePkg/MdeModulePkg.dec
MdeModulePkg/MdeModulePkg.uni
MdeModulePkg/Universal/Acpi/AcpiTableDxe/AcpiTableDxe.inf
MdeModulePkg/Universal/Acpi/AcpiTableDxe/AcpiTableProtocol.c

UEFI spec defined ACPI Tables at boot time can be contained in memory of type EfiACPIReclaimMemory or EfiAcpiMemoryNVS, although InstallAcpiTable with AcpiTableProtocol will only allocate memory with type EfiACPIReclaimMemory (Except FACS).
This patch provides an optional method controlled by PCD to avoid using EfiACPIReclaimMemory, by setting the PCD PcdNoACPIReclaimMemory to TRUE, all ACPI allocated memory will use EfiAcpiMemoryNVS instead.
Cc: Liu Yun <yun.y.liu@intel.com>
Reviewed-by: Zhiguang Liu …

MdeModulePkg/AcpiTableDxe: PCD switch to avoid using ACPI reclaim memory

---

MdeModulePkg/Universal/Acpi/AcpiTableDxe/AcpiTableProtocol.c

As per ACPI Spec 6.5+ Table 5-9 if xDSDT is available, it should be used first. Handle required flow when xDSDT is absent or present.
Test: Tested on RISCV64 Qemu platform with xDSDT and booted to linux kernel.
Cc: Pedro Falcato <pedro.falcato@gmail.com>
Cc: devel@edk2.groups.io
Acked-by: Chasel Chiu <chasel.chiu@...>

MdeModulePkg/AcpiTableDxe: Prefer xDSDT over DSDT when installing tables

---

BaseTools/Source/Python/GenFds/FfsInfStatement.py
BaseTools/Source/Python/Workspace/WorkspaceCommon.py

When collecting the required library instances for modules and libraries, included libraries will be recursed to ensure the module is built with all the libraries directly linked to it and indirectly linked to it via included libraries.
Using the following scenario as an example:
[LibraryClasses.common.DXE_CORE]
NULL|Path/To/Library1.inf // Includes DebugLib
[LibraryClasses.common.DXE_DRIVER]
NULL|Path/To/Library2.inf // Includes DebugLib
[LibraryClasses.common.DXE_CORE, LibraryClasses.common.DXE_DRIVER]
DebugLib|MdePkg/Library/BaseDebugLibSerialPort/BaseDebugLibSerialPort.inf
[Components]
MdeModulePkg/Core/Dxe/DxeMain.inf // Includes DebugLib
The DXE_CORE NULL library will be assigned a fake library class like NULL1 and the DXE_DRIVER will be assigned NULL2. The recursion logic will see …

BaseTools: Don't Recurse NULL Includes When Collecting Lib Instances

---

SecurityPkg/Tcg/Opal/OpalPassword/OpalDriver.h
SecurityPkg/Tcg/Opal/OpalPassword/OpalHii.c
SecurityPkg/Tcg/Opal/OpalPassword/OpalHiiFormValues.h
SecurityPkg/Tcg/Opal/OpalPassword/OpalPasswordDxe.inf
SecurityPkg/Tcg/Opal/OpalPassword/OpalPasswordForm.vfr

For opalHii current design, it will display all NVME disks when the user enters TCG Drive Management dynamically.
Also, the related disk info form will be created along with the disks.
These actions will call get/set browser to refresh the display, which is not allowed in ACTION_FORM_OPEN callback function.
To meet UEFI 2.9 spec, a latency issue will be observed if the browser callback action changes from ACTION_FORM_OPEN to ACTION_RETRIEVE.
The NVNE disks will not be displayed when the user enters the formset at the first time. Revisit the formset can see the update.
So need to force reparsing the IFR binary when RETRIEVE.
v2:
Format code with Uncrustify.
v3:
Code refine based on comments from Dandan and Tina.
v4:
Split solution into two patches as different purpose.
v5:
Update commit …

SecurityPkg/OpalPasswordDxe: Update according to UEFI spec

---

BaseTools/Source/Python/FMMT/FMMT.py

Ref to https://docs.python.org/3/whatsnew/3.12.html A backslash-character pair that is not a valid
escape sequence now generates

BaseTools/Fmmt.py: Python 3.12 support

---

OvmfPkg/VirtHstiDxe/VirtHstiDxe.c
OvmfPkg/VirtHstiDxe/VirtHstiDxe.inf

The VirtHstiDxe does not work in confidential guests.  There also isn't anything we can reasonably test, neither flash storage nor SMM mode will be used in that case.  So just skip driver load when running in a confidential guest.
Fixes: 506740982bba ("OvmfPkg/VirtHstiDxe: add code flash check")
Tested-by: Srikanth Aithal <sraithal@amd.com>

OvmfPkg/VirtHstiDxe: do not load driver in confidential guests

---

BaseTools/Scripts/GetUtcDateTime.py

Ref to https://docs.python.org/3/whatsnew/3.12.html utcnow() and utcfromtimestamp() are deprecated
Prevent use it cause build error.
Cc: Liming Gao <gaoliming@byosoft.com.cn> (https://edk2.groups.io/g/devel/message/118145?p=%2C%2C%2C20%2C0%2C0%2C0%3A%3Arecentpostdate%2Fsticky%2C%2CBaseTools%2FGetUtcDateTime.py+3.12+support%2C20%2C2%2C0%2C105690657)

BaseTools/GetUtcDateTime.py: Python 3.12 support

---

MdePkg/Include/IndustryStandard/Cxl.h
MdePkg/Include/IndustryStandard/Cxl30.h

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4516
1) Add CXL 3.0 header file to comply with CXL 3.0 specification 2) CXL 3.0 header will embed Cxl20.h
3) Updated Cxl.h to point to 3.0 header file
Cc: Chris Li <chrisli@os.amperecomputing.com>

MdePkg: Add Cxl30.h into IndustryStandard

---

UefiCpuPkg/Library/CpuCommonFeaturesLib/MachineCheck.c

ProcessorNumber 0 is not always BSP. Debug message based on 0 of ProcessorNumber is incorrect.
This patch is to clean the debug message in LmceSupport directly.
Cc: Zeng Star <star.zeng@intel.com>
Reviewed-by: Zeng Star <star.zeng@intel.com>

UefiCpuPkg/Library: Cleanup debug message in LmceSupport

---

IntelFsp2Pkg/Tools/PatchFv.py

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4762
Map file generating 8 byte address offset is not matched with the pattern defined in patchFv tool resulting build error.
Reviewed-by: Ashraf Ali S <ashraf.ali.s@intel.com>

IntelFsp2Pkg/PatchFv.py: FIX for GCC 32BIT build error

---

MdePkg/Include/IndustryStandard/UefiTcgPlatform.h
OvmfPkg/Tcg/TdTcg2Dxe/TdTcg2Dxe.c
SecurityPkg/Tcg/Tcg2Dxe/Tcg2Dxe.c

In December 2023, the TCG published the PC Client Platform Firmware
Profile version 1.06 revision 52. This revision includes a new event
type for NIST SP 800-155 recommended signed BIOS reference measurements.
The new type allows for the event log auditor to find local or remote
copies of the signed reference measurements.
Supporting this new event type eases the process of distributing signed
reference measurements since the machine can now simply report where
they can be found in a standard way.
Changes since v3:
- Fixed build error from 1 too many ')'s.
- Fixed formatting for uncrustify.
Changes since v2:
- Removed errant spacing.
Changes since v1:
- MdePkg defines TCG_Sp800_155_PlatformId_Event3 instead of adding a
comment about Event3 to Event2.
Cc: Michael D Kinney …

TCG_Sp800_155_PlatformId_Event3 support

---

MdeModulePkg/Bus/Pci/XhciDxe/Xhci.c
MdeModulePkg/Bus/Pci/XhciDxe/XhciSched.c
MdeModulePkg/Bus/Pci/XhciDxe/XhciSched.h

https://bugzilla.tianocore.org/show_bug.cgi?id=4556
Based on XHCI spec 4.8.3, software should do the
reset endpoint while USB Transaction occur.
Add the error code for USB Transaction error
since UEFI spec don't have the related definition.
Cc: Ray Ni                  <ray.ni@intel.com>
Cc: Liming Gao              <gaoliming@byosoft.com.cn>
Cc: Krzysztof Lewandowski   <krzysztof.lewandowski@intel.com>
Cc: Jenny Huang             <jenny.huang@intel.com>
Cc: More Shih               <more.shih@intel.com>
Reviewed-by: Krzysztof Lewandowski <krzysztof.lewandowski@intel.com>

MdeModulePkg/XhciDxe: Reset endpoint while USB Transaction error

---

MdeModulePkg/Bus/Pci/XhciDxe/Xhci.h
MdeModulePkg/Bus/Pci/XhciDxe/XhciDxe.inf
MdeModulePkg/Bus/Pci/XhciDxe/XhciReg.c
MdeModulePkg/MdeModulePkg.dec

https://bugzilla.tianocore.org/show_bug.cgi?id=4727
Recently some of XHCI host controllers require to have extra 1ms delay before accessing any MMIO register during reset. PHY transition from P3 to P0 can take around 1.3ms and the xHCI reset can take around 1.5ms. Add PCD to control the delay, the default is 2 ms.
Cc: Ray Ni                   <ray.ni@intel.com>
Cc: Liming Gao               <gaoliming@byosoft.com.cn>
Cc: Krzysztof Lewandowski    <krzysztof.lewandowski@intel.com>
Cc: Jenny Huang              <jenny.huang@intel.com>
Cc: More Shih                <more.shih@intel.com>
Cc: Ian Chiu                 <ian.chiu@intel.com>
Reviewed-by: Krzysztof Lewandowski <krzysztof.lewandowski@intel.com>

MdeModulePkg/XhciDxe: Add PCD for the delay of HCRST

---

UefiCpuPkg/PiSmmCpuDxeSmm/PiSmmCpuDxeSmm.c
UefiCpuPkg/PiSmmCpuDxeSmm/PiSmmCpuDxeSmm.inf

If gMpInformation2HobGuid HOB is NULL,
then fall back to an older way of collecting
CPU information from the MP services library.

UefiCpuPkg/PiSmmCpuDxeSmm: Handle the NULL gMpInformation2HobGuid

---

UefiCpuPkg/Library/RegisterCpuFeaturesLib/DxeRegisterCpuFeaturesLib.c
UefiCpuPkg/Library/RegisterCpuFeaturesLib/PeiRegisterCpuFeaturesLib.c

Intel has some features need to use processor extended information under CPU feature InitializeFunc(), so add code to support it: This patch is to add CPU_V2_EXTENDED_TOPOLOGY to get processor extended info.
Cc: Zeng Star <star.zeng@intel.com>

UefiCpuPkg/Library: Support to get processor extended info

---

MdePkg/Include/IndustryStandard/SerialPortConsoleRedirectionTable.h

REF:https://bugzilla.tianocore.org/show_bug.cgi?id=4656
In SPCR table, 4 structure members have been added newly as per SPCR table Revision 4, which has to be added in
MdePkg/Include/IndustryStandard/SerialPortConsoleRedirectionTable.h.
Signed-off-by: Praveen Sankar N <praveensankarn@ami.com>
Cc: Felix Polyudov <Felixp@ami.com>
Cc: Srinivasan Mani <srinivasanm@ami.com>
Cc: Sundaresan S <sundaresans@ami.com>
Cc: Rabisha R <rabishar@ami.com>

MdePkg: Updated SpcrTable structure for Revision_4

---

DynamicTablesPkg/Include/Library/AmlLib/AmlLib.h
DynamicTablesPkg/Library/Common/AmlLib/CodeGen/AmlCodeGen.c

Adds an AmlAddIntegerToNamedPackage() API to generate AML code, which adds an integer value to the package node.

DynamicTablesPkg: Adds integer to the AML package node

---

MdePkg/MdeLibs.dsc.inc

MdeLibs.dsc.inc included some default libraries provided by MdePkg. Platform can include MdeLibs.dsc.inc file to avoid some potential incompatible changes to platform dsc file in future.
Cc: Yuanhao Xie <yuanhao.xie@intel.com>
Reviewed-By: Zhiguang Liu <zhiguang.liu@intel.com>

MdePkg: Add MmUnblockMemoryLib to MdeLibs.dsc

---

MdePkg/Library/BaseLib/AArch64/SetJumpLongJump.S
MdePkg/Library/BaseLib/AArch64/SetJumpLongJump.asm

Declare InternalAssertJumpBuffer as EXTERN
Reviewed-by: levi.yun <yeoreum.yun@arm.com>

MdePkg/BaseLib: Fix AARCH64 compilation error

---

MdeModulePkg/Universal/Acpi/FirmwarePerformanceDataTablePei/FirmwarePerformancePei.c

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4677
Attacker able to modify physical memory and ResumeCount. System will crash/DoS when ResumeCount reaches its MAX_UINT32.

MdeModulePkg: Potential UINT32 overflow in S3 ResumeCount

---

UefiCpuPkg/Library/MpInitLib/MpLib.c

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4778
MPInitlib have wrong expectation that BSP index should always be 0 in MpInitLibInitialize(), SwitchBsp(),ApWakeupFunction(). That will cause the data mismatch, if the initial BSP is not 0.

UefiCpuPkg/MpLib:Do not assume BSP is #0.

---

BaseTools/Scripts/PatchCheck.py

The commit message format requirements have been updated for GitHub PR based code reviews and no longer required Cc: tags for the maintainers and reviewers.  Remove the Cc: tag check from PatchCheck.py.

BaseTools/Scripts: Remove Cc: tag check from PatchCheck.py

---

.github/pull_request_template.md
.github/workflows/pr-labeler.yml
.github/workflows/pr-labeler/regex.yml

Adds a pull request template with important information to note in
the PR description and guidance on how to classify the PR.
A simple GitHub action is present that applies three labels based
on the boxes checked in the PR template:
- `impact:breaking-change`
- `impact:security`
- `impact:testing`
These provide several benefits.
1. Bring attention to the impact of the PR both for reviewers and
consumers that reference the PR in the future during debug or integration.
3. Allow automated tools like those that create release notes to
be able to highlight important changes.
5. Similarly, to allow PR searches to conditionalize the search on
PRs with these tags present.

.github: Add PR template

---

EmulatorPkg/Unix/Host/Gasket.h

GasketSecSetTime is EMU_SET_TIME and returns EFI_STATUS.  Fix the
declaration accordingly.  Fixes build error with gcc 14.
/home/kraxel/projects/edk2/EmulatorPkg/Unix/Host/EmuThunk.c:429:3: error: initialization of ‘EFI_STATUS (__attribute__((ms_abi)) *)(EFI_TIME *)’ {aka ‘long long unsigned int (__attribute__((ms_abi)) *)(EFI_TIME *)’} from incompatible pointer type ‘void (__attribute__((ms_abi)) *)(EFI_TIME *)’ [-Wincompatible-pointer-types]
429 |   GasketSecSetTime,
|   ^~~~~~~~~~~~~~~~

EmulatorPkg: fix build error.

---

NetworkPkg/TcpDxe/TcpDriver.c

Pkg-Module: NetworkPkg TcpDxe
This bug fix is based on the following commit "NetworkPkg TcpDxe: SECURITY PATCH"
REF: https://github.com/tianocore/edk2/commit/1904a64bcc18199738e5be183d28887ac5d837d7
Issue Description:
An "Invalid handle" error was detected during runtime when attempting to destroy a child instance of the hashing protocol. The problematic code segment was:
NetworkPkg\TcpDxe\TcpDriver.c
Status = Hash2ServiceBinding->DestroyChild(Hash2ServiceBinding, ​&mHash2ServiceHandle);
Root Cause Analysis:
The root cause of the error was the passing of an incorrect parameter type, a pointer to an EFI_HANDLE instead of an EFI_HANDLE itself, to the DestroyChild function. This mismatch resulted in the function receiving an invalid handle.
Implemented Solution:
To resolve this issue, the …

NetworkPkg TcpDxe: Fixed system stuck on PXE boot flow in iPXE environment

---

CryptoPkg/Library/OpensslLib/OpensslStub/uefiprov.c

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4739
AES256-SHA256 is a Tls1.2 suite we need to support, add it to deflt_ciphers in OpensslStub.
- Examples: Crypto algorithm change or buffer …

CryptoPkg: Add support for aes128-sha256 and aes256-sha256 cipher

---

CryptoPkg/Library/BaseCryptLib/Pk/CryptX509.c

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4509
CryptX509.c file has X509GetTBSCert() funtion and it is added Inf variable to collect the return value of ASN1_get_object(), which return 0x80 in error case. Supplement the return value check during the second function call and correct the check logic.
- Examples: Add a new …

CryptoPkg: Fix bug for correct return value checking when get X509Cert

---

CryptoPkg/Library/BaseCryptLib/Rand/CryptRand.c
CryptoPkg/Library/BaseCryptLib/Rand/CryptRandTsc.c

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4698
The default drbg type of randlib has been switched to aes_256_ctr in openssl1.1.1, so sha1 is not really used in RandomSeed(). Remove related code which do SHA-1 support checking in CryptRand.c and CryptRandTsc.c to avoid potential compatibility errors.
- Examples: Add a new …

CryptoPkg: Remove deprecated code related to SHA-1

---

OvmfPkg/VirtioRngDxe/VirtioRng.c
OvmfPkg/VirtioRngDxe/VirtioRng.h

Add a 'Ready' boolean to the driver state struct, use it to track
whenever the device is ready to be used.  In case it is not ready
throw an EFI_DEVICE_ERROR instead of sending a request which will
never receive an answer.

OvmfPkg/VirtioRngDxe: check if device is ready

---

MdeModulePkg/Core/Dxe/Gcd/Gcd.c

Add a new entry into GCD attribute conversion table to convert EFI_RESOURCE_ATTRIBUTE_SPECIAL_PURPOSE to EFI_MEMORY_SP.

MdeModulePkg: Update GCD attribute conversion to support SP attribute

---

CryptoPkg/Library/BaseCryptLib/SmmCryptLib.inf

This enables RSA extension and bignum function which are needed for getting public key modulus value from X509 certificate.
N/A

CryptoPkg/BaseCryptLib: Enable more functions for SMM/StandaloneMM

---

UefiCpuPkg/Library/CpuPageTableLib/CpuPageTableMap.c

This patch set has been reviewed-by responding pkg maintainers Ni, Ray and Wu jiaxin in previous edk2 community mail loop.
This patch is to fix issue when splitting leaf paging entry in CpuPageTableLib code.
In previous code, before we assign the new child paging structure address to the content of splitted paging entry, PageTableLibSetPnle() is called to make sure the bit7 is set to 0, which indicate the previous leaf entry is changed to non-leaf entry now. There is a gap between we change the bit7 and we assign the new child paging structure address to the content of the splitted paging entry. If the address of code execution or data access happens to be in the range covered by the splitted paging
entry, this gap may cause issue.
In this patch, we prepare the new paging entry content …

Fix page split isuue in cpupagetablelib

---

MdeModulePkg/Universal/HiiDatabaseDxe/Image.c

Struct assignments are not permitted in EDK2, as they may be converted by the compiler into calls to the 'memcpy' intrinsic, which is not guaranteed to be available in EDK2.
So replace the assignment with a call to CopyMem (), and -while at it- replace the loop with a single CopyMem () call, as the loop operates on items that are contiguous in memory.
Build tested only

MdeModulePkg/HiiDatabaseDxe: Avoid struct assignment

---

ArmVirtPkg/ArmVirtQemu.dsc
ArmVirtPkg/ArmVirtQemuKernel.dsc
ArmVirtPkg/VarStore.fdf.inc
OvmfPkg/Library/FdtNorFlashQemuLib/FdtNorFlashQemuLib.c
OvmfPkg/Library/FdtNorFlashQemuLib/FdtNorFlashQemuLib.inf

Add a new FdtNorFalshQemuLib and enable it in ArmVirt platforms
* Patch1: Added a new library called FdtNorFlashQemuLib in OvmfPkg/Library which is non-hardcode dependency.
* Patch2: Enable the new library in ArmVirtQemu.dsc and ArmVirtQemuKernel.dsc.
BZ: https://bugzilla.tianocore.org/show_bug.cgi?id=4770
Build the two platforms firmware using ArmVirtQemu.dsc and ArmVirtQemuKernel.dsc, and then create the pflash files using following command:
```
cat QEMU_EFI.fd  /dev/zero | head -c 64m > ./QEMU_EFI-pflash.raw
cat QEMU_VARS.fd  /dev/zero | head -c 64m > ./vars-template-pflash.raw
qemu-img convert -f raw -O qcow2 -o cluster_size=4096 -S 4096 QEMU_EFI-pflash.raw  QEMU_EFI-pflash.qcow2
qemu-img convert -f raw -O qcow2 -o cluster_size=4096 -S 4096 vars-template-pflash.raw …
```

 Add a new FdtNorFalshQemuLib and enable it in ArmVirtPkg

---

MdePkg/Include/IndustryStandard/IpmiNetFnSensorEvent.h

Adding Ipmi command and structure definitions for optional `Get Sensor Threshold` and `Set Sensor Threshold` commands. 
Local CI Run.
Verified on platform that defines allowed communication with BMC.
N/A

Adding definitions for Ipmi Net Sensor Get/Set Thresholds commands 

---

CryptoPkg/Library/BaseCryptLib/Pk/CryptX509.c

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4509
Both return 0x80 value and Asn1Tag != V_ASN1_SEQUENCE are wrong return.
N/A

CryptoPkg: Fix wrong logic in X509GetTBSCert

---

BaseTools/Scripts/PatchCheck.py

There are a few PRs that are failing PatchCheck with an error condition of more than one package
modified by a commit, but there are no commits that have files modified in more than one package.
The root cause is a logic error that incorrectly changes the range of commits based on a verbosity level
and discards the list of commit shas collected from the range specified on the command line.
* Tested branch from …

BaseTools/Scripts: Fix PatchCheck commit range

---

MdeModulePkg/Universal/Variable/RuntimeDxe/Variable.c

Emit a DEBUG_WARN message if there is not enough flash space left to write/update a variable. This condition is currently not logged appropriately in all cases, given that full variable store can easily render the system unbootable.
This new message helps identifying this condition.
Built OvmfX64 and ran in Qemu with a full …

MdeModulePkg: Warn if out of flash space when writing variables

---

ShellPkg/Library/UefiShellDebug1CommandsLib/Pci.c

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4779
Refer to PCI express base specification Reversion 6.2, table 7-23 Link Capabilities Register.
Supported Link Speeds Vector bit 5: speed 64 GT/s. Add the support to shell command 'pci'.
Signed-off-by: HoraceX Lien <horacex.lien@intel.com>

ShellPkg/Pci.c: Update supported link speed to PCIe Gen6

---

MdeModulePkg/Universal/Acpi/AcpiTableDxe/AcpiTableProtocol.c

Instead of copying from unallocated memory in RemoveTableFromRsdt, do a CopyMem followed by ZeroMem.
Enabled the following PCDs and booted my ADLINK AADK system. The crash following the read from unallocated memory was no longer seen.
```
gEfiMdeModulePkgTokenSpaceGuid.PcdHeapGuardPageType|0xC000000000007B9E
gEfiMdeModulePkgTokenSpaceGuid.PcdHeapGuardPoolType|0xC000000000007B9E …
```

MdeModulePkg: In RemoveTableFromRsdt don't read from unallocated memory

---

MdeModulePkg/Library/DxeCapsuleLibFmp/DxeCapsuleLib.c
MdeModulePkg/Library/DxeCapsuleLibFmp/DxeCapsuleRuntime.c

The ESRT table is not required in UEFI firmware. In such cases, the table may not be present in the UEFI Configuration Table. The mEsrtTable is to check if the IsNestedFmpCapsule() function is invoked at runtime to determine whether to use gEsrtManagementProtocolGuid or the ESRT table from the Configuration Table. Unfortunately, the check does not cover situations where the ESRT is not present, potentially resulting in a kernel crash. This patch is intended to fix this issue.
- **Tests** - Does the change include any …

MdeModulePkg/DxeCapsuleLibFmp: Fix crash if no ESRT is found

---

ArmPkg/ArmPkg.dec
ArmPkg/Library/ArmMonitorLib/ArmMonitorLib.c
ArmVirtPkg/ArmVirt.dsc.inc
ArmVirtPkg/ArmVirtCloudHv.dsc
ArmVirtPkg/ArmVirtKvmTool.dsc
ArmVirtPkg/ArmVirtQemu.dsc
ArmVirtPkg/ArmVirtQemu.fdf
ArmVirtPkg/ArmVirtQemuKernel.dsc
ArmVirtPkg/ArmVirtXen.dsc
ArmVirtPkg/Library/ArmVirtQemuMonitorLib/ArmVirtQemuMonitorLib.c
ArmVirtPkg/Library/ArmVirtQemuMonitorLib/ArmVirtQemuMonitorLib.inf
ArmVirtPkg/Library/PlatformPeiLib/PlatformPeiLib.c
ArmVirtPkg/Library/PlatformPeiLib/PlatformPeiLib.inf
ArmVirtPkg/PrePi/AArch64/ArchPrePi.c
ArmVirtPkg/PrePi/AArch64/ModuleEntryPoint.S

The recent last-minute changes to the ArmMonitorLib to accommodate the NetworkPkg CVE fixes resulted in some breakage for PrePi based virtual ARM platforms, as they cannot support dynamic PCDs yet at the point where the SMCCC conduit is discovered.
Since discovering the SMCCC conduit is rarely necessary in practice, let's rip this out again, and instead, provide a special version of ArmMonitorLib for ArmVirtQemu that discovers the SMCCC conduit from the PSCI device tree node.
The first patch is an unrelated fix but required to test and run this code with the CLANGDWARF toolchain

Pr armvirt avoid dynamic pcds for smcccc conduit

---

UefiPayloadPkg/UniversalPayloadBuild.py

Provide commandline configuration to select proper platform file.
Tested this for RISC-V configuration.
python UefiPayloadPkg/UniversalPayloadBuild.py -t GCC5 --Fit -a RISCV64 -l 2415919104 -c Platform/Rivos/RivosPlatformPkg/UefiPayloadPkg.dsc

UefiPayloadPkg: Enable UPL FIT build for RiscV

---

MdePkg/Library/BaseLib/CpuDeadLoop.c

Starting from certain version of Visual Studio  C compiler (I don’t have the exact version. I am using VS2019), CpuDeadLoop is optimized quite well by compiler.
The compiler does not generate instructions that jump out of the loop when the "Index" is non-zero.
It becomes harder/impossible for developers to break out of the dead-loop in debugger.
The new version of CpuDeadLoop() compares a volatile global to a volatile local. This forces 2 reads and a comparison on every loop iteration. The local variable can be set to 1 to exit the loop without modifying the global variable.
Using VS2019 with max opt enabled, The dead-loop can be exit by setting Index to 1 in a debugger.

MdePkg/BaseLib: Let CpuDeadLoop() be breakable in debugger

---

CryptoPkg/Test/UnitTest/Library/BaseCryptLib/UnitTestMain.c
MdePkg/Library/BaseLib/X86UnitTestHost.c

- **CryptoPkg/Test: call ProcessLibraryConstructorList**
- **MdePkg/X86UnitTestHost: set rdrand cpuid bit**

fix crypto test failures

---

CryptoPkg/Library/BaseCryptLibMbedTls/SysCall/DummyOpensslSupport.c

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=2817
Because the change for strncpy, add the strncpy implementation for BaseCryptLibMbedTls.
From PR: https://github.com/tianocore/edk2/pull/5734
strcpy fix was tested after it was found with OVMF + GDB while testing HTTPS boot. In this test case the first HTTPS boot always failed, with the fix of strcpy the boot is successful on the first try.
NA

CryptoPkg: Fix strncpy for BaseCryptLibMbedTls

---

ArmPkg/Universal/Smbios/ProcessorSubClassDxe/ProcessorSubClass.c

The CoreCount, EnabledCore and ThreadCount counts should be set to 0xFF if value is greater than 255 per the SMBIOS specification.
Validated SMBIOS table was correct with CoreCounts > 255
N/A

ArmPkg/ProcessorSubClassDxe: Limit values to 0xFF

---

MdeModulePkg/Core/Pei/PeiMain.h
MdeModulePkg/Core/Pei/PeiMain.inf
MdeModulePkg/Core/Pei/PeiMain/PeiMain.c
MdeModulePkg/Include/Guid/MigratedFvInfo.h
MdeModulePkg/Include/Ppi/MigrateTempRam.h
MdeModulePkg/MdeModulePkg.dec

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4716
Migrate FSP-T/M binary from temporary RAM to permanent RAM before NEM tear down. Tcg module will use permanent address of FSP-T/M for measurement. In MdeModulePkg, PeiCore installs mMigrateTempRamPpi if PcdMigrateTemporaryRamFirmwareVolumes is True before NEM tear down and after permanent memory ready.
Cc: Chen Gang C <gang.c.chen@intel.com>

MdeModulePkg/Core/Pei: Install MigrateTempRamPpi

---

OvmfPkg/OvmfPkg.dec
OvmfPkg/QemuVideoDxe/Gop.c
OvmfPkg/QemuVideoDxe/Qemu.h
OvmfPkg/QemuVideoDxe/QemuVideoDxe.inf

============ RFC =============
QEMU no longer permits misaligned access to device memory, which breaks QemuVideoDxe on SbsaQemu.
This is one potential work-around - it is quick and dirty hack, and I'm open to alternative approaches.

OvmfPkg/QemuVideoDxe: add feature PCD to remap framebuffer W/C

---

MdeModulePkg/Library/DxeCapsuleLibFmp/DxeCapsuleLib.c
MdeModulePkg/Library/DxeCapsuleLibFmp/DxeCapsuleRuntime.c

The commit "MdeModulePkg/DxeCapsuleLibFmp: Fix crash if no ESRT is found" leads to a compilation error in
MdeModulePkg/Library/DxeCapsuleLibFmp/DxeCapsuleLib.inf. The issue occurs because the variable mDxeCapsuleLibReadyToBootEvent which is declared as extern does not exist, while it is defined in DxeCapsuleRuntime.c, a file not included in DxeCapsuleLib.inf. This patch is to fix this by moving the variable defintion to DxeCapsuleLib.c and declare it as extern in DxeCapsuleRuntime.c.
Reported-by: Gua Guo <gua.guo@intel.com>
- Examples: Crypto algorithm change or buffer overflow …

MdeModulePkg/DxeCapsuleLibFmp: Fix compilation error

---

MdeModulePkg/Core/Dxe/Mem/Page.c

Most of the times it is desirable not to use special purpose memory for regular edk2 usages. That memory (HBm/CXL) are either meant for special purposes or are less reliable to be used. So avoid using them as long as possible. We could also introduce PCD for this control.
Most of the times it is desirable not to use special purpose memory for regular edk2 usages. That memory (HBm/CXL) are either meant for special purposes or are less reliable to be used. So avoid using them as long as possible. We could also introduce PCD for this control.
Test: Tested working on a RISCV system where edk2 excludes this range from allocation

MdeModulePkg: Avoid efi memory allocation for SP type

---

OvmfPkg/Tcg/TdTcg2Dxe/TdTcg2Dxe.c
OvmfPkg/Tcg/TdTcg2Dxe/TdTcg2Dxe.inf

[x] gEfiResetNotificationProtocolGuid is not used in this driver, so let remove dependencies.
[x] Removed weird conversion of UINT64 value while preparing ACPI table. Similar assignment used above patched strings.
No tests. Changes are trivial.
N/A

Refine td tcg2 dxe

---

MdePkg/Library/BaseLib/LoongArch64/Cpucfg.S
UefiCpuPkg/Library/CpuExceptionHandlerLib/LoongArch/LoongArch64/ExceptionHandlerAsm.S

UefiCpuPkg/ExceptionHandler: Fix a context error in LoongArch64
On the LoongArch platform:
the a0 register can be used as both a function parameter and a return value.
Due to parameter EFI_SYSTEM_CONTEXT being overwritten by an invalid context address,
when calling GetExceptionType, incorrect parameter address causes memory access exception.
BZ: https://bugzilla.tianocore.org/show_bug.cgi?id=4796
...
MdePkg/BaseLib: Fix an instruction write width error in LoongArch64
Cpucfg fetch is a 32-bit register, and AsmCpucfg's function
declaration is a 32-bit address storage operation in BaseLib.h,
So, fix it by replacing stptr.d with stptr.w instrcution.
BZ: https://bugzilla.tianocore.org/show_bug.cgi?id=4797 …

Fix bugs in LoongArch64

---

ArmPkg/ArmPkg.dec
ArmPkg/Library/ArmArchTimerLib/ArmArchTimerLib.c
ArmPkg/Library/ArmArchTimerLib/ArmArchTimerLib.inf
ArmVirtPkg/ArmVirtKvmTool.dsc
ArmVirtPkg/ArmVirtQemu.dsc
ArmVirtPkg/ArmVirtQemuKernel.dsc
ArmVirtPkg/ArmVirtXen.dsc

PcdArmArchTimerFreqInHz lets platforms override the architectural timer
frequency, but this really isn't supported in hardware by anything lower
than EL3. And we no longer support running edk2 at EL3.
Setting it to 0 skips the override - but that is also the default.
So rework ArmArchTimerLib not to use it anymore (never set it, and retrieve
it from the system registers using ArmGenericTimerGetTimerFreq () when
needed), update ArmVirtPkg platforms not to ecpliticly set it, then drop it
completely.
Note: merging this series will break a bunch of targets in edk2-platforms.

Drop pcd arm arch timer freq in hz

---

ReadMe.rst

This patch add mbedtls submodule license.
N/A
N/A

ReadMe.rst: Add mbedtls submodule license

---

MdeModulePkg/Library/ImagePropertiesRecordLib/ImagePropertiesRecordLib.c

The presense of PdbPointer (PDB file name) is not an error. Hence, the debug message should be categorized as VERBOSE or INFO. However, the DEBUG_VERBOSE is more appropriate since the PDB file name is already output by the PeCoffLoaderRelocateImageExtraAction() function with the inline "add-symbol-file" when a platform uses the library instance DebugPeCoffExtraActionLib.

MdeModulePkg/ImagePropertiesRecordLib: Reduce debug level

---

MdeModulePkg/Universal/DisplayEngineDxe/InputHandler.c

BZ #4790
Support "^" and "V" key stokes on the pop-up form. Align the implementation with key support on the regular HII form.

MdeModulePkg/DisplayEngineDxe: Support "^" and "V" key on pop-up form

---

NetworkPkg/Library/DxeNetLib/DxeNetLib.c

There is a list of allowed rng algorithms, if /one/ of them is not
supported this is not a problem, only /all/ of them failing is an
error condition.
Downgrade the message for a single unsupported algorithm from ERROR to
VERBOSE.  Add an error message in case we finish the loop without
finding a supported algorithm.

NetworkPkg/DxeNetLib: adjust PseudoRandom error logging

---

BaseTools/Scripts/BinToPcd.py

The xdrlib dependency was removed in commit 5cadb8ce2148979b6c464f6da5a8cd97425c5165 but the actual import of the module was not removed. This commit removes the import of xdrlib and sorts the imports. This will prevent a runtime error when xdrlib is eventually removed from python.
No functional change.
N/A

BaseTools: BinToPcd: Remove xdrlib dependency

---

DynamicTablesPkg/Include/Library/AmlLib/AmlLib.h
DynamicTablesPkg/Library/Acpi/Arm/AcpiSsdtCmn600LibArm/SsdtCmn600Generator.c
DynamicTablesPkg/Library/Common/AmlLib/Api/AmlApi.c
DynamicTablesPkg/Library/Common/AmlLib/CodeGen/AmlCodeGen.c
DynamicTablesPkg/Library/Common/AmlLib/NameSpace/AmlNameSpace.c
DynamicTablesPkg/Library/Common/SsdtSerialPortFixupLib/SsdtSerialPortFixupLib.c

Several input strings to AmlLib APIs are treated
as CONST but were missing the CONST keyword,
requiring their callers to create unnecessary r/w
copies of r/o input strings. This change properly
marks these input strings as CONST.
Reviewed-by: Jeff Brasen <jbrasen@nvidia.com>
Compiled with constant strings being passed into the APIs.
N/A

DynamicTablesPkg: AmlLib CONST cleanup

---

SecurityPkg/Include/Guid/Tcg2AcpiCommunicateBuffer.h
SecurityPkg/Library/SmmTcg2PhysicalPresenceLib/MmTcg2PhysicalPresenceLibCommon.c
SecurityPkg/Library/SmmTcg2PhysicalPresenceLib/MmTcg2PhysicalPresenceLibCommon.h
SecurityPkg/Library/SmmTcg2PhysicalPresenceLib/SmmTcg2PhysicalPresenceLib.c
SecurityPkg/Library/SmmTcg2PhysicalPresenceLib/StandaloneMmTcg2PhysicalPresenceLib.c
SecurityPkg/Library/SmmTcg2PhysicalPresenceLib/StandaloneMmTcg2PhysicalPresenceLib.inf
SecurityPkg/SecurityPkg.dec
SecurityPkg/Tcg/Tcg2Acpi/Tcg2Acpi.c
SecurityPkg/Tcg/Tcg2Acpi/Tcg2Acpi.inf
SecurityPkg/Tcg/Tcg2Config/Tcg2ConfigPei.inf
SecurityPkg/Tcg/Tcg2Config/Tcg2ConfigPeim.c
SecurityPkg/Tcg/Tcg2Smm/Tcg2Smm.c
SecurityPkg/Tcg/Tcg2Smm/Tcg2Smm.h
SecurityPkg/Tcg/Tcg2Smm/Tcg2StandaloneMm.c
SecurityPkg/Tcg/Tcg2Smm/Tcg2StandaloneMm.inf
SecurityPkg/Tcg/Tcg2Smm/Tcg2TraditionalMm.c

---Goal of this task
Enable Tcg2Acpi and Tcg2StandaloneMm in incoming x86 standalone mm
1.Replace the dynamic pcd usage in Tcg2StandaloneMm driver with HOB usage.
2.Allocate Runtime buffer and unblock the communication buffer in PEI phase which is used in Tcg2Acpi driver.
---Background
The patch set is not to solve any existing issue. It’s to enable Tcg2Acpi and Tcg2StandaloneMm in the incoming X86 standalone MM. There will be a PR including a set of patches to enable standalone MM for X86. In the new infrastructure, non-mm buffer used in mm environment should be allocated and unblocked in early phase before the standalone mm env setup. That’s why we need this patch set to be merged first.
---Test I've done
1.Boot Intel internal platform with standalone mm into shell. The code behavior in …

Enable Tcg2Acpi and Tcg2StandaloneMm in standalone mm

---

.pytool/Plugin/CompilerPlugin/CompilerPlugin.py

Pass build variables (those passed to build.py through -D) to the DSC parser to provide a more accurate parsing of the DSC file.
Compiler plugin continues to successfully compile all packages.
N/A

.pytool: CompilerPlugin: Pass through build vars

---

MdeModulePkg/Bus/Usb/UsbBusDxe/UsbBus.c

BZ #4456
Fixed a bug which led to an ASSERT due to the USB device context being maintained after a port reset, but the underlying XHCI context was uninitialized. Specifically, Xhc->UsbDevContext is freed after a reset and only re-allocates the default [0] enpoint transfer ring. In order to avoid a memory leak, device enumeration is performed after freeing the necessary buffers. This allocates the Xhc->UsbDevContext for all endpoints of the USB device.
As mentioned in the commit message.
Our conversation in the edk2 mailing list before the tianocore PR process is copied to this PR conversation.
- **Security** - Does the change have a direct …

MdeModulePkg/UsbBusDxe: USB issue fix when the port reset

---

.pytool/Plugin/DscCompleteCheck/DscCompleteCheck.py
.pytool/Plugin/DscCompleteCheck/Readme.md

Allows ignore lines in the CI YAML file to use git ignore syntax.
This is especially useful for ignore files recursively in directories like those that may exist in an external dependency folder.
Currently used as-is in downstream consumers and passes all CI in edk2.
N/A - no changes to consumer

DscCompleteCheck: Allow git ignore syntax

---

BaseTools/Source/Python/Workspace/InfBuildData.py

Update retrieval of private guids, protocols, or ppis from a package's declaration file to use the original path of the module's INF file rather than the current path. When building the same module multiple times in the same INF (by override the define's FILE_GUID), a temporary instance of the module is generated outside the package, causing the retrieval of private values to fail as the check to access private values is done by verifying the module to build, is inside the package.
See: https://bugzilla.tianocore.org/show_bug.cgi?id=4730
- Examples: Crypto algorithm change or …

BaseTools: InfBuildData: Fix Private value retrieval

---

MdeModulePkg/Bus/Pci/NvmExpressDxe/NvmExpress.c

This PR fixes format specifiers used for UINT64 values.
This set was sent to the list in Feb 2024 and reviewed by Laszlo Ersek
https://edk2.groups.io/g/devel/message/115601 ,
and I didn't get any reply from MdeModulePkg/NvmExpressDxe maintainers.
- **Breaking change** - this patch can change the NVM device model name set as Controller Name which consumed by SecurityPkg/Tcg/Opal/OpalPassword driver and used in HII.
None. The change is trivial.
N/A

Nvme u64 format fix

---

OvmfPkg/AmdSev/BlobVerifierLibSevHashes/BlobVerifierSevHashes.c

#5769 does not allow for the situation where kernel hashes is used but an initrd is not provided. Thankfully it's easy to support this.
If kernel hashes are enabled but no initrd is provided, QEMU will still create an entry in the hash table, but it will be the hash of an empty buffer.
Remove the explicit check for the length of the blob. This logic will be handled by the later hash comparison, which will still fail when the blob is not present but is expected, but will pass when the blob is not present and the hash table contains a hash of an empty buffer.
cc: @bssrikanth @dubek @tlendacky @ardbiesheuvel @kraxel

AmdSev: enable kernel hashes without initrd

---

MdePkg/Include/IndustryStandard/Nvme.h

Most of the definitions in this file are currently well documented.
This adds documentation for a few missing fields in the NVMe Controller Capabilities structure.
- CI
N/A
---
> Note: This is a trivial change made while debugging a NVMe issue that has no functional impact.

MdePkg/Nvme.h: Add missing NVMe capability descriptions

---

EmbeddedPkg/Library/VirtualRealTimeClockLib/VirtualRealTimeClockLib.inf

RISC-V ovmf used VirtualRealTimeClockLib but the default epoch is a compilation time. It causes that the RISC-V ovmf binary image is NOT reproducible.
This patch added the support of SOURCE_DATE_EPOCH by printenv command. If SOURCE_DATE_EPOCH be found then we use it as BUILD_EPOCH. Otherwise we run date command for setting BUILD_EPOCH.
For distributions want a reproducible RISC-V ovmf image, they should export SOURCE_DATE_EPOCH environment variable before building ovmf.
References: https://reproducible-builds.org/docs/source-date-epoch/
Cc: Pete Batard <pete@akeo.ie>

EmbeddedPkg/VirtualRealTimeClockLib: Support SOURCE_DATE_EPOCH

---

MdePkg/Include/ConfidentialComputingGuestAttr.h
MdePkg/Include/Register/Amd/SevSnpMsr.h
OvmfPkg/Include/Library/MemEncryptSevLib.h
OvmfPkg/Library/BaseMemEncryptSevLib/DxeMemEncryptSevLibInternal.c
OvmfPkg/Library/BaseMemEncryptSevLib/PeiMemEncryptSevLibInternal.c
OvmfPkg/Library/BaseMemEncryptSevLib/SecMemEncryptSevLibInternal.c
OvmfPkg/Library/CcExitLib/CcExitVcHandler.c
OvmfPkg/PlatformPei/AmdSev.c
UefiCpuPkg/Library/MpInitLib/MpLib.c

This is to prevent #DB interception on AMD SEV-ES VM with enabled DebugSwap feature.
The goal of this pull request is CI check, attempt 4.

AMD SEV Debugswap

---

SecurityPkg/Tcg/Tcg2Config/Tcg2ConfigPeim.c

Cast pointer type to VOID* to avoid potential build error. If the two PCD are FixAtBuild, PcdGetPtr will return a const type pointer. Since the second parameter of BuildGuidDataHob is VOID*, build error may happen with following log: 
warning C4090: 'function': different 'const' qualifiers
Tested by tianocore edk2 CI

SecurityPkg/Tcg2Config: Cast pointer type to VOID* to avoid potential build error.

---

MdePkg/Include/IndustryStandard/Tdx.h

Currently, TDX QEMU always configure TD_PARAMS.MAX_VCPUS as the number of actual vcpus it has created for the TD. 
So in the TDG.VP.INFO, the returned value of NUM_VCPUS and MAX_VCPUS in R8 are always same. 
However, TDX QEMU + KVM are going to set a big value for TD_PARAMS.MAX_VCPUS than actual created TD vcpus, which triggers the issue and find the bug.

MdePkg/Tdx.h: Fix the order of NumVcpus and MaxVcpus

---

StandaloneMmPkg/Include/Library/FvLib.h
StandaloneMmPkg/Library/FvLib/FvLib.c

Fixes an issue where the returned section data length is always 4 bytes larger than the actual section length. This could cause an issue where the caller accesses the final 4 bytes which would be invalid.
> Marked as a breaking change due to modifying the behavior for the
library API.
- CI
- Verified size returned now matches the `SectionData` length
- Review code to determine if `FvLib` is being used
- If so, check if the `FfsFindSectionData()` API is being used
- If so, check usage of the `SectionDataSize` parameter in code
to determine if a change needs to be made for the header size
being removed from the size returned.

StandaloneMmPkg: Fix section data length returned larger than actual size

---

OvmfPkg/LoongArchVirt/LoongArchVirtQemu.dsc

Because the complex dependency between SerialPortLib and PciExpressLib leads to multiple references to the lib library in the loongarch dsc file, optimizing SerialPortLib now simplifies multiple references to lib in the dsc file.
Cc: Bibo Mao <maobibo@loongson.cn>
Cc: Xianglai Li <lixianglai@loongson.cn>
Cc: devel@edk2.groups.io
<_Delete lines in \<\> tags before creating the …

OvmfPkg/LoongArchVirt: Optimize the use of serial port libraries

---

BaseTools/Source/Python/Capsule/GenerateCapsule.py
BaseTools/Source/Python/Common/Uefi/Capsule/FmpCapsuleHeader.py

I was trying out `GenerateCapsule.py` for a [project](https://docs.dasharo.com/projects/capsule-updates/) to support coreboot firmware updates via UEFI capsules and hit a sequence of issues with running the script and interpreting its output.  Thought it's my bad but looking at the code proved that it needs to be improved in multiple places.
See individual commits for explanation of what they are fixing.
- No, unless somebody used incorrect `UpdateImageIndex` equal to zero which can't be used anymore.
- These are just fixes, like making `GenerateCapsule.py --decode` not fail due to querying an invalid parameter.
- No, I don't think so.
- No.
Manually run `BaseTools/BinWrappers/PosixLike/GenerateCapsule` with `--encode`, `--decode` and `--dump-info`.
N/A

Fixes for `GenerateCapsule.py`

---

BaseTools/Plugin/LinuxGcc5ToolChain/LinuxGcc5ToolChain.py

Commit ea56fa3d4706 ("BaseTools: Enable RISC-V architecture for RISC-V EDK2 CI") introduced a UTF-8 NBSP (0xc2a0) inside a comment block otherwise copied identically from pre-existing architectures. This was clearly unintentional and confuses things when looking for which files contain UTF-8 encodings, so change it to good old 0x20.
This change is non-functional.

BaseTools: change non-ASCII characters in LinuxGcc5ToolChain.py

---

MdeModulePkg/Core/Pei/Memory/MemoryServices.c

Removes an assert if PeiAllocatePool() fails to allocate memory to defer error handling to the caller so the error can be handled gracefully or asserted at that location which is more specific to the call that led to the allocation.
- CI
- Platform boot with change that includes calls to `PeiAllocatePool()`
- N/A

MdeModulePkg: Remove PeiAllocatePool() Assert

---

RedfishPkg/RedfishPlatformConfigDxe/RedfishPlatformConfigDxe.c

Change the debug message level to DEBUG_INFO for protocol notification functions. The protocol notification function is invoked at least one time. The failure of locating protocol is expected because protocol may not be installed when Redfish platform config driver is launched.
Signed-off-by: Nickle Wang <nicklew@nvidia.com>
N/A
N/A

RedfishPkg/RedfishPlatformConfigDxe: remove false alarm

---

NetworkPkg/HttpDxe/HttpImpl.c
NetworkPkg/HttpDxe/HttpProto.c
NetworkPkg/HttpDxe/HttpProto.h

In EfiHttpRequest(), length of target URLs was always compared to fixed-size value, even after allocating a larger URL buffer. This change ensures the right URL length is used during calculations.
CI
N/A

NetworkPkg/HttpDxe: Track HttpInstance URL buffer length.

---

MdeModulePkg/Library/RuntimeResetSystemLib/RuntimeResetSystemLib.c

Makes the `mInternalRT` global static in this library instance to avoid conflicting with other code such as a global variable with the same name in MdePkg/Library/UefiRuntimeLib.
- CI
- N/A

MdeModulePkg/RuntimeResetSystemLib: Make global static

---

MdePkg/Include/Register/Intel/StmApi.h

The `SMM_REV_ID` is defined in the STM specification: https://www.intel.com/content/www/us/en/content-details/671521/smi-transfer-monitor-stm-developer-or-user-guide.html?wapkw=stm, section 10.1.1.
This adds it into the `StmApi.h` for potential STM usage.
- CI
- N/A

MdePkg/StmApi.h: Add SMM_REV_ID definition for STM header

---

BaseTools/Conf/tools_def.template
OvmfPkg/LoongArchVirt/Library/Fdt16550SerialPortHookLib/Fdt16550SerialPortHookLib.c

Patch1: Remove the `fno-plt` from LoongArch CC flags, because it no used.
Patch2: A variable in Fdt16550SerialPortHookLib was not initialized, this has been fixed.
Build virt-machine BIOS using  OvmfPkg/LoongArchVirt/LoongArchQemu.dsc and run it.

Adjust LoongArch CC flags and fix some compiler check error.

---

UefiPayloadPkg/UefiPayloadPkg.dsc

The platforms  and UefiPayload  use the difference PCD attribute to define the PCD PcieResizableBarSupport , So that cause the UefiPayload  got the wrong value of this PCD.
Therefore synchronize PCD attribute settings to solve this problem.
NO
NO
NO
N/A
N/A

UefiPayloadPkg:Modify the PCD PcieResizableBar to dynamic PCD

---

SecurityPkg/Tcg/Tcg2Acpi/Tcg2Acpi.c

This debug print may attempt to print a string without a null terminator that can lead to a machine check.
The value printed is substituted with a source buffer to still allow debug.
- Verified boot with code after the change
- N/A

SecurityPkg/Tcg2Acpi: Revise debug print

---

MdePkg/Include/Register/RiscV64/RiscVEncoding.h
MdePkg/Library/BaseRngLib/BaseRngLib.inf
MdePkg/Library/BaseRngLib/Riscv/Rng.c
MdePkg/Library/BaseRngLib/Riscv/Seed.S
MdePkg/MdePkg.dec
OvmfPkg/RiscVVirt/RiscVVirt.dsc.inc

The ratified RISC-V crypto scalar extensions provide entropy bits via the
seed CSR, as exposed by the Zkr extension. The Zkr extension is ratified
and provides 16 bits of entropy seed when reading the SEED CSR.
Guarded by a RISCV64 Feature PCD, 64-bit random numbers can be
accumulated from the `seed` CSR. This driver is based on the driver in
the Linux kernel.
Test: It was tested on a simulation platform that implements zkr extension. A debug array was printed of mIndex to confirm random values are displayed.
Need to enable BIT3 of PcdRiscVFeatureOverride PCD. By default on Virt platform it is disabled.

Add RISC-V Drng Zkr extension support

---

OvmfPkg/LoongArchVirt/LoongArchVirtQemu.dsc
OvmfPkg/LoongArchVirt/LoongArchVirtQemu.fdf

Open the network option to enable networking on the LoongArch QEMU platform.
* Build using OvmfPkg/LoongArchVirt/LoongArchQemuVirt.dsc
* Run the QEMU_EFI.fd with QEMU and add following operations:
`-netdev user,id=net0 -device virtio-rng-pci -device virtio-net-pci,netdev=net0`
* A PXE boot option will appear in the Boot Manager:
N/A

OvmfPkg: Add network support for LoongArch QEMU platform

---

BaseTools/Source/Python/Ecc/Check.py
BaseTools/Source/Python/Ecc/Configuration.py
BaseTools/Source/Python/Ecc/EccToolError.py
BaseTools/Source/Python/Ecc/config.ini

Related to the discussion in #5893, replacing #5867 based on conversation with @mdkinney and @ajfish.
The conversation on what to do with regards to the style rules will be a longer one. This change lets us merge #5840 while that conversation is ongoing.
Patch 1/2 still fixes a consistent misspelling of ASCII in ECC.
Patch 2/2 now completely deletes the GeneralCheckNoAscii() test from ECC. However, there are some other tests that still verify (via regex) various identifiers against naming standards from the coding style, enforcing a subset of ASCII there.
My intent is to follow this PR with one adding ASCII-checks for remaining identifier types, as an RFC.

BaseTools: Ecc disable ascii scan

---

BaseTools/Plugin/HostBasedUnitTestRunner/HostBasedUnitTestRunner.py

Some unit tests would fail to execute or execute and not produce any output logs. In these cases, the only output would be in the CI Log as `UnitTest Execution Error`.
A UnitTest Execution Error should be considered the same as a unit tests test failing.
When running a unit test on a repo where the unit test was not implemented correctly, CI would still pass.
After making this change, the unit test execution …

BaseTools/HostBasedUnitTestRunner: Promote Unittest error to CI fail.

---

BaseTools/Plugin/CodeQL/CodeQlQueries.qls

This query produces a high rate of false positives with some common patterns in edk2 like passing function pointers for callback.
Previously, due to the usage of `STATIC` instead of `static`, particularly for functions, this query was rarely used in the past. It is removed here to prevent future false positives.
- Run the CodeQL plugin before and after the change with a `static` function present.
- N/A

BaseTools/CodeQL: Removed unused static function query

---

MdePkg/Library/UefiDebugLibDebugPortProtocol/DebugLibConstructor.c

REF:https://bugzilla.tianocore.org/show_bug.cgi?id=3083
Since this is a library, make the function ExitBootServicesCallback() STATIC to prevent the likelihood that it collides with other symbols.
- CI
N/A

MdePkg/UefiDebugLibDebugPortProtocol: ExitBootServicesCallback() static

---

MdeModulePkg/Application/SmiHandlerProfileInfo/SmiHandlerProfileInfo.c

The code prints wide strings, so the content should be "utf-16" rather than "utf-8".
- Check encoding declared vs actual
N/A

MdeModulePkg/SmiHandlerProfileInfo: Declare correct XML encoding

---

RedfishPkg/RedfishConfigHandler/RedfishConfigHandlerDriver.c
RedfishPkg/RedfishDiscoverDxe/RedfishDiscoverDxe.c

The Redfish drivers log messages as errors in various places when they don't find an appropriate network interface - even when one has already been found. Reduce those log messages to DEBUG_MANAGEABILITY to avoid spamming the console in Release builds.

RedfishPkg: Reduce DEBUG_ERROR to DEBUG_MANAGEABILITY in various places

---

MdeModulePkg/Core/DxeIplPeim/DxeLoad.c

- [Bugzilla#4653](https://bugzilla.tianocore.org/show_bug.cgi?id=4653)
- In DxeIplFindDxeCore function, there exists different behavior between Debug and Release built BIOS.
- This change is used to unify both of the code flow and fix the potential overflow of "Instance" variable.
- In this change,
1. Move the ASSERT_EFI_ERROR (Status) in failure to find DxeCore in any firmware volume condition.
2. Break the while-loop when not found required DxeCore. This would make the Instance variable not overflow in while-loop.
3. Add the CpuDeadLoop () in the end of the function and do not return since DxeCore is mandatory for the following booting to hand-off the PEI phase to DXE phase.
4. In case of the CpuDeadLoop () is de-assert by debugger, return the NULL pointer.
- No, it is changed the …

[BZ-4653] MdeModulePkg/Core/DxeIplPeim: Enhance Code in DxeIplFindDxeCore Function

---

MdePkg/Library/BaseLib/LoongArch64/AsmCsr.S
MdePkg/Library/BaseLib/LoongArch64/Csr.c

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4812
When the Select is out of support, use method break exception instead of method return -1, 
avoid unknown errors caused by untimely detection.
- **Security** - Does this PR have a …

MdePkg/BaseLib: Optimize LOONGARCH64 csr usage

---

MdeModulePkg/Core/PiSmmCore/SmiHandlerProfile.c

Includes the profiler SMI in the profile itself for completeness.
- Review SMI profile output to see the profiler SMI is accounted for
- N/A

MdeModulePkg/SmiHandlerProfileInfo: Include profile in profile

---

ArmPlatformPkg/Library/LcdHwNullLib/LcdHwNullLib.c

Library previously returned EFI_SUCCESS which causes the platform to continue initializing LCD HW. Should return EFI_NOT_FOUND as this is a null library.
Resolves TCBZ3351: https://bugzilla.tianocore.org/show_bug.cgi?id=3351.
Tested using the null lib and seeing LCD HW init not continue.
N/A.

ArmPlatformPkg: Update LcdHwNullLib to Prevent Init

---

MdeModulePkg/Library/VariablePolicyLib/VariablePolicyLib.c

Makes the `#` character used for comparison against wildcard characters in `CHAR16` strings to be prefixed with `L` so the character is treated as a wide character constant.
- CI
- N/A

MdeModulePkg/VariablePolicyLib: Use wildcard character constant

---

EmbeddedPkg/Library/NonCoherentDmaLib/NonCoherentDmaLib.c

When allocating memory for a non-coherent DMA device, the current core code removes the XP attribute, allowing code to execute from that region. This is a security vulnerability and unneeded. This change updates to mark the region as XP when allocating memory for the non-coherent DMA device.
Tested on a platform using a non-coherent DMA device and saw the DMA region marked XP.
N/A.

EmbeddedPkg: Mark DMA Memory Allocations XP By Default

---

ArmVirtPkg/Library/QemuVirtMemInfoLib/QemuVirtMemInfoPeiLib.inf

Platforms today may use this PCD as a dynamic PCD as that is an allowed type in its PCD declaration. From `ArmPkg.dec`:
[PcdsFixedAtBuild.common, PcdsDynamic.common, PcdsPatchableInModule.common]
gArmTokenSpaceGuid.PcdSystemMemorySize|0|UINT64|0x0000002A
This library causes a build error if it used as a dynamic PCD since it places the PCD in a `[FixedPcd]` section in the INF.
Other libraries do set the PCD and depend on the dynamic PCD behavior.
Since this library accesses the PCD with `PcdGet64 ()` which is compatible with FixedAtBuild PCDs, this change moves the PCD out an explicit `[FixedPcd]` section to resolve the following build error:
```
INFO -  : error 3000: Building modules from source INFs, following
PCD use Dynamic and FixedAtBuild access method.
It must be corrected to use …
```

ArmVirtPkg: QemuVirtMemInfoPeiLib: Allow PcdSystemMemorySize to be non-fixed

---

ArmPkg/Drivers/CpuDxe/MemoryAttribute.c
ArmPkg/Library/ArmMmuLib/AArch64/ArmMmuLibCore.c
ArmPkg/Library/ArmMmuLib/Arm/ArmMmuLibUpdate.c

The memory attribute protocol is primarily used by bootloaders and there are many released bootloaders who use the protocol incorrectly. It is challenging to debug these situations because the bootloaders are generally black boxes and we silently fail on the FW side. This patch series adds logging for ARM32 and AARCH64 to log during failures of the memory attribute protocol (and in ArmMmuLib) for commonly seen bootloader failures using the memory attribute protocol.
- **Tests** - Does this PR include any explicit …

Add Memory Attribute Protocol Logging

---

ArmPlatformPkg/Library/PL031RealTimeClockLib/PL031RealTimeClockLib.c
ArmVirtPkg/Library/KvmtoolRtcFdtClientLib/KvmtoolRtcFdtClientLib.c

Two ARM RTC libs will clear EFI_MEMORY_XP from MMIO memory if a platform has set it, because they explicitly set memory attributes that do not include EFI_MEMORY_XP. These regions are not intended to be executed from, so this patch set updates the libs to explicitly set the regions to EFI_MEMORY_XP.
Tested on ARM64 virtual platforms.
N/A.

Set ARM RTC MMIO as NX

---

ShellPkg/Library/UefiShellDebug1CommandsLib/SmbiosView/PrintInfo.c

Add changes to print PMIC and RCD details of Smbios Type17 in Shell smbiosview command.
Cc: Gaoliming <gaoliming@byosoft.com.cn>
Cc: Sainadh N <sainadhn@ami.com>
Cc: Sundaresan S <sundaresans@ami.com>
Cc: Srinivasan M <srinivasanm@ami.com>
Cc: Ramesh R <rameshr@ami.com>
Cc: Karthika R <karthikar@ami.com>
Reviewed-by: Giri Mudusuru <girimudusuru@microsoft.com>

ShellPkg: Changes to print Type17 in Smbiosview

---

ShellPkg/Library/UefiShellAcpiViewCommandLib/AcpiParser.h
ShellPkg/Library/UefiShellAcpiViewCommandLib/Parsers/Hest/HestParser.c
ShellPkg/Library/UefiShellAcpiViewCommandLib/UefiShellAcpiViewCommandLib.c
ShellPkg/Library/UefiShellAcpiViewCommandLib/UefiShellAcpiViewCommandLib.inf

Add a new pareser for the Hardware Error Source Table (HEST).
The HEST table is used to describe a system's hardware error sources to OSPM.

ShellPkg/Acpiview: Add HEST Parser

---

ShellPkg/Library/UefiShellAcpiViewCommandLib/Parsers/Madt/MadtParser.c

Parse CORE_PIC, LIO_PIC, HT_PIC, EIO_PIC, MSI_PIC, BIO_PIC and LPC_PIC tables in ACPI SPEC 6.5.
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4306
Co-authored-by: Jinwei Wang <wangjinwei@loongson.cn>
Reviewed-by: Chao Li <lichao@loongson.cn>
- **Breaking change** - Does this PR cause a break in …

ShellPkg: Support parser of MADT for LoongArch64

---

ArmPkg/ArmPkg.ci.yaml
ArmPkg/Library/ArmMonitorLib/ArmMonitorLib.c
ArmPkg/Library/DebugPeCoffExtraActionLib/DebugPeCoffExtraActionLib.c

Fix up a handful of uncrustify infractions and drop the AuditOnly override for uncrustify so we get the same uncrustify CI coverage as other packages.

ArmPkg: Disable AuditOnly mode for uncrustify

---

ArmPkg/ArmPkg.dsc
ArmPkg/Library/ArmPsciResetSystemLib/ArmPsciResetSystemLib.c
ArmPkg/Library/ArmPsciResetSystemLib/ArmPsciResetSystemLib.inf

Add a new implementation of ResetSystemLib based on ArmMonitorLib. This patch was part of #5933 but has been split off to work around some CI issues that were causing confusion.

ArmPkg: Introduce ResetSystemLib implementation based on ArmMonitorLib

---

PrmPkg/PrmConfigDxe/PrmConfigDxe.c

Passing in access attributes to SetMemorySpaceAttributes() will cause the existing attributes to be overwritten. The MMIO region should have the appropriate attributes applied during memory protection initialization and the attributes of the memory space descriptor are inaccurate. Don't pass in any CPU arch attributes so SetMemorySpaceAttributes() doesn't subsequently call gCpu->SetMemoryAttributes().
Tested on …

PrmPkg: Don't Set Access Attributes of Runtime MMIO Ranges

---

.github/scripts/GitHub.py
.github/workflows/request-reviews.yml
BaseTools/Scripts/GetMaintainer.py

A series of changes to automate reviewers being added to pull requests in edk2.
Long term, it is preferred to exclusively depend upon GitHub Code Owners. This
PR is meant to provide an immediate solution to adding reviewers to PRs while
opens around CODEOWNERS are closed.
---
**BaseTools/GetMaintainer.py: Add GitHub username argument**
Adds a new `-g` parameter so that output will also include the GitHub
username.
This change uses a simple regular expression as opposed to directly
returning the original line from the file to make the extraction of
GitHub usernames more robust to other changes on the line in the
maintainers text file.
---
**.github: Add GitHub python script**
Adds a script that provides GitHub API helpers for automation scripts
in the repository.
--- …

Automatically Add Reviewers to Pull Requests

---

UefiCpuPkg/Library/MpInitLib/LoongArch64/MpLib.c

Structure assignment may depend on the compiler to expand to memcpy. 
For this, we may need to add -mno-memcpy to the compilation flag. 
Here, we reduce dependencies and use CopyMem for data conversion without
memcpy.
Co-authored-by: Chao Li <lichao@loongson.cn>
<_Delete lines in \<\> tags before creating …

UefiCpuPkg/MpInitLib: Reduce compiler dependencies for LoongArch

---

FmpDevicePkg/FmpDxe/FmpDxe.c

This patch adds an assert to FmpDxe.c to catch a platform misconfiguration of PcdFmpDeviceImageTypeIdGuid.
N/A.
N/A.

FmpDevicePkg: Assert on PcdFmpDeviceImageTypeIdGuid Size Mismatch

---

MdeModulePkg/Universal/Variable/Pei/Variable.c

This patch is to fix issue caused by uninitialized local variable in Pei/Variable.c.
In the fucntion CalculateHobVariableCacheSize(), the local variable VARIABLE_STORE_INFO StoreInfo is used without
initialization. When the uninitialized variable is passed to CalculateAuthVarStorageSize() and GetNextVariablePtr(), the field StoreInfo->FtwLastWriteData might be a uninitialized non-zero value. Then the code execution will access the invalid address StoreInfo->FtwLastWriteData->TargetAddress. This might cause issue.
So in this commit, the local variable VARIABLE_STORE_INFO StoreInfo is initialized by a ZeroMem() before use.
Tested in Intel internal platform

Fix issue in Pei/Variable.c

---

EmbeddedPkg/Library/NonCoherentDmaLib/NonCoherentDmaLib.c

Commit 8984fba2f22a2cd44e1189403e3553f447b82852 added setting the EFI_MEMORY_XP attribute on DMA buffers. However, it did not ensure that the XP capability was set on that region.
This patch adds setting the XP capability before attempting to set the attribute. If setting the capability fails, it defaults to the old behavior of not setting the XP bit.
Fixing up last commit.
N/A.

EmbeddedPkg: NonCoherentDmaLib: Set EFI_MEMORY_XP Capability on DMA Buffer

---

MdePkg/Include/IndustryStandard/Acpi65.h

This modification come from ACPI 6.5 spec.
Besides, Starting with revision 2 of HEST, the Error Source Structures must be sorted in Type ascending order for Error Source Structure Types of less than 12.

MdePkg: Update HEST Revision As 2

---

BaseTools/Plugin/CodeQL/CodeQlQueries.qls
BaseTools/Plugin/CodeQL/codeqlcli_ext_dep.yaml
BaseTools/Plugin/CodeQL/codeqlcli_linux_ext_dep.yaml
BaseTools/Plugin/CodeQL/codeqlcli_windows_ext_dep.yaml

The codeql/cpp-queries pack used in CodeQlQueries.qls was versioned 1.1.0 for the CodeQL CLI v2.18.1 release currently used.
https://github.com/github/codeql/blob/codeql-cli/v2.18.1/cpp/ql/src/qlpack.yml
This change pins that pack version to prevent the CodeQL CLI and pack from getting out of sync until explicitly updated.
- CodeQL run with v2.18.1
- Confirm using the specified CodeQL language pack version is used
- N/A

BaseTools/Plugin/CodeQlQueries.qls: Pin to the 1.1.0 codeq/cpp-queries pack

---

BaseTools/Scripts/BinToPcd.py

With Python 3.12 invalid escape sequences now generate warning messages. This change fixes the problem exposed by the warning message.
```
BaseTools\Scripts\BinToPcd.py:40: SyntaxWarning: invalid escape sequence
BaseTools\Scripts\BinToPcd.py:46: SyntaxWarning: invalid escape sequence
```
Ran script before and after changes, same output, but no warning messages. 
N/A

BaseTools/Scripts/BinToPcd.py: Update regex strings to use raw strings.

---

BaseTools/Plugin/WindowsResourceCompiler/WinRcPath.py

WinRcPath generally takes about 2 seconds to run, due to calling multiple .bat files behind the scenes. This change reduces this time to ~0 seconds due to the following changes:
1. It will attempt to load the path from the cache, which is located a $(WORKSPACE)/Conf/.rc_path. If the loading is a success and the rc_path still exists, it will use it.
2. If the cache did not exist, or the path provided by the cache does not exist, it will find the rc path via the .bat files. If that succeeds, it will write the path to the cache.
- Examples: Crypto algorithm change or buffer …

BaseTools/WinRcPath: Improve Performance.

---

BaseTools/Source/Python/Capsule/GenerateCapsule.py

- [Bugzilla#4821](https://bugzilla.tianocore.org/show_bug.cgi?id=4821)
- Changes
- Deliver some of the script bug-fixes and correct the some of debug message.
- Add the ```HashAlgorithm``` key in JSON file and ```--hash-algorithm``` in command arguments.
- Allow caller to assign the expected hash algorithm for capsule payload digest.
- Backward Compatibility
- Default hash algorithm would be kept as ```SHA256```.
- Without giving the new key in JSON file or input the new flag in command line, default ```SHA256``` would be used.
- Notice
- Platform needs to enable the correspond code flow to make sure the PKCS#7 signature could be decoded and verified successfully.
- Based on the ```BaseCryptoLib``` in CryptoPkg, the ```Pkcs7Verify ()``` supported ```md5```, ```sha1```, ```sha256```, …

[BZ-4821] Support to Use Different Hash Algorithm for Capsule Payload Content

---

.github/scripts/GitHub.py
.github/scripts/RequestPrReviewers.py
.github/scripts/requirements.txt
.github/workflows/request-reviews.yml

Makes a number of optimizations and enhancements for the request reviewer workflow.  This is considered a large rewrite of the workflow. The following items represent the main changes.
1. Uses `PyGithub` for GitHub interactions instead of the GitHub REST API directly.
2. Uses `GitPython` instead of invoking the git executable directly.
3. Optimizes the repository checkout step from an average time of 21 seconds to 1 second by performing a sparse checkout of only the file paths needed for the workflow run at a fetch depth of 1.
4. Optimizes and makes the PIP module installation process for the workflow more robust by caching the pip modules used so the only time the workflow needs to reach to PyPi is when new PIP modules are published.
5. Improves long term stability by locking the major …

.github: Request PR reviewers enhancements

---

.github/workflows/request-reviews.yml

Since the edk2 repository is owned by an organization, the default GitHub token will not be able to access the collaborator list.
Therefore, a GitHub App with `metadata:read` permission will be used to grant access to that REST API. This is used in GitHub.py when it makes the `repo_gh.get_collaborators()` call that resolves to the `/repos/{owner}/{repo}/collaborators` GitHub REST API.
- Testing in `master` …

.github/request-reviews.yml: Use GitHub App authentication

---

MdeModulePkg/Universal/Console/ConPlatformDxe/ConPlatform.c

Some multi-function input devices (e.g. combo keyboard and mouse) present as IAD-style devices (https://www.usb.org/defined-class-codes, https://learn.microsoft.com/en-us/windows-hardware/drivers/usbcon/usb-interface-association-descriptor). Historically, multi-function devices would report a DeviceClass of 0, indicating that interface matching should be done on the interface descriptor rather than the global device descriptor.
IAD-style devices use DeviceClass of 0xEF, so they don't match MatchUsbClass() for keyboard (DeviceClass=3, SubClass=1, Proto=1). If they are treated as if they had a DeviceClass of zero, which is more traditional for legacy multi-function devices, then the interface descriptors are used instead and these types of devices will "just work" without needing to add a …

MdeModulePkg ConPlatform: Support IAD-style USB input devices.

---

RedfishPkg/Include/Protocol/EdkIIRedfishCredential2.h
RedfishPkg/RedfishCredentialDxe/RedfishCredentialDxe.c
RedfishPkg/RedfishCredentialDxe/RedfishCredentialDxe.h
RedfishPkg/RedfishCredentialDxe/RedfishCredentialDxe.inf
RedfishPkg/RedfishHttpDxe/RedfishHttpData.h
RedfishPkg/RedfishHttpDxe/RedfishHttpDxe.c
RedfishPkg/RedfishHttpDxe/RedfishHttpDxe.h
RedfishPkg/RedfishHttpDxe/RedfishHttpDxe.inf
RedfishPkg/RedfishPkg.dec

Extending the Redfish Credential protocol to allow Redfish Clients to be registered/unregistered for tracking their end of work and delete a bootstrap account when all registered Redfish clients finish their communication with Redfish service.
Redfish Http module also was updated to register/unregister clients on Redfish Service creation/stop event.
- **Breaking change** - Does this PR cause a break in …

RedfishPkg: Allow deletion of the bootstrap account

---

DynamicTablesPkg/DynamicTables.dsc.inc
DynamicTablesPkg/Include/AcpiTableGenerator.h
DynamicTablesPkg/Include/ArchCommonNameSpaceObjects.h
DynamicTablesPkg/Library/Acpi/Common/AcpiTpm2Lib/AcpiTpm2Lib.inf
DynamicTablesPkg/Library/Acpi/Common/AcpiTpm2Lib/Tpm2Generator.c
DynamicTablesPkg/Library/Common/TableHelperLib/ConfigurationManagerObjectParser.c
DynamicTablesPkg/Library/Common/TableHelperLib/ConfigurationManagerObjectParser.h
DynamicTablesPkg/Readme.md
MdePkg/Include/IndustryStandard/Tpm2Acpi.h

- Add AcpiTpm2LibArm for generating ACPI TPM2 table using the information obtained from Tpm2InterfaceInfo CM object.
- Add helper function HexDump for printing hex dump of CM Object fields. Also merge multiple flavors of PrintCharX into one function PrintChars by using the field length.
- Add parser for Tpm2 CM object, which uses HexDump for dumping the 12 bytes of "StartMethodParameters" field.
- Verified that TPM2 table was created properly on platform that produces Tpm2InterfaceInfo CM object.
- Called ParseCmObjDesc() and ensured that all fields of the CM objects were printed correctly.
N/A

Add ACPI TPM2 table generator

---

.mergify/config.yml

The following message is visible on mergify runs:
`"The configuration uses the deprecated merge_method attribute of the queue action in one or more pull_request_rules. It must now be used under the queue_rules configuration."`
With the following warning:
`"A brownout is planned on August 26th, 2024."`
`"This option will be removed on September 23rd, 2024."`
This change updates the configuration file to comply with the new format.
- PR gates
N/A - Only impacts edk2 repo usage of mergify

.mergify: Fix pull_request_rules deprecation

---

SecurityPkg/Tcg/Tcg2Config/Tcg2ConfigPeim.c

Allocate EfiACPIMemoryNVS buffer for TCG2 related usage in Tcg2ConfigPeim. The buffer will be used in Tcg2Acpi driver
to retrive information from SMM environment.
Previously, the buffer used in Tcg2Acpi driver is AcpiNvs type. But I mistakenly thought the Runtime Data type buffer should also work. So I used API AllocateRuntimePages() to allocate buffer in https://github.com/tianocore/edk2/commit/9a76c7945b762ed8abed3b917aa6217846ae1918 and consume the buffer in https://github.com/tianocore/edk2/commit/e939ecf6c19f932535d073e383d016e8bf2e8ee7. Recently we found that if the buffer type is Runtime Data instead of AcpiNvs, BSOD issue happened after boot into OS.
So this commit is to Allocate EfiACPIMemoryNVS buffer for TCG2 usage in SMM to align with the initial code logic.
Boot on Intel …

Allocate EfiACPIMemoryNVS buffer for TCG2 related usage in Tcg2ConfigPeim

---

IntelFsp2Pkg/FspSecCore/SecFsp.c
IntelFsp2Pkg/FspSecCore/X64/FspApiEntryT.nasm

MCUD Data Region Length(DATA_LEN_OF_MCUD) pushed to stack is incorrect for 64-bit. This commit inputs the correct Data Region Length for the MCUD Section.
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4793
N/A
N/A

IntelFsp2Pkg: Correcting Data Region Length of MCUD section

---

ArmPlatformPkg/PrePeiCore/PrePeiCore.c
ArmPlatformPkg/Sec/Sec.c

PrePeiCore and Sec directly write the firmware version to the serial port.
They relies on another component to initialize the serial port, however
in certain configurations (such as release builds that don't use a
DebugLib that initializes the serial port), the serial port can be
uninitialized at this point, causing a crash when SerialPortWrite
is called here.
This patch updates PrePeiCore and Sec to call SerialPortInitialize before
calling SerialPortWrite directly, which follows the pattern of
other serial port writes. It is accepted to call the initialization
routine multiple times, it is supposed to dump out if the serial
port is already initialized.
- Examples: Does it add a new library class or move a …

ArmPlatformPkg: Initialize Serial Port Before Writing

---

OvmfPkg/LoongArchVirt/Library/CpuMmuInitLib/CpuMmuInit.c

Since the PGD series registers are in an unknown state when reset, some simulators will hang when restarting if these registers are not cleared, so they are cleared in this patch.
Start the VM with an OS and reboot in the OS and it will hang. Apply this patch and it will work fine.
N/A

OvmfPkg/LoongArchVirt: Clear the PGD series registers

---

MdePkg/Include/Library/FdtLib.h
MdePkg/Library/BaseFdtLib/FdtLib.c

This adds FdtNodeOffsetByCompatible() to support finding the offset of the first node with a given 'compatible' value after an offset.

MdePkg/BaseFdtLib: Add FdtNodeOffsetByCompatible()

---

MdeModulePkg/Core/Dxe/Misc/MemoryAttributesTable.c

The Memory Attributes Table is generated by fetching the EFI memory map and splitting entries which contain loaded images so DATA and CODE sections have separate descriptors. The splitting is done via a call to SplitTable() which
marks image DATA sections with the EFI_MEMORY_XP attribute and CODE sections with the EFI_MEMORY_RO attribute when
splitting. After this process, there may still be EfiRuntimeServicesCode regions which did not have their attributes set because they are not part of loaded images.
This patch updates the MAT EnforceMemoryMapAttribute logic to set the access attributes of runtime memory regions which are not part of loaded images (have not had their access attributes set). The attributes of the code regions will be read-only and no-execute because the UEFI spec …

MdeModulePkg: MAT Set RO/XP on Code/Data Sections Outside Image Memory

---

MdeModulePkg/Core/Dxe/Gcd/Gcd.c

Currently whenever gDS->SetMemorySpaceCapabilities() is called, it attempts to set the corresponding attributes in the gMemoryMap descriptor. However, gMemoryMap only contains entries from GCD types EfiGcdMemoryTypeSystemMemory and EfiGcdMemoryTypeMoreReliable, so for all other types a failure is reported in the code. This is a failure that is expected, so it does not provide value and can lead to real failures being ignored.
This patch updates the gDS->SetMemorySpaceCapabilities() code to only call into updating gMemoryMap if the GCD type is SystemMemory or MoreReliable, to avoid spurious errors being reported. This also avoids the expensive operation of searching through gMemoryMap for entries we know we will fail to find.
- **Breaking change** - Does this PR cause a break in build or …

MdeModulePkg: Gcd: Only Update gMemoryMap Attributes if Correct GCD Type

---

MdeModulePkg/Bus/Pci/NonDiscoverablePciDeviceDxe/NonDiscoverablePciDeviceIo.c

When allocating memory for a non-discoverable PCI device's IO, the current core code removes the XP attribute, allowing code to execute from that region. This is a security vulnerability and unneeded. This change updates to mark the region as XP when allocating memory for the non-discoverable PCI device.
These allocations in this function are limited to `EfiBootServicesData` and `EfiRuntimeServicesData`, which we expect to be XP.
- Examples: Unit tests or …

MdeModulePkg NonDiscoverablePciDeviceIo: MMIO Memory XP By Default

---

OvmfPkg/Library/PlatformInitLib/MemDetect.c
OvmfPkg/Library/PlatformInitLib/PlatformInitLib.inf
OvmfPkg/Library/PlatformInitLib/X64/Paging.nasm

There are a number of mostly older guests such as RHEL-7 which do not
support 5-level paging.  This patch adds support for switching from
5-level paging mode back to 4-level paging mode.  This is done in PEI,
after inspecting the address space needed (installed memory and
reservations configured via fw_cfg).
By default small guests (which need less than 1 TB) will use 4-level
paging mode.  There is a fw_cfg override though, so it is possible to
force the one or the other this way:
qemu-system-x86_64 -fw_cfg name=opt/org.tianocode/PagingLevel,string=5

OvmfPkg/PlatformInitLib: allow switching to 4-level paging

---

OvmfPkg/ResetVector/X64/OvmfSevMetadata.asm

When launching a SEV-SNP VM, the ROM is not all that must be measured. The OvmfSevMetadata sections describe ranges of memory that must be measured with different types than PAGE_TYPE_NORMAL, except one. The SevSnpKernelHashes page is also PAGE_TYPE_NORMAL, but is populated by the VMM from configuration data that is separate from the OVMF build itself. To more compactly provide reference values for the measurement of the firmware separately from the kernel hashes, it's advantageous to measure as much known information as possible first.
Whereas VMMs are permitted to measure these sections in any order they prefer, the normative order of how they appear in the .fd is easiest to follow. This change is semantics-preserving. Measurement calculation tools that do not follow the normative …

OvmfPkg: Move kernel hashes section to end

---

CryptoPkg/Library/OpensslLib/OpensslLibAccel.inf
CryptoPkg/Library/OpensslLib/OpensslLibFullAccel.inf

'asm' is not a keyword in C99, but GCC supports it nonetheless as a GNU extension. So when using Clang, we must specify the gnu99 dialect explicitly, or inline asm blocks using asm() rather than \_\_asm\_\_() will be rejected by the compiler.

CryptoPkg/OpensslLib CLANGDWARF: Use gnu99 C dialect for asm() support

---

CryptoPkg/Library/BaseCryptLibMbedTls/Pk/CryptPkcs7Sign.c
CryptoPkg/Library/BaseCryptLibMbedTls/Pk/CryptTs.c

Clang complains about a couple of variables potentially being uninitialized, and those complaints seem to be valid.

CryptoPkg/BaseCryptLibMbedTls: Fix uninitialized variable errors

---

MdePkg/Library/BaseMemoryLibMmx/BaseMemoryLibMmx.inf
MdePkg/Library/BaseMemoryLibOptDxe/BaseMemoryLibOptDxe.inf
MdePkg/Library/BaseMemoryLibOptPei/BaseMemoryLibOptPei.inf
MdePkg/Library/BaseMemoryLibRepStr/BaseMemoryLibRepStr.inf
MdePkg/Library/BaseMemoryLibSse2/BaseMemoryLibSse2.inf

There are some duplicate source files exits in the INF file, this patch is to remove those duplicate sources.
Basic Build
N/A

MdePkg: Remove duplicate source from BaseMemoryLib INF files

---

SecurityPkg/Library/Tpm2CommandLib/Tpm2Object.c

According issue #5536, exponent is 32 bits but is unmarshaled as 16 bits.
N/A
N/A

SecurityPkg: Fix exponent unmarshaled as 16 bits

---

MdeModulePkg/Universal/Variable/RuntimeDxe/VariableStandaloneMm.c
MdeModulePkg/Universal/Variable/RuntimeDxe/VariableStandaloneMm.inf

In Standalone MM, there is no notification to MM drivers that variable write is ready. Install gSmmVariableWriteGuid into MM handle database for the notification.
- Examples: Crypto algorithm …

MdeModulePkg/VariableStandaloneMm: Notify variable write ready in MM

---

SecurityPkg/Library/Tpm2CommandLib/Tpm2Object.c

According issue #5509, case TPM_ALG_KEYEDHASH is missing the break statement.
N/A
N/A

SecurityPkg: Fix break missing at TPM_ALG_KEYEDHASH case

---

MdePkg/Library/UefiDevicePathLib/DevicePathToText.c

DevPathToTextUsbWWID allocates a separate copy of the SerialNumber string to append a null terminator if the original string is not null terminated.  However, by using AllocateCopyPool, it tries to copy 'Length + 1' words from the existing string containing 'Length' characters into the target string.  Split the copy out to only copy 'Length' characters instead.
This was reported by GCC's -Wstringop-overread when compiling a copy of this routine included in a library on FreeBSD.
Signed-off-by: John Baldwin <jhb@FreeBSD.org>

MdePkg: Fix a buffer overread.

---

MdePkg/Include/IndustryStandard/SmBios.h
ShellPkg/Library/UefiShellDebug1CommandsLib/SmbiosView/PrintInfo.c

The patch adds new socket type (Type 4, Offset 32h) for SMBIOS Type4 and also update SmbiosView PrintInfo.c to use the new field name based on SMBIOS v3.8.0.

MdePkg,ShellPkg: Add New Socket Type for SMBIOS Type4

---

OvmfPkg/OvmfPkgIa32.dsc
OvmfPkg/OvmfPkgIa32X64.dsc
OvmfPkg/PlatformPei/IntelTdx.c
OvmfPkg/PlatformPei/Platform.c

Since the PEI Hob service is ready after PEIM loaded, TDVF should build the Hob for TdHob and Cfv event
at first.
Cc: Elena Reshetova <elena.reshetova@intel.com>
Signed-off-by: Ceping Sun <cepingx.sun@intel.com>
- Examples: Does it add a new library class or …

OvmfPkg/PlatformPei: Build gCcEventEntryHobGuid at First

---

MdeModulePkg/Core/Dxe/Image/Image.c
MdeModulePkg/Universal/Disk/DiskIoDxe/DiskIo.c

Adds a call to RestoreTpl() in DiskIo2ReadWriteDisk(). While the current implementation does not technically violate spec on raise/restore TPL, this extra call ensures symmetry between RaiseTpl and RestoreTpl calls, which makes analysis of TPL correctness simpler and permits certain non-standard TPL usages that some platforms require.
Comments out a redundant call to RestoreTpl(). While this does not technically violate spec on raise/restore TPL, TPL should already be at the specified level. This extra call introduces an asymmetry between RaiseTpl and RestoreTpl calls, which makes analysis of TPL correctness more difficult and hampers certain non-standard TPL usages that some platforms require.
<_For each item, place an "x" in between `[` and `]` if true. Example: `[x]` (you can also …

MdeModulePkg: Add extra RestoreTpl() call in DiskIo and StartImage() to maintain TPL raise/restore symmetry

---

ArmVirtPkg/ArmVirt.dsc.inc
ArmVirtPkg/ArmVirtQemu.dsc

Alternative approach to enabling h/w accelerated OpenSSL on ArmVirtPkg, switching to MbedTls in cases where OpenSSL is either overkill, or should be avoided due to its dependency on floating point (32-bit ARM)

ArmVirtPkg: Reorganize crypto dependencies

---

EmulatorPkg/Unix/Host/Host.inf

Add the necessary toolchain override flags for ms_abi and LTO on X64 for the unversioned GCC toolchain profile.
This resolves a runtime segmentation fault.
Resolves issue reported as https://github.com/tianocore/containers/issues/98
Simple build/run test.
N/A

EmulatorPkg: fix X64 Unix/Host segfault with GCC toolchain profile

---

RedfishPkg/Library/PlatformHostInterfaceBmcUsbNicLib/PlatformHostInterfaceBmcUsbNicLib.c
RedfishPkg/Library/PlatformHostInterfaceBmcUsbNicLib/PlatformHostInterfaceBmcUsbNicLib.h
RedfishPkg/Library/PlatformHostInterfaceBmcUsbNicLib/PlatformHostInterfaceBmcUsbNicLib.inf
RedfishPkg/RedfishDiscoverDxe/RedfishDiscoverDxe.c

This patch replaces call of IpmiSubmitCommand() issued
REDFISH_IPMI_BOOTSTRAP_CREDENTIAL_ENABLE IPMI command to check
whether bootstrap credential support enabled or not.
The problem is that in accordance with IPMI spec while handling
such command BMC creates bootstrap account. The credentials of this account
is returned as a response. Obviously in this code the response is not used.
From the other side there is an implementation
of EDKII_REDFISH_CREDENTIAL_PROTOCOL exists and used by
RedfishPlatformCredentialIpmiLib.
By design RedfishPlatformCredentialIpmiLib keeps returned bootstrap
credentials and uses it later. So all services using
EDKII_REDFISH_CREDENTIAL_PROTOCOL instance operates with a same
credentials.
Current design of PlatformHostInterfaceBmcUsbNicLib leads to creation
of two …

RedfishPkg: Switch bmc usb nic lib to credential protocol

---

MdeModulePkg/Bus/Pci/XhciDxe/Xhci.c
MdeModulePkg/Bus/Pci/XhciDxe/XhciReg.c
MdeModulePkg/Bus/Pci/XhciDxe/XhciSched.c

Add missing error checking for malfunctioning XHCI controllers.
Ran OVMF X64 with the XHCI controller enabled.
This change has also been extensively tested internally.
N/A

XhciDxe: Fail the start of malfunctioning XHCI controllers

---

MdeModulePkg/Library/UefiBootManagerLib/BmBoot.c

Currently the following assertion is made in
`BmFindBootOptionInVariable()`:
```c
if (OptionNumber == LoadOptionNumberUnassigned) {
BootOptions = EfiBootManagerGetLoadOptions (&BootOptionCount, LoadOptionTypeBoot);
if (BootOptions == NULL) {
ASSERT (BootOptions != NULL);
return LoadOptionNumberUnassigned;
}
Index = EfiBootManagerFindLoadOption (OptionToFind, BootOptions, BootOptionCount);
```
The reason behind this is to prevent passing a null pointer to `EfiBootManagerFindLoadOption()`.
However, `EfiBootManagerFindLoadOption()` accepts a null pointer argument to be passed as the second argument ('Array') as long as the `Count` argument is `0`.
In that case `LoadOptionNumberUnassigned` will still be returned from the function but an assert is not necessary.
This change updates the …

MdeModulePkg: UefiBootManagerLib: Update assert condition

---

BaseTools/Conf/tools_def.template

Starting with Visual Studio 2019 version 16.10, the /volatileMetadata
option is enabled by default when generating x64 code.
This patch disables the /volatileMetadata option for x64 builds in both
VS2019 and VS2022.
We observed a slight increase in used space for the Firmware volumes in
VS2019. Upon investigation, we found that VS2019 version 16.10 enabled
this feature by default. Disabling /volatileMetadata helps reduce the
used space by approximately 3.5KB by considering the 2 Firmware volumes.
(2KB uncompressed FV and 1.5KB of compressed FV) …

BaseTools: Disable MSVC volatileMetadata for VS2019 and VS2022 for X64

---

MdeModulePkg/Core/Pei/FwVol/FwVol.c

This patch breaks the section processing loop if an invalid section with zero SectionLength is encountered.
Cc: Dhanaraj V <vdhanaraj@ami.com>
Cc: Sachin Ganesh <sachinganesh@ami.com>
This patch breaks the section processing loop if an invalid section with zero SectionLength is encountered.

MdeModulePkg/Core/Pei: Add error handling for Section Length

---

MdePkg/Include/Library/BaseLib.h
MdePkg/Library/BaseLib/BaseLib.inf
OvmfPkg/Library/QemuFwCfgS3Lib/QemuFwCfgS3PeiDxe.c

Refer to the section 2.1 of tdx-virtual-firmware-design-guide spec, APCI S3 is not supported in TDVF.
Therefore, TDVF should not read the S3 status via fw_cfg and always set it as unsupported.
spec: https://cdrdv2.intel.com/v1/dl/getContent/733585
Cc: Elena Reshetova <elena.reshetova@intel.com>
Signed-off-by: Ceping Sun <cepingx.sun@intel.com>
<_Delete lines in \<\> tags before creating …

OvmfPkg/QemuFwCfgS3Lib: Disable S3 detection in TDVF

---

NetworkPkg/Library/DxeNetLib/DxeNetLib.c

Commit 6862b9d538d96363635677198899e1669e591259 makes more explicit the previous logic of [the code](https://github.com/tianocore/edk2/commit/4c4ceb2ceb80c42fd5545b2a4bd80321f07f4345) which uses `mSecureHashAlgorithms`, which is that it is (and was) only a fatal error if all secure algorithms fail.
However the comment updated by this commit seems somewhat incompatible with that recent change, and even with the previous code (which operated as now, just logging different error messages).
This updates the comment to be more compatible with how the code operates.
cc @kraxel @Flickdm 
N/A (comment change only)
N/A

NetworkPkg/DxeNetLib: Update misleading comment

---

MdeModulePkg/Universal/Variable/RuntimeDxe/VariableRuntimeDxe.inf

This was spotted while trying to confirm whether `VariablePolicyDynamicCommand` makes sense to include in all Ovmf modules which can potentially use the `OvmfPkg/Include/*/Shell*.inc` files, for https://github.com/tianocore/edk2/pull/6092#issuecomment-2306961900. (I believe it does.)
If we search the codebase for `&gEdkiiVariablePolicyProtocolGuid` we can find two drivers which install this policy: [`VariableRuntimeDxe`](https://github.com/tianocore/edk2/blob/master/MdeModulePkg/Universal/Variable/RuntimeDxe/VariableRuntimeDxe.inf) (installed in [`VariableDxe.c`](https://github.com/tianocore/edk2/blob/master/MdeModulePkg/Universal/Variable/RuntimeDxe/VariableDxe.c)) and [`VariableSmmRuntimeDxe`](https://github.com/tianocore/edk2/blob/master/MdeModulePkg/Universal/Variable/RuntimeDxe/Variab …

MdeModulePkg/VariableRuntimeDxe: Fix VariablePolicyProtocol PRODUCES

---

.pytool/Plugin/EccCheck/EccCheck.py

The code changes in the patch is for trimming the leading path to the modified directory in the .pytool/EccCheck script. This is necessary when running Ecc on other repositories, such as edk2-platforms, where the platform package is located in a subfolder, like Platform/AMD/AmdPlatformPkg.
The EccCheck script checks for modified directories and expects them to start with the package name.
#
#
if file_dir.split('/')[0] != pkg:
continue
However, if the package name is in a subfolder,
the "git diff" command gives a relative path,
like Platform/AMD, which causes the condition to be false.
"M       Platform/AMD/AmdPlatformPkg/Universal/LogoDxe/Logo.c"
As a result, EccCheck does not happen on modified files.
To fix this issue, the leading path needs to be trimmed so that it starts from the …

.pytool/EccCheck: Trim leading path to modified directory

---

IntelFsp2Pkg/FspSecCore/Fsp24SecCoreM.inf
IntelFsp2Pkg/FspSecCore/FspSecCoreM.inf
IntelFsp2Pkg/FspSecCore/Ia32/Fsp24ApiEntryM.nasm
IntelFsp2Pkg/FspSecCore/Ia32/FspApiEntryM.nasm
IntelFsp2Pkg/FspSecCore/X64/Fsp24ApiEntryM.nasm
IntelFsp2Pkg/FspSecCore/X64/FspApiEntryM.nasm
IntelFsp2Pkg/IntelFsp2Pkg.dec
IntelFsp2Pkg/Library/BaseFspCommonLib/FspCommonLib.c
IntelFsp2Pkg/Library/BaseFspSwitchStackLib/BaseFspSwitchStackLib.inf
IntelFsp2Pkg/Library/BaseFspSwitchStackLib/Ia32/Stack.nasm
IntelFsp2Pkg/Library/BaseFspSwitchStackLib/X64/Stack.nasm

A potential issue may happen when FSP creates/changes page table while bootloader doesn't expect page table being changed in FSP. Current, FSP API support to save/restore stack, IDT and general purpose registers. Following the same pattern, add save/restore page table support to solve this issue.
Note that this feature is only impacted FSP API mode, and is controlled by PCD EnableSaveRestorePageTable. For compatibility, the PCD default value is set as FALSE.
- **Tests** - Does this PR include any explicit test …

IntelFsp2Pkg: Support FSP API to save and restore page table

---

StandaloneMmPkg/Drivers/StandaloneMmIplPei/MmFoundationHob.c

When PcdCpuSmmRestrictedMemoryAccess is FALSE, resource HOB should exclude unblocked memory regions.

StandaloneMmPkg/MmIpl: Correct unblocked memory regions attribute

---

MdePkg/Include/IndustryStandard/IpmiNetFnGroupExtension.h

The natural aligmenent seems to be failed on some cases. So, this patch intends to add the pack(1) to ensure the structure aligned with a one-byte boundary.

MdePkg/IpmiNetFnGroupExtension.h: Enforce structure alignment

---

MdePkg/Include/IndustryStandard/Acpi65.h
ShellPkg/Library/UefiShellAcpiViewCommandLib/AcpiParser.h
ShellPkg/Library/UefiShellAcpiViewCommandLib/Parsers/Ras2/Ras2Parser.c
ShellPkg/Library/UefiShellAcpiViewCommandLib/UefiShellAcpiViewCommandLib.c
ShellPkg/Library/UefiShellAcpiViewCommandLib/UefiShellAcpiViewCommandLib.inf

Adding RAS2 support in ACPI 6.5 and appropriate acpiview parsing
Sample platform was created with RAS2 ACPI Table with various ranges of PCC Entries and acpiview was used to verify it parses (based on ACPI 6.5 specifications).
N/A

Acpiview update 6 5 ras2

---

MdePkg/Library/DxeRngLib/DxeRngLib.c
MdePkg/Library/DxeRngLib/DxeRngLib.inf
MdePkg/MdePkg.dec
NetworkPkg/Library/DxeNetLib/DxeNetLib.inf
NetworkPkg/NetworkPkg.dec

Improve the DxeRngLib so that:
- the RNG prototocol is located only once instead of at each
random number generation
- algorithms that are not available on a platform are not called
when trying to generate a random number
- gEfiRngAlgorithmArmRndr support is added
- PcdEnforceSecureRngAlgorithms can be set to allow/avoid non-secure
algorithms
Tested on a Juno. Associated patches to be provided.

MdePkg/DxeRngLib: Refactoring and improvements

---

OvmfPkg/RiscVVirt/RiscVVirt.dsc.inc

RiscVVirt.dsc.inc includes NetworkPkg/NetworkLibs.dsc.inc. However RiscVVirt.dsc.inc is only ever included by RiscVVirtQemu.dsc, which has already included NetworkPkg/Network.dsc.inc, a general include file which brings in all the required includes for Network features at once, including NetworkPkg/NetworkLibs.dsc.inc.
CI
N/A

OvmfPkg/RiscVVirtQemu: Remove non-needed !include line

---

ArmPkg/ArmPkg.dsc

For reasons that are unclear, the Linaro EDK2 CI is throwing errors when building ArmCrashDumpDxe with CLANGDWARF, as the resulting build contains non-adjacet MOVW/MOVT pairs, which cannot be relocated correctly in PE/COFF.
Let's build it only for AARCH64 - its utility on ARM is doubtful anyway.

ArmPkg: Avoid building ArmCrashDumpDxe on ARM

---

UefiPayloadPkg/UefiPayloadEntry/UefiPayloadEntry.c
UefiPayloadPkg/UefiPayloadEntry/UefiPayloadEntry.inf

Set PcdSerialClockRate from SerialPortInfo in UefiPayloadEntry. 
The initial approach was to add a ClockRate field to UNIVERSAL_PAYLOAD_SERIAL_PORT_INFO data struct, but simplified to setting the PCD directly based on feedback from reviewers.
These changes enable the serial clock rate value, which is already passed in from the host firmware, to be used when configuring the serial port for debug output. AMD Zen platform devices require this in order to have functional serial output.
build/boot multiple AMD/Intel devices and verify serial output works for all.
N/A

Set Serial Clockrate based on data parsed from host firmware

---

BaseTools/Source/C/Include/Common/BaseTypes.h

This patch is to sync RETURN_ERROR macro with the
MdePkg/Include/Base.h
Ref: 1a89d9887f MdePkg:Update Return Error Macro in Base.h
Fixing RETURN_ERROR macro.
It is causing problem in Coverity Static analysis tool as we are directly converting the UINT value to INTN.
Changing value from UINT to INTN might cause problema Here we know that the values would not be in loss of data. To increase the code quality and increase the static tool analysis score we have to change it
This patch is to sync RETURN_ERROR macro with the
MdePkg/Include/Base.h
- Examples: Does it …

BaseTools: Update RETURN_ERROR Macro in BaseTypes.h

---

UefiPayloadPkg/PayloadLoaderPeim/FitLib.h
UefiPayloadPkg/UniversalPayloadBuild.py

Align relocation structure item with spec https://universalpayload.github.io/spec/chapter2-payload-image-format.html#loading-process-example
use hex editor to check relocation data content
N/A

UefiPayloadPkg: Align relocation with UPL spec

---

BaseTools/Source/Python/Ecc/Check.py
BaseTools/Source/Python/Ecc/Configuration.py
BaseTools/Source/Python/Ecc/MetaFileWorkspace/MetaFileParser.py
BaseTools/Source/Python/Ecc/c.py
BaseTools/Source/Python/Eot/EotGlobalData.py
BaseTools/Source/Python/Eot/c.py
BaseTools/Source/Python/UPT/Library/CommentParsing.py
BaseTools/Source/Python/UPT/Library/ExpressionValidate.py
BaseTools/Source/Python/UPT/Library/Misc.py
BaseTools/Source/Python/UPT/Library/StringUtils.py
BaseTools/Source/Python/UPT/Parser/DecParserMisc.py
BaseTools/Source/Python/UPT/Parser/InfAsBuiltProcess.py
BaseTools/Source/Python/UPT/Parser/InfDefineSectionParser.py
BaseTools/Source/Python/UPT/Parser/InfParserMisc.py
BaseTools/Source/Python/UPT/PomAdapter/DecPomAlignment.py
BaseTools/Source/Python/UPT/Xml/IniToXml.py
BaseTools/Source/Python/UPT/Xml/PcdXml.py
BaseTools/Source/Python/UPT/Xml/XmlParser.py

In Python 3.12 invalid escape sequences in strings moved from DeprecationWarning to SyntaxWarning (ref https://docs.python.org/3/whatsnew/changelog.html#python-3-12-0-final and search for gh-98401). In a future Python version this will become SyntaxError.
Multiple instances of these SyntaxWarnings are currently printed when running the BaseTools tests using Python 3.12 (though without actually failing the affected tests).
This commit updates all lines which were causing this type of warning.
Typical examples which needed fixing are:
- "BaseTools\Source\Python" representing a path: "\S" and "\P" are invalid escape sequences, therefore left unchanged, therefore the test works (with a warning in Python 3.12). r"BaseTools\Source\Python" represents the same string, but with escapes turned off …

BaseTools: Fix multiple 'invalid escape sequence' warnings in tests

---

ArmPkg/ArmPkg.dsc
ArmVirtPkg/Library/QemuVirtMemInfoLib/QemuVirtMemInfoPeiLib.inf
ArmVirtPkg/Library/QemuVirtMemInfoLib/QemuVirtMemInfoPeiLibConstructor.c
EmbeddedPkg/Drivers/ConsolePrefDxe/ConsolePrefDxe.c
EmbeddedPkg/Drivers/ConsolePrefDxe/ConsolePrefDxe.inf
EmbeddedPkg/Library/AndroidBootImgLib/AndroidBootImgLib.c
EmbeddedPkg/Library/AndroidBootImgLib/AndroidBootImgLib.inf

While working on migrating everything off the atrocious EmbeddedPkg FdtLib which
is facing imminent deletion, I came across some missing and spurious declarations
hidden by the use of that library and it pulling in the same.
Clean up ahead of the big change coming up in a few days.
Compile tested, no functional changes.
N/A

ArmPkg,ArmVirtPkg,EmbeddedPkg: Library use cleanup

---

.pytool/Plugin/UncrustifyCheck/UncrustifyCheck.py

Shows code formatting errors directly in build output. Previously only the filenames were in build output and the user had to look at the test result file either locally or in CI to find details.
It is still recommended that users configure their local environment to run Uncrustify so it can automatically fix problems as opposed to manually correcting code based on the output shown in the terminal. In any case, it is easier to see what is expected now.
Uncrustify reference material:
https://github.com/tianocore/tianocore.github.io/wiki/EDK-II-Code-Formatting https://github.com/tianocore/edk2/tree/master/.pytool/Plugin/UncrustifyCheck#readme
Some logging levels are also updated to refocus log output by current message importance and relevance.
---
**Before**
**After**
- Execute local (and …

.pytool/UncrustifyCheck: Show errors in output

---

MdePkg/Library/BasePeCoffLib/BasePeCoff.c

The RelocDir->Size is a UINT32 value, and RelocDir->VirtualAddress is also a UINT32 value. The current code does not check for overflow when adding RelocDir->Size to RelocDir->VirtualAddress. This patch adds a check to ensure that the addition does not overflow.
In BasePeCoff.c, the PeCoffLoaderRelocateImage() does RelocDir→VirtualAddress + ReloDir→Size- 1
inside the function was overflowing and causing memory corruption.
so added the below check for avoiding the memory corruption before calculating the RelocBase and RelocBaseEnd.
if ((RelocDir != NULL) && (RelocDir->Size > 0) && (RelocDir->Size -1 < MAX_UINT32 - RelocDir->VirtualAddress))
With this condition added the max value while adding size and address is always less than MAX_UINT32.
Hence there won’t be integer overflow with …

MdePkg: Fix overflow issue in BasePeCoffLib: PeCoffLoaderRelocateImage

---

.github/scripts/GitHub.py

The project moved from using the `github-actions[bot]` bot account to the `tianocore-assign-reviewers[bot]` account. A check is in place to prevent the "`WARNING: Cannot add some reviewers`" from appearing more than once if nothing has changed in the content it would post.
This change updates the bot account to the current one so the check can work again.
- Verify JSON dump for comment posted by the bot to verify text and account info.
- Example: [PR 6247 comments](https://api.github.com/repos/tianocore/edk2/issues/6247/comments)
N/A

.github/GitHub.py: Update bot in redundant comment check

---

MdePkg/Library/BasePeCoffLib/BasePeCoff.c

This change adds parantheses to the if condition detecting overflow in the PeCoffLoaderRelocateImage function to improve readability.
Follow on change for:
REF!: https://github.com/tianocore/edk2/pull/6249
Booted Locally

MdePkg: Improving readability of CVE patch for PeCoffLoaderRelocateImage

---

StandaloneMmPkg/Core/Dispatcher.c
StandaloneMmPkg/Library/FvLib/FvLib.c

Makes changes to comply with alerts raised by CodeQL.
Most of the issues here fall into the following two categories:
1. Potential use of uninitialized pointer
2. Inconsistent integer width used in loop comparison
Shipped in platforms with Project Mu.
N/A.

StandaloneMmPkg: CodeQL Fixes

---

DynamicTablesPkg/DynamicTables.dsc.inc
DynamicTablesPkg/DynamicTablesPkg.ci.yaml
DynamicTablesPkg/Include/AcpiTableGenerator.h
DynamicTablesPkg/Include/ArchCommonNameSpaceObjects.h
DynamicTablesPkg/Library/Acpi/Common/AcpiSpmiLib/AcpiSpmiLib.inf
DynamicTablesPkg/Library/Acpi/Common/AcpiSpmiLib/SpmiGenerator.c
DynamicTablesPkg/Library/Common/TableHelperLib/ConfigurationManagerObjectParser.c
DynamicTablesPkg/Readme.md
MdePkg/Include/IndustryStandard/ServiceProcessorManagementInterfaceTable.h

Adds ACPI SPMI table generator library.
Updates acpi standard table enum with spmi.
Updates arch common namespace object and parser.
Updates the Readme.
Adds ACPI SPMI table generator library.
Tested on AMD platform and dumped the acpi tables.
N/A

DynamicTablesPkg: Adds SPMI table generator

---

MdeModulePkg/Library/UefiBootManagerLib/BmBootDescription.c
MdeModulePkg/Library/UefiBootManagerLib/InternalBm.h

This generates boot descriptions for SD/MMC devices in the form of:
- "UEFI SanDisk SC128 2A2B1E4F SD Device"
- "UEFI Samsung BJTD4R 7AB3A8DE eMMC User Data"
The manufacturer ID tables are a best-effort, collected from various places and personal testing. They're not complete and may be inaccurate for rebranded cards.

MdeModulePkg/UefiBootManagerLib: Build proper SD/MMC boot descriptions

---

MdePkg/Library/StackCheckLib/Readme.md
MdePkg/MdeLibs.dsc.inc

Commit https://github.com/tianocore/edk2/commit/ac43bbacdef18a6fea6d978e096326ec0805885d
added StackCheckLibNull to MdeLibs.dsc.inc per review requests on the PR:
https://github.com/tianocore/edk2/pull/5957#issuecomment-2246925255
https://github.com/tianocore/edk2/pull/5957#discussion_r1694761065
The PR was adapted to move specifying StackCheckLibNull in every DSC
to MdeLibs.dsc.inc. However, while this works, it does not allow for
a platform to use one of the other StackCheckLibs (such as
StackCheckLibStaticInit) because we get a linker error by having the
compiler defined stack cookie variables defined more than once (once
from StackCheckLibNull in MdeLibs.dsc.inc and the other in the actual
StackCheckLib implementation). Every platform must include MdeLibs.dsc.inc
and there is no way …

MdePkg: Add CUSTOM_STACK_CHECK_LIB Macro

---

MdePkg/Include/Register/RiscV64/RiscVEncoding.h
OvmfPkg/RiscVVirt/RiscVVirt.dsc.inc
UefiCpuPkg/CpuDxeRiscV64/CpuDxe.c
UefiCpuPkg/CpuDxeRiscV64/CpuDxe.h
UefiCpuPkg/CpuDxeRiscV64/CpuDxeRiscV64.inf
UefiCpuPkg/Include/Library/BaseRiscVFpuLib.h
UefiCpuPkg/Library/BaseRiscVFpuLib/BaseRiscVFpuLib.inf
UefiCpuPkg/Library/BaseRiscVFpuLib/RiscVFpuCore.S
UefiCpuPkg/UefiCpuPkg.dec
UefiCpuPkg/UefiCpuPkg.dsc

EDK II build with TLS running on top of QEMU/KVM crashes when reaching the first floating point instruction in the OpenSSL library (https://bugs.launchpad.net/ubuntu/+source/qemu/+bug/2036604). This is due to the floating point unit being in an disabled state (FS bit-field in CSR mstatus).
With the series a library module BaseRiscVFpuLib is added. Here the relevant CSRs are initialized.
In future we can add here the initialization of the vector unit once any library uses it.
Running with QEMU/KVM on SiFive HiFive Premier.
N/A

UefiCpuPkg: RISC-V: Initialize FPU

---

DynamicTablesPkg/Library/Common/AmlLib/AmlEncoding/Aml.c

Without the addition of this cast, the compiler promotes 1 to a UINT32, which leads CodeQL to complain that different size types are being compared.
Running CodeQL, shipping in platforms.
N/A.

DynamicTablesPkg: AmlLib: Fix CodeQL Issue

---

UnitTestFrameworkPkg/Library/UnitTestLib/Assert.c
UnitTestFrameworkPkg/Library/UnitTestLib/Log.c
UnitTestFrameworkPkg/Library/UnitTestLib/UnitTestLib.c
UnitTestFrameworkPkg/PrivateInclude/UnitTestFrameworkTypes.h

Currently, there is a mismatch of allowed string sizes in UnitTestLib. The UT_LOG_* macros allow a string size of 512, but failure messages are constrained to 120 characters and some other string lengths are similarly constrained. 120 characters is too few for some longer error messages, particularly the ones that print out the path to the failing line. This can result in the actual error not getting printed in the log.
This patch updates all UnitTestLib allowed string lengths to be 512 characters.
- **Tests** - …

UnitTestFrameworkPkg: UnitTestLib: Support Failure Strings of 512 Chars

---

FmpDevicePkg/Library/FmpDependencyLib/FmpDependencyLib.c

FmpVersionsCount is a UINTN while the loop index variable compared against it is a UINT8. This can lead to an overflow of the loop index for FmpVersionsCount values larger than UINT8_MAX. This change makes Index a UINTN to match in width.
- FmpDevicePkg build and CI
- CodeQL against FmpDevicePkg
N/A

FmpDevicePkg/FmpDependencyLib: Fix potential overflow in loop

---

BaseTools/Plugin/CodeQL/CodeQlAnalyzePlugin.py

For the CodeQl `AuditOnly` flag,
prioritize Plugin settings over global settings.
This patch adjusts the logic for the global `AuditOnly` setting, placing it before the Plugin setting code.
This ensures that Plugin settings take precedence over global settings.
Cc: Joey Vagedes <joey.vagedes@gmail.com>
This patch adjusts the logic for the global `AuditOnly` setting, placing it before the Plugin setting code.
This ensures that Plugin settings take precedence over global settings.
- **Security** - …

BaseTools/CodeQl: Give preference to Plugin settings

---

BaseTools/Scripts/SetupGit.py

This fixes missing 'edk2-test' in the choices of the repo name option.
Tested with running BaseTools/Scripts/SetupGit.py with the repo name edk2-test.

BaseTools/SetupGit.py: Fix invalid choice 'edk2-test'

---

UefiPayloadPkg/UefiPayloadPkg.ci.yaml
UefiPayloadPkg/UefiPayloadPkg.dsc
UefiPayloadPkg/UefiPayloadPkg.fdf
UefiPayloadPkg/UniversalPayloadBuild.py

Introduce Secure Boot functionality within UefiPayloadPkg by adding necessary modules and configurations. A new build flag, `SECURE_BOOT_ENABLE`, is introduced to control the activation of Secure Boot.
This patch also overrides values in SecurityPkg to enforce image verification from all sources.
A new FV (`SECURITY_FV`) for security modules is added for components and the firmware volume sizes to accommodate additional Secure Boot components.

UefiPayloadPkg: Add Secure Boot support

---

OvmfPkg/Library/SmmCpuPlatformHookLibQemu/SmmCpuPlatformHookLibQemu.c
UefiCpuPkg/Include/Library/SmmCpuPlatformHookLib.h
UefiCpuPkg/Library/SmmCpuPlatformHookLibNull/SmmCpuPlatformHookLibNull.c
UefiCpuPkg/PiSmmCpuDxeSmm/MpService.c

This patch is to add SmmCpuPlatformHookBeforeMmiHandler interface in SmmCpuPlatformHookLib.
The new API can be used to perform the platform specific items before MMI Handler. For example, Intel can leverage this API to clear the pending SMI bit after all CPUs finish the sync and before the MMI handlers. If so, the the redundant SMI can be avoided after CPU exit from current SMI.
No function impact for open source.

Smmcpu platform hook Before MMI Handler 

---

RedfishPkg/RedfishCredentialDxe/RedfishCredentialDxe.c

This fixes the error 'too many arguments to ClearRedfishServiceList' when building with clang compiler.
```
RedfishPkg/RedfishCredentialDxe/RedfishCredentialDxe.c:920:48: error: too many arguments in call to 'ClearRedfishServiceList' [-Werror]
ClearRedfishServiceList (mCredentialPrivate);
~~~~~~~~~~~~~~~~~~~~~~~                    ^
1 error generated.
```
Compilation with the clang compiler.

RedfishPkg/RedfishCredentialDxe: Fix 'too many arguments' error

---

UnitTestFrameworkPkg/UnitTestFrameworkPkgHost.dsc.inc

Currently EDK2 is supporting VS2022, with VS2022 UnitTestFrameworkPkg build is failing, this patch is to add the VS2022 support for UnitTest
EDK2 UnitTestFrameworkPkg is failing with VS2022 due to UnitTestFrameworkPkgHost.dsc.inc is not having the required DLINK_FLAGS for VS2022.
Confirmed by successful build of UefiCpuPkg\Test\UefiCpuPkgHostTest.dsc
N/A

UnitTestFrameworkPkg: VS2022 Support on UnitTest.

---

MdeModulePkg/Core/Pei/Memory/MemoryServices.c

I recently ran into an AllocatePages() hang. It turns out that AllocatePages() does not account for the Memory Allocation HOB when it makes the decision of allocating out of free memory.
Here is the scenario:
FreeMemoryTop    - 0x71C03000
FreeMemoryBottom - 0x71BDBFD8
=> We have 159,784 bytes left => ~39.0098 pages left.
We attempt to allocate 39 pages. There are enough pages left but allocating those pages requires to allocate a Memory Allocation HOB which needs an extra 48 bytes. But once the pages are allocated, there are only 40 bytes left.
In addition to taking into account the Memory Allocation HOB size, this commit reverses the condition to keep it simple.
<_For each item, place an "x" in between `[` and `]` if …

MdeModulePkg: Fix PeiAllocatePages() corner case

---

MdePkg/Include/Guid/Cper.h

Previous [PR that introduced these definitions](https://github.com/tianocore/edk2/pull/6329) was merged without following naming convention of using EFI_ prefix in definitions in Cper.h. This PR fixes that.
[Issue Description]
In MdePkg/Include/Guid/Cper.h there are multiple definitions regarding CXL that can do use EFI_ prefix in their names
[Resolution]
Rename these definitions in MdePkg/Include/Guid/Cper.h
- No
- No
- No
Builds in CI pass
N/A

MdePkg/Include/Guid: Rename CXL definitions in Cper.h to include EFI_ prefix

---

ShellPkg/Library/UefiShellDebug1CommandsLib/SmbiosView/PrintInfo.c

The patch will correct wrong length offset usage in SMBIOS Type4. For SMBIOS Ver3.6, length should be larger than 0x30. For SMBIOS Ver3.8, length should be larger than 0x32.

ShellPkg/SmbiosView: Correct wrong length offset usage in SMBIOS Type4

---

MdeModulePkg/Bus/Usb/UsbNetwork/UsbCdcEcm/UsbEcmFunction.c
MdeModulePkg/Bus/Usb/UsbNetwork/UsbCdcNcm/UsbNcmFunction.c
MdeModulePkg/Bus/Usb/UsbNetwork/UsbRndis/UsbRndisFunction.c
MdeModulePkg/Include/Protocol/UsbEthernetProtocol.h

- Class specific types for interface and endpoint are generic
- Definitions are in IndustryStandard/Usb.h
- Remove type redefinition
- Update references to the descriptor types
N/A

USB Class specific definitions

---

ArmPkg/ArmPkg.ci.yaml

Library/CompilerIntrinsicsLib was moved from ArmPkg to MdePkg. Update the ci.yaml files to match.
This fixes the error during "stuart_ci_build":
ERROR - EccCheck.IgnoreInf ->
Build/.pytool/Plugin/EccCheck/ArmPkg/Library/CompilerIntrinsicsLib not found in filesystem.  Invalid ignore files
N/A

Update CI config following CompilerIntrinsicsLib move from ArmPkg

---

DynamicTablesPkg/Library/Acpi/Common/AcpiFadtLib/X64/X64FadtGenerator.c

Copy the provided configuration data for
PM1 event block.
Corrects the X64 FADT table by copying the PM1a event block
information from configuration data.
tested on AMD X64 platform
N/A

DynamicTablesPkg: Update X64 FADT XPm1aEvtBlk

---

MdePkg/Include/IndustryStandard/SmBios.h
ShellPkg/Library/UefiShellDebug1CommandsLib/SmbiosView/PrintInfo.c

Updated Type 4 Info as per Smbios 3.8.0
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4861
Added PROCESSOR_FAMILY_NAME support in MdePkg and ShellPkg.
Signed-off-by: Revathy <revathyv@ami.com>

Smbios Spec V 3.8.0 MdePkg and Shellpkg changes

---

MdePkg/Include/Guid/Cper.h

Fixes a19f50bb95f70c378488ed5459a1153730c0ef76 
[Issue Description]
CXL_ERROR_PCIE_DEV_ID in Cper.h was renamed to EFI_CXL_ERROR_PCIE_DEV_ID, but EFI_CXL_COMPONENT_EVENT_LOG still uses previous name.
[Resolution]
Modify EFI_CXL_COMPONENT_EVENT_LOG to use EFI_CXL_ERROR_PCIE_DEV_ID

MdePkg/Include/Guid: Fix EFI_CXL_COMPONENT_EVENT_LOG in Cper.h

---

BaseTools/Source/C/GenFw/Elf64Convert.c

GenFw relies on static ELF relocation tables emitted by the linker (via the --emit-relocs command line switch). These are different from the dynamic relocations that a dynamic loader uses: static relocations are emitted by the compiler/assembler, and consumed by the linker to construct the executable. Only when the load address is a priori unknown are dynamic relocations emitted, by the linker, in a format that the dynamic loader can consume.
This distinction is relevant because only dynamic relocations cover the GOT, and so GOT based indirections are better avoided. Unfortunately, there are cases where the toolchain insists on emitting GOT based symbol references, and so we have to deal with them in one of 2 ways:
- replace GOT based symbol references with direct references, so that the …

BaseTools/GenFw X64: Detect GOTCPRELX relaxations applied by LLD

---

EmbeddedPkg/EmbeddedPkg.dsc
EmbeddedPkg/Universal/MmcDxe/MmcDebug.c

Add -DMDEPKG_NDEBUG to EmbeddedPkg CC_FLAGS for RELEASE build. Although EmbeddedPkg normally provides components to other packages, it is less surprising if its own build defines MDEPKG_NDEBUG when consuming packages normally would.
Additionally remove MDEPKG_NDEBUG dependent code which is no longer needed given update of 'null' debug macros in ae83c6b7fd83a5906e016a32027c1bcd792a624e to explicitly mark debug-only code as discarded; correctly mark as STATIC the two arrays within the updated code block.
Local build.
N/A

EmbeddedPkg: MDEPKG_NDEBUG fixes

---

.pytool/Plugin/UncrustifyCheck/Readme.md
.pytool/Plugin/UncrustifyCheck/UncrustifyCheck.py

To simplify automatic formatting of new code, this feature lets a local developer specify the `UNCRUSTIFY_IN_PLACE=TRUE` parameter on the command line to automatically format files.
This is particularly useful when a large amount of new code needs to be formatted in batch.
See the readme for more details.
- Uncrustify execution with and without the new option enabled
- Use the new option if useful for a local development scenario

.pytool/UncrustifyCheck: Add a in-place option

---

FatPkg/EnhancedFatDxe/Info.c
FatPkg/FatPei/FatLiteApi.c

REF:https://bugzilla.tianocore.org/show_bug.cgi?id=1559
Initializes the variable to prevent an uninitialized variable
warning in Visual Studio with C4701 enabled.
- FatPkg build with VS2017, VS2019, VS2022, GCC
N/A

FatPkg: Fix potentially uninitialized variable

---

MdeModulePkg/Universal/Console/TerminalDxe/TerminalConIn.c

MdeModulePkg/TerminalDxe: Return success if device not support SetControl
Some serial device may not support SetControl.
Ignore the error from SetControl if EFI_UNSUPPORTED is return.
We see some compatible issue related to PR: https://github.com/tianocore/edk2/pull/6106/files
this patch can help on the compatible issue with some serial drivers which do not support SetControl.
<_Describe the test(s) that were …

MdeModulePkg/TerminalDxe: Return success if device not support SetControl

---

IntelFsp2WrapperPkg/FspsWrapperPeim/FspsWrapperPeim.c

Return from `FspsWrapperInitDispatchMode()` if a buffer allocation fails instead of attempting to dereference the pointer.
- IntelFsp2WrapperPkg build and CI
- Intel physical platform boot with change (FSP dispatch mode)
- N/A

IntelFsp2WrapperPkg: Prevent null pointer dereference

---

MdeModulePkg/Universal/HiiDatabaseDxe/Database.c
MdeModulePkg/Universal/HiiDatabaseDxe/HiiDatabaseDxe.inf

REF:https://bugzilla.tianocore.org/show_bug.cgi?id=4857
NVS needs to support both authenticated and non-authenticated header for NV region. PcdNvStoreDefaultValueBuffer can have variables with data format of the type Authenticated variable storage and this change provides the support to differentiate between the normal variable storage and authenticated variable storage for the hii database to consume and update the setup variables accordingly
By changing the variable's header format from Normal variable header to Authenticated variable header in the NvStoreDefaultValueBuffer and checking if the Hii database is able identify and consume and update the setup variables accordingly.

MdeModulePkg: adding support for authenticated variable storage data format

---

UefiCpuPkg/Library/MmUnblockMemoryLib/MmUnblockMemoryLib.c

Check if input buffer range unblockable:
1.The input buffer range to block should be totally covered by one or multi memory allocation HOB
2.All the memory allocation HOB that overlap with the input buffer range should be EfiRuntimeServicesData, EfiACPIMemoryNVS or EfiReservedMemoryType.
Tested in Intel internal server platform with the X86 standalone MM env and successfully booted into shell
Tested in QSP platform with the X86 standalone MM env and successfully booted into os

UefiCpuPkg/MmUnblockMemoryLib: Check if buffer range is valid

---

ArmVirtPkg/ArmVirtKvmTool.dsc

Clang build for ArmVirtPkg/ArmVirtKvmTool.dsc fails with the below warning:
|  ld.lld: error: duplicate symbol: PciExpressRegisterForRuntimeAccess
|  ld.lld: error: duplicate symbol: GetPciExpressBaseAddress
|  ld.lld: error: duplicate symbol: PciExpressRead8
|  ld.lld: error: duplicate symbol: PciExpressWrite8
|  ld.lld: error: duplicate symbol: PciExpressOr8
|  ld.lld: error: duplicate symbol: PciExpressAnd8
|  ld.lld: error: duplicate symbol: PciExpressAndThenOr8
|  ld.lld: error: duplicate symbol: PciExpressBitFieldRead8
|  ld.lld: error: duplicate symbol: PciExpressBitFieldWrite8
|  ld.lld: error: duplicate symbol: PciExpressBitFieldOr8
|  ld.lld: error: duplicate symbol: PciExpressBitFieldAnd8
|  ld.lld: error: duplicate symbol: PciExpressBitFieldAndThenOr8
|  ld.lld: error: …

ArmVirtPkg: KvmTool: Fix clang linker error

---

UefiPayloadPkg/Library/BuildFdtLib/X86_BuildFdtLib.c
UefiPayloadPkg/Library/CustomFdtNodeParserLib/CustomFdtNodeParserLib.c
UefiPayloadPkg/Library/CustomFdtNodeParserLib/CustomFdtNodeParserLib.inf
UefiPayloadPkg/Library/FdtParserLib/FdtParserLib.c

This PR mainly adding 1 feature and 1 bug fix:
1. Support building FDT reserved-memory nodes for PlatformInit pre-built SMBIOS tables and ACPI tables.
2. PciSegmentRead/Write ASSERT issue in single segment scenario:
a. pci-rb missing reg() property
b. (defer to separate PR as this may need more time) the PciSegmentInfoLibAcpiBoardInfo.c->RetrieveMultiSegmentInfoFromHob() did not handle single segment properly.
- Examples: Does it add a new library class or move a module …

Upl update 2

---

MdeModulePkg/Bus/Pci/SataControllerDxe/SataController.c
MdeModulePkg/Bus/Pci/SataControllerDxe/SataController.h
MdeModulePkg/Bus/Pci/SataControllerDxe/SataControllerDxe.inf

REF:https://bugzilla.tianocore.org/show_bug.cgi?id=4858
Ph52a PCIE to SATA card inserted on Intel MTL/ARL causes system hanged.
Root cause of this issue is because Ph52a's driver only uses DevicePath
protocol alone and EDK2 driver only uses PciIo protocol alone. Both drivers
start and try to manage SATA controller.
Ph52a PCIE to SATA card inserted on Intel MTL/ARL did not causes system hanged. And SATA devices …

MdeModulePkg: SataControllerSupported checks DevicePath Protocol

---

.gitmodules
ReadMe.rst
UnitTestFrameworkPkg/ReadMe.md

Change subhook url from https://github.com/Zeex/subhook to https://github.com/tianocore/edk2-subhook because old url is no longer available.
Also align .gitmodules file to use consistent LF line endings.
Test with edk2 CI and local clone new edk2 env and verify subhook files and sha match 83d4e1ebef3588fae48b69a7352cc21801cb70bc
N/A

UnitTestFrameworkPkg: Use TianoCore mirror of subhook submodule

---

CryptoPkg/Library/BaseCryptLib/SysCall/RuntimeMemAllocation.c

Openssl 3.0.15 has a larger memory footprint.
Updating from EDK 2022.2 (openssl 1.1.j) to 2024.2 (openssl 3.0.15) causes our EFI provisioning application[1] to fail due to an out of memory condition.
On inspection, at the time of that fault, 2022.2 had an additional 900 pages. This is why this patch proposes the increase of the ScratchMemory buffer by that same ammount.
[1] https://git.kernel.org/pub/scm/linux/kernel/git/jejb/efitools.git
- **Security**  Since this addresses OpenSSL errors that would be caused due to running out of memory, it has security implications.
https://git.kernel.org/pub/scm/linux/kernel/git/jejb/efitools.git
0) Build efitools and generate LockDown.efi
1) Using OVMF
Execute LockDown.efi from a systemd-boot menu
Without the fix, authenticating the proposed PK …

CryptoPkg: Increase ScratchMemory buffer for openssl 3.0.15

---

CryptoPkg/CryptoPkg.dsc
CryptoPkg/Driver/CryptoStandaloneMm.c
CryptoPkg/Driver/CryptoStandaloneMm.inf
CryptoPkg/Library/BaseCryptLibOnProtocolPpi/StandaloneMmCryptLib.c
CryptoPkg/Library/BaseCryptLibOnProtocolPpi/StandaloneMmCryptLib.inf

CryptoPkg: Added MM_STANDALONE support.
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4867
Added MM_STANDALONE support in Driver and BaseCryptLibOnProtocolPpi.
Signed-off-by: Kanagavel S <kanagavels@ami.com>
Added MM_STANDALONE support in CryptoPkg Driver and BaseCryptLibOnProtocolPpi.

CryptoPkg: Added MM_STANDALONE support in CryptoPkg.

---

CryptoPkg/Library/BaseCryptLib/Pk/CryptX509.c

Fix serial number read overrun detected with use of address sanitizer in host based unit tests in draft PR https://github.com/tianocore/edk2/pull/6408
Run host based unit tests with address sanitizer enabled and the issue is resolved with this change

CryptoPkg/BaseCryptLib: Fix serial number read overrun

---

MdePkg/Test/UnitTest/Library/DevicePathLib/TestDevicePathLib.c

Unit test checks if AppendDevicePathInstance() returns NULL. In those cases, AppendDevicePathInstance() does not allocate a device path, so the call to FreePool() must not be performed.
Detected with use of address sanitizer in host based unit tests in draft PR https://github.com/tianocore/edk2/pull/6408
Run host based unit tests with address sanitizer enabled and the issue is resolved with this change

MdePkg/Test/DevicePathLib: Remove FreePool(NULL)

---

UefiCpuPkg/Library/MtrrLib/UnitTest/Support.c

Change conditional check to check the array index before reading the array member to prevent read past end of buffer.
Detected with use of address sanitizer in host based unit tests in draft PR https://github.com/tianocore/edk2/pull/6408
Run host based unit tests with address sanitizer enabled and the issue is resolved with this change

UefiCpuPkg/MtrrLib: Fix unit test read overflow

---

NetworkPkg/Dhcp6Dxe/GoogleTest/Dhcp6IoGoogleTest.cpp

* EFI_DHCP6_DUID structure declares Duid[1], so the size of that structure is not large enough to hold an entire Duid. Instead, compute the correct size to allocate an EFI_DHCP6_DUID structure.
* Dhcp6AppendOption() takes a length parameter that in network order. Update test cases to make sure a network order length is passed in. A value of 0x0004 was being passed in and was then converted to 0x0400 length and buffer overflow was detected.
Detected with use of address sanitizer in host based unit tests in draft PR https://github.com/tianocore/edk2/pull/6408
- Examples: …

NetworkPkg/Dhcp6Dxe: Fix sanitizer issues

---

MdePkg/Include/Register/Amd/ArchitecturalMsr.h
MdePkg/Include/Register/Amd/Msr.h
UefiCpuPkg/Library/MmSaveStateLib/AmdMmSaveState.c
UefiCpuPkg/Library/SmmCpuFeaturesLib/AmdSmmCpuFeaturesLib.c
UefiCpuPkg/Library/SmmRelocationLib/AmdSmramSaveStateConfig.c
UefiCpuPkg/Library/SmmRelocationLib/InternalSmmRelocationLib.h
UefiCpuPkg/Library/SmmRelocationLib/SmramSaveStateConfig.c
UefiCpuPkg/PiSmmCpuDxeSmm/SmmProfile.c
UefiCpuPkg/PiSmmCpuDxeSmm/SmmProfileInternal.h

Added definition of AMD specific public MSRs:
1. SMBASE
2. SMM_ADDR
3. SMM_MASK
Replaced local Msr defines where applicable by including `Register/Amd/Msr.h`
---
Cherry-picked first commit from:
https://github.com/microsoft/mu_basecore/commit/2e2958c6d448fe8a31c71528ff954279c2bfeaf1
---
Tested in Project MU
N/A

MdePkg: Added definition of AMD specific public MSRs

---

PcAtChipsetPkg/PcatRealTimeClockRuntimeDxe/PcRtc.c
PcAtChipsetPkg/PcatRealTimeClockRuntimeDxe/PcRtc.h

<_Describe how these changes should …

Fix rtc drift issue

---

MdePkg/Library/DxeRngLib/DxeRngLib.c
NetworkPkg/Library/DxeNetLib/DxeNetLib.c

Both DxeRngLib and DxeNetLib have a mSecureHashAlgorithms variable.
This breaks the ArmVirtPkg builds with iscsi support enabled.
Fix that by making the variables static in both libraries.
- **MdePkg/DxeRngLib: make mSecureHashAlgorithms static**
- **NetworkPkg/DxeNetLib: make mSecureHashAlgorithms static**

fix mSecureHashAlgorithms name clash

---

UefiCpuPkg/CpuDxe/CpuMp.c
UefiCpuPkg/CpuMpPei/CpuMpPei.c
UefiCpuPkg/Library/CpuCommonFeaturesLib/MachineCheck.c
UefiCpuPkg/Library/CpuExceptionHandlerLib/PeiCpuException.c
UefiCpuPkg/Library/MpInitLib/AmdSev.c
UefiCpuPkg/Library/MpInitLib/DxeMpInitLib.inf
UefiCpuPkg/Library/MpInitLib/DxeMpLib.c
UefiCpuPkg/Library/MpInitLib/MpLib.c
UefiCpuPkg/Library/MpInitLib/MpLib.h
UefiCpuPkg/Library/MpInitLib/PeiMpInitLib.inf
UefiCpuPkg/Library/MpInitLib/PeiMpLib.c
UefiCpuPkg/Library/MtrrLib/MtrrLib.c
UefiCpuPkg/Library/RegisterCpuFeaturesLib/CpuFeaturesInitialize.c
UefiCpuPkg/Library/RegisterCpuFeaturesLib/RegisterCpuFeaturesLib.c
UefiCpuPkg/PiSmmCpuDxeSmm/MpService.c
UefiCpuPkg/PiSmmCpuDxeSmm/PiSmmCpuDxeSmm.c
UefiCpuPkg/PiSmmCpuDxeSmm/X64/PageTbl.c
UefiCpuPkg/PiSmmCpuDxeSmm/X64/SmmFuncsArch.c
UefiCpuPkg/UefiCpuPkg.dsc

Clone of PR #6397 to address issue with merging
Resolves several issues in UefiCpuPkg related to:
1. Unchecked returns leading to potential NULL or uninitialized access.
2. Potential unchecked integer overflows.
3. Incorrect comparison between integers of different sizes.
Shipped in platforms with Project Mu.
N/A

UefiCpuPkg: Fix unchecked returns and potential integer overflows V2

---

MdeModulePkg/Core/DxeIplPeim/Ia32/DxeLoadFunc.c
MdeModulePkg/Core/DxeIplPeim/X64/VirtualMemory.c
MdeModulePkg/Core/DxeIplPeim/X64/VirtualMemory.h
UefiPayloadPkg/UefiPayloadEntry/Ia32/DxeLoadFunc.c
UefiPayloadPkg/UefiPayloadEntry/X64/VirtualMemory.c
UefiPayloadPkg/UefiPayloadEntry/X64/VirtualMemory.h

MedModulePkg/DxeIplPeim: Fix pagetable protection region in 5 leve paging
REF:https://bugzilla.tianocore.org/show_bug.cgi?id=4873
Currently the function does not cover the 5 level paging case. it will caused pagetable protection region to be set incorrectly. This patch do the enhancement and with the patch protection region has been set correctly.
CC: Ray Ni [ray.ni@intel.com](mailto:ray.ni@intel.com)
##Description
Currently the function does not cover the 5 level paging case. it will casued pagetable protection region set incorrectly. This patch do the enhancemant and with the patch protection region has been set correctly.
##How This Was Tested
we test on real platform with below condition:
5level pagetable +UPL, pagetable region been protected correctly.
4level pagetable+UPL, pagetable …

[edk2-stable202411] MdeModulePkg/DxeIplPeim: Fix pagetable protection region in 5 leve paging

---

MdePkg/Library/SmmPciExpressLib/SmmPciExpressLib.inf

The PCD token, PcdPciExpressBaseAddress is referred in the constructor. If the token is defined as PcdsDynamic type, the PCD function that gets the token value uses the gBS service to locate PCD protocol internally. In this case, it is possible for the function to be called before initializing gBS variable, then cause a system hang due to gBS variable. Need to ensure the availability of gBS variable.
It was …

MdePkg/SmmPciExpressLib: Ensure gBS variable for the constructor

---

MdeModulePkg/Library/HobPrintLib/HobPrintLib.inf

gEfiHobMemoryAllocModuleGuid is referenced in the HobPrintLib, but it is not defined in the INF file, causing an unresolved external error when the module is consumed by code.
Modified module to consume this library, experienced build error.
Corrected INF, module compiled correctly.
N/A

MdeModulePkg HobPrintLib: Add Guid to Guids section.

---

NetworkPkg/Ip6Dxe/Ip6Impl.c
NetworkPkg/SnpDxe/Get_status.c
NetworkPkg/SnpDxe/Transmit.c

This patch fixes a few instances of error cases in NetworkPkg returning after a RaiseTpl call without restoring the TPL first.
Code review.
N/A.

NetworkPkg: Restore TPL Before Return

---

DynamicTablesPkg/Library/FdtHwInfoParserLib/Arm/Gic/ArmGicCParser.c

There are two issues in the GIC FDT parsing code:
- the GICC Flags 'Enabled' bit is overwritten when parsing the VGIC Maintenance Interrupt, whose trigger type occupies another bit in the same field;
- only the first CPU's Flags field is updated.
This breaks both SMP boot and KVM support on Linux, given that the boot CPU is disabled in the MADT, and the VGIC maintenance interrupt is set to 0x0 on all others.
Fix this, by OR'ing the trigger type into the field, and by iterating over all discovered CPUs.

DynamicTablesPkg/ArmGicCParser: Parse VGIC interrupt for all CPUs

---

ShellPkg/Application/Shell/ShellParametersProtocol.c

The UpdateArgcArgv() function documentation says "If OldArgv or OldArgc is NULL then that value is not returned."
However, only OldArgc was checked for NULL. In case OldArgc was non-NULL, but OldArgv was NULL, it could cause a segmentation fault.
Not tested. Not sure if any of the current code calls UpdateArgcArgv() with OldArgc non-NULL and OldArgv NULL.
N/A

ShellPkg: Fix copy-pasto in NULL check to prevent segfault

---

OvmfPkg/Library/PlatformInitLib/Platform.c
OvmfPkg/Library/PlatformInitLib/PlatformInitLib.inf

Enable x2apic mode in case the number of possible CPUs (including
hotplug-able CPus which are not (yet) online) is larger than 255.

OvmfPkg/PlatformInitLib: enable x2apic mode if needed

---

CryptoPkg/Library/BaseCryptLibMbedTls/SysCall/ConstantTimeClock.c
CryptoPkg/Library/BaseCryptLibMbedTls/SysCall/TimerWrapper.c

BaseCryptLib turn gettimeofday() from a Macro into a function call, apply the same change to BaseCryptLibMbedTls
BaseCryptLib turn gettimeofday() from a Macro into a function call, apply the same change to BaseCryptLibMbedTls
- **Breaking change** - Does this PR cause a break in build or boot behavior? No
- **Security** - Does this PR have a direct security impact? No
- **Tests** - Does this PR include any explicit test code? No
Local build and boot from emulator passed 
N/A

CryptoPkg: Apply gettimeofday() solution to BaseCryptLibMbedTls

---

UefiCpuPkg/PiSmmCpuDxeSmm/NonMmramMapStandaloneMm.c

This commit is to check if the resource HOB range does not exceed the max supported physical address.
The function BuildMemoryMapFromResDescHobs is to build Memory Region from resource HOBs. Then the memory maps will be used during creating or modifying SMM page table. If the resource HOB range exceeds the max supported physical address, then subsequent calling of PageTableMap() will fail.
Tested in Intel internal server platform with x86 standalone MM enabled and succussfully booted into shell

UefiCpuPkg/PiSmmCpuDxeSmm:Check resource HOB range before mapping

---

SecurityPkg/Tcg/Tcg2Config/Tcg2Config.vfr

As TPM2.0 is popular, updating default value for the Setup menu supports a benefit for some systems that have another TPM Setup menu to select TPM2.0 devices (e.g. dTPM, fTPM) depending on platform bios. 
For example, when loading default configuration using F9 key in Setup (Brower Action: SystemLevel), it is possible for them to load an unsynchronized value. If user does not adjust the value before saving Setup, it could influence an unexpected TPM initialization at next boot. Setting TPM2.0 as default value supports the benefit related to the case. …

SecurityPkg/Tcg2Config: Set TPM2.0 for default of Attempt TPM Device

---

.github/scripts/GitHub.py

If a GitHub account has been deleted entirely, a `None` user will be returrned from the GitHub API. This change accounts for a `None` user when querying GitHub APIs for user information.
- Verified flow locally against a PR with no reviewers. The `None` user is ignored as expected.
- N/A

.github: Handle deleted GitHub accounts

---

ArmVirtPkg/ArmVirt.dsc.inc

Refer to this [commit](https://github.com/tianocore/edk2/pull/6147), 32-bit ARM build will failed when `NETWORK_TLS_ENABLE` is `TRUE`.
This change report a error info directly then user can known the `NETWORK_TLS_ENABLE` usage.
And this change is also helpful for #6469
Use `build -p ArmVirtPkg/ArmVirtQemu.dsc -a ARM -t GCC5 -D NETWORK_TLS_ENABLE`, and it will give user a hint directly:
``` …
```

ArmVirtPkg: Report an error if NETWORK_TLS_ENABLE is TRUE on ARM

---

OvmfPkg/Library/PciHostBridgeUtilityLib/PciHostBridgeUtilityLib.c

Currently, PciHostBridgeUtilityGetRootBridgesHostProvided allocates memory
for aperture structures without clearing memory. This causes garbage in
the Translation field, but the Base and Limit fields have the correct
values because they are copied from the HOST_BRIDGE_INFO fields in the
HardwareInfoPciHostBridgeHostBridgeHostBridgeGetApertures function.
```
RootBridge: PciRoot(0x0)
Support/Attr: 70069 / 70069
DmaAbove4G: No
NoExtConfSpace: No
AllocAttr: 3 (CombineMemPMem Mem64Decode)
Bus: 0 - 80 Translation=0
Io: 6000 - FFFF Translation=5E9EB018
Mem: 80000000 - DFFFFFFF Translation=0
MemAbove4G: 600000000000 - 7FFFFFFFFFFF Translation=0
PMem: FFFFFFFFFFFFFFFF - 0 Translation=0
PMemAbove4G: FFFFFFFFFFFFFFFF - 0 Translation=0
```
- **Breaking change** - Does this PR cause a break in build …

OvmfPkg/Library/HardwareInfoLib: Fix memory allocation at PciHostBridgeUtilityGetRootBridgesHostProvided

---

DynamicTablesPkg/DynamicTables.dsc.inc
DynamicTablesPkg/DynamicTablesPkg.ci.yaml
DynamicTablesPkg/Include/X64NameSpaceObjects.h
DynamicTablesPkg/Library/Acpi/Common/AcpiSsdtCpuTopologyLib/SsdtCpuTopologyLib.inf
DynamicTablesPkg/Library/Acpi/Common/AcpiSsdtCpuTopologyLib/X64/X64SsdtCpuTopologyGenerator.c
DynamicTablesPkg/Library/Acpi/X64/AcpiMadtLib/AcpiMadtLib.inf
DynamicTablesPkg/Library/Acpi/X64/AcpiMadtLib/MadtGenerator.c
DynamicTablesPkg/Library/Common/TableHelperLib/ConfigurationManagerObjectParser.c
DynamicTablesPkg/Readme.md

Introduce support for generating ACPI CPU SSDT table for the X64 architecture.
This PR contains two patches
Patch 1) Adds ACPI MADT generator library for X64 platform.
which handles various APIC structures within a system,
including Local APIC, IO APIC, Interrupt Source Override, and Local APIC NMI.
Patch 2) Implements the X64 support for existing ACPI CPU SSDT topology generator library.
Adds X64 related supporting functions.
Creates the ACPI cpu device object. …

DynamicTablesPkg: Generates X64 MADT and CPU SSDT Topology Table

---

EmulatorPkg/EmuBlockIoDxe/EmuBlockIo.c

BlockIo2 Read/Write/Flush APIs should signal the token's event when the I/O operation completes, but the Emulator APIs do not. As a result, any code that tries to implement async I/O will hang on emulator.
Both Windows and Unix emulator hosts work the same way:
- All I/O is completed synchronously.
- All I/O implementations contain the comment: `// Caller is responsible for signaling EFI Event`
However, the protocol implementations do not signal the event, so the event is never signalled.
Fix is to signal the event in the appropriate protocol implementations.
- If the host API returns success then the I/O is complete since it's always synchronous.
- If there is a Token and Token->Event is not null and the I/O is successful then the event should be signalled.
- **Breaking change** - Does …

EmulatorPkg: BlockIo2 APIs do not signal event

---

UefiCpuPkg/Library/CpuMmuLib/LoongArch64/CpuMmu.c

When updating memory attributes, if only access attributes are changed, the default memory cache attribute is NULL and a CACHE_CC is added by default.
By calling CpuSetMemoryAttributes and giving only EFI_MEMORY_XP, the default memory cache will have a CACHE_CC attribute.
N/A

UefiCpuPkg/CpuMmuLib: Adjust default memory attributes on LoongArch

---

PrmPkg/Readme.md

Links from acpica.org are now redirected to the ACPICA overview page on intel.com. Update the link so it goes to the 20200517 download page.
N/A

PrmPkg: Update link to ACPICA in Readme.md

---

MdePkg/Include/IndustryStandard/Tpm12.h
MdePkg/Include/IndustryStandard/Tpm20.h
SecurityPkg/Library/Tpm2CommandLib/Tpm2Capability.c
SecurityPkg/Library/Tpm2CommandLib/Tpm2Object.c
SecurityPkg/Library/Tpm2CommandLib/Tpm2Session.c

Update `Tpm12.h` and `Tpm20.h` to not use C++ reserved keywords `operator` and `xor` in C structures to support use of these include files when building with a C++ compiler.  Change to `operator_` and `xor_` to match other projects name adjustments for C++ compatibility.
Update `SecurityPkg` TPM related sources to use `operator_` and `xor_`.
This is a non-backwards compatible change to `Tpm12.h` and `Tmp20.h`. Any consumers of these include files that access the `operator` or `xor` fields must be updated.

Remove TPM use of C++ Reserved Keywords

---

OvmfPkg/README

Intel's ACPICA download is no longer on acpica.org, but that site redirects to pages on intel.com. Update the link to acpica.org to the new ACPICA download page.
Microsoft's acpi.info no longer exists, so update the link to point to Microsoft's ACPI compiler information page.
While here, update the nasm link from http to https.
N/A

OvmfPkg: Update links to Intel & MS ACPI compilers in README

---

DynamicTablesPkg/Library/Acpi/Common/AcpiSratLib/SratGenerator.c

The BDF format for PCI initiators in the SRAT table is incorrect. The format is not a UINT16 but specific bytes.
PCI Bus Number (Bits 7:0 of Byte 2)
PCI Device Number (Bits 7:3 of Byte 3)
PCI Function Number (Bits 2:0 of Byte 3)
REF: https://uefi.org/specs/ACPI/6.5/05_ACPI_Software_Programming_Model.html#device-handle-pci
Validated table output with the acpiview -s SRAT
N/A

DynamicTablesPkg: Fix BDF format for PCI initiators

---

.azurepipelines/templates/defaults.yml
BaseTools/Plugin/HostBasedUnitTestRunner/HostBasedUnitTestRunner.py

Switch the Linux CI jobs over to the latest Fedora 40 image.

CI: Use new Fedora-40 image for Linux jobs

---

SecurityPkg/Library/SecureBootVariableProvisionLib/SecureBootVariableProvisionLib.c

Improve the formatting of the error message when GetVariable fails: start the message with an upper-case character, and close the quotes around the variable name.
Verified the error message was formatted better after the change.
N/A

SecurityPkg: Improve formatting of msg when GetVariable fails

---

SecurityPkg/Library/SecureBootVariableProvisionLib/SecureBootVariableProvisionLib.c

While looking through SecureBootFetchData I noticed the `EfiSig` variable is unused. So this PR removes it.
Built and ran with Secure Boot enabled on my Ampere Altra Dev Kit and verified functionality was unchanged.
N/A

SecurityPkg: remove unused `EfiSig` variable in SecureBootFetchData

---

OvmfPkg/Library/QemuFwCfgLib/QemuFwCfgDxe.c
OvmfPkg/Library/QemuFwCfgLib/QemuFwCfgDxeLib.inf

Check PcdConfidentialComputingGuestAttr instead of calling MemEncryptSevIsEnabled() and MemEncryptTdxIsEnabled() to figure whenever SEV or TDX is enabled.
This allows to remove the MemEncryptSevLib + MemEncryptTdxLib dependencies.

OvmfPkg/QemuFwCfgDxeLib: use PcdConfidentialComputingGuestAttr

---

Maintainers.txt

Added Xiangdong Meng as a new reviewer for LoongArch64 ARCH.

Maintainers.txt: Add a new R for LoongArch64

---

ArmVirtPkg/Library/ArmPlatformLibQemu/AArch64/ArmPlatformHelper.S

When booting at EL2, enable VHE if available so that the early ID map can be enabled as well. This gets rid of any memory accesses (reads or writes) before the MMU and caches are enabled.

ArmVirtPkg/ArmPlatformLibQemu: Enable early ID map on EL2+VHE

---

MdeModulePkg/Core/Dxe/DxeMain/DxeMain.c

According to UEFI spec 2.10 errata A section 7.4.6
"All events from the EFI_EVENT_GROUP_BEFORE_EXIT_BOOT_SERVICES and
EFI_EVENT_GROUP_EXIT_BOOT_SERVICES event notification groups as well
as events of type EVT_SIGNAL_EXIT_BOOT_SERVICES must be signaled
before ExitBootServices() returns EFI_SUCCESS. The events are only
signaled once even if ExitBootServices() is called multiple times."
So keep track of whether ExitBootServices() has been called, and signal
the event group EFI_EVENT_GROUP_BEFORE_EXIT_BOOT_SERVICES only the first
time around.
EFI_EVENT_GROUP_EXIT_BOOT_SERVICES will only be signalled if
ExitBootServices() is going to run to [successful] completion, after
which calling it a second time is not possible anyway. So for this case,
no special handling is needed.

MdeModulePkg/DxeCore: Call BeforeExitBootServices event group only once

---

UefiPayloadPkg/Library/CustomFdtNodeParserLib/CustomFdtNodeParserLib.c
UefiPayloadPkg/Library/FdtParserLib/FdtParseLib.inf
UefiPayloadPkg/Library/FdtParserLib/FdtParserLib.c
UefiPayloadPkg/UefiPayloadEntry/AcpiTable.c

1) Add AARCH64 support in UefiPayloadPkg/FdtParseLib
2) Add fix in Fdt Parse Lib for unaligned data access
3) Add fix in ACPI parsing
- No
- No
- No
These commits have been validated on top of QEMU and Bare Metal AARCH64 platforms.
<N/A>

UefiPayloadPkg: Add AARCH64 FdtParseLib support and fix unaligned data access

---

MdePkg/Include/IndustryStandard/IpmiSerial.h
MdePkg/MdePkg.dec

Add definitions for IPMI Serial and it can be used in ManageabilityPkg.
Tested in https://github.com/tianocore/edk2-platforms/pull/240
N/A

Add IPMI Serial definitions

---

Maintainers.txt
contrib/PullRequests.github-issues

Adds a VS Code GitHub issue notebook that can be used with the VS Code GitHub Issue Notebook Extension to view PR queries on Tianocore repositories.
VS Code extension:
https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-github-issue-notebooks
This is intended to provide a single real-time dashboard that reflects PR status from all Tianocore repositories so users can track their PRs and quickly find PRs that need their attention.
To use this, install the VS Code extension and open the file. This can be done in a Web browser at vscode.dev or locally in VS Code.
---
> This was shown in the Tianocore Tools & CI meeting as a view to help bring visibility to PRs.
- Used the notebook in VS Code to view PRs on Tianocore repositories
- N/A

PullRequests.github-issues: Add PR notebook

---

MdeModulePkg/Library/BrotliCustomDecompressLib/BrotliCustomDecompressLib.inf
MdeModulePkg/Library/BrotliCustomDecompressLib/intrin.h
MdeModulePkg/Library/BrotliCustomDecompressLib/memory.h
MdeModulePkg/Library/BrotliCustomDecompressLib/stdio.h

Brotli decompression library is supported in EDK2 core. Currently it is not buildable when linking it to DxeIpl driver. The result is also checked on edk2 master branch. It could be related to updating Brotli submodule (v1.0.9) on the previous commit (1193aa2). The update makes the library buildable. It was verified for the functional status.
REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4877
It has been …

MdeModulePkg/BrotliCustomDecompressLib: Make the library buildable

---

MdeModulePkg/Universal/DriverHealthManagerDxe/DriverHealthManagerDxe.c

When PcdBrowserGrayOutTextStatement is TRUE, TextOpCode will be GrayOut.
HealthStatus cannot be displayed in help area, always use TextTwo to display it.
This change will keep the same behavior(of display info) for different `PcdBrowserGrayOutTextStatement` config.
1. Set PcdBrowserGrayOutTextStatement to TRUE, check DriverHealthManager form.
--> Only Driver/Controller name can be displayed on the form, no …

MdeModulePkg DriverHealthManagerDxe: Display HealthStatus as TextTwo of TextOpCode

---

MdeModulePkg/Universal/SmbiosMeasurementDxe/SmbiosMeasurementDxe.c

BZ: https://bugzilla.tianocore.org/show_bug.cgi?id=4575
- N/A
- N/A
- N/A
Just include this module and boot into OS.
N/A

MdeModulePkg SmbiosMeasurementDxe: Release TableAddress after use

---

ArmPkg/Drivers/ArmGic/GicV3/ArmGicV3Dxe.c
ArmPkg/Drivers/TimerDxe/TimerDxe.c
ArmPkg/Library/ArmArchTimerLib/ArmArchTimerLib.c
ArmPkg/Library/ArmExceptionLib/ArmExceptionLib.c
ArmPkg/Library/ArmLib/ArmLib.c
ArmPkg/Library/DefaultExceptionHandlerLib/AArch64/DefaultExceptionHandler.c
MdePkg/Include/Library/ArmLib.h

The existing ArmPkg implementation has some implicit casting and even truncation. Some caused build failures on non-GCC compilers. This change intends to fix those issues.
This change is tested on QEMU SBSA platform.
N/A

ArmPkg: Update a few casting instances

---

MdePkg/Include/Protocol/DebugSupport.h
MdePkg/Library/BasePeCoffLib/LoongArch/PeCoffLoaderEx.c
OvmfPkg/LoongArchVirt/Sec/LoongArch64/Start.S
UefiCpuPkg/CpuDxe/LoongArch64/CpuDxe.h
UefiCpuPkg/Library/CpuExceptionHandlerLib/LoongArch/ExceptionCommon.h
UefiCpuPkg/Library/CpuMmuLib/LoongArch64/Page.h

1. Added LoongArch64 loading foreign image support.
2. Synchronized UEFI 2.11 LoongArch64 changes.
Build OvmfPkg/LoongArchVirt/LoongArchVirtQemu.dsc and run it.
N/A

Enable foreign image loading on LoongArch64 and synchronize the changes about LoongArch64 in section 18.2.5 of UEFI 2.11

---

OvmfPkg/TdxDxe/X64/ApRunLoop.nasm

Refer to intel-tdx-module-api spec section 5.5.21, GPR mask
(TDVMCALL_EXPOSE_REGS_MASK) is a bitmap that controls which
part of the guest TD GPR and XMM state is passed as-is to
the VMM and back.
- A bit value of 0 indicates that the corresponding register
is saved by the Intel TDX module and not passed as-is to
Host VMM.
- A bit value of 1 indicates that the corresponding register
is passed as-is to the host VMM.
Currently, RBX is used as the mailbox address in ApRunLoop.nasm,
the corresponding bit value of RBX in MASK(Bit 3) is set as 1 which
means the value is passed to Host VMM as-is and it can be changed by
Host VMM.
So the bitmask shall be set as 0 to avoid this situation.
Reference:
[TDX-API]: intel-tdx-module-abi-spec
https://cdrdv2.intel.com/v1/dl/getContent/733579
Cc: Erdem …

OvmfPkg/TdxDxe: Clear GPR Mask for RBX

---

EmulatorPkg/PlatformCI/ReadMe.md
OvmfPkg/PlatformCI/ReadMe.md
ReadMe.rst

The Python version used for build and CI should always be at least the minimum version supported by edk2-pytool-extensions. A badge is added that keeps this information dynamically up-to-date based on the minimum version specified in edk2-pytool-extensions [pyproject.toml](https://github.com/tianocore/edk2-pytool-extensions/blob/master/pyproject.toml) file.
- Check badges in files on fork
- N/A

Add minimum Python version badges

---

MdePkg/Include/Library/UefiUsbLib.h
MdePkg/Library/UefiUsbLib/UefiUsbLib.inf
MdePkg/Library/UefiUsbLib/UefiUsbLibInternal.h
MdePkg/Library/UefiUsbLib/UsbDxeLib.c

If USB device reports class specific descriptors, it is currently the job of device driver to parse the configuration to find the class specific data. The new library functions parse the configuration descriptor and return class specific interface and class specific endpoint descriptors. Also, these new functions allow to retrieve the data from non-default alternate settings without performing a switch to this setting. Switching to the alternate setting currently implies the execution of UsbSetInterface function that performs USB control trnasfer.
In some cases this switch is not desirable so the new functions UsbGetInterfaceDescriptorSetting and UsbGetEndpointDescriptorSetting come in handy.
- **No** - additional UefiUsbDxeLib library functions
- **No**
Uefi Shell application that …

MdePkg/UefiUsbDxeLib: Retrieve the USB class specific data from the configuration descriptor

---

CryptoPkg/Library/Include/CrtLibSupport.h

OpenSSL ticket <https://github.com/openssl/openssl/issues/8904> has been fixed in OpenSSL commit 2e9d61ecd81a ("crypto/evp/evp_key.c: #define BUFSIZ if <stdio.h> doesn't #define it", 2019-05-27).
We should simplify "CryptoPkg/Library/Include/CrtLibSupport.h" and back out the change made to that file by edk2 commit 456dd8b99f00 ("CryptoPkg: Upgrade OpenSSL to 1.1.1b", 2019-06-03).
Ref: https://bugzilla.tianocore.org/show_bug.cgi?id=1897
- Examples: Unit …

CryptoPkg: revert BUFSIZ macro definition from commit 456dd8b99f00

---

ShellPkg/Library/UefiShellLib/UefiShellLib.c

The commit _Prevent out-of-bounds access_ fixes a possible OOB in a way that is already used in another place in the file.
The commits _Correct check for empty string_ and _Simplify check for empty string_ can be squashed if the maintainers prefer, for the sake of review they are split up in a fix-up and an optimization.
The commit _Only write value if successful conversion_ is for correctness and conformance to documented behavior.
The commit _Accept "0 " as valid numeric string_ fixes a long-standing (since 2011?) bug that prevented the use of "0" as a numeric argument, e.g. to address the first boot option when using `bcfg`. A workaround, known to some, was to use "0x0" instead.
Note there was a similar fix for InternalShellStrDecimalToUint64() in commit 80f3e34f, however if …

ShellPkg: Fix bug #3080, OOB, minor UefiShellLib fixes

---

MdeModulePkg/Core/Dxe/DxeMain/DxeMain.c
MdeModulePkg/Include/Library/DebugAgentLib.h
SourceLevelDebugPkg/Library/DebugAgent/DxeDebugAgent/DxeDebugAgentLib.c

Add a late initialize in DxeMain for the debug agent. This is required for the debug agent to be able to setup events to handle image loads, exit boot services, and other important callbacks.
Define a reinitialize debug agent.
These are being used in https://github.com/microsoft/mu_feature_debugger
N/A
N/A

MdeModulePkg DxeMain: Add late initialization for Debug Agent.

---

ShellPkg/Library/UefiShellAcpiViewCommandLib/Parsers/Ras2/Ras2Parser.c

This checks the number of PCC descriptor entries provided match the count set in the table, and if they don't indicate and error and what it is.
As per review and reply comment https://github.com/tianocore/edk2/pull/6269#issuecomment-2387969394 - This now checks and reports errors when PCC Count does not match the number of Descriptor entries.
Compile and run an edk2 and a modified edk2-platforms firmware build against an FVP emulation. Modify edk2-platforms to add a RAS2 entry into a test platform. Use this result and once booted to an UEFI shell, run acpivew to see that it correctly displays the RAS2 and reports errors manually introduced into the platform code to test with.
N/A

ShellPkg/AcpiView: RAS2 Parser - check validity of PCC Count

---

SecurityPkg/VariableAuthenticated/SecureBootConfigDxe/SecureBootConfigImpl.c

Currently "Delete Signature" Setup page lists enrolled signatures, and each signature is shown with signature GUID (prompt) and type (help). It is possible for some signatures to be shown with same signature GUID and type. In this case, it is difficult to identify the target signature to delete. The update enhances help information to distinguish signatures.
It has been tested and verified on AMD platforms that …

SecurityPkg/SecureBootConfigDxe: Enhance help in Delete Signature page

---

EmulatorPkg/Win/Host/WinBlockIo.c

WinNtBlockIoWriteBlocks can spuriously fail on X64. This occurs because &BytesWritten is a `UINTN*` (i.e. `UINT64*`) but is cast to `LPDWORD` (i.e. `UINT32*`). Only the low 32 bits are initialized by WriteFile, so the high 32 bits are uninitialized. This means we will spuriously fail the `BytesWritten != BufferSize` test.
This doesn't occur on X86-32 since UINTN is the same as DWORD in that case.
Fix is to declare BytesWritten as DWORD to match the type expected by WriteFile. This also makes the cast unnecessary. …

EmulatorPkg: spurious failure in WriteBlocks on X64

---

NetworkPkg/WifiConnectionManagerDxe/WifiConnectionMgrHiiConfigAccess.c

With the driver, "Wi-Fi Configuration" Setup page is available regardless of Wi-Fi module existence. When there is no Wi-Fi module, it is found that entering the page causes exiting Setup browser. User would think the result as an error. For better user experience, the update enables the page to report the module status like a blank page. It prevents exiting Setup.
We had an issue that system exits setup …

NetworkPkg/WifiConnectionManagerDxe: Keep Setup page on no Wi-Fi module

---

.pytool/Plugin/EccCheck/EccCheck.py
.pytool/Plugin/LicenseCheck/LicenseCheck.py

The `LicenseCheck` and `EccCheck` plugins currently fail if a file contains characters outside the platform-dependent encoding returned from `locale.getencoding()`.
This change updates the encoding to utf-8 so the plugin is more robust while continuing to support backward compatibility with the ASCII range.
- Run against files with Unicode characters and verify no exceptions are thrown
- N/A

Utf8 ci plugins

---

UefiPayloadPkg/Library/FdtParserLib/FdtParserLib.c
UefiPayloadPkg/UniversalPayloadBuild.py

This is an enhancement for universal payload serial port FDT node.
Current impl doesn't support serial port node under root node, only support it under PCI root bridge node. This PR fixed it.
- **Tests** …

UefiPayloadPkg: Enhance universal payload serial port node

---

UefiCpuPkg/PiSmmCpuDxeSmm/SmmProfile.c

For PiSmmCpuDxeSmm driver. There is SetVariable logic for SmmProfile data. In traditional SMM Mode, still set the SmmProfile variable. But for standalone remove the SetVariable logic.
- **Tests** - Does …

UefiPkg/PiSmmCpuDxeSmm: Set SmmProfile Variable only for SMM Mode.

---

StandaloneMmPkg/Drivers/StandaloneMmIplPei/MmFoundationHob.c

StandaloneMmPkg/MmIpl : Check if  MM FV HOB was built

---

StandaloneMmPkg/Drivers/StandaloneMmIplPei/StandaloneMmIplPei.c
StandaloneMmPkg/Drivers/StandaloneMmIplPei/StandaloneMmIplPei.h
StandaloneMmPkg/Drivers/StandaloneMmIplPei/StandaloneMmIplPei.inf
StandaloneMmPkg/Include/Ppi/MmCoreFvLocationPpi.h
StandaloneMmPkg/StandaloneMmPkg.dec

StandaloneMmPkg : Add MM core fv location PPI

---

.github/advanced-issue-labeler.yml
.github/workflows/issue-assignment.yml
.github/workflows/issue-triage.yml
.github/workflows/scheduled-maintenance.yml

REF: https://github.com/tianocore/edk2/discussions/5926
Adds workflows to manage labels on issues based on issue content.
Workflows:
- `issue-assignment` - Performs actions when an issue is assigned.
- Currently, removed the `state:needs-owner` label.
- `issue-triage` - Assigns initial labels to the issue based on data entered when the issue was created.
- The policies for applying labels are defined in
- `advanced-issue-labeler.yml`
- Note: Based on https://github.com/marketplace/actions/advanced-issue-labeler
- `scheduled-maintenance` - Runs every hour to perform clean up work need on issues.
- Currently, closes issues that have had the `state:wont-fix` label applied.
- Tested on edk2 fork.
- N/A - Impacts GitHub issue usage on the tianocore/edk2 repo.

.github: Add issue automation workflows

---

MdeModulePkg/Bus/Pci/XhciDxe/Xhci.c

Resurrect Patrick Henz's patch for https://bugzilla.tianocore.org/show_bug.cgi?id=4578. Resolve rebase conflict from commit ff4c49a5ee38 ("MdeModulePkg/Bus: Fix XhciDxe Linker Issues", 2023-12-06): rename "mPerformanceCounter*" to "mXhciPerformanceCounter*".
The implementation of XhcGetElapsedTicks did not account for non-zero start and stop values for the performance counter timer, potentially resulting in an incorrect elapsed tick count getting returned to the caller. Account for non-zero start and stop values when calculating the elapsed tick count. …

MdeModulePkg/XhciDxe: Non-zero start/stop values in XhcGetElapsedTicks

---

OvmfPkg/LoongArchVirt/LoongArchVirtQemu.dsc
UefiCpuPkg/Library/CpuExceptionHandlerLib/LoongArch/DxeExceptionLib.c
UefiCpuPkg/Library/CpuExceptionHandlerLib/LoongArch/ExceptionCommon.c
UefiCpuPkg/Library/CpuExceptionHandlerLib/LoongArch/ExceptionCommon.h
UefiCpuPkg/Library/CpuExceptionHandlerLib/LoongArch/LoongArch64/ArchExceptionHandler.c
UefiCpuPkg/Library/CpuExceptionHandlerLib/LoongArch/SecPeiExceptionLib.c

Patch1: There is a problem with LoongArch64 exception handler, it returns a unhandled value when we get an exception type, the correct value should be right shifted 16 bits, so fix it. Increased the max number of exception handlers to 23.
Patch2: Added interrupt type dump function on LoongArch.
Patch3: BaseCryptLib, RngLib, IntrinsicLib and OpensslLib are enabled by default on LoongArch VM, since some APPs or OS require them.
Build OvmfPkg/LoongArchVirt/LoongArchVirtQemu.dsc and run it.
N/A.

Adjust LoongArch exception handler and enable some base libraries on LoongArch VM

---

OvmfPkg/Library/PlatformBootManagerLib/BdsPlatform.c
OvmfPkg/Library/PlatformBootManagerLib/PlatformBootManagerLib.inf
OvmfPkg/OvmfXen.dsc
OvmfPkg/RUNTIME_CONFIG.md

This PR introduces the possibility to disable the UEFI shell from the QEMU CLI using the fw_cfg variable.
Run QEMU on X86-64 with and without the fw_cfg flag set.
For reference `qemu -fw_cfg name=opt/org.tianocore/EFIShellSupport=no`
UEFI Shell fails to boot when the value is set to no.
N/A

OvmfPkg: Introduce UEFI shell support for fw_cfg 

---

ArmPkg/Drivers/GenericWatchdogDxe/GenericWatchdog.h
ArmPkg/Drivers/GenericWatchdogDxe/GenericWatchdogDxe.c

Do not use the PCDs as only fixed when there is an option to use them as dynamic that can be set per SKU.
SOCs with different addresses and INTR numbers governed via SKU were booted with this change.
N/A

ArmPkg: Update Generic Watchdog PCD Type

---

UefiPayloadPkg/Library/FdtParserLib/FdtParserLib.c

PixelsPerScanLine is required in some UEFI capable OS distribution. To align with simple-framebuffer definition in kernel Documentation: devicetree/bindings/display/simple-framebuffer.txt, no property node will be introduced for PixelsPerScanLine.
Set value of PixelsPerScanLine to HorizontalResolution, as they are identical in most cases.
- N/A
- N/A
- N/A
Tested with ESXi image
N/A

UefiPayloadPkg: Set PixelsPerScanLine property in GraphicInfo HOB

---

IntelFsp2WrapperPkg/FspmWrapperPeim/FspmWrapperPeim.c
IntelFsp2WrapperPkg/Library/FspWrapperMultiPhaseProcessLib/FspWrapperMultiPhaseProcessLib.inf
IntelFsp2WrapperPkg/Library/FspWrapperMultiPhaseProcessLib/PeiFspWrapperMultiPhaseProcessLib.c

Save FspHobList pointer to HOB right after FspMemoryInit exits so that FspHobList pointer is available when performing platform related reset in CallFspWrapperResetSystem(). Some platforms may consume FSP HOBs prior to performing platform related reset.
This PR was tested with FSP-M, FSP-S, FSP multi-phase memory initialization and FSP multi-phase silicon initialization enabled. And it's confirmed in the test …

IntelFsp2WrapperPkg: Save FspHobListPtr Right After FspMemoryInit Exits

---

UefiPayloadPkg/Library/FdtParserLib/FdtParserLib.c

In platform which support ACPI 2.0 only, the base address of ACPI region is not page aligned. This unalinged base address leads to failure at BuildMemoryAllocationHob when parsing ACPI node in FdtParserLib, before building gUniversalPayloadAcpiTableGuid GUID HOB.
Align base address of ACPI region down to EFI_PAGE_SIZE to make sure base address always aligned.
FYI. These is log snippet read from Bare Metal hardware platform which supports ACPI 2.0:
efi: SMBIOS 3.0=0xf7e90000 ACPI 2.0=0xf472f018
- N/A
- N/A
- N/A
<_Describe how these …

UefiPayloadPkg: Align base address for ACPI region

---

MdePkg/Library/UefiDevicePathLib/DevicePathToText.c

```
HD(Partition,Type,Signature,Start, Size)
HD(Partition,Type,Signature) (Display Only)
```
Reference: [UEFI Specification Version 2.1 (Errata D) (released October  2008)](https://uefi.org/sites/default/files/resources/UEFI_Spec_2_1.pdf)

MdePkg: UefiDevicePathLib: Fix missing the Display Only format of Media Device Path SubType Hard Drive.

---

RedfishPkg/Library/HiiUtilityLib/HiiUtilityInternal.c

Replaced direct assignment of 'Value = (EFI_HII_VALUE *)&Question->Value' with the correct usage of HiiStatementValueToHiiValue function. This resolves the issue where EFI_HII_VALUE and HII_STATEMENT_VALUE types are incompatible, ensuring proper handling of Question->Value.

Redfish/HiiUtilityLib Fix incorrect type assignment

---

ArmVirtPkg/ArmVirtQemu.dsc
OvmfPkg/Include/IndustryStandard/Virtio10.h
OvmfPkg/Library/PlatformBootManagerLib/BdsPlatform.c
OvmfPkg/OvmfPkgIa32X64.dsc
OvmfPkg/OvmfPkgIa32X64.fdf
OvmfPkg/OvmfPkgX64.dsc
OvmfPkg/OvmfPkgX64.fdf
OvmfPkg/VirtioKeyboardDxe/VirtioKeyCodes.h
OvmfPkg/VirtioKeyboardDxe/VirtioKeyboard.c
OvmfPkg/VirtioKeyboardDxe/VirtioKeyboard.h
OvmfPkg/VirtioKeyboardDxe/VirtioKeyboard.inf

This set of commits introduces virtio based keyboard driver. The main idea is to
have a keyboard driver which is more "light" than standard USB based driver.
This may be better for some small ARM based platforms with limited resources.
I have tested this manually with RPi5 ARM platform and qemu. For test I have navigated
over efi shell, config and grub bootloader window running from Fedora ISO.
```
#!/bin/bash …
```

Arm virtio keyboard driver

---

UefiPayloadPkg/Library/BuildFdtLib/X86_BuildFdtLib.c
UefiPayloadPkg/Library/PciSegmentInfoLibAcpiBoardInfo/PciSegmentInfoLibAcpiBoardInfo.c

<_Describe how these changes should …

Upl pci seg lib

---

NetworkPkg/UefiPxeBcDxe/PxeBcDriver.c

Ensure the poniter is not null before free it
During stress testing of PXE boot, the following message occasionally appeared:  
```
ASSERT_EFI_ERROR (Status = Invalid Parameter)  
ASSERT [UefiPxeBcDxe] /home/Bill.Li/code/build-platform/corsica/uefi/edk2/MdePkg/Library/UefiMemoryAllocationLib/MemoryAllocationLib.c(813): !EFI_ERROR (Status)
```
After debugging, I found that the pointer `Ip4nic->DevicePath` was null when being freed.
Perform PXE boot testing using Qemu and VirtioNet NIC.
N/A

NetworkPkg/UefiPxeBcDxe: Bugfix for pxe driver

---

CryptoPkg/Library/BaseCryptLibMbedTls/SysCall/ConstantTimeClock.c

In BaseCryptLib sleep() function is defined,
apply the same sleep function to BaseCryptLibMbedTls …

CryptoPkg: Add sleep() function to BaseCryptLibMbedTls

---

FatPkg/FatPkg.ci.yaml

Adds a PrEval entry to the package's ci.yaml file which is used to verify if the package uses a particular library instance when that library instance file (INF) is updated.
When a library instance file (INF) is updated, PrEval will review each package's DSC as described in the ci.yaml file to determine if the package uses said library instance. If the package does use the library instance, it will be built and tested to ensure the package is not broken from the change.
- **Tests** - Does this PR include any …

FatPkg: CI: Add PrEval entry

---

OvmfPkg/VirtioSerialDxe/VirtioSerial.c

The VirtIO spec states the following (from https://docs.oasis-open.org/virtio/virtio/v1.3/virtio-v1.3.html#x1-3330002):
> Upon receipt of a VIRTIO_CONSOLE_CONSOLE_PORT message, the driver SHOULD treat the port in a manner suitable for text console access and MUST respond with a VIRTIO_CONSOLE_PORT_OPEN message, which MUST have value set to 1
The current driver implementation, however, does not comply with that and only send PORT_OPEN messages when receiving PORT_OPEN messages. This causes a problem in platforms like Apple's Virtualization Framework, where PORT_OPEN messages are not sent back to the driver after CONSOLE_PORT messages, a behaviour that is compliant with the specification.
This patch addresses this issue by always responding CONSOLE_PORT messages with PORT_OPEN messages.
- …

OvmfPkg/VirtioSerialDxe: respond CONSOLE_PORT with PORT_OPEN

---

MdePkg/Include/Base.h

Coverity is a static analysis tool. It detects the macro as an error (case to incompatible type, cert_exp39_c_violation). The update resolves the error and supports compliance with the static tool.
For example,
MdeModulePkg\Universal\HiiDatabaseDxe\Database.c
Code : 
Entry = BASE_CR (Link, VARSTORAGE_DEFAULT_DATA, Entry);
Coverity Error : 
(3) Event cast_to_incompatible_type: Casting "(CHAR8 *)Link - 0ULL" of type "CHAR8 *" to incompatible type "VARSTORAGE_DEFAULT_DATA *".
(4) Event assign: Assigning: "Entry" = "(VARSTORAGE_DEFAULT_DATA *)((CHAR8 *)Link - 0ULL)".
Also see events: [[cert_exp39_c_violation](https://wiki.sei.cmu.edu/confluence/display/c/EXP39-C.+Do+not+access+a+variable+through+a+pointer+of+an+incompatible+type)]
- **Breaking change** - Does this PR cause a break in build or …

MdePkg: Update BASE_CR macro in Base.h for a Coverity error

---

BaseTools/Plugin/DebugMacroCheck/DebugMacroCheck.py

Currently openssl has an Open Quantum Safe provider submodule with directories like `oqs-provider/oqs-template/oqsprov/oqsprov.c` or `oqs-provider/oqs-template/oqsprov/oqsprov/oqsprov_capabilities.c` that are used as templates, but DebugMacroCheck tries to read them as a file when recursively traversing the subdirectories.
Fail message:
```
File "/usr/lib/python3.10/pathlib.py", line 1119, in open
return self._accessor.open(self, mode, buffering, encoding, errors,
IsADirectoryError: [Errno 21] Is a directory: '/CryptoPkg/Library/OpensslLib/openssl/oqs-provider/oqs-template/oqsprov/oqsprov.c'
```
- **Security** - Does this PR have a …

BaseTools: Skip directories with code extensions in the name

---

BaseTools/Source/Python/Common/MultipleWorkspace.py
BaseTools/Source/Python/Common/TargetTxtClassObject.py
BaseTools/Source/Python/Ecc/EccMain.py
BaseTools/Source/Python/GenFds/GenFds.py
BaseTools/Source/Python/build/build.py

Refer to the docs of python, `os.path.normcase(path)` function: "Normalize the case of a pathname. On Windows, convert all characters in the pathname to lowercase, and also convert forward slashes to backward slashes. On other operating systems, return the path unchanged."
`os.path.normpath(path)` also convert forward slashes to backward slashes.
So call `os.path.normcase` after `os.path.normpath` just convert path to lowercase on Windows(only).
And Windows is case-insensitive but case-preserving.
So the usage of `os.path.normcase(os.path.normpath(path))` can be simplified to `os.path.normpath(path)`. Then we can use case-preserving paths rather than lowercase paths in compile_commands.json file or build log.
But this patch continue to use `os.path.normcase`
when comparing/searching …

BaseTools: Clean up os.path.normcase and os.path.normpath usage

---

OvmfPkg/Library/SmmCpuPlatformHookLibQemu/SmmCpuPlatformHookLibQemu.c
UefiCpuPkg/Include/Library/SmmCpuPlatformHookLib.h
UefiCpuPkg/Library/SmmCpuPlatformHookLibNull/SmmCpuPlatformHookLibNull.c

Determines whether all CPUs sync is needed.
This function determine if all CPUs needed to be synced unconditional during the 1st APs sync.
By default, it returns FALSE which indicates not all CPUs needed to be synced. In case of all CPUs
needed to be synced, platform specific implementation can return TRUE.
No test except compile the code successfully as new interface not being used by other code now. Test can be done once it called by other code later.

Add SmmCpuPlatformHookLib IsCpuSyncAlwaysNeeded interface

---

CryptoPkg/Library/BaseCryptLibMbedTls/SysCall/CrtWrapper.c
CryptoPkg/Library/BaseCryptLibMbedTls/SysCall/DummyOpensslSupport.c

Move strncpy() from DummyOpensslSupport.c to CrtWrapper.c under SysCall folder
Move strncpy() from DummyOpensslSupport.c to CrtWrapper.c under SysCall folder
- **Breaking change** - Does this PR cause a break in build or boot behavior? No
- **Security** - Does this PR have a direct security impact? No
- Examples: Unit tests or integration tests. Build test
Build test
N/A

CryptoPkg/BaseCryptLibMbedTls : Add strncpy() support to SecCryptLib

---

ArmPkg/Drivers/ArmGic/ArmGicLib.c
ArmPkg/Include/Library/ArmGicLib.h

A compiler warning was detected that 'IntId' could be used uninitialized in the `else` branch.
Since there are no consumers of this function, it was decided to remove this function completely.
This solution was suggested at https://github.com/tianocore/edk2/pull/10603#discussion_r1910202751
None
N/A

ArmPkg: remove ArmGicAcknowledgeInterrupt function.

---

UefiCpuPkg/CpuDxe/CpuDxe.c
UefiCpuPkg/CpuDxe/CpuDxe.inf
UefiCpuPkg/CpuDxe/CpuPageTable.c
UefiCpuPkg/CpuDxe/CpuPageTable.h

Produce the EFI memory attribute protocol introduced in UEFI v2.10 that permits the caller to
manage mapping permissions in the page tables.

Produce EFI memory attribute protocol

---

CryptoPkg/Library/BaseCryptLib/SysCall/TimerWrapper.c

Move local variable init to C statements to follow coding standard and remove the use of field names in structure initialization to maximize compiler compatibility.
This issue was introduced by PR #6185
Build breaks with VS2015 before this change.  Passes VS2015 build after this change.
N/A

CryptoPkg/BaseCryptLib: Fix mktime() coding style issue

---

EmulatorPkg/Win/Host/WinHost.c

Update `SecPrint()` to use `_vsnprintf_s()` instead of `_vsnprintf()` that is a safe function and allows the defines `_CRT_SECURE_NO_WARNINGS` and `_CRT_SECURE_NO_DEPRECATE` to be removed from WinHost builds.
Build fails without `_CRT_SECURE_NO_WARNINGS` and `_CRT_SECURE_NO_DEPRECATE` defined before this change and passes without `_CRT_SECURE_NO_WARNINGS` and `_CRT_SECURE_NO_DEPRECATE` defined after this …

EmulatorPkg/Win/Host: Use safe function _vsnprintf_s()

---

StandaloneMmPkg/Drivers/StandaloneMmIplPei/MmFoundationHob.c

StandaloneMmPkg/MmIpl: Correct FV HOB check founction

---

CryptoPkg/Library/OpensslLib/OpensslStub/uefiprov.c

Some parts and versions of TLS require HMAC. This adds the missing HMAC algorithms to the UEFI provider. One entry in the default signature algorithms and one in the key management algorithms.
Source of these entries is the default OpenSSL provider, defltprov.c, included in the OpenSSL library.
This change was required to connect to some TLS servers depending on the used ciphers.
The following ciphers were tested:
IANA Name - OpenSSL name
**TLS_RSA_WITH_AES_128_CBC_SHA256 - AES128-SHA256 -> Fails**
**TLS_RSA_WITH_AES_256_CBC_SHA256 - AES256-SHA256 -> Fails**
TLS_RSA_WITH_AES_128_GCM_SHA256 - AES128-GCM-SHA256 -> OK
**TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 - ECDHE-RSA-AES128-SHA256 -> Fails**
**TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 - ECDHE-RSA-AES256-SHA384 -> Fails** …

CryptoPkg: Add HMAC algorithms for signature/keymgmt

---

MdeModulePkg/Universal/HiiDatabaseDxe/ConfigRouting.c

Add string question load default support
load default data from PCD PcdNvStoreDefaultValueBuffer. …

MdeModulePkg/HiiDatabaseDxe: Add string question load default support.

---

MdeModulePkg/Bus/Pci/PciSioSerialDxe/SerialIo.c

For bootup of VMs with multiple accelerators, these logging instructions flood the logs for a good 30 seconds.
Originally found by Gary Zibrat.
Google internal testing confirms performance improvements.
N/A

MdeModulePkg: Make noisy log DEBUG_VERBOSE

---

BaseTools/Conf/build_rule.template

When running the /wholearchive test build, generate the test .dll as a different filename to prevent the system holding onto the dll file too long and generating a build error that the actual dll cannot be found.
Local Builds using VS2022 and VS2019. 
N/A

BaseTools: build_rule.template wholearchive test

---

MdePkg/Include/Base.h

The clang compiler generates the following error
```error: use of 'static_assert' without inclusion of <assert.h>```
This is due to the use of the MSC Extension `static_assert`. Use `_Static_assert` instead for clang and GNUC compilers.
EmulatorPkg CLANGDWARF builds under Linux can reproduce this error before this change, and are resolved after this change.
N/A

MdePkg/Include: Use _Static_assert for clang and GNUC

---

contrib/Issues.github-issues

Filters issues in a notebook in VS Code based on common search criteria.
Additional search qualifiers can be added per this documentation: https://docs.github.com/search-github/searching-on-github/searching-issues-and-pull-requests
- View in VS Code with [GitHub Issues Notebook](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-github-issue-notebooks)
- N/A

Add VS Code GitHub issues notebook

---

NetworkPkg/UefiPxeBcDxe/PxeBcMtftp.c

Per RFC 1350, TFTP error packets include 2 byte OpCode and ErrorCode fields in network byte order. Those need to be swapped to host order to be interpreted correctly. Without this change, the TftpErrorReceived and TftpError Mode fields are never set and EFI applications can't inspect the error received from the TFTP server.
I was testing shim to see how it handles TFTP file not found errors in …

NetworkPkg: UefiPxeBcDxe: Fix error packet detection

---

MdePkg/Include/Pi/PiStatusCode.h

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4483
This change introduces EFI_COMPUTING_UNIT_MANAGEABILITY status code. EFI_COMPUTING_UNIT_MANAGEABILITY is created as one of the subclasses in computing unit class. EFI_COMPUTING_UNIT_MANAGEABILITY will be used in edk2 RedfishPkg and edk2-redfish-client RedfishClientPkg to report Redfish operation errors. It will also be used to report errors in edk2-platforms ManageabilityPkg.
PI 1.9 specification, 6.4.1.4.9. Manageability Subclass:
* https://uefi.org/specs/PI/1.9/V3_Status_Codes.html#manageability-subclass
RFC:
* https://edk2.groups.io/g/devel/message/105525
* https://edk2.groups.io/g/devel/message/105595
* https://edk2.groups.io/g/rfc/message/802
- …

MdePkg: Add manageability status code defined in PI 1.9 Spec.

---

ArmVirtPkg/ArmVirtQemu.dsc
OvmfPkg/Include/Dsc/OvmfDisplayPcds.dsc.inc
OvmfPkg/Microvm/MicrovmX64.dsc
OvmfPkg/OvmfPkgIa32.dsc
OvmfPkg/OvmfPkgIa32X64.dsc
OvmfPkg/OvmfPkgX64.dsc
OvmfPkg/OvmfXen.dsc
OvmfPkg/PlatformDxe/Platform.c
OvmfPkg/PlatformDxe/Platform.inf
OvmfPkg/QemuVideoDxe/Initialize.c
OvmfPkg/QemuVideoDxe/QemuVideoDxe.inf
OvmfPkg/RiscVVirt/RiscVVirtQemu.dsc
OvmfPkg/VirtioGpuDxe/Gop.c
OvmfPkg/VirtioGpuDxe/VirtioGpu.inf

- **OvmfPkg: move display pcds to OvmfDisplayPcds.dsc.inc include file**
- **OvmfPkg/OvmfXen.dsc: use OvmfDisplayPcds.dsc.inc**
- **OvmfPkg/RiscVVirtQemu.dsc: use OvmfDisplayPcds.dsc.inc**
- **ArmVirtPkg/ArmVirtQemu.dsc: use OvmfDisplayPcds.dsc.inc**
- **OvmfPkg/QemuVideoDxe: set SetupVideoResolution too**
- **OvmfPkg/VirtioGpuDxe: set SetupVideoResolution too**
- **OvmfPkg/PlatformDxe: set SetupVideoResolution too**
- **OvmfPkg/OvmfDisplayPcds.dsc.inc: set SetupVideoResolution too**
- **OvmfPkg/OvmfDisplayPcds.dsc.inc: set SetupConOut too**
This patch series makes sure the video PCDs for normal mode and for setup mode are identical.  This gets rid of pointless video mode changes when entering/leaving the firmware setup application.
The patch series also moves all the PCDs to an include …

update ovmf + armvirt display configuration for setup

---

OvmfPkg/Library/GenericQemuLoadImageLib/GenericQemuLoadImageLib.c
OvmfPkg/Library/X86QemuLoadImageLib/X86QemuLoadImageLib.c
OvmfPkg/Library/X86QemuLoadImageLib/X86QemuLoadImageLib.inf
OvmfPkg/QemuKernelLoaderFsDxe/QemuKernelLoaderFsDxe.c
OvmfPkg/QemuKernelLoaderFsDxe/QemuKernelLoaderFsDxe.inf
OvmfPkg/RUNTIME_CONFIG.md

- OvmfPkg/QemuKernelLoaderFsDxe: rework direct kernel boot filesystem
- OvmfPkg/QemuKernelLoaderFsDxe: add support for named blobs
- OvmfPkg/QemuKernelLoaderFsDxe: allow longer file names
- OvmfPkg/QemuKernelLoaderFsDxe: drop bogus assert
- OvmfPkg/QemuKernelLoaderFsDxe: accept absolute paths
- OvmfPkg/QemuKernelLoaderFsDxe: don't quit when named blobs are present
- OvmfPkg/X86QemuLoadImageLib: support booting via shim
- OvmfPkg/GenericQemuLoadImageLib: support booting via shim
- OvmfPkg/X86QemuLoadImageLib: make legacy loader configurable.
- OvmfPkg: document opt/org.tianocore/EnableLegacyLoader option

OvmfPkg: secure boot support for direct kernel boot (via shim), try #2

---

EmulatorPkg/Win/Host/WinHost.c

The Visual Studio Windows debugger will only load symbols for PE/COFF images that Windows is aware of. Therefore, to enable source level debugging, all PEI/DXE modules must be loaded via LoadLibrary() or LoadLibraryEx() and the the instance in memory created by LoadLibrary() must be the one that is actually executed.
The current source level debug implementation in EmulatorPkg for Windows is inherited from the old Nt32Pkg. This implementation makes the assumption that all PEI/DXE modules have a DLL export tables with a symbol named InitializeDriver. Therefore, this source level debug implementation requires all modules to be linked in a non-PI spec defined manner. Support for adding the InitializeDriver symbol was removed in EmulatorPkg, which broke source level debugging.
To fix this, …

EmulatorPkg: Fix Source Level Debug on Windows

---

EmulatorPkg/Win/Host/WinHost.c

Fixes #10652 
The magic page is allocated from a fixed address specified by `PcdPeiServicesTablePage`. This allocation has been observed to sometimes fail. Move the allocation of this buffer to the very beginning of `main()` to minimize the chance that another allocation is allocated from the `PcdPeiServicesTablePage` address.
The issue was reproduced with a build of EmulatorPkg VS2022 IA32 RELEASE. In order to minimize the time required to boot cycle the EmulatorPkg build, the boot manager front page timeout is set to 0 and the Shell default delay is also set to 0.
```
build -a IA32 -t VS2022 -p EmulatorPkg\EmulatorPkg.dsc -b RELEASE --pcd gEfiMdePkgTokenSpaceGuid.PcdPlatformBootTimeOut=0 --pcd gEfiShellPkgTokenSpaceGuid.PcdShellDefaultDelay=0
```
A cmd script was then used to boot the …

EmulatorPkg: Move magic page to first allocation

---

DynamicTablesPkg/DynamicTables.dsc.inc
DynamicTablesPkg/DynamicTablesPkg.dsc
DynamicTablesPkg/Include/AcpiTableGenerator.h
DynamicTablesPkg/Include/X64NameSpaceObjects.h
DynamicTablesPkg/Library/Acpi/X64/AcpiFacsLib/AcpiFacsLib.inf
DynamicTablesPkg/Library/Acpi/X64/AcpiFacsLib/FacsGenerator.c
DynamicTablesPkg/Library/Common/TableHelperLib/ConfigurationManagerObjectParser.c
DynamicTablesPkg/Readme.md

Adds a library to generate ACPI FACS table for X64.
Adds X64 generator library for creating ACPI FACS table.
Tested on AMD platform.
N/A

DynamicTablesPkg: Adds X64 FACS generator library

---

ShellPkg/Library/UefiShellDriver1CommandsLib/DrvCfg.c

Fixes https://github.com/tianocore/edk2/issues/10626
Issue command drvcfg derectly, system halt
- **Tests** - …

ShellPkg: DXE_ASSERT when issuing drvcfg command in UEFI Shell

---

OvmfPkg/QemuKernelLoaderFsDxe/QemuKernelLoaderFsDxe.c

UEFI spec says so, fix it.
https://uefi.org/specs/UEFI/2.11/13_Protocols_Media_Access.html#efi-file-info
Reported-by: Laszlo Ersek <laszlo.ersek@posteo.net>

OvmfPkg/QemuKernelLoaderFsDxe: root directory name should be ""

---

OvmfPkg/Library/GenericQemuLoadImageLib/GenericQemuLoadImageLib.c

Commit 459f5ffa24ae ("OvmfPkg/QemuKernelLoaderFsDxe: rework direct
kernel boot filesystem") has a small change in behavior:  In case
there is no data the file is not created and attempts to open file
return EFI_NOT_FOUND.  Old behavior was to add a zero-length file
to the filesystem.
Fix GenericQemuLoadImageLib to handle EFI_NOT_FOUND correctly for
'initrd' and 'cmdline'.
Reported-by: Srikanth Aithal <sraithal@amd.com>

OvmfPkg/GenericQemuLoadImageLib: fix cmdline + initrd handling

---

ShellPkg/DynamicCommand/HttpDynamicCommand/Http.c

There is already `PRINT_HII (STRING_TOKEN (STR_GEN_CRLF), NULL);` after `DownloadFile()`, remove this extra `\n` to avoid printing extra blank lines.
- N/A
- N/A
- N/A
Compare the output info of `http http://192.168.10.23:5000/BIN/BIOS.bin -m` cmd.
before:
```
FS0:\> http http://192.168.10.23:5000/BIN/BIOS.bin -m
[=======================================>]   32768 Kb, 44s
FS0:\>
```
after:
```
FS0:\> http http://192.168.10.23:5000/BIN/BIOS.bin -m
[=======================================>]   32768 Kb, 44s
FS0:\>
```
N/A

ShellPkg Http.c: Remove extra `\n` when using `-m` param

---

EmulatorPkg/Library/PlatformBmLib/PlatformBm.c

Call PlatformBdsRegisterStaticBootOptions (); after EfiBootManagerRefreshAllBootOption to prevent duplicate BootManagerMenuApp boot option.
- N/A
- N/A
- N/A
Check the Boot Options.
Before: (Two BootManagerMenuApp BootOption)
```
[Bds]=============Begin Load Options Dumping ...=============
Driver Options:
SysPrep Options:
Boot Options:
Boot0005: UEFI Shell                 0x0001
Boot0001: UEFI BootManagerMenuApp            0x0100
Boot0002: UEFI Misc Device           0x0001
Boot0003: UEFI Non-Block Boot Device                 0x0001
Boot0004: UEFI BootManagerMenuApp            0x0001
Boot0000: UEFI Enter Setup           0x0109
PlatformRecovery Options:
PlatformRecovery0000: Default PlatformRecovery               0x0001
[Bds]=============End Load Options Dumping=============
```
After:
``` …
```

EmulatorPkg PlatformBm: Fix duplicate BootManagerMenuApp boot option issue

---

UefiPayloadPkg/UefiPayloadPkg.dsc

After commit aca75d3 the PayloadEntry ELF header will miss dynamic section which caused PEI_ASSERT in PayloadLoader rebasing code.
This commit adding common-page-size=0x1000 to CLANGDWARF_DLINK_FLAGS to overcome the ELF header generation issue. …

UefiPayloadPkg: Add 4KB align to CLANGDWARF build.

---

OvmfPkg/Include/IndustryStandard/Xen/io/blkif.h
OvmfPkg/XenPvBlkDxe/BlockFront.c
OvmfPkg/XenPvBlkDxe/XenPvBlkDxe.c

This is a follow-up on a clarification of the Xen blkif PV disk protocol, which has been committed as https://github.com/xen-project/xen/commit/221f2748e8dabe8361b8cdfcffbeab9102c4c899. The calculation of the disk size happen to be wrong when the backend is Linux.
Just a quick run in `osstest` (one of Xen's CI) to check for regression.
N/A

OvmfPkg/XenPvBlkDxe: Update disk size calculation

---

OvmfPkg/Library/LoadLinuxLib/Linux.c

kernel pages are code not data.

OvmfPkg: make legacy direct kernel loader code nx clean

---

MdePkg/Library/BasePeCoffLib/BasePeCoff.c

Fixed Clang build error introduced by uninitialized variables in https://github.com/tianocore/edk2/commit/6278bbb89822c598fcd0637ae74174e367895c84
N/A

MdePkg: Fix Clang Build Error

---

NetworkPkg/HttpDxe/HttpImpl.c
NetworkPkg/HttpDxe/HttpsSupport.c

1.HttpResponseWorker(DEADCODE)
The result of pointer arithmetic "HttpHeaders+AsciiStrLen("HTTP/1.1") + 1" is never null.
2.HttpsSupport.c (NULL_RETURNS)
NetbufAlloc might return null pointer ,so assigning "NULL" to "PacketOut" and "DataOut" pointer.
Solution:
1.Removed the NULL Check for "StatusCodeStr"
2.Added Null Check for PacketOut and returned EFI_OUT_OF_RESOURCES on NULL case.

Resolved Coverity Issues in Http Dxe

---

OvmfPkg/QemuKernelLoaderFsDxe/QemuKernelLoaderFsDxe.c

- **OvmfPkg/QemuKernelLoaderFsDxe: use SIZE_OF_EFI_FILE_INFO**

OvmfPkg/QemuKernelLoaderFsDxe: use SIZE_OF_EFI_FILE_INFO

---

MdeModulePkg/Bus/Pci/NvmExpressDxe/NvmExpressMediaSanitize.c
MdeModulePkg/Core/Dxe/Hand/Handle.c
MdeModulePkg/Core/Pei/Dispatcher/Dispatcher.c
OvmfPkg/Library/GenericQemuLoadImageLib/GenericQemuLoadImageLib.c
SecurityPkg/RandomNumberGenerator/RngDxe/ArmTrng.c
ShellPkg/Library/UefiShellDebug1CommandsLib/Dmem.c

Sometimes I compile projects using old gcc (gcc-8.1.0)
This time I've tried to build ArmVirtPkg/ArmVirtQemu.dsc  and OvmfPkg/OvmfPkgIa{32,64}.dsc
and found a bunch of similar warnings preventing from complete project build.
The changes look trivial. 
N/A

MdeModulePkg: OvmfPkg: SecurityPkg: ShellPkg: fix [-Werror=maybe-uninitialized]

---

MdePkg/Library/BasePeCoffLib/BasePeCoff.c

PeCoffLoaderRelocateImageForRuntime() executes after boot services, and so it should not use DEBUG() prints at all, given that these may rely on MMIO mappings or other boot time facilities that are no longer available.
So revert the changes in aedcaa3df8a2 ("MdePkg: Fix overflow issue in PeCoffLoaderRelocateImageForRuntime") that replaced code comments with DEBUG() statements.

MdePkg/BasePeCoffLib: Remove DEBUG() statements from runtime code

---

Maintainers.txt

Add Oliver Smith-Denny and Michael Kubacki as maintainers.
- Verify `GetMaintainer.py` can still parse the file.
N/A

Maintainers.txt: Update EmulatorPkg maintainers

---

ArmPkg/Drivers/ArmGicDxe/ArmGicCommonDxe.c
ArmPkg/Drivers/ArmGicDxe/ArmGicDxe.h
ArmPkg/Drivers/ArmGicDxe/ArmGicDxe.inf
ArmPkg/Drivers/ArmGicDxe/ArmGicV2Dxe.inf
ArmPkg/Drivers/ArmGicDxe/ArmGicV3Dxe.inf
ArmPkg/Drivers/ArmGicDxe/GicV2/ArmGicV2Dxe.c
ArmPkg/Drivers/ArmGicDxe/GicV3/ArmGicV3Dxe.c
ArmPkg/Drivers/CpuDxe/CpuDxe.c
ArmPkg/Drivers/CpuDxe/CpuDxe.h
ArmPkg/Drivers/CpuDxe/CpuDxe.inf
ArmPkg/Drivers/CpuDxe/CpuMmuCommon.c
ArmPkg/Drivers/CpuDxe/Exception.c
ArmVirtPkg/Library/QemuVirtMemInfoLib/QemuVirtMemInfoLib.c

Refactor the CPU and GIC DXE drivers so that the latter can invoke the CPU arch protocol exposed by the former to map the MMIO control registers explicitly.

Arm gic mmio mapping

---

.devcontainer/devcontainer.json

Since the CI is now running on Fedora 40, let's also switch over VSCode Devcontainer to use the same.
Untested - I have trouble getting the VSCode Devcontainer extension to work.
Can some regular VSCode user please try this?

Devcontainer: Use latest Fedora 40 image

---

ArmVirtPkg/ArmVirtQemu.dsc

When running the verbose builds on arm for development and testing
it is quite convenient to use virtio serial to interact with the
system because console and logging are separated then.  Except that
the virtio serial driver spams the debug log in that case.  Set the
debug level for the driver to zero to avoid that.

ArmVirtPkg: turn off debug logging for VirtioSerialDxe

---

ArmVirtPkg/Library/QemuVirtMemInfoLib/QemuVirtMemInfoLib.c

This reverts commit 43233ff9f88e5c9b88228810f7725bade4cdfecf.
The TPM code (and possibly others too) must be fixed to also
map their MMIO ranges before we can do this cleanup.

Revert "ArmVirtPkg/ArmVirtQemu: Reduce MMIO region mapped by default"

---

MdePkg/Include/Pi/PiHob.h
MdePkg/Include/Protocol/CcMeasurement.h
MdePkg/Include/Uefi/UefiSpec.h

This PR contains updates pertaining to : 
UEFI 2.11 Specification:
- MdePkg: Add HotPlug Memory Attribute
- MdePkg: Add Confidential Computing Extension for RISC-V AP-TEE
- MdePkg: Add UEFI 2.11 specification macro
PI 1.9 Specification:
- MdePkg: Add Hot pluggable resource attribute
Minimal changes. Validated with edk2 CI.
N/A

General updates for UEFI 2.11 and PI 1.9 Specifications

---

BaseTools/Conf/tools_def.template

The command line option --no-warn-rwx-segments was added to the linker command line for all GCC family builds on ARM and AARCH64, including CLANGDWARF and GCC49 and older, none of which are intended for use with linkers that actually understand this option.
So instead, move it to the GCC5 DLINK FLAGS definitions for ARM and AARCH64 (which are inherited by the versionless GCC which is intended to replace GCC5 at some point).

BaseTools/tools_def: Use no-warn-rwx-segments only for GCC5

---

BaseTools/Source/Python/AutoGen/GenMake.py

If command line options are moved into a response file of a GCC family build, then the file path separators are converted from '\\' to '/'. However, this can corrupt command line options that are quoted strings.
Update GenMake to no convert '\\' to '/' in quoted strings.
Added CC_FLAGS to EmulatorPkg build to increase line length to force response file generation and added additional command line parameters with various file paths and quoted strings:
| Input | Before Change | Correct | After Change |
| ----- | -------|  ------ | ------ | 
| "Hello" | "Hello" | YES | "Hello" |
| L\\"Hello\\" | L/"Hello/" | NO | L\\"Hello\\" |
| "a/b/c/d" | "a/b/c/d" | YES | "a/b/c/d" |
| "a\b\c\d" | "a/b/c/d" | NO | "a\b\c\d" |
| L\\"a/b/c/d\\" | L/"a/b/c/d/" | NO | L\\"a/b/c/d\\" |
| L\\"a\b\c\d\\" | …

BaseTools/AutoGen: GenMake response file quotes strings

---

UefiPayloadPkg/UefiPayloadPkg.dsc

With the latest GccBase.lds combining with CLANG build, there is no need to enforce 4KB alignment of in UPL CLANGDWARF build.
This reverts commit b3bfb8f22d43bd9577df85bec20e75eb2f659990.
- **Tests** - …

UefiPayloadPkg: Revert 4KB alignment of CLANGDWARF build

---

BaseTools/Source/Python/Ecc/EccToolError.py
BaseTools/Source/Python/Ecc/c.py

Per the discussion in https://github.com/tianocore/edk2/pull/6476, update Ecc code to allow the `@verbatim` Doxygen tag.
Before this change, when I added `@verbatim` blocks to SignedCapsulePkg/Include/Guid/EdkiiSystemFmpCapsule.h I got a line in results.csv reporting:
```
Only Doxygen commands '@bug', '@todo', '@example', '@file', '@attention', '@param', '@post', '@pre', '@retval', '@return', '@sa', '@since', …
```

BaseTools: Add @verbatim as allowed Doxygen tag

---

License-History.txt

Update BZ links to corresponding GitHub issues links now that the BZ -> GitHub issue migration is complete.

License-History.txt: Reflect bugzilla migration

---

ReadMe.rst

There's a lot of documentation that needs to be updated to reflect the bugzilla migration, but let's start with the main ReadMe.rst.
This would be useful to get into the stable tag, even though we're into soft freeze. (It's just the ReadMe.)

ReadMe.rst: reflect bugzilla migration

---

StandaloneMmPkg/Library/StandaloneMmCoreMemoryAllocationLib/StandaloneMmCoreMemoryAllocationLib.c

StandaloneMmCoreMemoryAllocationLib.c and StandaloneMmServicesTableLib.c are both defining gMmst, StandaloneMmCoreMemoryAllocationLib will be linked to StandaloneMmCore directly, StandaloneMmServicesTableLib may be linked to StandaloneMmCore indirectly, when they are both linked to StandaloneMmCore, there will be "lld-link: error: duplicate symbol: gMmst" build error with Clang compiler.
gMmst is declared in MmServicesTableLib.h and its definition should be owned by MmServicesTableLib.
This patch renames gMmst in StandaloneMmCoreMemoryAllocationLib.c to mMemoryAllocationMmst to avoid this build error.
Local build pass with Clang compiler when StandaloneMmCoreMemoryAllocationLib and StandaloneMmServicesTableLib are both linked to StandaloneMmCore.

StandaloneMmPkg StandaloneMmCoreMemoryAllocationLib: Rename gMmst

---

UefiPayloadPkg/UefiPayloadEntry/FitUniversalPayloadEntry.inf

Commit efbf5ed moves StackCheckLibStaticInit to StackCheckLib, and each SEC module has a dependency on StatckCheckLib now.
Add StatckCheckLib in FitUniversalPayloadEntry.inf to fix build issue.

UefiPayloadPkg: Add StackCheckLib to fix FIT build issue

---

IntelFsp2Pkg/FspSecCore/Ia32/FspApiEntryT.nasm
IntelFsp2Pkg/FspSecCore/X64/FspApiEntryT.nasm

Issue : Configuring TemporaryRamSize using FSP-T arch UPD
(added as part of Spec 2.5) is not working as expected.
Root cause : Code is reading the ImageAttribute from the wrong
address which confirms the TemporaryRamSize Configurability,
hence the TemporaryRamSize UPD is ignored. This is because
the code expects the FspInfoheader Offset to be in ESI/RSI
(from which ImageAttribute read) is not guaranteed as per the
current implementation.
Fix : Modified code to make sure that ESI/RSI contains the
FspInfoheader offset by time the code reads the ImageAttribute.
Tests : Verified the fix on Both 32 Bit and 64 Bit FSP Binaries by 
configuring the TemporaryRamSize using the FSPT Arch UPD.
Signed-off-by: Aravind P R <aravind.p.r@intel.com>
- **Breaking change** - Does this PR cause a break in …

Fixing TemporaryRamSize Configurability option

---

UefiPayloadPkg/UefiPayloadPkg.dsc

This patch moves `PcdPlatformBootTimeOut` from `[PcdsDynamicExDefault]` to `[PcdsDynamicHii]`, allowing the boot timeout to be configured through HII, rather than being a compile-time setting.

UefiPayloadPkg: Allow boot timeout to be configured

---

IntelFsp2Pkg/FspSecCore/SecFsp.c

FspSecCore only runs in API mode.
When it allocates memory in stack for FSP_GLOBAL_DATA, it does not initialize the FspMode to FSP_IN_API_MODE.
The patch enhances the code to initialize the FspMode as well.
This change does not have functionality impact as there should be some code elsewhere which sets the FspMode.
This change allows to remove the extra code logic that sets FspMode in API mode.

IntelFsp2Pkg/FspSecCore: initialize FspMode in FSP_GLOBAL_DATA

---

.azurepipelines/templates/pr-gate-build-job.yml
UefiCpuPkg/Include/Library/BaseArchLibSupport.h
UefiCpuPkg/Library/BaseArchSupportLib/AArch64/AArch64LibSupport.c
UefiCpuPkg/Library/BaseArchSupportLib/BaseArchSupportLib.inf
UefiCpuPkg/Library/BaseArchSupportLib/X86/X86LibSupport.c
UefiCpuPkg/UefiCpuPkg.dec
UefiCpuPkg/UefiCpuPkg.dsc
UefiPayloadPkg/Library/PciSegmentInfoLibAcpiBoardInfo/PciSegmentInfoLibAcpiBoardInfo.inf
UefiPayloadPkg/Library/PlatformHookLib/PlatformHookLib.c
UefiPayloadPkg/UefiPayloadEntry/AArch64/DxeHandoff.c
UefiPayloadPkg/UefiPayloadEntry/AArch64/DxeLoadFuncFit.c
UefiPayloadPkg/UefiPayloadEntry/FitUniversalPayloadEntry.inf
UefiPayloadPkg/UefiPayloadEntry/PrintHob.c
UefiPayloadPkg/UefiPayloadEntry/UefiPayloadEntry.c
UefiPayloadPkg/UefiPayloadEntry/UefiPayloadEntry.h
UefiPayloadPkg/UefiPayloadEntry/UefiPayloadEntry.inf
UefiPayloadPkg/UefiPayloadEntry/UniversalPayloadEntry.inf
UefiPayloadPkg/UefiPayloadPkg.dec
UefiPayloadPkg/UefiPayloadPkg.dsc
UefiPayloadPkg/UefiPayloadPkg.fdf
UefiPayloadPkg/UniversalPayloadBuild.py

REF: https://bugzilla.tianocore.org/show_bug.cgi?id=4849
Add base FIT image support on the AARCH64 architecture, introduce new dsc and fdf files for AARCH64 architecture, and introduce new PCD: PcdUseUniversalPayloadSerialPort to indicate which serial port component is used due to some serial port parameters are fixed for ARM SoC and Platform.
- N/A
- N/A
- N/A
Validated on top of qemu-system-x86_64 and qemu-system-aarch64.
export GCC5_AARCH64_PREFIX=aarch64-linux-gnu-
python UefiPayloadPkg/UniversalPayloadBuild.py -a AARCH64 -t GCC5 -b DEBUG --Fit

UefiPayloadPkg: Add AARCH64 support

---

MdeModulePkg/Core/Dxe/Gcd/Gcd.c

Add the `EFI_RESOURCE_ATTRIBUTE_SPECIAL_PURPOSE` resource attribute as per the PI 1.9 spec. This flag is used to indicate that the memory should be treated as special purpose memory (SPM).
- Test in system that produces resource descriptor HOBs with `EFI_RESOURCE_ATTRIBUTE_SPECIAL_PURPOSE`
Use the special purpose attribute based on platform need.

MdeModulePkg: Add the EFI_RESOURCE_ATTRIBUTE_SPECIAL_PURPOSE attribute

---

DynamicTablesPkg/Include/AcpiObjects.h
DynamicTablesPkg/Include/ArchCommonNameSpaceObjects.h
DynamicTablesPkg/Include/Library/AmlLib/AmlLib.h
DynamicTablesPkg/Include/X64NameSpaceObjects.h
DynamicTablesPkg/Library/Acpi/Common/AcpiSsdtCpuTopologyLib/SsdtCpuTopologyGenerator.c
DynamicTablesPkg/Library/Acpi/Common/AcpiSsdtCpuTopologyLib/SsdtCpuTopologyGenerator.h
DynamicTablesPkg/Library/Acpi/Common/AcpiSsdtCpuTopologyLib/X64/X64SsdtCpuTopologyGenerator.c
DynamicTablesPkg/Library/Common/AmlLib/CodeGen/AmlCodeGen.c
DynamicTablesPkg/Library/Common/TableHelperLib/ConfigurationManagerObjectParser.c
DynamicTablesPkg/Readme.md
MdePkg/Include/IndustryStandard/Acpi30.h
MdePkg/Include/IndustryStandard/Acpi40.h
MdePkg/Include/IndustryStandard/Acpi50.h
MdePkg/Include/IndustryStandard/Acpi51.h
MdePkg/Include/IndustryStandard/Acpi60.h
MdePkg/Include/IndustryStandard/Acpi61.h
MdePkg/Include/IndustryStandard/Acpi62.h
MdePkg/Include/IndustryStandard/Acpi63.h
MdePkg/Include/IndustryStandard/Acpi64.h
MdePkg/Include/IndustryStandard/Acpi65.h

This PR creates below ACPI objects for processor device for X64 arch
C-State: Creates _CST and _CSD objects.
P-State: Create _PCT, _PSS objects plus _PPC method
_PSD object for domain dependency
_CPC continue performance control object
Update AML library to generate _CST, _CSD, _PCT and _PSS node.
Generates _STA method based on configuration data.
Tested on AMD Platform
N/A

Creates C-State, P-State and CPC objects under processor for X64 arch

---

CryptoPkg/Library/OpensslLib/OpensslGen/AARCH64-GCC/crypto/aes/aesv8-armx.S
CryptoPkg/Library/OpensslLib/OpensslGen/AARCH64-GCC/crypto/bn/armv8-mont.S
CryptoPkg/Library/OpensslLib/OpensslGen/include/openssl/opensslv.h
CryptoPkg/Library/OpensslLib/OpensslGen/include/openssl/x509.h

Cherry-pick below fix by upgrade openssl submodule to 3.4.1
https://openssl-library.org/news/secadv/20250120.txt
CryptoPkg currently supports ECDSA Sign of NIST P-521, so this problem will affect EDK2 code.
Edk2\CryptoPkg\Include\Library\BaseCryptLib.h L28:
#define CRYPTO_NID_SECP521R1 0x0206 …

Openssl3.4.1 Upgrade

---

.azurepipelines/templates/platform-build-run-steps.yml
.azurepipelines/templates/pr-gate-steps.yml

Install a fresh python virtual environment every time to ensure
correct permissions and compatibility of the packages.
This is more robust than relying on being able to upgrade
an existing one.
pip upgrades are currently failing due to incorrect file permissions
in the container image virtual environment.
Let's not make use of the venv in the container and set up a fresh one
each time.
Test CI runs, for example …

CI: Install a fresh python virtual env every time (Linux)

---

MdeModulePkg/Universal/Console/TerminalDxe/Terminal.c
MdeModulePkg/Universal/Console/TerminalDxe/Terminal.h
MdeModulePkg/Universal/Console/TerminalDxe/TerminalConOut.c

When the terminal driver is active, currently terminals available through SetMode function are limited to mode 0 (80x25) despite multiple modes are configured as MaxMode value (e.g. 3 modes in mTerminalConsoleModeData list). Improve the function to support multiple modes based on the value. Additionally add more modes that match with the GraphicsConsoleDxe driver. This update is expected to help the symptom that the Setup or Shell screen becomes smaller due to the text mode.
- **Tests** - Does this PR include any …

MdeModulePkg/TerminalDxe: Support multiple modes for SetMode function

---

CryptoPkg/Library/BaseCryptLibMbedTls/SysCall/TimerWrapper.c

Add sleep() function to BaseCryptLibMbedTls library in Timerwrapper.c
Encountering an unresolved external symbol error for sleep while using the BaseCryptLibMbedTls library in RuntimeDxe
- **Tests** - …

CryptoPkg: Add sleep function to BaseCryptLibMbedTls Timerwrapper

---

MdeModulePkg/MdeModulePkg.ci.yaml

Looks like my PR #10668 broke the CI due to a duplicate guid. For some reason the CI in the PR didn't pick it up.
This adds an exception to the MdeModulePkg for the duplicate.
Sorry guys, my bad :)
N/A

MdeModulePkg: Fix CI fail because of guid duplicate error

---

BaseTools/Plugin/DebugMacroCheck/DebugMacroCheck.py

In the case that the total provided to the `_show_progress()` function is zero, do not show a progress bar to prevent aborts `ZeroDivisionError` when calculating the progress percentage.
- Test progress bar with zero and non-zero total
- N/A

DebugMacroCheck: Do not show progress bar with zero items

---

pip-requirements.txt

Updates from dependabot for pytools have been accumulating over
time. This updates the modules to latest.
`edk2-pytool-library` changes:
https://github.com/tianocore/edk2-pytool-library/compare/v0.21.9...v0.23.0
`edk2-pytool-extensions` changes:
https://github.com/tianocore/edk2-pytool-extensions/compare/v0.27.10...v0.29.0
Other pip modules are updated to latest versions tested alongside these pytool versions.
- CI
- Pytools integration and unit tests
Notes:
In these releases, Python 3.10 is a Minimum Supported Version while 3.11, 3.12, and 3.13 are official versions. For more details:
https://github.com/tianocore/edk2-pytool-extensions/blob/master/docs/contributor/python_msv.md

pip-requirements.txt: Update pip modules

---

UefiPayloadPkg/UefiPayloadPkg.dsc
UefiPayloadPkg/UniversalPayloadBuild.py

Add macro DISABLE_MMX_SSE to disable MMX and SSE usages in build time for IA32 and X64 to avoid MMX and SSE usages.
Add macro to control HandOffFdt configuration, PcdHandOffFdtEnable can be enabled without editing source code
- N/A
- **Security** - N/A
- **Tests** - N/A
Validated for both X64 and ARM64 with QEMU
python UefiPayloadPkg/UniversalPayloadBuild.py -t GCC5 -b DEBUG --Fit -DDISABLE_MMX_SSE=TRUE -DHAND_OFF_FDT_ENABLE=TRUE

UefiPayloadPkg: Add macroes to control settings and build options

---

.github/workflows/BuildPlatform.yml
.github/workflows/upl-build.yml
UefiPayloadPkg/PlatformCI/PlatformBuild.py
UefiPayloadPkg/PlatformCI/ReadMe.md
UefiPayloadPkg/UefiPayloadPkg.dsc
UefiPayloadPkg/UniversalPayloadBuild.py

Create a new PlatformBuild.py that can be called by stuart_build. UniversalPayloadBuild.py is consumed by new script to maintain backward compatibility and eliminate duplicate build steps.
Supported builds:
1. UEFI package build: directly call BaseTools build for EFI bin
2. UPL ELF/FIT build: call UniversalPayloadBuild.py
3. (new) UPL ELF - stuart build: follow stuart build steps to call PlatformBuild.py (edk2toolext is mandatory)
- Examples: Unit tests …

UefiPayloadPkg: Add stuart build support.

---

MdePkg/Include/IndustryStandard/IpmiNetFnStorage.h

As per IPMI spec, fru string can be maximum of 16 bytes length and fru length field can take 5 bits (to hold values up to 16 - 10000b).
Current implementation allocates only 4 bits for Fru String Length and this is causing an error when 16 bytes length fru string needs to be copied as the first 4 bits in 0x10 is 0.
Fixed the structure IPMI_SDR_RECORD_DEV_ID_STR_TYPE_LENGTH, by allocating 5 bits for Length field as per the spec instead of 4.

MdePkg: fix fru device description string copy error.

---

UnitTestFrameworkPkg/UnitTestFrameworkPkgHost.dsc.inc

PR #6408 introduced a regression by removing /WHOLEARCHIVE from VS20xx DLINK_FLAGS when building host based unit tests.
PR #5098 added /WHOLEARCHIVE to resolve issues when building host based unit tests with GoogleTest.
Build and run GoogleTests with VS2019 and VS2022
N/A

UnitTestFrameworkPkg: Fix host test /WHOLEARCHIVE regression

---

StandaloneMmPkg/Library/StandaloneMmHobLib/StandaloneMmHobLib.c

This patch is to print the warning message if GUID HOB not found
<_Describe the test(s) that were …

StandaloneMmPkg/Library: Print warning message if GUID HOB not found

---

BaseTools/Source/C/Makefiles/ms.common

Add /wd4200 to all visual studio builds of C tools in BaseTools. This disables warnings for use of flexible array members that are allowed in edk2 include files. Some tools use include files from MdePkg that use flexible array members.
This matches the warning disables used to build structured PCD in BaseTools/Source/Python/Workspace/DscBuildData.py where flexible array members are more widely used.
Build BaseTools before this change with flexible array member in MdePkg ACPI include files and GenFw build fails with an error.
Apply this change to add /wd4200 and GenFw build completed without error.
N/A

BaseTools/Source/C: Disable VS flexible array member warning

---

DynamicTablesPkg/Include/ConfigurationManagerObject.h
DynamicTablesPkg/Include/TableGenerator.h

The CREATE_CM_OBJECT_ID() and CREATE_TABLE_GEN_ID() macros shift an enum by 31 bits.  As enums are signed integers, this generates a portability finding from cppcheck.  To resolve the finding, we'll cast the enum values to the type expected as output from the macro.
Reviewed-by: Girish Mahadevan <gmahadevan@nvidia.com>
cppcheck finding is resolved.  DynPkg tests continue to pass.
N/A

DynamicTablesPkg: Resolve cppcheck findings in macros

---

PrmPkg/Include/PrmDataBuffer.h
PrmPkg/PrmConfigDxe/PrmConfigDxe.c

This commit consists of two commits:
PrmPkg: PRM support for non-existent MMIO ranges
--
This is regarding PRM modules that are describing MMIO ranges.
When PrmConfigDxe is calling GetMemorySpaceDescriptor() with a memory range that is visible to the boot processor but has not been added to the memory map GetMemorySpaceDescriptor() will return EFI_SUCCESS and then return a memory descriptor indicating that the region is non-existent. This causes SetRuntimeMemoryRangeAttributes() to believe that the region has already been added to the memory map and will eventually cause an ASSERT.
This PR allows for SetRuntimeMemoryRangeAttributes() to treat a non-existent MMIO range the same as a range that triggered a EFI_NOT_FOUND error response from GetMemorySpaceDescriptor().
PrmPkg: Align Data …

PrmPkg: Handle Non-Existent MMIO and Align Signature to Spec

---

MdePkg/Include/IndustryStandard/Acpi64.h

Add structures for the ACPI table CEDT as defined in the CXL 3.0 specification
Adding definitions for the ACPI CEDT table defined in CXL.
- No.
- No.
- No.
Type definitions only; verified in local build.
N/A

MdePkg: Add ACPI CEDT table structures

---

MdeModulePkg/Library/UefiBootManagerLib/BmBoot.c
MdeModulePkg/Library/UefiBootManagerLib/BmBootDescription.c
MdePkg/Include/Protocol/Http.h
NetworkPkg/HttpBootDxe/HttpBootClient.c
NetworkPkg/HttpBootDxe/HttpBootClient.h
NetworkPkg/HttpBootDxe/HttpBootConfig.c
NetworkPkg/HttpBootDxe/HttpBootConfigNVDataStruc.h
NetworkPkg/HttpBootDxe/HttpBootConfigStrings.uni
NetworkPkg/HttpBootDxe/HttpBootConfigVfr.vfr
NetworkPkg/HttpBootDxe/HttpBootDxe.h
NetworkPkg/HttpBootDxe/HttpBootImpl.c
NetworkPkg/HttpBootDxe/HttpBootImpl.h
NetworkPkg/HttpBootDxe/HttpBootSupport.c
NetworkPkg/HttpBootDxe/HttpBootSupport.h
NetworkPkg/HttpDxe/HttpDriver.h
NetworkPkg/HttpDxe/HttpDxe.inf
NetworkPkg/HttpDxe/HttpImpl.c
NetworkPkg/HttpDxe/HttpProto.c
NetworkPkg/HttpDxe/HttpProto.h
NetworkPkg/HttpDxe/HttpsSupport.c

Adds new feature to support HTTP Boot through Proxy Server. Adds HTTP CONNECT flow to connect through Proxy Server to then use HTTP GET/HEAD to retrieve Endpoint Server boot file.
Implementation based on UEFI Specification v2.11 as follows - 
Section 24.7.3.1 - Updated code to recognize device path with ProxyURI included
Section 24.7.10 - Updated code to use HTTP CONNECT method to connect to Proxy Server and use it to forward the HEAD/GET request to Endpoint Server's BootURI.
Section 29.6.6 - Added EFI_HTTP_CONNECT_REQUEST_DATA structure for HttpMethodConnect usage in EFI_HTTP_PROTOCOL.Request() 
REF - #10239 
Verified as part of Edk2-staging branch. Also tested on CI.
N/A

Add support for HTTP Boot through Proxy Server

---

MdeModulePkg/Application/CapsuleApp/CapsuleApp.c

After a failed capsule updated it returns 0 and not Status failure.
Tested-by: Ilias Apalodimas <ilias.apalodimas@linaro.org>
Signed-off-by: Javier Tia <javier.tia@linaro.org>
self-explanatory by the change.
- Examples: Crypto algorithm change or buffer overflow …

CapsuleApp: Fix proper return after capsule update

---

DynamicTablesPkg/Library/Acpi/Common/AcpiSsdtCpuTopologyLib/X64/X64SsdtCpuTopologyGenerator.c

Relocate StaToken detection and _STA method generation logic within the loop for each processor object.
Relocate StaToken detection and _STA method generation logic within the loop for each processor object.
Tested on AMD X64 platform
N/A

DynamicTablesPkg/AcpiSsdtCpuTopologyLib: Correct _STA method for X64

---

OvmfPkg/Library/HardwareInfoLib/HardwareInfoTypesLib.h

Reserve a new device type ID for Virtio MMIO devices intended to be used by
the Secure VM Service Module (SVSM).
Coconut SVSM will be using a Virtio-Blk device via the MMIO transport to
persist state, when running under Qemu. The guest OS shall not try to use the device.
The HardwareInfoLib is an ideal channel to communicate the device
information to the SVSM, due to its simplicity and flexibility to
include arbitrary information, and since it does not interfere with
regular hardware configuration mechanisms of the guest OS.
This device type is intended for the SVSM only and no code is added
to EDK2 that makes use of it.
- N/A
- N/A

OvmfPkg/HardwareInfoLib: Reserve device type ID for SVSM

---

BaseTools/Plugin/DebugMacroCheck/DebugMacroCheck.py
DynamicTablesPkg/Library/Acpi/X64/AcpiFacsLib/FacsGenerator.c

- In the commit 42a141800c0c26a09d2344e84a89ce4097a263ae there was a misuse of "is_dir" method.
- Treating it as an object rather than function call, which caused if-condition to always as "false".
- No files would be added to scanning list due to incorrect usage.
- This patch corrects the issue by properly using "is_dir()".
- No, this change is bug-fix only.
- No, this change do not include any security-related change.
- This change passed the EDK-II CI build without any issue.
- Check the pytool plugin could be executed correctly.
- N/A.

BaseTools: Fix Debug Macro Checking to Include Scanning Files

---

UnitTestFrameworkPkg/Library/UnitTestPeiServicesTablePointerLib/UnitTestPeiServicesTablePointerLib.c
UnitTestFrameworkPkg/Library/UnitTestPeiServicesTablePointerLib/UnitTestPeiServicesTablePointerLib.h
UnitTestFrameworkPkg/Library/UnitTestPeiServicesTablePointerLib/UnitTestPeiServicesTablePointerLibMisc.c

There are duplicate library function names between 2 Unit Test libraries (UnitTestPeiServicesTablePointerLib and UnitTestUefiBootServicesTableLib). There are 3 functions (UnitTestAllocatePages, UnitTestAllocatePool and UnitTestFreePage). This update avoids the duplication and prevents a build error when building a Unit Test application that links the libraries based on UnitTestFrameworkPkg.
Build Error Example : 
UnitTestUefiBootServicesTableLib.lib(UnitTestUefiBootServicesTableLibMemory.obj) : error LNK2005: _UnitTestAllocatePages already defined in UnitTestPeiServicesTablePointerLib.lib(UnitTestPeiServicesTablePointerLibMisc.obj)
UnitTestUefiBootServicesTableLib.lib(UnitTestUefiBootServicesTableLibMemory.obj) : error LNK2005: _UnitTestAllocatePool already defined in …

UnitTestFrameworkPkg: Avoid duplicate library function names

---

StandaloneMmPkg/Core/StandaloneMmCore.c

When running StandaloneMmCore on a system, do not assert if gMmCommBufferHobGuid is not found. Output a debug message that details that the gMmCommBufferHobGuid was not found, that only root MmiHandlers will be dispatched.
Tested on virtual platform with top of tree TFA, with HOB_LIST=1 TRANSFER_LIST=1 used when building TFA.
N/A

StandaloneMmPkg: Remove Assert when gMmCommBufferHobGuid does not exist.

---

.mergify/config.yml

Periodically, mergify rebase operations will fail because an account is selected to perform the rebase that does not have permissions to do the rebase.
Instead, use the tianocore-issues account to perform the rebase operation.

.mergify: Use tianocore-issues to rebase PRs for merge

---

Maintainers.txt
MdePkg/Include/Register/Amd/Svsm.h
OvmfPkg/Include/Dsc/OvmfTpmComponentsDxe.dsc.inc
OvmfPkg/Include/Dsc/OvmfTpmLibs.dsc.inc
OvmfPkg/Library/AmdSvsmLib/AmdSvsmLib.c
SecurityPkg/Library/Tpm2DeviceLibDTpm/Tpm2DeviceLibDTpm.c
SecurityPkg/Library/Tpm2DeviceLibDTpm/Tpm2DeviceLibDTpmSvsm.c
SecurityPkg/Library/Tpm2DeviceLibDTpm/Tpm2DeviceLibDTpmSvsm.inf
SecurityPkg/Library/Tpm2DeviceLibDTpm/Tpm2InstanceLibDTpm.c
SecurityPkg/Library/Tpm2DeviceLibDTpm/Tpm2InstanceLibDTpmSvsm.c
SecurityPkg/Library/Tpm2DeviceLibDTpm/Tpm2InstanceLibDTpmSvsm.inf
SecurityPkg/Library/Tpm2DeviceLibDTpm/Tpm2Ptp.c
SecurityPkg/Library/Tpm2DeviceLibDTpm/Tpm2Ptp.h
SecurityPkg/Library/Tpm2DeviceLibDTpm/Tpm2PtpSvsmShim.c
SecurityPkg/Library/Tpm2DeviceLibDTpm/Tpm2PtpSvsmShim.h
SecurityPkg/Library/Tpm2DeviceLibDTpm/Tpm2Svsm.c
SecurityPkg/Library/Tpm2DeviceLibDTpm/Tpm2Svsm.h
SecurityPkg/SecurityPkg.ci.yaml
SecurityPkg/SecurityPkg.dec
SecurityPkg/SecurityPkg.dsc
UefiCpuPkg/Include/Library/AmdSvsmLib.h
UefiCpuPkg/Library/AmdSvsmLibNull/AmdSvsmLibNull.c

This is version 2 of #5770.
This series adds a DTpm driver to communicate with a virtual TPM running in the Secure VM Service Module (SVSM), enabling OVMF to do measured boot in SEV-SNP confidential VMs.
SEV-SNP provides a feature known as VM Privilege Level (VMPL), which allows for services to be run in the guest at different privilege levels. By running at VMPL0 (most priviledged VM level), the SVSM can be used to provide privileged services, e.g. virtual TPM, for the guest rather than trust such services from the hypervisor.
As described in the [SVSM specification](https://www.amd.com/content/dam/amd/en/documents/epyc-technical-docs/specifications/58019.pdf), guest components can call to the SVSM vTPM through the vTPM protocol (protocol-id 2).
The vTPM protocol follows the [Microsoft …

[v2] Add support for a SVSM vTPM

---

MdeModulePkg/Bus/Pci/XhciDxe/XhciSched.c

Some high/super-speed devices incorrectly report full-speed bInterval values in their interrupt endpoint descriptors which results in an assertion error due to being out of range of the spec-expected values.
Rather than asserting, try to adjust those assuming they were expressed in units of ms with an upper limit of 8ms.
Inspiration was taken from the Linux kernel which has long had similar workarounds in its USB core (links to git.kernel.org):
* [USB: Fix up full-speed bInterval values in high-speed interrupt descriptor](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=300871cd963e24a68aaa9b762f4a10403697d9be)  (2007)
* [USB: change bInterval default to 10 ms](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=08c5cd37480f59ea39682f4 …

MdeModulePkg/XhciDxe: Adjust out-of-range bInterval values

---

ArmPkg/Drivers/MmCommunicationDxe/MmCommunication.c
ArmPkg/Drivers/MmCommunicationDxe/MmCommunication.inf

Create DxeMmReadyToLockProtocol notification that Mm requires
The mmCommunication driver in ArmPkg needs to create a gEfiDxeMmReadyToLockProtocolGuid notification so that MmReadyToLockHandler can be called
Tested in Arm platform

ArmPkg: Create DxeMmReadyToLockProtocol notification

---

MdeModulePkg/Library/VarCheckHiiLib/VarCheckHiiLibStandaloneMm.c

While attempting to build MdeModulePkg.dsc for other reasons, I was blocked by a compiler error:
```
/work/git/edk2/MdeModulePkg/Library/VarCheckHiiLib/VarCheckHiiLibStandaloneMm.c:78:7: error: variable 'Status' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
78 |   if (DispatchHandle != NULL) {
|       ^~~~~~~~~~~~~~~~~~~~~~
/work/git/edk2/MdeModulePkg/Library/VarCheckHiiLib/VarCheckHiiLibStandaloneMm.c:82:18: note: uninitialized use occurs here
82 |   if (EFI_ERROR (Status)) {
|                  ^~~~~~
```
Then when I looked at the code, I noticed the documented return values are not what the function returns.
I do think there are additional issues with this code; CommBuffer and CommBufferSize are documented as needing to be not-NULL, but are …

MdeModulePkg: address VarCheckHiiLib build failures

---

Maintainers.txt

UefiPayloadPkg is used by non-UEFI bootloaders, e.g. coreboot.
Shuo works on Xeon-SP coreboot and will contribute to the
reviewing activity for UefiPayloadPkg.

Maintainers.txt: Add Shuo Liu as UefiPayloadPkg Reviewer

---

UefiCpuPkg/Include/Guid/MpInformation2.h

There will be build failure because of EFI_AP_PROCEDURE definition not found if MpInformation2.h is included by base type library.
MpInformation2.h depends on MpService.h because of EFI_PROCESSOR_INFORMATION definition, and then MpService.h depends on PiMultiPhase.h because of EFI_AP_PROCEDURE definition.
This patch updates MpInformation2.h to include PiMultiPhase.h instead of PiPei.h and also removes SecPlatformInformation.h including. It also does minor refinement to file header description.

UefiCpuPkg MpInformation2.h: Include PiMultiPhase.h

---

BaseTools/Source/C/GenFv/GenFvInternalLib.c

In case of the FV with VTF, the left size should be enough to add the minimum pad file size (EFI_FFS_FILE_HEADER, 0x18). It prevents the build error, "GenFv: ERROR 0006: invalid FFS file header checksum" caused by the pad file overwriting some header data in VTF. This includes these updates for CalculateFvSize() function.
1. If NumBlocks is not defined, ensure the minimum pad file size for the left size (if the pad file is required as VTF is not bottom aligned at end of block, insert EFI_FFS_FILE_HEADER to ensure the pad file size)
2. If NumBlocks is defined, report more clear error message (the required fv image size = 0x%x. the set fv image size = 0x%x. Free space left is not enough to add a pad file (0x18))
3. Remove MaxPadFileSize, which is reported when the taken size is same as the …

BaseTools/GenFv: Ensure the minimum pad file size for the FV with VTF

---

BaseTools/Source/Python/build/BuildReport.py

Module PCD in compile information is missed in module_report.json

BaseTools: Fix missing module PCD in compile information of build report

---

MdeModulePkg/Library/DxeCorePerformanceLib/DxeCorePerformanceLib.c

Fix the issues found on Intel platform:
##
Issue1:  After enabling the MM performance, boot fails with assert issue at https://github.com/tianocore/edk2/blob/master/StandaloneMmPkg/Drivers/MmCommunicationDxe/MmCommunicationDxe.c#L279
Root cause: CommSize value is incorrect.
Fix: Set CommSize to OFFSET_OF (EFI_MM_COMMUNICATE_HEADER, Data) + (UINTN)MmCommBufferHeader->MessageLength
##
Issue2: Hang when execute 'dp' command under UEFI shell.
Root cause: The Smm Boot Record data is all 0, causing a dead loop when 'dp' parses the smm data. BootRecordDataPayloadSize is incorrect, smaller than the actual size of the Smm Boot Record data, causing failure of copying data from SMM to comm buffer:
https://github.com/tianocore/edk2/blob/master/MdeModulePkg/Library/SmmCorePerformanceLib/MmCorePerforman …

MdeModulePkg/DxeCorePerformanceLib: Fix incorrect size calculation

---

PrmPkg/Samples/PrmSampleAcpiParameterBufferModule/PrmSampleAcpiParameterBufferModule.inf
PrmPkg/Samples/PrmSampleContextBufferModule/PrmSampleContextBufferModule.inf

Correct the GCC GenFw and ld flag to build PRM run time modules.
These changes are made for X64 GCC compiler, current present for AARCH64 only.
Build on Ubuntu environment
N/A

PrmPkg: Correct the flags for GCC compiler

---

RedfishPkg/RedfishHttpDxe/RedfishHttpDxe.c

Use AsciiStrLen function instead of AsciiStrSize to determine the length of Basic Auth string.
Use AsciiStrSize, which leads to the incorrect length of the Basic Auth string.
Use AsciiStrLen function instead of AsciiStrSize.
The change was tested on Redfish simulator.
None

RedfishPkg/RedfishHttpDxe : Fix the incorrect length of the Basic Auth

---

MdeModulePkg/Core/Dxe/Gcd/Gcd.c

Hot Pluggable memory resource attribute was introduced in UEFI 2.11 and PI 1.9 specifications.
This type should have an entry in the Attribute Conversion Table.
- **Breaking change** - Does this PR cause a break in build or boot behaviour?
N/A
N/A

MdeModulePkg/Core: Add Hot Pluggable type to Attribute Conversion Table

---

BaseTools/Source/Python/build/build.py

If an FV_SPARE_SPACE_THRESHOLD is enabled and an FV is 100% full with 0 bytes free, then this is likely a special FV that may have alignment requirements
for the FFS file for both the start address and the length and the FFS file consumes all the available FV space.
Reduce FV_SPARE_SPACE_THRESHOLD from an error to a warning if this FV 0 bytes free condition is
detected.
PR #10828 introduced the generation of these error conditions for an FV with large alignment requirements. The pad region before the aligned FFS file used to be counted as free space even though it could never be used due to the alignment requirements. There was actually no free space available. PR #10828 fixed the free space calculation to properly show it as 0 bytes free, and this change then caused build error when …

BaseTools/build: Reduce special FV full to warning

---

Maintainers.txt

- Updated Maintainers.txt to include Guillermo Antonio Palomino Sosa as a maintainer for the BaseTools section.
- Added his contact information: email and GitHub username.
This change updates the Maintainers.txt file to include Guillermo Antonio Palomino Sosa as a maintainer for the BaseTools section. 
- **Breaking change** - No, this PR does not cause any break in build or boot behavior.
- **Security** - No, this PR does not have a direct security impact.
- **Tests** - No, this PR does not include any explicit test code.
N/A - This change is documentation-only and does not affect functionality.
N/A - No integration steps are required for this documentation update.

Maintainers.txt: Add new maintainer to BaseTools section

---

ArmPkg/Include/Library/ArmFfaLib.h
ArmPkg/Include/Library/ArmSmcLib.h
ArmPkg/Include/Library/ArmSvcLib.h
ArmPkg/Library/ArmFfaLib/ArmFfaCommon.c
ArmPkg/Library/ArmFfaLib/ArmFfaCommon.h
ArmPkg/Library/ArmSmcLib/AArch64/ArmSmc.S
ArmPkg/Library/ArmStandaloneMmCoreEntryPoint/ArmStandaloneMmCoreEntryPoint.c
ArmPkg/Library/ArmSvcLib/AArch64/ArmSvc.S

Current SMC and SVC only supports up to 8 registers.
However, the FF-A spec has definition for FFA direct request 2 which could use up to 18 registers.
This change is added to support such use case.
Note:
https://review.trustedfirmware.org/c/TF-A/trusted-firmware-a/+/36018 must be paired to make sure SPMC at EL3 to work properly.
This was tested on QEMU SBSA and booted to Windows
N/A

Add 18 register support for SMC and SVC calls for AArch64 platforms

---

MdePkg/Include/IndustryStandard/IoRemappingTable.h

This corrects the value of the type `Named Component` and `Root Complex` in the structure comments, according to the DEN0049E_IO_Remapping_Table specification [1], table 2.
[1] https://developer.arm.com/documentation/den0049/latest
N/A.
N/A.

MdePkg/IndustryStandard: Fix typos in IoRemappingTable.h

---

UefiPayloadPkg/Library/CbParseLib/CbParseLib.c
UefiPayloadPkg/UefiPayloadEntry/UefiPayloadEntry.c

Recent AMD platforms reserve parts of the lower DRAM where UefiPayload is being loaded to and since UefiPayloadEntry doesn't care, it uses the reserved memory for HOB and memory allocation.
The bootloader cannot prevent this, as it can only place the UEFI FV in usable DRAM, but it has no control over EfiBootService memory allocations.
This issue prevents boot on those platforms without any specific error message. It's not vendor specific and can happen on every platform.
Add the same logic as used on UniversalPayload and do the following:
- Walk bootloader provided memory information
- Skip everything that's not marked as usable DRAM
- Align entries to 1MiB boundary
- Don't use memory above 4GiB on x86_32
- Skip memory ranges too small
- Don't use memory currently occupied by the UEFI FV …

UefiPayloadPkg: UefiPayloadEntry: Don't use reserved DRAM for EfiBootServices

---

BaseTools/Source/Python/Workspace/WorkspaceCommon.py

When a module M depends on L1, which depends on L2, which depends on L3, the build fails when the library instance of L3 cannot be found according to the library class-instance mapping configuration specified in the DSC file.
When such failure happens, the build tool only prints that the instance of L3 required by module M cannot be found. But it does not tell how L3 is required by M.
The change enhances build tool to print the entire dependency chain when such failure happens.
With the change, the new error message will be as follows:
<dsc-path>(...): error 4000: Instance of library class [L3] is not found for module [M], [L3] is:
consumed by <instance of L2>
consumed by <instance of L1>
<_For each item, place an "x" …

BaseTools: Dump library dependency chain on build failure

---

SecurityPkg/Library/DxeImageVerificationLib/DxeImageVerificationLib.c
SecurityPkg/SecurityFixes.yaml
SecurityPkg/VariableAuthenticated/SecureBootConfigDxe/SecureBootConfigImpl.c

CVE: CVE-2024-38797
In HashPeImageByType(), the hash of a PE/COFF image is calculated. This function may get untrusted input.
Inside this function, the following code verifies the loaded image has the correct format, by reading the second byte of the buffer.
```c
if ((*(AuthData + 1) & TWO_BYTE_ENCODE) != TWO_BYTE_ENCODE) {
...
}
```
Since the input image is not trusted, it may not have a second byte present to read. So this poses a potential out of bounds read error.
With the below fix, we are ensuring that we don't perform an out of bound read. i.e, we make sure that AuthDataSize is greater than 1.
```c
if (AuthDataSize > 1 && (*(AuthData + 1) & TWO_BYTE_ENCODE) != TWO_BYTE_ENCODE){
...
}
```
AuthDataSize size is verified before reading the second byte. So, if AuthDataSize is less than …

SecurityPkg: Out of bound read in HashPeImageByType()

---

UefiPayloadPkg/UefiPayloadPkg.dsc

OVMF SmbiosVersionLib applies to QEMU SMBIOS only, it does not work on Bare Metal platform. Drop SmbiosVersionLib dependency for SmbiosDxe on AArch64 architecture.

UefiPayloadPkg: Drop SmbiosVersionLib for SmbiosDxe on AArch64

---

StandaloneMmPkg/Core/Dispatcher.c
StandaloneMmPkg/Core/StandaloneMmCore.h
StandaloneMmPkg/Core/StandaloneMmCore.inf
StandaloneMmPkg/StandaloneMmPkg.dsc

Include PerformanceLib for StandaloneMmCore, add performance logging for MM driver loading and starting.
Add FV_FILEPATH_DEVICE_PATH into Loaded Image protocol for MM driver, then StandaloneMmCorePerformanceLib can get the FILE_GUID from the device path.
MM Boot record data for driver load and start can be found in FPDT dump on Intel platform.
N/A

StandaloneMmPkg/Core: Performance logging for MM driver load and start

---

BaseTools/Source/Python/FMMT/core/FvHandler.py

When using the replace function, if the replaced file located in a compress section, then the tool will re-build the section. As the compress status set in the wrong place, in some situation, the compress will do twice times which is a wrong behavior.
This patch is used to fix this issue.
No
No
No
successfully build and boot in OVMFPKG
N/A

BaseTools: Fix FMMT Compress wrong behavior

---

UefiCpuPkg/Library/MmSaveStateLib/IntelMmSaveStateLib.inf
UefiCpuPkg/Library/SmmCpuPlatformHookLibNull/SmmCpuPlatformHookLibNull.inf

IntelMmSaveStateLib and SmmCpuPlatformHookLibNull were limited to DXE_SMM_DRIVER MM_STANDALONE
in https://github.com/tianocore/edk2/pull/5805. Previously the supported modules were not limited.
Add MM_CORE_STANDALONE as a supported module type for these libraries to support a StmmCore
implementation that requires it.
Compile failed prior to fix, compiled correctly after. 
N/A

UefiCpuPkg: Add StmmCore for IntelMmSaveStateLib,SmmCpuPlatformHookLibNull.

---

MdeModulePkg/Include/Guid/MmCommBuffer.h

Make sure MM buffer structures are packed as different FW modules access them.
Create packed structures which describe MM info. These structures are used across different FW compoents (sometimes non edk2).
No
No
No
Change was tested on RISC-V MM implementation to be upstreamed later.

Make MM buffer related structures packed

---

MdeModulePkg/Bus/Usb/UsbMassStorageDxe/UsbMassBoot.c
MdeModulePkg/Bus/Usb/UsbMassStorageDxe/UsbMassBot.c

During USB mass storage enumeration, if a USB transfer fails due to any other reason, UsbMassStorageDxe will attempt to reset the device. With the commit ed07a2bb11 ("MdeModulePkg/UsbBusDxe: USB issue fix when the port reset"), UsbIoPortReset now tears down the USB device context and reinstalls it (via DisconnectController & ConnectController).
This process is not handled by the UsbMassDriver, causing the upper layer to access an old pointer that has been freed during the teardown, leading to a crash.
Example:
UsbMassReadBlocks (Failed)
-> UsbMassReset
-> UsbBotResetDevice
-> UsbIoPortReset (teardown + reinstall and return)
Now the UsbBot context pointer is invalidated and pointing to freed memory.
-> UsbBot->UsbIo->UsbControlTransfer() therefore accesses a invalid pointer and crashes. …

MdeModulePkg/UsbMassStorageDxe: Remove Port Reset

---

SecurityPkg/Library/AuthVariableLib/AuthService.c

RsaGetPublicKeyFromX509 allocates memory for RsaContext parameter and the memory allocated earlier is not necessary
Verified basic secure boot keys are enrolled which goes thru CheckSignatureListFormat
N/A

SecurityPkg/AuthVariableLib: Fix memory leak in CheckSignatureListFormat

---

SecurityPkg/Library/SecureBootVariableLib/SecureBootVariableLib.c
SecurityPkg/Library/SecureBootVariableLib/UnitTest/SecureBootVariableLibUnitTest.c

This PR prevents setting the  Dbx variable the Default being provided is less than the size of the EFI_SIGNATURE_LIST structure. This is to prevent the setting of ab invalid DBX which would cause the system to fail to boot.
Additionally, this can be used to signal that setting the DBX should leave DBX undefined for Platforms that want to let the OS be the sole servicer of the DBX.
Breakdown of the math is as follows:
1. **`sizeof(EFI_SIGNATURE_LIST)`**:
- This is the size of the `EFI_SIGNATURE_LIST` structure itself, which includes: - `EFI_GUID SignatureType` (16 bytes) - `UINT32 SignatureListSize` (4 bytes) - `UINT32 SignatureHeaderSize` (4 bytes) - `UINT32 SignatureSize` (4 bytes)
- Total: `16 + 4 + 4 + 4 = 28 bytes`
2. **`SignatureHeaderSize`**:
- This is the size of the optional …

SecurityPkg: Prevent invalid DBX from being set

---

SecurityPkg/Library/Tpm2DeviceLibDTpm/Tpm2DeviceLibDTpmSvsm.inf
SecurityPkg/Library/Tpm2DeviceLibDTpm/Tpm2InstanceLibDTpmSvsm.inf
SecurityPkg/Library/Tpm2DeviceLibDTpm/Tpm2PtpSvsmShim.c

This patch fixes boot failures observed on SEV and SEV-ES VMs using OvmfPkg broken by https://github.com/tianocore/edk2/pull/6527.
AmdSvsmLib currently doesn't check if SNP enabled, thus using AmdSvsmLib may errantly cause the caller code to believe SVSM is present. This can lead to boot failure on non-SNP enabled VMs.
Compiled OVMF target (but not tested) on edk2 upstream code following instructions https://github.com/tianocore/tianocore.github.io/wiki/Common-instructions
Compiled and tested on internal edk2 fork on SEV VM boot-up using internal hypervisor.
N/A

SecurityPkg-Tpm2DeviceLibDTpm: Check SNP enabled prior to using AmdSvsmLib

---

MdePkg/Include/Ppi/MpServices2.h
MdePkg/MdePkg.ci.yaml
UefiCpuPkg/UefiCpuPkg.ci.yaml
UefiCpuPkg/UefiCpuPkg.dec

Commit aef50446ced0662c8dfd968ab0ea05cc88b989ae
removed gEdkiiPeiMpServices2PpiGuid from UefiCpuPkg.dec which causes build breaks if an INF [Ppis] section lists gEdkiiPeiMpServices2PpiGuid. There is no method for a DEC file for conditionally declare a PPI.
In order to support the migration from use of
gEdkiiPeiMpServices2PpiGuid to the preferred use of the gPeiMpServices2Ppi, add gEdkiiPeiMpServices2PpiGuid back to the UefiCpuPkg.dec and update MpServices2.h in MdePkg to define EDKII_PEI_MP_SERVICES2_PPI_GUID and
EDKII_PEI_MP_SERVICES2_PPI.
All references to the EDK II PEI MP Services 2 PPI can be removed after all downstream consumers have had a chance to perform the migration.

UefiCpuPkg: Add back gEdkiiPeiMpServices2PpiGuid

---

MdePkg/Library/UefiDevicePathLib/UefiDevicePathLibBase.inf

Remove unused gEfiDevicePathProtocolGuid in Base UefiDevicePathLib since it's not used.
No impact

MdePkg/Library: Remove unused gEfiDevicePathProtocolGuid

---

ShellPkg/Library/UefiShellDebug1CommandsLib/SmbiosView/QueryTable.c

This patch adds additional support for the new CAMM form factor defined in SMBIOS specification 3.8.0
This change extends the Memory Form Factor Table to include the new entry for "CAMM". SMBIOS spec 3.8.0 defines this entry as well. The change is intended to get the edk2 code in sync with 3.8.0 spec.
The change only impacts ShellPkg package and it is a follow up to the corresponding change in MdPkg to add the CAMM entry (PR #10965)
- Examples: Unit tests …

ShellPkg: Updated Memory Form Factor definition per SMBIOS 3.8.0

---

MdeModulePkg/Library/ArmFfaLib/ArmFfaPeiLib.inf

If ArmFfaLibRxTxMap is called before permanent memory is installed the memory allocated for the FF-A buffers will be migrated to the permanent memory after it is installed without updating gArmFfaRxTxBufferInfoGuid or unmapping the old buffers and mapping the updated buffers.
An ASSERT in MemoryServices at ExitBootServices is triggered when ArmFfaDxeLib tries to call FreeAlignedPages on the original buffer reference.
Add depex on gEfiPeiMemoryDiscoveredPpiGuid for ArmFfaPeiLib so any Peims that use FF-A are only dispatched after permanent memory is available.
- Examples: …

MdeModulePkg/ArmFfaLib: Add depex on gEfiPeiMemoryDiscoveredPpiGuid

---

ArmVirtPkg/ArmVirt.dsc.inc
ArmVirtPkg/ArmVirtQemu.dsc
ArmVirtPkg/ArmVirtQemuFvMain.fdf.inc
ArmVirtPkg/ArmVirtQemuKernel.dsc
OvmfPkg/Include/IndustryStandard/QemuUefiVars.h
OvmfPkg/Library/HardwareInfoLib/HardwareInfoTypesLib.h
OvmfPkg/OvmfPkg.dec
OvmfPkg/OvmfPkgX64.dsc
OvmfPkg/OvmfPkgX64.fdf
OvmfPkg/PlatformPei/Platform.c
OvmfPkg/PlatformPei/PlatformPei.inf
OvmfPkg/VirtMmCommunicationDxe/QemuFdt.c
OvmfPkg/VirtMmCommunicationDxe/QemuHwInfo.c
OvmfPkg/VirtMmCommunicationDxe/QemuMmio.c
OvmfPkg/VirtMmCommunicationDxe/QemuX64.c
OvmfPkg/VirtMmCommunicationDxe/VirtMmCommunication.c
OvmfPkg/VirtMmCommunicationDxe/VirtMmCommunication.h
OvmfPkg/VirtMmCommunicationDxe/VirtMmCommunication.inf

- **OvmfPkg: add IndustryStandard/QemuUefiVars.h**
- **OvmfPkg: add new VirtMmCommunicationDxe driver**
- **OvmfPkg/OvmfPkgX64: add QEMU_VARS option**
- **OvmfPkg: add PcdQemuVarsRequire**
- **OvmfPkg/VirtMmCommunicationDxe: stop on init failure**
- **OvmfPkg/VirtMmCommunicationDxe: add arm support**
- **ArmVirtPkg/ArmVirtQemu: add QEMU_VARS option**
- **[fixup] PcdQemuVarsRequire clash**

ovmv / armvirt: add support for qemu uefi variable store

---

MdeModulePkg/Library/DeviceManagerUiLib/DeviceManager.c
MdeModulePkg/Library/DeviceManagerUiLib/DeviceManagerVfr.Vfr

Issue link:https://github.com/tianocore/edk2/issues/10925
If new HII resource is installed, show it in DeviceManager form. If HII resource is uninstalled, remove it from DeviceManager form. So once we enter DeviceManager form, form data should be refreshed to display dynamically.
Cc: Li Chao <lichao@loongson.cn>
Cc: Qian Dongyan <qiandongyan@loongson.cn>
- Examples: Does it add a new library class or …

DeviceManagerUiLib:Update DeviceManager form data when the form opens.

---

ArmPkg/Drivers/ArmScmiDxe/ScmiClockProtocol.c

MessageParams1 and MessageParams2 always point to adjacent slots in the payload buffer, so no need to keep two separate pointers.

ArmPkg/ArmScmiDxe: Use array indexing to access adjacent buffers

---

OvmfPkg/Library/CcExitLib/CcExitVcHandler.c

The MsrExit() routine uses an incorrect register to check for the CAA MSR. Instead of checking RCX, the input register for RDMSR/WRMSR that holds the MSR value, it is checking RAX, which results in failure to detect the CAA MSR request. The check should only be checking the lower 32-bits of the register (ECX), too.
Change the check in MsrExit() to check the MSR value contained in ECX.
Fixes: 47001ab98914 ("Ovmfpkg/CcExitLib: Provide SVSM discovery support")
- **Tests** - Does this PR include any explicit test …

OvmfPkg/CcExitLib: Use the proper register when filtering MSRs

---

MdeModulePkg/Core/Dxe/Gcd/Gcd.c
MdeModulePkg/Core/Dxe/Misc/MemoryProtection.c

Today, SetUefiImageMemoryAttributes calls directly to the CPU Arch protocol to set EFI_MEMORY_XP or EFI_MEMORY_RO on image memory. However, this bypasses the GCD and so the GCD is out of sync with the actual state of memory.
This can cause an issue in the scenario where a new attribute is being set (whether a virtual attribute or a real HW attribute), if the GCD attributes are queried for a region and the new attribute is appended to the existing GCD attributes (which are incorrect), then the incorrect attributes can get applied. This can result in setting EFI_MEMORY_XP on code sections of images and causing an execution fault.
This patch updates SetUefiImageMemoryAttributes to call into the GCD to update the attributes there and let the GCD code call into the CPU Arch protocol to update …

MdeModulePkg: DxeCore: Set Image Memory Protections Through GCD

---

ReadMe.rst

Update badges for the equivalent pipelines that are now being used.
Builds that have been dropped over time are marked **N/A** in the table.
---
- On [update_pipeline_badges branch on edk2 fork](https://github.com/makubacki/edk2/tree/update_pipeline_badges?tab=readme-ov-file#platform-ci-build-status)
N/A

ReadMe.rst: Update pipeline badges for new pipelines

---

BaseTools/Conf/tools_def.template
BaseTools/Source/C/VfrCompile/VfrSyntax.g

This change adds support for GCC-style preprocessor line directives as documented in:
https://gcc.gnu.org/onlinedocs/cpp/Preprocessor-Output.html
On Windows systems, one can use line-markers to see which .vfr file was used to generate a *.i file in the Build directory. This is useful for debugging VFR compilation failures.
With this change, the VfrCompiler will no longer generate compilation errors if the *.i file contains GCC-style line-markers. As a consequence, tools_def.template has been modified to enable pre-processor emission of line-markers by default on the GCC and Clang compilers, like Visual C++. Now users of those compilers have access to this helpful debugging feature as well.
- Examples: Does it …

BaseTools: Add support for GCC preprocessor line-markers to the VFR Compiler

---

NetworkPkg/HttpDxe/HttpDriver.h
NetworkPkg/HttpDxe/HttpDxe.inf
NetworkPkg/HttpDxe/HttpProto.c
NetworkPkg/HttpDxe/HttpProto.h
NetworkPkg/NetworkPkg.dec
NetworkPkg/NetworkPkg.uni

Current HTTP transfer size have a default value of 2M. 
This PCD change allows the platform code to change the transfer buffer size.
Based on the network bandwidth, the buffer size can be adjusted to improve performance.
Large buffer size provides better performance in high-bandwidth connections.
However, small buffer size helps to reduce packet loss in low-bandwidth scenarios.
Verified basic HTTP file download …

NetworkPkg:  Add PCD for HTTP transfer buffer size

---

MdeModulePkg/Bus/Spi/SpiBus/SpiBus.c
MdeModulePkg/Bus/Spi/SpiBus/SpiBusDxe.c

Fix incorrect guid in SpiBusDxe
Fix incorrect gEfiDevicePathProtocolGuid in the HandleProtocol.
Replace gEfiDevicePathProtocolGuid with gEfiSpiHcProtocolGuid to locate the spi protocol.
N/A
N/A

 MdeModulePkg SpiBus: Use correct GUID

---

MdeModulePkg/Bus/Spi/SpiNorFlashJedecSfdp/SpiNorFlash.c

`Instance->SfdpBasicFlash` can be used before initializing.
Example code flow:
- CreateSpiNorFlashSfdpInstance: Allocate pool for `Instance`
- InitialSpiNorFlashSfdpInstance
- ReadSfdp
- ReadSfdpHeader
- FillWriteBuffer: Dereferencing `Instance->SfdpBasicFlash`
- ReadSfdpBasicParameterTable: Allocate pool for `Instance->SfdpBasicFlash`
Test with NULL Detection feature enabled, an exception was fixed by this …

Solving potential null pointer dereference in SpiNorFlashJedecSfdp

---

MdeModulePkg/Core/Dxe/Gcd/Gcd.c

CoreDumpGcdMemorySpaceMap() gets called on every update to the GCD, but it only prints if DEBUG_GCD is set. However, the compiler is not smart enough to remove all of this logic if we are not printing anything, so we end up needlessly allocating memory for the copy of the map and spending many cycles looping through each entry, only to not print anything.
This code is compiled out on release builds, but slows down debug builds that aren't printing at DEBUG_GCD level.
This patch updates CoreDumpGcdMemorySpaceMap() to shortcircuit and immediately exit if DEBUG_GCD is not set. It also adds the same logic to CoreDumpGcdIoSpaceMap(), which is called less frequently, but has the same issue.
- Examples: Does it add a …

MdeModulePkg: Shortcircuit GCD Dumping Logic if Not Printing

---

UefiCpuPkg/PiSmmCpuDxeSmm/MpService.c

SyncContext of SMM_DISPATCHER_MP_SYNC_DATA was dynamically allocated from SMRAM. The memory was not freed before reallocation in S3 resume path. This could lead to:
1. Memory leak in SMRAM.
2. Potential S3 resume failure after repeated S3 tests due to SMRAM exhaustion.
This change releases the SyncContext memory before reallocating it.
Run S3 cycling test for over 5000 cycles.
N/A

UefiCpuPkg/PiSmmCpuDxeSmm: Fix SMRAM memory leak during S3 resume

---

MdeModulePkg/Core/Dxe/Misc/MemoryProtection.c

Commit 5ccb5fff02a66b21898bd57f48bbd7c3cd6f4e8d updated the image memory protection code to set the protection attributes through the GCD instead of directly to the page table. However, this code had an implicit assumption that each base address passed to it was the beginning of a GCD descriptor. On the virtual platforms tested, this was the case. However, on a physical platform, a scenario was encountered where the base address was not the beginning of a GCD descriptor, thus causing memory attributes to be applied incorrectly.
This assumption does not need to be made and this patch updates the code to handle the case where the base address is not the beginning of a GCD descriptor.
- Examples: Does it add a new …

MdeModulePkg: Fix Image Memory Protection Applying

---

MdeModulePkg/Core/Dxe/Misc/DebugImageInfo.c

The DebugImageInfoTable contains an array of image info structures. The current implementation removes an entry by freeing the info structure and putting NULL in that entry of the array. It then decrements the table size tracked in the table. However, the array is invalid at this point, it contains a NULL entry, which the UEFI spec does not envision and it contains a valid entry past the end of the array as tracked in the spec defined config table. If the table is consumed at this point it can lead to an invalid assessment of the image state, which defeats the purpose of the table.
When a new info structure is added, it then scans for the first NULL entry adds a pointer to the new info structure there and increments the table size to cover the entrythat was formerly past the end of the …

MdeModulePkg: DebugImageInfoTable: Fix Array Maintenance

---

BaseTools/Source/Python/Workspace/MetaFileParser.py

BaseTools currently does not expand macros for component architecture when nested !include directives are used. This breaks use cases like `[Component.$(DXE_ARCH)]`.
The fix is to add explicit macro expansion when computing the Arch value for component lines in the DscParser class.
1. Run `build_bios.py -p BoardX58Ich10` in edk2-platforms/Platform/Intel. A correct workspace to run this build can be generated …

BaseTools: Fix Macro Expansion on Machine Architecture for Components

---

UefiCpuPkg/Library/CpuExceptionHandlerLib/LoongArch/ExceptionCommon.h
UefiCpuPkg/Library/CpuExceptionHandlerLib/LoongArch/LoongArch64/ArchExceptionHandler.c
UefiCpuPkg/Library/CpuExceptionHandlerLib/LoongArch/LoongArch64/ExceptionHandlerAsm.S
UefiCpuPkg/Library/MpInitLib/LoongArch64/MpLib.c

1. Fix a bug about MP init on LoongArch
2. Enable the IPI vectors on LoongArch
Using out-of-order wake-up APs, they can start correctly.
<N/A>

LoongArch: Fixed a MP wake up bug and enabled IPI vectors.

---

MdeModulePkg/Bus/Usb/UsbMouseAbsolutePointerDxe/UsbMouseAbsolutePointer.c

https://www.usb.org/sites/default/files/hid1_11.pdf Appendix B, B.2 Protocol 2 (Mouse) details the information returned by a usb mouse HID.
bytes 3..n are specific to the device, but are used by absolute pointer devices to return a z axis.
Prior to this change, the existing code was reusing the X value for the Z axis, which was incorrect.
For usb devices which do not return enough data for a z axis, this change will be a no-op.
for reference, the dxemouse can also be viewed to show that for "z axis" is it referencing the 3rd byte of returned data. 
N/A
No integration necessary.

MdeModulePkg: Correct Usb Mouse Z for absolute pointer.

---

ArmVirtPkg/ArmVirt.dsc.inc
ArmVirtPkg/ArmVirtCloudHv.dsc
ArmVirtPkg/ArmVirtKvmTool.dsc
ArmVirtPkg/ArmVirtQemu.dsc
ArmVirtPkg/ArmVirtQemuKernel.dsc
ArmVirtPkg/ArmVirtStackCookies.dsc.inc
ArmVirtPkg/ArmVirtXen.dsc

Fix the issue caused by ordering change in dsc include files while enabling dynamic stack check.
vUEFI built from Tianocore edk2 mainline was failing to boot on hosts with TRNG enabled
as TRNG lib was getting overridden by NULL library. vUEFI boot was tested with this fix.
<N/A>

ArmVirtPkg: Fix dsc include ordering

---

.github/scripts/GitHub.py

Since case of a GitHub user name may by specified differently in the `Maintainers.txt` file versus what is actually returned by the GitHub API (actual case), convert both to lowercase for comparison.
Other GitHub user name inputs are directly from APIs and maintain consistent casing.
- Verified changes locally inspecting usernames returned from the `Maintainers.txt` file against GitHub API results.
N/A

.github: Compare collaborator GitHub ID's in single case

---

MdeModulePkg/Universal/HiiDatabaseDxe/String.c

The BlockSize calculation was missing the 0 terminator which caused the string block to shrink by 1 every time the string was processed. Therefore causing memory corruptions, because the string took more memory space as was allocated for the string block therefore corrupting the memory pool at the end (which caused an ASSERT upon trying to free it).
No more ASSERTS from the memory allocator.
N/A

MdeModulePkg/HiiDatabaseDxe: Fix BlockSize length

---

SecurityPkg/Library/Tpm2DeviceLibFfa/Tpm2InstanceLibFfa.c

Fix unmatched constructor name of Tpm2InstanceLibFfa.

SecurityPkg/Tpm2InstanceLibFfa: Fix constructor wrong name

---

Maintainers.txt

Back in the day, we added wildcard maintainer entries for */Arm/ and */AArch64/, to make sure Arm maintainers got cc:d on patches What this was really meant for was core packages - MdeModulePkg and MdePkg - which were the only ones containing Arm-specific code outside of Arm*Pkg at the time.
However, this is no longer true, so we're increasingly finding ourselves cc:d on PRs where we don't necessarily have any opinion from an arch-maintainer perspective.
So convert the block to an include-list applying to MdeModulePkg, MdePkg, and UefiCpuPkg.

Maintainers.txt: restrict Arm architectures wildcard entries

---

CryptoPkg/Library/BaseCryptLib/Pk/CryptRsaBasic.c

Memory allocated by BN_new calls isn't deallocated within RsaSetKey.
RSA signature verification still works after this change and confirmed thru debug memory allocated by BN_new are de-allocated.
N/A

CryptoPkg: Fix memory leak in RsaSetKey

---

MdeModulePkg/Bus/Pci/SdMmcPciHcDxe/SdMmcPciHci.c
MdeModulePkg/Bus/Pci/SdMmcPciHcDxe/SdMmcPciHci.h

Add missing bit defines from 2.2.26 Capabilities Register (Cat.C Offset 040h)
- Test in system that has SD Card Host Controller
N/A

MdeModulePkg-SdMmcPciHcDxe: Add missing defines in SD_MMC_HC_SLOT_CAP

---

BaseTools/Plugin/CodeQL/analyze/analyze_filter.py
BaseTools/Plugin/CodeQL/integration/stuart_codeql.py

Fixed type annotations for functions:
- `def _parse_pattern(line: str) -> Tuple[str]:` -> `def _parse_pattern(line: str) -> Tuple[bool, str, str]:`
- `def get_scopes(codeql_enabled: bool) -> Tuple[str]:` -> `def get_scopes(codeql_enabled: bool) -> Tuple[str, ...]:`
N/A
N/A

BaseTools: Fix type annotations

---

MdeModulePkg/Library/ArmFfaLib/ArmFfaPeiLib.c
MdeModulePkg/Library/ArmFfaLib/ArmFfaPeiLib.inf

commit 26fb5edff397 ("MdeModulePkg/ArmFfaLib: Add depex on gEfiPeiMemoryDiscoveredPpiGuid") restricts ArmFfaPeiLib usage only after PEI phase can be used permanent memory. However, This would be problem for PEIM which runs before gEfiPeiMemoryDiscoveredPpiGuid Ppi installed. (i.e) Tcg2Pei PEIM.
To resolve this, remove dependency on gEfiPeiMemoryDiscoveredPpiGuid and let ArmFfaPeiLib remap the Rx/Tx buffer after
gEfiPeiMemoryDiscoveredPpiGuid is installed so that ArmFfaPeiLib can be used with temporary memory.
Signed-off-by: Yeoreum Yun <yeoreum.yun@arm.com>
Fixes: 26fb5edff397 ("MdeModulePkg/ArmFfaLib: Add depex on gEfiPeiMemoryDiscoveredPpiGuid")
Run FVP-RevC with Tcg2Pei, VariableService and MmcommunicationPei.

MdeModulePkg/Library: make ArmFfaPeiLib available early PEIM stage

---

MdeModulePkg/Universal/RegularExpressionDxe/OnigurumaUefiPort.h
RedfishPkg/Include/Library/RedfishCrtLib.h
SecurityPkg/DeviceSecurity/SpdmLib/Include/hal/LibspdmStdBoolAlt.h

In C23 bool is a built-in type, so it's not necessary to typedef bool.
This fixes a build error when using GCC 15. We can't add `-std=c17` to Conf/tools_def.txt because the same flags get passed to g++ when building GoogleTest, which causes an error because it's building C++ code where `-std=c17` isn't valid.
Ran `stuart_ci_build -c .pytool/CISettings.py TOOL_CHAIN_TAG=GCC`

Fix building in C23 mode (e.g. with GCC 15.1)

---

EmbeddedPkg/Drivers/VirtualKeyboardDxe/VirtualKeyboard.h

KEYBOARD_TIMER_INTERVAL is used as TriggerTime parameter of gBS->SetTimer() function. TriggerTime parameter represents the number of 100ns units, so number 500000 indicates 0.05s.

EmbeddedPkg: Fix a data error in comment

---

MdeModulePkg/Universal/DisplayEngineDxe/InputHandler.c
ShellPkg/Library/UefiShellDebug1CommandsLib/Edit/FileBuffer.c
ShellPkg/Library/UefiShellDebug1CommandsLib/HexEdit/BufferImage.c

The latest VS2022 update replaces some code patterns with struct
assignments with `memcpy`. This change convert the code to
explicitly use `CopyMem`.
- Build before and after with 17.14.2 VS2022 toolchain
- Use this commit if you encounter `memcpy` linking issues in these files.

Prevent memcpy intrinsics in VS22 (17.14.2)

---

OvmfPkg/Library/PlatformBmPrintScLib/StatusCodeHandler.c

The UEFI spec 2.11 documents `EFI_SECURITY_VIOLATION` for both `gBS->LoadImage()` and `gBS->StartImage()` as
> [`Image` was loaded and an `ImageHandle` was created with a valid `EFI_LOADED_IMAGE_PROTOCOL`. However,] the current platform policy specifies that the image should not be started.
Additionally, the spec documents `EFI_ACCESS_DENIED` for `gBS->LoadImage()` as
> `Image` was not loaded because the platform policy prohibits the image from being loaded. `NULL` is returned in `ImageHandle`.
When image loading/starting fails under the above conditions (according to the status code being reported), print a hint about Secure Boot. This should help users diagnose and fix their Secure Boot configuration.
Updates: 77874ceebb118cd58f518cbf6bcb63f47c993ec0
Fixes: …

OvmfPkg/PlatformBmPrintScLib: hint at Secure Boot verification

---

MdeModulePkg/Library/SmmCorePerformanceLib/MmCorePerformanceLib.c
MdeModulePkg/Library/SmmCorePerformanceLib/SmmCorePerformanceLib.c
MdeModulePkg/Library/SmmCorePerformanceLib/SmmCorePerformanceLib.inf
MdeModulePkg/Library/SmmCorePerformanceLib/SmmCorePerformanceLibInternal.h
MdeModulePkg/Library/SmmCorePerformanceLib/StandaloneMmCorePerformanceLib.c

The code used a `MmServicesTableLib` dependency for both the Standalone MM and Traditional MM instances and shared code between those. There is not a readily available `MmServicesTable` lib instance for Traditional SMM (that can link to `PiSmmCore`). To ease integration and prevent creating an instance just for this case, this change uses `SmmServicesTableLib` in the Traditional SMM instance and `MmServicesTableLib` in the Standalone MM instance and moves code as necessary to accommodate this.
For general reference, there are two available instances of
`MmServicesTableLib`:
- MdePkg/MmServicesTableLib - only supports DXE_SMM drivers.
- MdePkg/StandaloneMmServicesTableLib - supports both MM drivers and
MM cores.
- Build and boot on a Traditional MM and Standalone MM X64 platform
N/A

MdeModulePkg: Refactor MM Services Tables linked in MM Core Perf Lib

---

MdePkg/Include/IndustryStandard/Acpi.h
MdePkg/Include/IndustryStandard/Acpi66.h
OvmfPkg/Include/IndustryStandard/IntelTdx.h
OvmfPkg/Include/TdxCommondefs.inc
OvmfPkg/Include/WorkArea.h
OvmfPkg/Library/PlatformInitLib/IntelTdx.c
OvmfPkg/TdxDxe/TdxAcpiTable.c
OvmfPkg/TdxDxe/TdxAcpiTable.h
OvmfPkg/TdxDxe/TdxDxe.inf
OvmfPkg/TdxDxe/X64/ApRunLoop.nasm

As currently defined, after using the Multiprocessor Wakeup Mailbox
to make a given AP jump to the wakeup vector, it cannot be used any
more with that AP, which is problematic in some use cases, like kexec.
For this reason, the definition of Multiprocessor Wakeup Structure
is changed in ACPI 6.6. It allow the Multiprocessor Wakeup Mailbox
to be reset in order to be used once again with a given AP.
Since the AP CPU states is different between TDVF and OS and
TDVF doesn't support CPU hardware restart, it can't direct reset
the AP and enable the mailbox again. TDVF needs to use CPU
instructions to change the CPU state to enable mailbox again.
It requires TDVF to changes the control register and paging mode
for a given AP, and make the AP be able wake up again.
Patch1: Add the new file for …

Implement ACPI 6.6 Multiprocessor Wakeup Mailbox for TDX

---

NetworkPkg/WifiConnectionManagerDxe/WifiConnectionMgrHiiConfigAccess.c

Replace timer eventclose with scan timerset in WifiConnectionManagerDxe. This change ensures that the driver sets and manages scan timers correctly without requiring a reload when the user enables WiFi and initiates a scan for available networks.
By using scan timerset directly, the driver maintains consistent behavior across WiFi sessions and avoids redundant event handling.
No
No
No
Testing with commit 42f17cd for use of timer set vs. the event. All tests passed.
Flash new image with restart.

WifiConnectionManagerDxe: clear timers not events

---

BaseTools/Conf/build_rule.template

`$(DEBUG_DIR)/<M>.efi` is generated by the recipe of `$(OUTPUT_DIR)/<M>.efi`: the .efi file is generated and then copied into `$(DEBUG_DIR)`. At the moment the generate GNUmakefile does not declare the dependency between these two files, which can be a problem because `$(FFS_OUTPUT_DIR)/<M>.offset` depends on `$(DEBUG_DIR)/<M>.efi`.
Normally `$(DEBUG_DIR)/<M>.efi` is generated first and there is no problem, but when an external tool builds edk2 from a Makefile, like OP-TEE build does for instance, the parallel '-j' flag passed to Make is inherited by the edk2 GNUmakefile from the environment. As a result Make might try to build the `$(FFS_OUTPUT_DIR)/<M>.offset` target in parallel and fail to find the .efi file:
make[1]: *** No rule to make target …

BaseTools: Declare $(DEBUG_DIR)/<module>.efi output

---

MdeModulePkg/Bus/Ufs/UfsPassThruDxe/UfsPassThruHci.c

UfsHc->FreeBuffer accepts page numbers rather than bytes as its size argument. Fix two positions where wrong size were passed.
Only building test was done for UfsPassThruDxe.
N/A

MdeModulePkg/UfsPassThruDxe: Correct size in UfsHc->FreeBuffer call

---

MdePkg/Include/IndustryStandard/Acpi51.h

This is a struct needed for virtualizing Windows.
https://uefi.org/acpi entry for WAET links to
https://learn.microsoft.com/en-us/previous-versions/gg487524(v=msdn.10)
which describes the 32-bit flags field with bits 0 and 1 defined.
Definition only. Part of upstreaming effort for Google fork of EDK2.

MdePkg: Add ACPI 5.1 table definition for WAET

---

UnitTestFrameworkPkg/UnitTestFrameworkPkgHost.dsc.inc

Disable write strings warning for host-based unit test builds when building modules of type HOST_APPLICATION.
Modules of type HOST_APPLICATION may compile and link code under test into the host-based unit test. When building GoogleTest based unit tests, the G++ compiler is used. The G++ compiler is stricter than GCC for passing a const string into a function parameter that is not const. This is not a warning for GCC build of firmware code. But GoogleTest builds that use g++ detect as a warning and that breaks the build.
The firmware code under test can not be changed, so the warning -Wno-write-strings is added to CC_FLAGS to ignore this warning.
Linux/GCC host-based unit test build using GoogleTest halted with warning -Wno-write-strings when passing
a const string to a firmware API that …

UnitTestFrameworkPkg: Add -Wno-write-strings to host unit tests

---

Maintainers.txt
MdeModulePkg/Library/ArmFfaLib/ArmFfaCommon.h
MdeModulePkg/Library/ArmFfaLib/ArmFfaRxTxMapStmm.c
MdeModulePkg/Library/ArmFfaLib/ArmFfaStandaloneMmCoreLib.inf
MdeModulePkg/Library/ArmFfaLib/ArmFfaStandaloneMmLib.c
MdeModulePkg/Library/ArmFfaLib/ArmFfaStandaloneMmLib.inf
MdePkg/Include/IndustryStandard/ArmFfaMemMgmt.h
MdePkg/Include/Library/ArmFfaLib.h
MdePkg/Include/Library/ArmFfaMemMgmtLib.h
MdePkg/Library/ArmFfaMemMgmtLib/ArmFfaMemMgmtLib.c
MdePkg/Library/ArmFfaMemMgmtLib/ArmFfaMemMgmtLib.inf
MdePkg/MdePkg.dec
MdePkg/MdePkg.dsc

This change adds the FF-A memory management protocol implementation according to https://developer.arm.com/documentation/den0140/latest/
This change was tested on QEMU SBSA and proprietary hardware with Hafnium as the SPMC.
Add `ArmFfaMemMgmtLib|MdePkg/Library/ArmFfaMemMgmtLib/ArmFfaMemMgmtLib.inf` to platform DSC.

Adding FF-A memory management library

---

EmbeddedPkg/Library/TimeBaseLib/TimeBaseLib.c

EmbeddedPkg/TimeBaseLib: aligning year with UEFI specification
According to the UEFI Specification version 2.11, the valid range for the Year field in the EFI_TIME structure is from 1900 to 9999. Currently IsTimeValid() checks a restricted range 2000 - 2099. 
Update range in TimeBaseLib.c to match UEFI specification.
Run EDK2-test(SCT) suite to verify code change.
https://github.com/tianocore/edk2-test/pull/267

EmbeddedPkg/TimeBaseLib: aligning year with UEFI specification

---

ArmPkg/Drivers/MmCommunicationDxe/MmCommunication.c
ArmPkg/Drivers/MmCommunicationDxe/MmCommunication.inf
ArmPkg/Drivers/MmCommunicationPei/MmCommunicationPei.c
ArmPkg/Drivers/MmCommunicationPei/MmCommunicationPei.inf
ArmPkg/Drivers/StandaloneMmCpu/EventHandle.c
ArmPkg/Drivers/StandaloneMmCpu/StandaloneMmCpu.inf
ArmPkg/Library/ArmStandaloneMmCoreEntryPoint/ArmStandaloneMmCoreEntryPoint.c
ArmPkg/Library/ArmStandaloneMmCoreEntryPoint/ArmStandaloneMmCoreEntryPoint.inf
MdeModulePkg/Core/PiSmmCore/PiSmmIpl.c
MdeModulePkg/Include/Guid/SmmVariableCommon.h
MdeModulePkg/Universal/Variable/MmVariablePei/MmVariablePei.c
MdeModulePkg/Universal/Variable/MmVariablePei/MmVariablePei.h
MdeModulePkg/Universal/Variable/MmVariablePei/MmVariablePei.inf
MdeModulePkg/Universal/Variable/RuntimeDxe/VariableSmmRuntimeDxe.c
MdeModulePkg/Universal/Variable/RuntimeDxe/VariableSmmRuntimeDxe.inf

This change adds support of MM communicate v3 for ARM based drivers and moved variable driver to use MM communicate v3.
This change was tested on QEMU Q35 and SBSA machines and booted to UEFI shell.
N/A

Extend MM communication v3 to ARM and UEFI variable modules

---

MdeModulePkg/Universal/FaultTolerantWriteDxe/FtwMisc.c
MdeModulePkg/Universal/FaultTolerantWriteDxe/UpdateWorkingBlock.c

Fixes https://github.com/tianocore/edk2/issues/11118
Add validation for FtwWorkSpaceHeader within the
WorkSpaceRefresh() function to address an issue where the variable store cannot recover from the FTW spare block if the variable store is erased or corrupted during an FTW write or reclaim operation.
Flash UEFI with the corrupted variable store dumped from the failed device. The device should boot successfully …

MdeModulePkg/FaultTolerantWriteDxe: Add validation for FtwWorkSpaceHeader

---

MdeModulePkg/Universal/SmmCommunicationBufferDxe/SmmCommunicationBufferDxe.c

Running Codeql on MdeModulePkg/Universal/SmmCommunicationBuffer drivers results in codeql errors stemming from missing null tests.
Local CI and booting virtual platform with no ill effects.
No integration necessary.

MdeModulePkg: SmmCommunicationBuffer cumulative codeql issues.

---

BaseTools/Source/Python/build/BuildReport.py

Build report would only detect a nested FV if the nested FV was in a subsection of an FFS.
Modify the build report to better handle some of the variations of nested FVs.
Failing Example:
[Fv.FvName1]
INF <path to some driver>.inf
[Fv.FvName0]
FILE FV_IMAGE = B25ACDEF-39CE-4FA5-B50A-33E24DB1BDDF {
SECTION FV_IMAGE = FvName1
}
Working Example:
[Fv.FvName1]
INF <path to some driver>.inf
[Fv.FvName0]
FILE FV_IMAGE = DA04F6BF-A0FD-47EC-928B-5101A6C95026 {
SECTION GUIDED EE4E5898-3914-4259-9D6E-DC7BD79403CF
PROCESSING_REQUIRED = TRUE {
SECTION FV_IMAGE = FvName1
}
}
Tested in a platform build using the failing example. 
After modifications to build report, nested FVs were discovered.
N/A

BaseTools: Improve report generation for Nested Fvs.

---

OvmfPkg/PlatformCI/PlatformBuildLib.py

Allow PR eval to operate with the same input variable values as the build command would.
Because `BLD_*_SMM_REQUIRE` and `BLD_*_STANDALONE_MM_ENABLE` were not being passed to PR Eval, https://github.com/tianocore/edk2/commit/bbee92c9af59e877f9a5028140e600571faea181 was merged and broke the mainline because the MM build was not run during the [PR gate](https://dev.azure.com/tianocore/edk2-ci/_build/results?buildId=189138&view=logs&jobId=7a85138a-5e2d-569e-7f8d-012982ba61ab).
Local PR eval run before and after the change. After, PR eval detects the package needs to be built:
N/A

OvmfPkg: Pass command-line args to PR Eval

---

OvmfPkg/PlatformDxe/Platform.c
OvmfPkg/PlatformDxe/Platform.inf

If a memory debug log buffer is present, register the buffer location as
config table so the OS can find and show it.

OvmfPkg/PlatformDxe: register log buffer as efi config table

---

MdeModulePkg/MdeModulePkg.dec
UefiCpuPkg/Library/MpInitLib/DxeMpLib.c
UefiCpuPkg/Library/MpInitLib/MpLib.c
UefiCpuPkg/Library/MpInitLib/MpLib.h
UefiCpuPkg/Library/MpInitLib/PeiMpLib.c

In the MpInitLib, pages are allocated for
the APs, and data is copied into them. Depending
on the allocation type, Nx needs to be removed
from the pages to allow the processors to execute.
Additionally, ReadOnly needs to be applied to the
pages after they have been filled with the
instructions that the APs need to execute.
Found by running PagingAudit test application on system and found a single section as RWX.
Booted virtual platform to windows with no page faults.
Passed local CI.
Ran a PagingAudit report for system and after changes, no memory was marked RWX.
no integration necessary.

UefiCpuPkg: Apply ReadOnly on Ap loop buffers.

---

MdePkg/Include/Library/DebugLib.h
MdePkg/MdePkg.dec
SecurityPkg/Library/DxeTpm2MeasureBootLib/DxeTpm2MeasureBootLib.c
SecurityPkg/Library/Tpm2CommandLib/Tpm2Capability.c
SecurityPkg/Library/Tpm2CommandLib/Tpm2Integrity.c
SecurityPkg/Library/Tpm2DeviceLibDTpm/Tpm2DeviceLibDTpm.inf
SecurityPkg/Library/Tpm2DeviceLibDTpm/Tpm2DeviceLibDTpmDump.c
SecurityPkg/Library/Tpm2DeviceLibDTpm/Tpm2DeviceLibDTpmStandaloneMm.inf
SecurityPkg/Library/Tpm2DeviceLibDTpm/Tpm2DeviceLibDTpmSvsm.inf
SecurityPkg/Library/Tpm2DeviceLibDTpm/Tpm2InstanceLibDTpm.inf
SecurityPkg/Library/Tpm2DeviceLibDTpm/Tpm2InstanceLibDTpmSvsm.inf
SecurityPkg/Library/Tpm2DeviceLibDTpm/Tpm2Ptp.c
SecurityPkg/Library/Tpm2DeviceLibDTpm/Tpm2Ptp.h
SecurityPkg/Library/Tpm2DeviceLibDTpm/Tpm2Tis.c
SecurityPkg/Tcg/Tcg2Dxe/Tcg2Dxe.c

This PR consists of four commits:
MdePkg: Add DEBUG_TPM Bit in PcdDebugPrintErrorLevel
--
Tcg2Dxe and its libraries are currently the noisiest modules in edk2. For a sample platform printing at INFO level, Tcg2Dxe printed 4,000 lines out of 5,700 total lines printed.
This commit defines a DEBUG_TPM bit to control the debug output of Tcg2Dxe and related TCG/TPM components. Most of the output is not useful except for deep debugging of TPM transactions, so it is appropriate to only print when the DEBUG_TPM bit is present.
SecurityPkg: Remove/Downgrade Noisy TCG Prints
--
The TCG code is very noisy when a TPM is connected. This commit downgrades some prints to verbose and removes some others that do not have value (such as function enter and exit prints).
SecurityPkg: Move Noisy Logs to …

MdePkg/SecurityPkg: Add DEBUG_TPM Bit

---

Maintainers.txt

Stanislaw Grams replaces Min Xu as the reviewer for patches to OvmfPkg/Confidential Computing

Maintainers.txt: Update reviewer for OvmfPkg/Confidential Computing

---

MdeModulePkg/Universal/FvSimpleFileSystemDxe/FvSimpleFileSystem.c
MdeModulePkg/Universal/FvSimpleFileSystemDxe/FvSimpleFileSystemEntryPoint.c

Running Codeql on MdeModulePkg/Universal/FvSimpleFileSystemDxe drivers results in codeql errors stemming from missing null tests.
Local CI, booting Virtual platform with no ill effects.
No integration necessary.

MdeModulePkg: FvSimpleFileSystemDxe cumulative codeql issues.

---

OvmfPkg/Tcg/TdTcg2Dxe/TdTcg2Dxe.c
SecurityPkg/Tcg/Tcg2Dxe/Tcg2Dxe.c

The Event3 memory comparison is technically correct since the definitions of the struct types are the same. The extended bodies of the events are different. The Event2 size guard for the Event3 comparison should be split to use the Event3 in its sizeof for better clarity.
The large single condition makes the function difficult to understand, so the combined logic is split into different conditional statements.
There is no dedicated library for event Tcg event predicates to deduplicate this logic into for reuse in SecurityPkg and OvmfPkg, but I'm open to suggestion.
Internal TPM attestation tests.
N/A

OvmfPkg: Clarify Is800155Event

---

MdePkg/Include/IndustryStandard/Acpi66.h

New structures and tables are defined for RISC-V in ACPI 6.6 release. Add their definitions in the header file.
This is tested with DynamicTablesPkg changes which will be a separate PR after the header file changes get merged.

MdePkg: Add RISC-V specific structure definitions in Acpi66.h

---

MdeModulePkg/MdeModulePkg.dec

Move PcdSerialRegisterBase from [PcdsFixedAtBuild, PcdsPatchableInModule] section to [PcdsFixedAtBuild, PcdsPatchableInModule, PcdsDynamic, PcdsDynamicEx] section to enable dynamic configuration.
Tested with internal platform and it is working
N/A

MdeModulePkg: Change PCD type to support dynamic

---

UefiCpuPkg/PiSmmCpuDxeSmm/X64/SmiEntry.nasm

(CVE-2025-3770)
Do not assume that IDT.limit is loaded with a zero value upon SMM entry. Delay enabling Machine Check Exceptions in SMM until after the SMM IDT has been reloaded.
No harm.
N/A

UefiCpuPkg/PiSmmCpuDxeSmm: Safe handling of IDT register on SMM entry

---

MdeModulePkg/Library/UefiBootManagerLib/BmBoot.c

The ramdisk is modelled as an NVDIMM which have a naturally higher alignment than 4K. Operating systems may wish to map NVDIMMs using large pages, so force the allocation alignment to 2MB.
Testing using HTTP ramdisk boot, targeting a windows image.
No integration necessary.

MdeModulePkg: UefiBootManagerLib Change default alignment for ramdisk.

---

SecurityPkg/FvReportPei/FvReportPei.c
SecurityPkg/HddPassword/HddPasswordDxe.c
SecurityPkg/Library/AuthVariableLib/AuthService.c
SecurityPkg/Library/DxeImageVerificationLib/DxeImageVerificationLib.c
SecurityPkg/Library/DxeTcg2PhysicalPresenceLib/DxeTcg2PhysicalPresenceLib.c
SecurityPkg/Library/DxeTcgPhysicalPresenceLib/DxeTcgPhysicalPresenceLib.c
SecurityPkg/Library/DxeTpm2MeasureBootLib/DxeTpm2MeasureBootLib.c
SecurityPkg/Library/HashInstanceLibSha1/HashInstanceLibSha1.c
SecurityPkg/Library/HashInstanceLibSha256/HashInstanceLibSha256.c
SecurityPkg/Library/HashLibBaseCryptoRouter/HashLibBaseCryptoRouterDxe.c
SecurityPkg/Library/HashLibBaseCryptoRouter/HashLibBaseCryptoRouterPei.c
SecurityPkg/Library/SecureBootVariableProvisionLib/SecureBootVariableProvisionLib.c
SecurityPkg/Library/TcgEventLogRecordLib/TcgEventLogRecordLib.c
SecurityPkg/Library/Tpm12DeviceLibDTpm/Tpm12Tis.c
SecurityPkg/RandomNumberGenerator/RngDxe/Rand/AesCore.c
SecurityPkg/Tcg/Opal/OpalPassword/OpalDriver.c
SecurityPkg/Tcg/Opal/OpalPassword/OpalHii.c
SecurityPkg/Tcg/Tcg2Config/Tcg2ConfigDriver.c
SecurityPkg/Tcg/Tcg2Dxe/Tcg2Dxe.c
SecurityPkg/Tcg/TcgConfigDxe/TcgConfigImpl.c
SecurityPkg/Tcg/TcgDxe/TcgDxe.c
SecurityPkg/VariableAuthenticated/SecureBootConfigDxe/SecureBootConfigFileExplorer.c
SecurityPkg/VariableAuthenticated/SecureBootConfigDxe/SecureBootConfigImpl.c

This reverts commit ba6a8eb045aededbc1472cce7314ab1911f0ea1c.
PR https://github.com/tianocore/edk2/pull/11307 introduced a logic change that caused regressions in FV verification on some platforms. This PR is being reverted to restore the prior logic.
The Code QL fixes in https://github.com/tianocore/edk2/pull/11307 can be resubmitted without the logic change along with one commit for each type of Code QL issue being addressed.
N/A

Revert "SecurityPkg: CodeQL Fixes."

---

MdeModulePkg/Library/CustomizedDisplayLib/CustomizedDisplayLibInternal.c
MdeModulePkg/Universal/Console/GraphicsConsoleDxe/GraphicsConsole.c
MdeModulePkg/Universal/Console/TerminalDxe/Terminal.h
MdeModulePkg/Universal/Console/TerminalDxe/TerminalConOut.c

Issue link: https://github.com/tianocore/edk2/issues/11299
According to UEFI Spec, only Bit0...6 is valid in mode attribute, other bits are undefined and must be 0. So attribute with EFI_WIDE_ATTRIBUTE is unacceptable as EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL.SetAttribute() input parameter. In current PrintInternal function, wide character removed WIDE_CHAR, and is used as EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL.OutputString() input parameter. So, wide character is mistakenly be treated as narrow character.
Because EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL.OutputString() can handle unicode string with NARROW_CHAR and WIDE_CHAR, we can directly invoke OutputString() with whole unicode string instead of separated wide/narrow string. And then, the logic of computing unicode string width is also simplified.
By the …

MdeModulePkg: Fix wide characters can not display issue.

---

.pytool/Plugin/UncrustifyCheck/uncrustify_ext_dep.yaml

Tianocore uses a customized version of Uncrustify that previously resided in https://dev.azure.com/projectmu/_git/Uncrustify.
An official fork in the Tianocore organization has been created here https://github.com/tianocore/uncrustify.
The Tianocore fork publishes its releases to a GitHub release in the repo. This is the first release from that repo:
https://github.com/tianocore/uncrustify/releases/tag/73.0.10
An advantage of this process is that the binaries for the release are simply attached on the release page in a zip file.
For example, this is the zip file for that release: https://github.com/tianocore/uncrustify/releases/download/73.0.10/uncrustify-release.zip
This eases consumption of the release, especially on non-Windows hosts versus the previous distribution method with NuGet. …

.pytool: Use Tianocore Uncrustify release

---

pip-requirements.txt

pip-requirements: Add pylibfdt and PE tool and swig
1. Tool supportUPL requires libfdt support
2. Also added swig which is required by UefiPayloadPkg.
N /A
N/A

pip-requirements: Add pylibfdt and swig

---

MdePkg/Library/BaseFdtLib/LibFdtSupport.h

Removed legacy macros and string helper APIs that are no longer used
in the BaseFdtLib implementation. Specifically:
- Dropped strcmp macro that incorrectly expected 3 arguments but
ignored the third parameter.
- Cleaned up other unused macros and redundant string APIs.
These changes align with the current upstream libfdt module and
reduce dead code.
Hii @leiflindholm , @vishalo 
could you please review the PR. …

MdePkg/BaseFdtLib: Cleanup unused Macros and unused string apis

---

OvmfPkg/RiscVVirt/Feature/SecureBoot/SecureBootDefaultKeysInit/SecureBootDefaultKeysInit.c
OvmfPkg/RiscVVirt/Feature/SecureBoot/SecureBootDefaultKeysInit/SecureBootDefaultKeysInit.inf
OvmfPkg/RiscVVirt/PlatformPei/PlatformPeim.c
OvmfPkg/RiscVVirt/PlatformPei/PlatformPeim.inf
OvmfPkg/RiscVVirt/RiscVVirtQemu.dsc
OvmfPkg/RiscVVirt/RiscVVirtQemu.fdf
OvmfPkg/Tcg/Tcg2Config/Tcg2ConfigPei.inf
UefiCpuPkg/Library/BaseRiscV64CpuTimerLib/CpuTimerLib.c

This patchset adds Secure Boot and TPM support for the RISC-V architecture and the RiscVVirt platform.
- Started a TPM emulator using swtpm:
`swtpm socket --tpmstate dir=/tmp/mytpm1 --ctrl type=unixio,path=/tmp/mytpm1/swtpm-sock --tpm2 --log level=20 --daemon`
- Launched QEMU with TPM support enabled:
`-chardev socket,id=chrtpm,path=/tmp/mytpm1/swtpm-sock -tpmdev emulator,id=tpm0,chardev=chrtpm -device tpm-tis-device,tpmdev=tpm0`
N/A

OvmfPkg: RiscVVirt: Add Secure Boot and TPM support

---

MdePkg/Include/IndustryStandard/SmBios.h
ShellPkg/Library/UefiShellDebug1CommandsLib/SmbiosView/QueryTable.c

added the MRDIMM (0x08) entry to the MemoryDeviceMemoryTechnologyTable in QueryTable.c.
This enables proper display and decoding of MRDIMM memory technology in SMBIOS Type 17 structures.
fix bug: https://github.com/tianocore/edk2/issues/11449
How This Was Tested
local test pass

Add MRDIMM (0x08) entry to MemoryDeviceMemoryTechnologyTable

---

UefiCpuPkg/Library/MpInitLib/DxeMpInitLib.inf
UefiCpuPkg/Library/MpInitLib/MpLib.c
UefiCpuPkg/Library/MpInitLib/PeiMpInitLib.inf

If AP loop mode is not Halt loop, it is found that the AP in ApInitDone state exits the loop mode immediately when WAKEUP_AP_SIGNAL is signaled at the first step of AP wake up. When WakeUpByInitSipiSipi is enabled, it is possible that the AP could clear StartupApSignal buffer before the BSP sends Init-Startup IPI to the AP. In the case, it causes that the BSP frees AP reset vector buffer even though AP wake up is in process. This results in an exception error. To ensure AP wake up, it is expected that the AP is in the known non-executable state before the AP wakeup signal.
The issue happens when the AP is disabled through the MP service of gEfiMpServiceProtocolGuid->EnableDisableAP(FALSE) and enabled later through gEfiMpServiceProtocolGuid->EnableDisableAP(TRUE). In the flow, the AP that …

UefiCpuPkg/MpInitLib: Ensure AP wake up on WakeUpByInitSipiSipi mode

---

MdeModulePkg/Core/Dxe/Event/Event.c

There are a lot of notify callback events for Event Groups. Usually they are not reported unless there is a debug code in the callback itself. The debug message helps to check which/when the callback is registered and executed in POST. Also helps to notice the callback sequence. It depends on DEBUG_EVENT flag enabled by PcdFixedDebugPrintErrorLevel PCD token.
Enablement : 
Set DEBUG_EVENT flag to PcdFixedDebugPrintErrorLevel PCD token.
```c
``` 
Major Event Groups : 
```c
gEfiEndOfDxeEventGroupGuid          = {0X02CE967A, 0XDD7E, 0X4FFC, {0X9E, 0XE7, 0X81, 0X0C, 0XF0, 0X47, 0X08, 0X80}}
gEfiEventReadyToBootGuid            = {0X7CE88FB3, 0X4BD7, 0X4679, {0X87, 0XA8, 0XA8, 0XD8, 0XDE, 0XE5, 0X0D, 0X2B}}
gEfiEventAfterReadyToBootGuid       = {0X3A2A00AD, 0X98B9, 0X4CDF, {0XA4, 0X78, 0X70, …
```

MdeModulePkg/DxeMain: Add debug code for Event Group notify functions

---

MdeModulePkg/Universal/Disk/UnicodeCollation/EnglishDxe/UnicodeCollationEng.c

Build failed with the below error:
error: variable 'Status' is used uninitialized when 
PcdUnicodeCollation2Support is FALSE.
Fixing this issue by initializing Status unconditionally.
This is a regression issue caused by below Edk2 commit a46697f73532dbaa84babacc887cd5ccd8c4fdc2
After initialization of Status build passed.
NA

MdeModulePkg/UnicodeCollation: Fix uninitialized variable usage

---

ArmPkg/Drivers/ArmPsciMpServicesDxe/ArmPsciMpServicesDxe.c

This change fixes 2 logical issues in the `ArmPsciMpServicesDxe` module:
1. An issue with `EnableDisableAP` function where the function will be rejected if the previous AP operation ended up with timer expiration.
2. An issue with MPIDR usage, where the non-affinity bits are not filtered when comparing the CPU info data from the hob and register readings.
This change was tested on QEMU SBSA virtual platform as …

Fix MP services over PSCI module

---

FmpDevicePkg/FmpDxe/FmpDxe.c

The current implementation for XDR certificate handling assumes the PublicKeyDataXdr buffer is 4-byte aligned. This is not always the case. For example, if PublicKeyDataXdr=0x02, and the length is 0x05, the correct offset should be 0x2 + align_up(0x5, 4) -> 0x2 + 0x8 = 0xA. The current logic produces align_up(0x2 + 0x5, 4) -> align_up(0x7, 4) = 0x8.
RFC XDR reference on 4-byte alignment. https://www.rfc-editor.org/rfc/rfc4506#page-16
```
(4) Why is the XDR unit four bytes wide?
There is a tradeoff in choosing the XDR unit size.  Choosing a small
size, such as two, makes the encoded data small, but causes alignment
problems for machines that aren't aligned on these boundaries.  A
large size, such as eight, means the data will be aligned on
virtually every machine, but causes the encoded …
```

FmpDevicePkg/FmpDxe: Improve handling of XDR certs

---

SecurityPkg/Library/Tpm2DeviceLibDTpm/Tpm2DeviceLibDTpmDump.c
SecurityPkg/Library/Tpm2DeviceLibDTpm/Tpm2Ptp.c
SecurityPkg/Library/Tpm2DeviceLibDTpm/Tpm2Ptp.h
SecurityPkg/Library/Tpm2DeviceLibDTpm/Tpm2Tis.c

As a BASE type library, currently the TCG PEI driver, Tcg2Pei.inf links the library. On edk2-stable202508 version, it is found that the driver includes and updates the global variable of mLastCommandSent in debug build. Also found that the previous commit (460f270) for the library adds and uses the global variable. Updating the global variable in PEI drivers could affect the following issues. To address these issues, remove the global variable usage.
PEI ROM Boot : Global variable is not updated
PEI RAM Boot : PEI FV integration/security check is failed …

SecurityPkg/Tpm2DeviceLibDTpm: Remove global variable for command code

---

ArmPkg/Drivers/CpuDxe/AArch64/Mmu.c
ArmPkg/Library/ArmLib/AArch64/AArch64Lib.c
MdePkg/Include/AArch64/AArch64.h
MdePkg/Include/AArch64/AArch64Mmu.h
MdePkg/Include/Library/ArmLib.h
UefiCpuPkg/Library/ArmMmuLib/AArch64/ArmMmuLibCore.c

Add support for LPA2 (52-bit physical addressing).
Booted to UEFI shell on FVP Versatile Express model with and without LPA2 enabled.
N/A

ArmPkg/ArmMmuLib: Add support for LPA2

---

ArmPkg/Filesystem/SemihostFs/AArch64/SemihostFs.c

Since FileFcb's list entry doesn't initialised at allocation,
SemihostFs reports below crash while freeing FileFcb when
get failed to size of file in FileOpen():
ASSERT [SemihostFs] LinkedList.c(75): List->ForwardLink != ((void *) 0)
To address this, initailise list entry properly at FCB allocation
and move RemoveListEntry() to FileClose()
since the FCB entry will be on the list when VolumeOpen() or
FileOpen() is successed.
Signed-off: Yeoreum Yun <yeoreum.yun@arm.com>

ArmPkg/SemihostFs: fix crash when failed to open file

---

ShellPkg/Library/UefiShellDebug1CommandsLib/Pci.c

1. Add BoundaryCheck function for PCIe extended capability structures
to prevent reads beyond the 4KB PCIe configuration space limit.
The function calculates whether the requested size would cause an
access beyond the boundary and truncates the size if necessary,
while warning the user about the truncation.
2. Enhance DVSEC capability structure size calculation method. Size is
now obtained from the DesignatedVendorSpecificHeader1.Bits.DvsecLength
register.
3. fix some typo in the source code
Issue: https://github.com/tianocore/edk2/issues/11554 …

ShellPkg: Add PCIe boundary check function for config space access
